const NEWS = [
  { id:1,  title:'Claude Opus 4.7 Tops SWE-bench with 87.6% Score', summary:'Anthropic\'s Claude Opus 4.7 has set a new record on SWE-bench Verified, scoring 87.6% — the highest ever for a publicly available model. Priced at $5/$25 per million tokens, it marks a step-change in agentic software engineering capabilities.', date:'Apr 17, 2026', source:'Anthropic Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?id=1' },
  { id:2,  title:'GPT-5.4 Ships in Three Variants with 1M Token Context', summary:'OpenAI released GPT-5.4 in Standard, Thinking and Pro variants. All three share a 1.05 million token context window — the largest OpenAI has ever released commercially. The model dynamically retrieves tool specs rather than loading every definition into the prompt.', date:'Apr 16, 2026', source:'OpenAI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?id=2' },
  { id:3,  title:'Apple Rebuilds Siri on Google Gemini via Private Cloud', summary:'Apple announced a completely reimagined Siri powered by Google\'s Gemini model running on Apple\'s Private Cloud Compute. The new Siri handles multi-step tasks on-device for the first time and answers complex questions with far greater accuracy.', date:'Apr 16, 2026', source:'9to5Mac', category:'business', catLabel:'Business', catColor:'#f5a623', url:'news-article.html?id=3' },
  { id:4,  title:'Stanford AI Index 2026: AI Adoption Faster Than PC or Internet', summary:'Stanford\'s annual AI Index reveals that as of March 2026, Anthropic leads the overall model rankings, trailed closely by xAI, Google and OpenAI. The report finds people are adopting AI faster than they adopted the personal computer or the internet.', date:'Apr 15, 2026', source:'Stanford HAI', category:'research', catLabel:'Research', catColor:'#4aaef5', url:'news-article.html?id=4' },
  { id:5,  title:'PwC: Top 20% of Companies Capture 75% of AI Economic Gains', summary:'PwC\'s 2026 AI Performance study finds a sharp divide: a small group of companies focused on growth — not just productivity — is pulling far ahead. The report warns that most businesses are still in early experimentation, missing the compounding returns.', date:'Apr 14, 2026', source:'PwC', category:'research', catLabel:'Research', catColor:'#4aaef5', url:'news-article.html?id=5' },
  { id:6,  title:'OpenAI Acquires Silicon Valley Media Show TBPN', summary:'OpenAI announced it has acquired TBPN, the Technology Business Programming Network — a daily live tech and business show that has become a cult phenomenon in Silicon Valley. It is the company\'s first acquisition of a media company.', date:'Apr 14, 2026', source:'The Verge', category:'business', catLabel:'Business', catColor:'#f5a623', url:'news-article.html?id=6' },
  { id:7,  title:'Anthropic Confirms Claude Mythos — But Won\'t Release It Publicly', summary:'Anthropic confirmed the existence of Claude Mythos, described as the most capable model they have ever built. It will not be released to the public. Access is limited to ~50 partner organizations through Project Glasswing, focused on cybersecurity and advanced reasoning.', date:'Apr 13, 2026', source:'Anthropic Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?id=7' },
  { id:8,  title:'OpenAI Surpasses $25B Annual Revenue, Eyes IPO in Late 2026', summary:'OpenAI has surpassed $25 billion in annualized revenue and is reportedly taking early steps toward a public listing, potentially as soon as late 2026. Anthropic is close behind, approaching $19 billion in annualized revenue.', date:'Apr 13, 2026', source:'Bloomberg', category:'business', catLabel:'Business', catColor:'#f5a623', url:'news-article.html?id=8' },
  { id:9,  title:'Meta Llama 4 Scout: 10M Token Context with MoE Architecture', summary:'Meta released Llama 4 Scout and Maverick — the first Llama models with Mixture-of-Experts architecture. Scout features 17B active parameters across 16 experts (109B total) and a 10-million-token context window. Available for commercial use.', date:'Apr 12, 2026', source:'Meta AI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?id=9' },
  { id:10, title:'Google Gemma 4 Released: 31B Open Model Ranks #3 Globally', summary:'Google released Gemma 4 in four variants from 2.3B to 31B parameters. The 31B Dense model ranks #3 globally on Arena AI among open models, making it the strongest open-weight model Google has shipped to date.', date:'Apr 10, 2026', source:'Google Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?id=10' },
  { id:11, title:'EU AI Act Full Enforcement: Major Providers Publish Compliance Docs', summary:'The EU AI Act entered full enforcement in March 2026, requiring all AI systems in the EU to meet transparency, safety and risk classification requirements. OpenAI, Anthropic and Google have now published their GPAI compliance documentation.', date:'Apr 9, 2026', source:'Wired', category:'regulation', catLabel:'Regulation', catColor:'#f56565', url:'news-article.html?id=11' },
  { id:12, title:'Zhipu AI Open-Sources GLM-5.1: 744B Parameter MoE Model', summary:'Chinese lab Zhipu AI released GLM-5.1 under the MIT license — a 744-billion-parameter mixture-of-experts model with 40B active parameters per forward pass and a 200K context window. The fully open release puts serious pressure on closed-source competitors.', date:'Apr 8, 2026', source:'Zhipu AI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?id=12' },
];

const NEWS_CATS = [
  { id:'all',        label: () => t('newscat.all'),        color:'' },
  { id:'models',     label: () => t('newscat.models'),     color:'#7c6af7' },
  { id:'tools',      label: () => t('newscat.tools'),      color:'#2dd4a0' },
  { id:'business',   label: () => t('newscat.business'),   color:'#f5a623' },
  { id:'research',   label: () => t('newscat.research'),   color:'#4aaef5' },
  { id:'regulation', label: () => t('newscat.regulation'), color:'#f56565' },
];
