// Auto-generated from Supabase — do not edit manually.
// Run: python3 scripts/generate-news-snapshot.py

const NEWS = [
  { id:345, slug:'us-government-ai-security-testing-nist', title:'Microsoft, Google and xAI to Give US Government Early Access to Unreleased AI Models for Security Testing', summary:'NIST\'s Center for AI Standards and Innovation announced agreements with Microsoft, Google, and xAI to evaluate unreleased AI models for national security risks before launch. The move was prompted by Anthropic\'s restricted Mythos model. Anthropic is notably absent from the agreement.', date:'May 5, 2026', source:'CNN Business', category:'industry', catLabel:'Industry', catColor:'#888', url:'news-article.html?slug=us-government-ai-security-testing-nist' },
  { id:361, slug:'openai-novo-nordisk-drug-discovery', title:'Novo Nordisk and OpenAI Partner to Accelerate Drug Discovery and Manufacturing with AI', summary:'Novo Nordisk announced a strategic partnership with OpenAI to integrate AI across drug discovery, clinical trials, manufacturing, supply chains, and commercial operations. The deal targets acceleration of new obesity and diabetes treatments.', date:'May 2, 2026', source:'Financial Times', category:'industry', catLabel:'Industry', catColor:'#888', url:'news-article.html?slug=openai-novo-nordisk-drug-discovery' },
  { id:329, slug:'anthropic-mythos-restricted-release', title:'Anthropic\'s Mythos Model: "Far Ahead" on Cybersecurity — Restricted to Approved Orgs Only', summary:'Anthropic has developed a new frontier model called Mythos which the company says is "far ahead" of all other models in cybersecurity capability. Due to the risks, Anthropic is restricting access to a select group of vetted organizations. The model prompted the White House to begin weighing a formal AI review process.', date:'Apr 30, 2026', source:'The Verge', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=anthropic-mythos-restricted-release' },
  { id:353, slug:'mcp-anthropic-97m-installs', title:'Anthropic\'s Model Context Protocol Crosses 97 Million Installs — Becomes Core AI Agent Infrastructure', summary:'Anthropic\'s Model Context Protocol (MCP) crossed 97 million installs in March 2026, transitioning from an experimental standard to foundational infrastructure for building AI agents. Every major AI provider now ships MCP-compatible tooling.', date:'Apr 30, 2026', source:'Anthropic Blog', category:'industry', catLabel:'Industry', catColor:'#888', url:'news-article.html?slug=mcp-anthropic-97m-installs' },
  { id:337, slug:'gemini-3-1-benchmark-leader', title:'Gemini 3.1 Pro Tops 13 of 16 Major AI Benchmarks — Including 80.6% SWE-bench and 94.3% GPQA Diamond', summary:'Google\'s Gemini 3.1 Pro has emerged as the overall benchmark leader across independent evaluations, topping 13 of 16 major benchmarks. Key scores: 80.6% on SWE-bench, 94.3% on GPQA Diamond (highest of any model), 2M token context window across text, image, audio and video.', date:'Apr 29, 2026', source:'Artificial Analysis', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=gemini-3-1-benchmark-leader' },
  { id:315, slug:'mistral-small-4-release', title:'Mistral Releases Small 4 — 119B Open-Source Model with Reasoning and Vision', summary:'Mistral released Small 4, a 119-billion-parameter open-source model with a 256k context window, configurable reasoning, and multimodal (vision) capabilities. It combines fast instruction-following, deep reasoning, and image understanding in a single unified model under an open license.', date:'Apr 28, 2026', source:'Mistral Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=mistral-small-4-release' },
  { id:321, slug:'microsoft-openai-partnership-restructure', title:'Microsoft and OpenAI Restructure Partnership — Exclusivity Ends, OpenAI Opens to AWS and Google Cloud', summary:'Microsoft and OpenAI rewrote their foundational 2019 deal: Microsoft ends its Azure revenue share to OpenAI, OpenAI can now sell via Amazon Web Services and Google Cloud, and the famous "AGI clause" is removed. Anthropic\'s ARR has surpassed OpenAI\'s for the first time at $30B, which may have accelerated the renegotiation.', date:'Apr 27, 2026', source:'CNBC', category:'industry', catLabel:'Industry', catColor:'#888', url:'news-article.html?slug=microsoft-openai-partnership-restructure' },
  { id:309, slug:'google-40b-anthropic-investment', title:'Google Commits Up to $40 Billion in Anthropic — Largest AI Investment in History', summary:'Google announced an investment of up to $40 billion in Anthropic, starting with $10 billion at a $350 billion valuation, with follow-on tranches tied to milestones. Google Cloud also committed 5 gigawatts of compute capacity over five years — the largest single AI investment ever recorded.', date:'Apr 24, 2026', source:'TechCrunch', category:'industry', catLabel:'Industry', catColor:'#888', url:'news-article.html?slug=google-40b-anthropic-investment' },
  { id:303, slug:'openai-gpt-55-launch', title:'OpenAI Releases GPT-5.5 — Most Capable Model Yet with Full Agentic Coding', summary:'OpenAI launched GPT-5.5, its most capable model to date, with dramatic improvements in agentic coding via Codex, deep research, and the ability to operate software end-to-end. It rolled out to Plus, Pro, Business and Enterprise users in ChatGPT and the API on April 24.', date:'Apr 23, 2026', source:'OpenAI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=openai-gpt-55-launch' },
  { id:295, slug:'anthropic-claude-design-launch', title:'Anthropic Launches Claude Design — AI That Builds Brand-Consistent Visuals', summary:'Anthropic released Claude Design, its first dedicated design product, as part of Anthropic Labs. Built on Claude Opus 4.7, it generates slide decks, mockups and marketing materials from conversation — with automatic brand system generation from existing codebases or design files. Available at no extra cost for Claude Pro, Max, Team and Enterprise subscribers.', date:'Apr 22, 2026', source:'Anthropic Blog', category:'tools', catLabel:'New Tool', catColor:'#2dd4a0', url:'news-article.html?slug=anthropic-claude-design-launch' },
  { id:253, slug:'xai-grok-4-3-beta-1-trillion-parameters', title:'xAI Releases Grok 4.3 Beta — 1 Trillion Parameters', summary:'xAI launched Grok 4.3 beta to SuperGrok Heavy subscribers — twice the size of Grok 4.20 at 1 trillion parameters. Early benchmarks show significant gains on reasoning and coding tasks. General availability is expected within weeks.', date:'Apr 19, 2026', source:'xAI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=xai-grok-4-3-beta-1-trillion-parameters' },
  { id:274, slug:'anthropic-agent-memory-long-term-memory-claude', title:'Anthropic Launches Agent Memory — Long-Term Memory for Claude', summary:'Anthropic opened a private beta for Agent Memory, a managed service that extracts key information from agent conversations and surfaces it when relevant — keeping context windows lean. Anthropic also announced a $100K developer hackathon on Claude Opus 4.7.', date:'Apr 18, 2026', source:'Anthropic Blog', category:'tools', catLabel:'New Tool', catColor:'#2dd4a0', url:'news-article.html?slug=anthropic-agent-memory-long-term-memory-claude' },
  { id:1, slug:'claude-opus-47-swe-bench', title:'Claude Opus 4.7 Tops SWE-bench with 87.6% Score', summary:'Anthropic\'s Claude Opus 4.7 has set a new record on SWE-bench Verified, scoring 87.6% — the highest ever for a publicly available model. Priced at $5/$25 per million tokens, it marks a step-change in agentic software engineering capabilities.', date:'Apr 17, 2026', source:'Anthropic Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=claude-opus-47-swe-bench' },
  { id:2, slug:'gpt-54-three-variants-1m-context', title:'GPT-5.4 Ships in Three Variants with 1M Token Context', summary:'OpenAI released GPT-5.4 in Standard, Thinking and Pro variants. All three share a 1.05 million token context window — the largest OpenAI has ever released commercially. The model dynamically retrieves tool specs rather than loading every definition into the prompt.', date:'Apr 16, 2026', source:'OpenAI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=gpt-54-three-variants-1m-context' },
  { id:3, slug:'apple-rebuilds-siri-google-gemini', title:'Apple Rebuilds Siri on Google Gemini via Private Cloud', summary:'Apple announced a completely reimagined Siri powered by Google\'s Gemini model running on Apple\'s Private Cloud Compute. The new Siri handles multi-step tasks on-device for the first time and answers complex questions with far greater accuracy.', date:'Apr 16, 2026', source:'9to5Mac', category:'business', catLabel:'Business', catColor:'#f5a623', url:'news-article.html?slug=apple-rebuilds-siri-google-gemini' },
  { id:4, slug:'stanford-ai-index-2026', title:'Stanford AI Index 2026: AI Adoption Faster Than PC or Internet', summary:'Stanford\'s annual AI Index reveals that as of March 2026, Anthropic leads the overall model rankings, trailed closely by xAI, Google and OpenAI. The report finds people are adopting AI faster than they adopted the personal computer or the internet.', date:'Apr 15, 2026', source:'Stanford HAI', category:'research', catLabel:'Research', catColor:'#4aaef5', url:'news-article.html?slug=stanford-ai-index-2026' },
  { id:6, slug:'openai-acquires-tbpn', title:'OpenAI Acquires Silicon Valley Media Show TBPN', summary:'OpenAI announced it has acquired TBPN, the Technology Business Programming Network — a daily live tech and business show that has become a cult phenomenon in Silicon Valley. It is the company\'s first acquisition of a media company.', date:'Apr 14, 2026', source:'The Verge', category:'business', catLabel:'Business', catColor:'#f5a623', url:'news-article.html?slug=openai-acquires-tbpn' },
  { id:5, slug:'pwc-top-companies-ai-economic-gains', title:'PwC: Top 20% of Companies Capture 75% of AI Economic Gains', summary:'PwC\'s 2026 AI Performance study finds a sharp divide: a small group of companies focused on growth — not just productivity — is pulling far ahead. The report warns that most businesses are still in early experimentation, missing the compounding returns.', date:'Apr 14, 2026', source:'PwC', category:'research', catLabel:'Research', catColor:'#4aaef5', url:'news-article.html?slug=pwc-top-companies-ai-economic-gains' },
  { id:8, slug:'openai-25b-revenue-ipo-2026', title:'OpenAI Surpasses $25B Annual Revenue, Eyes IPO in Late 2026', summary:'OpenAI has surpassed $25 billion in annualized revenue and is reportedly taking early steps toward a public listing, potentially as soon as late 2026. Anthropic is close behind, approaching $19 billion in annualized revenue.', date:'Apr 13, 2026', source:'Bloomberg', category:'business', catLabel:'Business', catColor:'#f5a623', url:'news-article.html?slug=openai-25b-revenue-ipo-2026' },
  { id:7, slug:'anthropic-confirms-claude-mythos', title:'Anthropic Confirms Claude Mythos — But Won\'t Release It Publicly', summary:'Anthropic confirmed the existence of Claude Mythos, described as the most capable model they have ever built. It will not be released to the public. Access is limited to ~50 partner organizations through Project Glasswing, focused on cybersecurity and advanced reasoning.', date:'Apr 13, 2026', source:'Anthropic Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=anthropic-confirms-claude-mythos' },
  { id:9, slug:'meta-llama-4-scout-10m-context', title:'Meta Llama 4 Scout: 10M Token Context with MoE Architecture', summary:'Meta released Llama 4 Scout and Maverick — the first Llama models with Mixture-of-Experts architecture. Scout features 17B active parameters across 16 experts (109B total) and a 10-million-token context window. Available for commercial use.', date:'Apr 12, 2026', source:'Meta AI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=meta-llama-4-scout-10m-context' },
  { id:10, slug:'google-gemma-4-31b-open-model', title:'Google Gemma 4 Released: 31B Open Model Ranks #3 Globally', summary:'Google released Gemma 4 in four variants from 2.3B to 31B parameters. The 31B Dense model ranks #3 globally on Arena AI among open models, making it the strongest open-weight model Google has shipped to date.', date:'Apr 10, 2026', source:'Google Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=google-gemma-4-31b-open-model' },
  { id:11, slug:'eu-ai-act-full-enforcement', title:'EU AI Act Full Enforcement: Major Providers Publish Compliance Docs', summary:'The EU AI Act entered full enforcement in March 2026, requiring all AI systems in the EU to meet transparency, safety and risk classification requirements. OpenAI, Anthropic and Google have now published their GPAI compliance documentation.', date:'Apr 9, 2026', source:'Wired', category:'regulation', catLabel:'Regulation', catColor:'#f56565', url:'news-article.html?slug=eu-ai-act-full-enforcement' },
  { id:12, slug:'zhipu-glm-51-744b-open-source', title:'Zhipu AI Open-Sources GLM-5.1: 744B Parameter MoE Model', summary:'Chinese lab Zhipu AI released GLM-5.1 under the MIT license — a 744-billion-parameter mixture-of-experts model with 40B active parameters per forward pass and a 200K context window. The fully open release puts serious pressure on closed-source competitors.', date:'Apr 8, 2026', source:'Zhipu AI Blog', category:'models', catLabel:'Models', catColor:'#7c6af7', url:'news-article.html?slug=zhipu-glm-51-744b-open-source' },
];

const NEWS_CATS = [
  { id:'all',        label: () => t('newscat.all'),        color:'' },
  { id:'models',     label: () => t('newscat.models'),     color:'#7c6af7' },
  { id:'tools',      label: () => t('newscat.tools'),      color:'#2dd4a0' },
  { id:'business',   label: () => t('newscat.business'),   color:'#f5a623' },
  { id:'research',   label: () => t('newscat.research'),   color:'#4aaef5' },
  { id:'regulation', label: () => t('newscat.regulation'), color:'#f56565' },
];
