-- AItoolFit — news article bodies for July-2026 batch (6 items x 8 langs).
-- EN hand-written (verified); other langs machine-translated (haiku), HTML preserved.
-- Run AFTER 01_news_july2026.sql. Then Claude regenerates news pages.

UPDATE news SET body='<p>On July 9, 2026, OpenAI publicly released <strong>GPT-5.6</strong>, its most capable model family yet, in three tiers: <strong>Sol</strong>, the top model; <strong>Terra</strong>, a mid-range option; and <strong>Luna</strong>, a fast, low-cost tier. The company framed the lineup around efficiency as much as raw power — CEO Sam Altman said Sol is roughly 54% more token-efficient on coding tasks than the previous generation.</p>
<h2>Agents and voice, not just chat</h2>
<p>Alongside the models, OpenAI shipped <strong>ChatGPT Work</strong>, an agent built to carry out complete jobs rather than answer one question at a time, and <strong>GPT-Live</strong>, a full-duplex voice mode that can listen and speak at the same time for more natural conversations. Together they mark OpenAI''s push from a chatbot toward systems that act on a user''s behalf across enterprise work, coding and research.</p>' WHERE slug='openai-gpt-5-6' AND lang='en';
UPDATE news SET body='<p>9 июля 2026 года OpenAI публично выпустила <strong>GPT-5.6</strong>, самое мощное семейство моделей на сегодняшний день, в трех уровнях: <strong>Sol</strong>, топовая модель; <strong>Terra</strong>, среднего уровня вариант; и <strong>Luna</strong>, быстрый, низкозатратный уровень. Компания позиционировала линейку вокруг эффективности в той же мере, что и вокруг чистой мощности — генеральный директор Сэм Альтман сказал, что Sol примерно на 54% более эффективна по токенам в задачах кодирования, чем предыдущее поколение.</p>
<h2>Агенты и голос, а не только чат</h2>
<p>Наряду с моделями OpenAI выпустила <strong>ChatGPT Work</strong>, агента, созданного для выполнения полных задач, а не для ответа на один вопрос за раз, и <strong>GPT-Live</strong>, полнодуплексный голосовой режим, который может одновременно слушать и говорить для более естественных разговоров. Вместе они обозначают переход OpenAI от чат-бота к системам, которые действуют от имени пользователя в корпоративной работе, кодировании и исследованиях.</p>' WHERE slug='openai-gpt-5-6' AND lang='ru';
UPDATE news SET body='<p>9 липня 2026 року OpenAI публічно випустила <strong>GPT-5.6</strong>, своє найпотужніше сімейство моделей на сьогодні, у трьох варіантах: <strong>Sol</strong>, топова модель; <strong>Terra</strong>, середньовартісна опція; та <strong>Luna</strong>, швидкий бюджетний варіант. Компанія позиціонувала лінійку навколо ефективності так само, як і навколо чистої потужності — генеральний директор Sam Altman сказав, що Sol приблизно на 54% більш ефективна за токенами для завдань кодування, ніж попереднє покоління.</p>
<h2>Агенти та голос, а не просто чат</h2>
<p>Разом з моделями OpenAI випустила <strong>ChatGPT Work</strong>, агента, створеного для виконання повних завдань, а не для відповіді на одне питання за раз, та <strong>GPT-Live</strong>, повнодуплексний голосовий режим, який може одночасно слухати й говорити для природніших розмов. Разом вони позначають рух OpenAI від чат-бота до систем, які діють від імені користувача в корпоративній роботі, кодуванні та дослідженнях.</p>' WHERE slug='openai-gpt-5-6' AND lang='ua';
UPDATE news SET body='<p>ב-9 ביולי 2026, OpenAI שיחררה לציבור את <strong>GPT-5.6</strong>, משפחת המודלים הכי מסוגלת שלה עד כה, בשלוש רמות: <strong>Sol</strong>, המודל העליון; <strong>Terra</strong>, אפשרות בטווח הביניים; ו-<strong>Luna</strong>, רמה מהירה וזולה. החברה ניסחה את הקו סביב יעילות כמו גם כוח גולמי — מנכ״ל Sam Altman אמר ש-Sol הוא בערך 54% יעיל יותר בטוקנים על משימות קידוד מאשר הדור הקודם.</p>
<h2>סוכנים וקול, לא רק צ''אט</h2>
<p>לצד המודלים, OpenAI שיגרה את <strong>ChatGPT Work</strong>, סוכן שנבנה כדי לבצע עבודות שלמות ולא רק להשיב על שאלה אחת בכל פעם, ו-<strong>GPT-Live</strong>, מצב קול דו-כיווני מלא שיכול להאזין ולדבר בו-זמנית לשיחות טבעיות יותר. ביחד הם מסמנים את הדחיפה של OpenAI מצ''אטבוט לכיוון מערכות שפועלות בשם משתמש על פני עבודה ארגונית, קידוד וחקר.</p>' WHERE slug='openai-gpt-5-6' AND lang='he';
UPDATE news SET body='<p>Am 9. Juli 2026 veröffentlichte OpenAI öffentlich <strong>GPT-5.6</strong>, seine bislang leistungsfähigste Modellfamilie, in drei Varianten: <strong>Sol</strong>, das Top-Modell; <strong>Terra</strong>, eine Option im mittleren Bereich; und <strong>Luna</strong>, eine schnelle, kostengünstige Variante. Das Unternehmen rahmt die Produktlinie ebenso sehr um Effizienz wie um reine Leistung ein — CEO Sam Altman sagte, Sol sei etwa 54% token-effizienter bei Coding-Aufgaben als die vorherige Generation.</p>
<h2>Agents und Voice, nicht nur Chat</h2>
<p>Parallel zu den Modellen brachte OpenAI <strong>ChatGPT Work</strong> auf den Markt, einen Agent, der dazu entwickelt wurde, komplette Jobs auszuführen, anstatt nur eine Frage nach der anderen zu beantworten, und <strong>GPT-Live</strong>, einen Full-Duplex-Voice-Modus, der gleichzeitig hören und sprechen kann, um natürlichere Gespräche zu ermöglichen. Zusammen markieren sie OpenAIs Vorstoß von einem Chatbot hin zu Systemen, die im Namen eines Benutzers bei Enterprise-Arbeiten, Coding und Forschung handeln.</p>' WHERE slug='openai-gpt-5-6' AND lang='de';
UPDATE news SET body='<p>El 9 de julio de 2026, OpenAI lanzó públicamente <strong>GPT-5.6</strong>, su familia de modelos más capaz hasta ahora, en tres niveles: <strong>Sol</strong>, el modelo superior; <strong>Terra</strong>, una opción de rango medio; y <strong>Luna</strong>, un nivel rápido y de bajo costo. La empresa enmarcó la alineación en torno a la eficiencia tanto como a la potencia bruta — el CEO Sam Altman dijo que Sol es aproximadamente 54% más eficiente en tokens en tareas de codificación que la generación anterior.</p>
<h2>Agentes y voz, no solo chat</h2>
<p>Junto con los modelos, OpenAI lanzó <strong>ChatGPT Work</strong>, un agente construido para realizar trabajos completos en lugar de responder una pregunta a la vez, y <strong>GPT-Live</strong>, un modo de voz full-duplex que puede escuchar y hablar al mismo tiempo para conversaciones más naturales. Juntos marcan el avance de OpenAI de un chatbot hacia sistemas que actúan en nombre del usuario en el trabajo empresarial, la codificación y la investigación.</p>' WHERE slug='openai-gpt-5-6' AND lang='es';
UPDATE news SET body='<p>Le 9 juillet 2026, OpenAI a publié publiquement <strong>GPT-5.6</strong>, sa famille de modèles la plus capable à ce jour, en trois niveaux : <strong>Sol</strong>, le modèle haut de gamme ; <strong>Terra</strong>, une option milieu de gamme ; et <strong>Luna</strong>, un niveau rapide et économique. L''entreprise a encadré la gamme autour de l''efficacité autant que de la puissance brute — le PDG Sam Altman a déclaré que Sol est environ 54% plus efficace en termes de tokens sur les tâches de codage que la génération précédente.</p>
<h2>Agents et voix, pas seulement du chat</h2>
<p>Aux côtés des modèles, OpenAI a lancé <strong>ChatGPT Work</strong>, un agent conçu pour accomplir des tâches complètes plutôt que de répondre à une seule question à la fois, et <strong>GPT-Live</strong>, un mode voix full-duplex qui peut écouter et parler simultanément pour des conversations plus naturelles. Ensemble, ils marquent le passage d''OpenAI d''un chatbot à des systèmes qui agissent au nom d''un utilisateur dans le travail en entreprise, le codage et la recherche.</p>' WHERE slug='openai-gpt-5-6' AND lang='fr';
UPDATE news SET body='<p>Em 9 de julho de 2026, a OpenAI lançou publicamente o <strong>GPT-5.6</strong>, sua família de modelos mais capacitada até agora, em três camadas: <strong>Sol</strong>, o modelo topo de linha; <strong>Terra</strong>, uma opção intermediária; e <strong>Luna</strong>, uma camada rápida e de baixo custo. A empresa enquadrou o lineup em torno da eficiência tanto quanto do poder bruto — o CEO Sam Altman disse que Sol é aproximadamente 54% mais eficiente em tokens em tarefas de codificação do que a geração anterior.</p>
<h2>Agentes e voz, não apenas chat</h2>
<p>Junto aos modelos, a OpenAI lançou o <strong>ChatGPT Work</strong>, um agente construído para executar trabalhos completos em vez de responder uma pergunta por vez, e o <strong>GPT-Live</strong>, um modo de voz full-duplex que pode ouvir e falar ao mesmo tempo para conversas mais naturais. Juntos, eles marcam o avanço da OpenAI de um chatbot para sistemas que atuam em nome do usuário em trabalho empresarial, codificação e pesquisa.</p>' WHERE slug='openai-gpt-5-6' AND lang='pt';
UPDATE news SET body='<p>Anthropic released <strong>Claude Opus 5</strong> on July 24, 2026, describing it as a step-change over Opus 4.8 for agentic coding and computer use. Crucially, it keeps Opus pricing unchanged at <strong>$5 per million input tokens and $25 per million output</strong> — half the price of the company''s frontier Fable 5 model — making frontier-class capability far cheaper to run.</p>
<h2>Specs and availability</h2>
<p>Opus 5 ships with a <strong>1-million-token context window</strong>, up to 128K output tokens, extended thinking enabled by default, and a knowledge cutoff of May 2026 — the most current of any Claude model. It becomes the new default on Claude Max and the strongest model available on Claude Pro, offered through the Claude apps and API.</p>' WHERE slug='claude-opus-5' AND lang='en';
UPDATE news SET body='<p>Anthropic выпустила <strong>Claude Opus 5</strong> 24 июля 2026 года, описав её как качественный скачок в развитии по сравнению с Opus 4.8 для агентского кодирования и взаимодействия с компьютером. Принципиально важно, что Opus сохраняет неизменную цену в <strong>$5 за миллион входных токенов и $25 за миллион выходных</strong> — вдвое дешевле, чем передовая модель Fable 5 компании — что делает возможность класса frontier намного дешевле в эксплуатации.</p>
<h2>Характеристики и доступность</h2>
<p>Opus 5 поставляется с <strong>контекстным окном в 1 миллион токенов</strong>, выходом до 128K токенов, расширенным мышлением, включённым по умолчанию, и датой знаний май 2026 года — самой актуальной из всех моделей Claude. Она становится новой моделью по умолчанию на Claude Max и самой мощной доступной моделью на Claude Pro, предоставляемой через приложения Claude и API.</p>' WHERE slug='claude-opus-5' AND lang='ru';
UPDATE news SET body='<p>Anthropic випустила <strong>Claude Opus 5</strong> 24 липня 2026 року, описуючи її як якісний стрибок порівняно з Opus 4.8 для агентного кодування та комп''ютерного використання. Принципово важливо, що вона зберігає ціну Opus без змін на рівні <strong>$5 за мільйон вхідних токенів та $25 за мільйон вихідних</strong> — половина ціни флагманської моделі Fable 5 компанії — роблячи можливість класу frontier набагато дешевшою у використанні.</p>
<h2>Характеристики та доступність</h2>
<p>Opus 5 постачається з <strong>контекстним вікном в 1 мільйон токенів</strong>, до 128K вихідних токенів, розширеним мисленням, увімкненим за замовчуванням, та знаннями актуальними на май 2026 року — найактуальнішими з усіх моделей Claude. Вона стає новою моделлю за замовчуванням на Claude Max та найпотужнішою доступною моделлю на Claude Pro, пропонованою через додатки Claude та API.</p>' WHERE slug='claude-opus-5' AND lang='ua';
UPDATE news SET body='<p>Anthropic שחררה את <strong>Claude Opus 5</strong> ב-24 ביולי 2026, והתארה אותה כקפיצה איכותית מעל Opus 4.8 לקידוד אגנטי ושימוש במחשב. במיוחד, היא שומרת על התמחור של Opus ללא שינוי ב-<strong>$5 למיליון טוקני קלט ו-$25 למיליון פלט</strong> — חצי מהמחיר של מודל Fable 5 החדשני של החברה — מה שהופך יכולת ברמת חזית זולה הרבה יותר להפעלה.</p>
<h2>מפרט וזמינות</h2>
<p>Opus 5 מגיע עם <strong>חלון הקשר של 1-million-token</strong>, עד 128K טוקני פלט, חשיבה מורחבת מופעלת כברירת מחדל, וחתך ידע של מאי 2026 — העדכני ביותר מכל מודל Claude. זה הופך להיות ההגדרה החדשה של ברירת המחדל ב-Claude Max והמודל החזק ביותר הזמין ב-Claude Pro, המוצע דרך ה-Claude apps וה-API.</p>' WHERE slug='claude-opus-5' AND lang='he';
UPDATE news SET body='<p>Anthropic veröffentlichte <strong>Claude Opus 5</strong> am 24. Juli 2026 und beschrieb es als einen großen Sprung gegenüber Opus 4.8 für agentenbasierte Codierung und Computernutzung. Entscheidend ist, dass die Preisgestaltung von Opus unverändert bleibt bei <strong>$5 pro Million Eingabe-Token und $25 pro Million Ausgabe-Token</strong> — die Hälfte des Preises des Frontier-Modells Fable 5 des Unternehmens — was Frontier-Klasse-Fähigkeit viel günstiger im Betrieb macht.</p>
<h2>Spezifikationen und Verfügbarkeit</h2>
<p>Opus 5 wird mit einem <strong>1-Million-Token-Kontextfenster</strong>, bis zu 128K Ausgabe-Token, standardmäßig aktiviertem erweiterten Denken und einem Wissensstichtag von Mai 2026 ausgeliefert — dem aktuellsten aller Claude-Modelle. Es wird zum neuen Standard auf Claude Max und zum stärksten auf Claude Pro verfügbaren Modell, angeboten über die Claude-Apps und API.</p>' WHERE slug='claude-opus-5' AND lang='de';
UPDATE news SET body='<p>Anthropic lanzó <strong>Claude Opus 5</strong> el 24 de julio de 2026, describiéndolo como un cambio radical respecto a Opus 4.8 para codificación agéntica y uso de computadora. Crucialmente, mantiene el precio de Opus sin cambios en <strong>$5 por millón de tokens de entrada y $25 por millón de salida</strong> — la mitad del precio del modelo frontera Fable 5 de la empresa — lo que hace que la capacidad de clase frontera sea mucho más barata de ejecutar.</p>
<h2>Especificaciones y disponibilidad</h2>
<p>Opus 5 incluye una <strong>ventana de contexto de 1-million-token</strong>, hasta 128K tokens de salida, pensamiento extendido habilitado por defecto, y una fecha de corte de conocimiento de mayo de 2026 — la más actual de cualquier modelo Claude. Se convierte en el nuevo modelo predeterminado en Claude Max y el modelo más potente disponible en Claude Pro, ofrecido a través de las aplicaciones Claude y API.</p>' WHERE slug='claude-opus-5' AND lang='es';
UPDATE news SET body='<p>Anthropic a lancé <strong>Claude Opus 5</strong> le 24 juillet 2026, la décrivant comme un changement majeur par rapport à Opus 4.8 pour le codage agentique et l''utilisation informatique. De manière cruciale, elle maintient la tarification d''Opus inchangée à <strong>5 $ par million de jetons d''entrée et 25 $ par million de jetons de sortie</strong> — la moitié du prix du modèle Fable 5 de pointe de l''entreprise — rendant la capacité de classe frontière beaucoup moins chère à utiliser.</p>
<h2>Spécifications et disponibilité</h2>
<p>Opus 5 est livré avec une <strong>fenêtre de contexte d''1 million de jetons</strong>, jusqu''à 128K jetons de sortie, la pensée étendue activée par défaut, et une date limite de connaissance de mai 2026 — la plus actuelle de tous les modèles Claude. Il devient le nouveau modèle par défaut sur Claude Max et le modèle le plus puissant disponible sur Claude Pro, proposé via les applications Claude et l''API.</p>' WHERE slug='claude-opus-5' AND lang='fr';
UPDATE news SET body='<p>A Anthropic lançou o <strong>Claude Opus 5</strong> em 24 de julho de 2026, descrevendo-o como um salto qualitativo em relação ao Opus 4.8 para codificação por agentes e uso de computador. Crucialmente, ele mantém o preço do Opus inalterado em <strong>$5 por milhão de tokens de entrada e $25 por milhão de saída</strong> — metade do preço do modelo de fronteira Fable 5 da empresa — tornando a capacidade de classe fronteira muito mais barata de executar.</p>
<h2>Especificações e disponibilidade</h2>
<p>O Opus 5 vem com uma <strong>janela de contexto de 1-million-token</strong>, até 128K tokens de saída, pensamento estendido ativado por padrão, e um corte de conhecimento de maio de 2026 — o mais atual de qualquer modelo Claude. Ele se torna o novo padrão no Claude Max e o modelo mais forte disponível no Claude Pro, oferecido através dos aplicativos e API Claude.</p>' WHERE slug='claude-opus-5' AND lang='pt';
UPDATE news SET body='<p>On July 22, 2026, <strong>AMD and Anthropic</strong> announced a strategic partnership to deploy up to <strong>two gigawatts</strong> of AMD Instinct MI450-series GPUs, with the first gigawatt slated to come online in the first half of 2027. The systems pair AMD''s Instinct MI455X accelerators with EPYC "Venice" CPUs and the ROCm software stack.</p>
<h2>A circular, multi-billion-dollar deal</h2>
<p>AMD intends to invest up to <strong>$5 billion</strong> in Anthropic, contingent on milestones, while Anthropic commits to buying tens of billions of dollars in AI server chips over the term of the deal. The two also launched an engineering collaboration that uses Claude to optimize Instinct workloads and accelerate ROCm — a direct challenge to Nvidia''s dominance of AI infrastructure.</p>' WHERE slug='amd-anthropic-partnership' AND lang='en';
UPDATE news SET body='<p>22 июля 2026 года <strong>AMD и Anthropic</strong> объявили о стратегическом партнёрстве по развёртыванию до <strong>двух гигаватт</strong> GPU серии AMD Instinct MI450, при этом первый гигаватт должен заработать в первой половине 2027 года. Системы сочетают ускорители AMD Instinct MI455X с процессорами EPYC "Venice" и программным стеком ROCm.</p>
<h2>Круговая сделка на несколько миллиардов долларов</h2>
<p>AMD намерена инвестировать до <strong>$5 billion</strong> в Anthropic в зависимости от достижения определённых целевых показателей, а Anthropic обязуется закупить десятки миллиардов долларов в AI серверных чипах на протяжении срока действия сделки. Компании также запустили инженерное сотрудничество, которое использует Claude для оптимизации рабочих нагрузок Instinct и ускорения ROCm — прямой вызов доминированию Nvidia в инфраструктуре ИИ.</p>' WHERE slug='amd-anthropic-partnership' AND lang='ru';
UPDATE news SET body='<p>22 липня 2026 року <strong>AMD та Anthropic</strong> оголосили про стратегічне партнерство щодо розгортання до <strong>двох гігаватів</strong> графічних процесорів AMD Instinct MI450-series, причому перший гігават має запуститися в першій половині 2027 року. Системи поєднують прискорювачі AMD Instinct MI455X з процесорами EPYC "Venice" та програмним стеком ROCm.</p>
<h2>Циклічна многомільярдна угода</h2>
<p>AMD має намір інвестувати до <strong>$5 мільярдів</strong> у Anthropic, при умові досягнення ключових етапів, тоді як Anthropic зобов''язується купити десятки мільярдів доларів у мікросхемах AI-серверів упродовж терміну угоди. Обидві компанії також запустили інженерне співробітництво, яке використовує Claude для оптимізації робочих навантажень Instinct та прискорення ROCm — прямий виклик домінуванню Nvidia в інфраструктурі AI.</p>' WHERE slug='amd-anthropic-partnership' AND lang='ua';
UPDATE news SET body='<p>ב-22 ביולי 2026, <strong>AMD ו-Anthropic</strong> הודיעו על שותפות אסטרטגית לפריסת עד <strong>שני ג''יגוואט</strong> של GPUs מסדרת AMD Instinct MI450, כאשר הג''יגוואט הראשון צפוי להיכנס לפעולה במחצית הראשונה של 2027. המערכות משלבות מאיצי AMD Instinct MI455X עם CPUs EPYC "Venice" וערימת התוכנה ROCm.</p>
<h2>עסקה מעגלית בעלת מיליארדים</h2>
<p>AMD מתכננת להשקיע עד <strong>5 מיליארד דולר</strong> ב-Anthropic, בהתאם לאבני דרך, בעוד ש-Anthropic מתחייבת לרכישת עשרות מיליארדים של דולרים בשבבי שרתי AI על פני תקופת העסקה. השתיים גם הטיחו שיתוף פעולה הנדסי המשתמש ב-Claude כדי לייעל עומסי עבודה של Instinct ולהאיץ את ROCm — אתגר ישיר להדומיננטיות של Nvidia בתשתיות AI.</p>' WHERE slug='amd-anthropic-partnership' AND lang='he';
UPDATE news SET body='<p>Am 22. Juli 2026 kündigten <strong>AMD und Anthropic</strong> eine strategische Partnerschaft an, um bis zu <strong>zwei Gigawatt</strong> AMD Instinct MI450-Serie GPUs bereitzustellen, wobei das erste Gigawatt in der ersten Hälfte 2027 in Betrieb gehen soll. Die Systeme kombinieren AMDs Instinct MI455X Beschleuniger mit EPYC "Venice" CPUs und den ROCm Software Stack.</p>
<h2>Ein zirkulärer, mehrere Milliarden Dollar schwerer Deal</h2>
<p>AMD beabsichtigt, bis zu <strong>$5 Milliarden</strong> in Anthropic zu investieren, abhängig von Meilensteinen, während sich Anthropic zum Kauf von Zehner-Milliarden-Dollar-Beträgen in AI-Server-Chips über die Laufzeit des Deals verpflichtet. Die beiden starteten auch eine Engineering-Zusammenarbeit, die Claude nutzt, um Instinct Workloads zu optimieren und ROCm zu beschleunigen – eine direkte Herausforderung für Nvidias Dominanz in der AI-Infrastruktur.</p>' WHERE slug='amd-anthropic-partnership' AND lang='de';
UPDATE news SET body='<p>El 22 de julio de 2026, <strong>AMD y Anthropic</strong> anunciaron una asociación estratégica para desplegar hasta <strong>dos gigavatios</strong> de GPUs de la serie AMD Instinct MI450, con el primer gigavatio previsto para entrar en funcionamiento en la primera mitad de 2027. Los sistemas combinan aceleradores AMD Instinct MI455X con CPUs EPYC "Venice" y la pila de software ROCm.</p>
<h2>Un acuerdo circular de miles de millones de dólares</h2>
<p>AMD tiene la intención de invertir hasta <strong>$5 billion</strong> en Anthropic, condicionado a hitos, mientras que Anthropic se compromete a comprar decenas de miles de millones de dólares en chips de servidor de IA durante el período del acuerdo. Los dos también lanzaron una colaboración de ingeniería que utiliza Claude para optimizar cargas de trabajo de Instinct y acelerar ROCm — un desafío directo a la dominancia de Nvidia en la infraestructura de IA.</p>' WHERE slug='amd-anthropic-partnership' AND lang='es';
UPDATE news SET body='<p>Le 22 juillet 2026, <strong>AMD et Anthropic</strong> ont annoncé un partenariat stratégique pour déployer jusqu''à <strong>deux gigawatts</strong> de GPU de la série AMD Instinct MI450, le premier gigawatt devant être mis en ligne au cours du premier semestre 2027. Les systèmes associent les accélérateurs AMD Instinct MI455X aux processeurs EPYC « Venice » et à la pile logicielle ROCm.</p>
<h2>Un accord circulaire d''plusieurs milliards de dollars</h2>
<p>AMD a l''intention d''investir jusqu''à <strong>5 milliards de dollars</strong> dans Anthropic, sous réserve de jalons, tandis qu''Anthropic s''engage à acheter des dizaines de milliards de dollars de puces serveur IA au cours de la durée de l''accord. Les deux ont également lancé une collaboration d''ingénierie qui utilise Claude pour optimiser les charges de travail Instinct et accélérer ROCm — un défi direct à la domination d''Nvidia dans l''infrastructure IA.</p>' WHERE slug='amd-anthropic-partnership' AND lang='fr';
UPDATE news SET body='<p>Em 22 de julho de 2026, <strong>AMD e Anthropic</strong> anunciaram uma parceria estratégica para implementar até <strong>dois gigawatts</strong> de GPUs da série AMD Instinct MI450, com o primeiro gigawatt previsto para entrar em operação no primeiro semestre de 2027. Os sistemas combinam aceleradores AMD Instinct MI455X com CPUs EPYC "Venice" e a pilha de software ROCm.</p>
<h2>Um acordo circular de bilhões de dólares</h2>
<p>A AMD pretende investir até <strong>$5 billion</strong> na Anthropic, condicionado a marcos, enquanto a Anthropic se compromete a comprar dezenas de bilhões de dólares em chips de servidores de IA ao longo do período do acordo. As duas também lançaram uma colaboração de engenharia que usa Claude para otimizar cargas de trabalho do Instinct e acelerar o ROCm — um desafio direto à dominância da Nvidia na infraestrutura de IA.</p>' WHERE slug='amd-anthropic-partnership' AND lang='pt';
UPDATE news SET body='<p>On July 16, 2026, the <strong>European Commission</strong> issued two binding decisions under the Digital Markets Act requiring Google to give competing AI assistants equal footing on Android. Google must open <strong>11 system features</strong> to third-party AI services — including on-device model access, background task execution and screen context on par with its own Gemini assistant.</p>
<h2>Data sharing and pushback</h2>
<p>A second decision obliges Google to share anonymized search data with rival search engines and AI chatbots from January 2027, while most Android changes are due by August 2027. Google has strongly opposed the rules, warning that granting deep system-level access to external apps could create security risks — setting up a prolonged fight over how AI assistants work on Europe''s phones.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='en';
UPDATE news SET body='<p>16 июля 2026 года <strong>Европейская комиссия</strong> издала два обязательных решения в соответствии с Законом о цифровых рынках, требующих от Google предоставить конкурирующим AI-ассистентам равные условия на Android. Google должна открыть <strong>11 системных функций</strong> сторонним AI-сервисам — включая доступ к моделям на устройстве, выполнение фоновых задач и доступ к контексту экрана наравне со своим ассистентом Gemini.</p>
<h2>Обмен данными и противодействие</h2>
<p>Второе решение обязывает Google делиться анонимизированными данными поиска с конкурирующими поисковыми системами и AI-чатботами с января 2027 года, в то время как большинство изменений Android должны быть реализованы к августу 2027 года. Google решительно выступила против этих правил, предупредив, что предоставление глубокого системного доступа внешним приложениям может создать риски безопасности — что приводит к затяжному конфликту по поводу того, как AI-ассистенты работают на телефонах в Европе.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='ru';
UPDATE news SET body='<p>16 липня 2026 року <strong>Європейська комісія</strong> видала два обов''язкових рішення відповідно до Закону про цифрові ринки, вимагаючи від Google надати конкуруючим AI-асистентам рівні умови на Android. Google повинна відкрити <strong>11 системних функцій</strong> для сторонніх AI-сервісів — включаючи доступ до локальних моделей, виконання фонових завдань та контекст екрана на рівні з її власним асистентом Gemini.</p>
<h2>Обмін даними та опір</h2>
<p>Друге рішення зобов''язує Google ділитися анонімізованими даними пошуку з конкуруючими пошуковими системами та AI-чатботами з січня 2027 року, тоді як більшість змін Android мають бути завершені до серпня 2027 року. Google рішуче протистоїть цим правилам, попереджуючи, що надання глибокого доступу на рівні системи зовнішнім додаткам може створити ризики безпеки — що призводить до тривалої боротьби щодо того, як AI-асистенти працюють на європейських телефонах.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='ua';
UPDATE news SET body='<p>ב-16 ליולי 2026, ה-<strong>European Commission</strong> הוציאה שתי החלטות חיוביות על פי ה-Digital Markets Act המחייבות את Google לתן לעוזרי AI מתחרים עמדה שווה ב-Android. Google חייבת לפתוח <strong>11 תכונות מערכת</strong> לשירותי AI של צד שלישי — כולל גישה למודל מקומי, ביצוע משימות רקע והקשר מסך כמו בעוזר Gemini שלה.</p>
<h2>שיתוף נתונים והתנגדות</h2>
<p>החלטה שנייה מחייבת את Google לשתף נתוני חיפוש אנונימיים עם מנועי חיפוש ותיקיות AI מתחרות החל מינואר 2027, בעוד שרוב השינויים ב-Android צפויים עד אוגוסט 2027. Google התנגדה בחוזקה לכללים, מזהירה כי הענקת גישה עמוקה ברמת המערכת ליישומים חיצוניים עלולה ליצור סיכונים אבטחה — מה שמתווה קרב ממושך על אופן פעולת עוזרי AI בטלפוני היד של אירופה.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='he';
UPDATE news SET body='<p>Am 16. Juli 2026 erließ die <strong>Europäische Kommission</strong> zwei verbindliche Entscheidungen gemäß des Digital Markets Act, die Google verpflichten, konkurrierende KI-Assistenten auf Android gleichberechtigt zu behandeln. Google muss <strong>11 Systemfunktionen</strong> für Drittanbieter-KI-Dienste öffnen — einschließlich On-Device-Modellzugriff, Ausführung von Hintergrundaufgaben und Bildschirmkontext gleichwertig mit seinem eigenen Gemini-Assistenten.</p>
<h2>Datenaustausch und Widerstand</h2>
<p>Eine zweite Entscheidung verpflichtet Google, anonymisierte Suchdaten ab Januar 2027 mit konkurrierenden Suchmaschinen und KI-Chatbots zu teilen, während die meisten Android-Änderungen bis August 2027 erfolgen müssen. Google hat sich den Regeln stark widersetzt und warnt davor, dass die Gewährung von tiefem Systemzugriff für externe Apps Sicherheitsrisiken schaffen könnte — was zu einem längeren Kampf darüber führt, wie KI-Assistenten auf europäischen Telefonen funktionieren.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='de';
UPDATE news SET body='<p>El 16 de julio de 2026, la <strong>Comisión Europea</strong> emitió dos decisiones vinculantes en virtud de la Ley de Mercados Digitales que requieren que Google otorgue a los asistentes de IA competidores igualdad de condiciones en Android. Google debe abrir <strong>11 características del sistema</strong> a servicios de IA de terceros — incluyendo acceso a modelos en el dispositivo, ejecución de tareas en segundo plano y contexto de pantalla equivalente al de su propio asistente Gemini.</p>
<h2>Intercambio de datos y rechazo</h2>
<p>Una segunda decisión obliga a Google a compartir datos de búsqueda anonimizados con motores de búsqueda rivales y chatbots de IA a partir de enero de 2027, mientras que la mayoría de los cambios en Android vencen en agosto de 2027. Google se ha opuesto firmemente a las normas, advirtiendo que otorgar acceso profundo a nivel del sistema a aplicaciones externas podría crear riesgos de seguridad — preparando el terreno para una prolongada batalla sobre cómo funcionan los asistentes de IA en los teléfonos de Europa.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='es';
UPDATE news SET body='<p>Le 16 juillet 2026, la <strong>Commission européenne</strong> a rendu deux décisions contraignantes en vertu de la Loi sur les marchés numériques obligeant Google à donner une égalité des chances aux assistants IA concurrents sur Android. Google doit ouvrir <strong>11 fonctionnalités système</strong> aux services IA tiers — notamment l''accès aux modèles sur appareil, l''exécution des tâches en arrière-plan et le contexte d''écran au même titre que son propre assistant Gemini.</p>
<h2>Partage de données et opposition</h2>
<p>Une deuxième décision oblige Google à partager des données de recherche anonymisées avec les moteurs de recherche concurrents et les chatbots IA à partir de janvier 2027, tandis que la plupart des modifications Android doivent être effectuées d''ici août 2027. Google s''est fortement opposé à ces règles, avertissant que l''octroi d''un accès profond au niveau système à des applications externes pourrait créer des risques de sécurité — préparant le terrain à un affrontement prolongé sur le fonctionnement des assistants IA sur les téléphones européens.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='fr';
UPDATE news SET body='<p>Em 16 de julho de 2026, a <strong>Comissão Europeia</strong> emitiu duas decisões vinculantes sob a Lei de Mercados Digitais exigindo que o Google dê aos assistentes de IA concorrentes igualdade de condições no Android. O Google deve abrir <strong>11 recursos do sistema</strong> para serviços de IA de terceiros — incluindo acesso a modelos on-device, execução de tarefas em segundo plano e contexto de tela equivalente ao seu próprio assistente Gemini.</p>
<h2>Compartilhamento de dados e resistência</h2>
<p>Uma segunda decisão obriga o Google a compartilhar dados de busca anonimizados com mecanismos de busca rivais e chatbots de IA a partir de janeiro de 2027, enquanto a maioria das mudanças do Android vence em agosto de 2027. O Google se opôs fortemente às regras, advertindo que conceder acesso profundo no nível do sistema a aplicativos externos pode criar riscos de segurança — criando uma luta prolongada sobre como assistentes de IA funcionam nos telefones europeus.</p>' WHERE slug='eu-google-android-ai-assistants' AND lang='pt';
UPDATE news SET body='<p>On July 16, 2026, China''s <strong>Moonshot AI</strong> released <strong>Kimi K3</strong>, a 2.8-trillion-parameter open-weight Mixture-of-Experts model with a 1-million-token context window — the largest open-weight model ever shipped. Within hours it debuted at <strong>#1 on LMArena''s Frontend Code Arena</strong> with a score of 1679, overtaking Anthropic''s Claude Fable 5 on the benchmark that most directly measures production coding value.</p>
<h2>Open models reach the frontier</h2>
<p>The launch is a milestone for open-weight AI: a freely available model from China is now competing with the best closed systems on real-world coding, despite US limits on advanced chip exports. For developers, K3 offers frontier-level performance that can be self-hosted or accessed cheaply, intensifying price and capability pressure on proprietary providers.</p>' WHERE slug='moonshot-kimi-k3' AND lang='en';
UPDATE news SET body='<p>16 июля 2026 года китайская компания <strong>Moonshot AI</strong> выпустила <strong>Kimi K3</strong> — модель Mixture-of-Experts с 2,8 триллионами параметров с открытыми весами и контекстным окном в 1 миллион токенов, самую крупную модель с открытыми весами из когда-либо выпущенных. В течение нескольких часов она заняла <strong>#1 место в Frontend Code Arena на LMArena</strong> с результатом 1679, обойдя Claude Fable 5 компании Anthropic на тесте, который наиболее прямо измеряет ценность кодирования в production.</p>
<h2>Открытые модели достигают границы возможностей</h2>
<p>Запуск стал вехой для открытых моделей ИИ: свободно доступная модель из Китая теперь конкурирует с лучшими закрытыми системами в реальном кодировании, несмотря на ограничения США на экспорт передовых чипов. Для разработчиков K3 предлагает производительность мирового уровня, которая может быть самостоятельно размещена или доступна по низкой цене, усиливая давление на цены и возможности проприетарных поставщиков.</p>' WHERE slug='moonshot-kimi-k3' AND lang='ru';
UPDATE news SET body='<p>16 липня 2026 року китайська компанія <strong>Moonshot AI</strong> випустила <strong>Kimi K3</strong> — модель Mixture-of-Experts з 2.8 трильйонами параметрів та відкритими вагами з контекстним вікном на 1-million-token, найбільшу модель з відкритими вагами, що коли-небудь була випущена. За кілька годин вона посіла <strong>#1 місце в LMArena''s Frontend Code Arena</strong> з результатом 1679, обійшовши Claude Fable 5 від Anthropic у бенчмарку, який найбільше безпосередньо вимірює цінність продакшену коду.</p>
<h2>Відкриті моделі досягають границь можливого</h2>
<p>Запуск є значним етапом для відкритовагової ШІ: вільнодоступна модель з Китаю тепер конкурує з найкращими закритими системами у реальному кодуванні, незважаючи на обмеження США щодо експорту передових чипів. Для розробників K3 пропонує продвинутий рівень продуктивності, який можна використовувати локально або отримати дешево, посилюючи цінову та функціональну конкуренцію для постачальників закритих рішень.</p>' WHERE slug='moonshot-kimi-k3' AND lang='ua';
UPDATE news SET body='<p>ב-16 ביולי 2026, <strong>Moonshot AI</strong> של סין השיקה את <strong>Kimi K3</strong>, מודל Mixture-of-Experts בעל משקל פתוח עם 2.8 טריליון פרמטרים וחלון קונטקסט של 1-million-token — המודל בעל משקל פתוח הגדול ביותר שהושק אי פעם. תוך שעות הוא הופיע במקום <strong>#1 ב-LMArena''s Frontend Code Arena</strong> עם ניקוד של 1679, וגבר על Claude Fable 5 של Anthropic בבנצ''מארק שמודד ישירות ביותר את הערך של קוד ייצור.</p>
<h2>מודלים פתוחים מגיעים לקצה</h2>
<p>ההשקה היא אבן דרך עבור AI בעל משקל פתוח: מודל זמין בחופשיות מסין מתחרה כעת עם המערכות הסגורות הטובות ביותר בקידוד בעולם האמת, למרות מגבלות ארה"ב על ייצוא שבבים מתקדמים. עבור מפתחים, K3 מציע ביצועים ברמת הגבול שניתן לארח בעצמי או לגשת אליהם בעלות נמוכה, ומעצים לחץ של מחיר ויכולת על ספקים קנייניים.</p>' WHERE slug='moonshot-kimi-k3' AND lang='he';
UPDATE news SET body='<p>Am 16. Juli 2026 veröffentlichte Chinas <strong>Moonshot AI</strong> <strong>Kimi K3</strong>, ein Mixture-of-Experts-Modell mit 2,8 Billionen Parametern und offenem Gewicht mit einem 1-million-token-Kontextfenster — das größte Open-Weight-Modell, das je veröffentlicht wurde. Innerhalb weniger Stunden debütierte es auf <strong>#1 in LMArena''s Frontend Code Arena</strong> mit einem Score von 1679 und überholte damit Anthropics Claude Fable 5 in dem Benchmark, der den Produktions-Codierungswert am direktesten misst.</p>
<h2>Open Models erreichen die Grenze</h2>
<p>Der Launch ist ein Meilenstein für Open-Weight-AI: Ein frei verfügbares Modell aus China konkurriert nun mit den besten geschlossenen Systemen bei realer Programmierung, trotz US-Beschränkungen für den Export fortgeschrittener Chips. Für Entwickler bietet K3 Frontier-Level-Performance, die selbst gehostet oder günstig zugänglich ist und verstärkt den Preis- und Leistungsdruck auf proprietäre Anbieter.</p>' WHERE slug='moonshot-kimi-k3' AND lang='de';
UPDATE news SET body='<p>El 16 de julio de 2026, la empresa china <strong>Moonshot AI</strong> lanzó <strong>Kimi K3</strong>, un modelo de Mezcla de Expertos de código abierto con 2.8 billones de parámetros y una ventana de contexto de 1-million-token — el modelo de código abierto más grande jamás lanzado. En cuestión de horas, debutó en el <strong>#1 en el Frontend Code Arena de LMArena</strong> con una puntuación de 1679, superando al Claude Fable 5 de Anthropic en el benchmark que mide más directamente el valor de codificación en producción.</p>
<h2>Los modelos abiertos alcanzan la frontera</h2>
<p>El lanzamiento es un hito para la IA de código abierto: un modelo disponible gratuitamente de China ahora está compitiendo con los mejores sistemas cerrados en codificación del mundo real, a pesar de las limitaciones estadounidenses en las exportaciones de chips avanzados. Para los desarrolladores, K3 ofrece un rendimiento de nivel fronterizo que puede ser autohospedado o accedido económicamente, intensificando la presión de precio y capacidad sobre los proveedores propietarios.</p>' WHERE slug='moonshot-kimi-k3' AND lang='es';
UPDATE news SET body='<p>Le 16 juillet 2026, <strong>Moonshot AI</strong> chinois a lancé <strong>Kimi K3</strong>, un modèle Mixture-of-Experts open-weight de 2,8 billions de paramètres avec une fenêtre de contexte de 1-million-token — le plus grand modèle open-weight jamais livré. En quelques heures, il a fait ses débuts à la <strong>#1 sur le Frontend Code Arena de LMArena</strong> avec un score de 1679, dépassant Claude Fable 5 d''Anthropic sur le benchmark qui mesure le plus directement la valeur du codage en production.</p>
<h2>Les modèles open atteignent la frontière</h2>
<p>Le lancement est un jalon pour l''IA open-weight : un modèle librement disponible de Chine concurrence désormais les meilleurs systèmes fermés sur le codage du monde réel, malgré les restrictions américaines sur les exportations de puces avancées. Pour les développeurs, K3 offre une performance au niveau de la frontière qui peut être auto-hébergée ou accessible à bas coût, intensifiant la pression tarifaire et de capacité sur les fournisseurs propriétaires.</p>' WHERE slug='moonshot-kimi-k3' AND lang='fr';
UPDATE news SET body='<p>Em 16 de julho de 2026, a <strong>Moonshot AI</strong> chinesa lançou o <strong>Kimi K3</strong>, um modelo Mixture-of-Experts open-weight com 2.8 trilhões de parâmetros e janela de contexto de 1-million-token — o maior modelo open-weight já lançado. Horas depois, ele estreou em <strong>#1 na Frontend Code Arena do LMArena</strong> com uma pontuação de 1679, ultrapassando o Claude Fable 5 da Anthropic no benchmark que mais diretamente mede o valor de codificação em produção.</p>
<h2>Modelos abertos atingem a fronteira</h2>
<p>O lançamento é um marco para a IA open-weight: um modelo gratuito da China agora está competindo com os melhores sistemas fechados em codificação do mundo real, apesar das limitações dos EUA sobre exportações de chips avançados. Para desenvolvedores, o K3 oferece desempenho em nível de fronteira que pode ser auto-hospedado ou acessado com baixo custo, intensificando a pressão de preço e capacidade sobre os provedores proprietários.</p>' WHERE slug='moonshot-kimi-k3' AND lang='pt';
UPDATE news SET body='<p>Google''s <strong>Gemini 3.5 Pro</strong> — announced at I/O in May 2026 with a 2-million-token context window and a Deep Think reasoning layer — slipped again in mid-July. After reportedly targeting a July 17 launch, Google delayed the release when the model missed internal quality goals on hallucination rates and real-world reliability.</p>
<h2>Back to the drawing board</h2>
<p>According to reporting, DeepMind scrapped and rebuilt the base model rather than ship something below its standards, leaving no confirmed date, context-window figure or pricing. For now, the faster <strong>Gemini 3.5 Flash</strong> — recently upgraded with agentic Computer Use — remains Google''s current stable flagship, while the more powerful Pro tier stays in limited preview.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='en';
UPDATE news SET body='<p>Google''s <strong>Gemini 3.5 Pro</strong> — announced at I/O in May 2026 with a 2-million-token context window and a Deep Think reasoning layer — slipped again in mid-July. After reportedly targeting a July 17 launch, Google delayed the release when the model missed internal quality goals on hallucination rates and real-world reliability.</p>
<h2>Back to the drawing board</h2>
<p>According to reporting, DeepMind scrapped and rebuilt the base model rather than ship something below its standards, leaving no confirmed date, context-window figure or pricing. For now, the faster <strong>Gemini 3.5 Flash</strong> — recently upgraded with agentic Computer Use — remains Google''s current stable flagship, while the more powerful Pro tier stays in limited preview.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='ru';
UPDATE news SET body='<p>Google''s <strong>Gemini 3.5 Pro</strong> — announced at I/O in May 2026 with a 2-million-token context window and a Deep Think reasoning layer — slipped again in mid-July. After reportedly targeting a July 17 launch, Google delayed the release when the model missed internal quality goals on hallucination rates and real-world reliability.</p>
<h2>Back to the drawing board</h2>
<p>According to reporting, DeepMind scrapped and rebuilt the base model rather than ship something below its standards, leaving no confirmed date, context-window figure or pricing. For now, the faster <strong>Gemini 3.5 Flash</strong> — recently upgraded with agentic Computer Use — remains Google''s current stable flagship, while the more powerful Pro tier stays in limited preview.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='ua';
UPDATE news SET body='<p>ה-<strong>Gemini 3.5 Pro</strong> של Google — שהוכרז ב-I/O במאי 2026 עם חלון הקשר של 2-million-token ושכבת推론Deep Think — התעכב שוב באמצע יולי. לאחר שדווח כי Google כיוונה להשקה ב-17 ביולי, העיכבה Google את ההוצאה לאור כאשר המודל לא עמד במטרות איכות פנימיות בקצב ההזיות ובאמינות בעולם האמיתי.</p>
<h2>חזרה לשולחן הדיוקן</h2>
<p>על פי הדיווחים, DeepMind ביטלה ובנתה מחדש את המודל הבסיסי במקום לספק משהו מתחת לתקנים שלה, תוך שלא הותירה תאריך מאושר, נתון חלון הקשר או תמחור. לעת עתה, ה-<strong>Gemini 3.5 Flash</strong> המהיר יותר — שנשדרג לאחרונה עם Computer Use מבוססת סוכן — נשאר הדגל היציב הנוכחי של Google, בעוד שרמת Pro החזקה יותר נשארת בתצוגה מוגבלת.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='he';
UPDATE news SET body='<p>Googles <strong>Gemini 3.5 Pro</strong> — angekündigt bei der I/O im Mai 2026 mit einem 2-Million-Token-Kontextfenster und einer Deep Think Reasoning-Schicht — verzögerte sich erneut Mitte Juli. Nach einem angestrebten Start am 17. Juli verzögerte Google die Veröffentlichung, da das Modell interne Qualitätsziele bei Halluzinationsraten und realer Zuverlässigkeit nicht erfüllte.</p>
<h2>Zurück an den Anfang</h2>
<p>Berichten zufolge verwarf und rekonstruierte DeepMind das Basismodell, anstatt etwas unter seinen Standards zu veröffentlichen, sodass kein bestätigtes Veröffentlichungsdatum, Kontextfenster-Größe oder Preis verfügbar ist. Vorerst bleibt das schnellere <strong>Gemini 3.5 Flash</strong> — kürzlich mit agentic Computer Use erweitert — Googles aktuelles stabiles Flaggschiff, während die leistungsstärkere Pro-Tier in limitierter Vorschau bleibt.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='de';
UPDATE news SET body='<p>El <strong>Gemini 3.5 Pro</strong> de Google — anunciado en I/O en mayo de 2026 con una ventana de contexto de 2-million-token y una capa de razonamiento Deep Think — se retrasó nuevamente a mediados de julio. Después de apuntar aparentemente a un lanzamiento el 17 de julio, Google retrasó el lanzamiento cuando el modelo no alcanzó los objetivos de calidad internos en tasas de alucinación y confiabilidad en el mundo real.</p>
<h2>Volver a empezar</h2>
<p>Según los reportes, DeepMind desechó y reconstruyó el modelo base en lugar de lanzar algo por debajo de sus estándares, sin dejar una fecha de lanzamiento confirmada, cifra de ventana de contexto o precio. Por ahora, el más rápido <strong>Gemini 3.5 Flash</strong> — recientemente actualizado con Computer Use agentic — sigue siendo el buque insignia estable actual de Google, mientras que el nivel Pro más potente permanece en vista previa limitada.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='es';
UPDATE news SET body='<p>Le <strong>Gemini 3.5 Pro</strong> de Google — annoncé à la conférence I/O en mai 2026 avec une fenêtre de contexte de 2-million-token et une couche de raisonnement Deep Think — a connu un nouveau retard à la mi-juillet. Après avoir visé un lancement le 17 juillet, Google a retardé la sortie lorsque le modèle n''a pas atteint ses objectifs de qualité internes en matière de taux d''hallucination et de fiabilité dans le monde réel.</p>
<h2>Retour à la planche à dessin</h2>
<p>Selon les rapports, DeepMind a abandonné et reconstruit le modèle de base plutôt que de livrer quelque chose en deçà de ses normes, ne laissant aucune date de lancement confirmée, figure de fenêtre de contexte ou tarification. Pour l''instant, le plus rapide <strong>Gemini 3.5 Flash</strong> — récemment amélioré avec Computer Use agentic — reste l''étendard stable actuel de Google, tandis que le tier Pro plus puissant reste en aperçu limité.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='fr';
UPDATE news SET body='<p>O <strong>Gemini 3.5 Pro</strong> do Google — anunciado na I/O em maio de 2026 com uma janela de contexto de 2-million-token e uma camada de raciocínio Deep Think — sofreu um atraso novamente em meados de julho. Após supostamente visar um lançamento em 17 de julho, o Google adiou o lançamento quando o modelo não atingiu os objetivos de qualidade interna em taxas de alucinação e confiabilidade no mundo real.</p>
<h2>De volta à prancheta</h2>
<p>De acordo com relatos, o DeepMind descartou e reconstruiu o modelo base em vez de lançar algo abaixo de seus padrões, deixando sem data confirmada, figura de janela de contexto ou preço. Por enquanto, o mais rápido <strong>Gemini 3.5 Flash</strong> — recentemente atualizado com Computer Use agêntico — permanece como o flagship estável atual do Google, enquanto o nível Pro mais poderoso continua em preview limitado.</p>' WHERE slug='gemini-3-5-pro-delayed-rebuild' AND lang='pt';
