-- AItoolFit — tool description_long freshness + Kiro replacing Amazon Q. Web-verified 2026-07-27.
-- Run AFTER 01/02/03. Idempotent. Then Claude regenerates tool pages + sitemap.

-- 1) version-token swaps (per-slug, applies to all 8 langs) --
UPDATE tools SET description_long=replace(description_long, 'GPT-4o', 'GPT-5.6'), last_updated='2026-07-28' WHERE slug='aider';
UPDATE tools SET description_long=replace(description_long, 'Opus 4.6', 'Opus 4.8'), last_updated='2026-07-28' WHERE slug='bolt-new';
UPDATE tools SET description_long=replace(description_long, 'Opus 4.7', 'Opus 4.8'), last_updated='2026-07-28' WHERE slug='cursor';
UPDATE tools SET description_long=replace(description_long, 'GPT-4o', 'GPT-5.6'), last_updated='2026-07-28' WHERE slug='duolingo-max';
UPDATE tools SET description_long=replace(description_long, 'Grok 4.3', 'Grok 4.5'), last_updated='2026-07-28' WHERE slug='grok';
UPDATE tools SET description_long=replace(description_long, 'Opus 4.6', 'Opus 4.8'), last_updated='2026-07-28' WHERE slug='microsoft-copilot-studio';
UPDATE tools SET description_long=replace(description_long, 'GPT-4o', 'GPT-5.6'), last_updated='2026-07-28' WHERE slug='n8n';
UPDATE tools SET description_long=replace(description_long, 'Gemini 2.5 Flash', 'Gemini 3.1 Flash'), last_updated='2026-07-28' WHERE slug='nano-banana';
UPDATE tools SET description_long=replace(description_long, 'Claude 4.5', 'Claude Sonnet 5'), last_updated='2026-07-28' WHERE slug='writesonic';
UPDATE tools SET description_long=replace(description_long, 'Opus 4.7', 'Opus 4.8'), last_updated='2026-07-28' WHERE slug='julius-ai';

-- 2) narrative tools: full body replaced per lang (EN edited, others translated) --
UPDATE tools SET description_long='ChatGPT is OpenAI''s flagship chat assistant for writing, coding, research, analysis and multimodal tasks. It works in the browser, in desktop and mobile apps, and through the API, and it has become one of the most widely used consumer AI products in the world.

As of July 2026 the default model is the GPT-5.6 family — Sol, Terra and Luna — offered in Instant and Thinking modes, with a Pro variant on higher tiers. GPT-5.6 launched in July 2026 and replaced the GPT-5.5 lineup; the model picker was simplified to Instant, Thinking and Pro. The GPT-4o era is over, and GPT-4o is no longer the flagship. A newer GPT-5.6 family (Sol flagship, Terra balanced, Luna fast) has entered limited preview but is not yet generally available.

Capabilities cover long-form and technical writing, code generation and debugging, document and image analysis, voice conversations, web browsing, data analysis, and image generation, all built on the current multimodal GPT-5.x stack rather than the older GPT-4o pipeline. Higher tiers add larger context windows and Sora video generation.

Pricing is tiered. Free is $0/mo and now shows ads to logged-in adult users in the US (since February 2026), with the default GPT-5.6 model at limited usage. The new Go tier is $8/mo and has rolled out worldwide. Plus is $20/mo. Pro is now split into two options: $100/mo with roughly 5x Plus quotas, and $200/mo with about 20x quotas plus Sora video and a 1M-token context window. Business (Team) is $25/user/mo with a two-seat minimum, and Enterprise is custom-priced.

Limitations remain real. The model can still produce confident but wrong answers, free usage is capped and now ad-supported in the US, and the most useful capabilities (long context, video, heavy quotas) sit behind the pricier tiers. GPT-5.6 is preview-only, so you cannot rely on it for production yet.

ChatGPT suits almost anyone who wants a general-purpose AI assistant, from casual users on the free or Go tier to professionals and teams who need higher quotas, larger context and collaboration features.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='en';
UPDATE tools SET description_long='ChatGPT — флагманский чат-помощник OpenAI для написания текстов, программирования, исследований, анализа и мультимодальных задач. Он работает в браузере, в приложениях для компьютера и мобильных устройств, а также через API и стал одним из самых широко используемых потребительских продуктов ИИ в мире.

По состоянию на июль 2026 года моделью по умолчанию является семейство GPT-5.6 — Sol, Terra и Luna — предлагаемое в режимах Instant и Thinking с вариантом Pro на более высоких уровнях. GPT-5.6 запущен в июле 2026 года и заменил линейку GPT-5.5; селектор моделей был упрощен до Instant, Thinking и Pro. Эра GPT-4o закончилась, и GPT-4o больше не является флагманом. Новое семейство GPT-5.6 (флагман Sol, сбалансированный Terra, быстрый Luna) вступило в ограниченный предпросмотр, но еще не доступно широкой публике.

Возможности включают написание развернутых и технических текстов, генерацию и отладку кода, анализ документов и изображений, голосовые диалоги, веб-поиск, анализ данных и генерацию изображений — все это построено на текущем мультимодальном стеке GPT-5.x, а не на старом конвейере GPT-4o. Более высокие уровни добавляют большие контекстные окна и видеогенерацию Sora.

Цены распределены по уровням. Free составляет $0/mo и теперь показывает объявления авторизованным взрослым пользователям в США (с февраля 2026 года) с моделью GPT-5.6 по умолчанию при ограниченном использовании. Новый уровень Go стоит $8/mo и развернут по всему миру. Plus стоит $20/mo. Pro теперь разделен на два варианта: $100/mo с примерно 5-кратной квотой Plus и $200/mo с примерно 20-кратной квотой плюс видео Sora и контекстным окном в 1M токенов. Business (Team) стоит $25/user/mo с минимумом в два места, и Enterprise оценивается индивидуально.

Ограничения остаются реальными. Модель по-прежнему может выдавать уверенные, но неправильные ответы, бесплатное использование ограничено и теперь поддерживается объявлениями в США, а самые полезные возможности (большой контекст, видео, высокие квоты) находятся за более дорогими уровнями. GPT-5.6 находится только в режиме предпросмотра, поэтому вы не можете на него полагаться в production.

ChatGPT подходит почти всем, кто хочет универсального помощника ИИ, от случайных пользователей на бесплатном уровне или Go до профессионалов и команд, которым нужны более высокие квоты, больший контекст и функции сотрудничества.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='ru';
UPDATE tools SET description_long='ChatGPT — флагманський чат-асистент OpenAI для письма, кодування, досліджень, аналізу та мультимодальних завдань. Він працює у браузері, у настільних та мобільних застосунках, а також через API, і став одним із найбільш широко використовуваних споживацьких продуктів штучного інтелекту у світі.

Станом на липень 2026 року моделлю за замовчуванням є сімейство GPT-5.6 — Sol, Terra і Luna — пропоноване в режимах Instant і Thinking із варіантом Pro на вищих рівнях. GPT-5.6 запущений у липні 2026 року й замінив лінійку GPT-5.5; вибірник моделей було спрощено до Instant, Thinking і Pro. Епоха GPT-4o закінчилася, і GPT-4o більше не є флагманом. Нове сімейство GPT-5.6 (флагман Sol, збалансований Terra, швидкий Luna) увійшло в обмежену попередню версію, але ще недоступне широкому загалу.

Можливості охоплюють розгорнуте та технічне письмо, генерацію коду та налагодження, аналіз документів і зображень, голосові розмови, веб-перегляд, аналіз даних та генерацію зображень — усе побудоване на поточному мультимодальному стеку GPT-5.x замість старішого конвеєра GPT-4o. Вищі рівні додають більші контекстні вікна та генерацію відео Sora.

Ціноутворення є багаторівневим. Free коштує $0/mo і тепер показує оголошення авторизованим дорослим користувачам у США (з лютого 2026 року), з моделлю GPT-5.6 за замовчуванням з обмеженим використанням. Новий рівень Go коштує $8/mo й розгортається у всьому світі. Plus коштує $20/mo. Pro тепер розділений на два варіанти: $100/mo з приблизно 5-кратними квотами Plus та $200/mo з приблизно 20-кратними квотами плюс Sora для відео та контекстним вікном 1M-токен. Business (Team) коштує $25/user/mo з мінімумом двох місць, а Enterprise має індивідуальну ціну.

Обмеження залишаються реальними. Модель все ще може продукувати впевнені, але неправильні відповіді, безкоштовне використання обмежене й тепер підтримується оголошеннями у США, а найбільш корисні можливості (великий контекст, відео, великі квоти) знаходяться за дорожчими рівнями. GPT-5.6 тільки в попередній версії, тому ви не можете покладатися на нього для виробництва поки що.

ChatGPT підходить майже кожному, хто хоче загальнозначущого AI-асистента — від випадкових користувачів на безкоштовному рівні або Go до професіоналів і команд, які потребують вищих квот, більшого контексту та функцій співпраці.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='ua';
UPDATE tools SET description_long='ChatGPT הוא עוזר הצ''אט הדגלי של OpenAI לכתיבה, קוד, מחקר, ניתוח ומשימות מולטימודליות. הוא פועל בדפדפן, באפליקציות שולחן עבודה וסלולר, ודרך ה-API, והוא הפך לאחד מתוך מוצרי ה-AI הצרכניים הנמצאים בשימוש הנפוץ ביותר בעולם.

נכון ליולי 2026 מודל ברירת המחדל הוא משפחת GPT-5.6 — Sol, Terra ו-Luna — המוצעת במצבי Instant ו-Thinking, עם גרסת Pro בשכבות גבוהות יותר. GPT-5.6 הושקה ביולי 2026 והחליפה את קו ה-GPT-5.5; בוחר המודל פשוט לאפשרויות Instant, Thinking ו-Pro. עידן ה-GPT-4o הסתיים, ו-GPT-4o כבר אינו הדגלי. משפחת GPT-5.6 חדשה יותר (Sol דגלי, Terra מאוזן, Luna מהיר) נכנסה לתצוגה מקדימה מוגבלת אך עדיין אינה זמינה בכלל.

יכולות מכסות כתיבה ארוכת טווח וטכנית, יצירת קוד וניפוי שגיאות, ניתוח מסמכים ותמונות, שיחות קוליות, גלישה באינטרנט, ניתוח נתונים וייצור תמונות, כולם בנויים על ערימת GPT-5.x המולטימודלית הנוכחית ולא על צינור ה-GPT-4o הישן יותר. שכבות גבוהות יותר מוסיפות חלונות הקשר גדולים יותר וייצור וידאו Sora.

התמחור בשכבות. Free הוא $0/mo וכעת מציג מודעות למשתמשים מבוגרים מחוברים בארה"ב (מפברואר 2026), עם מודל GPT-5.6 ברירת המחדל בשימוש מוגבל. שכבת Go החדשה היא $8/mo והתגלגלה ברחבי העולם. Plus הוא $20/mo. Pro הוא כעת חלוקה לשתי אפשרויות: $100/mo עם בערך 5x Plus quotas, ו-$200/mo עם בערך 20x quotas בתוספת וידאו Sora וחלון הקשר של 1M-token. Business (Team) הוא $25/user/mo עם מינימום של שני מושבים, ו-Enterprise הוא בתמחור מותאם אישית.

מגבלות נותרות אמיתיות. המודל עדיין יכול לייצר תשובות בטוחות אך שגויות, השימוש בחינם מעוקף וכעת תומך בקידום במודעות בארה"ב, והיכולות השימושיות ביותר (הקשר ארוך, וידאו, quotas כבדים) יושבות מאחורי השכבות היקרות יותר. GPT-5.6 הוא בתצוגה מקדימה בלבד, ולכן אתה לא יכול להסתמך עליו לייצור בעדיין.

ChatGPT מתאים כמעט לכל מי שרוצה עוזר AI לשימוש כללי, מ-casual users בשכבה החינמית או Go לאנשי מקצוע וצוותים שצריכים quotas גבוהים יותר, הקשר גדול יותר ותכונות שיתוף פעולה.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='he';
UPDATE tools SET description_long='ChatGPT ist OpenAIs Flaggschiff-Chat-Assistent für Schreiben, Programmierung, Recherche, Analyse und multimodale Aufgaben. Es funktioniert im Browser, in Desktop- und Mobile-Apps sowie über die API und ist zu einem der am weitesten verbreiteten KI-Produkte für Verbraucher weltweit geworden.

Seit Juli 2026 ist das Standard-Modell die GPT-5.6-Familie — Sol, Terra und Luna — erhältlich in den Modi Instant und Thinking, mit einer Pro-Variante auf höheren Stufen. GPT-5.6 startete im Juli 2026 und ersetzte die GPT-5.5-Reihe; die Modellauswahl wurde auf Instant, Thinking und Pro vereinfacht. Die GPT-4o-Ära ist vorbei, und GPT-4o ist nicht mehr das Flaggschiff. Eine neuere GPT-5.6-Familie (Sol Flaggschiff, Terra ausgewogen, Luna schnell) ist in limitierte Vorschau gegangen, aber noch nicht allgemein verfügbar.

Die Funktionen umfassen längere und technische Texte, Code-Generierung und Debugging, Dokument- und Bildanalyse, Sprachgespräche, Web-Browsing, Datenanalyse und Bildgenerierung, alle basierend auf dem aktuellen multimodalen GPT-5.x-Stack anstelle der älteren GPT-4o-Pipeline. Höhere Stufen bieten größere Kontextfenster und Sora-Videogenerierung.

Die Preisgestaltung ist gestaffelt. Kostenlos ist $0/Mo und zeigt jetzt Anzeigen für angemeldete erwachsene Nutzer in den USA (seit Februar 2026), mit dem Standard-GPT-5.6-Modell bei begrenzter Nutzung. Der neue Go-Plan kostet $8/Mo und ist weltweit verfügbar. Plus kostet $20/Mo. Pro ist jetzt in zwei Optionen aufgeteilt: $100/Mo mit etwa 5x Plus-Kontingenten und $200/Mo mit etwa 20x Kontingenten plus Sora-Video und einem 1M-Token-Kontextfenster. Business (Team) kostet $25/Benutzer/Mo mit Mindestens zwei Plätzen, und Enterprise ist kundenspezifisch bepreist.

Einschränkungen bleiben bestehen. Das Modell kann immer noch sichere, aber falsche Antworten produzieren, die kostenlose Nutzung ist begrenzt und wird jetzt in den USA mit Anzeigen unterstützt, und die nützlichsten Funktionen (großer Kontext, Video, hohe Kontingente) sitzen hinter den teureren Stufen. GPT-5.6 ist nur Vorschau, daher können Sie sich darauf für die Produktion noch nicht verlassen.

ChatGPT eignet sich für fast jeden, der einen universellen KI-Assistenten möchte, von gelegentlichen Benutzern im kostenlosen oder Go-Plan bis zu Profis und Teams, die höhere Kontingente, größere Kontexte und Zusammenarbeitsfunktionen benötigen.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='de';
UPDATE tools SET description_long='ChatGPT es el asistente de chat insignia de OpenAI para escritura, codificación, investigación, análisis y tareas multimodales. Funciona en el navegador, en aplicaciones de escritorio y móviles, y a través de la API, y se ha convertido en uno de los productos de IA para consumidores más utilizados en el mundo.

A partir de julio de 2026, el modelo predeterminado es la familia GPT-5.6 — Sol, Terra y Luna — ofrecida en modos Instant y Thinking, con una variante Pro en niveles superiores. GPT-5.6 se lanzó en julio de 2026 y reemplazó la línea GPT-5.5; el selector de modelo se simplificó a Instant, Thinking y Pro. La era GPT-4o ha terminado, y GPT-4o ya no es el modelo insignia. Una familia GPT-5.6 más nueva (Sol insignia, Terra equilibrado, Luna rápido) ha entrado en vista previa limitada pero aún no está disponible al público en general.

Las capacidades cubren escritura larga y técnica, generación y depuración de código, análisis de documentos e imágenes, conversaciones de voz, navegación web, análisis de datos y generación de imágenes, todo basado en la pila GPT-5.x multimodal actual en lugar de la canalización GPT-4o más antigua. Los niveles superiores añaden ventanas de contexto más grandes y generación de video Sora.

Los precios están en niveles. Gratis es $0/mo y ahora muestra anuncios a usuarios adultos registrados en EE.UU. (desde febrero de 2026), con el modelo GPT-5.6 predeterminado con uso limitado. El nuevo nivel Go es $8/mo y se ha lanzado a nivel mundial. Plus es $20/mo. Pro ahora se divide en dos opciones: $100/mo con aproximadamente 5x cuotas de Plus, y $200/mo con aproximadamente 20x cuotas más video Sora y una ventana de contexto de 1M tokens. Business (Team) es $25/usuario/mo con un mínimo de dos asientos, y Enterprise tiene un precio personalizado.

Las limitaciones siguen siendo reales. El modelo aún puede producir respuestas confiantes pero incorrectas, el uso gratuito está limitado y ahora tiene soporte de anuncios en EE.UU., y las capacidades más útiles (contexto largo, video, cuotas altas) se encuentran detrás de los niveles más caros. GPT-5.6 es solo vista previa, por lo que no puede depender de él para producción aún.

ChatGPT es adecuado para casi cualquiera que desee un asistente de IA de propósito general, desde usuarios ocasionales en el nivel gratuito o Go hasta profesionales y equipos que necesitan cuotas más altas, contexto más grande y características de colaboración.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='es';
UPDATE tools SET description_long='ChatGPT est l''assistant de chat phare d''OpenAI pour la rédaction, la programmation, la recherche, l''analyse et les tâches multimodales. Il fonctionne dans le navigateur, dans les applications de bureau et mobile, et via l''API, et il est devenu l''un des produits d''IA grand public les plus utilisés au monde.

Depuis juillet 2026, le modèle par défaut est la famille GPT-5.6 — Sol, Terra et Luna — proposée en modes Instant et Thinking, avec une variante Pro sur les niveaux supérieurs. GPT-5.6 a été lancé en juillet 2026 et a remplacé la gamme GPT-5.5 ; le sélecteur de modèle a été simplifié à Instant, Thinking et Pro. L''ère GPT-4o est révolue, et GPT-4o n''est plus le phare. Une nouvelle famille GPT-5.6 (Sol phare, Terra équilibré, Luna rapide) est entrée en aperçu limité mais n''est pas encore généralement disponible.

Les capacités couvrent la rédaction longue et technique, la génération et le débogage de code, l''analyse de documents et d''images, les conversations vocales, la navigation web, l''analyse de données et la génération d''images, le tout basé sur la pile multimodale GPT-5.x actuelle plutôt que sur l''ancien pipeline GPT-4o. Les niveaux supérieurs ajoutent des fenêtres contextuelles plus larges et la génération vidéo Sora.

La tarification est échelonnée. Gratuit est $0/mo et affiche désormais des publicités aux utilisateurs adultes connectés aux États-Unis (depuis février 2026), avec le modèle GPT-5.6 par défaut à utilisation limitée. Le nouveau tier Go est $8/mo et s''est déployé dans le monde entier. Plus est $20/mo. Pro est maintenant divisé en deux options : $100/mo avec environ 5x les quotas Plus, et $200/mo avec environ 20x les quotas plus Sora vidéo et une fenêtre contextuelle de 1M tokens. Business (Team) est $25/user/mo avec un minimum de deux sièges, et Enterprise est au prix personnalisé.

Les limitations restent réelles. Le modèle peut toujours produire des réponses confiantes mais incorrectes, l''utilisation gratuite est limitée et soutenue par des publicités aux États-Unis, et les capacités les plus utiles (long contexte, vidéo, quotas importants) se situent derrière les tiers les plus chers. GPT-5.6 est en aperçu uniquement, vous ne pouvez donc pas en dépendre pour la production pour le moment.

ChatGPT convient à presque tous ceux qui veulent un assistant IA polyvalent, des utilisateurs occasionnels sur les tier gratuit ou Go aux professionnels et équipes qui ont besoin de quotas plus élevés, de contexte plus large et de fonctionnalités de collaboration.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='fr';
UPDATE tools SET description_long='ChatGPT é o assistente de chat principal da OpenAI para escrita, codificação, pesquisa, análise e tarefas multimodais. Funciona no navegador, em aplicativos de desktop e celular, e através da API, e se tornou um dos produtos de IA para consumidor mais amplamente utilizados do mundo.

A partir de julho de 2026, o modelo padrão é a família GPT-5.6 — Sol, Terra e Luna — oferecida nos modos Instant e Thinking, com uma variante Pro nos níveis mais altos. O GPT-5.6 foi lançado em julho de 2026 e substituiu a linha GPT-5.5; o seletor de modelo foi simplificado para Instant, Thinking e Pro. A era GPT-4o acabou, e o GPT-4o não é mais o principal. Uma família GPT-5.6 mais nova (Sol flagship, Terra balanced, Luna fast) entrou em preview limitado, mas ainda não está disponível para o público em geral.

Os recursos cobrem escrita técnica e de longa forma, geração e depuração de código, análise de documentos e imagens, conversas de voz, navegação na web, análise de dados e geração de imagens, tudo baseado no stack multimodal GPT-5.x atual em vez do pipeline GPT-4o mais antigo. Os níveis mais altos adicionam janelas de contexto maiores e geração de vídeos Sora.

Os preços são em camadas. Gratuito é $0/mo e agora mostra anúncios para usuários adultos conectados nos EUA (desde fevereiro de 2026), com o modelo GPT-5.6 padrão em uso limitado. O novo nível Go é $8/mo e foi implementado mundialmente. Plus é $20/mo. Pro agora está dividido em duas opções: $100/mo com aproximadamente 5x as cotas do Plus, e $200/mo com cerca de 20x as cotas mais vídeo Sora e uma janela de contexto de 1M-token. Business (Team) é $25/user/mo com mínimo de dois usuários, e Enterprise é com preço personalizado.

As limitações permanecem reais. O modelo ainda pode produzir respostas confiantes mas incorretas, o uso gratuito é limitado e agora com suporte a anúncios nos EUA, e os recursos mais úteis (contexto longo, vídeo, cotas pesadas) estão atrás dos níveis mais caros. O GPT-5.6 é apenas preview, então você não pode contar com ele para produção ainda.

ChatGPT é adequado para quase qualquer pessoa que deseja um assistente de IA de propósito geral, desde usuários ocasionais nos níveis gratuito ou Go até profissionais e equipes que precisam de cotas maiores, contexto maior e recursos de colaboração.', last_updated='2026-07-28' WHERE slug='chatgpt' AND lang='pt';
UPDATE tools SET description_long='GitHub Copilot started as an in-editor autocomplete tool, but the current 2026 product is a full multi-model coding platform. It lives inside your editor, in the terminal and on GitHub itself, handling code completion, chat, an agent mode that edits across files, cloud agents that work on tasks asynchronously, and automated code review.

The biggest recent change came on June 1, 2026, when Copilot moved from premium request units to consumption-based GitHub AI Credits, a token-based system. Every plan now includes a monthly credit allowance, with pay-as-you-go overages and new admin budget and spending caps. The older automatic fallback to cheaper models was discontinued, and code review now also consumes GitHub Actions minutes.

The core capabilities today are agent mode, cloud agents, chat, code review, a CLI, and the ability to pick which frontier model you want, including Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 and Gemini 3.1 Pro. Code completions and Next Edit suggestions stay included and do not draw down your credit allowance.

On pricing, individuals can choose Free at 0 dollars a month (around 2,000 completions, limited chat and agent use, automatic model selection), Pro at 10 dollars a month (unlimited completions, model selection, cloud agents, a monthly credit allowance), Pro+ at 39 dollars a month (premium frontier models including Opus and a higher allowance), or Max at 100 dollars a month (the highest allowance and priority access to new models). Verified students get Pro-level access free. Organizations pick Business at 19 dollars per user a month (including 19 dollars of monthly AI Credits) or Enterprise at 39 dollars per user a month (including 39 dollars of credits, codebase indexing and GitHub.com chat). Promotional bonus credits run June through August 2026: Business plus 30 dollars a month, Enterprise plus 70 dollars a month.

The main limitation is cost predictability: usage-based billing means heavy agent, chat or frontier-model use can push you into overages, and code review burning Actions minutes adds a second meter to watch. Budgets and caps help, but teams need to monitor consumption.

Copilot is a strong fit if you already work in GitHub and VS Code, want an agentic assistant rather than plain autocomplete, and value being able to choose the underlying model. The free tier is a low-risk way to try it, while Pro+ and Max suit heavier users of premium models.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='en';
UPDATE tools SET description_long='GitHub Copilot начинал как инструмент автодополнения в редакторе, но текущий продукт 2026 года — это полнофункциональная платформа кодирования с несколькими моделями. Она работает внутри вашего редактора, в терминале и на самом GitHub, обрабатывая автодополнение кода, чат, режим агента, редактирующий файлы, облачные агенты, которые выполняют задачи асинхронно, и автоматический анализ кода.

Самое крупное недавнее изменение произошло 1 июня 2026 года, когда Copilot перешёл с премиум-запросов на потребление GitHub AI Credits на основе токенов. Каждый план теперь включает месячное выделение кредитов с оплатой по мере использования сверх лимита и новыми функциями администраторского управления бюджетом и лимитами расходов. Старая автоматическая переоценка на более дешёвые модели была отменена, а анализ кода теперь также расходует минуты GitHub Actions.

Основные возможности на сегодняшний день — режим агента, облачные агенты, чат, анализ кода, CLI и возможность выбрать желаемую передовую модель, включая Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 и Gemini 3.1 Pro. Автодополнение кода и предложения Next Edit остаются включенными и не расходуют ваше выделение кредитов.

По ценам отдельные пользователи могут выбрать Free за 0 долларов в месяц (около 2000 автодополнений, ограниченный чат и использование агента, автоматический выбор модели), Pro за 10 долларов в месяц (неограниченное автодополнение, выбор модели, облачные агенты, месячное выделение кредитов), Pro+ за 39 долларов в месяц (премиум передовые модели включая Opus и большее выделение) или Max за 100 долларов в месяц (наибольшее выделение и приоритетный доступ к новым моделям). Проверенные студенты получают доступ уровня Pro бесплатно. Организации выбирают Business за 19 долларов на пользователя в месяц (включая 19 долларов месячных AI Credits) или Enterprise за 39 долларов на пользователя в месяц (включая 39 долларов кредитов, индексирование кодовой базы и чат на GitHub.com). Промо-кредиты действуют с июня по август 2026 года: Business плюс 30 долларов в месяц, Enterprise плюс 70 долларов в месяц.

Главное ограничение — предсказуемость стоимости: биллинг на основе использования означает, что интенсивное использование агента, чата или передовых моделей может привести к превышению лимита, а анализ кода, расходующий Actions минуты, добавляет второй счётчик для отслеживания. Бюджеты и лимиты помогают, но команды должны отслеживать потребление.

Copilot — хороший выбор, если вы уже работаете в GitHub и VS Code, хотите помощника с возможностями агента, а не просто автодополнение, и цените возможность выбрать базовую модель. Бесплатный уровень — это способ попробовать с минимальным риском, в то время как Pro+ и Max подходят для более интенсивного использования премиум-моделей.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='ru';
UPDATE tools SET description_long='GitHub Copilot почався як інструмент автозаповнення всередині редактора, але поточний продукт 2026 року — це повноцінна багатомодельна платформа кодування. Вона розташована всередині вашого редактора, в терміналі та на самому GitHub, обробляючи доповнення коду, чат, режим агента, який редагує файли, хмарні агенти, які працюють над завданнями асинхронно, та автоматизований огляд коду.

Найбільша недавня зміна сталася 1 червня 2026 року, коли Copilot перейшов від преміум-одиниць запитів до споживчих GitHub AI Credits, системи на основі токенів. Кожен план тепер включає щомісячне виділення кредитів із переплатою за додатковим використанням та новими ліміти бюджету та видатків адміністратора. Старіший автоматичний перехід на дешевші моделі було припинено, а огляд коду тепер також споживає хвилини GitHub Actions.

Основні можливості сьогодні — це режим агента, хмарні агенти, чат, огляд коду, CLI та можливість вибрати, яку передову модель ви хочете використовувати, включаючи Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 та Gemini 3.1 Pro. Доповнення коду та пропозиції Next Edit залишаються включеними й не витягують ваше виділення кредитів.

Щодо ціноутворення, фізичні особи можуть вибрати Free за 0 доларів на місяць (приблизно 2000 доповнень, обмежений чат та використання агента, автоматичний вибір моделі), Pro за 10 доларів на місяць (безлімітні доповнення, вибір моделі, хмарні агенти, щомісячне виділення кредитів), Pro+ за 39 доларів на місяць (преміум передові моделі, включаючи Opus та більше виділення) або Max за 100 доларів на місяць (найбільше виділення та пріоритетний доступ до нових моделей). Перевірені студенти отримують доступ на рівні Pro безкоштовно. Організації вибирають Business за 19 доларів за користувача на місяць (включаючи 19 доларів щомісячних AI Credits) або Enterprise за 39 доларів за користувача на місяць (включаючи 39 доларів кредитів, індексування кодової бази та GitHub.com чат). Промоційні бонусні кредити працюють червень–серпень 2026: Business плюс 30 доларів на місяць, Enterprise плюс 70 доларів на місяць.

Основне обмеження — передбачуваність вартості: біллінг на основі використання означає, що інтенсивне використання агента, чату або передової моделі може привести вас до переплати, а огляд коду, що спалює хвилини Actions, додає ще один лічильник, за яким потрібно спостерігати. Бюджети та ліміти допомагають, але команди повинні контролювати споживання.

Copilot є хорошим вибором, якщо ви вже працюєте на GitHub та VS Code, хочете агентського асистента замість простого автозаповнення та цінуєте можливість вибрати базову модель. Безплатний рівень — це безризиковий спосіб спробувати, тоді як Pro+ та Max підходять для інтенсивніших користувачів преміум-моделей.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='ua';
UPDATE tools SET description_long='GitHub Copilot התחיל כטול השלמה בעורך, אך המוצר הנוכחי של 2026 היא פלטפורמת קידוד מלאה עם מודלים מרובים. היא קיימת בעורך שלך, בטרמינל ובתוך GitHub עצמו, תוך שהיא מטפלת בהשלמת קוד, צ''אט, מצב אג''נט המערך קבצים, אג''נטים בענן שעובדים על משימות באופן אסינכרוני, וביקורת קוד אוטומטית.

השינוי הגדול ביותר לאחרונה התרחש ב-1 ביוני 2026, כאשר Copilot עבר מיחידות בקשה פרימיום לצריכה מבוססת GitHub AI Credits, מערכת מבוססת טוקנים. כל תוכנית כוללת כעת הקצאת קרדיט חודשית, עם תשלום לפי עלות וגבולות תקציב וההוצאות החדשים של מנהל. ההחזרה האוטומטית הישנה למודלים זולים יותר הופסקה, וביקורת הקוד כעת גם צורכת דקות GitHub Actions.

היכולות הליבה היום הן מצב אג''נט, אג''נטים בענן, צ''אט, ביקורת קוד, CLI, והיכולת לבחור איזה מודל גבול אתה רוצה, כולל Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 ו-Gemini 3.1 Pro. השלמות קוד והצעות Next Edit נשארות כלולות ואינן צורכות מהקצאת הקרדיט שלך.

במחירים, אנשים יכולים לבחור Free ב-0 דולר בחודש (בערך 2,000 השלמות, צ''אט ושימוש בסוכנים מוגבל, בחירת מודל אוטומטית), Pro ב-10 דולר בחודש (השלמות ללא הגבלה, בחירת מודל, אג''נטים בענן, הקצאת קרדיט חודשית), Pro+ ב-39 דולר בחודש (מודלי גבול פרימיום כולל Opus והקצאה גבוהה יותר), או Max ב-100 דולר בחודש (ההקצאה הגבוהה ביותר וגישה עדיפות למודלים חדשים). תלמידים מאומתים מקבלים גישה ברמת Pro בחינם. ארגונים בוחרים Business ב-19 דולר לכל משתמש בחודש (כולל 19 דולר של GitHub AI Credits חודשיים) או Enterprise ב-39 דולר לכל משתמש בחודש (כולל 39 דולר של קרדיטים, אינדוקס בסיס קוד וצ''אט GitHub.com). קרדיטים בונוס קידום פועלים יוני עד אוגוסט 2026: Business ועוד 30 דולר בחודש, Enterprise ועוד 70 דולר בחודש.

המגבלה הראשית היא צפיות עלויות: חיוב מבוסס שימוש משמעו שיישום כבד של אג''נט, צ''אט או מודל גבול יכול להביא אותך לתשלומים חריגים, וביקורת קוד שצורכת דקות Actions מוסיפה מטר שני לצפייה. תקציבים וגבולות עוזרים, אך הצוותים צריכים לנטר צריכה.

Copilot מתאים היטב אם אתה כבר עובד ב-GitHub ו-VS Code, רוצה סוכן מעצמות במקום השלמה פשוטה, וחוקר את היכולת לבחור את המודל הבסיסי. הטיר החינם הוא דרך בסיכון נמוך לנסות אותו, בעוד Pro+ ו-Max מתאימים למשתמשים כבדים יותר של מודלים פרימיום.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='he';
UPDATE tools SET description_long='GitHub Copilot begann als In-Editor-Autocomplete-Tool, ist aber das aktuelle Produkt von 2026 eine vollständige Multi-Model-Coding-Plattform. Sie läuft in Ihrem Editor, im Terminal und auf GitHub selbst und verwaltet Code-Completion, Chat, einen Agent-Modus, der dateienübergreifend bearbeitet, Cloud-Agents, die asynchron an Aufgaben arbeiten, und automatisierte Code-Reviews.

Die größte kürzliche Änderung kam am 1. Juni 2026, als Copilot von Premium-Request-Units zu verbrauchsbasiertem GitHub AI Credits wechselte, einem Token-basierten System. Jeder Plan enthält jetzt eine monatliche Gutschrift, mit Pay-as-you-go-Überschüssen und neuen Admin-Budget- und Ausgabenlimits. Der ältere automatische Fallback zu günstigeren Modellen wurde eingestellt, und Code-Review verbraucht nun auch GitHub Actions-Minuten.

Die Kernfunktionen heute sind Agent-Modus, Cloud-Agents, Chat, Code-Review, eine CLI und die Möglichkeit, das gewünschte Frontier-Modell auszuwählen, einschließlich Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 und Gemini 3.1 Pro. Code-Completions und Next Edit-Vorschläge bleiben enthalten und belasten nicht Ihre Gutschrift.

Bei der Preisgestaltung können Einzelpersonen zwischen Free für 0 Dollar pro Monat (etwa 2.000 Completions, eingeschränkter Chat und Agent-Nutzung, automatische Modellauswahl), Pro für 10 Dollar pro Monat (unbegrenzte Completions, Modellauswahl, Cloud-Agents, monatliche Gutschrift), Pro+ für 39 Dollar pro Monat (Premium-Frontier-Modelle einschließlich Opus und höheres Guthaben) oder Max für 100 Dollar pro Monat (höchstes Guthaben und Prioritätszugriff auf neue Modelle) wählen. Verifizierte Studenten erhalten Pro-Zugang kostenlos. Organisationen wählen Business für 19 Dollar pro Benutzer pro Monat (inklusive 19 Dollar monatliches AI Credits) oder Enterprise für 39 Dollar pro Benutzer pro Monat (inklusive 39 Dollar Credits, Codebase-Indexierung und GitHub.com-Chat). Werbebon-Gutschriften laufen Juni bis August 2026: Business plus 30 Dollar pro Monat, Enterprise plus 70 Dollar pro Monat.

Die Haupteinschränkung ist Kostenkontrolle: verbrauchsbasierte Abrechnung bedeutet, dass intensive Agent-, Chat- oder Frontier-Modellnutzung Sie in Überschüsse führen kann, und Code-Review, das Actions-Minuten verbraucht, fügt einen zweiten Messwert hinzu, den Sie überwachen müssen. Budgets und Limits helfen, aber Teams müssen den Verbrauch überwachen.

Copilot ist eine gute Wahl, wenn Sie bereits in GitHub und VS Code arbeiten, einen agentischen Assistenten anstelle von einfacher Autocomplete wünschen und es schätzen, das zugrunde liegende Modell wählen zu können. Der kostenlose Tarif ist eine risikoarme Möglichkeit, ihn auszuprobieren, während Pro+ und Max sich für intensivere Nutzer von Premium-Modellen eignen.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='de';
UPDATE tools SET description_long='GitHub Copilot comenzó como una herramienta de autocompletado en el editor, pero el producto actual de 2026 es una plataforma de codificación multi-modelo completa. Se encuentra dentro de tu editor, en la terminal y en GitHub mismo, manejando completación de código, chat, un modo agente que edita entre archivos, agentes en la nube que trabajan en tareas de forma asincrónica, y revisión de código automatizada.

El cambio más importante llegó el 1 de junio de 2026, cuando Copilot pasó de unidades de solicitud premium a GitHub AI Credits basados en consumo, un sistema basado en tokens. Todos los planes ahora incluyen una asignación mensual de créditos, con sobrecostos bajo demanda y nuevos límites de presupuesto y gasto para administradores. La antigua alternancia automática a modelos más económicos fue descontinuada, y la revisión de código ahora también consume minutos de GitHub Actions.

Las capacidades principales hoy son el modo agente, agentes en la nube, chat, revisión de código, un CLI, y la capacidad de elegir qué modelo frontera deseas, incluyendo Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 y Gemini 3.1 Pro. Las completaciones de código y las sugerencias de Next Edit siguen incluidas y no consumen tu asignación de créditos.

En cuanto a precios, los usuarios individuales pueden elegir Free a 0 dólares al mes (aproximadamente 2.000 completaciones, chat y uso de agente limitados, selección automática de modelo), Pro a 10 dólares al mes (completaciones ilimitadas, selección de modelo, agentes en la nube, asignación mensual de créditos), Pro+ a 39 dólares al mes (modelos frontera premium incluyendo Opus y una asignación más alta), o Max a 100 dólares al mes (la asignación más alta y acceso prioritario a nuevos modelos). Los estudiantes verificados obtienen acceso de nivel Pro gratis. Las organizaciones eligen Business a 19 dólares por usuario al mes (incluyendo 19 dólares en AI Credits mensuales) o Enterprise a 39 dólares por usuario al mes (incluyendo 39 dólares en créditos, indexación de base de código y chat en GitHub.com). Los créditos bonus promocionales se ejecutan de junio a agosto de 2026: Business más 30 dólares al mes, Enterprise más 70 dólares al mes.

La limitación principal es la previsibilidad de costos: la facturación basada en uso significa que el uso intensivo de agente, chat o modelos frontera puede llevarte a sobrecostos, y la revisión de código consumiendo minutos de Actions añade un segundo medidor a vigilar. Los presupuestos y límites ayudan, pero los equipos necesitan monitorear el consumo.

Copilot es una opción sólida si ya trabajas en GitHub y VS Code, deseas un asistente agentivo en lugar de autocompletado simple, y valoras poder elegir el modelo subyacente. El nivel gratuito es una forma de bajo riesgo para probarlo, mientras que Pro+ y Max son adecuados para usuarios más intensivos de modelos premium.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='es';
UPDATE tools SET description_long='GitHub Copilot a commencé comme un outil d''autocomplétion dans l''éditeur, mais le produit actuel de 2026 est une plateforme de codage multi-modèles complète. Elle existe dans votre éditeur, dans le terminal et sur GitHub lui-même, gérant la complétion de code, le chat, un mode agent qui édite sur plusieurs fichiers, des agents cloud qui travaillent sur des tâches de manière asynchrone, et l''examen automatisé du code.

Le plus grand changement récent s''est produit le 1er juin 2026, quand Copilot est passé des unités de requête premium aux GitHub AI Credits basés sur la consommation, un système basé sur les tokens. Chaque plan inclut désormais une allocation de crédits mensuelle, avec des dépassements à la carte et des nouvelles limites de budget et de dépenses pour les administrateurs. L''ancien repli automatique vers des modèles moins chers a été abandonné, et l''examen du code consomme désormais aussi des minutes GitHub Actions.

Les capacités principales aujourd''hui sont le mode agent, les agents cloud, le chat, l''examen du code, une CLI, et la possibilité de choisir quel modèle frontier vous voulez, notamment Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 et Gemini 3.1 Pro. Les complétions de code et les suggestions Next Edit restent incluses et ne consomment pas votre allocation de crédits.

Pour la tarification, les particuliers peuvent choisir Free à 0 dollars par mois (environ 2 000 complétions, chat et usage agent limités, sélection automatique du modèle), Pro à 10 dollars par mois (complétions illimitées, sélection du modèle, agents cloud, une allocation de crédits mensuelle), Pro+ à 39 dollars par mois (modèles frontier premium dont Opus et une allocation supérieure), ou Max à 100 dollars par mois (l''allocation la plus élevée et accès prioritaire aux nouveaux modèles). Les étudiants vérifiés obtiennent un accès Pro gratuitement. Les organisations choisissent Business à 19 dollars par utilisateur par mois (incluant 19 dollars de crédits IA mensuels) ou Enterprise à 39 dollars par utilisateur par mois (incluant 39 dollars de crédits, indexation de la base de code et chat GitHub.com). Les crédits bonus promotionnels s''exécutent de juin à août 2026 : Business plus 30 dollars par mois, Enterprise plus 70 dollars par mois.

La principale limitation est la prévisibilité des coûts : la facturation basée sur l''utilisation signifie que l''usage intensif d''agents, de chat ou de modèles frontier peut entraîner des dépassements, et l''examen du code qui consomme les minutes Actions ajoute un deuxième compteur à surveiller. Les budgets et les limites aident, mais les équipes doivent surveiller la consommation.

Copilot convient bien si vous travaillez déjà dans GitHub et VS Code, si vous voulez un assistant agent plutôt qu''une simple autocomplétion, et si vous valorisez la possibilité de choisir le modèle sous-jacent. L''offre gratuite est un moyen à faible risque de l''essayer, tandis que Pro+ et Max conviennent aux utilisateurs plus intensifs de modèles premium.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='fr';
UPDATE tools SET description_long='O GitHub Copilot começou como uma ferramenta de autocompletar no editor, mas o produto atual de 2026 é uma plataforma de codificação multi-modelo completa. Ele funciona dentro do seu editor, no terminal e no próprio GitHub, tratando conclusão de código, chat, um modo agent que edita entre arquivos, agentes na nuvem que trabalham em tarefas de forma assíncrona e revisão de código automatizada.

A maior mudança recente ocorreu em 1º de junho de 2026, quando o Copilot passou de unidades de solicitação premium para GitHub AI Credits baseados em consumo, um sistema baseado em tokens. Todos os planos agora incluem uma alocação mensal de créditos, com sobrecarga paga conforme o uso e novos limites de orçamento e gastos para administradores. O fallback automático anterior para modelos mais baratos foi descontinuado, e a revisão de código agora também consome minutos do GitHub Actions.

As capacidades principais hoje são modo agent, agentes na nuvem, chat, revisão de código, um CLI e a capacidade de escolher qual modelo frontier você deseja, incluindo Claude Sonnet 5, Claude Opus 4.8, GPT-5.5 e Gemini 3.1 Pro. As conclusões de código e sugestões Next Edit continuam incluídas e não reduzem sua alocação de créditos.

Em relação aos preços, indivíduos podem escolher Free a 0 dólares por mês (cerca de 2.000 conclusões, chat e uso de agent limitados, seleção automática de modelo), Pro a 10 dólares por mês (conclusões ilimitadas, seleção de modelo, agentes na nuvem, alocação mensal de créditos), Pro+ a 39 dólares por mês (modelos frontier premium incluindo Opus e alocação maior) ou Max a 100 dólares por mês (a alocação mais alta e acesso prioritário a novos modelos). Estudantes verificados recebem acesso em nível Pro gratuitamente. Organizações escolhem Business a 19 dólares por usuário por mês (incluindo 19 dólares de AI Credits mensais) ou Enterprise a 39 dólares por usuário por mês (incluindo 39 dólares de créditos, indexação de base de código e chat GitHub.com). Créditos bônus promocionais funcionam de junho a agosto de 2026: Business mais 30 dólares por mês, Enterprise mais 70 dólares por mês.

A principal limitação é a previsibilidade de custos: faturamento baseado em uso significa que o uso pesado de agent, chat ou modelo frontier pode gerar sobrecarga, e a revisão de código consumindo minutos do Actions adiciona um segundo medidor para monitorar. Orçamentos e limites ajudam, mas as equipes precisam monitorar o consumo.

O Copilot é uma ótima opção se você já trabalha no GitHub e VS Code, deseja um assistente agentic em vez de autocompletar simples e valoriza a capacidade de escolher o modelo subjacente. O tier gratuito é uma forma de baixo risco de testá-lo, enquanto Pro+ e Max são adequados para usuários mais pesados de modelos premium.', last_updated='2026-07-28' WHERE slug='github-copilot' AND lang='pt';
UPDATE tools SET description_long='Microsoft Copilot is the AI assistant Microsoft has woven across Windows, Edge, Bing, and the Microsoft 365 apps. It handles conversational chat, web search with cited answers, image generation, document drafting, and in the paid tiers it works directly inside Word, Excel, PowerPoint, and Outlook.

The biggest recent change is the model. Copilot has moved onto the GPT-5.6 family, now the preferred model in Microsoft 365 Copilot. GPT-5.6 became the default in the October-November 2025 rollout, GPT-5.4 Thinking reached Microsoft 365 Copilot in March 2026, and GPT-5.6 rolled out in July 2026 as the preferred model. Copilot Chat added GPT-5.2 with an Auto/Instant/Thinking selector, and Anthropic''s Claude models (Sonnet 4.5/4.6 and Opus) are now selectable inside Copilot too.

Day to day you get Smart mode and Think Deeper for harder questions, voice conversations, web search that returns answers with citations, and roughly 15 image-generation boosts per day on the free tier. July 2026 also added AI-content watermarking and a rebuilt Copilot Notebooks experience that reached general availability.

Pricing splits into consumer and business. Copilot Free costs nothing and covers chat with the latest GPT models when capacity allows, cited web search, Think Deeper, voice, and the daily image boosts. Microsoft 365 Personal (about $9.99/mo) and Family (about $12.99/mo) raise Copilot usage limits. Microsoft 365 Premium at $19.99/mo replaced the retired standalone Copilot Pro and adds the highest consumer limits, Copilot inside the Office apps, Designer, and up to 6 TB of storage.

For organizations, the Microsoft 365 Copilot add-on is $18.00/user/mo on an annual promo (down from $21) or $25.20 monthly; Business Standard with Copilot runs $23.50 yearly, Business Premium with Copilot $32.00 yearly, and the enterprise add-on lands around $30/user/mo. Copilot Studio for building custom agents is $200/mo. Note the standalone Copilot Pro was sunset in late 2025 and existing subscriptions only work until August 1, 2026.

The main limitations: the free tier throttles priority model access to when capacity allows and caps image generation, the strongest features are tied to a Microsoft 365 subscription, and the tiering across consumer, business, and enterprise SKUs is genuinely confusing. Copilot makes the most sense if you already live in Microsoft 365 and want an assistant that reaches into your documents, mail, and calendar rather than a standalone chatbot.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='en';
UPDATE tools SET description_long='Microsoft Copilot — это AI-помощник, который Microsoft интегрировал в Windows, Edge, Bing и приложения Microsoft 365. Он обрабатывает диалоговый чат, веб-поиск с цитируемыми ответами, генерацию изображений, создание документов, а в платных тарифах работает непосредственно внутри Word, Excel, PowerPoint и Outlook.

Самое большое недавнее изменение — модель. Copilot перешёл на семейство GPT-5.6, теперь предпочтительную модель в Microsoft 365 Copilot. GPT-5.6 стал стандартом при развёртывании октября-ноября 2025 года, GPT-5.4 Thinking поступил в Microsoft 365 Copilot в марте 2026 года, а GPT-5.6 был развёрнут в июле 2026 года как предпочтительная модель. Copilot Chat добавил GPT-5.2 с селектором Auto/Instant/Thinking, а модели Claude компании Anthropic (Sonnet 4.5/4.6 и Opus) теперь также доступны для выбора внутри Copilot.

В повседневной работе вы получаете режим Smart mode и Think Deeper для сложных вопросов, голосовые беседы, веб-поиск с цитируемыми ответами и примерно 15 ускорений генерации изображений в день на бесплатном тарифе. В июле 2026 года также добавлены водяной знак AI-контента и обновлённый интерфейс Copilot Notebooks, достигший общей доступности.

Ценообразование разделено на потребительский и бизнес-сегменты. Copilot Free стоит ничего и включает чат с последними моделями GPT при наличии мощности, веб-поиск с цитированием, Think Deeper, голос и ежедневные ускорения изображений. Microsoft 365 Personal (примерно $9.99/мес) и Family (примерно $12.99/мес) увеличивают лимиты использования Copilot. Microsoft 365 Premium стоимостью $19.99/мес заменил снятый с продажи автономный Copilot Pro и добавляет максимальные потребительские лимиты, Copilot внутри приложений Office, Designer и до 6 ТБ хранилища.

Для организаций надстройка Microsoft 365 Copilot стоит $18.00/пользователь/мес при годовой акции (снижено с $21) или $25.20 ежемесячно; Business Standard с Copilot обходится в $23.50 в год, Business Premium с Copilot — $32.00 в год, а корпоративная надстройка составляет около $30/пользователь/мес. Copilot Studio для создания пользовательских агентов стоит $200/мес. Учтите, что автономный Copilot Pro был снят с продажи в конце 2025 года и существующие подписки работают только до 1 августа 2026 года.

Основные ограничения: бесплатный тариф ограничивает приоритетный доступ к модели при наличии мощности и ограничивает генерацию изображений, самые сильные функции привязаны к подписке Microsoft 365, а структура тарифов на потребительский, бизнес и корпоративный SKU действительно запутана. Copilot имеет наибольший смысл, если вы уже используете Microsoft 365 и хотите помощника, который имеет доступ к вашим документам, почте и календарю, а не просто автономный чатбот.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='ru';
UPDATE tools SET description_long='Microsoft Copilot — це AI-помічник, який Microsoft інтегрував у Windows, Edge, Bing та додатки Microsoft 365. Він обробляє діалогові чати, пошук у веб з цитуванням відповідей, генерацію зображень, підготовку документів, а в платних тарифах працює безпосередньо у Word, Excel, PowerPoint та Outlook.

Найбільша недавня зміна — це модель. Copilot перейшов на сімейство GPT-5.6, яке тепер є переважною моделлю в Microsoft 365 Copilot. GPT-5.6 став стандартом за розгортання в жовтні-листопаді 2025 року, GPT-5.4 Thinking з''явився в Microsoft 365 Copilot у березні 2026 року, а GPT-5.6 розгорнувся в липні 2026 року як переважна модель. Copilot Chat додав GPT-5.2 з селектором Auto/Instant/Thinking, а моделі Anthropic Claude (Sonnet 4.5/4.6 та Opus) тепер також можна обирати у Copilot.

У повсякденному використанні ви отримуєте Smart режим та Think Deeper для складніших запитань, голосові розмови, пошук у веб з цитуванням відповідей та приблизно 15 посилень генерації зображень на день на безплатному тарифі. У липні 2026 року також додали водяний знак AI-контенту та перебудований досвід Copilot Notebooks, який досяг загальної доступності.

Ціноутворення розділяється на споживчий та бізнес-сегменти. Copilot Free коштує нічого й охоплює чат з останніми GPT-моделями при наявності ємності, пошук у веб з цитуванням, Think Deeper, голос та щоденні посилення зображень. Microsoft 365 Personal (близько $9.99/міс.) та Family (близько $12.99/міс.) підвищують ліміти використання Copilot. Microsoft 365 Premium за $19.99/міс. замінив знятий з виробництва самостійний Copilot Pro та додає найвищі споживчі ліміти, Copilot всередині додатків Office, Designer та до 6 TB сховища.

Для організацій надбудова Microsoft 365 Copilot коштує $18.00/користувач/міс. за річною промоакцією (знижено з $21) або $25.20 щомісячно; Business Standard з Copilot — $23.50 щорічно, Business Premium з Copilot — $32.00 щорічно, а додаток для підприємства коштує близько $30/користувач/міс. Copilot Studio для створення власних агентів — $200/міс. Зверніть увагу, що самостійний Copilot Pro був припинений в кінці 2025 року, а існуючі підписки працюватимуть тільки до 1 серпня 2026 року.

Основні обмеження: безплатний тариф обмежує доступ до пріоритетної моделі залежно від наявності ємності та обмежує генерацію зображень, найпотужніші функції пов''язані з підпискою Microsoft 365, а розподіл тарифів за споживчим, бізнес-сегментом і корпоративними SKU дійсно заплутаний. Copilot має найбільше сенсу, якщо ви вже користуєтесь Microsoft 365 і хочете помічника, який отримує доступ до ваших документів, пошти та календаря, а не самостійного чат-бота.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='ua';
UPDATE tools SET description_long='Microsoft Copilot הוא עוזר AI שמיקרוסופט שילבה ב-Windows, Edge, Bing ובאפליקציות Microsoft 365. הוא מטפל בשיחות שיחה, חיפוש באינטרנט עם תשובות מצוטטות, יצירת תמונות, עריכת מסמכים, ובשכבות משלם הוא עובד ישירות ב-Word, Excel, PowerPoint ו-Outlook.

השינוי הגדול ביותר לאחרונה הוא הדגם. Copilot עבר לקבוצת GPT-5.6, כעת הדגם המעדיף ב-Microsoft 365 Copilot. GPT-5.6 הפך לברירת המחדל בהטלת אוקטובר-נובמבר 2025, GPT-5.4 Thinking הגיע ל-Microsoft 365 Copilot במרץ 2026, ו-GPT-5.6 הוצא בהנפקה ביולי 2026 כדגם המעדיף. Copilot Chat הוסיף GPT-5.2 עם בוחר Auto/Instant/Thinking, וגם דגמי Claude של Anthropic (Sonnet 4.5/4.6 ו-Opus) ניתנים לבחירה כעת בתוך Copilot.

ביומיום אתה מקבל Smart mode ו-Think Deeper לשאלות קשות יותר, שיחות קוליות, חיפוש באינטרנט המחזיר תשובות עם ציטוטים, וכ-15 דחיפות ליצירת תמונות ביום בשכבה החינמית. יולי 2026 הוסיף גם סימון AI-content וחוויית Copilot Notebooks שנבנתה מחדש שהגיעה לזמינות כללית.

התמחור מתחלק לצרכן וביזנס. Copilot Free עולה אפס וכולל שיחה עם דגמי GPT העדכניים ביותר כאשר הקיבולת מאפשרת, חיפוש באינטרנט מצוטט, Think Deeper, קול, והדחיפות היומיות של תמונות. Microsoft 365 Personal (בערך $9.99/mo) ו-Family (בערך $12.99/mo) מעלים את גבולות השימוש ב-Copilot. Microsoft 365 Premium ב-$19.99/mo החליפה את ה-Copilot Pro העצמאי שפרש וממוסד את גבולות הצרכן הגבוהים ביותר, Copilot בתוך אפליקציות ה-Office, Designer, ועד 6 TB של אחסון.

לארגונים, תוסף Microsoft 365 Copilot הוא $18.00/user/mo בתעריף שנתי מקדמי (ירד מ-$21) או $25.20 חודשי; Business Standard עם Copilot עולה $23.50 בשנה, Business Premium עם Copilot $32.00 בשנה, ותוסף הארגון נחת סביב $30/user/mo. Copilot Studio ליצירת סוכנים מותאמים אישית הוא $200/mo. שים לב ש-Copilot Pro העצמאי הושקע בסוף 2025 והרשומות הקיימות פועלות רק עד 1 באוגוסט 2026.

ההגבלות העיקריות: השכבה החינמית מעכבת את גישת דגם עדיפות כאשר הקיבולת מאפשרת וקופצת יצירת תמונות, התכונות החזקות ביותר קשורות למנוי Microsoft 365, והשכבות על פני SKU של צרכן, ביזנס וארגון באמת מבלבלים. Copilot הגיוני ביותר אם אתה כבר חי ב-Microsoft 365 ורוצה עוזר שמגיע למסמכים, דואר ולוח השנה שלך במקום chatbot עצמאי.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='he';
UPDATE tools SET description_long='Microsoft Copilot ist der KI-Assistent, den Microsoft in Windows, Edge, Bing und die Microsoft 365-Apps integriert hat. Er beherrscht Konversations-Chat, Web-Suche mit zitierten Antworten, Bildgenerierung, Dokumentenerstellung und funktioniert in den kostenpflichtigen Versionen direkt in Word, Excel, PowerPoint und Outlook.

Die größte jüngste Änderung ist das Modell. Copilot ist zur GPT-5.6-Familie übergegangen, jetzt das bevorzugte Modell in Microsoft 365 Copilot. GPT-5.6 wurde im Oktober-November 2025 zum Standard, GPT-5.4 Thinking erreichte Microsoft 365 Copilot im März 2026, und GPT-5.6 wurde im Juli 2026 als bevorzugtes Modell ausgerollt. Copilot Chat erhielt GPT-5.2 mit einem Auto/Instant/Thinking-Selector, und die Claude-Modelle von Anthropic (Sonnet 4.5/4.6 und Opus) sind jetzt auch in Copilot wählbar.

Im täglichen Gebrauch gibt es Smart Mode und Think Deeper für schwierigere Fragen, Sprachkonversationen, Web-Suche, die Antworten mit Zitaten liefert, und ungefähr 15 Bildgenerations-Boosts pro Tag in der kostenlosen Version. Im Juli 2026 kamen auch KI-Content-Watermarking und ein neu aufgebautes Copilot Notebooks-Erlebnis hinzu, das allgemeine Verfügbarkeit erreichte.

Die Preisgestaltung ist unterteilt in Consumer und Business. Copilot Free kostet nichts und umfasst Chat mit den neuesten GPT-Modellen bei verfügbarer Kapazität, zitierte Web-Suche, Think Deeper, Sprache und die täglichen Bildgenerations-Boosts. Microsoft 365 Personal (etwa $9.99/Mo) und Family (etwa $12.99/Mo) erhöhen die Copilot-Nutzungsgrenzen. Microsoft 365 Premium für $19.99/Mo ersetzte das eingestellte standalone Copilot Pro und bietet die höchsten Consumer-Grenzen, Copilot in den Office-Apps, Designer und bis zu 6 TB Speicher.

Für Organisationen kostet das Microsoft 365 Copilot Add-on $18.00/Nutzer/Mo bei jährlicher Promotion (reduziert von $21) oder $25.20 monatlich; Business Standard mit Copilot kostet $23.50 jährlich, Business Premium mit Copilot $32.00 jährlich, und das Enterprise Add-on kostet etwa $30/Nutzer/Mo. Copilot Studio zum Erstellen benutzerdefinierter Agenten kostet $200/Mo. Beachten Sie, dass das standalone Copilot Pro Ende 2025 eingestellt wurde und bestehende Abonnements nur bis zum 1. August 2026 funktionieren.

Die Hauptbeschränkungen: Die kostenlose Version drosselt den Zugriff auf Priority-Modelle auf Kapazitätsverfügbarkeit und begrenzt die Bildgenerierung, die stärksten Features sind an ein Microsoft 365-Abonnement gebunden, und die Abstufung über Consumer-, Business- und Enterprise-SKUs ist wirklich verwirrend. Copilot ist am sinnvollsten, wenn Sie bereits in Microsoft 365 tätig sind und einen Assistenten möchten, der in Ihre Dokumente, E-Mails und Kalender reicht, anstatt eines standalone Chatbots.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='de';
UPDATE tools SET description_long='Microsoft Copilot es el asistente de IA que Microsoft ha integrado en Windows, Edge, Bing y las aplicaciones de Microsoft 365. Maneja chat conversacional, búsqueda web con respuestas citadas, generación de imágenes, redacción de documentos, y en los planes de pago funciona directamente dentro de Word, Excel, PowerPoint y Outlook.

El cambio más reciente importante es el modelo. Copilot ha pasado a la familia GPT-5.6, ahora el modelo preferido en Microsoft 365 Copilot. GPT-5.6 se convirtió en el predeterminado en el despliegue de octubre-noviembre de 2025, GPT-5.4 Thinking llegó a Microsoft 365 Copilot en marzo de 2026, y GPT-5.6 se desplegó en julio de 2026 como el modelo preferido. Copilot Chat agregó GPT-5.2 con un selector Auto/Instant/Thinking, y los modelos Claude de Anthropic (Sonnet 4.5/4.6 y Opus) ahora también son seleccionables dentro de Copilot.

En el día a día obtienes modo Smart y Think Deeper para preguntas más difíciles, conversaciones de voz, búsqueda web que devuelve respuestas con citas, y aproximadamente 15 impulsos de generación de imágenes por día en el plan gratuito. Julio de 2026 también agregó marcas de agua de contenido de IA y una experiencia reconstruida de Copilot Notebooks que llegó a disponibilidad general.

Los precios se dividen en consumidor y empresarial. Copilot Free no cuesta nada e incluye chat con los últimos modelos GPT cuando la capacidad lo permite, búsqueda web citada, Think Deeper, voz e impulsos de imagen diarios. Microsoft 365 Personal (aproximadamente $9.99/mes) y Family (aproximadamente $12.99/mes) aumentan los límites de uso de Copilot. Microsoft 365 Premium a $19.99/mes reemplazó al Copilot Pro independiente descontinuado y agrega los límites de consumidor más altos, Copilot dentro de las aplicaciones de Office, Designer y hasta 6 TB de almacenamiento.

Para organizaciones, el complemento Microsoft 365 Copilot es $18.00/usuario/mes en una promoción anual (reducido de $21) o $25.20 mensuales; Business Standard con Copilot cuesta $23.50 anuales, Business Premium con Copilot $32.00 anuales, y el complemento empresarial ronda los $30/usuario/mes. Copilot Studio para crear agentes personalizados cuesta $200/mes. Ten en cuenta que Copilot Pro independiente se descontinuó a finales de 2025 y las suscripciones existentes solo funcionan hasta el 1 de agosto de 2026.

Las limitaciones principales: el plan gratuito restringe el acceso al modelo de prioridad cuando la capacidad lo permite y limita la generación de imágenes, las características más potentes están vinculadas a una suscripción de Microsoft 365, y la estratificación entre SKU de consumidor, empresarial y empresa es genuinamente confusa. Copilot tiene más sentido si ya vives en Microsoft 365 y quieres un asistente que acceda a tus documentos, correo y calendario en lugar de un chatbot independiente.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='es';
UPDATE tools SET description_long='Microsoft Copilot est l''assistant IA que Microsoft a intégré dans Windows, Edge, Bing et les applications Microsoft 365. Il gère les conversations, la recherche web avec réponses citées, la génération d''images, la rédaction de documents, et dans les offres payantes, il fonctionne directement dans Word, Excel, PowerPoint et Outlook.

Le plus grand changement récent concerne le modèle. Copilot a migré vers la famille GPT-5.6, désormais le modèle préféré dans Microsoft 365 Copilot. GPT-5.6 est devenu le modèle par défaut lors du déploiement d''octobre-novembre 2025, GPT-5.4 Thinking a atteint Microsoft 365 Copilot en mars 2026, et GPT-5.6 a été déployé en juillet 2026 en tant que modèle préféré. Copilot Chat a ajouté GPT-5.2 avec un sélecteur Auto/Instant/Thinking, et les modèles Claude d''Anthropic (Sonnet 4.5/4.6 et Opus) sont désormais sélectionnables dans Copilot également.

Au quotidien, vous disposez du mode Smart et de Think Deeper pour les questions difficiles, des conversations vocales, de la recherche web qui retourne des réponses avec citations, et d''environ 15 accélérations de génération d''images par jour sur l''offre gratuite. Juillet 2026 a également ajouté un filigrane de contenu IA et une expérience Copilot Notebooks reconstruite qui a atteint la disponibilité générale.

La tarification se divise entre les consommateurs et les entreprises. Copilot Free est gratuit et couvre les conversations avec les derniers modèles GPT selon la capacité disponible, la recherche web citée, Think Deeper, la voix et les accélérations d''images quotidiennes. Microsoft 365 Personal (environ $9.99/mo) et Family (environ $12.99/mo) augmentent les limites d''utilisation de Copilot. Microsoft 365 Premium à $19.99/mo a remplacé l''ancienne offre Copilot Pro autonome et ajoute les limites les plus élevées pour les consommateurs, Copilot dans les applications Office, Designer et jusqu''à 6 TB de stockage.

Pour les organisations, l''add-on Microsoft 365 Copilot coûte $18.00/utilisateur/mo en promotion annuelle (réduit de $21) ou $25.20 mensuels ; Business Standard avec Copilot coûte $23.50 par an, Business Premium avec Copilot $32.00 par an, et l''add-on entreprise coûte environ $30/utilisateur/mo. Copilot Studio pour construire des agents personnalisés coûte $200/mo. Notez que l''offre Copilot Pro autonome a été abandonnée fin 2025 et les abonnements existants ne fonctionnent que jusqu''au 1er août 2026.

Les principales limitations : l''offre gratuite limite l''accès aux modèles prioritaires selon la capacité disponible et plafonné la génération d''images, les fonctionnalités les plus puissantes sont liées à un abonnement Microsoft 365, et la tarification entre les SKU consommateur, entreprise et entreprise est véritablement confuse. Copilot est plus judicieux si vous vivez déjà dans Microsoft 365 et souhaitez un assistant qui accède à vos documents, e-mails et calendrier plutôt qu''un simple chatbot autonome.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='fr';
UPDATE tools SET description_long='Microsoft Copilot é o assistente de IA que a Microsoft integrou ao Windows, Edge, Bing e aos aplicativos do Microsoft 365. Ele realiza bate-papo conversacional, busca na web com respostas citadas, geração de imagens, redação de documentos, e nas camadas pagas funciona diretamente dentro do Word, Excel, PowerPoint e Outlook.

A maior mudança recente é o modelo. O Copilot evoluiu para a família GPT-5.6, agora o modelo preferido no Microsoft 365 Copilot. O GPT-5.6 se tornou o padrão no lançamento de outubro-novembro de 2025, o GPT-5.4 Thinking chegou ao Microsoft 365 Copilot em março de 2026, e o GPT-5.6 foi lançado em julho de 2026 como o modelo preferido. O Copilot Chat adicionou o GPT-5.2 com um seletor Auto/Instant/Thinking, e os modelos Claude da Anthropic (Sonnet 4.5/4.6 e Opus) agora também são selecionáveis dentro do Copilot.

No dia a dia você tem o modo Smart e Think Deeper para perguntas mais difíceis, conversas por voz, busca na web que retorna respostas com citações, e aproximadamente 15 impulsionadores de geração de imagens por dia na camada gratuita. Julho de 2026 também adicionou marca d''água de conteúdo de IA e uma experiência reconstruída do Copilot Notebooks que atingiu disponibilidade geral.

O preço se divide entre consumidor e negócios. Copilot Free não custa nada e inclui bate-papo com os últimos modelos GPT quando a capacidade permite, busca na web com citações, Think Deeper, voz e os impulsionadores diários de imagens. Microsoft 365 Personal (cerca de $9.99/mês) e Family (cerca de $12.99/mês) aumentam os limites de uso do Copilot. Microsoft 365 Premium a $19.99/mês substituiu o Copilot Pro independente descontinuado e adiciona os limites mais altos para consumidor, Copilot dentro dos aplicativos do Office, Designer e até 6 TB de armazenamento.

Para organizações, o complemento Microsoft 365 Copilot é $18.00/usuário/mês em promoção anual (reduzido de $21) ou $25.20 mensal; Business Standard com Copilot custa $23.50 anual, Business Premium com Copilot $32.00 anual, e o complemento corporativo chega a cerca de $30/usuário/mês. Copilot Studio para criar agentes personalizados é $200/mês. Note que o Copilot Pro independente foi descontinuado no final de 2025 e as assinaturas existentes funcionam apenas até 1º de agosto de 2026.

As principais limitações: a camada gratuita reduz o acesso ao modelo prioritário quando a capacidade permite e limita a geração de imagens, os recursos mais fortes estão vinculados a uma assinatura do Microsoft 365, e o escalonamento entre SKUs de consumidor, negócios e empresa é genuinamente confuso. Copilot faz mais sentido se você já vive no Microsoft 365 e quer um assistente que acesse seus documentos, e-mail e calendário em vez de um chatbot independente.', last_updated='2026-07-28' WHERE slug='microsoft-copilot' AND lang='pt';
UPDATE tools SET description_long='Perplexity is a conversational search tool that answers questions with cited, up-to-date sources instead of a list of links. It sits somewhere between a chatbot and a search engine, and over 2026 it has leaned hard into research and agentic work.

The headline change is Advanced Deep Research. It is no longer a simple multi-page report mode: it now runs agentically inside Perplexity Computer, asks clarifying questions before it starts, accepts follow-ups mid-run, and shows live source and progress tracking. On Pro and Max, Deep Research is powered by Claude Opus 4.7 and Sonnet 4.6, and Perplexity reports state-of-the-art benchmark scores (93.9% on SimpleQA, 21.1% on Humanity''s Last Exam). The Deep Research in Computer agentic assistant shipped on June 19, 2026, adding a command panel, thread forking, inline actions, analytics APIs, and enterprise credit controls.

Beyond research, Perplexity gives you multi-model access to the GPT-5.6 family, Claude Opus 5, Gemini and other frontier models, a Model Council feature that compares several models side by side, and the Comet browser for AI-assisted browsing.

Pricing runs across five tiers. Free is $0 and includes roughly 5 Pro searches per day. Pro is $20/mo or $200/yr, bundles $5/mo of Sonar API credits, and allows about 20 Deep Research runs a day. The new Max tier is $200/mo or $2,000/yr and adds Model Council, 10,000 Computer credits a month, Sora 2 Pro video and Nano Banana Pro image generation, and unlimited Labs. Students get Pro for around $10/mo, and there are Enterprise Pro (~$40/seat/mo) and Enterprise Max (~$325/seat/mo) plans.

The limitations are worth knowing. Like any AI system it can still misread or over-trust weak sources, so citations need checking. The most capable features sit behind the $200/mo Max tier and a monthly Computer credit budget, the free tier is quite tight, and juggling multiple models plus Model Council adds a learning curve.

Perplexity is a strong pick if you do a lot of source-backed research, want agentic Deep Research on top-tier models, or like comparing several AI models on the same question. Casual users who just need a few answers a day can stay on Free, while heavy or enterprise users will find the paid tiers built around them.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='en';
UPDATE tools SET description_long='Perplexity — это инструмент для поиска в диалоговом режиме, который отвечает на вопросы со ссылками на актуальные источники вместо простого списка ссылок. Он находится где-то между чат-ботом и поисковой системой, и на протяжении 2026 года сделал упор на исследовательскую работу и агентивные функции.

Главное изменение — Advanced Deep Research. Это уже не простой многостраничный режим отчётов: теперь он работает агентивно внутри Perplexity Computer, задаёт уточняющие вопросы перед началом, принимает дополнения во время выполнения и показывает отслеживание источников и прогресса в реальном времени. На Pro и Max тарифах Deep Research работает на Claude Opus 4.7 и Sonnet 4.6, и Perplexity заявляет передовые результаты в бенчмарках (93,9% на SimpleQA, 21,1% на Humanity''s Last Exam). Агентивный помощник Deep Research в Computer был запущен 19 июня 2026 года, добавив панель команд, ветвление потоков, встроенные действия, API аналитики и контроль корпоративных кредитов.

Помимо исследований, Perplexity предоставляет многомодельный доступ к семейству GPT-5.6, Claude Opus 5, Gemini и другим передовым моделям, функцию Model Council для сравнения нескольких моделей рядом и браузер Comet для поиска с поддержкой ИИ.

Ценообразование охватывает пять уровней. Free стоит $0 и включает примерно 5 Pro-поисков в день. Pro стоит $20/мес или $200/год, включает $5/мес кредитов Sonar API и позволяет примерно 20 запусков Deep Research в день. Новый уровень Max стоит $200/мес или $2,000/год и добавляет Model Council, 10 000 кредитов Computer в месяц, видеогенерацию Sora 2 Pro и генерацию изображений Nano Banana Pro, а также неограниченный Labs. Студенты получают Pro примерно за $10/мес, а также доступны планы Enterprise Pro (~$40/место/мес) и Enterprise Max (~$325/место/мес).

Ограничения стоит учитывать. Как и любая система ИИ, она может неправильно прочитать или чрезмерно доверять слабым источникам, поэтому цитаты требуют проверки. Наиболее мощные функции доступны только на тарифе Max за $200/мес и при условии ежемесячного бюджета кредитов Computer, Free-уровень довольно ограничен, а работа с несколькими моделями плюс Model Council требует кривой обучения.

Perplexity — это отличный выбор, если вы занимаетесь много исследованиями с опорой на источники, хотите агентивный Deep Research на моделях верхнего уровня или любите сравнивать несколько ИИ-моделей на один и тот же вопрос. Случайные пользователи, которым нужно всего несколько ответов в день, могут остаться на Free, в то время как активные или корпоративные пользователи найдут платные уровни, созданные специально для них.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='ru';
UPDATE tools SET description_long='Perplexity — це інструмент для конверсаційного пошуку, який відповідає на запитання з посиланнями на актуальні джерела замість списку посилань. Він займає проміжне місце між чат-ботом і пошуковою системою, а протягом 2026 року він активно розвивався в напрямку дослідницької роботи та агентного функціоналу.

Найголовніша зміна — Advanced Deep Research. Це більше не простий багатосторінковий режим звіту: тепер він працює агентно всередину Perplexity Computer, ставить уточнювальні запитання перед початком, приймає уточнення під час роботи та показує живе відстеження джерел і прогресу. На Pro та Max, Deep Research розраховується на Claude Opus 4.7 і Sonnet 4.6, а Perplexity повідомляє про найсучасніші результати бенчмарків (93.9% на SimpleQA, 21.1% на Humanity''s Last Exam). Deep Research в Computer агентному помічнику був випущений 19 червня 2026 року з панеллю команд, розгалуженням потоків, вбудованими діями, API аналітики та контролем корпоративних кредитів.

Окрім дослідження, Perplexity надає вам багатомодельний доступ до сімейства GPT-5.6, Claude Opus 5, Gemini та інших передових моделей, функцію Model Council, яка порівнює кілька моделей поруч, та браузер Comet для AI-допоміжного перегляду.

Ціни розраховані на п''ять рівнів. Free коштує $0 і включає приблизно 5 Pro пошуків на день. Pro коштує $20/місяць або $200/рік, включає $5/місяць кредитів Sonar API та дозволяє близько 20 прогонів Deep Research на день. Новий рівень Max коштує $200/місяць або $2,000/рік і додає Model Council, 10,000 Computer кредитів на місяць, Sora 2 Pro для відео та Nano Banana Pro для генерації зображень, а також необмежений Labs. Студенти отримують Pro приблизно за $10/місяць, і існують плани Enterprise Pro (~$40/місяць за користувача) та Enterprise Max (~$325/місяць за користувача).

Обмеження варто знати. Як і будь-яка система штучного інтелекту, вона все ще може неправильно прочитати або надмірно довіритися слабким джерелам, тому цитування потребують перевірки. Найбільш здатні функції знаходяться за рівнем Max за $200/місяць та щомісячним бюджетом Computer кредитів, безплатний рівень доволі обмежений, а жонглювання кількома моделями плюс Model Council додає крутої кривої навчання.

Perplexity — це чудовий вибір, якщо ви багато займаєтесь дослідженням з посиланнями на джерела, хочете агентне Deep Research на найкращих моделях або вам подобається порівнювати кілька AI моделей на одному й тому ж запитанні. Випадкові користувачі, яким потрібна лише кілька відповідей на день, можуть залишатися на Free, тоді як активні або корпоративні користувачі знайдуть платні рівні, розраховані на них.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='ua';
UPDATE tools SET description_long='Perplexity הוא כלי חיפוש שיח שמענה על שאלות עם מקורות מצוטטים ומעודכנים במקום רשימת קישורים. הוא נמצא איפשהו בין chatbot לבין מנוע חיפוש, וחלף על פני 2026 הוא התמקד בחוזקה בעבודת מחקר ועבודה agentive.

השינוי המרכזי הוא Advanced Deep Research. זה כבר לא מצב דוח רב-עמודי פשוט: כעת הוא פועל agentively בתוך Perplexity Computer, שואל שאלות הבהרה לפני תחילת ההרצה, קובל עדכונים באמצע ההרצה, ומציג מעקב חי של מקורות והתקדמות. ב-Pro וב-Max, Deep Research מופעל על ידי Claude Opus 4.7 ו-Sonnet 4.6, וPerplexity מדווחת על ניקוד benchmark מתקדם ביותר (93.9% ב-SimpleQA, 21.1% ב-Humanity''s Last Exam). ה-Deep Research ב-Computer agentic assistant הושק ב-19 ביוני 2026, והוסיף לוח פקודות, שיתופי חוטים, פעולות inline, APIs analytics, וקontrol אשראי ארגוני.

מעבר למחקר, Perplexity נותן לך גישה לmulti-model ל-משפחת GPT-5.6, Claude Opus 5, Gemini וmodels frontier אחרים, תכונת Model Council המשווה כמה models זה לצד זה, והדפדפן Comet לעיון בעזרת AI.

התמחור משתרע על פני חמש שכבות. Free הוא $0 וכולל בערך 5 Pro searches ליום. Pro הוא $20/mo או $200/yr, מכריז $5/mo של Sonar API credits, ומאפשר בערך 20 Deep Research runs ליום. השכבה החדשה Max היא $200/mo או $2,000/yr ומוסיפה Model Council, 10,000 Computer credits חודשיים, Sora 2 Pro video ו-Nano Banana Pro image generation, ו-unlimited Labs. סטודנטים מקבלים Pro בערך ב-$10/mo, וישנם תוכניות Enterprise Pro (~$40/seat/mo) ו-Enterprise Max (~$325/seat/mo).

הגבלות ראוי להכיר. כמו כל מערכת AI היא עדיין יכולה לתגובת קריאה שגויה או להאמין יתר על מידה למקורות חלשים, כך שהציטוטים זקוקים לבדיקה. התכונות הכי מסוגלות יושבות מאחורי $200/mo Max tier ותקציב חודשי של Computer credits, ה-free tier הוא די צר, וניהול דוקדוק של modelers מרובים בתוספת Model Council מוסיף עקומת למידה.

Perplexity הוא בחירה חזקה אם אתה עושה הרבה מחקר תומך במקורות, רוצה Deep Research agentive על modelers מדרגה ראשונה, או אוהב להשוות כמה modelers AI על אותה שאלה. משתמשים casual שרק צריכים כמה תשובות ביום יכולים להישאר ב-Free, בעוד משתמשים כבדים או ארגוניים ימצאו את ה-paid tiers בנויים סביבם.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='he';
UPDATE tools SET description_long='Perplexity ist ein conversational Search Tool, das Fragen mit zitierten, aktuellen Quellen beantwortet statt eine Liste von Links anzuzeigen. Es sitzt irgendwo zwischen einem Chatbot und einer Suchmaschine und hat sich 2026 stark auf Research und agentic Work konzentriert.

Die Hauptneuerung ist Advanced Deep Research. Es ist kein einfacher mehrseitiger Reportmodus mehr: Er läuft jetzt agentisch in Perplexity Computer, stellt Verständnisfragen vor dem Start, akzeptiert Follow-ups während der Ausführung und zeigt Live-Quellen- und Fortschrittserfassung. Bei Pro und Max wird Deep Research von Claude Opus 4.7 und Sonnet 4.6 unterstützt, und Perplexity meldet State-of-the-Art-Benchmark-Scores (93,9% bei SimpleQA, 21,1% bei Humanity''s Last Exam). Der Deep Research in Computer agentic assistant wurde am 19. Juni 2026 veröffentlicht und fügte ein Command Panel, Thread Forking, Inline Actions, Analytics APIs und Enterprise Credit Controls hinzu.

Über Research hinaus bietet Perplexity Multi-Model-Zugang zur GPT-5.6 Familie, Claude Opus 5, Gemini und anderen Frontier Models, ein Model Council Feature, das mehrere Modelle nebeneinander vergleicht, und den Comet Browser für AI-gestützte Browsing.

Die Preisgestaltung umfasst fünf Stufen. Free kostet $0 und beinhaltet etwa 5 Pro Searches pro Tag. Pro kostet $20/Monat oder $200/Jahr, bündelt $5/Monat Sonar API Credits und erlaubt etwa 20 Deep Research Runs pro Tag. Die neue Max Stufe kostet $200/Monat oder $2.000/Jahr und fügt Model Council, 10.000 Computer Credits pro Monat, Sora 2 Pro Video und Nano Banana Pro Imagegenerierung sowie unbegrenzte Labs hinzu. Studenten erhalten Pro für etwa $10/Monat, und es gibt Enterprise Pro (~$40/Platz/Monat) und Enterprise Max (~$325/Platz/Monat) Pläne.

Die Limitierungen sind erwähnenswert. Wie jedes AI-System kann es schwache Quellen immer noch missverstehen oder zu sehr vertrauen, daher müssen Zitate überprüft werden. Die fähigsten Features befinden sich hinter der $200/Monat Max Stufe und einem monatlichen Computer Credit Budget, die Free Stufe ist ziemlich begrenzt, und die Verwaltung mehrerer Modelle plus Model Council fügt eine Lernkurve hinzu.

Perplexity ist eine starke Wahl, wenn Sie viel quellengestützte Research betreiben, agentisches Deep Research auf Top-Tier Models wünschen oder mehrere AI Modelle bei derselben Frage vergleichen mögen. Gelegenheitsnutzer, die nur ein paar Antworten pro Tag brauchen, können bei Free bleiben, während intensive oder Enterprise-Nutzer die bezahlten Stufen, die um sie herum gebaut sind, finden werden.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='de';
UPDATE tools SET description_long='Perplexity es una herramienta de búsqueda conversacional que responde preguntas con fuentes citadas y actualizadas en lugar de una lista de enlaces. Se sitúa en algún punto entre un chatbot y un motor de búsqueda, y durante 2026 se ha enfocado fuertemente en investigación y trabajo agéntico.

El cambio principal es Advanced Deep Research. Ya no es un simple modo de informe multipágina: ahora funciona de manera agéntica dentro de Perplexity Computer, hace preguntas aclaratorias antes de comenzar, acepta seguimientos durante la ejecución, y muestra seguimiento en vivo de fuentes y progreso. En Pro y Max, Deep Research funciona con Claude Opus 4.7 y Sonnet 4.6, y Perplexity reporta puntuaciones de referencia de última generación (93.9% en SimpleQA, 21.1% en Humanity''s Last Exam). El asistente agéntico Deep Research in Computer se lanzó el 19 de junio de 2026, agregando un panel de comandos, bifurcación de hilos, acciones en línea, APIs de análisis y controles de crédito empresarial.

Más allá de la investigación, Perplexity te da acceso multimodelo a la familia GPT-5.6, Claude Opus 5, Gemini y otros modelos de frontera, una función Model Council que compara varios modelos lado a lado, y el navegador Comet para navegación asistida por IA.

Los precios abarcen cinco niveles. Free es $0 e incluye aproximadamente 5 búsquedas Pro por día. Pro es $20/mes o $200/año, incluye $5/mes de créditos de API Sonar, y permite alrededor de 20 ejecuciones de Deep Research al día. El nuevo nivel Max es $200/mes o $2,000/año e incluye Model Council, 10,000 créditos de Computer al mes, generación de video Sora 2 Pro y generación de imágenes Nano Banana Pro, y Labs ilimitado. Los estudiantes obtienen Pro por alrededor de $10/mes, y hay planes Enterprise Pro (~$40/usuario/mes) y Enterprise Max (~$325/usuario/mes).

Vale la pena conocer las limitaciones. Como cualquier sistema de IA, todavía puede malinterpretar o confiar excesivamente en fuentes débiles, por lo que las citas necesitan verificación. Las características más capaces están detrás del nivel Max de $200/mes y un presupuesto mensual de créditos de Computer, el nivel gratuito es bastante limitado, y equilibrar múltiples modelos más Model Council añade una curva de aprendizaje.

Perplexity es una excelente opción si haces mucha investigación respaldada por fuentes, deseas Deep Research agéntico en modelos de primera categoría, o te gusta comparar varios modelos de IA en la misma pregunta. Los usuarios casuales que solo necesitan algunas respuestas al día pueden mantenerse en Free, mientras que los usuarios pesados o empresariales encontrarán los niveles pagos construidos específicamente para ellos.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='es';
UPDATE tools SET description_long='Perplexity est un outil de recherche conversationnelle qui répond aux questions avec des sources citées et à jour au lieu d''une liste de liens. Il se situe quelque part entre un chatbot et un moteur de recherche, et au cours de 2026, il s''est fortement orienté vers la recherche et le travail agentique.

Le changement majeur est Advanced Deep Research. Ce n''est plus un simple mode de rapport multi-pages : il s''exécute maintenant de manière agentique à l''intérieur de Perplexity Computer, pose des questions de clarification avant de commencer, accepte les suites en cours d''exécution, et affiche le suivi des sources et de la progression en direct. Sur Pro et Max, Deep Research est alimenté par Claude Opus 4.7 et Sonnet 4.6, et Perplexity rapporte des scores de référence à l''état de l''art (93,9% sur SimpleQA, 21,1% sur Humanity''s Last Exam). L''assistant agentique Deep Research in Computer a été lancé le 19 juin 2026, ajoutant un panneau de commande, le forking de fils de discussion, les actions en ligne, les APIs d''analyse et les contrôles de crédit d''entreprise.

Au-delà de la recherche, Perplexity vous offre un accès multi-modèles à la famille GPT-5.6, Claude Opus 5, Gemini et autres modèles de pointe, une fonctionnalité Model Council qui compare plusieurs modèles côte à côte, et le navigateur Comet pour la navigation assistée par IA.

La tarification s''étend sur cinq niveaux. Free est à $0 et inclut environ 5 recherches Pro par jour. Pro est $20/mo ou $200/yr, inclut $5/mo de crédits API Sonar, et permet environ 20 exécutions Deep Research par jour. Le nouveau niveau Max est $200/mo ou $2,000/yr et ajoute Model Council, 10 000 crédits Computer par mois, la génération vidéo Sora 2 Pro et la génération d''images Nano Banana Pro, et Labs illimités. Les étudiants obtiennent Pro pour environ $10/mo, et il existe des plans Enterprise Pro (~$40/seat/mo) et Enterprise Max (~$325/seat/mo).

Les limitations méritent d''être connues. Comme tout système IA, il peut toujours mal lire ou faire confiance excessivement à des sources faibles, donc les citations nécessitent une vérification. Les fonctionnalités les plus puissantes se trouvent derrière le niveau Max $200/mo et un budget mensuel de crédits Computer, le niveau gratuit est assez serré, et jongler avec plusieurs modèles plus Model Council ajoute une courbe d''apprentissage.

Perplexity est un excellent choix si vous effectuez beaucoup de recherches documentées, si vous souhaitez une Deep Research agentique sur des modèles de premier plan, ou si vous aimez comparer plusieurs modèles IA sur la même question. Les utilisateurs occasionnels qui n''ont besoin que de quelques réponses par jour peuvent rester sur Free, tandis que les utilisateurs intensifs ou d''entreprise trouveront les niveaux payants construits autour de leurs besoins.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='fr';
UPDATE tools SET description_long='Perplexity é uma ferramenta de busca conversacional que responde perguntas com fontes citadas e atualizadas em vez de uma lista de links. Fica em algum lugar entre um chatbot e um mecanismo de busca, e ao longo de 2026 investiu pesadamente em pesquisa e trabalho com agentes.

A principal mudança é Advanced Deep Research. Não é mais um simples modo de relatório multipáginas: agora funciona com agentes dentro do Perplexity Computer, faz perguntas de esclarecimento antes de começar, aceita acompanhamentos durante a execução e mostra rastreamento de fonte e progresso em tempo real. No Pro e Max, Deep Research é alimentado por Claude Opus 4.7 e Sonnet 4.6, e a Perplexity relata pontuações de benchmark de última geração (93,9% no SimpleQA, 21,1% no Humanity''s Last Exam). O Deep Research no assistente agentic Computer foi lançado em 19 de junho de 2026, adicionando um painel de comandos, bifurcação de threads, ações inline, APIs de análise e controles de crédito corporativos.

Além da pesquisa, Perplexity oferece acesso multímodelo à família GPT-5.6, Claude Opus 5, Gemini e outros modelos de fronteira, um recurso Model Council que compara vários modelos lado a lado, e o navegador Comet para navegação assistida por IA.

O preço abrange cinco níveis. Free é $0 e inclui aproximadamente 5 buscas Pro por dia. Pro é $20/mês ou $200/ano, oferece $5/mês de créditos da Sonar API e permite cerca de 20 execuções de Deep Research por dia. O novo nível Max é $200/mês ou $2.000/ano e adiciona Model Council, 10.000 créditos Computer por mês, geração de vídeo Sora 2 Pro e geração de imagem Nano Banana Pro, e Labs ilimitado. Estudantes recebem Pro por aproximadamente $10/mês, e existem planos Enterprise Pro (~$40/assento/mês) e Enterprise Max (~$325/assento/mês).

As limitações merecem atenção. Como qualquer sistema de IA, ainda pode interpretar mal ou confiar demais em fontes fracas, portanto as citações precisam ser verificadas. Os recursos mais capazes ficam atrás do nível Max de $200/mês e um orçamento mensal de créditos Computer, o nível free é bastante restrito, e malabarismos com múltiplos modelos mais Model Council agregam uma curva de aprendizado.

Perplexity é uma escolha forte se você faz muita pesquisa com suporte de fontes, quer Deep Research com agentes em modelos de primeira linha, ou gosta de comparar vários modelos de IA na mesma pergunta. Usuários ocasionais que precisam apenas de algumas respostas por dia podem ficar no Free, enquanto usuários pesados ou corporativos encontrarão os níveis pagos construídos ao seu redor.', last_updated='2026-07-28' WHERE slug='perplexity' AND lang='pt';

-- 3) amazon-q-developer -> unpublished (replaced by Kiro) --
UPDATE tools SET published=false, last_updated='2026-07-28' WHERE slug='amazon-q-developer';
