-- Kiro new tool card (8 langs). Run after 04. --
DELETE FROM tools WHERE slug='kiro';
INSERT INTO tools (slug,lang,name,url,domain,category,badge,users,best_for,description,description_long,pros,cons,rating,also_consider,published) VALUES
('kiro','en','Kiro','https://kiro.dev','kiro.dev','code','freemium','','Spec-driven agentic coding','Kiro is AWS''s agentic IDE — a VS Code fork built around spec-driven development: it writes a structured requirements, design and tasks spec before generating code. The agent runs on Anthropic''s Claude.','Kiro is Amazon Web Services'' agentic IDE, launched in May 2026 as a VS Code fork built around spec-driven development. Instead of prompting straight to code, Kiro first produces a structured requirements document, a design and architecture plan, and a task spec, then implements against them — an approach aimed at reducing the rework that free-form AI coding often creates.

The agent runs on Anthropic''s Claude models (Sonnet at the core, with Opus available for harder reasoning), executing multi-file changes, running tests, and iterating against the spec. Kiro effectively replaces AWS''s earlier Amazon Q Developer, which is being wound down.

Pricing uses a credit model: a Free tier with 50 credits, Pro at $20/month (1,000 credits), Pro+ at $40/month (2,000 credits), and Power at $200/month (10,000 credits), with pay-as-you-go overage at $0.04 per credit. Kiro is best for teams that want the AI to plan before it builds, and for AWS-centric development shops.',ARRAY['Spec-driven flow reduces rework and scope drift','Writes requirements, design and task specs before any code','Runs frontier Claude models (Sonnet/Opus)','Familiar VS Code-based interface','Transparent credit pricing from a free tier']::text[],ARRAY['Spec-first flow adds overhead for small, quick tasks','Newer, smaller ecosystem than Cursor or Copilot','Credit model can get costly under heavy use','Most valuable inside AWS-centric workflows']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true),
('kiro','ru','Kiro','https://kiro.dev','kiro.dev','code','freemium','','Разработка на основе спецификаций с использованием агентских систем','Kiro — это агентская IDE от AWS, форк VS Code, созданный для разработки, управляемой спецификациями: сначала он пишет структурированную спецификацию требований, дизайна и задач, а затем генерирует код. Агент работает на Claude от Anthropic.','Kiro — это агентская IDE от Amazon Web Services, запущенная в мае 2026 года как форк VS Code, построенный вокруг разработки, управляемой спецификациями. Вместо прямой генерации кода Kiro сначала создает структурированный документ требований, план дизайна и архитектуры, а также спецификацию задач, а затем реализует их — подход, направленный на снижение переделок, которые часто возникают при свободной генерации кода с помощью ИИ.

Агент работает на моделях Claude от Anthropic (Sonnet в основе, Opus доступен для более сложных задач рассуждения), выполняя изменения в нескольких файлах, запуская тесты и итерируя в соответствии со спецификацией. Kiro фактически заменяет более раннюю Amazon Q Developer от AWS, которая прекращает работу.

Ценообразование использует модель кредитов: бесплатный уровень с 50 кредитами, Pro за $20/месяц (1000 кредитов), Pro+ за $40/месяц (2000 кредитов) и Power за $200/месяц (10000 кредитов), с оплатой по мере использования при избыточном использовании в размере $0,04 за кредит. Kiro лучше всего подходит для команд, которые хотят, чтобы ИИ планировал перед построением, и для разработочных команд, сосредоточенных на AWS.',ARRAY['Рабочий процесс, управляемый спецификациями, сокращает переделки и дрейф области применения','Пишет спецификации требований, дизайна и задач перед любым кодом','Запускает передовые модели Claude (Sonnet/Opus)','Знакомый интерфейс на основе VS Code','Прозрачное ценообразование в кредитах с бесплатным уровнем']::text[],ARRAY['Рабочий процесс, ориентированный на спецификации, добавляет накладные расходы для небольших быстрых задач','Новая и меньшая экосистема по сравнению с Cursor или Copilot','Модель кредитов может стать дорогой при интенсивном использовании','Наиболее ценна в рабочих процессах, сосредоточенных на AWS']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true),
('kiro','ua','Kiro','https://kiro.dev','kiro.dev','code','freemium','','Розробка коду, керована специфікаціями','Kiro — агентна IDE від AWS — форк VS Code, побудований навколо розробки, керованої специфікаціями: він пише структуровану специфікацію вимог, дизайну та завдань перед генеруванням коду. Агент працює на Claude від Anthropic.','Kiro — агентна IDE від Amazon Web Services, запущена у травні 2026 року як форк VS Code, побудований навколо розробки, керованої специфікаціями. Замість прямого запиту до коду Kiro спочатку створює структурований документ вимог, план дизайну та архітектури та специфікацію завдань, а потім реалізує їх — підхід, спрямований на зменшення переробок, які часто створює вільний AI-кодинг.

Агент працює на моделях Claude від Anthropic (Sonnet в основі, з доступним Opus для складніших міркувань), виконуючи багатофайлові зміни, запускаючи тести та повторюючи виконання відповідно до специфікації. Kiro фактично замінює раніший Amazon Q Developer від AWS, який припиняється.

Ціноутворення використовує модель кредитів: Безплатний рівень з 50 кредитами, Pro за $20/місяць (1000 кредитів), Pro+ за $40/місяць (2000 кредитів) і Power за $200/місяць (10000 кредитів), з оплатою за перевищення $0,04 за кредит. Kiro найкраще підходить для команд, які хочуть, щоб AI планував перед компіляцією, а також для розробки, орієнтованої на AWS.',ARRAY['Потік, керований специфікаціями, зменшує переробку та відхилення обсягу','Пише специфікації вимог, дизайну та завдань перед будь-яким кодом','Запускає передові моделі Claude (Sonnet/Opus)','Знайомий інтерфейс на основі VS Code','Прозоре цінообразування кредитів від безплатного рівня']::text[],ARRAY['Потік, керований специфікаціями, створює додаткові витрати для малих, швидких завдань','Новіша, менша екосистема, ніж Cursor або Copilot','Модель кредитів може бути дорогою при інтенсивному використанні','Найцінніша в робочих процесах, орієнтованих на AWS']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true),
('kiro','he','Kiro','https://kiro.dev','kiro.dev','code','freemium','','פיתוח קוד עם סוכנים המונעים על ידי מפרטים','Kiro היא ה-IDE של סוכנים של AWS — fork של VS Code שבנויה סביב פיתוח מונע על ידי מפרטים: היא כותבת מפרט דרישות, עיצוב ומשימות מובנה לפני יצירת קוד. הסוכן פועל על Claude של Anthropic.','Kiro היא ה-IDE של סוכנים של Amazon Web Services, שהושקה במאי 2026 כ-fork של VS Code שנבנה סביב פיתוח מונע על ידי מפרטים. במקום לשאול ישירות לקוד, Kiro קודם כל מייצרת מסמך דרישות מובנה, תכנית עיצוב וארכיטקטורה, ומפרט משימות, ואז מיישמות אותן — גישה שמטרתה להפחית את השיפוץ שפיתוח קוד AI חופשי לעתים קרובות יוצר.

הסוכן פועל על מודלים Claude של Anthropic (Sonnet בליבה, כשOpus זמין לחשיבה קשה יותר), מבצע שינויים בקבצים מרובים, מריץ בדיקות ופועל חוזר על המפרט. Kiro למעשה מחליפה את Amazon Q Developer של AWS, שמתמוטטת.

תמחור משתמש במודל קרדיט: שכבה חופשית עם 50 קרדיט, Pro ב-$20 לחודש (1,000 קרדיט), Pro+ ב-$40 לחודש (2,000 קרדיט), ו-Power ב-$200 לחודש (10,000 קרדיט), עם תשלום לפי השימוש עבור חריגה ב-$0.04 לקרדיט. Kiro הטובה ביותר לצוותים שרוצים שה-AI תתכננן לפני שהוא בונה, וליצור חדר פיתוח שמתמקדת ב-AWS.',ARRAY['זרימת מפרט מפחיתה שיפוץ וסחיפת היקף','כותבת דרישות, עיצוב ומפרט משימות לפני כל קוד','מריץ מודלים Claude חדשים (Sonnet/Opus)','ממשק מוכר המבוסס על VS Code','תמחור קרדיט שקוף מ-tier חופשי']::text[],ARRAY['זרימת spec-first מוסיפה עומס לעבודות קטנות ומהירות','מערכת אקולוגית חדשה וקטנה יותר מ-Cursor או Copilot','מודל קרדיט יכול להיות יקר תחת שימוש כבד','הערך ביותר בתוך תזרימי עבודה שמתמקדים ב-AWS']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true),
('kiro','de','Kiro','https://kiro.dev','kiro.dev','code','freemium','','Spec-gesteuerte agentic Codierung','Kiro ist AWs agentic IDE — ein VS Code Fork, der auf spec-gesteuerte Entwicklung ausgerichtet ist: Er schreibt zunächst eine strukturierte Anforderungs-, Design- und Task-Spec, bevor er Code generiert. Der Agent läuft auf Anthropics Claude.','Kiro ist die agentic IDE von Amazon Web Services, die im Mai 2026 als VS Code Fork mit Fokus auf spec-gesteuerte Entwicklung gestartet wurde. Statt direkt zum Code zu springen, erstellt Kiro zunächst ein strukturiertes Anforderungsdokument, einen Design- und Architekturplan sowie eine Task-Spec und implementiert dann danach — ein Ansatz, der das Rework reduzieren soll, das freie KI-Codierung oft mit sich bringt.

Der Agent läuft auf Anthropics Claude-Modellen (Sonnet im Kern, mit Opus für schwierigere Reasoning-Aufgaben), führt Multi-File-Änderungen aus, führt Tests aus und iteriert gegen die Spec. Kiro ersetzt effektiv AWs früheres Amazon Q Developer, das eingestellt wird.

Die Preisgestaltung nutzt ein Credit-Modell: Free-Tier mit 50 Credits, Pro mit $20/Monat (1.000 Credits), Pro+ mit $40/Monat (2.000 Credits) und Power mit $200/Monat (10.000 Credits), mit Pay-as-you-go Overage zu $0,04 pro Credit. Kiro eignet sich am besten für Teams, die wollen, dass die KI plant, bevor sie baut, und für AWS-zentrische Entwicklungsteams.',ARRAY['Spec-gesteuerte Arbeitsweise reduziert Rework und Scope Drift','Schreibt Anforderungen, Design und Task-Specs vor jeglichem Code','Führt Frontier Claude Modelle aus (Sonnet/Opus)','Vertraute VS Code-basierte Oberfläche','Transparente Credit-Preisgestaltung ab kostenlosem Tier']::text[],ARRAY['Spec-First-Ansatz erzeugt Overhead bei kleinen, schnellen Aufgaben','Neueres, kleineres Ökosystem als Cursor oder Copilot','Credit-Modell kann bei intensiver Nutzung teuer werden','Am wertvollsten in AWS-zentrierten Workflows']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true),
('kiro','es','Kiro','https://kiro.dev','kiro.dev','code','freemium','','Codificación agéntica impulsada por especificaciones','Kiro es el IDE agéntico de AWS — un fork de VS Code construido en torno al desarrollo impulsado por especificaciones: escribe una especificación estructurada de requisitos, diseño y tareas antes de generar código. El agente se ejecuta en Claude de Anthropic.','Kiro es el IDE agéntico de Amazon Web Services, lanzado en mayo de 2026 como un fork de VS Code construido en torno al desarrollo impulsado por especificaciones. En lugar de ir directamente a código, Kiro primero produce un documento de requisitos estructurado, un plan de diseño y arquitectura, y una especificación de tareas, luego implementa contra ellos — un enfoque dirigido a reducir el retrabajo que la codificación IA sin estructura a menudo crea.

El agente se ejecuta en modelos Claude de Anthropic (Sonnet en el núcleo, con Opus disponible para razonamientos más complejos), ejecutando cambios multiarquivo, ejecutando pruebas e iterando contra la especificación. Kiro reemplaza efectivamente el anterior Amazon Q Developer de AWS, que está siendo descontinuado.

Los precios utilizan un modelo de créditos: un nivel gratuito con 50 créditos, Pro a $20/mes (1.000 créditos), Pro+ a $40/mes (2.000 créditos) y Power a $200/mes (10.000 créditos), con pago por uso en exceso a $0,04 por crédito. Kiro es mejor para equipos que quieren que la IA planifique antes de construir, y para equipos de desarrollo centrados en AWS.',ARRAY['El flujo impulsado por especificaciones reduce el retrabajo y la expansión del alcance','Escribe especificaciones de requisitos, diseño y tareas antes de cualquier código','Ejecuta modelos Claude de frontera (Sonnet/Opus)','Interfaz familiar basada en VS Code','Precios de créditos transparentes desde un nivel gratuito']::text[],ARRAY['El flujo especificaciones-primero añade sobrecarga para tareas pequeñas y rápidas','Ecosistema más nuevo y pequeño que Cursor o Copilot','El modelo de créditos puede resultar costoso con uso intensivo','Más valioso dentro de flujos de trabajo centrados en AWS']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true),
('kiro','fr','Kiro','https://kiro.dev','kiro.dev','code','freemium','','Développement de code agentique piloté par les spécifications','Kiro est l''IDE agentique d''AWS — un fork de VS Code conçu autour du développement piloté par les spécifications : il rédige d''abord une spécification structurée des exigences, de la conception et des tâches avant de générer le code. L''agent s''exécute sur Claude d''Anthropic.','Kiro est l''IDE agentique d''Amazon Web Services, lancé en mai 2026 en tant que fork de VS Code construit autour du développement piloté par les spécifications. Au lieu d''inviter directement la génération de code, Kiro produit d''abord un document de spécifications structuré, un plan de conception et d''architecture, et une spécification des tâches, puis les implémente — une approche visant à réduire les reprises que la génération de code IA sans structure crée souvent.

L''agent s''exécute sur les modèles Claude d''Anthropic (Sonnet au cœur, avec Opus disponible pour le raisonnement plus complexe), exécutant les modifications multi-fichiers, exécutant les tests et itérant selon les spécifications. Kiro remplace effectivement Amazon Q Developer d''AWS, qui est en cours de suppression.

La tarification utilise un modèle de crédits : un forfait gratuit avec 50 crédits, Pro à 20 $/mois (1 000 crédits), Pro+ à 40 $/mois (2 000 crédits) et Power à 200 $/mois (10 000 crédits), avec dépassement au tarif à l''utilisation à 0,04 $ par crédit. Kiro est idéal pour les équipes qui veulent que l''IA planifie avant de construire, et pour les ateliers de développement centrés sur AWS.',ARRAY['Le flux piloté par les spécifications réduit les reprises et la dérive des objectifs','Rédige les spécifications de exigences, conception et tâches avant tout code','Exécute les modèles Claude de pointe (Sonnet/Opus)','Interface familière basée sur VS Code','Tarification de crédits transparente à partir d''un forfait gratuit']::text[],ARRAY['Le flux spécifications-d''abord ajoute une surcharge pour les petites tâches rapides','Écosystème plus récent et plus petit que Cursor ou Copilot','Le modèle de crédits peut devenir coûteux en cas d''utilisation intensive','Très utile surtout dans les flux de travail centrés sur AWS']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true),
('kiro','pt','Kiro','https://kiro.dev','kiro.dev','code','freemium','','Codificação agnóstica orientada por especificações','Kiro é a IDE agnóstica da AWS — um fork do VS Code construído em torno do desenvolvimento orientado por especificações: ela escreve uma especificação estruturada de requisitos, design e tarefas antes de gerar código. O agente é executado no Claude da Anthropic.','Kiro é a IDE agnóstica da Amazon Web Services, lançada em maio de 2026 como um fork do VS Code construído em torno do desenvolvimento orientado por especificações. Em vez de ir direto para o código, Kiro primeiro produz um documento de requisitos estruturado, um plano de design e arquitetura, e uma especificação de tarefas, depois implementa contra eles — uma abordagem que visa reduzir o retrabalho que a codificação IA de forma livre frequentemente cria.

O agente é executado nos modelos Claude da Anthropic (Sonnet no núcleo, com Opus disponível para raciocínio mais complexo), executando mudanças em múltiplos arquivos, executando testes e iterando contra a especificação. Kiro efetivamente substitui o Amazon Q Developer anterior da AWS, que está sendo descontinuado.

O preço usa um modelo de créditos: um nível gratuito com 50 créditos, Pro a $20/mês (1.000 créditos), Pro+ a $40/mês (2.000 créditos) e Power a $200/mês (10.000 créditos), com pagamento conforme o uso de excedentes a $0,04 por crédito. Kiro é melhor para equipes que querem que a IA planeje antes de construir, e para empresas de desenvolvimento focadas em AWS.',ARRAY['Fluxo orientado por especificações reduz retrabalho e desvio de escopo','Escreve requisitos, design e especificações de tarefas antes de qualquer código','Executa modelos Claude de última geração (Sonnet/Opus)','Interface familiarizada baseada em VS Code','Preço de crédito transparente a partir de um nível gratuito']::text[],ARRAY['Fluxo orientado por especificações adiciona overhead para tarefas pequenas e rápidas','Ecossistema mais novo e menor que Cursor ou Copilot','Modelo de crédito pode ficar custoso com uso intenso','Mais valioso dentro de fluxos de trabalho focados em AWS']::text[],NULL,ARRAY['cursor','github-copilot','claude']::text[],true);
