-- batch A part 7/7 — choose_if as jsonb

-- hemingway-editor
UPDATE tools SET badge='freemium', description='A readability editor that flags hard-to-read sentences, passive voice and adverbs. The current flagship, Hemingway Editor Plus, adds an AI layer with sentence rewrites, grammar fixes and tone adjustment on top of the long-standing free online highlighter.', description_long='Hemingway Editor is a writing tool built around one simple idea: bold, clear prose. It highlights sentences that are hard or very hard to read, marks passive voice, adverbs and overly complex phrases, and gives you a readability grade so you can tighten your text.

The product has shifted well beyond the old free highlighter. The current flagship is Hemingway Editor Plus, a web-based, AI-powered version that sits alongside the free online editor and the one-time-purchase desktop app now called Hemingway Editor Classic. The site also exposes standalone free AI tools such as a proofreader, paraphraser, grammar checker and readability checker.

Capabilities depend on which version you use. The free online editor gives you the classic color-coded readability highlighting with no signup. Plus adds the AI features that are now central to the product: AI sentence rewrites, advanced grammar fixes, tone adjustment, AI synonym suggestions and document feedback.

Pricing is tiered. The online editor is free. Hemingway Editor Plus Individual 5K is $10/month or $100/year (about $8.33/month) and includes 5,000 AI sentence rewrites per month. Individual 10K is $12.50/month billed annually ($150/year) for 10,000 rewrites. Team 10K is $12.50 per user/month ($150/user/year) with 10,000 rewrites per user plus admin controls and priority support. Plus comes with a free two-week trial and no credit card required. The Classic desktop app has historically been a one-time purchase of around $19.99, though that figure is reported by third parties rather than confirmed on the current official pricing pages.

The limitations are worth knowing. The AI rewrites are metered by a monthly quota (5K or 10K), so heavy users can run out. The readability model is opinionated and English-centric, and it can flag perfectly good sentences simply for being long. It is not a full writing suite like a word processor or a research assistant.

Hemingway Editor suits writers, bloggers, students and professionals who want punchier, easier-to-read prose. The free tool is enough for occasional polishing; Plus makes sense if you want AI rewrites and grammar help in one place, and the Classic desktop app fits people who prefer a one-time offline purchase.', pros=ARRAY['Free online editor requires no signup and instantly highlights readability issues, passive voice and adverbs','Hemingway Editor Plus adds genuinely useful AI: sentence rewrites, grammar fixes, tone adjustment and synonym suggestions','Two-week Plus trial with no credit card lets you test the AI features risk-free','Clear tiered pricing, including a team plan with admin controls and priority support','Classic desktop app offers an offline, one-time-purchase option for people who dislike subscriptions']::text[], cons=ARRAY['AI rewrites are capped by a monthly quota (5,000 or 10,000), which heavy writers can exhaust','The readability engine is opinionated and English-focused, sometimes flagging good sentences just for length','Core AI value now sits behind a paid subscription; the free tool is highlighting only','Not a full document editor or research tool, so it complements rather than replaces your main writing app','Classic desktop pricing is not clearly confirmed on the current official pages']::text[], choose_if='["You want to make your writing punchier and easier to read", "You need AI sentence rewrites and grammar help alongside readability highlighting", "You want to try the AI features free for two weeks before paying", "You prefer a one-time-purchase offline app (Classic) over a subscription", "You are a team that needs shared access with admin controls"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='en';
UPDATE tools SET badge='freemium', description='Редактор читаемости, который подсвечивает сложные для чтения предложения, пассивный залог и наречия. Актуальный флагман Hemingway Editor Plus добавляет ИИ-слой с переписыванием фраз, исправлением грамматики и настройкой тона поверх давно знакомого бесплатного онлайн-редактора.', description_long='Hemingway Editor — инструмент для письма, построенный вокруг одной идеи: ясный и лаконичный текст. Он подсвечивает трудные и очень трудные для чтения предложения, отмечает пассивный залог, наречия и излишне сложные конструкции, а также показывает оценку читаемости, чтобы вы могли подтянуть текст.

Продукт заметно вышел за рамки прежнего бесплатного подсветчика. Актуальный флагман — Hemingway Editor Plus, веб-версия с искусственным интеллектом, которая соседствует с бесплатным онлайн-редактором и десктопным приложением с разовой оплатой, теперь называемым Hemingway Editor Classic. На сайте также есть отдельные бесплатные ИИ-инструменты: корректор, перефразировщик, проверка грамматики и проверка читаемости.

Возможности зависят от версии. Бесплатный онлайн-редактор даёт классическую цветовую подсветку читаемости без регистрации. Plus добавляет ИИ-функции, которые теперь в центре продукта: переписывание предложений, продвинутые исправления грамматики, настройку тона, подбор синонимов и обратную связь по документу.

Цены разбиты на тарифы. Онлайн-редактор бесплатен. Hemingway Editor Plus Individual 5K стоит $10 в месяц или $100 в год (около $8,33 в месяц) и включает 5000 ИИ-переписываний в месяц. Individual 10K — $12,50 в месяц при годовой оплате ($150 в год) за 10 000 переписываний. Team 10K — $12,50 за пользователя в месяц ($150 за пользователя в год), 10 000 переписываний на пользователя плюс админ-панель и приоритетная поддержка. У Plus есть бесплатный двухнедельный пробный период без привязки карты. Десктопное приложение Classic исторически стоило около $19,99 разово, но эта цифра указана сторонними источниками и не подтверждена на текущих официальных страницах цен.

Ограничения стоит учитывать. ИИ-переписывания ограничены месячной квотой (5K или 10K), так что активным пользователям их может не хватить. Модель читаемости субъективна и ориентирована на английский язык, она может помечать вполне удачные предложения просто за длину. Это не полноценный текстовый процессор и не исследовательский ассистент.

Hemingway Editor подойдёт авторам, блогерам, студентам и специалистам, которым нужен более чёткий и лёгкий для чтения текст. Бесплатного инструмента достаточно для эпизодической правки; Plus имеет смысл, если нужны ИИ-переписывания и помощь с грамматикой в одном месте, а Classic подходит тем, кто предпочитает разовую офлайн-покупку.', pros=ARRAY['Бесплатный онлайн-редактор не требует регистрации и сразу подсвечивает проблемы читаемости, пассивный залог и наречия','Hemingway Editor Plus добавляет действительно полезный ИИ: переписывание фраз, исправление грамматики, настройку тона и синонимы','Двухнедельный пробный период Plus без привязки карты позволяет протестировать ИИ без риска','Понятные тарифы, включая командный план с админ-управлением и приоритетной поддержкой','Desktop-приложение Classic даёт офлайн-вариант с разовой оплатой для тех, кто не любит подписки']::text[], cons=ARRAY['ИИ-переписывания ограничены месячной квотой (5000 или 10 000), которую активные авторы могут исчерпать','Движок читаемости субъективен и ориентирован на английский, иногда помечает хорошие предложения просто за длину','Основная ценность ИИ теперь за платной подпиской; бесплатный инструмент — только подсветка','Это не полноценный текстовый редактор и не исследовательский инструмент, он дополняет, а не заменяет основное приложение для письма','Цена Classic для десктопа не подтверждена явно на текущих официальных страницах']::text[], choose_if='["Вы хотите сделать текст чётче и легче для чтения", "Вам нужны ИИ-переписывания и помощь с грамматикой вместе с подсветкой читаемости", "Вы хотите протестировать ИИ-функции бесплатно две недели перед оплатой", "Вы предпочитаете офлайн-приложение с разовой оплатой (Classic) вместо подписки", "Вы команда, которой нужен общий доступ с админ-управлением"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='ru';
UPDATE tools SET badge='freemium', description='Un editor de legibilidad que resalta las frases difíciles de leer, la voz pasiva y los adverbios. Su producto insignia actual, Hemingway Editor Plus, añade una capa de IA con reescritura de frases, correcciones gramaticales y ajuste de tono sobre el conocido resaltador online gratuito.', description_long='Hemingway Editor es una herramienta de escritura construida en torno a una idea sencilla: prosa clara y directa. Resalta las frases difíciles y muy difíciles de leer, marca la voz pasiva, los adverbios y las construcciones demasiado complejas, y ofrece una puntuación de legibilidad para que puedas afinar tu texto.

El producto ha ido mucho más allá del antiguo resaltador gratuito. El buque insignia actual es Hemingway Editor Plus, una versión web con IA que convive con el editor online gratuito y con la aplicación de escritorio de compra única, ahora llamada Hemingway Editor Classic. El sitio también ofrece herramientas de IA gratuitas e independientes: corrector, parafraseador, verificador gramatical y verificador de legibilidad.

Las funciones dependen de la versión. El editor online gratuito ofrece el clásico resaltado por colores sin necesidad de registro. Plus añade las funciones de IA que hoy son el centro del producto: reescritura de frases, correcciones gramaticales avanzadas, ajuste de tono, sugerencias de sinónimos por IA y comentarios sobre el documento.

Los precios están escalonados. El editor online es gratuito. Hemingway Editor Plus Individual 5K cuesta 10 $/mes o 100 $/año (unos 8,33 $/mes) e incluye 5.000 reescrituras de IA al mes. Individual 10K cuesta 12,50 $/mes con facturación anual (150 $/año) por 10.000 reescrituras. Team 10K cuesta 12,50 $ por usuario/mes (150 $/usuario/año), con 10.000 reescrituras por usuario más controles de administrador y soporte prioritario. Plus incluye una prueba gratuita de dos semanas sin tarjeta de crédito. La app de escritorio Classic ha costado históricamente una compra única de unos 19,99 $, aunque esa cifra la reportan terceros y no está confirmada en las páginas oficiales de precios actuales.

Conviene conocer las limitaciones. Las reescrituras de IA están limitadas por una cuota mensual (5K o 10K), así que los usuarios intensivos pueden agotarlas. El modelo de legibilidad es opinado y centrado en el inglés, y puede marcar frases perfectamente válidas solo por ser largas. No es una suite de escritura completa ni un asistente de investigación.

Hemingway Editor conviene a redactores, blogueros, estudiantes y profesionales que buscan una prosa más contundente y fácil de leer. La herramienta gratuita basta para pulir de vez en cuando; Plus tiene sentido si quieres reescrituras de IA y ayuda gramatical en un solo lugar, y Classic encaja con quienes prefieren una compra única sin conexión.', pros=ARRAY['El editor online gratuito no requiere registro y resalta al instante los problemas de legibilidad, la voz pasiva y los adverbios','Hemingway Editor Plus añade una IA realmente útil: reescritura de frases, correcciones gramaticales, ajuste de tono y sinónimos','La prueba gratuita de dos semanas de Plus sin tarjeta permite probar la IA sin riesgo','Precios escalonados claros, incluido un plan de equipo con controles de administrador y soporte prioritario','La app de escritorio Classic ofrece una opción sin conexión y de compra única para quienes rechazan las suscripciones']::text[], cons=ARRAY['Las reescrituras de IA están limitadas por una cuota mensual (5.000 o 10.000) que los escritores intensivos pueden agotar','El motor de legibilidad es opinado y centrado en el inglés, y a veces marca buenas frases solo por su longitud','El valor principal de la IA está ahora tras una suscripción de pago; la herramienta gratuita solo resalta','No es un editor de documentos completo ni una herramienta de investigación, complementa en lugar de sustituir tu app principal','El precio de Classic para escritorio no está claramente confirmado en las páginas oficiales actuales']::text[], choose_if='["Quieres que tu escritura sea más contundente y fácil de leer", "Necesitas reescrituras de IA y ayuda gramatical junto al resaltado de legibilidad", "Quieres probar las funciones de IA gratis durante dos semanas antes de pagar", "Prefieres una app sin conexión y de compra única (Classic) frente a una suscripción", "Formas parte de un equipo que necesita acceso compartido con controles de administrador"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='es';
UPDATE tools SET badge='freemium', description='Ein Lesbarkeits-Editor, der schwer lesbare Sätze, Passivkonstruktionen und Adverbien markiert. Das aktuelle Flaggschiff Hemingway Editor Plus ergänzt den seit Langem bekannten kostenlosen Online-Highlighter um eine KI-Ebene mit Satzumschreibungen, Grammatikkorrekturen und Tonanpassung.', description_long='Hemingway Editor ist ein Schreibwerkzeug rund um eine einfache Idee: klare, kraftvolle Prosa. Es hebt schwer und sehr schwer lesbare Sätze hervor, markiert Passiv, Adverbien und zu komplexe Formulierungen und liefert eine Lesbarkeitsbewertung, damit Sie Ihren Text straffen können.

Das Produkt hat sich deutlich über den alten kostenlosen Highlighter hinaus entwickelt. Aktuelles Flaggschiff ist Hemingway Editor Plus, eine webbasierte KI-Version, die neben dem kostenlosen Online-Editor und der Desktop-App mit Einmalkauf steht, die jetzt Hemingway Editor Classic heißt. Die Website bietet außerdem eigenständige kostenlose KI-Tools: Korrekturleser, Umformulierer, Grammatikprüfer und Lesbarkeitsprüfer.

Der Funktionsumfang hängt von der Version ab. Der kostenlose Online-Editor bietet die klassische farbcodierte Lesbarkeitsmarkierung ohne Anmeldung. Plus ergänzt die KI-Funktionen, die heute im Zentrum des Produkts stehen: Satzumschreibungen, erweiterte Grammatikkorrekturen, Tonanpassung, KI-Synonymvorschläge und Dokument-Feedback.

Die Preise sind gestaffelt. Der Online-Editor ist kostenlos. Hemingway Editor Plus Individual 5K kostet 10 $/Monat oder 100 $/Jahr (rund 8,33 $/Monat) und umfasst 5.000 KI-Satzumschreibungen pro Monat. Individual 10K kostet 12,50 $/Monat bei jährlicher Abrechnung (150 $/Jahr) für 10.000 Umschreibungen. Team 10K kostet 12,50 $ pro Nutzer/Monat (150 $/Nutzer/Jahr) mit 10.000 Umschreibungen pro Nutzer sowie Admin-Steuerung und priorisiertem Support. Plus enthält eine kostenlose zweiwöchige Testphase ohne Kreditkarte. Die Classic-Desktop-App kostete historisch einen Einmalkauf von rund 19,99 $, allerdings stammt diese Zahl von Dritten und ist auf den aktuellen offiziellen Preisseiten nicht bestätigt.

Die Grenzen sollte man kennen. Die KI-Umschreibungen sind durch ein Monatskontingent (5K oder 10K) begrenzt, das Vielschreiber ausschöpfen können. Das Lesbarkeitsmodell ist meinungsstark und stark auf Englisch ausgerichtet und markiert mitunter gute Sätze allein wegen ihrer Länge. Es ist keine vollständige Schreib-Suite und kein Recherche-Assistent.

Hemingway Editor eignet sich für Autoren, Blogger, Studierende und Fachleute, die prägnantere, leichter lesbare Texte wollen. Das kostenlose Tool reicht für gelegentliches Feilen; Plus lohnt sich, wenn Sie KI-Umschreibungen und Grammatikhilfe an einem Ort möchten, und Classic passt für alle, die einen einmaligen Offline-Kauf bevorzugen.', pros=ARRAY['Der kostenlose Online-Editor erfordert keine Anmeldung und markiert Lesbarkeitsprobleme, Passiv und Adverbien sofort','Hemingway Editor Plus bietet wirklich nützliche KI: Satzumschreibungen, Grammatikkorrekturen, Tonanpassung und Synonyme','Die zweiwöchige Plus-Testphase ohne Kreditkarte erlaubt ein risikofreies Ausprobieren der KI','Klar gestaffelte Preise, inklusive Team-Tarif mit Admin-Steuerung und priorisiertem Support','Die Classic-Desktop-App bietet eine Offline-Option mit Einmalkauf für Abo-Muffel']::text[], cons=ARRAY['KI-Umschreibungen sind durch ein Monatskontingent (5.000 oder 10.000) begrenzt, das Vielschreiber ausschöpfen können','Die Lesbarkeits-Engine ist meinungsstark und englischlastig und markiert gute Sätze mitunter nur wegen ihrer Länge','Der KI-Kernwert steckt jetzt hinter einem kostenpflichtigen Abo; das kostenlose Tool markiert nur','Kein vollständiger Dokumenteneditor und kein Recherche-Tool, es ergänzt Ihre Haupt-Schreibapp, ersetzt sie aber nicht','Der Classic-Desktop-Preis ist auf den aktuellen offiziellen Seiten nicht eindeutig bestätigt']::text[], choose_if='["Sie wollen Ihre Texte prägnanter und leichter lesbar machen", "Sie brauchen KI-Satzumschreibungen und Grammatikhilfe zusätzlich zur Lesbarkeitsmarkierung", "Sie wollen die KI-Funktionen zwei Wochen kostenlos testen, bevor Sie zahlen", "Sie bevorzugen eine Offline-App mit Einmalkauf (Classic) statt eines Abos", "Sie sind ein Team, das gemeinsamen Zugang mit Admin-Steuerung braucht"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='de';
UPDATE tools SET badge='freemium', description='Редактор читабельності, який підсвічує складні для читання речення, пасивний стан і прислівники. Актуальний флагман Hemingway Editor Plus додає ШІ-шар із переписуванням фраз, виправленням граматики та налаштуванням тону поверх давно знайомого безкоштовного онлайн-редактора.', description_long='Hemingway Editor — це інструмент для письма, побудований навколо однієї простої ідеї: ясний і чіткий текст. Він підсвічує важкі та дуже важкі для читання речення, позначає пасивний стан, прислівники й надто складні конструкції та дає оцінку читабельності, щоб ви могли підтягнути текст.

Продукт помітно вийшов за межі колишнього безкоштовного підсвічувача. Актуальний флагман — Hemingway Editor Plus, вебверсія зі штучним інтелектом, що співіснує з безкоштовним онлайн-редактором і десктопним застосунком із разовою оплатою, який тепер називається Hemingway Editor Classic. На сайті також є окремі безкоштовні ШІ-інструменти: коректор, перефразувальник, перевірка граматики та перевірка читабельності.

Можливості залежать від версії. Безкоштовний онлайн-редактор дає класичну кольорову підсвітку читабельності без реєстрації. Plus додає ШІ-функції, які тепер у центрі продукту: переписування речень, розширені виправлення граматики, налаштування тону, підбір синонімів і зворотний зв''язок щодо документа.

Ціни поділені на тарифи. Онлайн-редактор безкоштовний. Hemingway Editor Plus Individual 5K коштує $10 на місяць або $100 на рік (близько $8,33 на місяць) і включає 5000 ШІ-переписувань на місяць. Individual 10K — $12,50 на місяць при річній оплаті ($150 на рік) за 10 000 переписувань. Team 10K — $12,50 за користувача на місяць ($150 за користувача на рік), 10 000 переписувань на користувача плюс адмін-керування та пріоритетна підтримка. Plus має безкоштовний двотижневий пробний період без прив''язки картки. Десктопний застосунок Classic історично коштував близько $19,99 разово, проте цю цифру наводять сторонні джерела, і вона не підтверджена на поточних офіційних сторінках цін.

Обмеження варто врахувати. ШІ-переписування обмежені місячною квотою (5K або 10K), тож активним користувачам їх може не вистачити. Модель читабельності суб''єктивна й орієнтована на англійську, вона може позначати цілком вдалі речення просто за довжину. Це не повноцінний текстовий процесор і не дослідницький асистент.

Hemingway Editor підійде авторам, блогерам, студентам і фахівцям, яким потрібен чіткіший і легший для читання текст. Безкоштовного інструмента достатньо для епізодичного шліфування; Plus має сенс, якщо потрібні ШІ-переписування та допомога з граматикою в одному місці, а Classic пасує тим, хто віддає перевагу разовій офлайн-покупці.', pros=ARRAY['Безкоштовний онлайн-редактор не потребує реєстрації і одразу підсвічує проблеми читабельності, пасивний стан та прислівники','Hemingway Editor Plus додає справді корисний ШІ: переписування фраз, виправлення граматики, налаштування тону та синоніми','Двотижневий пробний період Plus без прив''язки картки дозволяє протестувати ШІ без ризику','Зрозумілі тарифи, зокрема командний план з адмін-керуванням і пріоритетною підтримкою','Десктопний застосунок Classic дає офлайн-варіант із разовою оплатою для тих, хто не любить підписки']::text[], cons=ARRAY['ШІ-переписування обмежені місячною квотою (5000 або 10 000), яку активні автори можуть вичерпати','Рушій читабельності суб''єктивний і орієнтований на англійську, іноді позначає хороші речення просто за довжину','Основна цінність ШІ тепер за платною підпискою; безкоштовний інструмент лише підсвічує','Це не повноцінний редактор документів і не дослідницький інструмент, він доповнює, а не замінює основний застосунок для письма','Ціна Classic для десктопа не підтверджена явно на поточних офіційних сторінках']::text[], choose_if='["Ви хочете зробити текст чіткішим і легшим для читання", "Вам потрібні ШІ-переписування та допомога з граматикою разом із підсвіткою читабельності", "Ви хочете безкоштовно протестувати ШІ-функції два тижні перед оплатою", "Ви віддаєте перевагу офлайн-застосунку з разовою оплатою (Classic) замість підписки", "Ви команда, якій потрібен спільний доступ з адмін-керуванням"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='ua';
UPDATE tools SET badge='freemium', description='עורך קריאוּת שמסמן משפטים קשים לקריאה, סביל ותוארי פועל. מוצר הדגל הנוכחי, Hemingway Editor Plus, מוסיף שכבת בינה מלאכותית עם ניסוח מחדש של משפטים, תיקוני דקדוק והתאמת טון מעל המדגיש המקוון החינמי הוותיק.', description_long='Hemingway Editor הוא כלי כתיבה שנבנה סביב רעיון פשוט אחד: פרוזה ברורה ותמציתית. הוא מדגיש משפטים קשים וקשים מאוד לקריאה, מסמן סביל, תוארי פועל וניסוחים מורכבים מדי, ונותן ציון קריאוּת כדי שתוכלו להדק את הטקסט.

המוצר התקדם הרבה מעבר למדגיש החינמי הישן. מוצר הדגל הנוכחי הוא Hemingway Editor Plus, גרסה מבוססת ווב עם בינה מלאכותית שקיימת לצד העורך המקוון החינמי ולצד אפליקציית הדסקטופ ברכישה חד-פעמית שנקראת כעת Hemingway Editor Classic. האתר גם מציע כלי בינה מלאכותית חינמיים עצמאיים: מגיה, כלי ניסוח מחדש, בודק דקדוק ובודק קריאוּת.

היכולות תלויות בגרסה. העורך המקוון החינמי מספק את הדגשת הקריאוּת הצבעונית הקלאסית ללא הרשמה. Plus מוסיף את יכולות הבינה המלאכותית שנמצאות כיום במרכז המוצר: ניסוח מחדש של משפטים, תיקוני דקדוק מתקדמים, התאמת טון, הצעות מילים נרדפות ומשוב על המסמך.

התמחור מדורג. העורך המקוון חינמי. Hemingway Editor Plus Individual 5K עולה 10$ לחודש או 100$ לשנה (כ-8.33$ לחודש) וכולל 5,000 ניסוחים מחדש בבינה מלאכותית בחודש. Individual 10K עולה 12.50$ לחודש בחיוב שנתי (150$ לשנה) עבור 10,000 ניסוחים מחדש. Team 10K עולה 12.50$ למשתמש לחודש (150$ למשתמש לשנה), עם 10,000 ניסוחים מחדש למשתמש בתוספת בקרות מנהל ותמיכה בעדיפות. Plus כולל תקופת ניסיון חינם של שבועיים ללא כרטיס אשראי. אפליקציית הדסקטופ Classic עלתה היסטורית ברכישה חד-פעמית של כ-19.99$, אך נתון זה מדווח על ידי גורמי צד שלישי ואינו מאושר בדפי התמחור הרשמיים הנוכחיים.

כדאי להכיר את המגבלות. הניסוחים מחדש בבינה מלאכותית מוגבלים במכסה חודשית (5K או 10K), כך שמשתמשים כבדים עלולים למצות אותה. מודל הקריאוּת דעתני וממוקד באנגלית, והוא עלול לסמן משפטים טובים לחלוטין רק בשל אורכם. זהו אינו מעבד תמלילים מלא ולא עוזר מחקר.

Hemingway Editor מתאים לכותבים, בלוגרים, סטודנטים ואנשי מקצוע שרוצים טקסט חד וקל יותר לקריאה. הכלי החינמי מספיק לליטוש מזדמן; Plus הגיוני אם רוצים ניסוח מחדש בבינה מלאכותית ועזרה בדקדוק במקום אחד, ו-Classic מתאים למי שמעדיף רכישה חד-פעמית ללא חיבור לרשת.', pros=ARRAY['העורך המקוון החינמי אינו דורש הרשמה ומסמן מיד בעיות קריאוּת, סביל ותוארי פועל','Hemingway Editor Plus מוסיף בינה מלאכותית שימושית באמת: ניסוח מחדש של משפטים, תיקוני דקדוק, התאמת טון ומילים נרדפות','תקופת ניסיון של שבועיים ב-Plus ללא כרטיס אשראי מאפשרת לבדוק את הבינה המלאכותית ללא סיכון','תמחור מדורג ברור, כולל תוכנית צוות עם בקרות מנהל ותמיכה בעדיפות','אפליקציית הדסקטופ Classic מציעה אפשרות לא-מקוונת ברכישה חד-פעמית למי שלא אוהב מנויים']::text[], cons=ARRAY['הניסוחים מחדש בבינה מלאכותית מוגבלים במכסה חודשית (5,000 או 10,000) שכותבים כבדים עלולים למצות','מנוע הקריאוּת דעתני וממוקד באנגלית, ולעיתים מסמן משפטים טובים רק בשל אורכם','הערך המרכזי של הבינה המלאכותית נמצא כעת מאחורי מנוי בתשלום; הכלי החינמי מדגיש בלבד','אינו עורך מסמכים מלא ולא כלי מחקר, הוא משלים ולא מחליף את אפליקציית הכתיבה הראשית שלכם','מחיר Classic לדסקטופ אינו מאושר בבירור בדפים הרשמיים הנוכחיים']::text[], choose_if='["אתם רוצים להפוך את הכתיבה שלכם לחדה וקלה יותר לקריאה", "אתם צריכים ניסוח מחדש בבינה מלאכותית ועזרה בדקדוק לצד הדגשת קריאוּת", "אתם רוצים לנסות את יכולות הבינה המלאכותית בחינם לשבועיים לפני התשלום", "אתם מעדיפים אפליקציה לא-מקוונת ברכישה חד-פעמית (Classic) על פני מנוי", "אתם צוות שצריך גישה משותפת עם בקרות מנהל"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='he';
UPDATE tools SET badge='freemium', description='Un éditeur de lisibilité qui met en évidence les phrases difficiles à lire, la voix passive et les adverbes. Le produit phare actuel, Hemingway Editor Plus, ajoute une couche d''IA avec réécriture de phrases, corrections grammaticales et ajustement du ton, en plus du surligneur en ligne gratuit bien connu.', description_long='Hemingway Editor est un outil d''écriture bâti autour d''une idée simple : une prose claire et directe. Il met en évidence les phrases difficiles et très difficiles à lire, signale la voix passive, les adverbes et les tournures trop complexes, et fournit une note de lisibilité pour resserrer votre texte.

Le produit a largement dépassé l''ancien surligneur gratuit. Le produit phare actuel est Hemingway Editor Plus, une version web dotée d''IA qui cohabite avec l''éditeur en ligne gratuit et l''application de bureau à achat unique, désormais appelée Hemingway Editor Classic. Le site propose aussi des outils d''IA gratuits et autonomes : correcteur, outil de paraphrase, vérificateur grammatical et vérificateur de lisibilité.

Les fonctionnalités dépendent de la version. L''éditeur en ligne gratuit offre le surlignage de lisibilité classique en couleurs sans inscription. Plus ajoute les fonctions d''IA désormais au cœur du produit : réécriture de phrases, corrections grammaticales avancées, ajustement du ton, suggestions de synonymes par IA et retours sur le document.

Les tarifs sont échelonnés. L''éditeur en ligne est gratuit. Hemingway Editor Plus Individual 5K coûte 10 $/mois ou 100 $/an (environ 8,33 $/mois) et inclut 5 000 réécritures par IA par mois. Individual 10K coûte 12,50 $/mois en facturation annuelle (150 $/an) pour 10 000 réécritures. Team 10K coûte 12,50 $ par utilisateur/mois (150 $/utilisateur/an), avec 10 000 réécritures par utilisateur, des contrôles d''administration et une assistance prioritaire. Plus comprend un essai gratuit de deux semaines sans carte bancaire. L''application de bureau Classic a historiquement coûté un achat unique d''environ 19,99 $, mais ce chiffre est rapporté par des tiers et n''est pas confirmé sur les pages de tarifs officielles actuelles.

Il faut connaître les limites. Les réécritures par IA sont plafonnées par un quota mensuel (5K ou 10K), que les gros utilisateurs peuvent épuiser. Le modèle de lisibilité est tranché et centré sur l''anglais, et il peut signaler des phrases tout à fait correctes uniquement à cause de leur longueur. Ce n''est ni une suite d''écriture complète ni un assistant de recherche.

Hemingway Editor convient aux rédacteurs, blogueurs, étudiants et professionnels qui veulent une prose plus percutante et plus facile à lire. L''outil gratuit suffit pour un peaufinage ponctuel ; Plus a du sens si vous voulez la réécriture par IA et l''aide grammaticale au même endroit, et Classic convient à ceux qui préfèrent un achat unique hors ligne.', pros=ARRAY['L''éditeur en ligne gratuit ne demande aucune inscription et signale instantanément les problèmes de lisibilité, la voix passive et les adverbes','Hemingway Editor Plus ajoute une IA réellement utile : réécriture de phrases, corrections grammaticales, ajustement du ton et synonymes','L''essai gratuit de deux semaines de Plus, sans carte bancaire, permet de tester l''IA sans risque','Une tarification échelonnée claire, dont un plan d''équipe avec contrôles d''administration et assistance prioritaire','L''application de bureau Classic offre une option hors ligne à achat unique pour ceux qui n''aiment pas les abonnements']::text[], cons=ARRAY['Les réécritures par IA sont plafonnées par un quota mensuel (5 000 ou 10 000) que les gros rédacteurs peuvent épuiser','Le moteur de lisibilité est tranché et centré sur l''anglais, et signale parfois de bonnes phrases uniquement à cause de leur longueur','La valeur principale de l''IA est désormais derrière un abonnement payant ; l''outil gratuit ne fait que surligner','Ce n''est pas un éditeur de documents complet ni un outil de recherche : il complète votre application d''écriture principale sans la remplacer','Le prix de Classic pour le bureau n''est pas clairement confirmé sur les pages officielles actuelles']::text[], choose_if='["Vous voulez rendre votre écriture plus percutante et plus facile à lire", "Vous avez besoin de réécritures par IA et d''aide grammaticale en plus du surlignage de lisibilité", "Vous voulez tester les fonctions d''IA gratuitement pendant deux semaines avant de payer", "Vous préférez une application hors ligne à achat unique (Classic) plutôt qu''un abonnement", "Vous êtes une équipe qui a besoin d''un accès partagé avec contrôles d''administration"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='fr';
UPDATE tools SET badge='freemium', description='Um editor de legibilidade que destaca frases difíceis de ler, voz passiva e advérbios. O produto principal atual, o Hemingway Editor Plus, acrescenta uma camada de IA com reescrita de frases, correções gramaticais e ajuste de tom sobre o já conhecido destacador online gratuito.', description_long='O Hemingway Editor é uma ferramenta de escrita construída em torno de uma ideia simples: uma prosa clara e direta. Ele destaca frases difíceis e muito difíceis de ler, marca a voz passiva, os advérbios e as construções complexas demais, e fornece uma nota de legibilidade para você enxugar o texto.

O produto avançou muito além do antigo destacador gratuito. O carro-chefe atual é o Hemingway Editor Plus, uma versão web com IA que convive com o editor online gratuito e com o aplicativo de desktop de compra única, agora chamado Hemingway Editor Classic. O site também oferece ferramentas de IA gratuitas e independentes: corretor, parafraseador, verificador gramatical e verificador de legibilidade.

Os recursos dependem da versão. O editor online gratuito oferece o clássico destaque colorido de legibilidade sem cadastro. O Plus acrescenta os recursos de IA que hoje são o centro do produto: reescrita de frases, correções gramaticais avançadas, ajuste de tom, sugestões de sinônimos por IA e feedback sobre o documento.

Os preços são escalonados. O editor online é gratuito. O Hemingway Editor Plus Individual 5K custa US$ 10/mês ou US$ 100/ano (cerca de US$ 8,33/mês) e inclui 5.000 reescritas por IA por mês. O Individual 10K custa US$ 12,50/mês na cobrança anual (US$ 150/ano) por 10.000 reescritas. O Team 10K custa US$ 12,50 por usuário/mês (US$ 150/usuário/ano), com 10.000 reescritas por usuário mais controles de administrador e suporte prioritário. O Plus inclui um teste gratuito de duas semanas sem cartão de crédito. O aplicativo de desktop Classic historicamente custou uma compra única de cerca de US$ 19,99, embora esse valor seja relatado por terceiros e não confirmado nas páginas oficiais de preços atuais.

Vale conhecer as limitações. As reescritas por IA têm uma cota mensal (5K ou 10K), então usuários intensos podem esgotá-la. O modelo de legibilidade é opinativo e centrado no inglês, e pode marcar frases perfeitamente boas apenas por serem longas. Não é uma suíte de escrita completa nem um assistente de pesquisa.

O Hemingway Editor serve a redatores, blogueiros, estudantes e profissionais que querem uma prosa mais direta e fácil de ler. A ferramenta gratuita basta para ajustes ocasionais; o Plus faz sentido se você quer reescrita por IA e ajuda gramatical no mesmo lugar, e o Classic combina com quem prefere uma compra única offline.', pros=ARRAY['O editor online gratuito não exige cadastro e destaca instantaneamente problemas de legibilidade, voz passiva e advérbios','O Hemingway Editor Plus acrescenta uma IA realmente útil: reescrita de frases, correções gramaticais, ajuste de tom e sinônimos','O teste gratuito de duas semanas do Plus, sem cartão de crédito, permite avaliar a IA sem risco','Preços escalonados claros, incluindo um plano de equipe com controles de administrador e suporte prioritário','O aplicativo de desktop Classic oferece uma opção offline de compra única para quem não gosta de assinaturas']::text[], cons=ARRAY['As reescritas por IA têm cota mensal (5.000 ou 10.000) que redatores intensos podem esgotar','O motor de legibilidade é opinativo e centrado no inglês, às vezes marcando boas frases só pelo tamanho','O valor principal da IA agora está atrás de uma assinatura paga; a ferramenta gratuita apenas destaca','Não é um editor de documentos completo nem uma ferramenta de pesquisa, complementa em vez de substituir seu aplicativo principal de escrita','O preço do Classic para desktop não está claramente confirmado nas páginas oficiais atuais']::text[], choose_if='["Você quer deixar sua escrita mais direta e fácil de ler", "Você precisa de reescrita por IA e ajuda gramatical junto com o destaque de legibilidade", "Você quer testar os recursos de IA de graça por duas semanas antes de pagar", "Você prefere um aplicativo offline de compra única (Classic) em vez de assinatura", "Você é uma equipe que precisa de acesso compartilhado com controles de administrador"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='hemingway-editor' AND lang='pt';

-- heygen
UPDATE tools SET badge='freemium', description='HeyGen is an AI video platform for creating avatar-driven videos, voice cloning and translation. Its current flagship model, Avatar V (May 2026), builds a lifelike digital twin from a 15-second recording.', description_long='HeyGen is a browser-based platform for producing videos that are presented by AI avatars. You type or paste a script, pick or create an avatar, choose a voice, and the system generates a talking-head video without a camera crew or studio.

The current flagship is Avatar V, released in May 2026 and now the most realistic avatar model HeyGen offers. It is created from a single 15-second recording and adds full upper-body motion, multi-angle consistency and long-form identity stability, so the same avatar stays believable across longer scripts. Multi-look generation lets you change outfit or background while preserving the original movement. HeyGen has also integrated Seedance 2.0 for more cinematic AI video generation, and language coverage has grown to 175+ on paid plans (30+ on Free).

Beyond avatars, the core toolkit covers voice cloning, video translation with lip-sync, a library of 500+ stock avatars, and an API for programmatic generation.

Pricing now runs on a credit system across five tiers. Free is $0/mo (3 videos/mo, up to 1 minute each, 1 custom digital twin, 30+ languages). Creator is $29/mo ($24 billed annually) with 600 credits, up to 30-minute videos, 1080p, voice cloning and 175+ languages. Pro is $49/mo with 1,000 credits, 4K and scalable credit tiers. Business is $149/mo plus $20 per extra seat, 1,500 credits, up to 60-minute videos, 5 digital twins, SSO/SAML and LMS. Enterprise is custom.

The main limitation is credit consumption: Avatar IV/V studio videos cost around 20 credits per minute, far faster than older avatars, and lip-sync translation runs about 5 credits per minute, so heavy users burn through allowances quickly. Add-on packs (e.g. 300 credits for $15/mo) and API pricing (~$0.05/second for Avatar V) fill the gap.

HeyGen suits marketers, training teams, localization teams and creators who need frequent talking-head video without filming, and who can work within a credit budget.', pros=ARRAY['Avatar V (May 2026) produces highly realistic avatars from just a 15-second recording, with full upper-body motion and multi-angle consistency','Multi-look generation reuses one recording to change outfit or background while keeping natural movement','175+ languages on paid plans with lip-synced translation, useful for localization at scale','Generous free tier (3 videos/month, 1 custom digital twin) to test the platform','API with per-second pricing (~$0.05/sec for Avatar V) enables automated, high-volume workflows']::text[], cons=ARRAY['Avatar IV/V videos consume credits fast (~20 credits/min), so monthly allowances run out quickly on heavy use','The credit system makes real costs harder to predict than a flat per-video price','Free plan caps videos at 1 minute and only 3 per month','Highest realism and long videos require Pro or Business tiers, and Pro credit tiers can scale to thousands of dollars','Advanced controls like SSO/SAML and LMS are locked to the Business tier and up']::text[], choose_if='["You need frequent talking-head videos without filming or a studio", "You want to localize content into many languages with lip-sync", "You can build a fast digital twin from a short recording", "You have API/automation needs and can budget per-second generation", "You want to start free before committing to a paid credit plan"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='en';
UPDATE tools SET badge='freemium', description='HeyGen — платформа для создания видео с ИИ-аватарами, клонированием голоса и переводом. Актуальная флагманская модель Avatar V (май 2026) создаёт реалистичного цифрового двойника из 15-секундной записи.', description_long='HeyGen — это работающая в браузере платформа для создания видео, которые ведут ИИ-аватары. Вы вводите или вставляете сценарий, выбираете или создаёте аватар, задаёте голос — и система генерирует видео с говорящим человеком без съёмочной группы и студии.

Текущий флагман — Avatar V, выпущенный в мае 2026 года и ставший самой реалистичной моделью аватаров у HeyGen. Он создаётся всего из одной 15-секундной записи и добавляет движение всей верхней части тела, согласованность при разных ракурсах и устойчивость образа в длинных роликах, так что один и тот же аватар остаётся убедительным на протяжении долгих сценариев. Генерация в разных образах позволяет менять одежду или фон, сохраняя исходную пластику движений. Также интегрирована Seedance 2.0 для более кинематографичной генерации видео, а число языков выросло до 175+ на платных тарифах (30+ на бесплатном).

Помимо аватаров, базовый набор включает клонирование голоса, перевод видео с синхронизацией губ, библиотеку из 500+ готовых аватаров и API для программной генерации.

Цены теперь построены на кредитной системе с пятью тарифами. Free — $0/мес (3 видео в месяц, до 1 минуты каждое, 1 цифровой двойник, 30+ языков). Creator — $29/мес ($24 при годовой оплате), 600 кредитов, ролики до 30 минут, 1080p, клонирование голоса и 175+ языков. Pro — $49/мес, 1000 кредитов, 4K и масштабируемые уровни кредитов. Business — $149/мес плюс $20 за доп. место, 1500 кредитов, ролики до 60 минут, 5 двойников, SSO/SAML и LMS. Enterprise — по запросу.

Главное ограничение — расход кредитов: студийные видео Avatar IV/V стоят около 20 кредитов за минуту, что заметно быстрее старых аватаров, а перевод с синхронизацией губ — около 5 кредитов за минуту, так что при активном использовании лимиты тают быстро. Дополнительные пакеты (например, 300 кредитов за $15/мес) и API (~$0,05 за секунду для Avatar V) закрывают дефицит.

HeyGen подходит маркетологам, командам обучения и локализации, а также авторам, которым нужно регулярно делать видео с говорящей головой без съёмок и которые готовы укладываться в кредитный бюджет.', pros=ARRAY['Avatar V (май 2026) создаёт очень реалистичных аватаров всего из 15-секундной записи, с движением верхней части тела и согласованностью ракурсов','Генерация в разных образах позволяет из одной записи менять одежду и фон, сохраняя естественность движений','175+ языков на платных тарифах с синхронизацией губ — удобно для масштабной локализации','Щедрый бесплатный тариф (3 видео в месяц, 1 цифровой двойник) для теста платформы','API с посекундной оплатой (~$0,05/сек для Avatar V) для автоматизированных потоковых задач']::text[], cons=ARRAY['Видео Avatar IV/V быстро расходуют кредиты (~20 кредитов/мин), поэтому месячные лимиты исчерпываются быстро','Кредитная система затрудняет прогноз реальных затрат по сравнению с фиксированной ценой за видео','Бесплатный тариф ограничивает ролики 1 минутой и всего 3 в месяц','Максимальный реализм и длинные видео требуют тарифов Pro или Business, а уровни кредитов Pro доходят до тысяч долларов','SSO/SAML и LMS доступны только начиная с тарифа Business']::text[], choose_if='["Вам нужно регулярно делать видео с говорящей головой без съёмок и студии", "Вы хотите локализовать контент на множество языков с синхронизацией губ", "Вы можете быстро создать цифрового двойника из короткой записи", "У вас есть задачи с API/автоматизацией и бюджет на посекундную генерацию", "Вы хотите начать бесплатно, прежде чем переходить на платный кредитный тариф"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='ru';
UPDATE tools SET badge='freemium', description='HeyGen es una plataforma de vídeo con IA para crear vídeos con avatares, clonación de voz y traducción. Su modelo estrella actual, Avatar V (mayo de 2026), genera un gemelo digital realista a partir de una grabación de 15 segundos.', description_long='HeyGen es una plataforma que funciona en el navegador para producir vídeos presentados por avatares de IA. Escribes o pegas un guion, eliges o creas un avatar, seleccionas una voz y el sistema genera un vídeo de busto parlante sin equipo de rodaje ni estudio.

El modelo estrella actual es Avatar V, lanzado en mayo de 2026 y hoy el más realista de HeyGen. Se crea a partir de una sola grabación de 15 segundos e incorpora movimiento de toda la parte superior del cuerpo, coherencia en varios ángulos y estabilidad de identidad en formatos largos, de modo que el mismo avatar sigue siendo creíble en guiones extensos. La generación multi-look permite cambiar la ropa o el fondo conservando el movimiento original. Además, se ha integrado Seedance 2.0 para una generación de vídeo más cinematográfica, y la cobertura de idiomas ha crecido hasta más de 175 en los planes de pago (30+ en el gratuito).

Más allá de los avatares, el conjunto básico incluye clonación de voz, traducción de vídeo con sincronización labial, una biblioteca de más de 500 avatares predefinidos y una API para generación programática.

Los precios funcionan ahora con un sistema de créditos y cinco niveles. Free: 0 $/mes (3 vídeos al mes, hasta 1 minuto cada uno, 1 gemelo digital, 30+ idiomas). Creator: 29 $/mes (24 $ con pago anual), 600 créditos, vídeos de hasta 30 minutos, 1080p, clonación de voz y 175+ idiomas. Pro: 49 $/mes, 1.000 créditos, 4K y niveles de crédito escalables. Business: 149 $/mes más 20 $ por puesto adicional, 1.500 créditos, vídeos de hasta 60 minutos, 5 gemelos digitales, SSO/SAML y LMS. Enterprise: precio a medida.

La principal limitación es el consumo de créditos: los vídeos de estudio con Avatar IV/V cuestan unos 20 créditos por minuto, mucho más rápido que los avatares antiguos, y la traducción con sincronización labial ronda los 5 créditos por minuto, por lo que un uso intensivo agota rápido las asignaciones. Los paquetes adicionales (por ejemplo, 300 créditos por 15 $/mes) y la API (~0,05 $/segundo para Avatar V) cubren el resto.

HeyGen encaja con equipos de marketing, formación y localización y con creadores que necesitan vídeo de busto parlante con frecuencia sin grabar y que pueden ceñirse a un presupuesto de créditos.', pros=ARRAY['Avatar V (mayo de 2026) genera avatares muy realistas a partir de solo 15 segundos de grabación, con movimiento del torso y coherencia entre ángulos','La generación multi-look reutiliza una grabación para cambiar ropa o fondo manteniendo el movimiento natural','Más de 175 idiomas en los planes de pago con traducción sincronizada, útil para localizar a gran escala','Plan gratuito generoso (3 vídeos al mes, 1 gemelo digital) para probar la plataforma','API con precio por segundo (~0,05 $/s para Avatar V) para flujos automatizados de gran volumen']::text[], cons=ARRAY['Los vídeos con Avatar IV/V consumen créditos rápido (~20 créditos/min), así que las asignaciones mensuales se agotan pronto','El sistema de créditos hace que el coste real sea menos predecible que un precio fijo por vídeo','El plan gratuito limita los vídeos a 1 minuto y solo 3 al mes','El máximo realismo y los vídeos largos exigen los niveles Pro o Business, y los tramos de crédito de Pro llegan a miles de dólares','SSO/SAML y LMS solo están disponibles a partir del nivel Business']::text[], choose_if='["Necesitas vídeos de busto parlante con frecuencia sin grabar ni estudio", "Quieres localizar contenido a muchos idiomas con sincronización labial", "Puedes crear un gemelo digital rápido a partir de una grabación corta", "Tienes necesidades de API o automatización y puedes presupuestar la generación por segundo", "Quieres empezar gratis antes de pasar a un plan de créditos de pago"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='es';
UPDATE tools SET badge='freemium', description='HeyGen ist eine KI-Videoplattform zum Erstellen von Videos mit Avataren, Voice-Cloning und Übersetzung. Das aktuelle Flaggschiffmodell Avatar V (Mai 2026) erzeugt aus einer 15-Sekunden-Aufnahme einen realistischen digitalen Zwilling.', description_long='HeyGen ist eine im Browser laufende Plattform für Videos, die von KI-Avataren präsentiert werden. Man tippt oder fügt ein Skript ein, wählt oder erstellt einen Avatar, legt eine Stimme fest, und das System erzeugt ein Sprechervideo ohne Filmteam oder Studio.

Das aktuelle Flaggschiff ist Avatar V, veröffentlicht im Mai 2026 und heute das realistischste Avatar-Modell von HeyGen. Es wird aus einer einzigen 15-Sekunden-Aufnahme erstellt und ergänzt Bewegung des gesamten Oberkörpers, Konsistenz über mehrere Blickwinkel und eine stabile Identität in Langformaten, sodass derselbe Avatar auch bei längeren Skripten glaubwürdig bleibt. Die Multi-Look-Generierung erlaubt es, Outfit oder Hintergrund zu ändern und dabei die ursprüngliche Bewegung zu erhalten. Zusätzlich ist Seedance 2.0 für filmreifere KI-Videogenerierung integriert, und die Sprachabdeckung ist auf über 175 in den kostenpflichtigen Tarifen gewachsen (30+ im Free-Tarif).

Neben Avataren umfasst das Kernangebot Voice-Cloning, Videoübersetzung mit Lippensynchronisation, eine Bibliothek mit über 500 Standard-Avataren und eine API für die programmatische Generierung.

Die Preise laufen jetzt über ein Kreditsystem mit fünf Stufen. Free: 0 $/Monat (3 Videos/Monat, je bis zu 1 Minute, 1 digitaler Zwilling, 30+ Sprachen). Creator: 29 $/Monat (24 $ bei Jahreszahlung), 600 Credits, Videos bis 30 Minuten, 1080p, Voice-Cloning und 175+ Sprachen. Pro: 49 $/Monat, 1.000 Credits, 4K und skalierbare Kreditstufen. Business: 149 $/Monat plus 20 $ je zusätzlichem Platz, 1.500 Credits, Videos bis 60 Minuten, 5 digitale Zwillinge, SSO/SAML und LMS. Enterprise: individueller Preis.

Die größte Einschränkung ist der Kreditverbrauch: Studio-Videos mit Avatar IV/V kosten rund 20 Credits pro Minute, deutlich schneller als ältere Avatare, und die Übersetzung mit Lippensynchronisation etwa 5 Credits pro Minute. Bei intensiver Nutzung sind die Kontingente schnell aufgebraucht. Zusatzpakete (z. B. 300 Credits für 15 $/Monat) und die API (~0,05 $/Sekunde für Avatar V) schließen die Lücke.

HeyGen eignet sich für Marketing-, Schulungs- und Lokalisierungsteams sowie Creator, die regelmäßig Sprechervideos ohne Dreh brauchen und mit einem Kreditbudget arbeiten können.', pros=ARRAY['Avatar V (Mai 2026) erzeugt aus nur 15 Sekunden Aufnahme sehr realistische Avatare, mit Oberkörperbewegung und Konsistenz über Blickwinkel','Multi-Look-Generierung nutzt eine Aufnahme, um Outfit oder Hintergrund zu ändern und dabei natürliche Bewegung zu behalten','175+ Sprachen in den Bezahltarifen mit lippensynchroner Übersetzung, praktisch für Lokalisierung im großen Maßstab','Großzügiger Free-Tarif (3 Videos/Monat, 1 digitaler Zwilling) zum Testen der Plattform','API mit Preis pro Sekunde (~0,05 $/Sek. für Avatar V) für automatisierte Workflows mit hohem Volumen']::text[], cons=ARRAY['Videos mit Avatar IV/V verbrauchen Credits schnell (~20 Credits/Min.), sodass Monatskontingente rasch erschöpft sind','Das Kreditsystem macht die realen Kosten schwerer planbar als ein fester Preis pro Video','Der Free-Tarif begrenzt Videos auf 1 Minute und nur 3 pro Monat','Höchster Realismus und lange Videos erfordern Pro oder Business, und die Pro-Kreditstufen reichen bis in den Tausender-Dollar-Bereich','SSO/SAML und LMS sind erst ab dem Business-Tarif verfügbar']::text[], choose_if='["Du brauchst regelmäßig Sprechervideos ohne Dreh und Studio", "Du willst Inhalte in viele Sprachen mit Lippensynchronisation lokalisieren", "Du kannst aus einer kurzen Aufnahme schnell einen digitalen Zwilling erstellen", "Du hast API-/Automatisierungsbedarf und kannst die Generierung pro Sekunde einplanen", "Du willst kostenlos starten, bevor du auf einen bezahlten Kreditplan wechselst"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='de';
UPDATE tools SET badge='freemium', description='HeyGen — платформа для створення відео з ШІ-аватарами, клонуванням голосу та перекладом. Актуальна флагманська модель Avatar V (травень 2026) створює реалістичного цифрового двійника з 15-секундного запису.', description_long='HeyGen — це платформа, що працює у браузері, для створення відео, які ведуть ШІ-аватари. Ви вводите або вставляєте сценарій, обираєте чи створюєте аватар, задаєте голос — і система генерує відео з мовцем без знімальної групи та студії.

Поточний флагман — Avatar V, випущений у травні 2026 року і наразі найреалістичніша модель аватарів у HeyGen. Він створюється лише з одного 15-секундного запису й додає рух усієї верхньої частини тіла, узгодженість під різними кутами та стабільність образу в довгих роликах, тож той самий аватар лишається переконливим у тривалих сценаріях. Генерація в різних образах дозволяє змінювати одяг чи фон, зберігаючи початкову пластику рухів. Також інтегровано Seedance 2.0 для більш кінематографічної генерації відео, а кількість мов зросла до 175+ на платних тарифах (30+ на безкоштовному).

Окрім аватарів, базовий набір містить клонування голосу, переклад відео із синхронізацією губ, бібліотеку з понад 500 готових аватарів та API для програмної генерації.

Ціни тепер побудовані на кредитній системі з п''ятьма тарифами. Free — $0/міс (3 відео на місяць, до 1 хвилини кожне, 1 цифровий двійник, 30+ мов). Creator — $29/міс ($24 при річній оплаті), 600 кредитів, ролики до 30 хвилин, 1080p, клонування голосу та 175+ мов. Pro — $49/міс, 1000 кредитів, 4K і масштабовані рівні кредитів. Business — $149/міс плюс $20 за додаткове місце, 1500 кредитів, ролики до 60 хвилин, 5 двійників, SSO/SAML та LMS. Enterprise — за запитом.

Головне обмеження — витрата кредитів: студійні відео Avatar IV/V коштують близько 20 кредитів за хвилину, помітно швидше за старі аватари, а переклад із синхронізацією губ — близько 5 кредитів за хвилину, тож за активного використання ліміти вичерпуються швидко. Додаткові пакети (наприклад, 300 кредитів за $15/міс) та API (~$0,05 за секунду для Avatar V) закривають дефіцит.

HeyGen підходить маркетологам, командам навчання й локалізації, а також авторам, яким потрібно регулярно робити відео з мовцем без зйомок і які готові вкладатися в кредитний бюджет.', pros=ARRAY['Avatar V (травень 2026) створює дуже реалістичних аватарів лише з 15-секундного запису, з рухом верхньої частини тіла та узгодженістю кутів','Генерація в різних образах дозволяє з одного запису змінювати одяг і фон, зберігаючи природність рухів','175+ мов на платних тарифах із синхронізацією губ — зручно для масштабної локалізації','Щедрий безкоштовний тариф (3 відео на місяць, 1 цифровий двійник) для тесту платформи','API з посекундною оплатою (~$0,05/сек для Avatar V) для автоматизованих потокових завдань']::text[], cons=ARRAY['Відео Avatar IV/V швидко витрачають кредити (~20 кредитів/хв), тож місячні ліміти вичерпуються швидко','Кредитна система ускладнює прогноз реальних витрат порівняно з фіксованою ціною за відео','Безкоштовний тариф обмежує ролики 1 хвилиною і лише 3 на місяць','Максимальний реалізм і довгі відео потребують тарифів Pro або Business, а рівні кредитів Pro сягають тисяч доларів','SSO/SAML та LMS доступні лише починаючи з тарифу Business']::text[], choose_if='["Вам потрібно регулярно робити відео з мовцем без зйомок і студії", "Ви хочете локалізувати контент багатьма мовами із синхронізацією губ", "Ви можете швидко створити цифрового двійника з короткого запису", "У вас є завдання з API/автоматизацією та бюджет на посекундну генерацію", "Ви хочете почати безкоштовно, перш ніж переходити на платний кредитний тариф"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='ua';
UPDATE tools SET badge='freemium', description='HeyGen היא פלטפורמת וידאו מבוססת בינה מלאכותית ליצירת סרטונים עם אווטארים, שכפול קול ותרגום. המודל המוביל הנוכחי, Avatar V (מאי 2026), יוצר תאום דיגיטלי ריאליסטי מהקלטה של 15 שניות.', description_long='HeyGen היא פלטפורמה הפועלת בדפדפן ליצירת סרטונים שמוגשים על ידי אווטארים של בינה מלאכותית. מקלידים או מדביקים תסריט, בוחרים או יוצרים אווטאר, מגדירים קול, והמערכת מפיקה סרטון של דובר בלי צוות צילום ובלי אולפן.

המודל המוביל הנוכחי הוא Avatar V, שיצא במאי 2026 והוא כיום מודל האווטארים הריאליסטי ביותר של HeyGen. הוא נוצר מהקלטה בודדת של 15 שניות ומוסיף תנועה של כל פלג הגוף העליון, עקביות בין זוויות שונות ויציבות זהות לאורך תוכן ארוך, כך שאותו אווטאר נשאר אמין גם בתסריטים ארוכים. יצירה בכמה מראות מאפשרת להחליף לבוש או רקע תוך שמירה על התנועה המקורית. בנוסף שולב Seedance 2.0 ליצירת וידאו קולנועית יותר, ומספר השפות גדל ל-175 ומעלה בתוכניות בתשלום (30 ומעלה בחינם).

מעבר לאווטארים, ערכת הכלים הבסיסית כוללת שכפול קול, תרגום וידאו עם סנכרון שפתיים, ספרייה של יותר מ-500 אווטארים מוכנים, וגם API ליצירה תכנותית.

התמחור מבוסס כעת על מערכת קרדיטים בחמש רמות. Free: 0 $ לחודש (3 סרטונים בחודש, עד דקה כל אחד, תאום דיגיטלי אחד, 30+ שפות). Creator: 29 $ לחודש (24 $ בתשלום שנתי), 600 קרדיטים, סרטונים עד 30 דקות, 1080p, שכפול קול ו-175+ שפות. Pro: 49 $ לחודש, 1,000 קרדיטים, 4K ורמות קרדיט שניתנות להרחבה. Business: 149 $ לחודש בתוספת 20 $ לכל מושב נוסף, 1,500 קרדיטים, סרטונים עד 60 דקות, 5 תאומים דיגיטליים, SSO/SAML ו-LMS. Enterprise: תמחור מותאם אישית.

המגבלה המרכזית היא צריכת הקרדיטים: סרטוני אולפן עם Avatar IV/V עולים כ-20 קרדיטים לדקה, מהר בהרבה מהאווטארים הישנים, ותרגום עם סנכרון שפתיים עולה כ-5 קרדיטים לדקה, כך שאצל משתמשים כבדים המכסות נגמרות מהר. חבילות תוספת (למשל 300 קרדיטים ב-15 $ לחודש) ו-API (בערך 0.05 $ לשנייה עבור Avatar V) סוגרים את הפער.

HeyGen מתאימה לצוותי שיווק, הדרכה ולוקליזציה וליוצרים שצריכים סרטוני דובר בתדירות גבוהה בלי צילום ושיכולים לעבוד במסגרת תקציב קרדיטים.', pros=ARRAY['Avatar V (מאי 2026) מפיק אווטארים ריאליסטיים מאוד מהקלטה של 15 שניות בלבד, עם תנועת פלג גוף עליון ועקביות בין זוויות','יצירה בכמה מראות מנצלת הקלטה אחת כדי להחליף לבוש או רקע תוך שמירה על תנועה טבעית','175+ שפות בתוכניות בתשלום עם תרגום מסונכרן שפתיים, שימושי ללוקליזציה בקנה מידה גדול','תוכנית חינם נדיבה (3 סרטונים בחודש, תאום דיגיטלי אחד) לבדיקת הפלטפורמה','API עם תמחור לפי שנייה (בערך 0.05 $ לשנייה עבור Avatar V) לזרימות עבודה אוטומטיות בנפח גבוה']::text[], cons=ARRAY['סרטוני Avatar IV/V צורכים קרדיטים במהירות (כ-20 קרדיטים לדקה), כך שהמכסות החודשיות נגמרות מהר בשימוש כבד','מערכת הקרדיטים מקשה לחזות את העלות האמיתית לעומת מחיר קבוע לסרטון','התוכנית החינמית מגבילה סרטונים לדקה אחת ורק 3 בחודש','ריאליזם מרבי וסרטונים ארוכים דורשים רמות Pro או Business, ורמות הקרדיט של Pro מגיעות לאלפי דולרים','SSO/SAML ו-LMS זמינים רק החל מרמת Business']::text[], choose_if='["אתם צריכים סרטוני דובר בתדירות גבוהה בלי צילום ובלי אולפן", "אתם רוצים ללקלס תוכן להרבה שפות עם סנכרון שפתיים", "אתם יכולים ליצור תאום דיגיטלי מהיר מהקלטה קצרה", "יש לכם צרכי API או אוטומציה ואתם יכולים לתקצב יצירה לפי שנייה", "אתם רוצים להתחיל בחינם לפני מעבר לתוכנית קרדיטים בתשלום"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='he';
UPDATE tools SET badge='freemium', description='HeyGen est une plateforme vidéo par IA pour créer des vidéos avec avatars, du clonage de voix et de la traduction. Son modèle phare actuel, Avatar V (mai 2026), génère un jumeau numérique réaliste à partir d''un enregistrement de 15 secondes.', description_long='HeyGen est une plateforme accessible depuis le navigateur pour produire des vidéos présentées par des avatars IA. Vous saisissez ou collez un script, choisissez ou créez un avatar, sélectionnez une voix, et le système génère une vidéo de présentateur sans équipe de tournage ni studio.

Le modèle phare actuel est Avatar V, sorti en mai 2026 et aujourd''hui le plus réaliste chez HeyGen. Il se crée à partir d''un seul enregistrement de 15 secondes et ajoute le mouvement de tout le haut du corps, la cohérence sous plusieurs angles et une stabilité d''identité sur les formats longs, si bien que le même avatar reste crédible sur des scripts étendus. La génération multi-look permet de changer de tenue ou d''arrière-plan tout en conservant le mouvement d''origine. Seedance 2.0 est désormais intégré pour une génération vidéo plus cinématographique, et la couverture linguistique atteint plus de 175 langues sur les offres payantes (30+ sur la version gratuite).

Au-delà des avatars, la boîte à outils comprend le clonage de voix, la traduction vidéo avec synchronisation labiale, une bibliothèque de plus de 500 avatars préexistants et une API pour la génération programmatique.

Les tarifs reposent désormais sur un système de crédits à cinq niveaux. Free : 0 $/mois (3 vidéos/mois, jusqu''à 1 minute chacune, 1 jumeau numérique, 30+ langues). Creator : 29 $/mois (24 $ en facturation annuelle), 600 crédits, vidéos jusqu''à 30 minutes, 1080p, clonage de voix et 175+ langues. Pro : 49 $/mois, 1 000 crédits, 4K et paliers de crédits évolutifs. Business : 149 $/mois plus 20 $ par siège supplémentaire, 1 500 crédits, vidéos jusqu''à 60 minutes, 5 jumeaux numériques, SSO/SAML et LMS. Enterprise : tarif sur mesure.

La principale limite est la consommation de crédits : les vidéos studio avec Avatar IV/V coûtent environ 20 crédits par minute, bien plus vite que les anciens avatars, et la traduction avec synchronisation labiale environ 5 crédits par minute, si bien qu''un usage intensif épuise vite les quotas. Des packs additionnels (par exemple 300 crédits pour 15 $/mois) et l''API (~0,05 $/seconde pour Avatar V) comblent l''écart.

HeyGen convient aux équipes marketing, formation et localisation ainsi qu''aux créateurs qui ont besoin de vidéos de présentateur fréquentes sans tournage et qui peuvent travailler dans un budget de crédits.', pros=ARRAY['Avatar V (mai 2026) produit des avatars très réalistes à partir de seulement 15 secondes d''enregistrement, avec mouvement du buste et cohérence entre les angles','La génération multi-look réutilise un enregistrement pour changer de tenue ou d''arrière-plan tout en gardant un mouvement naturel','Plus de 175 langues sur les offres payantes avec traduction synchronisée, utile pour la localisation à grande échelle','Offre gratuite généreuse (3 vidéos/mois, 1 jumeau numérique) pour tester la plateforme','API avec tarif à la seconde (~0,05 $/s pour Avatar V) pour des flux automatisés à fort volume']::text[], cons=ARRAY['Les vidéos Avatar IV/V consomment vite les crédits (~20 crédits/min), donc les quotas mensuels s''épuisent rapidement en usage intensif','Le système de crédits rend le coût réel moins prévisible qu''un prix fixe par vidéo','L''offre gratuite limite les vidéos à 1 minute et à seulement 3 par mois','Le réalisme maximal et les vidéos longues exigent les niveaux Pro ou Business, et les paliers de crédits Pro grimpent jusqu''à plusieurs milliers de dollars','SSO/SAML et LMS ne sont disponibles qu''à partir du niveau Business']::text[], choose_if='["Vous avez besoin de vidéos de présentateur fréquentes sans tournage ni studio", "Vous voulez localiser du contenu dans de nombreuses langues avec synchronisation labiale", "Vous pouvez créer rapidement un jumeau numérique à partir d''un court enregistrement", "Vous avez des besoins d''API ou d''automatisation et pouvez budgétiser la génération à la seconde", "Vous voulez commencer gratuitement avant de passer à une offre de crédits payante"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='fr';
UPDATE tools SET badge='freemium', description='HeyGen é uma plataforma de vídeo com IA para criar vídeos com avatares, clonagem de voz e tradução. Seu modelo principal atual, o Avatar V (maio de 2026), gera um gêmeo digital realista a partir de uma gravação de 15 segundos.', description_long='HeyGen é uma plataforma que funciona no navegador para produzir vídeos apresentados por avatares de IA. Você digita ou cola um roteiro, escolhe ou cria um avatar, seleciona uma voz e o sistema gera um vídeo de apresentador sem equipe de filmagem nem estúdio.

O modelo principal atual é o Avatar V, lançado em maio de 2026 e hoje o mais realista da HeyGen. Ele é criado a partir de uma única gravação de 15 segundos e acrescenta movimento de toda a parte superior do corpo, consistência em vários ângulos e estabilidade de identidade em formatos longos, de modo que o mesmo avatar continua convincente em roteiros extensos. A geração multi-look permite trocar a roupa ou o fundo preservando o movimento original. Além disso, o Seedance 2.0 foi integrado para uma geração de vídeo mais cinematográfica, e a cobertura de idiomas cresceu para mais de 175 nos planos pagos (30+ no gratuito).

Além dos avatares, o conjunto básico inclui clonagem de voz, tradução de vídeo com sincronização labial, uma biblioteca com mais de 500 avatares prontos e uma API para geração programática.

Os preços agora funcionam com um sistema de créditos em cinco níveis. Free: US$ 0/mês (3 vídeos/mês, até 1 minuto cada, 1 gêmeo digital, 30+ idiomas). Creator: US$ 29/mês (US$ 24 na cobrança anual), 600 créditos, vídeos de até 30 minutos, 1080p, clonagem de voz e 175+ idiomas. Pro: US$ 49/mês, 1.000 créditos, 4K e faixas de crédito escaláveis. Business: US$ 149/mês mais US$ 20 por assento adicional, 1.500 créditos, vídeos de até 60 minutos, 5 gêmeos digitais, SSO/SAML e LMS. Enterprise: preço sob medida.

A principal limitação é o consumo de créditos: vídeos de estúdio com Avatar IV/V custam cerca de 20 créditos por minuto, bem mais rápido que os avatares antigos, e a tradução com sincronização labial gira em torno de 5 créditos por minuto, então quem usa intensamente esgota as cotas rapidamente. Pacotes adicionais (por exemplo, 300 créditos por US$ 15/mês) e a API (~US$ 0,05/segundo para o Avatar V) cobrem a diferença.

A HeyGen atende equipes de marketing, treinamento e localização, além de criadores que precisam de vídeos de apresentador com frequência sem filmar e que conseguem trabalhar dentro de um orçamento de créditos.', pros=ARRAY['O Avatar V (maio de 2026) produz avatares muito realistas a partir de apenas 15 segundos de gravação, com movimento do tronco e consistência entre ângulos','A geração multi-look reaproveita uma gravação para trocar roupa ou fundo mantendo o movimento natural','Mais de 175 idiomas nos planos pagos com tradução sincronizada, útil para localização em larga escala','Plano gratuito generoso (3 vídeos/mês, 1 gêmeo digital) para testar a plataforma','API com preço por segundo (~US$ 0,05/s para o Avatar V) para fluxos automatizados de alto volume']::text[], cons=ARRAY['Vídeos com Avatar IV/V consomem créditos rápido (~20 créditos/min), então as cotas mensais se esgotam logo em uso intenso','O sistema de créditos torna o custo real menos previsível que um preço fixo por vídeo','O plano gratuito limita os vídeos a 1 minuto e apenas 3 por mês','Realismo máximo e vídeos longos exigem os níveis Pro ou Business, e as faixas de crédito do Pro chegam a milhares de dólares','SSO/SAML e LMS só estão disponíveis a partir do nível Business']::text[], choose_if='["Você precisa de vídeos de apresentador com frequência sem filmar nem usar estúdio", "Você quer localizar conteúdo em muitos idiomas com sincronização labial", "Você consegue criar um gêmeo digital rápido a partir de uma gravação curta", "Você tem necessidades de API ou automação e pode orçar a geração por segundo", "Você quer começar de graça antes de migrar para um plano de créditos pago"]'::jsonb, last_updated=CURRENT_DATE WHERE slug='heygen' AND lang='pt';
