#!/usr/bin/env python3
"""Generate SQL for Spanish (lang=es) translations of choose_if and faq. Batch 4/4 (comparisons 91-117)."""

import json, sys

DATA_ES = {
"gamma-vs-prezi": {
  "a": "Gamma", "b": "Prezi",
  "choose_a": ["✅ Quieres generar una presentación completa desde texto con IA en minutos — Gamma es el líder en velocidad de creación","✅ Necesitas crear documentos web y páginas interactivas además de slides en la misma herramienta","✅ Publicas como enlace web o PDF sin necesitar software de presentación instalado","✅ Priorizas la velocidad y la IA sobre la narrativa visual no lineal"],
  "choose_b": ["✅ Quieres presentaciones con zoom dinámico y navegación no lineal — ideal para contar historias visuales únicas","✅ Creas presentaciones de conferencia o charlas TED donde la estructura no lineal añade impacto narrativo","✅ Necesitas que la audiencia recuerde tu presentación por su formato visual diferente al PowerPoint tradicional","✅ Trabajas en entornos educativos donde el zoom hacia el detalle ayuda a explicar conceptos complejos"],
  "faq": [{"q":"¿Gamma o Prezi para presentaciones educativas?","a":"Prezi puede ser más memorable para presentaciones donde la estructura espacial ayuda a entender relaciones entre conceptos (mapas mentales, timelines). Gamma es más rápido para crear y mejor para texto e imágenes generados por IA. Para profesores con poco tiempo — Gamma; para presentaciones educativas visuales únicas — Prezi."},{"q":"¿Prezi es gratuito?","a":"Prezi tiene un plan gratuito con 5 presentaciones públicas. Los planes de pago empiezan desde $5/mes (Student) o $15/mes (Standard). Gamma tiene plan gratuito con 400 créditos; planes desde $10/mes."},{"q":"¿Prezi funciona sin conexión?","a":"Prezi tiene una app de escritorio (Prezi Desktop) disponible en planes de pago que permite trabajar y presentar sin internet. Gamma requiere conexión a internet para generación IA; las presentaciones pueden visualizarse offline como PDF exportado."},{"q":"¿Gamma puede hacer el efecto zoom de Prezi?","a":"No. Gamma genera presentaciones con estilo de slides tradicional mejoradas con diseño IA. El zoom dinámico espacial es la característica distintiva de Prezi y no está replicado en Gamma. Para narrativa con zoom — Prezi es único en el mercado."}]
},
"beautiful-ai-vs-pitch": {
  "a": "Beautiful.ai", "b": "Pitch",
  "choose_a": ["✅ Quieres que el diseño de tus slides se ajuste automáticamente sin romperse cuando añades contenido","✅ Necesitas presentaciones con diseño consistente y profesional sin contratar un diseñador","✅ Produces presentaciones de ventas, informes y updates de negocio donde la consistencia visual importa","✅ Prefieres que la IA gestione el layout automáticamente mientras te centras en el contenido"],
  "choose_b": ["✅ Tu equipo de startup necesita colaborar en tiempo real en pitch decks con comentarios y feedback integrado","✅ Quieres templates específicamente diseñados para pitch decks de inversión y presentaciones de VC","✅ Necesitas versiones de presentación con analíticas: saber cuánto tiempo vio cada slide el receptor","✅ Buscas una herramienta con culture de startup y diseño moderno orientada a fundadores y equipos de producto"],
  "faq": [{"q":"¿Beautiful.ai o Google Slides para equipos?","a":"Beautiful.ai tiene diseño automático superior — los slides se ajustan solos. Google Slides tiene colaboración más familiar y es gratuito. Para calidad de diseño sin esfuerzo — Beautiful.ai. Para colaboración sencilla sin costo — Google Slides. Muchos equipos usan Google Slides para borradores y Beautiful.ai para versiones finales."},{"q":"¿Cuánto cuesta Beautiful.ai?","a":"Beautiful.ai tiene una prueba gratuita de 14 días. Los planes de pago empiezan desde $12/mes (Pro). Pitch tiene plan gratuito con presentaciones ilimitadas; planes de team desde $25/mes."},{"q":"¿Pitch tiene IA para generar slides?","a":"Pitch tiene funciones de IA para sugerir contenido y mejorar texto. Para generación completa de presentaciones desde texto — Gamma es más potente. Pitch prioriza la colaboración de equipo y el diseño de calidad; la generación IA es secundaria."},{"q":"¿Beautiful.ai puede exportar a PowerPoint?","a":"Sí. Beautiful.ai permite exportar a PDF y PowerPoint. Esto facilita compartir con personas que no tienen cuenta de Beautiful.ai. La calidad del export a PowerPoint es buena, aunque algunas animaciones automáticas pueden simplificarse en la conversión."}]
},
"slidesgo-vs-gamma": {
  "a": "Slidesgo", "b": "Gamma",
  "choose_a": ["✅ Necesitas plantillas profesionales y gratuitas para Google Slides o PowerPoint en minutos sin generar contenido desde cero","✅ Tienes el contenido listo y solo necesitas una plantilla atractiva para presentarlo visualmente","✅ Buscas la mayor biblioteca gratuita de plantillas de presentación: +20.000 diseños para cualquier tema","✅ Eres estudiante o docente que necesita presentaciones bien diseñadas con templates listos para educación"],
  "choose_b": ["✅ Quieres generar toda la presentación — estructura, contenido y diseño — desde una descripción de texto con IA","✅ No tienes el contenido preparado y necesitas que la IA lo cree desde un tema o brief","✅ Necesitas publicar como página web interactiva o documento, no solo como presentación de slides","✅ Priorizas la velocidad total: de idea a presentación en minutos sin seleccionar plantillas manualmente"],
  "faq": [{"q":"¿Slidesgo es gratuito?","a":"Slidesgo tiene miles de plantillas gratuitas accesibles sin registro. Slidesgo Premium ($7.99/mes) desbloquea todas las plantillas y funciones avanzadas. Gamma tiene plan gratuito con 400 créditos; planes desde $10/mes. Para plantillas gratis — Slidesgo; para generación IA de contenido — Gamma."},{"q":"¿Slidesgo tiene IA?","a":"Slidesgo tiene Slidesgo AI Presentation Maker que genera presentaciones desde un prompt de texto, similar a Gamma pero con menor potencia de IA. La principal fortaleza de Slidesgo son sus templates de diseño para Google Slides y PowerPoint, no la generación de contenido."},{"q":"¿Qué es mejor, Slidesgo o Canva para presentaciones?","a":"Canva tiene más funciones de diseño personalizable y herramientas de IA más potentes. Slidesgo se especializa en plantillas para Google Slides y PowerPoint específicamente. Para diseño personalizado completo — Canva; para plantillas de calidad directamente en Google Slides — Slidesgo."},{"q":"¿Gamma reemplaza a PowerPoint?","a":"Gamma no exporta a PowerPoint de la misma forma (aunque tiene export a PDF). Funciona mejor como alternativa web a PowerPoint — sus presentaciones se comparten como links. Para contextos donde se requiere un archivo .pptx, PowerPoint, Canva o Google Slides siguen siendo necesarios."}]
},
"tradingview-vs-fiscal-ai": {
  "a": "TradingView", "b": "FinChat",
  "choose_a": ["✅ Necesitas los mejores gráficos de análisis técnico del mercado: indicadores, herramientas de dibujo, backtesting de estrategias","✅ Eres trader activo que opera en bolsa, forex o cripto y necesita análisis de precio en tiempo real","✅ Quieres acceso a la mayor red social de traders: ver ideas, estrategias y análisis de otros inversores","✅ Necesitas alertas de precio y señales técnicas configurables para cualquier activo financiero"],
  "choose_b": ["✅ Quieres analizar fundamentales de empresas usando IA: hacer preguntas sobre estados financieros, earnings y KPIs","✅ Necesitas leer y resumir earnings calls, reportes anuales y presentaciones de inversores con asistente IA","✅ Eres inversor de largo plazo que necesita análisis fundamental profundo, no análisis técnico de precio","✅ Quieres comparar métricas financieras de múltiples empresas con IA que explica los datos"],
  "faq": [{"q":"¿TradingView o Bloomberg para traders?","a":"Bloomberg es la herramienta profesional institucional ($2.000+/mes). TradingView es la mejor opción para traders retail e inversores individuales — mejores gráficos del mercado consumer a un precio accesible. Para traders no institucionales, TradingView es el estándar de facto."},{"q":"¿TradingView es gratuito?","a":"TradingView tiene un plan gratuito con funciones básicas (3 indicadores por gráfico, 1 alerta). Los planes de pago (Essential $12.95/mes, Plus $24.95/mes, Premium $49.95/mes) desbloquean más indicadores, alertas y funciones. FinChat tiene plan gratuito limitado; Pro desde $17/mes."},{"q":"¿Qué es FinChat?","a":"FinChat (anteriormente conocido como Fiscal AI) es una plataforma de análisis financiero con IA. Permite hacer preguntas en lenguaje natural sobre empresas públicas: 'cuál fue el margen bruto de Apple en Q3 2024', analizar earnings calls y comparar métricas financieras entre competidores."},{"q":"¿TradingView tiene análisis fundamental?","a":"TradingView tiene datos fundamentales básicos (P/E, EPS, ingresos) pero no está especializado en análisis fundamental profundo. Para análisis fundamental serio — FinChat, Koyfin o Tikr son más completos. TradingView es imbatible en análisis técnico y gráficos."}]
},
"koyfin-vs-tradingview": {
  "a": "Koyfin", "b": "TradingView",
  "choose_a": ["✅ Necesitas análisis fundamental gratuito completo: estados financieros históricos, métricas de valoración, datos macroeconómicos","✅ Eres inversor de largo plazo que quiere dashboards de datos financieros de empresas sin pagar Bloomberg","✅ Quieres comparar métricas financieras entre empresas del mismo sector de forma visual e intuitiva","✅ Necesitas acceso a datos macroeconómicos globales: tipos de interés, PIB, inflación, datos de banco central"],
  "choose_b": ["✅ Necesitas los mejores gráficos de análisis técnico del mercado con indicadores avanzados y herramientas de trading","✅ Eres trader activo que opera en bolsa, forex o cripto y necesita análisis de precio en tiempo real","✅ Quieres ser parte de la mayor comunidad de traders: publicar ideas, ver análisis y estrategias de otros","✅ Necesitas alertas de precio personalizadas y backtesting de estrategias técnicas"],
  "faq": [{"q":"¿Koyfin es gratuito?","a":"Sí. Koyfin tiene un plan gratuito muy completo con acceso a estados financieros, métricas de valoración y datos macroeconómicos. El plan Pro ($49/mes) añade datos más avanzados y mayor personalización. Es una de las mejores alternativas gratuitas a Bloomberg para inversores fundamentales."},{"q":"¿Koyfin vs Tikr para análisis fundamental?","a":"Koyfin tiene mejor interfaz y dashboards más visuales. Tikr tiene más datos históricos y profundidad de datos financieros. Koyfin es más popular entre inversores individuales por su experiencia de usuario; Tikr entre analistas que necesitan datos más detallados. Ambas son excelentes alternativas gratuitas a Bloomberg."},{"q":"¿TradingView tiene datos fundamentales?","a":"TradingView incluye datos fundamentales básicos pero no es su punto fuerte. Para análisis fundamental profundo (10-K, earnings históricos, múltiplos de valoración) — Koyfin, FinChat o Tikr son más completos. TradingView es imbatible en análisis técnico y gráficos de precio."},{"q":"¿Koyfin tiene datos de renta fija?","a":"Koyfin tiene datos de bonos del tesoro y algunos datos de tipos de interés. Para análisis profundo de renta fija — Bloomberg Terminal sigue siendo el estándar profesional. Koyfin es excelente para renta variable; más limitado para renta fija institucional."}]
},
"fiscal-ai-vs-koyfin": {
  "a": "FinChat", "b": "Koyfin",
  "choose_a": ["✅ Quieres hacer preguntas en lenguaje natural sobre los financieros de cualquier empresa pública con IA que entiende el contexto","✅ Necesitas analizar earnings calls rápidamente: la IA resume los puntos clave y responde preguntas específicas","✅ Buscas la forma más rápida de extraer datos específicos de reportes financieros sin leer documentos completos","✅ Quieres comparar KPIs entre empresas competidoras con asistente IA que explica las diferencias"],
  "choose_b": ["✅ Necesitas dashboards de datos financieros visuales y completos para seguimiento de un portfolio o sector","✅ Quieres acceso gratuito a estados financieros históricos, métricas de valoración y datos macroeconómicos","✅ Necesitas datos macroeconómicos globales integrados con análisis de empresas en la misma plataforma","✅ Prefieres explorar datos de forma visual con gráficos interactivos sin hacer preguntas en lenguaje natural"],
  "faq": [{"q":"¿Qué es FinChat y cómo funciona?","a":"FinChat es una plataforma de análisis financiero con IA. Indexa los documentos financieros de miles de empresas públicas (10-K, 10-Q, earnings calls) y permite hacer preguntas en lenguaje natural: '¿cuánto gastó Microsoft en I+D en 2024?', '¿cuáles son los principales riesgos mencionados en el 10-K de Nvidia?'. La IA responde citando la fuente exacta."},{"q":"¿FinChat es gratuito?","a":"FinChat tiene un plan gratuito con acceso limitado a preguntas y empresas. El plan Pro ($17/mes) ofrece acceso completo a todas las empresas, preguntas ilimitadas y funciones avanzadas. Koyfin tiene plan gratuito más completo para datos de mercado generales."},{"q":"¿FinChat puede analizar empresas privadas?","a":"FinChat está principalmente enfocado en empresas públicas con documentos regulatorios disponibles (SEC filings). Para empresas privadas sin documentos públicos, las capacidades son limitadas. Koyfin también se centra en empresas públicas."},{"q":"¿Koyfin o FinChat para principiantes en inversión?","a":"Koyfin es más amigable para principiantes — dashboards visuales intuitivos con datos financieros organizados. FinChat requiere saber qué preguntas hacer para sacarle partido. Para aprender análisis fundamental explorando datos — Koyfin; para respuestas rápidas sobre documentos financieros — FinChat."}]
},
"tickeron-vs-tradingview": {
  "a": "Tickeron", "b": "TradingView",
  "choose_a": ["✅ Quieres predicciones y señales de trading generadas por IA: Tickeron usa IA para identificar patrones y dar señales de compra/venta","✅ Necesitas backtesting automático de estrategias con IA sin programar indicadores manualmente","✅ Buscas un asistente de IA (AI Robots) que ejecute estrategias de trading según condiciones predefinidas","✅ Quieres reconocimiento automático de patrones técnicos (cabeza y hombros, triángulos, etc.) sin analizarlos manualmente"],
  "choose_b": ["✅ Necesitas los gráficos de análisis técnico más potentes y personalizables del mercado","✅ Quieres la mayor comunidad de traders para ver ideas, estrategias y análisis de miles de usuarios","✅ Eres trader que prefiere hacer su propio análisis con herramientas profesionales sin depender de señales IA","✅ Necesitas alertas de precio altamente configurables y backtesting manual de estrategias propias"],
  "faq": [{"q":"¿Tickeron es fiable para señales de trading?","a":"Las señales de IA de Tickeron muestran resultados históricos pero, como toda predicción de mercado, no garantizan rentabilidad futura. Tickeron es transparente sobre la precisión histórica de sus patrones. Para traders que quieren asistencia IA — útil como referencia; para trading real — siempre requiere criterio propio."},{"q":"¿Tickeron es gratuito?","a":"Tickeron tiene un plan gratuito limitado. Los planes de pago empiezan desde $17/mes con acceso a más funciones de IA y señales. TradingView tiene plan gratuito sólido; planes de pago desde $12.95/mes."},{"q":"¿TradingView tiene IA?","a":"TradingView ha incorporado funciones de IA básicas, pero no es su punto fuerte — su ventaja es en gráficos y comunidad. Tickeron está especializado en IA para trading: patrones automáticos, señales y robots de trading. Para análisis técnico propio — TradingView; para señales IA — Tickeron."},{"q":"¿Cuáles son los mejores indicadores de TradingView?","a":"Los indicadores más populares en TradingView son: RSI, MACD, Bollinger Bands, EMA (medias móviles), Volume Profile y Fibonacci. TradingView tiene miles de indicadores de la comunidad además de los estándar. Puedes programar tus propios indicadores con Pine Script."}]
},
"uptrends-ai-vs-koyfin": {
  "a": "Uptrends AI", "b": "Koyfin",
  "choose_a": ["✅ Quieres inteligencia de mercado sobre tendencias de inversión: qué sectores y activos están ganando momentum","✅ Necesitas alertas y análisis de sentimiento de mercado impulsados por IA para identificar oportunidades","✅ Buscas una herramienta especializada en detectar tendencias emergentes antes de que sean mainstream","✅ Quieres análisis de flujo de capital institucional y movimientos de smart money con IA"],
  "choose_b": ["✅ Necesitas análisis fundamental completo y gratuito: estados financieros, métricas de valoración, comparación de empresas","✅ Quieres dashboards visuales de datos financieros para seguimiento de portfolio y análisis de sectores","✅ Necesitas datos macroeconómicos integrados con análisis de renta variable en una sola plataforma","✅ Buscas la mejor alternativa gratuita a Bloomberg para inversión fundamental en renta variable"],
  "faq": [{"q":"¿Qué es Uptrends AI?","a":"Uptrends AI es una plataforma de análisis de tendencias de mercado que usa IA para identificar qué activos, sectores y temáticas de inversión están ganando momentum. Se enfoca en la detección temprana de tendencias emergentes, diferenciándose de herramientas de análisis fundamental como Koyfin."},{"q":"¿Uptrends AI es gratuito?","a":"Uptrends AI tiene acceso gratuito limitado. Los planes de pago varían según las funciones de análisis de tendencias. Koyfin tiene un plan gratuito más completo para análisis fundamental de empresas."},{"q":"¿Koyfin o Uptrends para inversores value?","a":"Koyfin es claramente mejor para inversión value — tiene estados financieros, ratios de valoración históricos, P/E, EV/EBITDA y todas las métricas que un inversor value necesita gratuitamente. Uptrends es más útil para inversores de momentum que siguen tendencias."},{"q":"¿Pueden usarse Koyfin y Uptrends juntos?","a":"Sí. Son complementarias: Uptrends para identificar tendencias y sectores con momentum, Koyfin para analizar fundamentalmente las empresas dentro de esos sectores. Muchos inversores usan herramientas de momentum para el filtrado inicial y herramientas fundamentales para el análisis profundo."}]
},
"amazon-q-developer-vs-github-copilot": {
  "a": "Amazon Q Developer", "b": "GitHub Copilot",
  "choose_a": ["✅ Tu stack está en AWS: Lambda, EC2, DynamoDB, CloudFormation — Amazon Q entiende el ecosistema AWS profundamente","✅ Necesitas asistencia para infraestructura como código: Q puede generar y explicar plantillas de CloudFormation y CDK","✅ Quieres un asistente IA integrado en la consola de AWS para entender errores, optimizar costos y configurar servicios","✅ Buscas análisis de seguridad de código especializado en vulnerabilidades AWS y mejores prácticas cloud"],
  "choose_b": ["✅ Necesitas el asistente de código más popular con el mayor soporte de IDEs: VS Code, JetBrains, Neovim, Visual Studio","✅ Tu trabajo no está centrado en AWS — necesitas asistencia general en cualquier lenguaje y cualquier stack","✅ Quieres la mejor experiencia de autocompletado en línea y generación de código en el editor","✅ Necesitas Copilot Chat para preguntas de código general, revisión de PRs en GitHub y generación de tests"],
  "faq": [{"q":"¿Amazon Q Developer es gratuito?","a":"Amazon Q Developer tiene un plan gratuito con 50 respuestas de chat y análisis de código al mes. El plan Pro ($19/usuario/mes) desbloquea uso ilimitado. GitHub Copilot tiene plan Individual ($10/mes) y Business ($19/usuario/mes). Copilot tiene prueba gratuita de 30 días; Q Developer tiene tier gratuito permanente."},{"q":"¿Amazon Q puede reemplazar a GitHub Copilot?","a":"Para proyectos AWS — Q Developer tiene ventaja por su profundo conocimiento del ecosistema Amazon. Para proyectos no-AWS — GitHub Copilot es más completo y versátil. Para equipos mixtos o proyectos multi-cloud — Copilot es la opción más segura."},{"q":"¿Amazon Q Developer habla español?","a":"Amazon Q Developer puede responder en español cuando se le hace la pregunta en español. Sin embargo, la mayor parte de su documentación de entrenamiento es en inglés, por lo que las respuestas técnicas suelen ser más precisas en inglés."},{"q":"¿Qué IDEs soporta Amazon Q Developer?","a":"Amazon Q Developer está integrado en VS Code, JetBrains IDEs (IntelliJ, PyCharm, etc.), AWS Cloud9, AWS Lambda console y la CLI de AWS. GitHub Copilot tiene soporte en más IDEs, incluyendo Visual Studio, Neovim y Xcode."}]
},
"continue-dev-vs-github-copilot": {
  "a": "Continue.dev", "b": "GitHub Copilot",
  "choose_a": ["✅ Quieres un asistente de código open-source que funcione con cualquier modelo: Claude, GPT-4, modelos locales (Ollama, LM Studio)","✅ Necesitas control total sobre el modelo que usa tu asistente de código — sin dependencia de un proveedor único","✅ Quieres usar modelos de código localmente para privacidad total de tu código sin enviar nada a la nube","✅ Eres desarrollador con preocupaciones de privacidad de código o en una empresa sin política de IA de terceros aprobada"],
  "choose_b": ["✅ Quieres la mejor experiencia de autocompletado de código con el menor tiempo de configuración posible","✅ Necesitas la herramienta con mayor soporte comunitario, tutoriales y el mayor ecosistema de usuarios","✅ Usas GitHub intensamente — Copilot está integrado en PRs, issues y revisión de código directamente en GitHub","✅ Prefieres pagar por un servicio gestionado con alta disponibilidad garantizada sin gestionar infraestructura"],
  "faq": [{"q":"¿Continue.dev es gratuito?","a":"Continue.dev es completamente open-source y gratuito como extensión. El costo depende del modelo que uses: si usas Ollama con modelos locales (Llama, Mistral) — completamente gratuito. Si usas la API de Anthropic o OpenAI — pagas por el uso de la API. GitHub Copilot cuesta $10/mes."},{"q":"¿Continue.dev puede usar Claude?","a":"Sí. Continue.dev se integra con la API de Anthropic, OpenAI, Mistral, Google Gemini y modelos locales via Ollama. Puedes configurar Claude como el modelo para chat y autocompletado, pagando directamente a Anthropic por el uso de API."},{"q":"¿Es seguro usar GitHub Copilot con código propietario?","a":"GitHub Copilot envía fragmentos de código a los servidores de GitHub/Microsoft para generar sugerencias. Para código propietario sensible, muchas empresas tienen políticas que requieren Copilot Business/Enterprise con garantías de no uso de datos para entrenamiento. Continue.dev con modelos locales elimina este problema completamente."},{"q":"¿Continue.dev soporta JetBrains?","a":"Continue.dev tiene plugins para VS Code y JetBrains IDEs. GitHub Copilot también soporta ambos. Para usuarios de IntelliJ, PyCharm, etc. — ambas herramientas están disponibles."}]
},
"opencode-vs-claude-code": {
  "a": "OpenCode", "b": "Claude Code",
  "choose_a": ["✅ Quieres un agente de código de terminal open-source que funcione con múltiples modelos (Claude, GPT-4, modelos locales)","✅ Necesitas un agente de código sin dependencia de un único proveedor de IA — total flexibilidad de modelo","✅ Prefieres contribuir a o modificar el agente de código según tus necesidades específicas","✅ Buscas una alternativa open-source a Claude Code con filosofía de código abierto y comunidad activa"],
  "choose_b": ["✅ Quieres el agente de código más capaz del mercado para tareas complejas de ingeniería de software","✅ Priorizas la mejor calidad de razonamiento para refactorizar código, encontrar bugs y añadir funcionalidades","✅ Necesitas un agente que gestione repositorios completos con contexto profundo del codebase","✅ Usas ya Claude a diario y quieres la integración más profunda con el modelo Anthropic en terminal"],
  "faq": [{"q":"¿Qué es OpenCode?","a":"OpenCode es un agente de código de terminal open-source inspirado en Claude Code. Funciona con múltiples modelos de IA (Claude, GPT-4, modelos locales) y puede realizar tareas de desarrollo autónomas: leer código, hacer cambios, ejecutar tests. Es la alternativa open-source más directa a Claude Code."},{"q":"¿Claude Code es gratuito?","a":"Claude Code requiere una suscripción de Claude (Pro $20/mes o Max $100-$200/mes). El uso intensivo de Claude Code consume créditos de API rápidamente. OpenCode es gratuito como herramienta, pero el costo depende del modelo API que uses."},{"q":"¿OpenCode es tan bueno como Claude Code?","a":"Claude Code tiene ventaja en calidad de razonamiento al estar optimizado específicamente para Claude 3.7/3.5. OpenCode es más flexible al soportar múltiples modelos. Para la mejor calidad absoluta — Claude Code con Claude Sonnet; para flexibilidad y open-source — OpenCode."},{"q":"¿Claude Code puede trabajar con cualquier lenguaje de programación?","a":"Sí. Claude Code entiende prácticamente cualquier lenguaje de programación moderno: Python, JavaScript/TypeScript, Go, Rust, Java, C++, Ruby, etc. Su ventaja es el razonamiento sobre el codebase completo, no solo snippets individuales."}]
},
"zed-vs-cursor": {
  "a": "Zed", "b": "Cursor",
  "choose_a": ["✅ Priorizas el rendimiento del editor — Zed es el editor de código más rápido disponible, construido en Rust con velocidad nativa","✅ Quieres colaboración multiplayer en tiempo real integrada en el editor, como Google Docs pero para código","✅ Necesitas un editor con IA (Zed AI) que no sacrifique velocidad ni rendimiento del editor base","✅ Eres desarrollador que valora la eficiencia del editor tanto como las capacidades de IA"],
  "choose_b": ["✅ Quieres las capacidades de IA más avanzadas integradas en el editor: autocompletado predictivo, edición de múltiples archivos simultáneos","✅ Necesitas Cursor Composer para hacer cambios en múltiples archivos con una sola instrucción de lenguaje natural","✅ Quieres el contexto completo del codebase disponible para el asistente IA sin configuración adicional","✅ Buscas la herramienta más productiva para desarrollo con IA aunque el editor sea menos rápido que Zed puro"],
  "faq": [{"q":"¿Zed o VS Code para desarrollo?","a":"Zed es significativamente más rápido que VS Code — lanzamiento instantáneo, sin lag en archivos grandes. VS Code tiene ecosistema de extensiones mucho mayor. Cursor está basado en VS Code. Para velocidad pura — Zed; para mayor ecosistema — VS Code o Cursor."},{"q":"¿Zed es gratuito?","a":"Zed es gratuito y open-source. Las funciones de IA (Zed AI) usan la API de Anthropic o pueden configurarse con otros modelos. Cursor tiene plan gratuito con 2.000 autocompletados; Pro ($20/mes) para uso ilimitado."},{"q":"¿Zed está disponible en Windows?","a":"Zed empezó como exclusivo de macOS pero lanzó soporte para Linux. El soporte para Windows está en desarrollo activo pero puede no estar completamente estable. Cursor está disponible en macOS, Windows y Linux."},{"q":"¿Qué es Cursor Composer?","a":"Cursor Composer (ahora llamado Cursor Agent) es la función más potente de Cursor — permite describir en lenguaje natural cambios que afectan múltiples archivos simultáneamente y Cursor los implementa. Es la diferencia clave frente a otros editores con IA que solo trabajan en el archivo activo."}]
},
"comfyui-vs-stable-diffusion": {
  "a": "ComfyUI", "b": "Stable Diffusion (AUTOMATIC1111)",
  "choose_a": ["✅ Quieres crear flujos de generación de imágenes complejos con nodos visuales: encadenar modelos, ControlNet, upscalers y múltiples pasos","✅ Necesitas mayor control técnico sobre el proceso de generación: latentes, schedulers, condicionales avanzados","✅ Experimentas con flujos de trabajo avanzados: inpainting complejo, image-to-image con transformaciones múltiples, video con AnimateDiff","✅ Eres usuario técnico que quiere entender y controlar cada paso del proceso de difusión"],
  "choose_b": ["✅ Buscas la interfaz más accesible para generar imágenes con Stable Diffusion con la menor curva de aprendizaje","✅ Necesitas acceso rápido a la mayor biblioteca de modelos y LoRAs de CivitAI con instalación fácil de extensiones","✅ Usas funciones básicas de txt2img, img2img y outpainting sin necesitar flujos de trabajo complejos de nodos","✅ Prefieres la interfaz web tradicional sobre el paradigma de nodos visuales de ComfyUI"],
  "faq": [{"q":"¿ComfyUI o AUTOMATIC1111 para principiantes?","a":"AUTOMATIC1111 es mucho más accesible para principiantes — interfaz web familiar con pestañas y sliders. ComfyUI tiene una curva de aprendizaje más pronunciada con su sistema de nodos. Para empezar con Stable Diffusion — AUTOMATIC1111 (o Forge, su fork mejorado); para flujos avanzados — ComfyUI."},{"q":"¿ComfyUI es gratuito?","a":"Sí. ComfyUI es completamente open-source y gratuito. AUTOMATIC1111 también es gratuito y open-source. Ambos requieren hardware propio (GPU Nvidia recomendada) o pueden usarse en servicios cloud como Google Colab o RunPod a precios por hora."},{"q":"¿Qué es Forge (SD Web UI Forge)?","a":"Forge es un fork de AUTOMATIC1111 optimizado para mayor velocidad y menor uso de VRAM. Mantiene la misma interfaz familiar pero con mejor rendimiento. Para usuarios de AUTOMATIC1111 que quieren mejor velocidad sin aprender ComfyUI — Forge es la mejor opción intermedia."},{"q":"¿ComfyUI puede usar modelos FLUX?","a":"Sí. ComfyUI fue la primera interfaz en soportar FLUX.1 y sigue siendo la más flexible para flujos de trabajo con FLUX. AUTOMATIC1111/Forge también soporta FLUX. Para flujos FLUX avanzados con nodos — ComfyUI es la opción preferida de la comunidad."}]
},
"krea-ai-vs-midjourney": {
  "a": "Krea AI", "b": "Midjourney",
  "choose_a": ["✅ Quieres ver cómo evoluciona tu imagen en tiempo real mientras escribes el prompt — la generación en streaming de Krea es única","✅ Necesitas un canvas creativo interactivo donde puedes dibujar, añadir elementos y ver la IA interpretar tu boceto instantáneamente","✅ Produces video corto, flux y experimentos creativos donde la interactividad del proceso importa tanto como el resultado","✅ Buscas una experiencia de generación de imágenes más lúdica e interactiva, no solo ingresar prompt y esperar"],
  "choose_b": ["✅ Priorizas la máxima calidad artística en el resultado final — Midjourney V7 sigue siendo el estándar de calidad","✅ Produces imágenes para uso profesional donde la consistencia y calidad predecible son prioritarias","✅ Necesitas variedad de estilos artísticos establecidos con una gran comunidad de referencia","✅ Quieres el flujo de trabajo más directo: prompt → imagen de alta calidad, sin interfaces complejas"],
  "faq": [{"q":"¿Qué hace especial a Krea AI?","a":"Krea AI tiene una función única: generación en tiempo real. Mientras escribes el prompt o dibocas en el canvas, la imagen se actualiza instantáneamente con cada cambio. Esta experiencia iterativa y visual es completamente diferente al ciclo de espera de Midjourney u otros generadores."},{"q":"¿Krea AI es gratuito?","a":"Krea AI tiene un plan gratuito con generaciones limitadas. Los planes de pago empiezan desde $24/mes (Standard) con mayor resolución y generaciones ilimitadas. Midjourney no tiene plan gratuito; desde $10/mes."},{"q":"¿Krea AI puede generar video?","a":"Sí. Krea AI tiene función de generación de video además de imágenes. También puede hacer image-to-video y tiene herramientas de upscaling de video. La suite es más completa que solo generación de imágenes."},{"q":"¿Midjourney o Krea para diseño de producto?","a":"Para concepto de producto con máxima calidad artística — Midjourney. Para exploración rápida e iterativa donde necesitas ver múltiples variaciones en tiempo real — Krea. Muchos diseñadores de producto usan Krea para exploración rápida y Midjourney para renders finales."}]
},
"nano-banana-vs-leonardo-ai": {
  "a": "Nano Banana", "b": "Leonardo AI",
  "choose_a": ["✅ Quieres la herramienta de generación de imágenes IA más simple y accesible sin curva de aprendizaje","✅ Necesitas resultados rápidos con configuración mínima, sin seleccionar modelos ni ajustar parámetros","✅ Eres principiante en generación de imágenes IA que quiere explorar sin abrumarse con opciones técnicas","✅ Buscas una interfaz limpia y minimalista para generación de imágenes cotidiana"],
  "choose_b": ["✅ Necesitas activos de videojuegos, concept art y diseño de personajes con modelos especializados para game art","✅ Quieres el plan gratuito más generoso del mercado: 150 tokens diarios para explorar sin pagar","✅ Quieres entrenar modelos personalizados con tus propias imágenes para estilos únicos","✅ Produces contenido visual a escala con control de estilo, aspect ratios y modelos especializados"],
  "faq": [{"q":"¿Qué es Nano Banana?","a":"Nano Banana es una herramienta de generación de imágenes IA diseñada con simplicidad extrema como prioridad. Su propuesta es hacer accesible la generación de imágenes IA sin la complejidad técnica de otras plataformas. Está orientada a usuarios que quieren resultados rápidos sin aprender parámetros."},{"q":"¿Leonardo AI tiene plan gratuito?","a":"Sí. Leonardo AI tiene un plan gratuito muy generoso con 150 tokens diarios (cada imagen cuesta 1-8 tokens según el modelo y resolución). Esto permite generar decenas de imágenes al día sin pagar. Los planes de pago (desde $12/mes) añaden tokens ilimitados y funciones avanzadas."},{"q":"¿Leonardo AI es bueno para principiantes?","a":"Leonardo AI tiene más funciones que Nano Banana, pero tiene una interfaz razonablemente accesible. El plan gratuito generoso lo hace ideal para experimentar. Para principiantes absolutos — Nano Banana es más simple; para principiantes que quieren aprender más — Leonardo AI con su plan gratuito es excelente."},{"q":"¿Nano Banana vs Ideogram para imágenes simples?","a":"Ideogram tiene mejor reputación por calidad y generación de texto dentro de imágenes, con plan gratuito sólido. Nano Banana prioriza simplicidad. Para resultados de calidad con plan gratuito — Ideogram; para máxima simplicidad — Nano Banana."}]
},
"chatgpt-images-vs-adobe-firefly": {
  "a": "ChatGPT Images (DALL-E 3)", "b": "Adobe Firefly",
  "choose_a": ["✅ Quieres generar imágenes directamente dentro de tu conversación de ChatGPT sin cambiar de herramienta","✅ Usas ChatGPT Plus o Pro y tienes DALL-E 3 disponible sin costo adicional en tu suscripción","✅ Necesitas iterar imágenes conversacionalmente: 'hazla más oscura', 'añade una persona en el fondo' de forma natural","✅ Produces imágenes para uso personal, presentaciones o contenido donde la licencia comercial no es crítica"],
  "choose_b": ["✅ Necesitas imágenes con licencia comercial clara — Firefly está entrenado solo con imágenes con licencia de Adobe Stock","✅ Usas Photoshop y quieres Generative Fill para editar imágenes existentes de forma inteligente","✅ Trabajas en una empresa donde el departamento legal exige garantías de derechos de autor sobre las imágenes IA","✅ Produces contenido para campañas publicitarias, packaging o medios impresos donde la propiedad intelectual importa"],
  "faq": [{"q":"¿DALL-E 3 o Midjourney para calidad?","a":"Midjourney V7 sigue siendo superior en calidad artística general. DALL-E 3 es mejor en seguir instrucciones específicas y texto dentro de imágenes. DALL-E 3 está integrado en ChatGPT lo que facilita iteración conversacional. Para arte — Midjourney; para instrucciones precisas en chat — DALL-E 3."},{"q":"¿ChatGPT puede editar imágenes existentes?","a":"Sí. ChatGPT con DALL-E 3 puede editar imágenes existentes — seleccionar áreas para modificar, añadir o quitar elementos. Adobe Firefly (Generative Fill en Photoshop) es más potente para edición precisa de fotos. Para edición simple — ChatGPT; para edición profesional — Photoshop con Firefly."},{"q":"¿Las imágenes de DALL-E 3 son libres de derechos?","a":"Según los términos de OpenAI, los usuarios de pago tienen derechos sobre las imágenes generadas. Sin embargo, hay debate legal sobre los derechos de autor de imágenes generadas por IA. Para uso comercial con garantías claras — Adobe Firefly (entrenado con contenido con licencia) es la opción más segura legalmente."},{"q":"¿Adobe Firefly puede generar desde texto sin Photoshop?","a":"Sí. Adobe Firefly tiene una interfaz web (firefly.adobe.com) donde puedes generar imágenes desde texto sin necesitar Photoshop. Las funciones de Generative Fill e integración profunda sí requieren Photoshop. La web app tiene plan gratuito con créditos limitados."}]
},
"claude-design-vs-figma-ai": {
  "a": "Claude (design)", "b": "Figma AI",
  "choose_a": ["✅ Quieres generar código HTML/CSS/React de componentes de UI directamente desde una descripción sin abrir herramientas de diseño","✅ Necesitas que la IA diseñe y codifique simultáneamente — Claude genera componentes funcionales listos para implementar","✅ Usas Claude para iterar rápidamente conceptos de diseño en código sin el ciclo diseño → handoff → código","✅ Eres desarrollador que prefiere trabajar directamente en código y usar IA para el diseño visual sin herramientas de diseño dedicadas"],
  "choose_b": ["✅ Necesitas diseño UI profesional con sistemas de diseño reales, componentes reutilizables y prototipado interactivo","✅ Trabajas en un equipo de producto donde el diseño debe entregarse a desarrolladores con especificaciones precisas","✅ Quieres las funciones de IA de Figma integradas en el flujo de diseño: autocompletado, sugerencias contextuales, búsqueda de componentes","✅ Tu equipo usa Figma como herramienta de diseño estándar y quieres IA dentro de ese flujo sin cambiar de herramienta"],
  "faq": [{"q":"¿Puede Claude diseñar interfaces de usuario?","a":"Claude puede generar código de interfaz de usuario (HTML, CSS, React, Tailwind) con calidad sorprendente. También puede describir diseños y dar feedback de UX. Sin embargo, no genera imágenes de diseño — trabaja en código o descripción textual. Para interfaces en código — Claude es muy potente; para diseño visual directo — Figma."},{"q":"¿Claude o v0 para generar UI en código?","a":"v0 de Vercel está específicamente diseñado para generar componentes React/Tailwind de alta calidad con vista previa visual. Claude es más flexible y razona mejor sobre la lógica del diseño pero sin vista previa. Para componentes UI de producción — v0; para diseño de sistemas complejos con razonamiento — Claude."},{"q":"¿Figma AI puede generar código?","a":"Figma tiene Dev Mode que muestra código CSS, iOS y Android de los diseños. También hay plugins como Figma to Code. Figma AI está desarrollando capacidades de generación de código más directas. Claude genera código desde cero; Figma convierte diseños existentes a código."},{"q":"¿Claude puede revisar diseños existentes?","a":"Si compartes imágenes o descripciones de diseños, Claude puede dar feedback de UX, sugerir mejoras y analizar problemas de usabilidad. Esta capacidad de revisión de diseño conversacional es útil para equipos sin acceso a UX designers dedicados."}]
},
"google-stitch-vs-figma-ai": {
  "a": "Google Stitch", "b": "Figma AI",
  "choose_a": ["✅ Desarrollas apps Android y quieres generar prototipos de UI directamente desde texto con integración con Android Studio","✅ Quieres que Google genere componentes Material Design 3 automáticamente desde una descripción de pantalla","✅ Necesitas la forma más rápida de crear prototipos de UI para apps Android sin abrir Figma","✅ Tu equipo Android quiere validar ideas de UI rápidamente con una herramienta integrada en el ecosistema Google"],
  "choose_b": ["✅ Diseñas productos digitales multi-plataforma (web, iOS, Android) con diseño UI/UX profesional completo","✅ Necesitas sistemas de diseño, componentes reutilizables, prototipado interactivo y handoff a desarrolladores","✅ Tu equipo de producto trabaja con Figma como herramienta estándar y quiere IA integrada en ese flujo","✅ Produces diseños para múltiples plataformas simultáneamente, no solo para Android"],
  "faq": [{"q":"¿Qué es Google Stitch?","a":"Google Stitch es una herramienta de Google para generar prototipos de UI de Android desde descripciones de texto. Genera layouts con componentes Material Design 3 y puede exportarlos para continuar en Android Studio o Figma. Está orientada a desarrolladores Android que necesitan prototipar rápidamente sin diseñador."},{"q":"¿Google Stitch está disponible para iOS?","a":"Google Stitch está principalmente orientado a Android y Material Design. Para diseño iOS con IA — herramientas como Uizard, Framer AI o simplemente Figma con plugins son más apropiadas. La especialización Android/Material Design es tanto la fortaleza como la limitación de Stitch."},{"q":"¿Figma AI puede generar layouts completos?","a":"Figma AI está desarrollando capacidades de generación de UI desde prompts, pero en 2025 estas funciones siguen evolucionando. Para generación de pantallas completas ya disponible — Uizard, Google Stitch y v0 son más especializados actualmente. Figma AI brilla en asistencia contextual dentro de diseños existentes."},{"q":"¿Google Stitch genera código?","a":"Google Stitch puede exportar diseños que se integran en el flujo de desarrollo Android con Android Studio. La generación de código directamente está en evolución. El valor principal es la generación rápida de prototipos visuales, no necesariamente código de producción final."}]
},
"recraft-vs-canva-ai": {
  "a": "Recraft", "b": "Canva AI",
  "choose_a": ["✅ Necesitas crear ilustraciones vectoriales, iconos y gráficos de marca con control preciso de estilo y paleta de colores","✅ Exportas SVG directamente desde la herramienta IA para logos, iconos y gráficos escalables","✅ Eres diseñador que necesita coherencia de estilo visual en todos los activos de una marca o producto","✅ Produces gráficos de UI, ilustraciones de producto o iconografía donde el formato vectorial es esencial"],
  "choose_b": ["✅ Necesitas la herramienta de diseño gráfico más completa para marketing: social media, presentaciones, videos, documentos","✅ Tu equipo no tiene experiencia en diseño y necesita templates listos para usar en cualquier formato","✅ Quieres generar imágenes, videos, textos y diseños con IA en una sola plataforma sin cambiar de herramienta","✅ Produces contenido para múltiples canales simultáneamente con la herramienta de mayor versatilidad"],
  "faq": [{"q":"¿Recraft o Adobe Illustrator para vectoriales?","a":"Recraft genera vectoriales con IA desde texto — mucho más rápido para crear conceptos. Illustrator da control total sobre cada punto y curva del vector. Para crear activos vectoriales rápidamente desde prompts — Recraft; para edición vectorial manual precisa y profesional — Illustrator."},{"q":"¿Canva tiene generación de vectores?","a":"Canva puede generar imágenes con IA pero principalmente en formato raster (PNG). La exportación SVG en Canva es limitada y no siempre de calidad vectorial real. Para vectoriales de calidad — Recraft o Illustrator son más adecuados."},{"q":"¿Recraft es gratuito?","a":"Recraft tiene un plan gratuito con 50 generaciones al mes incluyendo SVG. Los planes de pago empiezan desde $12/mes. Canva tiene plan gratuito completo; Pro ($15/mes) para funciones de IA avanzadas."},{"q":"¿Recraft puede crear iconos para apps?","a":"Sí. Recraft es excelente para crear sets de iconos coherentes en estilo y peso visual. Puedes generar múltiples iconos con la misma paleta y estilo, exportarlos como SVG y usarlos directamente en apps. Esta capacidad de sets de iconos es una de sus fortalezas más valoradas por diseñadores de UI."}]
},
"remove-bg-vs-canva-ai": {
  "a": "Remove.bg", "b": "Canva AI",
  "choose_a": ["✅ Necesitas eliminar fondos de imágenes con la mayor precisión y velocidad disponible — uno de los mejores del mercado en esta tarea específica","✅ Procesas grandes volúmenes de imágenes en batch para e-commerce, catálogos de producto o fotografía de estudio","✅ Necesitas integración API para automatizar la eliminación de fondos en tu flujo de trabajo o aplicación","✅ Buscas la herramienta especializada con la mayor precisión en cabello, bordes complejos y transparencias"],
  "choose_b": ["✅ La eliminación de fondo es solo una de las muchas cosas que necesitas hacer en tu flujo de diseño","✅ Ya usas Canva y prefieres tener todo en un solo lugar sin cambiar de herramienta para cada tarea","✅ Produces diseños completos donde eliminar el fondo es un paso dentro de un proceso mayor de diseño","✅ Buscas la solución más económica — Canva Pro incluye eliminación de fondo sin costo adicional"],
  "faq": [{"q":"¿Remove.bg es gratuito?","a":"Remove.bg tiene un plan gratuito con previsualización de baja resolución y 1 descarga gratis. Para imágenes en alta resolución, los precios empiezan desde $9.99 para 40 créditos. Canva Pro ($15/mes) incluye eliminación de fondo ilimitada de calidad suficiente para la mayoría de usos."},{"q":"¿Canva puede eliminar fondos?","a":"Sí. Canva Pro tiene la función 'Eliminar fondo' que funciona bien para la mayoría de casos. Para imágenes simples con fondos claros, la calidad es excelente. Para cabello detallado, transparencias complejas o uso profesional — Remove.bg o Photoshop tienen mayor precisión."},{"q":"¿Remove.bg tiene API?","a":"Sí. Remove.bg tiene una API bien documentada para integrar la eliminación de fondos automáticamente. Es popular en plataformas de e-commerce, apps de fotografía y flujos de automatización. Canva tiene una API más limitada orientada a integración de diseño, no específicamente para eliminación de fondos."},{"q":"¿Qué alternativas gratuitas tiene Remove.bg?","a":"Alternativas gratuitas incluyen: Canva Pro (plan de pago pero barato), Adobe Express (tiene función básica), GIMP con plugins (local y gratuito), PhotoRoom y Cleanup.pictures. Para volúmenes altos a bajo costo — comparar precios de API de Remove.bg vs Canva Pro."}]
},
"seedance-vs-runway": {
  "a": "Seedance 2.0", "b": "Runway",
  "choose_a": ["✅ Quieres generación de video IA con excelente relación calidad-precio — Seedance 2.0 ofrece alta calidad a menor costo","✅ Necesitas videos con física de movimiento realista y coherencia temporal entre frames","✅ Buscas una alternativa competitiva a Runway con buena calidad en texto-a-video y imagen-a-video","✅ Quieres explorar las últimas capacidades de generación de video IA de ByteDance (creadores de TikTok)"],
  "choose_b": ["✅ Necesitas la suite de producción de video IA más establecida con herramientas de edición avanzadas además de generación","✅ Tu flujo incluye rotoscopia, eliminación de objetos, background swap y otras funciones de edición IA","✅ Trabajas en producción profesional donde necesitas una plataforma con historial probado y soporte","✅ Quieres las herramientas más maduras del mercado de video IA con mayor documentación y comunidad"],
  "faq": [{"q":"¿Qué es Seedance 2.0?","a":"Seedance 2.0 es un modelo de generación de video IA desarrollado por ByteDance (la empresa de TikTok). Genera videos de alta calidad desde texto o imágenes con física realista y buena coherencia temporal. Compite en el tier superior de generadores de video junto a Runway, Kling y Veo."},{"q":"¿Seedance es mejor que Kling?","a":"Seedance 2.0 y Kling 2.0 compiten directamente en calidad. Kling tiene mayor disponibilidad de acceso y más experiencia en el mercado. Seedance 2.0 muestra resultados impresionantes especialmente en física de movimiento. La competencia entre ambos es intensa en 2025."},{"q":"¿Runway está disponible en todos los países?","a":"Runway está disponible globalmente aunque con algunas restricciones regionales. Los planes y precios son los mismos internacionalmente. Seedance puede tener disponibilidad más limitada según la región dado que es más reciente."},{"q":"¿Cuántos segundos de video puede generar Seedance?","a":"Seedance 2.0 genera clips de video de varios segundos de alta calidad. Los detalles específicos de duración máxima y especificaciones técnicas varían según el plan de acceso. Runway Gen-3 genera clips de hasta 10 segundos por generación."}]
},
"whisper-vs-otter-ai": {
  "a": "Whisper", "b": "Otter AI",
  "choose_a": ["✅ Necesitas transcripción de alta precisión en más de 100 idiomas incluyendo idiomas menos comunes","✅ Quieres usar transcripción localmente sin enviar audio a terceros — Whisper es open-source y ejecutable en tu máquina","✅ Tienes archivos de audio o video existentes que necesitas transcribir en batch sin interfaz de usuario","✅ Integras transcripción en tu propio producto o flujo de trabajo vía la API de OpenAI o el modelo local"],
  "choose_b": ["✅ Quieres transcripción de reuniones en tiempo real con resúmenes automáticos e integración con Zoom, Teams y Meet","✅ Necesitas colaborar en notas de reunión con tu equipo directamente en la plataforma después de la reunión","✅ Buscas una herramienta de productividad para reuniones con interfaz amigable sin configuración técnica","✅ Quieres buscar en el historial de reuniones transcritas y resaltado de momentos clave"],
  "faq": [{"q":"¿Whisper es gratuito?","a":"Whisper es open-source (modelo gratuito de OpenAI para descargar y usar localmente). Vía la API de OpenAI, cuesta $0.006/minuto. Otter AI tiene plan gratuito con 300 minutos/mes; planes de pago desde $16.99/mes."},{"q":"¿Qué precisión tiene Whisper?","a":"Whisper large-v3 tiene una de las mayores precisiones de transcripción disponibles, especialmente en inglés. En español y otros idiomas también es muy competitivo. Para audio limpio, la precisión supera el 95%. Para audio de baja calidad — la precisión baja pero sigue siendo buena comparada con alternativas."},{"q":"¿Otter AI transcribe en español?","a":"Otter AI está principalmente optimizado para inglés. La transcripción en español existe pero con menor precisión. Whisper tiene soporte nativo multilingüe y transcribe en español con buena calidad. Para reuniones en español — Whisper (API o local) puede ser más preciso."},{"q":"¿Cómo uso Whisper sin ser técnico?","a":"Whisper está disponible de forma accesible en: MacWhisper (app Mac gratuita), OpenAI Playground, varias apps de escritorio que lo integran. No necesitas ser programador para usarlo. La versión más técnica (línea de comandos) ofrece más control pero no es necesaria para uso básico."}]
},
"adcreative-ai-vs-canva-ai": {
  "a": "AdCreative AI", "b": "Canva AI",
  "choose_a": ["✅ Necesitas creatividades publicitarias optimizadas para conversión, no solo diseños bonitos — AdCreative usa datos de rendimiento para predecir qué convierte mejor","✅ Produces anuncios a escala: cientos de variantes de creatividades para A/B testing en Meta Ads, Google Ads o TikTok Ads","✅ Quieres scores de conversión predichos para cada creatividad antes de publicarla y orientación de qué elementos cambiar","✅ Tu equipo de paid media necesita acelerar la producción de creatividades sin aumentar el equipo de diseño"],
  "choose_b": ["✅ Necesitas la herramienta de diseño más versátil para todo tipo de contenido de marketing, no solo anuncios","✅ Tu equipo produce contenido orgánico, presentaciones, email y materiales impresos además de publicidad de pago","✅ Buscas la mayor variedad de templates y herramientas con el precio más accesible para todo el equipo","✅ No tienes presupuesto elevado para herramientas de IA especializadas — Canva cubre más casos de uso por menos"],
  "faq": [{"q":"¿AdCreative AI vale la pena?","a":"AdCreative AI es valioso si gestionas presupuestos de publicidad pagada significativos — el tiempo ahorrado en crear variantes y la orientación de conversión pueden mejorar el ROAS. Para equipos con presupuesto de ads pequeño o que producen contenido principalmente orgánico — Canva es más rentable."},{"q":"¿AdCreative AI es gratuito?","a":"AdCreative AI no tiene plan gratuito permanente, solo prueba. Los planes empiezan desde $21/mes (Starter). Canva tiene plan gratuito muy completo; Pro a $15/mes. Para comenzar con publicidad IA — Canva Magic Studio puede ser suficiente antes de invertir en AdCreative."},{"q":"¿Qué plataformas soporta AdCreative AI?","a":"AdCreative AI genera creatividades para Meta Ads (Facebook e Instagram), Google Display, TikTok, LinkedIn y otras plataformas con los tamaños correctos. Incluye variantes de copy y copy IA para los anuncios. Canva también tiene templates de ads para estas plataformas pero sin el score de conversión predictivo."},{"q":"¿Canva puede hacer anuncios publicitarios?","a":"Sí. Canva tiene templates para anuncios en todas las plataformas con tamaños correctos, y Magic Studio puede generar copias e imágenes. Sin embargo, no tiene el análisis predictivo de conversión de AdCreative. Para diseño de anuncios básico — Canva; para optimización de conversión a escala — AdCreative."}]
},
"akkio-vs-julius-ai": {
  "a": "Akkio", "b": "Julius AI",
  "choose_a": ["✅ Necesitas construir modelos predictivos de negocio sin código: predicción de churn, lead scoring, forecasting de ventas","✅ Quieres que la IA identifique automáticamente qué variables predicen mejor un resultado de negocio","✅ Tu equipo de negocio necesita machine learning aplicado sin científicos de datos ni código Python","✅ Produces predicciones a escala que se integran en tu CRM o herramientas de marketing automatizadas"],
  "choose_b": ["✅ Quieres análisis de datos conversacional: cargas un CSV y haces preguntas en lenguaje natural para explorar los datos","✅ Necesitas visualizaciones automáticas, estadísticas y gráficos generados por IA a partir de tus datos","✅ Buscas la herramienta más accesible para exploración de datos sin machine learning predictivo como objetivo","✅ Produces análisis ad-hoc y reportes de datos de forma rápida sin configurar modelos de predicción"],
  "faq": [{"q":"¿Akkio o DataRobot para ML sin código?","a":"DataRobot está más orientado a empresas grandes con equipos de datos — más potente pero mucho más caro. Akkio está diseñado para equipos de negocio sin científicos de datos — más accesible y fácil de configurar. Para PMEs y equipos de marketing/ventas — Akkio; para grandes empresas con datos complejos — DataRobot."},{"q":"¿Akkio es gratuito?","a":"Akkio tiene un plan gratuito limitado con proyectos básicos. Los planes de pago empiezan desde $49/mes. Julius AI tiene plan gratuito con 15 análisis/mes; planes desde $22/mes."},{"q":"¿Julius AI puede construir modelos predictivos?","a":"Julius AI puede hacer análisis estadísticos y regresiones básicas, pero no está diseñado para construir modelos predictivos de producción. Akkio está específicamente hecho para crear modelos de predicción (churn, conversión, forecasting) listos para integrar en sistemas de negocio."},{"q":"¿Qué datos puede analizar Akkio?","a":"Akkio funciona con datos tabulares en CSV, Excel, Google Sheets o conectores directos a CRM (HubSpot, Salesforce). Para ML predictivo, necesitas datos históricos con la variable objetivo que quieres predecir (ej: clientes que se dieron de baja vs. los que no)."}]
},
"autogpt-vs-manus": {
  "a": "AutoGPT", "b": "Manus",
  "choose_a": ["✅ Quieres explorar agentes de IA autónomos open-source que puedes self-hospedar con control total","✅ Necesitas un agente de IA personalizable según tus necesidades específicas con acceso al código fuente","✅ Tienes conocimientos técnicos y quieres experimentar con arquitecturas de agentes IA en tu propio entorno","✅ Buscas contribuir al desarrollo de agentes IA open-source o construir sobre la base de AutoGPT"],
  "choose_b": ["✅ Quieres un agente de IA autónomo listo para usar que completa tareas complejas de múltiples pasos sin configuración técnica","✅ Necesitas resultados inmediatos en investigación, escritura de código y creación de documentos con el menor setup posible","✅ No tienes conocimientos técnicos para self-hospedar un agente — Manus es un servicio gestionado","✅ Buscas las últimas capacidades de agentes multimodales sin necesidad de gestionar infraestructura"],
  "faq": [{"q":"¿AutoGPT todavía es relevante en 2025?","a":"AutoGPT fue pionero en agentes IA autónomos en 2023. En 2025, Claude Code, Manus y otros agentes más maduros han igualado o superado sus capacidades con mejor experiencia de uso. AutoGPT sigue siendo relevante como proyecto open-source y plataforma de experimentación, pero no es la opción más práctica para producción."},{"q":"¿Manus es gratuito?","a":"Manus tuvo acceso por invitación limitado en su lanzamiento. El acceso completo requiere suscripción de pago. AutoGPT es open-source y gratuito como herramienta, aunque requiere APIs de modelos de IA (OpenAI, Anthropic) que tienen su propio costo."},{"q":"¿Cuál es la diferencia entre AutoGPT y LangChain?","a":"AutoGPT es un agente de IA con objetivo fijo de completar tareas de forma autónoma. LangChain es un framework para desarrolladores para construir aplicaciones con LLMs y agentes. AutoGPT es para usuarios finales; LangChain es para desarrolladores que quieren construir sus propios sistemas de agentes."},{"q":"¿Los agentes IA son seguros?","a":"Los agentes IA como AutoGPT y Manus pueden ejecutar código, navegar la web y realizar acciones. Esto requiere precaución — siempre revisar los permisos antes de dar acceso a datos sensibles o sistemas críticos. Para experimentación — entornos aislados; para producción — revisión humana de acciones críticas."}]
},
"coursera-coach-vs-khanmigo": {
  "a": "Coursera Coach", "b": "Khanmigo",
  "choose_a": ["✅ Estás tomando un curso en Coursera y necesitas ayuda con el contenido específico de esa clase con IA que conoce el material","✅ Quieres prepararte para certificaciones profesionales (Google, Meta, IBM, DeepLearning.AI) con asistencia IA integrada","✅ Necesitas que el asistente IA conozca exactamente qué has estudiado y dónde estás en el curso","✅ Eres profesional que aprende en Coursera y quiere apoyo IA contextual dentro de la plataforma donde estudia"],
  "choose_b": ["✅ Necesitas tutoría socrática en materias académicas generales: matemáticas, ciencias, historia, escritura, SAT","✅ Eres estudiante K-12 o universitario que necesita ayuda en el currículo académico fuera de plataformas de e-learning","✅ Quieres un tutor IA que te guíe sin darte las respuestas directamente, fomentando el razonamiento propio","✅ Buscas preparación para exámenes estandarizados con práctica adaptativa en múltiples materias académicas"],
  "faq": [{"q":"¿Coursera Coach está disponible en todos los cursos?","a":"Coursera Coach está disponible en cursos seleccionados de Coursera, principalmente en planes Coursera Plus y cursos de pago. No todos los cursos tienen el asistente IA integrado. Khanmigo está disponible en todo el contenido de Khan Academy sin restricciones de curso."},{"q":"¿Coursera Coach es gratuito?","a":"Coursera Coach está incluido en los planes de pago de Coursera (Coursera Plus desde $59/mes o $399/año). No está disponible en el acceso gratuito. Khanmigo cuesta $9/mes o $44/año independientemente, con Khan Academy gratuito aparte."},{"q":"¿Khanmigo puede ayudar con cursos universitarios?","a":"Khanmigo puede ayudar con materias universitarias si el contenido está en Khan Academy (cálculo, estadística, ciencias, economía, etc.). Para cursos específicos de plataformas de e-learning como Coursera — el contexto del curso no está disponible para Khanmigo."},{"q":"¿Hay alternativas a Coursera Coach?","a":"Alternativas para apoyo en e-learning: Khanmigo (Khan Academy), Synthesis Tutor, herramientas de estudio como Quizlet con IA, o directamente ChatGPT/Claude para preguntas sobre el material del curso. También Duolingo Max para idiomas y Photomath para matemáticas."}]
},
"socratic-vs-khanmigo": {
  "a": "Socratic (by Google)", "b": "Khanmigo",
  "choose_a": ["✅ Eres estudiante de secundaria que necesita ayuda inmediata con los deberes: fotografías el problema y Socratic da la respuesta y explicación","✅ Quieres cubrir múltiples materias con una sola app gratuita: matemáticas, ciencias, historia, inglés","✅ Necesitas la herramienta más accesible y gratuita para deberes de secundaria sin registro complejo","✅ Prefieres respuestas directas con explicaciones visuales y videos relacionados de YouTube sobre la materia"],
  "choose_b": ["✅ Buscas un tutor socrático que te guía con preguntas en lugar de darte la respuesta directamente — mejor para aprendizaje profundo","✅ Necesitas tutoría en matemáticas, ciencias e historia con el respaldo pedagógico de Khan Academy","✅ Eres estudiante que quiere desarrollar habilidades de razonamiento, no solo resolver el problema inmediato","✅ Buscas preparación para exámenes estandarizados (SAT, ACT) con práctica adaptativa guiada por IA socrática"],
  "faq": [{"q":"¿Socratic by Google es gratuito?","a":"Sí. Socratic es completamente gratuito, disponible como app de iOS y Android. Es de Google y no tiene planes de pago. Khanmigo cuesta $9/mes o $44/año."},{"q":"¿Socratic puede resolver problemas de cálculo?","a":"Socratic puede ayudar con cálculo y matemáticas avanzadas de secundaria. Para cálculo universitario complejo, Wolfram Alpha o Symbolab son más potentes. Khanmigo tiene más contenido de Khan Academy para cálculo con explicaciones pedagógicas estructuradas."},{"q":"¿Socratic o PhotoMath para matemáticas?","a":"Socratic cubre más materias (no solo matemáticas) y explica el concepto detrás del problema. PhotoMath es más especializado en matemáticas y muestra los pasos con mayor detalle. Para solo matemáticas con pasos muy detallados — PhotoMath; para múltiples materias y conceptos — Socratic."},{"q":"¿Es malo usar Socratic para los deberes?","a":"Como toda herramienta de IA para deberes, Socratic puede usarse para aprender o para copiar. Usarlo para entender el concepto y verificar tu razonamiento es educativo. Copiar la respuesta sin entender es contraproducente para el aprendizaje. Los mejores resultados vienen de intentar el problema primero y usar Socratic para verificar y entender."}]
},
}

COMPARISONS = [
    {'slug': 'chatgpt-vs-claude',                    'a': 'chatgpt',                'b': 'claude'},
    {'slug': 'gemini-vs-chatgpt',                    'a': 'gemini',                 'b': 'chatgpt'},
    {'slug': 'deepseek-vs-chatgpt',                  'a': 'deepseek',               'b': 'chatgpt'},
    {'slug': 'microsoft-copilot-vs-chatgpt',         'a': 'microsoft-copilot',      'b': 'chatgpt'},
    {'slug': 'meta-ai-vs-chatgpt',                   'a': 'meta-ai',                'b': 'chatgpt'},
    {'slug': 'grok-vs-chatgpt',                      'a': 'grok',                   'b': 'chatgpt'},
    {'slug': 'mistral-le-chat-vs-chatgpt',           'a': 'mistral-le-chat',        'b': 'chatgpt'},
    {'slug': 'character-ai-vs-chatgpt',              'a': 'character-ai',           'b': 'chatgpt'},
    {'slug': 'copilot-studio-vs-manus',              'a': 'copilot-studio',         'b': 'manus'},
    {'slug': 'n8n-vs-copilot-studio',                'a': 'n8n',                    'b': 'copilot-studio'},
    {'slug': 'make-vs-copilot-studio',               'a': 'make',                   'b': 'copilot-studio'},
    {'slug': 'lindy-vs-copilot-studio',              'a': 'lindy',                  'b': 'copilot-studio'},
    {'slug': 'relevance-ai-vs-copilot-studio',       'a': 'relevance-ai',           'b': 'copilot-studio'},
    {'slug': 'devin-vs-copilot-studio',              'a': 'devin',                  'b': 'copilot-studio'},
    {'slug': 'make-vs-n8n',                          'a': 'make',                   'b': 'n8n'},
    {'slug': 'cursor-vs-copilot',                    'a': 'cursor',                 'b': 'github-copilot'},
    {'slug': 'windsurf-vs-cursor',                   'a': 'windsurf',               'b': 'cursor'},
    {'slug': 'claude-code-vs-github-copilot',        'a': 'claude-code',            'b': 'github-copilot'},
    {'slug': 'replit-vs-github-copilot',             'a': 'replit',                 'b': 'github-copilot'},
    {'slug': 'bolt-new-vs-cursor',                   'a': 'bolt-new',               'b': 'cursor'},
    {'slug': 'v0-by-vercel-vs-cursor',               'a': 'v0-by-vercel',           'b': 'cursor'},
    {'slug': 'cline-vs-github-copilot',              'a': 'cline',                  'b': 'github-copilot'},
    {'slug': 'aider-vs-github-copilot',              'a': 'aider',                  'b': 'github-copilot'},
    {'slug': 'windsurf-vs-github-copilot',           'a': 'windsurf',               'b': 'github-copilot'},
    {'slug': 'deepl-vs-grammarly',                   'a': 'deepl',                  'b': 'grammarly'},
    {'slug': 'quillbot-vs-grammarly',                'a': 'quillbot',               'b': 'grammarly'},
    {'slug': 'jasper-vs-writesonic',                 'a': 'jasper',                 'b': 'writesonic'},
    {'slug': 'writesonic-vs-grammarly',              'a': 'writesonic',             'b': 'grammarly'},
    {'slug': 'hemingway-editor-vs-grammarly',        'a': 'hemingway-editor',       'b': 'grammarly'},
    {'slug': 'semrush-vs-copy-ai',                   'a': 'semrush',                'b': 'copy-ai'},
    {'slug': 'surferseo-vs-semrush',                 'a': 'surferseo',              'b': 'semrush'},
    {'slug': 'frase-vs-semrush',                     'a': 'frase',                  'b': 'semrush'},
    {'slug': 'clearscope-vs-surferseo',              'a': 'clearscope',             'b': 'surferseo'},
    {'slug': 'copy-ai-vs-jasper',                    'a': 'copy-ai',                'b': 'jasper'},
    {'slug': 'midjourney-vs-flux',                   'a': 'midjourney',             'b': 'flux'},
    {'slug': 'midjourney-vs-stable-diffusion',       'a': 'midjourney',             'b': 'stable-diffusion'},
    {'slug': 'ideogram-vs-midjourney',               'a': 'ideogram',               'b': 'midjourney'},
    {'slug': 'adobe-firefly-vs-midjourney',          'a': 'adobe-firefly',          'b': 'midjourney'},
    {'slug': 'recraft-ai-vs-midjourney',             'a': 'recraft-ai',             'b': 'midjourney'},
    {'slug': 'flux-vs-stable-diffusion',             'a': 'flux',                   'b': 'stable-diffusion'},
    {'slug': 'leonardo-ai-vs-midjourney',            'a': 'leonardo-ai',            'b': 'midjourney'},
    {'slug': 'kling-vs-runway',                      'a': 'kling-ai',               'b': 'runway'},
    {'slug': 'capcut-vs-kling-ai',                   'a': 'capcut',                 'b': 'kling-ai'},
    {'slug': 'runway-vs-capcut',                     'a': 'runway',                 'b': 'capcut'},
    {'slug': 'heygen-vs-synthesia',                  'a': 'heygen',                 'b': 'synthesia'},
    {'slug': 'pika-vs-kling-ai',                     'a': 'pika',                   'b': 'kling-ai'},
    {'slug': 'luma-ai-vs-runway',                    'a': 'luma-ai',                'b': 'runway'},
    {'slug': 'google-veo-3-vs-runway',               'a': 'google-veo-3',           'b': 'runway'},
    {'slug': 'canva-ai-vs-figma-ai',                 'a': 'canva-ai',               'b': 'figma-ai'},
    {'slug': 'figma-ai-vs-canva-ai',                 'a': 'figma-ai',               'b': 'canva-ai'},
    {'slug': 'framer-ai-vs-canva-ai',                'a': 'framer-ai',              'b': 'canva-ai'},
    {'slug': 'looka-vs-canva-ai',                    'a': 'looka',                  'b': 'canva-ai'},
    {'slug': 'uizard-vs-figma-ai',                   'a': 'uizard',                 'b': 'figma-ai'},
    {'slug': 'uxpilot-vs-figma-ai',                  'a': 'uxpilot',                'b': 'figma-ai'},
    {'slug': 'relume-vs-framer-ai',                  'a': 'relume',                 'b': 'framer-ai'},
    {'slug': 'whimsical-ai-vs-figma-ai',             'a': 'whimsical-ai',           'b': 'figma-ai'},
    {'slug': 'suno-vs-udio',                         'a': 'suno',                   'b': 'udio'},
    {'slug': 'speechify-vs-elevenlabs',              'a': 'speechify',              'b': 'elevenlabs'},
    {'slug': 'elevenlabs-vs-murf-ai',                'a': 'elevenlabs',             'b': 'murf-ai'},
    {'slug': 'elevenlabs-vs-playht',                 'a': 'elevenlabs',             'b': 'playht'},
    {'slug': 'descript-vs-adobe-podcast',            'a': 'descript',               'b': 'adobe-podcast'},
    {'slug': 'suno-vs-elevenlabs',                   'a': 'suno',                   'b': 'elevenlabs'},
    {'slug': 'notion-ai-vs-zapier-ai',               'a': 'notion-ai',              'b': 'zapier-ai'},
    {'slug': 'gamma-vs-notion-ai',                   'a': 'gamma',                  'b': 'notion-ai'},
    {'slug': 'otter-ai-vs-fireflies-ai',             'a': 'otter-ai',               'b': 'fireflies-ai'},
    {'slug': 'motion-vs-reclaim-ai',                 'a': 'motion',                 'b': 'reclaim-ai'},
    {'slug': 'zapier-ai-vs-make',                    'a': 'zapier-ai',              'b': 'make'},
    {'slug': 'perplexity-vs-notebooklm',             'a': 'perplexity',             'b': 'notebooklm'},
    {'slug': 'elicit-vs-consensus',                  'a': 'elicit',                 'b': 'consensus'},
    {'slug': 'consensus-vs-perplexity',              'a': 'consensus',              'b': 'perplexity'},
    {'slug': 'notebooklm-vs-humata',                 'a': 'notebooklm',             'b': 'humata'},
    {'slug': 'scite-vs-semantic-scholar',            'a': 'scite',                  'b': 'semantic-scholar'},
    {'slug': 'looker-studio-vs-tableau-ai',          'a': 'looker-studio',          'b': 'tableau-ai'},
    {'slug': 'julius-ai-vs-looker-studio',           'a': 'julius-ai',              'b': 'looker-studio'},
    {'slug': 'hex-vs-looker-studio',                 'a': 'hex',                    'b': 'looker-studio'},
    {'slug': 'rows-vs-hex',                          'a': 'rows',                   'b': 'hex'},
    {'slug': 'retool-ai-vs-looker-studio',           'a': 'retool-ai',              'b': 'looker-studio'},
    {'slug': 'bubble-vs-webflow',                    'a': 'bubble',                 'b': 'webflow'},
    {'slug': 'lovable-vs-bubble',                    'a': 'lovable',                'b': 'bubble'},
    {'slug': 'flutterflow-vs-bubble',                'a': 'flutterflow',            'b': 'bubble'},
    {'slug': 'glide-vs-bubble',                      'a': 'glide',                  'b': 'bubble'},
    {'slug': 'softr-vs-bubble',                      'a': 'softr',                  'b': 'bubble'},
    {'slug': 'webflow-vs-framer-ai',                 'a': 'webflow',                'b': 'framer-ai'},
    {'slug': 'photomath-vs-duolingo-max',            'a': 'photomath',              'b': 'duolingo-max'},
    {'slug': 'khanmigo-vs-photomath',                'a': 'khanmigo',               'b': 'photomath'},
    {'slug': 'duolingo-max-vs-khanmigo',             'a': 'duolingo-max',           'b': 'khanmigo'},
    {'slug': 'youlearn-vs-notebooklm',               'a': 'youlearn',               'b': 'notebooklm'},
    {'slug': 'synthesis-vs-khanmigo',                'a': 'synthesis',              'b': 'khanmigo'},
    {'slug': 'gamma-vs-beautiful-ai',                'a': 'gamma',                  'b': 'beautiful-ai'},
    {'slug': 'gamma-vs-pitch',                       'a': 'gamma',                  'b': 'pitch'},
    {'slug': 'gamma-vs-prezi',                       'a': 'gamma',                  'b': 'prezi'},
    {'slug': 'beautiful-ai-vs-pitch',                'a': 'beautiful-ai',           'b': 'pitch'},
    {'slug': 'slidesgo-vs-gamma',                    'a': 'slidesgo',               'b': 'gamma'},
    {'slug': 'tradingview-vs-fiscal-ai',             'a': 'tradingview',            'b': 'finchat'},
    {'slug': 'koyfin-vs-tradingview',                'a': 'koyfin',                 'b': 'tradingview'},
    {'slug': 'fiscal-ai-vs-koyfin',                  'a': 'finchat',                'b': 'koyfin'},
    {'slug': 'tickeron-vs-tradingview',              'a': 'tickeron',               'b': 'tradingview'},
    {'slug': 'uptrends-ai-vs-koyfin',               'a': 'uptrends-ai',            'b': 'koyfin'},
    {'slug': 'amazon-q-developer-vs-github-copilot','a': 'amazon-q-developer',     'b': 'github-copilot'},
    {'slug': 'continue-dev-vs-github-copilot',      'a': 'continue-dev',           'b': 'github-copilot'},
    {'slug': 'opencode-vs-claude-code',             'a': 'opencode',               'b': 'claude-code'},
    {'slug': 'zed-vs-cursor',                       'a': 'zed',                    'b': 'cursor'},
    {'slug': 'comfyui-vs-stable-diffusion',         'a': 'comfyui',                'b': 'stable-diffusion'},
    {'slug': 'krea-ai-vs-midjourney',               'a': 'krea-ai',                'b': 'midjourney'},
    {'slug': 'nano-banana-vs-leonardo-ai',          'a': 'nano-banana',            'b': 'leonardo-ai'},
    {'slug': 'chatgpt-images-vs-adobe-firefly',     'a': 'chatgpt-images',         'b': 'adobe-firefly'},
    {'slug': 'claude-design-vs-figma-ai',           'a': 'claude-design',          'b': 'figma-ai'},
    {'slug': 'google-stitch-vs-figma-ai',           'a': 'google-stitch',          'b': 'figma-ai'},
    {'slug': 'recraft-vs-canva-ai',                 'a': 'recraft',                'b': 'canva-ai'},
    {'slug': 'remove-bg-vs-canva-ai',               'a': 'remove-bg',              'b': 'canva-ai'},
    {'slug': 'seedance-vs-runway',                  'a': 'seedance-2-0',           'b': 'runway'},
    {'slug': 'whisper-vs-otter-ai',                 'a': 'whisper',                'b': 'otter-ai'},
    {'slug': 'adcreative-ai-vs-canva-ai',           'a': 'adcreative-ai',          'b': 'canva-ai'},
    {'slug': 'akkio-vs-julius-ai',                  'a': 'akkio',                  'b': 'julius-ai'},
    {'slug': 'autogpt-vs-manus',                    'a': 'autogpt',                'b': 'manus'},
    {'slug': 'coursera-coach-vs-khanmigo',          'a': 'coursera-coach',         'b': 'khanmigo'},
    {'slug': 'socratic-vs-khanmigo',                'a': 'socratic-by-google',     'b': 'khanmigo'},
]

# ── Build tool_slug → {choose_if, faq} ──────────────────────────────────────
tool_data = {}
for comp in COMPARISONS:
    slug_a = comp['a']
    slug_b = comp['b']
    key    = comp['slug']
    if key not in DATA_ES:
        continue
    d = DATA_ES[key]
    if slug_a not in tool_data:
        tool_data[slug_a] = {'choose_if': d['choose_a'], 'faq': d['faq']}
    if slug_b not in tool_data:
        tool_data[slug_b] = {'choose_if': d['choose_b'], 'faq': d['faq']}

# ── Generate SQL for tools table ─────────────────────────────────────────────
lines = []
lines.append("-- Spanish choose_if + faq UPDATE — generated by gen_tool_choose_faq_es_b4.py (batch 4/4)")
lines.append("BEGIN;")
for i, (tool_slug, td) in enumerate(sorted(tool_data.items()), start=1):
    ci_json = json.dumps(td['choose_if'], ensure_ascii=False)
    fq_json = json.dumps(td['faq'],       ensure_ascii=False)
    tag_ci  = f't{i}ci'
    tag_fq  = f't{i}fq'
    lines.append(
        f"UPDATE tools SET"
        f" choose_if = ${tag_ci}${ci_json}${tag_ci}$::JSONB,"
        f" faq = ${tag_fq}${fq_json}${tag_fq}$::JSONB"
        f" WHERE slug = '{tool_slug}' AND lang = 'es';"
    )
lines.append("COMMIT;")
sql = "\n".join(lines)
out_path = __file__.replace('.py', '.sql')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(sql)
print(f"-- Tools SQL written to {out_path}", file=sys.stderr)

# ── Generate SQL for comparisons table ───────────────────────────────────────
comp_lines = []
comp_lines.append("-- Spanish choose_a + choose_b + faq INSERT for comparisons table (batch 4/4)")
comp_lines.append("BEGIN;")
for i, comp in enumerate(COMPARISONS, start=1):
    key = comp['slug']
    if key not in DATA_ES:
        continue
    d = DATA_ES[key]
    ca_json  = json.dumps(d['choose_a'], ensure_ascii=False)
    cb_json  = json.dumps(d['choose_b'], ensure_ascii=False)
    faq_json = json.dumps(d['faq'],      ensure_ascii=False)
    tag_a = f'c{i}a'; tag_b = f'c{i}b'; tag_f = f'c{i}f'
    comp_lines.append(
        f"INSERT INTO comparisons "
        f"(slug,lang,tool_a,tool_b,tool_a_slug,tool_b_slug,tool_a_url,tool_b_url,"
        f"title,meta_desc,intro,table_data,best_a,best_b,verdict_a,verdict_b,choose_a,choose_b,faq)"
        f" SELECT slug,'es',tool_a,tool_b,tool_a_slug,tool_b_slug,tool_a_url,tool_b_url,"
        f"title,meta_desc,intro,table_data,best_a,best_b,verdict_a,verdict_b,"
        f"${tag_a}${ca_json}${tag_a}$::JSONB,"
        f"${tag_b}${cb_json}${tag_b}$::JSONB,"
        f"${tag_f}${faq_json}${tag_f}$::JSONB"
        f" FROM comparisons WHERE slug='{key}' AND lang='en'"
        f" ON CONFLICT (slug,lang) DO UPDATE SET"
        f" choose_a=EXCLUDED.choose_a, choose_b=EXCLUDED.choose_b, faq=EXCLUDED.faq;"
    )
comp_lines.append("COMMIT;")
comp_sql = "\n".join(comp_lines)
comp_out = __file__.replace('.py', '_comparisons.sql')
with open(comp_out, 'w', encoding='utf-8') as f:
    f.write(comp_sql)
print(f"-- Comparisons SQL written to {comp_out}", file=sys.stderr)
print(f"Batch 4/4 done: {len(DATA_ES)} comparisons, {len(tool_data)} tools")
