#!/usr/bin/env python3
"""Generate SQL for Spanish (lang=es) translations of choose_if and faq. Batch 3/4 (comparisons 61-90)."""

import json, sys

DATA_ES = {
"descript-vs-adobe-podcast": {
  "a": "Descript", "b": "Adobe Podcast",
  "choose_a": ["✅ Necesitas edición de audio y video completa basada en transcripción — editas el texto y el audio cambia automáticamente","✅ Quieres eliminar palabras de relleno ('eh', 'um', silencios) con un solo clic en tu podcast o video","✅ Produces contenido de video y podcast en el mismo flujo de trabajo: grabación → transcripción → edición → publicación","✅ Necesitas una herramienta de producción de podcast profesional con doblaje IA de tu propia voz (Overdub)"],
  "choose_b": ["✅ Tu único objetivo es mejorar la calidad del audio existente: limpiar ruido de fondo, mejorar la voz — Enhance Speech hace esto en segundos","✅ Tienes grabaciones de audio de baja calidad (micro de portátil, llamadas Zoom) que necesitas mejorar para publicar","✅ No necesitas edición completa — solo quieres subir el audio y descargarlo mejorado sin aprender ningún software","✅ Buscas la herramienta de mejora de audio más rápida y gratuita integrada en Creative Cloud"],
  "faq": [{"q":"¿Descript o Adobe Podcast para podcasters principiantes?","a":"Adobe Podcast (Enhance Speech) es más simple — subes el audio, lo mejoras y listo. Descript es más potente pero requiere más aprendizaje. Para empezar con mejora básica — Adobe Podcast; para producción profesional de podcasts con edición completa — Descript."},{"q":"¿Descript es gratuito?","a":"Descript tiene un plan gratuito con 1 hora de transcripción al mes. El plan Creator ($24/mes) ofrece más funciones. Adobe Podcast (Enhance Speech) es gratuito en beta. El acceso completo requiere suscripción a Adobe Creative Cloud."},{"q":"¿Qué hace Overdub de Descript?","a":"Overdub es la función de clonación de voz de Descript. Entrenas un modelo con tu voz y puedes reemplazar o añadir palabras en tu grabación de audio sin volver a grabar — el resultado suena como tú. Es útil para correcciones rápidas sin sesiones de grabación adicionales."},{"q":"¿Adobe Podcast Enhance Speech funciona bien?","a":"Sí. Enhance Speech de Adobe es sorprendentemente efectivo — toma audio grabado con micro de laptop o en ambientes ruidosos y lo transforma para sonar como grabado en estudio. Es gratuito y no requiere instalación. Una de las mejores herramientas de mejora de audio accesibles."}]
},
"suno-vs-elevenlabs": {
  "a": "Suno", "b": "ElevenLabs",
  "choose_a": ["✅ Quieres crear canciones completas con música, instrumentación y letra desde un prompt de texto","✅ Produces contenido creativo musical: jingles, canciones para videos, música de fondo personalizada","✅ Eres creador de contenido que necesita música original sin pagar royalties por licencias","✅ Quieres experimentar con géneros musicales y composición sin conocimientos musicales"],
  "choose_b": ["✅ Necesitas síntesis de voz o narración — locuciones, audiolibros, podcasts de texto a voz","✅ Quieres clonar tu voz para producir audio consistente sin necesidad de grabar cada vez","✅ Produces doblaje de video en múltiples idiomas conservando la voz original","✅ Integras síntesis de voz en tu aplicación o producto vía API"],
  "faq": [{"q":"¿Suno o ElevenLabs para crear contenido de audio?","a":"Son herramientas para propósitos completamente distintos. Suno crea música: canciones con instrumentación y letra. ElevenLabs convierte texto en voz hablada realista. Si necesitas música — Suno; si necesitas voz narrada — ElevenLabs."},{"q":"¿Puede Suno crear voz hablada?","a":"Suno genera voces cantadas dentro de canciones, no locución o narración. Para texto a voz realista — ElevenLabs, Murf o Play.ht. Para canciones con voz cantada — Suno."},{"q":"¿Se puede usar la música de Suno en videos de YouTube?","a":"Con el plan de pago de Suno (Pro o Premier) obtienes derechos comerciales. El plan gratuito tiene restricciones de uso comercial. Verifica los términos actuales antes de monetizar contenido. ElevenLabs tiene políticas similares según el plan."},{"q":"¿ElevenLabs puede generar música?","a":"ElevenLabs está especializado en síntesis de voz y clonación, no en generación de música instrumental. Para música — usa Suno o Udio. Para voz — ElevenLabs es el estándar de calidad."}]
},
"notion-ai-vs-zapier-ai": {
  "a": "Notion AI", "b": "Zapier AI",
  "choose_a": ["✅ Tu equipo ya usa Notion y quieres IA integrada en tu espacio de trabajo: resumir notas, redactar documentos, responder preguntas sobre tu base de conocimiento","✅ Necesitas un asistente IA para documentación, wikis y gestión de conocimiento sin cambiar de herramienta","✅ Quieres generar contenido, traducir, corregir o transformar texto directamente en tus páginas de Notion","✅ Buscas IA para productividad personal y de equipo en la misma herramienta donde ya gestionas proyectos"],
  "choose_b": ["✅ Quieres automatizar flujos de trabajo entre 6.000+ aplicaciones con disparadores y acciones inteligentes","✅ Necesitas que la IA tome decisiones en tus automatizaciones: clasificar emails, extraer datos, enrutar tareas","✅ Construyes flujos de trabajo que conectan Notion con otras herramientas (CRM, email, Slack, etc.) de forma automática","✅ Buscas automatización de procesos repetitivos que involucran múltiples aplicaciones, no solo gestión de conocimiento"],
  "faq": [{"q":"¿Notion AI o ChatGPT para productividad?","a":"Notion AI está integrado directamente en tu espacio de trabajo — sin cambiar de ventana, con contexto de tus documentos. ChatGPT es más potente en razonamiento general pero sin integración con tu base de conocimiento. Para trabajar sobre tus documentos existentes — Notion AI; para tareas de IA general — ChatGPT."},{"q":"¿Notion AI es gratuito?","a":"Notion AI es un add-on de pago: $10/usuario/mes añadido al plan de Notion (que empieza gratuito). Zapier AI está incluido en los planes de Zapier, que empieza desde $19.99/mes. Notion AI para un solo usuario sale a $10/mes extra sobre tu plan actual."},{"q":"¿Qué puede hacer Notion AI?","a":"Notion AI puede: resumir páginas largas, redactar documentos desde prompts, responder preguntas sobre tu base de datos de Notion, traducir texto, corregir gramática, extraer tareas pendientes de reuniones y generar tablas. Todo sin salir de Notion."},{"q":"¿Zapier AI puede trabajar con Notion?","a":"Sí. Zapier tiene integración nativa con Notion — puede leer y escribir en bases de datos de Notion, crear páginas automáticamente cuando ocurren eventos en otras apps, y usar IA para procesar datos antes de insertarlos en Notion."}]
},
"gamma-vs-notion-ai": {
  "a": "Gamma", "b": "Notion AI",
  "choose_a": ["✅ Necesitas crear una presentación, propuesta o documento visualmente atractivo desde cero en minutos con IA","✅ Quieres que el resultado final tenga diseño visual profesional: layouts, imágenes integradas, animaciones suaves","✅ Presentas a clientes, inversores o equipos y necesitas que el material se vea impactante sin ser diseñador","✅ Quieres publicar como página web, PDF o presentación interactiva directamente desde la herramienta"],
  "choose_b": ["✅ Tu equipo ya usa Notion y quieres IA integrada para mejorar documentos, resumir notas y generar contenido","✅ Necesitas gestión de conocimiento con asistente IA: buscar en tu wiki, responder preguntas sobre proyectos","✅ Trabajas con documentos colaborativos donde la estructura y el proceso importan más que el diseño visual","✅ Quieres automatizar redacción y transformación de texto dentro de tu flujo de trabajo existente en Notion"],
  "faq": [{"q":"¿Gamma o PowerPoint para presentaciones?","a":"Gamma es significativamente más rápido — genera toda la presentación desde un prompt en segundos con diseño incluido. PowerPoint da más control granular sobre cada elemento. Para presentaciones rápidas con buen diseño — Gamma gana en velocidad. Para presentaciones corporativas con brand strict — PowerPoint o Google Slides."},{"q":"¿Gamma es gratuito?","a":"Gamma tiene un plan gratuito con 400 créditos (suficiente para varias presentaciones). Los planes de pago empiezan desde $10/mes (Plus). Notion AI cuesta $10/mes extra sobre el plan de Notion."},{"q":"¿Notion AI puede crear presentaciones?","a":"Notion AI puede generar contenido estructurado para presentaciones — texto, listas, tablas — pero Notion no exporta como presentación visual. Para convertir ese contenido en una presentación, necesitas Gamma, PowerPoint o Google Slides."},{"q":"¿Gamma puede usarse como wiki de equipo?","a":"Gamma no está diseñado para gestión de conocimiento o wikis — es para crear presentaciones y documentos de comunicación. Para wiki de equipo con IA — Notion AI, Confluence AI o Coda AI son mucho más adecuados."}]
},
"otter-ai-vs-fireflies-ai": {
  "a": "Otter AI", "b": "Fireflies AI",
  "choose_a": ["✅ Quieres transcripción de reuniones en tiempo real con notas resumidas inmediatamente después — Otter está integrado en Zoom, Teams y Meet","✅ Necesitas una herramienta de notas de reunión para uso personal o de equipo pequeño con exportación fácil","✅ Quieres buscar en transcripciones pasadas y destacar momentos clave directamente desde la app","✅ Buscas la mejor experiencia de transcripción en tiempo real con interfaz más intuitiva"],
  "choose_b": ["✅ Necesitas inteligencia de conversación completa: análisis de sentimiento, seguimiento de temas, estadísticas de participación por hablante","✅ Gestionas un equipo de ventas y necesitas analizar llamadas con insights de CRM y seguimiento de temas de ventas","✅ Quieres buscar en todas las reuniones de tu empresa con búsqueda semántica potenciada por IA","✅ Necesitas integración con CRM (HubSpot, Salesforce) para sincronizar automáticamente notas de reuniones con deals"],
  "faq": [{"q":"¿Otter AI o Fireflies para reuniones de equipo?","a":"Para transcripción y notas de reunión básicas — Otter es muy completo y fácil de usar. Para análisis avanzado de conversaciones, inteligencia de ventas e integración con CRM — Fireflies es más potente. Equipos de ventas prefieren Fireflies; equipos de conocimiento general prefieren Otter."},{"q":"¿Otter AI es gratuito?","a":"Otter AI tiene un plan gratuito con 300 minutos de transcripción/mes y máximo 30 por conversación. El plan Pro ($16.99/mes) añade más minutos y funciones. Fireflies tiene plan gratuito con 800 minutos de almacenamiento; planes de pago desde $10/mes."},{"q":"¿Fireflies puede integrarse con Salesforce?","a":"Sí. Fireflies tiene integración directa con Salesforce, HubSpot y otros CRM. Puede crear automáticamente notas de llamada en el CRM después de cada reunión, sincronizar resúmenes y actualizar deals. Esta integración es una de las razones principales por las que equipos de ventas lo prefieren."},{"q":"¿Otter AI transcribe en español?","a":"Otter AI está principalmente optimizado para inglés. La transcripción en español existe pero con menor precisión. Fireflies también está principalmente en inglés. Para transcripción de alta calidad en español, herramientas como Whisper de OpenAI o Rev ofrecen mejor soporte multilingüe."}]
},
"motion-vs-reclaim-ai": {
  "a": "Motion", "b": "Reclaim AI",
  "choose_a": ["✅ Quieres que la IA organice automáticamente todas tus tareas y reuniones en tu calendario cada día sin tu intervención","✅ Necesitas planificación de proyectos integrada: Motion gestiona deadlines, prioridades y distribuye el trabajo en el tiempo automáticamente","✅ Eres profesional con muchas tareas y reuniones que necesita optimización automática del tiempo disponible","✅ Quieres un asistente de planificación de IA que recalcule tu agenda cuando cambian las prioridades"],
  "choose_b": ["✅ Quieres proteger bloques de tiempo para hábitos y tareas recurrentes (ejercicio, tiempo de enfoque, 1:1s) contra invasión de reuniones","✅ Necesitas sincronización bidireccional con herramientas de gestión de proyectos: Asana, Linear, Jira, Todoist","✅ Buscas una herramienta más económica que automatice la defensa de tu tiempo sin reorganizar todo tu calendario","✅ Quieres que los eventos de tu calendario se ajusten automáticamente para proteger tu tiempo de enfoque"],
  "faq": [{"q":"¿Motion o Reclaim para gestión de tiempo con IA?","a":"Motion reorganiza activamente todo tu día — es más agresivo y completo, planificando cada tarea. Reclaim es más sutil: protege bloques de tiempo sin reorganizar todo. Motion es mejor para profesionales con muchas tareas cambiantes; Reclaim para quienes quieren proteger hábitos y tiempo de enfoque."},{"q":"¿Motion es gratuito?","a":"Motion no tiene plan gratuito permanente, solo prueba de 7 días. Los planes de pago empiezan desde $34/mes (Individual). Reclaim AI tiene un plan gratuito con funciones básicas; planes de pago desde $10/mes."},{"q":"¿Reclaim AI puede sincronizar con Jira?","a":"Sí. Reclaim tiene integración con Jira, Asana, Linear y Todoist. Importa tus tareas y las programa automáticamente en tu calendario según disponibilidad y prioridad. Esta integración con herramientas de desarrollo es una de las razones por las que es popular entre equipos técnicos."},{"q":"¿Motion puede gestionar proyectos de equipo?","a":"Sí. Motion tiene funciones de gestión de proyectos de equipo — asignar tareas, gestionar deadlines y coordinar workload entre miembros. La IA planifica el trabajo de cada persona según su disponibilidad real en el calendario. Es más potente que Reclaim para gestión de proyectos."}]
},
"zapier-ai-vs-make": {
  "a": "Zapier AI", "b": "Make",
  "choose_a": ["✅ Eres usuario no técnico que necesita automatizar tareas entre más de 6.000 aplicaciones con la interfaz más fácil del mercado","✅ Quieres usar IA en tus automatizaciones (clasificar emails, resumir contenido, extraer datos) con configuración simple","✅ Tu empresa necesita automatización rápida sin tiempo de aprendizaje técnico — Zapier es el estándar del sector para no-técnicos","✅ Necesitas las mejores integraciones pre-construidas con el mayor número de aplicaciones compatibles"],
  "choose_b": ["✅ Necesitas automatizaciones visuales más complejas con lógica avanzada: iteradores, transformadores de datos, rutas condicionales múltiples","✅ Buscas mejor relación calidad-precio: Make ofrece más operaciones por menos dinero que Zapier para flujos complejos","✅ Construyes flujos de trabajo con manejo de arrays, transformación de datos JSON y webhooks personalizados","✅ Tienes conocimientos técnicos básicos y quieres más control sobre el flujo sin escribir código"],
  "faq": [{"q":"¿Zapier o Make para automatización de marketing?","a":"Ambas funcionan bien para marketing. Zapier es más fácil de configurar con templates listos para HubSpot, Mailchimp, Slack. Make permite flujos más complejos (ej: procesar listas de leads con lógica condicional) a menor precio. Para flujos simples — Zapier; para campañas complejas — Make."},{"q":"¿Cuánto cuesta Zapier?","a":"Zapier tiene plan gratuito con 100 tareas/mes y 5 Zaps. Los planes de pago empiezan desde $19.99/mes (Starter, 750 tareas). Make tiene plan gratuito con 1.000 operaciones; planes desde $10.59/mes. Make es más económico para volumen alto."},{"q":"¿Qué son los Zaps de Zapier?","a":"Un Zap es una automatización en Zapier: un disparador (trigger) de una app que activa una acción en otra. Por ejemplo: 'Cuando alguien completa un formulario de Typeform, añadir fila en Google Sheets y enviar email de bienvenida con Gmail'. Zapier AI puede generar Zaps desde descripción en texto natural."},{"q":"¿Make puede usar IA en automatizaciones?","a":"Sí. Make tiene módulos de IA que integran OpenAI, Anthropic y otros proveedores. Puedes añadir pasos de IA en cualquier parte del flujo: resumir contenido, clasificar datos, generar texto, analizar imágenes. Funciona igual que Zapier AI pero con más control sobre la lógica alrededor."}]
},
"perplexity-vs-notebooklm": {
  "a": "Perplexity", "b": "NotebookLM",
  "choose_a": ["✅ Necesitas búsqueda web en tiempo real con respuestas sintetizadas y fuentes citadas — alternativa directa a Google con IA","✅ Quieres respuestas actualizadas sobre noticias, eventos recientes, precios, disponibilidad — información que cambia","✅ Investigas temas generales y quieres una visión general rápida con múltiples fuentes verificadas","✅ Buscas una herramienta de investigación web IA para el día a día sin necesidad de cargar documentos propios"],
  "choose_b": ["✅ Tienes tus propios documentos (PDFs, artículos, notas) y quieres analizarlos en profundidad con IA que cita exactamente de dónde saca cada afirmación","✅ Necesitas generar podcasts de audio a partir de tus documentos para consumir el contenido en formato diferente","✅ Trabajas en investigación académica o profesional y necesitas síntesis de múltiples fuentes propias con citas precisas","✅ Quieres una herramienta de estudio: cargas el material del curso y haces preguntas sobre él"],
  "faq": [{"q":"¿Perplexity o NotebookLM para investigación?","a":"Perplexity busca en internet en tiempo real — ideal para temas actuales y preguntas sobre el mundo. NotebookLM trabaja solo con documentos que tú cargas — ideal para analizar material específico con citas precisas. Perplexity para investigar el mundo; NotebookLM para analizar tu propio material."},{"q":"¿NotebookLM es gratuito?","a":"Sí. NotebookLM de Google es gratuito con hasta 50 fuentes por notebook y 500.000 palabras por fuente. NotebookLM Plus está disponible con Google One AI Premium ($19.99/mes). Perplexity tiene plan gratuito; Pro ($20/mes) desbloquea modelos avanzados y más búsquedas."},{"q":"¿NotebookLM puede generar podcasts?","a":"Sí. La función Audio Overview de NotebookLM genera automáticamente un podcast conversacional entre dos voces IA que discuten el contenido de tus documentos. Es una de las funciones más innovadoras — convierte papers académicos o informes en contenido de audio fácil de consumir."},{"q":"¿Perplexity puede analizar PDFs?","a":"Sí. Perplexity Pro permite cargar PDFs y hacer preguntas sobre ellos. Sin embargo, NotebookLM está más especializado en análisis profundo de documentos con citaciones exactas. Para un PDF ocasional — Perplexity Pro funciona; para investigación intensiva con múltiples documentos — NotebookLM."}]
},
"elicit-vs-consensus": {
  "a": "Elicit", "b": "Consensus",
  "choose_a": ["✅ Necesitas extraer datos estructurados de múltiples papers académicos: metodología, tamaño de muestra, resultados, conclusiones","✅ Realizas revisiones sistemáticas de literatura y quieres automatizar el proceso de extracción de datos de estudios","✅ Eres investigador que necesita procesar cientos de papers y resumir sus hallazgos en una tabla comparativa","✅ Quieres herramientas de gestión de literatura: clasificar papers, gestionar bibliotecas de referencias con IA"],
  "choose_b": ["✅ Quieres saber qué dice la evidencia científica sobre una pregunta específica con un porcentaje claro de estudios a favor/en contra","✅ Necesitas respuestas rápidas respaldadas por literatura científica sin leer papers completos","✅ Eres profesional de salud, periodista científico o tomador de decisiones que necesita síntesis de evidencia verificable","✅ Quieres citas directas de papers con indicación de si el estudio apoya o contradice la afirmación"],
  "faq": [{"q":"¿Elicit o Consensus para investigación académica?","a":"Elicit es mejor para procesar grandes volúmenes de papers — extrae datos estructurados y hace revisiones sistemáticas. Consensus es mejor para preguntas específicas sobre evidencia — te dice qué porcentaje de estudios apoyan una afirmación. Para revisar literatura — Elicit; para verificar claims — Consensus."},{"q":"¿Elicit es gratuito?","a":"Elicit tiene un plan gratuito con acceso limitado. El plan Plus ($12/mes) ofrece más créditos para búsqueda y extracción. Consensus tiene un plan gratuito limitado; el plan Premium ($9.99/mes) desbloquea todas las funciones de búsqueda científica."},{"q":"¿Consensus inventa resultados?","a":"Consensus está diseñado para citar papers reales y mostrar sus conclusiones — no las inventa. Sin embargo, como toda IA, puede malinterpretar o simplificar matices. Siempre verifica las fuentes originales para investigación seria. Consensus indica cuándo no hay consenso claro sobre una pregunta."},{"q":"¿Qué bases de datos usa Elicit?","a":"Elicit usa principalmente Semantic Scholar, que indexa más de 200 millones de papers académicos de múltiples disciplinas. También se integra con otras fuentes. La cobertura es amplia pero puede no incluir papers muy recientes o de acceso restringido."}]
},
"consensus-vs-perplexity": {
  "a": "Consensus", "b": "Perplexity",
  "choose_a": ["✅ Quieres saber qué dice la evidencia científica publicada sobre una pregunta de salud, comportamiento, educación o ciencia","✅ Necesitas el porcentaje de estudios que apoyan o contradicen una afirmación con citas de papers específicos","✅ Eres profesional que necesita tomar decisiones basadas en evidencia científica verificable, no en noticias o blogs","✅ Investigas claims de salud o bienestar y quieres contrastar con literatura peer-reviewed, no con resultados de web general"],
  "choose_b": ["✅ Necesitas búsqueda web en tiempo real sobre cualquier tema: noticias, eventos, productos, personas, precios","✅ Quieres respuestas síntesis rápidas sobre temas generales sin necesidad de que sean científicamente validados","✅ Investigas temas de actualidad donde los papers académicos no son la fuente más relevante","✅ Buscas la mejor alternativa a Google para búsqueda general con IA, no específicamente para investigación científica"],
  "faq": [{"q":"¿Consensus o Google Scholar para investigación?","a":"Consensus usa IA para sintetizar qué dice la evidencia — te da la respuesta directamente con porcentajes. Google Scholar muestra la lista de papers pero no sintetiza. Para encontrar papers específicos — Scholar; para entender qué dice la evidencia sobre una pregunta — Consensus es más eficiente."},{"q":"¿Consensus es fiable?","a":"Consensus se basa en papers peer-reviewed reales de bases de datos como Semantic Scholar. Es más fiable que una búsqueda web general para preguntas científicas. Sin embargo, simplifica la investigación — para decisiones críticas, leer los papers originales sigue siendo necesario."},{"q":"¿Perplexity puede buscar papers académicos?","a":"Perplexity tiene un modo académico que prioriza fuentes académicas. Sin embargo, no tiene las capacidades especializadas de Consensus — no calcula porcentajes de consenso ni está entrenado específicamente para síntesis de investigación científica. Para preguntas académicas serias — Consensus."},{"q":"¿Consensus es gratuito?","a":"Consensus tiene un plan gratuito con 20 búsquedas/mes. El plan Premium ($9.99/mes) ofrece búsquedas ilimitadas, filtros avanzados y análisis de papers completos. Perplexity tiene plan gratuito; Pro ($20/mes) para búsquedas avanzadas ilimitadas."}]
},
"notebooklm-vs-humata": {
  "a": "NotebookLM", "b": "Humata",
  "choose_a": ["✅ Quieres analizar múltiples documentos juntos y hacer preguntas que sinteticen información de varias fuentes simultáneamente","✅ Necesitas la función de Audio Overview: convertir tus documentos en un podcast conversacional de audio","✅ Trabajas con material de estudio o investigación y quieres una herramienta gratuita de Google con citas precisas","✅ Quieres compartir notebooks con colegas para investigación colaborativa con las mismas fuentes"],
  "choose_b": ["✅ Tu caso de uso principal es hacer preguntas rápidas sobre un PDF técnico o documento específico para encontrar información","✅ Necesitas procesar PDFs largos (informes, contratos, papers) y extraer respuestas concretas con referencia de página","✅ Trabajas en entornos empresariales que manejan documentos sensibles y prefieres garantías de privacidad claras","✅ Quieres integrar análisis de documentos PDF en flujos de trabajo empresariales con API"],
  "faq": [{"q":"¿NotebookLM o Humata para PDFs?","a":"NotebookLM es más potente para análisis profundo con múltiples documentos y genera Audio Overviews. Humata está más enfocado en Q&A rápido sobre PDFs individuales para contextos empresariales. Para investigación con múltiples fuentes — NotebookLM; para preguntas sobre documentos en contexto de negocio — Humata."},{"q":"¿NotebookLM puede leer PDFs?","a":"Sí. NotebookLM acepta PDFs, Google Docs, páginas web, videos de YouTube y archivos de texto como fuentes. Puedes cargar hasta 50 fuentes por notebook. Analiza el contenido con citas exactas de página y sección."},{"q":"¿Humata es gratuito?","a":"Humata tiene un plan gratuito con 60 páginas de PDF/mes. El plan Student ($1.99/mes) y Team ($9.99/usuario/mes) ofrecen más capacidad. NotebookLM de Google es gratuito con límites generosos — la opción más económica para análisis de documentos."},{"q":"¿NotebookLM puede equivocarse?","a":"NotebookLM puede simplificar o malinterpretar documentos complejos. Tiene la ventaja de citar exactamente de dónde saca cada afirmación — lo que te permite verificar fácilmente. Para investigación crítica, siempre verifica en las fuentes originales que NotebookLM cita."}]
},
"scite-vs-semantic-scholar": {
  "a": "Scite", "b": "Semantic Scholar",
  "choose_a": ["✅ Quieres saber si estudios posteriores han confirmado, contradicho o simplemente citado un paper específico — Smart Citations","✅ Necesitas evaluar la credibilidad de un paper viendo su historial de citaciones: ¿otros lo apoyan o lo refutan?","✅ Eres investigador que necesita verificar claims científicos buscando cómo la comunidad científica ha respondido a un estudio","✅ Quieres asistente IA para búsqueda y síntesis de literatura científica con citaciones clasificadas por tipo"],
  "choose_b": ["✅ Necesitas acceso gratuito ilimitado a más de 200 millones de papers académicos de todas las disciplinas","✅ Quieres ver la influencia de un paper: cuántas veces ha sido citado, por quién y en qué contexto","✅ Buscas papers relacionados semánticamente — Semantic Scholar usa IA para recomendar literatura relevante","✅ Necesitas la base de datos de papers académicos más grande sin costo, ideal para búsqueda exploratoria"],
  "faq": [{"q":"¿Qué son las Smart Citations de Scite?","a":"Smart Citations de Scite clasifica automáticamente las citas de un paper según si citas posteriores lo apoyan (supporting), contradicen (contrasting) o simplemente lo mencionan (mentioning). Esto te permite evaluar rápidamente si un paper ha sido validado o refutado por la comunidad científica."},{"q":"¿Semantic Scholar es gratuito?","a":"Sí. Semantic Scholar es completamente gratuito — es un proyecto del Allen Institute for AI. Incluye 200M+ papers, gráficos de citas, papers relacionados y funciones de IA básicas sin costo. Scite tiene funciones limitadas gratuitas; el plan premium cuesta $20/mes."},{"q":"¿Scite vs ResearchRabbit?","a":"Scite se centra en clasificar citaciones (supporting/contrasting). ResearchRabbit es mejor para descubrir literatura relacionada visualmente — crea mapas de investigación conectando papers por similitud y autores. Para verificar claims — Scite; para explorar un campo nuevo — ResearchRabbit."},{"q":"¿Qué disciplinas cubre Semantic Scholar?","a":"Semantic Scholar cubre todas las disciplinas académicas: ciencias, medicina, informática, ciencias sociales, humanidades, ingeniería y más. Con 200 millones de papers, es una de las bases de datos académicas más completas disponibles gratuitamente."}]
},
"looker-studio-vs-tableau-ai": {
  "a": "Looker Studio", "b": "Tableau AI",
  "choose_a": ["✅ Necesitas dashboards de datos gratuitos conectados a Google Analytics, Search Console, Google Ads, Sheets y BigQuery","✅ Tu equipo de marketing o SEO necesita reportes visuales de datos de Google sin presupuesto para herramientas BI","✅ Compartes reportes con clientes o stakeholders a través de links sin que necesiten instalar nada","✅ Comienzas con business intelligence y necesitas la herramienta más accesible y gratuita del mercado"],
  "choose_b": ["✅ Necesitas análisis de datos exploratorio avanzado con visualizaciones más potentes e interactivas","✅ Tu organización trabaja con grandes volúmenes de datos de múltiples fuentes que van más allá del ecosistema Google","✅ Quieres las funciones de IA de Tableau: análisis explicativo automático, preguntas en lenguaje natural, predicciones","✅ Necesitas una herramienta BI empresarial con gobernanza de datos, permisos avanzados y soporte de nivel empresa"],
  "faq": [{"q":"¿Looker Studio o Tableau para marketing?","a":"Looker Studio para marketing digital es excelente — integración nativa con Google Analytics, Ads y Search Console, completamente gratuito. Tableau es más potente para análisis complejo con datos de múltiples fuentes. Para reportes de marketing de Google — Looker Studio; para análisis BI empresarial avanzado — Tableau."},{"q":"¿Looker Studio es gratuito?","a":"Sí. Looker Studio es completamente gratuito para individuos y equipos. Google ofrece hasta 1.000 informes gratuitos. Looker Studio Pro ($9/usuario/mes) añade funciones de colaboración empresarial. Tableau empieza desde $75/usuario/mes."},{"q":"¿Qué es Tableau AI?","a":"Tableau AI son las funciones de inteligencia artificial integradas en Tableau: Einstein Analytics explica automáticamente por qué cambian los datos, Ask Data permite preguntas en lenguaje natural sobre cualquier dashboard, y Tableau Pulse envía resúmenes inteligentes automáticos. Disponibles en Tableau Cloud."},{"q":"¿Looker Studio vs Google Data Studio?","a":"Son el mismo producto. Google Data Studio fue renombrado a Looker Studio en 2022. Looker Studio sigue siendo la herramienta gratuita de reportes de Google, con las mismas funciones de siempre más nuevas integraciones."}]
},
"julius-ai-vs-looker-studio": {
  "a": "Julius AI", "b": "Looker Studio",
  "choose_a": ["✅ Quieres analizar datos subiendo un CSV o Excel y preguntando en lenguaje natural sin configurar dashboards","✅ Necesitas análisis exploratorio rápido: 'muéstrame las ventas por región el último trimestre' en segundos","✅ Eres analista o científico de datos que necesita exploración conversacional sin preparar visualizaciones de antemano","✅ Quieres que la IA genere código Python/R automáticamente para análisis estadístico más avanzado"],
  "choose_b": ["✅ Necesitas dashboards en tiempo real conectados a fuentes de datos vivas (Google Analytics, bases de datos, APIs)","✅ Produces reportes recurrentes que se actualizan automáticamente y compartes con clientes o equipo","✅ Necesitas una herramienta de reporting establecida con plantillas, compartición de links y colaboración de equipo","✅ Tu equipo de marketing necesita dashboards de Google (Analytics, Ads, Search Console) siempre actualizados"],
  "faq": [{"q":"¿Julius AI o ChatGPT para análisis de datos?","a":"Julius AI está especializado en análisis de datos — ejecuta código Python automáticamente, genera gráficos interactivos y puede hacer estadística avanzada. ChatGPT puede ayudar con análisis pero sin ejecutar código en tiempo real (salvo con el intérprete de código de Plus). Para análisis de datos serio — Julius AI."},{"q":"¿Julius AI es gratuito?","a":"Julius AI tiene un plan gratuito con 15 análisis al mes. Los planes de pago empiezan desde $22/mes (Essential) con análisis ilimitados. Looker Studio es completamente gratuito."},{"q":"¿Qué tipos de archivos acepta Julius AI?","a":"Julius AI acepta CSV, Excel, Google Sheets y conexiones directas a bases de datos. También puede conectarse a APIs y procesar datos estructurados de diversas fuentes. Looke Studio acepta principalmente datos de Google y conectores de bases de datos."},{"q":"¿Puede Julius AI reemplazar a un analista de datos?","a":"Julius AI automatiza muchas tareas de análisis exploratorio — limpieza de datos, visualización, estadística básica y correlaciones. Sin embargo, para análisis estratégico, interpretación de negocio y modelado predictivo complejo, un analista humano sigue siendo necesario. Es una herramienta de asistencia, no un reemplazo."}]
},
"hex-vs-looker-studio": {
  "a": "Hex", "b": "Looker Studio",
  "choose_a": ["✅ Eres científico de datos o analista técnico que necesita notebooks colaborativos con SQL y Python en un solo lugar","✅ Quieres combinar consultas SQL con visualizaciones interactivas y narrativa explicativa en un documento compartible","✅ Tu equipo necesita publicar análisis de datos complejos como apps interactivas para stakeholders no técnicos","✅ Necesitas control total sobre transformaciones de datos con código mientras mantienes visualizaciones de calidad BI"],
  "choose_b": ["✅ Tu equipo de negocio necesita dashboards conectados a Google y otras fuentes sin conocimientos técnicos de código","✅ Produces reportes de marketing digital con datos de Google Analytics, Ads y Search Console completamente gratis","✅ Compartes dashboards con clientes o stakeholders que solo necesitan ver el reporte actualizado automáticamente","✅ Buscas la opción más accesible y económica para reporting de datos de Google"],
  "faq": [{"q":"¿Hex o Jupyter Notebooks para análisis de datos?","a":"Hex es una versión colaborativa y más potente de Jupyter — añade SQL nativo, visualizaciones drag-and-drop, publicación como apps y colaboración en tiempo real. Para análisis individual exploratorio — Jupyter es suficiente y gratuito. Para equipos de datos que necesitan compartir y publicar — Hex."},{"q":"¿Hex es gratuito?","a":"Hex tiene un plan gratuito para proyectos personales con funciones limitadas. Los planes de pago empiezan desde $24/mes (Team). Looker Studio es completamente gratuito. Hex está orientado a equipos de datos; Looker Studio a marketing y business."},{"q":"¿Qué lenguajes soporta Hex?","a":"Hex soporta SQL (para cualquier base de datos) y Python. Puedes combinar celdas SQL y Python en el mismo notebook, lo que lo hace muy flexible para análisis que requieren tanto consultas de BD como procesamiento de datos con Python."},{"q":"¿Hex puede conectarse a BigQuery?","a":"Sí. Hex se conecta a BigQuery, Snowflake, Databricks, Redshift, PostgreSQL y muchos otros data warehouses. Looker Studio también conecta a BigQuery de forma nativa. Ambas son buenas opciones para análisis sobre BigQuery; Hex ofrece más capacidad de transformación con código."}]
},
"rows-vs-hex": {
  "a": "Rows", "b": "Hex",
  "choose_a": ["✅ Necesitas una hoja de cálculo familiar (tipo Excel/Google Sheets) que se conecta a APIs, bases de datos y fuentes externas sin programar","✅ Quieres enriquecer datos con IA directamente en celdas: enriquecer listas de empresas, generar contenido, clasificar datos","✅ Tu equipo no es técnico y necesita datos externos en una interfaz de hoja de cálculo familiar sin código","✅ Buscas automatizar reportes de datos sin aprender SQL ni Python — solo configurar integraciones en una tabla"],
  "choose_b": ["✅ Eres científico de datos o analista técnico que necesita combinar SQL, Python y visualizaciones en notebooks colaborativos","✅ Necesitas análisis estadístico avanzado, machine learning básico o transformaciones complejas de datos con código","✅ Tu equipo publica análisis como apps interactivas para stakeholders que necesitan explorar los datos","✅ Trabajas con grandes volúmenes de datos en data warehouses (BigQuery, Snowflake, Databricks) a escala"],
  "faq": [{"q":"¿Qué es Rows?","a":"Rows es una hoja de cálculo potenciada con IA e integraciones. Tiene interfaz familiar de spreadsheet pero se conecta nativamente a cientos de APIs (Twitter, HubSpot, Stripe, SQL databases), permite enriquecer datos con IA y automatizar reportes recurrentes sin código."},{"q":"¿Rows es gratuito?","a":"Rows tiene un plan gratuito con funciones básicas e integraciones limitadas. Los planes de pago empiezan desde $59/mes (Plus). Hex tiene plan gratuito para proyectos personales; planes de pago desde $24/mes."},{"q":"¿Rows puede reemplazar a Google Sheets?","a":"Para casos de uso con datos externos y automatización — Rows ofrece más capacidades. Para colaboración simple y compatibilidad con el ecosistema Google — Google Sheets sigue siendo más práctico. Muchos equipos usan ambas: Sheets para colaboración general, Rows para reportes de datos automatizados."},{"q":"¿Hex o Rows para equipos de marketing?","a":"Rows es más adecuado para marketing — interfaz de hoja de cálculo familiar, sin necesidad de SQL o Python, integraciones directas con herramientas de marketing (HubSpot, Stripe). Hex está orientado a equipos de datos técnicos. Para marketing — Rows; para data science — Hex."}]
},
"retool-ai-vs-looker-studio": {
  "a": "Retool AI", "b": "Looker Studio",
  "choose_a": ["✅ Necesitas herramientas internas que permitan acciones sobre los datos, no solo visualizarlos (actualizar registros, aprobar solicitudes, ejecutar operaciones)","✅ Construyes paneles de administración, herramientas de soporte al cliente o dashboards operativos con flujos de trabajo integrados","✅ Tu equipo técnico necesita crear aplicaciones internas rápidamente conectadas a bases de datos propias o APIs","✅ Quieres incorporar IA en tus herramientas internas: asistentes de soporte, generación de contenido, análisis automático"],
  "choose_b": ["✅ Necesitas dashboards de reporting y visualización de datos para comunicar métricas sin capacidad de acciones","✅ Tu equipo de marketing o SEO necesita reportes de Google (Analytics, Ads, Search Console) completamente gratis","✅ Compartes informes con clientes o stakeholders que solo necesitan ver gráficos actualizados automáticamente","✅ Buscas la opción más económica (gratuita) para dashboards de datos sin necesidad de desarrollo"],
  "faq": [{"q":"¿Retool o Bubble para apps internas?","a":"Retool está diseñado específicamente para herramientas internas de empresa — se conecta a bases de datos y APIs existentes con menos configuración. Bubble es mejor para aplicaciones de cara al usuario con base de datos propia. Para herramientas internas de equipo — Retool; para apps de usuario final — Bubble."},{"q":"¿Retool es gratuito?","a":"Retool tiene plan gratuito para hasta 5 usuarios con apps ilimitadas. Los planes de pago empiezan desde $10/usuario/mes (Team). Looker Studio es completamente gratuito."},{"q":"¿Qué es Retool AI?","a":"Retool AI son las funciones de inteligencia artificial integradas en Retool — permite añadir asistentes de IA en herramientas internas, generar queries SQL automáticamente, crear chats de soporte al cliente con contexto de tu base de datos, y automatizar tareas repetitivas dentro de tus apps."},{"q":"¿Retool puede conectarse a cualquier base de datos?","a":"Sí. Retool se conecta a más de 100 fuentes de datos: PostgreSQL, MySQL, MongoDB, REST APIs, GraphQL, Airtable, Salesforce, Stripe y muchas más. Esta compatibilidad amplia es una de sus mayores fortalezas para construcción de herramientas internas."}]
},
"bubble-vs-webflow": {
  "a": "Bubble", "b": "Webflow",
  "choose_a": ["✅ Necesitas construir una aplicación web con lógica de negocio compleja: autenticación de usuarios, base de datos, flujos de trabajo, pagos, APIs","✅ Creas un MVP o producto SaaS sin saber programar — Bubble es el no-code más potente para aplicaciones reales","✅ Tu aplicación necesita funcionalidades dinámicas: perfiles de usuario, dashboards personalizados, interacciones basadas en datos","✅ Construyes un marketplace, red social o herramienta de gestión interna que requiere lógica backend compleja"],
  "choose_b": ["✅ Necesitas crear un sitio web de marketing profesional con diseño visual impecable y CMS para contenido","✅ Tu proyecto es un sitio corporativo, portfolio, blog o landing page — no una aplicación con lógica compleja","✅ Quieres el mejor control de diseño visual sin código: pixel-perfect layouts, animaciones avanzadas, responsive design","✅ Necesitas e-commerce básico o un CMS potente para equipo de contenido sin desarrolladores"],
  "faq": [{"q":"¿Bubble o Webflow para startups?","a":"Depende del producto. Si construyes una aplicación SaaS con usuarios, datos y lógica — Bubble. Si construyes el sitio web de marketing de tu startup — Webflow. Muchas startups usan ambas: Webflow para el sitio de marketing y Bubble para el producto."},{"q":"¿Bubble es gratuito?","a":"Bubble tiene plan gratuito para desarrollar y probar apps (con subdominio bubble.io). Para lanzar en producción, el plan más económico cuesta $32/mes (Starter). Webflow tiene plan gratuito para 2 proyectos con subdominio webflow.io; planes para sites desde $14/mes."},{"q":"¿Qué apps famosas se construyeron en Bubble?","a":"Varias startups notables comenzaron en Bubble: Dividend Finance, Teal (gestión de carrera), varios MVPs de Y Combinator. Bubble es reconocido en el ecosistema no-code como la plataforma más seria para construir productos reales antes de contratar desarrolladores."},{"q":"¿Puede Webflow construir aplicaciones?","a":"Webflow tiene lógica básica (formularios, filtros, miembros) pero no está diseñado para aplicaciones complejas con base de datos propia y lógica de negocio. Para funcionalidades de app reales — Bubble. Webflow es mejor para sitios con contenido dinámico pero no para productos SaaS."}]
},
"lovable-vs-bubble": {
  "a": "Lovable", "b": "Bubble",
  "choose_a": ["✅ Quieres construir una app web completa generando código desde una descripción de texto — Lovable usa IA para generar React + Supabase directamente","✅ Necesitas velocidad máxima: de idea a prototipo funcional en horas, mucho más rápido que aprender Bubble","✅ Quieres poseer el código generado: Lovable exporta código real que puedes hospedar en cualquier lugar","✅ Eres desarrollador que quiere acelerar el desarrollo con IA o no-técnico que quiere empezar con IA generativa"],
  "choose_b": ["✅ Necesitas una plataforma no-code madura con ecosistema establecido: miles de plugins, tutoriales, agencia de Bubble disponible","✅ Construyes una app compleja con workflows visuales, lógica de negocio detallada y control granular sobre cada proceso","✅ No quieres depender del código generado — Bubble te da control visual completo sin necesidad de entender el código","✅ Tu app requiere integración con servicios externos específicos con plugins de Bubble ya construidos"],
  "faq": [{"q":"¿Lovable o Cursor para desarrollo con IA?","a":"Lovable está diseñado para crear apps de principio a fin desde cero desde prompts de texto. Cursor es un editor de código para desarrolladores que ya saben programar. Lovable para no-técnicos que quieren construir apps con IA; Cursor para desarrolladores que quieren IA en su flujo de código."},{"q":"¿Lovable es gratuito?","a":"Lovable tiene un plan gratuito con créditos limitados. Los planes de pago empiezan desde $20/mes (Starter). Bubble tiene plan gratuito para desarrollo; producción desde $32/mes."},{"q":"¿El código de Lovable es de calidad?","a":"Lovable genera código React con Supabase — tecnologías estándar de la industria. La calidad varía según la complejidad. Para MVPs y prototipos, el código es generalmente funcional. Para producción a escala, puede requerir revisión y refactoring por un desarrollador."},{"q":"¿Puede Lovable conectarse a bases de datos existentes?","a":"Lovable usa principalmente Supabase como backend. Puede conectarse a otras APIs y bases de datos según la complejidad del prompt. Bubble tiene más conectores nativos para integraciones de terceros. Para bases de datos existentes complejas — Bubble puede ser más flexible actualmente."}]
},
"flutterflow-vs-bubble": {
  "a": "FlutterFlow", "b": "Bubble",
  "choose_a": ["✅ Necesitas construir apps móviles nativas para iOS y Android — FlutterFlow genera código Flutter real para publicar en App Store y Play Store","✅ Quieres la mejor experiencia en móvil: rendimiento nativo, animaciones fluidas y acceso a APIs del dispositivo (cámara, GPS, notificaciones)","✅ Usas Firebase como backend y quieres una herramienta no-code integrada con el ecosistema Google/Firebase","✅ Exportas el código Flutter para continuar el desarrollo con un equipo técnico cuando escales"],
  "choose_b": ["✅ Tu producto es principalmente una aplicación web — Bubble está más maduro para web apps complejas","✅ Necesitas un ecosistema más rico de plugins, workflows visuales y mayor comunidad de soporte","✅ No planeas publicar en app stores — Bubble genera web apps responsivas que funcionan en móvil vía navegador","✅ Necesitas lógica de negocio más compleja con workflows visuales y conexiones a bases de datos relacionales"],
  "faq": [{"q":"¿FlutterFlow o React Native para apps móviles?","a":"FlutterFlow es no-code — mucho más rápido para empezar sin programar. React Native requiere conocimientos de JavaScript pero da más control. FlutterFlow para MVPs rápidos y no-técnicos; React Native para equipos de desarrollo con control total. FlutterFlow puede exportar código Flutter si necesitas."},{"q":"¿FlutterFlow es gratuito?","a":"FlutterFlow tiene plan gratuito con funciones básicas. Los planes de pago empiezan desde $30/mes (Standard) para publicar en app stores y acceder a más funciones. Bubble tiene plan gratuito; producción desde $32/mes."},{"q":"¿Pueden publicarse apps de FlutterFlow en App Store?","a":"Sí. FlutterFlow genera código Flutter real que puedes compilar y publicar en App Store (iOS) y Play Store (Android). Bubble web apps pueden funcionar en móvil pero no se publican como apps nativas en tiendas de apps."},{"q":"¿FlutterFlow o Adalo para apps móviles sin código?","a":"FlutterFlow usa Flutter (más moderno) y produce apps de mayor calidad y rendimiento. Adalo es más fácil para principiantes. FlutterFlow tiene mayor curva de aprendizaje pero mejor resultado final — especialmente para apps complejas con Firebase."}]
},
"glide-vs-bubble": {
  "a": "Glide", "b": "Bubble",
  "choose_a": ["✅ Tienes datos en Google Sheets o Excel y quieres convertirlos en una app móvil o web en minutos sin configurar base de datos","✅ Construyes herramientas internas sencillas: directorio de empleados, tracker de inventario, app de campo — sin desarrollo","✅ Necesitas la herramienta no-code más rápida para prototipar y lanzar apps simples basadas en datos existentes","✅ Buscas la opción más económica para apps de negocio simples conectadas a hojas de cálculo"],
  "choose_b": ["✅ Necesitas una aplicación web con lógica de negocio compleja, base de datos propia y flujos avanzados","✅ Tu app necesita autenticación, roles de usuario, pagos y funcionalidades más allá de mostrar datos de una hoja","✅ Construyes un SaaS o marketplace que escalará a miles de usuarios con lógica dinámica","✅ Necesitas mayor control sobre el diseño y la experiencia de usuario que Glide permite"],
  "faq": [{"q":"¿Glide o AppSheet para apps de Google Sheets?","a":"Glide produce apps con diseño más moderno y atractivo — mejor experiencia visual. AppSheet (de Google) tiene más funciones para flujos de negocio complejos e integración nativa con Google Workspace. Para apps simples y bien diseñadas — Glide; para flujos complejos con Sheets — AppSheet."},{"q":"¿Glide es gratuito?","a":"Glide tiene un plan gratuito para proyectos personales con 500 filas de datos. Los planes de negocios empiezan desde $49/mes (Starter). Bubble tiene plan gratuito para desarrollo; producción desde $32/mes."},{"q":"¿Qué tipo de apps se pueden hacer con Glide?","a":"Glide es ideal para: directorios de empleados, apps de seguimiento de inventario, portales de clientes simples, apps de campo para equipos en terreno, catálogos de productos, apps de eventos y cualquier app que se base en datos tabulares simples."},{"q":"¿Glide puede conectarse a bases de datos más allá de Sheets?","a":"Sí. Glide también se conecta a Airtable, Excel, MySQL, BigQuery y otras fuentes de datos. Sin embargo, Google Sheets sigue siendo la integración más fluida y popular. Para bases de datos SQL complejas — Bubble ofrece más flexibilidad."}]
},
"softr-vs-bubble": {
  "a": "Softr", "b": "Bubble",
  "choose_a": ["✅ Necesitas construir un portal de clientes, directorio de membresía, intranet o comunidad conectada a Airtable o Google Sheets","✅ Quieres lanzar rápidamente sin código — Softr es el más sencillo para portales de membresía sin configuración técnica","✅ Tu caso de uso encaja en los templates de Softr: portal de clientes, job board, directorio, marketplace de servicios","✅ Airtable es tu fuente de verdad y necesitas una interfaz de cara al usuario para tus datos"],
  "choose_b": ["✅ Necesitas lógica de negocio avanzada que va más allá de mostrar datos de Airtable a usuarios autenticados","✅ Construyes una aplicación web completa con flujos complejos, pagos, workflows automatizados y base de datos propia","✅ Tu app escalará a miles de usuarios con necesidades de personalización profunda que Softr no cubre","✅ Necesitas mayor control sobre el diseño y la funcionalidad que los bloques de Softr permiten"],
  "faq": [{"q":"¿Softr o Glide para portales de clientes?","a":"Ambas son buenas para portales simples. Softr está más orientado a portales de membresía y comunidades con Airtable. Glide es mejor para apps de campo y herramientas internas basadas en Sheets. Para portales de clientes B2B con Airtable — Softr; para apps de equipo móvil — Glide."},{"q":"¿Softr es gratuito?","a":"Softr tiene plan gratuito con 5 usuarios internos y funciones básicas. Los planes de pago empiezan desde $49/mes (Basic). Bubble tiene plan gratuito para desarrollo; producción desde $32/mes."},{"q":"¿Qué es Airtable y por qué Softr lo usa?","a":"Airtable es una base de datos visual tipo hoja de cálculo con relaciones entre tablas — más potente que Google Sheets pero más simple que SQL. Softr usa Airtable como backend porque muchos equipos ya gestionan sus datos allí. Puedes construir un portal de clientes completo sin tocar código."},{"q":"¿Softr puede hacer e-commerce?","a":"Softr tiene funciones básicas de e-commerce para directorios de productos y marketplaces simples. Para tiendas online con inventario complejo, pagos avanzados y logística — Bubble o Shopify son más adecuados."}]
},
"webflow-vs-framer-ai": {
  "a": "Webflow", "b": "Framer AI",
  "choose_a": ["✅ Necesitas un sitio web con CMS potente para publicar contenido regularmente: blog, portfolio, sitio de productos","✅ Quieres control total sobre cada aspecto del diseño y código CSS sin limitaciones de plantilla","✅ Tu sitio requiere e-commerce, membresías o integraciones complejas con un CMS estructurado","✅ Necesitas SEO avanzado: control completo de metadatos, schemas estructurados, sitemap y rendimiento"],
  "choose_b": ["✅ Quieres la forma más rápida de crear y publicar un sitio web moderno con IA — descripción de texto a sitio publicado","✅ Tu sitio es de presentación o landing page que necesita animaciones impresionantes y diseño muy moderno","✅ Priorizas el tiempo de lanzamiento sobre el control granular — Framer AI lanza en horas vs. días en Webflow","✅ Quieres animaciones de scroll y transiciones avanzadas sin configuración técnica compleja"],
  "faq": [{"q":"¿Webflow o WordPress en 2025?","a":"Webflow ofrece más control de diseño visual y no requiere plugins de seguridad. WordPress tiene más plugins (50.000+), mayor ecosistema y es gratuito de base. Para diseños personalizados sin código complejo — Webflow. Para blogs con mucho contenido y SEO establecido — WordPress sigue siendo una opción sólida."},{"q":"¿Webflow es gratuito?","a":"Webflow tiene plan gratuito para 2 proyectos con subdominio webflow.io. Para sitios con dominio propio, el plan Basic empieza desde $14/mes. CMS desde $23/mes. Framer tiene plan gratuito con subdominio y planes desde $5/mes."},{"q":"¿Framer AI genera el código real del sitio?","a":"Sí. Framer AI genera el diseño real del sitio — no es un mockup sino un sitio publicable directamente. Genera código React que se compila y sirve. Puedes editar el resultado visualmente o en código si tienes conocimientos técnicos."},{"q":"¿Webflow o Framer para agencias?","a":"Webflow es más maduro para agencias — tiene flujos de trabajo para múltiples clientes, transferencia de proyectos y CMS avanzado para clientes que gestionan su propio contenido. Framer es más popular para sitios de presentación de startups y portfolios modernos."}]
},
"photomath-vs-duolingo-max": {
  "a": "Photomath", "b": "Duolingo Max",
  "choose_a": ["✅ Necesitas resolver problemas de matemáticas paso a paso — fotografías el ejercicio con la cámara y Photomath explica la solución","✅ Eres estudiante de secundaria o universidad con dificultades en matemáticas, álgebra, cálculo o geometría","✅ Quieres entender el proceso, no solo la respuesta — Photomath muestra cada paso con explicación","✅ Buscas la herramienta más eficiente para aprender matemáticas con práctica de problemas específicos"],
  "choose_b": ["✅ Quieres aprender o mejorar un idioma extranjero con el método gamificado más popular del mundo","✅ Necesitas práctica de conversación con IA (Roleplay) y explicaciones de errores por IA (Explain My Answer) en Duolingo Max","✅ Aprendes idiomas de forma consistente con racha diaria, sistema de puntos y lecciones de 5 minutos","✅ Buscas la experiencia de aprendizaje de idiomas más accesible y motivadora para hábito diario"],
  "faq": [{"q":"¿Photomath o Wolfram Alpha para matemáticas?","a":"Photomath es más accesible — fotografías el problema y obtienes pasos explicados en lenguaje simple. Wolfram Alpha es más potente para matemáticas avanzadas (universitarias, cálculo complejo) pero requiere escribir el problema correctamente. Para estudiantes de secundaria — Photomath; para matemáticas avanzadas — Wolfram Alpha."},{"q":"¿Photomath es gratuito?","a":"Photomath tiene una versión gratuita que resuelve problemas y muestra pasos básicos. Photomath Plus ($9.99/mes o $29.99/año) desbloquea pasos animados, más métodos de solución y práctica adicional. Duolingo Max ($14.99/mes, incluido en Super Duolingo en algunos planes)."},{"q":"¿Duolingo Max vale la pena?","a":"Duolingo Max añade dos funciones sobre Super Duolingo: Roleplay (práctica de conversación IA en situaciones reales) y Explain My Answer (la IA explica por qué una respuesta es correcta o incorrecta). Para aprendizaje serio de idiomas que ya usa Duolingo regularmente — vale la pena."},{"q":"¿Puede Photomath hacer trampa en los deberes?","a":"Photomath puede resolver problemas automáticamente, lo que algunos usan para copiar en lugar de aprender. La herramienta está diseñada para aprender los pasos, no para obtener respuestas sin entender. Usarla responsablemente — entender cada paso — hace la diferencia entre aprender y copiar."}]
},
"khanmigo-vs-photomath": {
  "a": "Khanmigo", "b": "Photomath",
  "choose_a": ["✅ Necesitas un tutor de IA socrático que guía sin dar la respuesta directamente — fomenta el pensamiento crítico","✅ Quieres ayuda en múltiples materias: matemáticas, ciencias, historia, escritura, programación — no solo matemáticas","✅ Eres padre o educador que busca una herramienta IA educativa segura con enfoque pedagógico probado","✅ Buscas preparación para exámenes estandarizados con práctica adaptativa en todas las materias del currículo"],
  "choose_b": ["✅ Necesitas resolver un problema de matemáticas específico ahora mismo con los pasos explicados","✅ Quieres la solución más rápida y directa para un ejercicio concreto de álgebra, geometría o cálculo","✅ Tu hijo necesita ayuda inmediata con los deberes de matemáticas sin esperar explicaciones largas","✅ Buscas la herramienta más accesible (gratuita) para verificar y entender soluciones matemáticas"],
  "faq": [{"q":"¿Khanmigo es de Khan Academy?","a":"Sí. Khanmigo es el tutor de IA de Khan Academy, basado en GPT-4. Sigue la filosofía socrática de Khan Academy — hace preguntas guía en lugar de dar respuestas directas, fomentando que el estudiante razone por sí mismo."},{"q":"¿Khanmigo es gratuito?","a":"Khanmigo tiene un costo mensual ($44/año o $9/mes en EE.UU.) que va a la fundación Khan Academy. El contenido de Khan Academy en sí sigue siendo gratuito. Photomath tiene versión gratuita; Plus desde $9.99/mes."},{"q":"¿Para qué edades es Khanmigo?","a":"Khanmigo está diseñado para estudiantes desde primaria hasta universidad, con contenido adaptado al nivel. También tiene herramientas para profesores. Es especialmente útil para secundaria y preparatoria donde el contenido cubre todas las materias del currículo estándar."},{"q":"¿Photomath puede resolver álgebra lineal universitaria?","a":"Photomath cubre desde aritmética básica hasta cálculo diferencial e integral universitario. Para álgebra lineal (matrices, vectores, eigenvalores) y matemáticas más avanzadas, Wolfram Alpha o Symbolab son más completos."}]
},
"duolingo-max-vs-khanmigo": {
  "a": "Duolingo Max", "b": "Khanmigo",
  "choose_a": ["✅ Tu objetivo principal es aprender o mantener un idioma extranjero con el método más motivador y gamificado","✅ Quieres práctica de conversación con IA (Roleplay) en situaciones reales del idioma que aprendes","✅ Necesitas un hábito diario de aprendizaje de idiomas con sistema de rachas y recompensas que te mantiene constante","✅ Aprendes español, francés, japonés u otro idioma de los disponibles en Duolingo con asistencia IA avanzada"],
  "choose_b": ["✅ Necesitas tutoría IA en múltiples materias académicas: matemáticas, ciencias, historia, literatura, SAT","✅ Buscas un tutor socrático que te guía sin darte las respuestas directamente, fomentando el pensamiento crítico","✅ Eres estudiante de secundaria que necesita ayuda integral en el currículo académico, no solo idiomas","✅ Quieres preparación para exámenes académicos (SAT, ACT) con práctica adaptativa en todas las materias"],
  "faq": [{"q":"¿Duolingo Max o Babbel para aprender idiomas?","a":"Duolingo Max es más gamificado y gratuito en su versión básica — ideal para hábito diario y motivación. Babbel es más estructurado y orientado a conversación práctica desde el principio, sin elementos de juego. Para comenzar y mantener el hábito — Duolingo; para aprendizaje más serio y estructurado — Babbel."},{"q":"¿Qué idiomas tiene Duolingo Max?","a":"Duolingo Max (con IA avanzada) está disponible principalmente para inglés (para hablantes de español) y español (para hablantes de inglés). Las funciones de Roleplay y Explain My Answer están expandiéndose a más idiomas gradualmente."},{"q":"¿Khanmigo ayuda con idiomas extranjeros?","a":"Khanmigo puede ayudar con gramática inglesa y escritura, pero no está diseñado para enseñar idiomas extranjeros como Duolingo. Para idiomas — Duolingo, Babbel o Pimsleur; para matemáticas y ciencias — Khanmigo."},{"q":"¿Cuánto cuesta Duolingo Max?","a":"Duolingo Max cuesta aproximadamente $14.99/mes o $83.99/año. Super Duolingo (sin funciones Max de IA avanzada) cuesta $6.99/mes. El plan gratuito de Duolingo sigue siendo muy completo pero con anuncios."}]
},
"youlearn-vs-notebooklm": {
  "a": "YouLearn", "b": "NotebookLM",
  "choose_a": ["✅ Quieres aprender de videos de YouTube haciendo preguntas sobre el contenido — YouLearn conecta directamente con YouTube","✅ Subes PDFs o documentos y tienes conversaciones de aprendizaje con IA que te explica, resume y evalúa tu comprensión","✅ Eres estudiante que consume principalmente contenido en video y necesita extraer conocimiento de forma más activa","✅ Quieres una experiencia de aprendizaje interactiva con flashcards, quizzes y resúmenes generados automáticamente"],
  "choose_b": ["✅ Necesitas analizar múltiples documentos propios juntos con citas precisas de página y sección","✅ Quieres crear podcasts de audio conversacional a partir de tus materiales de estudio o investigación","✅ Trabajas en investigación académica o profesional donde la precisión de las fuentes es crítica","✅ Colaboras con colegas compartiendo notebooks con las mismas fuentes de documentos"],
  "faq": [{"q":"¿YouLearn o Recall para aprender de YouTube?","a":"YouLearn permite conversaciones profundas sobre videos de YouTube con preguntas y respuestas. Recall crea tarjetas de memoria automáticamente de videos y artículos para repaso espaciado. Para entender en profundidad — YouLearn; para memorizar a largo plazo — Recall."},{"q":"¿YouLearn es gratuito?","a":"YouLearn tiene un plan gratuito con acceso limitado. Los planes de pago empiezan desde $12/mes. NotebookLM de Google es gratuito con límites generosos."},{"q":"¿NotebookLM puede analizar videos de YouTube?","a":"Sí. NotebookLM acepta URLs de YouTube como fuentes — transcribe el video automáticamente y permite preguntas sobre el contenido. Sin embargo, YouLearn está más especializado en aprendizaje de video con funciones como quizzes y flashcards."},{"q":"¿YouLearn puede crear flashcards?","a":"Sí. YouLearn puede generar flashcards automáticamente a partir del contenido de videos o documentos cargados para estudio activo. NotebookLM no tiene esta función específica de flashcards — se centra más en preguntas y respuestas y Audio Overview."}]
},
"synthesis-vs-khanmigo": {
  "a": "Synthesis", "b": "Khanmigo",
  "choose_a": ["✅ Buscas aprendizaje matemático profundo para niños de 6 a 14 años a través de videojuegos y desafíos colaborativos","✅ Quieres que tu hijo desarrolle pensamiento matemático y resolución de problemas, no solo memorización de procedimientos","✅ Tu hijo se aburre con el aprendizaje tradicional — Synthesis usa gamificación intensa para motivar el aprendizaje matemático","✅ Buscas la plataforma de matemáticas IA más avanzada para niños, creada originalmente para estudiantes de SpaceX"],
  "choose_b": ["✅ Necesitas tutoría IA en múltiples materias: matemáticas, ciencias, historia, escritura — no solo matemáticas","✅ Tienes un estudiante de secundaria o preparatoria que necesita ayuda en el currículo académico completo","✅ Buscas un tutor socrático que guía sin dar respuestas directamente, fomentando el pensamiento crítico","✅ Quieres acceso a todo el contenido de Khan Academy con un tutor IA que lo complementa"],
  "faq": [{"q":"¿Qué es Synthesis?","a":"Synthesis es una plataforma de aprendizaje matemático para niños que nació en la escuela de SpaceX (Ad Astra School de Elon Musk). Usa videojuegos multijugador donde los niños resuelven problemas matemáticos y de pensamiento lógico en desafíos colaborativos. Fue considerada la mejor plataforma de matemáticas para niños en su lanzamiento."},{"q":"¿Synthesis es gratuito?","a":"Synthesis tiene un plan gratuito limitado para explorar. El plan completo cuesta $35/mes por familia. Khanmigo cuesta $9/mes o $44/año. Khan Academy (sin Khanmigo) es completamente gratuito."},{"q":"¿Para qué edades es Synthesis?","a":"Synthesis está diseñado para niños de 6 a 14 años (primaria y secundaria baja). Khanmigo cubre más rango de edad — desde primaria hasta preparatoria e incluso universitaria para algunas materias."},{"q":"¿Synthesis o Beast Academy para matemáticas avanzadas?","a":"Synthesis es mejor para aprendizaje a través del juego y pensamiento matemático. Beast Academy (de Art of Problem Solving) está orientado a matemáticas de competencia — más riguroso y desafiante para niños que quieren matemáticas olímpicas. Para motivación y hábito — Synthesis; para matemáticas avanzadas de competencia — Beast Academy."}]
},
"gamma-vs-beautiful-ai": {
  "a": "Gamma", "b": "Beautiful.ai",
  "choose_a": ["✅ Quieres generar una presentación completa desde una descripción de texto en menos de un minuto con IA","✅ Necesitas crear no solo slides sino también documentos web y páginas interactivas con la misma herramienta","✅ Publicas como enlace web, PDF o presentación interactiva directamente sin exportar a PowerPoint","✅ Priorizas la velocidad de creación sobre el control granular del diseño — Gamma es el más rápido del mercado"],
  "choose_b": ["✅ Quieres presentaciones con diseño automático que se mantiene visualmente consistente sin importar cuánto contenido añadas","✅ Necesitas templates más estructurados con diseño más controlado y uniforme para presentaciones corporativas","✅ Tu flujo de trabajo incluye colaboración en equipo con comentarios y revisiones en las presentaciones","✅ Prefieres que el sistema de diseño IA gestione el layout automáticamente mientras tú te enfocas en el contenido"],
  "faq": [{"q":"¿Gamma o Canva para presentaciones?","a":"Gamma es más rápido para generar presentaciones completas desde texto con IA. Canva tiene más templates y mayor control sobre diseño visual elemento por elemento. Para crear rápido con IA — Gamma; para diseño personalizado con muchos templates — Canva."},{"q":"¿Beautiful.ai es gratuito?","a":"Beautiful.ai tiene una prueba gratuita de 14 días. El plan de pago empieza desde $12/mes (Pro). Gamma tiene plan gratuito con 400 créditos y planes de pago desde $10/mes. Ambas ofrecen buenas opciones para equipos."},{"q":"¿Gamma puede exportar a PowerPoint?","a":"Sí. Gamma permite exportar a PDF y PowerPoint (.pptx). Esto facilita compartir con personas que usan PowerPoint sin acceso a Gamma. Beautiful.ai también exporta a PDF y PowerPoint."},{"q":"¿Beautiful.ai tiene IA para generar contenido?","a":"Beautiful.ai tiene IA para sugerir layouts y mantener el diseño consistente (su punto fuerte). También tiene algunas funciones de generación de contenido IA, aunque es más limitada que Gamma en generación completa de presentaciones desde texto."}]
},
"gamma-vs-pitch": {
  "a": "Gamma", "b": "Pitch",
  "choose_a": ["✅ Quieres generar una presentación completa desde texto con IA en minutos — Gamma es el líder en generación IA de presentaciones","✅ Necesitas crear documentos y páginas web además de presentaciones en la misma herramienta","✅ Presentas a audiencias diversas y necesitas versiones en diferentes formatos (web, PDF, slides) rápidamente","✅ Eres solopreneur o pequeña empresa que necesita presentaciones de calidad sin equipo de diseño"],
  "choose_b": ["✅ Tu equipo de startup necesita una herramienta colaborativa para crear y refinar pitch decks con feedback integrado","✅ Quieres templates específicamente diseñados para pitch decks de inversión y presentaciones de startup","✅ Necesitas colaboración en tiempo real con comentarios, versiones y roles de equipo en las presentaciones","✅ Buscas una herramienta donde el equipo fundador y los asesores puedan trabajar juntos en el mismo deck"],
  "faq": [{"q":"¿Pitch es solo para startups?","a":"Pitch comenzó enfocado en pitch decks para startups e inversores, pero ha evolucionado a una herramienta de presentaciones general. Sigue siendo especialmente popular en el ecosistema de startups por sus templates y su cultura de diseño. Cualquier equipo puede usarlo, pero brilla en contextos de startup."},{"q":"¿Pitch es gratuito?","a":"Pitch tiene plan gratuito con presentaciones ilimitadas y colaboradores. Los planes de equipo (desde $25/mes) añaden funciones avanzadas de colaboración, analíticas y personalización de marca. Gamma tiene plan gratuito; planes desde $10/mes."},{"q":"¿Gamma o Pitch para inversores?","a":"Depende de tu prioridad. Gamma es más rápido para crear el pitch inicial. Pitch tiene templates de pitch deck específicos para VC y funciones de colaboración para refinar el deck con tu equipo. Muchos founders crean el primer borrador en Gamma y lo refinan en Pitch."},{"q":"¿Pitch tiene IA para generar contenido?","a":"Pitch tiene funciones de IA para sugerir contenido y mejorar texto. Sin embargo, la generación completa de presentaciones desde texto es el punto fuerte de Gamma. Pitch prioriza la colaboración y el diseño; Gamma prioriza la velocidad de generación con IA."}]
},
}

COMPARISONS = [
    {'slug': 'chatgpt-vs-claude',                    'a': 'chatgpt',                'b': 'claude'},
    {'slug': 'gemini-vs-chatgpt',                    'a': 'gemini',                 'b': 'chatgpt'},
    {'slug': 'deepseek-vs-chatgpt',                  'a': 'deepseek',               'b': 'chatgpt'},
    {'slug': 'microsoft-copilot-vs-chatgpt',         'a': 'microsoft-copilot',      'b': 'chatgpt'},
    {'slug': 'meta-ai-vs-chatgpt',                   'a': 'meta-ai',                'b': 'chatgpt'},
    {'slug': 'grok-vs-chatgpt',                      'a': 'grok',                   'b': 'chatgpt'},
    {'slug': 'mistral-le-chat-vs-chatgpt',           'a': 'mistral-le-chat',        'b': 'chatgpt'},
    {'slug': 'character-ai-vs-chatgpt',              'a': 'character-ai',           'b': 'chatgpt'},
    {'slug': 'copilot-studio-vs-manus',              'a': 'copilot-studio',         'b': 'manus'},
    {'slug': 'n8n-vs-copilot-studio',                'a': 'n8n',                    'b': 'copilot-studio'},
    {'slug': 'make-vs-copilot-studio',               'a': 'make',                   'b': 'copilot-studio'},
    {'slug': 'lindy-vs-copilot-studio',              'a': 'lindy',                  'b': 'copilot-studio'},
    {'slug': 'relevance-ai-vs-copilot-studio',       'a': 'relevance-ai',           'b': 'copilot-studio'},
    {'slug': 'devin-vs-copilot-studio',              'a': 'devin',                  'b': 'copilot-studio'},
    {'slug': 'make-vs-n8n',                          'a': 'make',                   'b': 'n8n'},
    {'slug': 'cursor-vs-copilot',                    'a': 'cursor',                 'b': 'github-copilot'},
    {'slug': 'windsurf-vs-cursor',                   'a': 'windsurf',               'b': 'cursor'},
    {'slug': 'claude-code-vs-github-copilot',        'a': 'claude-code',            'b': 'github-copilot'},
    {'slug': 'replit-vs-github-copilot',             'a': 'replit',                 'b': 'github-copilot'},
    {'slug': 'bolt-new-vs-cursor',                   'a': 'bolt-new',               'b': 'cursor'},
    {'slug': 'v0-by-vercel-vs-cursor',               'a': 'v0-by-vercel',           'b': 'cursor'},
    {'slug': 'cline-vs-github-copilot',              'a': 'cline',                  'b': 'github-copilot'},
    {'slug': 'aider-vs-github-copilot',              'a': 'aider',                  'b': 'github-copilot'},
    {'slug': 'windsurf-vs-github-copilot',           'a': 'windsurf',               'b': 'github-copilot'},
    {'slug': 'deepl-vs-grammarly',                   'a': 'deepl',                  'b': 'grammarly'},
    {'slug': 'quillbot-vs-grammarly',                'a': 'quillbot',               'b': 'grammarly'},
    {'slug': 'jasper-vs-writesonic',                 'a': 'jasper',                 'b': 'writesonic'},
    {'slug': 'writesonic-vs-grammarly',              'a': 'writesonic',             'b': 'grammarly'},
    {'slug': 'hemingway-editor-vs-grammarly',        'a': 'hemingway-editor',       'b': 'grammarly'},
    {'slug': 'semrush-vs-copy-ai',                   'a': 'semrush',                'b': 'copy-ai'},
    {'slug': 'surferseo-vs-semrush',                 'a': 'surferseo',              'b': 'semrush'},
    {'slug': 'frase-vs-semrush',                     'a': 'frase',                  'b': 'semrush'},
    {'slug': 'clearscope-vs-surferseo',              'a': 'clearscope',             'b': 'surferseo'},
    {'slug': 'copy-ai-vs-jasper',                    'a': 'copy-ai',                'b': 'jasper'},
    {'slug': 'midjourney-vs-flux',                   'a': 'midjourney',             'b': 'flux'},
    {'slug': 'midjourney-vs-stable-diffusion',       'a': 'midjourney',             'b': 'stable-diffusion'},
    {'slug': 'ideogram-vs-midjourney',               'a': 'ideogram',               'b': 'midjourney'},
    {'slug': 'adobe-firefly-vs-midjourney',          'a': 'adobe-firefly',          'b': 'midjourney'},
    {'slug': 'recraft-ai-vs-midjourney',             'a': 'recraft-ai',             'b': 'midjourney'},
    {'slug': 'flux-vs-stable-diffusion',             'a': 'flux',                   'b': 'stable-diffusion'},
    {'slug': 'leonardo-ai-vs-midjourney',            'a': 'leonardo-ai',            'b': 'midjourney'},
    {'slug': 'kling-vs-runway',                      'a': 'kling-ai',               'b': 'runway'},
    {'slug': 'capcut-vs-kling-ai',                   'a': 'capcut',                 'b': 'kling-ai'},
    {'slug': 'runway-vs-capcut',                     'a': 'runway',                 'b': 'capcut'},
    {'slug': 'heygen-vs-synthesia',                  'a': 'heygen',                 'b': 'synthesia'},
    {'slug': 'pika-vs-kling-ai',                     'a': 'pika',                   'b': 'kling-ai'},
    {'slug': 'luma-ai-vs-runway',                    'a': 'luma-ai',                'b': 'runway'},
    {'slug': 'google-veo-3-vs-runway',               'a': 'google-veo-3',           'b': 'runway'},
    {'slug': 'canva-ai-vs-figma-ai',                 'a': 'canva-ai',               'b': 'figma-ai'},
    {'slug': 'figma-ai-vs-canva-ai',                 'a': 'figma-ai',               'b': 'canva-ai'},
    {'slug': 'framer-ai-vs-canva-ai',                'a': 'framer-ai',              'b': 'canva-ai'},
    {'slug': 'looka-vs-canva-ai',                    'a': 'looka',                  'b': 'canva-ai'},
    {'slug': 'uizard-vs-figma-ai',                   'a': 'uizard',                 'b': 'figma-ai'},
    {'slug': 'uxpilot-vs-figma-ai',                  'a': 'uxpilot',                'b': 'figma-ai'},
    {'slug': 'relume-vs-framer-ai',                  'a': 'relume',                 'b': 'framer-ai'},
    {'slug': 'whimsical-ai-vs-figma-ai',             'a': 'whimsical-ai',           'b': 'figma-ai'},
    {'slug': 'suno-vs-udio',                         'a': 'suno',                   'b': 'udio'},
    {'slug': 'speechify-vs-elevenlabs',              'a': 'speechify',              'b': 'elevenlabs'},
    {'slug': 'elevenlabs-vs-murf-ai',                'a': 'elevenlabs',             'b': 'murf-ai'},
    {'slug': 'elevenlabs-vs-playht',                 'a': 'elevenlabs',             'b': 'playht'},
    {'slug': 'descript-vs-adobe-podcast',            'a': 'descript',               'b': 'adobe-podcast'},
    {'slug': 'suno-vs-elevenlabs',                   'a': 'suno',                   'b': 'elevenlabs'},
    {'slug': 'notion-ai-vs-zapier-ai',               'a': 'notion-ai',              'b': 'zapier-ai'},
    {'slug': 'gamma-vs-notion-ai',                   'a': 'gamma',                  'b': 'notion-ai'},
    {'slug': 'otter-ai-vs-fireflies-ai',             'a': 'otter-ai',               'b': 'fireflies-ai'},
    {'slug': 'motion-vs-reclaim-ai',                 'a': 'motion',                 'b': 'reclaim-ai'},
    {'slug': 'zapier-ai-vs-make',                    'a': 'zapier-ai',              'b': 'make'},
    {'slug': 'perplexity-vs-notebooklm',             'a': 'perplexity',             'b': 'notebooklm'},
    {'slug': 'elicit-vs-consensus',                  'a': 'elicit',                 'b': 'consensus'},
    {'slug': 'consensus-vs-perplexity',              'a': 'consensus',              'b': 'perplexity'},
    {'slug': 'notebooklm-vs-humata',                 'a': 'notebooklm',             'b': 'humata'},
    {'slug': 'scite-vs-semantic-scholar',            'a': 'scite',                  'b': 'semantic-scholar'},
    {'slug': 'looker-studio-vs-tableau-ai',          'a': 'looker-studio',          'b': 'tableau-ai'},
    {'slug': 'julius-ai-vs-looker-studio',           'a': 'julius-ai',              'b': 'looker-studio'},
    {'slug': 'hex-vs-looker-studio',                 'a': 'hex',                    'b': 'looker-studio'},
    {'slug': 'rows-vs-hex',                          'a': 'rows',                   'b': 'hex'},
    {'slug': 'retool-ai-vs-looker-studio',           'a': 'retool-ai',              'b': 'looker-studio'},
    {'slug': 'bubble-vs-webflow',                    'a': 'bubble',                 'b': 'webflow'},
    {'slug': 'lovable-vs-bubble',                    'a': 'lovable',                'b': 'bubble'},
    {'slug': 'flutterflow-vs-bubble',                'a': 'flutterflow',            'b': 'bubble'},
    {'slug': 'glide-vs-bubble',                      'a': 'glide',                  'b': 'bubble'},
    {'slug': 'softr-vs-bubble',                      'a': 'softr',                  'b': 'bubble'},
    {'slug': 'webflow-vs-framer-ai',                 'a': 'webflow',                'b': 'framer-ai'},
    {'slug': 'photomath-vs-duolingo-max',            'a': 'photomath',              'b': 'duolingo-max'},
    {'slug': 'khanmigo-vs-photomath',                'a': 'khanmigo',               'b': 'photomath'},
    {'slug': 'duolingo-max-vs-khanmigo',             'a': 'duolingo-max',           'b': 'khanmigo'},
    {'slug': 'youlearn-vs-notebooklm',               'a': 'youlearn',               'b': 'notebooklm'},
    {'slug': 'synthesis-vs-khanmigo',                'a': 'synthesis',              'b': 'khanmigo'},
    {'slug': 'gamma-vs-beautiful-ai',                'a': 'gamma',                  'b': 'beautiful-ai'},
    {'slug': 'gamma-vs-pitch',                       'a': 'gamma',                  'b': 'pitch'},
    {'slug': 'gamma-vs-prezi',                       'a': 'gamma',                  'b': 'prezi'},
    {'slug': 'beautiful-ai-vs-pitch',                'a': 'beautiful-ai',           'b': 'pitch'},
    {'slug': 'slidesgo-vs-gamma',                    'a': 'slidesgo',               'b': 'gamma'},
    {'slug': 'tradingview-vs-fiscal-ai',             'a': 'tradingview',            'b': 'finchat'},
    {'slug': 'koyfin-vs-tradingview',                'a': 'koyfin',                 'b': 'tradingview'},
    {'slug': 'fiscal-ai-vs-koyfin',                  'a': 'finchat',                'b': 'koyfin'},
    {'slug': 'tickeron-vs-tradingview',              'a': 'tickeron',               'b': 'tradingview'},
    {'slug': 'uptrends-ai-vs-koyfin',               'a': 'uptrends-ai',            'b': 'koyfin'},
    {'slug': 'amazon-q-developer-vs-github-copilot','a': 'amazon-q-developer',     'b': 'github-copilot'},
    {'slug': 'continue-dev-vs-github-copilot',      'a': 'continue-dev',           'b': 'github-copilot'},
    {'slug': 'opencode-vs-claude-code',             'a': 'opencode',               'b': 'claude-code'},
    {'slug': 'zed-vs-cursor',                       'a': 'zed',                    'b': 'cursor'},
    {'slug': 'comfyui-vs-stable-diffusion',         'a': 'comfyui',                'b': 'stable-diffusion'},
    {'slug': 'krea-ai-vs-midjourney',               'a': 'krea-ai',                'b': 'midjourney'},
    {'slug': 'nano-banana-vs-leonardo-ai',          'a': 'nano-banana',            'b': 'leonardo-ai'},
    {'slug': 'chatgpt-images-vs-adobe-firefly',     'a': 'chatgpt-images',         'b': 'adobe-firefly'},
    {'slug': 'claude-design-vs-figma-ai',           'a': 'claude-design',          'b': 'figma-ai'},
    {'slug': 'google-stitch-vs-figma-ai',           'a': 'google-stitch',          'b': 'figma-ai'},
    {'slug': 'recraft-vs-canva-ai',                 'a': 'recraft',                'b': 'canva-ai'},
    {'slug': 'remove-bg-vs-canva-ai',               'a': 'remove-bg',              'b': 'canva-ai'},
    {'slug': 'seedance-vs-runway',                  'a': 'seedance-2-0',           'b': 'runway'},
    {'slug': 'whisper-vs-otter-ai',                 'a': 'whisper',                'b': 'otter-ai'},
    {'slug': 'adcreative-ai-vs-canva-ai',           'a': 'adcreative-ai',          'b': 'canva-ai'},
    {'slug': 'akkio-vs-julius-ai',                  'a': 'akkio',                  'b': 'julius-ai'},
    {'slug': 'autogpt-vs-manus',                    'a': 'autogpt',                'b': 'manus'},
    {'slug': 'coursera-coach-vs-khanmigo',          'a': 'coursera-coach',         'b': 'khanmigo'},
    {'slug': 'socratic-vs-khanmigo',                'a': 'socratic-by-google',     'b': 'khanmigo'},
]

# ── Build tool_slug → {choose_if, faq} ──────────────────────────────────────
tool_data = {}
for comp in COMPARISONS:
    slug_a = comp['a']
    slug_b = comp['b']
    key    = comp['slug']
    if key not in DATA_ES:
        continue
    d = DATA_ES[key]
    if slug_a not in tool_data:
        tool_data[slug_a] = {'choose_if': d['choose_a'], 'faq': d['faq']}
    if slug_b not in tool_data:
        tool_data[slug_b] = {'choose_if': d['choose_b'], 'faq': d['faq']}

# ── Generate SQL for tools table ─────────────────────────────────────────────
lines = []
lines.append("-- Spanish choose_if + faq UPDATE — generated by gen_tool_choose_faq_es_b3.py (batch 3/4)")
lines.append("BEGIN;")
for i, (tool_slug, td) in enumerate(sorted(tool_data.items()), start=1):
    ci_json = json.dumps(td['choose_if'], ensure_ascii=False)
    fq_json = json.dumps(td['faq'],       ensure_ascii=False)
    tag_ci  = f't{i}ci'
    tag_fq  = f't{i}fq'
    lines.append(
        f"UPDATE tools SET"
        f" choose_if = ${tag_ci}${ci_json}${tag_ci}$::JSONB,"
        f" faq = ${tag_fq}${fq_json}${tag_fq}$::JSONB"
        f" WHERE slug = '{tool_slug}' AND lang = 'es';"
    )
lines.append("COMMIT;")
sql = "\n".join(lines)
out_path = __file__.replace('.py', '.sql')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(sql)
print(f"-- Tools SQL written to {out_path}", file=sys.stderr)

# ── Generate SQL for comparisons table ───────────────────────────────────────
comp_lines = []
comp_lines.append("-- Spanish choose_a + choose_b + faq INSERT for comparisons table (batch 3/4)")
comp_lines.append("BEGIN;")
for i, comp in enumerate(COMPARISONS, start=1):
    key = comp['slug']
    if key not in DATA_ES:
        continue
    d = DATA_ES[key]
    ca_json  = json.dumps(d['choose_a'], ensure_ascii=False)
    cb_json  = json.dumps(d['choose_b'], ensure_ascii=False)
    faq_json = json.dumps(d['faq'],      ensure_ascii=False)
    tag_a = f'c{i}a'; tag_b = f'c{i}b'; tag_f = f'c{i}f'
    comp_lines.append(
        f"INSERT INTO comparisons "
        f"(slug,lang,tool_a,tool_b,tool_a_slug,tool_b_slug,tool_a_url,tool_b_url,"
        f"title,meta_desc,intro,table_data,best_a,best_b,verdict_a,verdict_b,choose_a,choose_b,faq)"
        f" SELECT slug,'es',tool_a,tool_b,tool_a_slug,tool_b_slug,tool_a_url,tool_b_url,"
        f"title,meta_desc,intro,table_data,best_a,best_b,verdict_a,verdict_b,"
        f"${tag_a}${ca_json}${tag_a}$::JSONB,"
        f"${tag_b}${cb_json}${tag_b}$::JSONB,"
        f"${tag_f}${faq_json}${tag_f}$::JSONB"
        f" FROM comparisons WHERE slug='{key}' AND lang='en'"
        f" ON CONFLICT (slug,lang) DO UPDATE SET"
        f" choose_a=EXCLUDED.choose_a, choose_b=EXCLUDED.choose_b, faq=EXCLUDED.faq;"
    )
comp_lines.append("COMMIT;")
comp_sql = "\n".join(comp_lines)
comp_out = __file__.replace('.py', '_comparisons.sql')
with open(comp_out, 'w', encoding='utf-8') as f:
    f.write(comp_sql)
print(f"-- Comparisons SQL written to {comp_out}", file=sys.stderr)
print(f"Batch 3/4 done: {len(DATA_ES)} comparisons, {len(tool_data)} tools")
