#!/usr/bin/env python3
"""Generate SQL for Spanish (lang=es) translations of choose_if and faq. Batch 2/4 (comparisons 31-60)."""

import json, sys

DATA_ES = {
"surferseo-vs-semrush": {
  "a": "SurferSEO", "b": "SEMrush",
  "choose_a": ["✅ Tu objetivo principal es optimizar el contenido: Surfer muestra en tiempo real cómo mejorar cada artículo frente a los competidores del top 10","✅ Quieres un flujo de trabajo integrado: investigación de palabras clave + editor de contenido IA en una sola herramienta","✅ Necesitas un Content Score claro para saber cuándo el artículo está listo para publicar","✅ Eres blogger, freelancer o agencia SEO enfocada en producción de contenido optimizado"],
  "choose_b": ["✅ Necesitas una suite SEO completa: auditoría técnica, backlinks, seguimiento de rankings, análisis de competidores — todo en un solo lugar","✅ Tu equipo de marketing necesita datos de palabras clave, volúmenes de búsqueda y dificultad para planificar la estrategia","✅ Gestionas campañas PPC además de SEO orgánico — SEMrush tiene herramientas de publicidad integradas","✅ Necesitas monitorear la presencia online completa de una marca o dominio"],
  "faq": [{"q":"¿SurferSEO o SEMrush para contenido?","a":"SurferSEO es mejor para la optimización de contenido paso a paso — te dice exactamente qué palabras clave incluir y cuántas veces mientras escribes. SEMrush es mejor para la estrategia global: encontrar temas, analizar competidores y auditar el sitio. Muchos equipos SEO usan ambas herramientas juntas."},{"q":"¿SurferSEO vale la pena?","a":"SurferSEO es valioso si produces contenido SEO regularmente. El Content Score y las sugerencias de términos semánticamente relacionados aceleran significativamente el proceso de optimización. Para creadores de contenido activos — el ROI suele ser positivo. Para publicación ocasional, puede ser caro."},{"q":"¿Cuánto cuesta SurferSEO?","a":"SurferSEO empieza desde $99/mes (Essential), con planes más avanzados para agencias. SEMrush empieza desde $139.95/mes (Pro). Ambos tienen pruebas gratuitas."},{"q":"¿Puede SurferSEO reemplazar a SEMrush?","a":"No completamente. SurferSEO es excelente para optimización on-page y creación de contenido. SEMrush cubre análisis de backlinks, auditorías técnicas y seguimiento de rankings con mayor profundidad. Para una estrategia SEO completa, necesitas capacidades de ambas."}]
},
"frase-vs-semrush": {
  "a": "Frase", "b": "SEMrush",
  "choose_a": ["✅ Necesitas crear briefings de contenido SEO completos automáticamente a partir de una palabra clave","✅ Quieres investigar qué respuestas dan los competidores del top 10 y superar su contenido","✅ Tu flujo de trabajo es: investigar → redactar → optimizar en una sola herramienta con IA","✅ Eres escritor freelance o agencia de contenido que necesita acelerar la investigación de artículos"],
  "choose_b": ["✅ Necesitas la suite SEO más completa: palabras clave, backlinks, auditorías técnicas, PPC y análisis competitivo","✅ Tu equipo de marketing necesita datos de mercado amplios, no solo ayuda para escribir artículos","✅ Gestionas el SEO de múltiples dominios o clientes con seguimiento de posiciones detallado","✅ Necesitas informes SEO completos para presentar a clientes o dirección"],
  "faq": [{"q":"¿Qué es Frase y para qué sirve?","a":"Frase es una herramienta de IA para creación de contenido SEO. Analiza el contenido del top 10 para una palabra clave, genera briefings automáticos y ayuda a escribir y optimizar el artículo. Es más específica que SEMrush: se centra en crear contenido que rankea, no en análisis técnico SEO."},{"q":"¿Frase vs SurferSEO: cuál es mejor?","a":"Ambas son herramientas de optimización de contenido. Frase destaca en la investigación de SERP y generación de briefings; SurferSEO es más fuerte en la puntuación de contenido en tiempo real. Muchos profesionales del contenido prefieren Frase por su capacidad de resumir lo que cubre la competencia."},{"q":"¿Frase es gratuito?","a":"Frase ofrece una prueba gratuita de 5 días. Los planes de pago empiezan desde $45/mes (Solo). SEMrush tiene una prueba gratuita limitada; los planes de pago desde $139.95/mes."},{"q":"¿Puede Frase reemplazar a SEMrush?","a":"No. Frase es una herramienta de contenido; SEMrush es una suite SEO completa. Frase no tiene análisis de backlinks, auditoría técnica o seguimiento de rankings. Son complementarias: SEMrush para encontrar oportunidades, Frase para ejecutar el contenido."}]
},
"clearscope-vs-surferseo": {
  "a": "Clearscope", "b": "SurferSEO",
  "choose_a": ["✅ Tu equipo incluye escritores no técnicos que necesitan orientación de contenido simple sin curva de aprendizaje","✅ Quieres la integración más fluida con Google Docs y WordPress para editar directamente donde escribes","✅ Priorizas la calidad de los informes de términos relacionados — Clearscope usa datos de Google directamente","✅ Necesitas una herramienta de optimización de contenido con interfaz más limpia y menos abrumadora"],
  "choose_b": ["✅ Quieres un editor de contenido integrado dentro de la herramienta para escribir y optimizar en el mismo lugar","✅ Necesitas análisis de SERP más detallado: estructura de páginas competidoras, recuento de palabras, backlinks de la competencia","✅ Buscas un flujo completo: investigación de palabras clave + planificación de contenido + optimización en una plataforma","✅ El precio es importante: SurferSEO ofrece más funciones por un precio similar"],
  "faq": [{"q":"¿Clearscope o SurferSEO para SEO de contenido?","a":"Clearscope es preferido por equipos con escritores no técnicos — su interfaz es más simple y las sugerencias menos abrumadoras. SurferSEO ofrece más funciones y análisis más profundo del SERP. Agencias y equipos técnicos suelen preferir Surfer; equipos de contenido más grandes con muchos escritores prefieren Clearscope."},{"q":"¿Cuánto cuesta Clearscope?","a":"Clearscope empieza en $199/mes (Essentials). SurferSEO desde $99/mes. Clearscope es significativamente más caro, pero muchos equipos valoran su simplicidad y calidad de datos para equipos más grandes."},{"q":"¿Clearscope mejora el ranking?","a":"Clearscope ayuda a crear contenido más completo y relevante semánticamente, lo que generalmente mejora el ranking. Sin embargo, el SEO depende de muchos factores: backlinks, autoridad de dominio, velocidad del sitio. Clearscope optimiza el factor contenido, no el SEO técnico."},{"q":"¿Qué es mejor para principiantes, Clearscope o SurferSEO?","a":"Para equipos con escritores sin experiencia en SEO técnico — Clearscope es más accesible. Para marketers SEO que quieren más datos — SurferSEO. Ambas tienen curvas de aprendizaje razonables."}]
},
"copy-ai-vs-jasper": {
  "a": "Copy.ai", "b": "Jasper",
  "choose_a": ["✅ Necesitas generación rápida de copias cortas: anuncios, emails, descripciones de productos, títulos","✅ Buscas un plan gratuito generoso para empezar sin inversión inicial","✅ Eres solopreneur o pequeña empresa que necesita copywriting de IA a bajo costo","✅ Quieres plantillas de copywriting probadas (AIDA, PAS, etc.) listas para usar sin configuración"],
  "choose_b": ["✅ Tu equipo de marketing produce contenido de formato largo: blogs, whitepapers, contenido de marca a escala","✅ Necesitas configurar la voz de marca (Brand Voice) para que todo el contenido suene consistente","✅ Trabajas en equipo y necesitas flujos de trabajo colaborativos y gestión de proyectos de contenido","✅ Requieres integración con SEO (Surfer SEO integrado) para optimizar el contenido mientras lo creas"],
  "faq": [{"q":"¿Copy.ai o Jasper para marketing?","a":"Copy.ai es mejor para copias cortas y equipos pequeños con presupuesto ajustado. Jasper es más potente para equipos de contenido que producen a escala con brand voice configurado. Para startups y freelancers — Copy.ai; para equipos de marketing maduros — Jasper."},{"q":"¿Copy.ai es gratuito?","a":"Copy.ai tiene un plan gratuito con créditos mensuales. Los planes de pago empiezan desde $49/mes. Jasper no tiene plan gratuito permanente; los planes empiezan desde $49/mes (Creator) con prueba gratuita de 7 días."},{"q":"¿Jasper es mejor que ChatGPT para marketing?","a":"Jasper está especialmente diseñado para marketing — tiene plantillas de marketing, brand voice y flujos de trabajo integrados. ChatGPT es más versátil pero requiere más configuración para marketing. Para equipos de marketing dedicados, Jasper ahorra tiempo; para uso general, ChatGPT ofrece más flexibilidad."},{"q":"¿Copy.ai puede escribir artículos de blog completos?","a":"Sí. Copy.ai puede generar artículos de blog completos, aunque su punto fuerte son los fragmentos cortos de copia. Para contenido largo de calidad, Jasper o Claude ofrecen resultados más consistentes en artículos extensos."}]
},
"midjourney-vs-flux": {
  "a": "Midjourney", "b": "Flux",
  "choose_a": ["✅ Priorizas la calidad artística: Midjourney V7 sigue siendo referencia en arte fotorrealista y estilizado de alta calidad","✅ Quieres una comunidad establecida con millones de ejemplos, estilos y prompts disponibles en Discord","✅ Necesitas resultados consistentes y predecibles con una curva de aprendizaje probada","✅ Creas arte conceptual, ilustraciones o imágenes para marketing donde la calidad artística es prioritaria"],
  "choose_b": ["✅ Quieres un modelo open-weights que puedes ejecutar localmente o vía API sin depender de un servicio cloud","✅ FLUX.1 [dev] y [schnell] ofrecen excelente calidad con mayor control técnico sobre el proceso de generación","✅ No quieres usar Discord — Flux está disponible vía API, Replicate, ComfyUI y otras interfaces","✅ Buscas mayor adherencia al prompt y control sobre los detalles de la imagen generada"],
  "faq": [{"q":"¿Flux es mejor que Midjourney?","a":"Depende del caso. Midjourney V7 sigue siendo superior en calidad artística consistente y fotorrealismo extremo. FLUX.1 Pro compite directamente y tiene ventajas en adherencia al prompt y control técnico. Para arte general — Midjourney; para control y uso via API — Flux."},{"q":"¿Qué es FLUX.1?","a":"FLUX.1 es la familia de modelos de generación de imágenes de Black Forest Labs (fundadores de Stable Diffusion). Incluye variantes: [schnell] (rápido, libre), [dev] (calidad alta, open-weights) y [pro] (la mejor calidad, API). Es el principal competidor open-source de Midjourney en 2025."},{"q":"¿Midjourney es gratuito?","a":"Midjourney eliminó su plan gratuito. Los planes de pago empiezan desde $10/mes (Basic). Flux tiene versiones open-source gratuitas ([schnell]) y una versión Pro vía API de pago. Replicate y otras plataformas ofrecen acceso por uso."},{"q":"¿Cómo accedo a FLUX sin Discord?","a":"Flux está disponible en Replicate (pago por uso), fal.ai, API de Black Forest Labs, ComfyUI (local) y muchas plataformas de imágenes IA. Midjourney requiere Discord o su web app."}]
},
"midjourney-vs-stable-diffusion": {
  "a": "Midjourney", "b": "Stable Diffusion",
  "choose_a": ["✅ Quieres la mejor calidad artística con el mínimo esfuerzo — sin configuración técnica, solo prompts","✅ Necesitas resultados consistentes y de alto nivel sin fine-tuning ni ajuste de parámetros","✅ Creas imágenes para uso profesional o comercial donde la calidad predecible es prioritaria","✅ No quieres gestionar hardware, modelos o extensiones — Midjourney es un servicio gestionado"],
  "choose_b": ["✅ Quieres control total: ejecutar el modelo localmente, ajustar parámetros, usar LoRAs y modelos personalizados","✅ Necesitas usar imágenes sin restricciones de contenido — Stable Diffusion ejecutado localmente no tiene filtros","✅ Buscas el ecosistema más grande: miles de modelos en CivitAI, extensiones AUTOMATIC1111, ComfyUI","✅ No quieres pagar suscripción mensual — Stable Diffusion es gratuito si tienes GPU adecuada"],
  "faq": [{"q":"¿Midjourney o Stable Diffusion para principiantes?","a":"Midjourney es mucho más fácil para principiantes — escribe un prompt y obtienes resultados de calidad inmediatamente. Stable Diffusion requiere configuración técnica: instalar software, descargar modelos, ajustar parámetros. Para resultados rápidos sin experiencia técnica — Midjourney."},{"q":"¿Stable Diffusion es gratuito?","a":"Sí. Stable Diffusion es open-source y gratuito. Necesitas hardware (GPU Nvidia 6GB+ VRAM para ejecución local) o usar servicios cloud que cobran por generación. Midjourney requiere suscripción desde $10/mes."},{"q":"¿Es legal usar imágenes de Midjourney comercialmente?","a":"Con planes de pago, Midjourney otorga derechos comerciales sobre las imágenes generadas. Las imágenes del plan gratuito (cuando existía) tenían restricciones. Lee los términos actuales en midjourney.com. Stable Diffusion con modelos open-source generalmente permite uso comercial según la licencia de cada modelo."},{"q":"¿Qué es AUTOMATIC1111?","a":"AUTOMATIC1111 es la interfaz web más popular para Stable Diffusion. Permite usar el modelo localmente con una interfaz gráfica, soporta miles de modelos y extensiones de CivitAI. Es gratuito pero requiere instalación técnica y una GPU compatible."}]
},
"ideogram-vs-midjourney": {
  "a": "Ideogram", "b": "Midjourney",
  "choose_a": ["✅ Necesitas generar texto dentro de imágenes con precisión: logos, carteles, tipografía, señalética — Ideogram es el líder en texto-en-imagen","✅ Quieres un plan gratuito generoso para empezar sin pagar — Ideogram tiene créditos diarios gratuitos","✅ Creas materiales de marketing, thumbnails de YouTube o posts de redes sociales que requieren texto integrado en el diseño","✅ Necesitas diseños con paletas de colores específicas y estilos controlados para identidad de marca"],
  "choose_b": ["✅ Priorizas la calidad artística máxima en fotorrealismo, ilustración y arte conceptual","✅ Necesitas una variedad más amplia de estilos artísticos y mayor consistencia en resultados complejos","✅ Tienes proyectos creativos sin texto en imagen donde la calidad visual general importa más","✅ Quieres acceso a la mayor comunidad de artistas IA con millones de prompts de referencia"],
  "faq": [{"q":"¿Ideogram es mejor que Midjourney para texto en imágenes?","a":"Sí, claramente. Ideogram es el modelo líder para renderizar texto dentro de imágenes con precisión. Midjourney históricamente ha tenido problemas con texto — letras incorrectas, deformadas. Ideogram 3.0 genera texto tipográfico muy fiel al prompt. Para cualquier imagen con texto — Ideogram."},{"q":"¿Ideogram es gratuito?","a":"Sí. Ideogram tiene un plan gratuito con 10 generaciones lentas por día (o 25 prioritarias/semana). Los planes de pago (Basic $8/mes, Plus $20/mes) ofrecen más generaciones y acceso prioritario."},{"q":"¿Qué puede hacer Ideogram que Midjourney no puede?","a":"Ideogram sobresale en: texto tipográfico en imágenes, colores específicos de marca, estilos de diseño gráfico (carteles, logos). Midjourney supera en arte fotorrealista de alta complejidad y estilos artísticos únicos."},{"q":"¿Puede Ideogram crear logos profesionales?","a":"Ideogram puede generar conceptos de logos con texto integrado de forma precisa, algo que otros modelos hacen mal. Sin embargo, los logos de IA no son vectoriales — necesitas un diseñador o herramienta de vectorización para logos profesionales listos para imprimir."}]
},
"adobe-firefly-vs-midjourney": {
  "a": "Adobe Firefly", "b": "Midjourney",
  "choose_a": ["✅ Necesitas imágenes para uso comercial con licencia clara — Firefly está entrenado solo con imágenes con licencia de Adobe Stock","✅ Usas Photoshop, Illustrator o la suite Creative Cloud — Firefly está integrado nativamente en estos programas","✅ Necesitas Generative Fill en Photoshop para editar imágenes existentes de forma inteligente","✅ Trabajas en una empresa con departamento legal sensible a los derechos de autor de las IA"],
  "choose_b": ["✅ Priorizas la mayor calidad artística global: Midjourney V7 produce imágenes artísticas superiores en la mayoría de estilos","✅ No tienes suscripción a Adobe Creative Cloud y necesitas la mejor herramienta de generación independiente","✅ Creas arte conceptual, ilustraciones o imágenes artísticas donde la estética importa más que la licencia","✅ Quieres una comunidad activa y acceso a millones de prompts de referencia en Discord"],
  "faq": [{"q":"¿Adobe Firefly es seguro para uso comercial?","a":"Sí. Adobe diseñó Firefly específicamente para uso comercial — solo fue entrenado con contenido bajo licencia de Adobe Stock y contenido de dominio público. Esto lo hace el modelo más 'legalmente seguro' del mercado para uso empresarial."},{"q":"¿Adobe Firefly es gratuito?","a":"Adobe Firefly tiene un plan gratuito con 25 créditos mensuales. Las suscripciones de Creative Cloud incluyen créditos adicionales. Los planes independientes de Firefly empiezan desde $9.99/mes (100 créditos). Midjourney desde $10/mes."},{"q":"¿Midjourney o Firefly para diseño gráfico?","a":"Para diseño integrado en flujos de trabajo Adobe (Photoshop, Illustrator) — Firefly es más práctico. Para crear imágenes artísticas de referencia, conceptos e ilustraciones — Midjourney produce resultados más impresionantes. Muchos diseñadores usan ambas."},{"q":"¿Qué es Generative Fill de Adobe?","a":"Generative Fill es una función de Photoshop (powered by Firefly) que permite añadir, eliminar o reemplazar elementos en imágenes existentes usando IA. Seleccionas un área, escribes un prompt y Photoshop genera contenido que se integra naturalmente. Es una de las funciones de edición IA más potentes del mercado."}]
},
"recraft-ai-vs-midjourney": {
  "a": "Recraft AI", "b": "Midjourney",
  "choose_a": ["✅ Necesitas crear ilustraciones vectoriales, iconos y gráficos de producto — Recraft es líder en generación vectorial con IA","✅ Tu trabajo es diseño de marca: necesitas control de paleta de colores exacta y estilos consistentes en todos los activos","✅ Creas UI, mockups de apps o gráficos para sitios web que requieren formatos vectoriales escalables","✅ Quieres exportar SVG directamente desde la herramienta de IA sin vectorizar manualmente"],
  "choose_b": ["✅ Priorizas la mayor calidad artística en fotorrealismo e ilustraciones complejas no vectoriales","✅ Necesitas variedad de estilos artísticos únicos, arte conceptual cinematográfico o renders 3D foto-realistas","✅ Quieres acceso a la mayor comunidad de artistas IA con referencias y estilos de Midjourney","✅ Creas contenido artístico general donde el formato vectorial no es necesario"],
  "faq": [{"q":"¿Qué hace especial a Recraft AI?","a":"Recraft es el primer modelo de IA que genera imágenes vectoriales (SVG) de alta calidad — algo que ningún otro modelo principal hace bien. También tiene excelente control de estilos y paletas para diseño de marca. Ganó el primer puesto en Elo benchmark de Text-to-Image en 2024."},{"q":"¿Recraft AI es gratuito?","a":"Recraft tiene un plan gratuito con 50 generaciones al mes. Los planes de pago empiezan desde $12/mes. Midjourney desde $10/mes pero sin plan gratuito."},{"q":"¿Recraft puede crear logos?","a":"Sí. Recraft es una de las mejores opciones para generar conceptos de logos en formato vectorial SVG. Puedes configurar la paleta de colores exacta y el estilo. Aunque para logos finales profesionales siempre se recomienda refinamiento por un diseñador humano."},{"q":"¿Recraft vs Midjourney para diseñadores?","a":"Son herramientas para propósitos diferentes. Recraft es para diseñadores que necesitan gráficos de marca consistentes, vectoriales y con control de estilo. Midjourney es para arte creativo de alta calidad sin restricciones de formato. Muchos diseñadores usan Recraft para activos de diseño y Midjourney para inspiración artística."}]
},
"flux-vs-stable-diffusion": {
  "a": "Flux", "b": "Stable Diffusion",
  "choose_a": ["✅ Quieres la mejor calidad de imagen open-source disponible en 2025 — FLUX.1 Pro supera a SD en la mayoría de benchmarks","✅ Necesitas mayor adherencia al prompt: Flux entiende mejor las instrucciones complejas y las ejecuta con más precisión","✅ Buscas generación más rápida con mejor calidad por paso de inferencia que los modelos SD clásicos","✅ Usas ComfyUI o plataformas modernas como Replicate y fal.ai donde Flux está integrado"],
  "choose_b": ["✅ Quieres el ecosistema más maduro: miles de modelos en CivitAI, LoRAs especializados, Checkpoints para cualquier estilo","✅ Usas AUTOMATIC1111, la interfaz de usuario más establecida con la mayor variedad de extensiones y plugins","✅ Tienes modelos fine-tuned para un estilo muy específico (anime, realista, etc.) entrenados con SD1.5 o SDXL","✅ Necesitas documentación, tutoriales y soporte comunitario — SD tiene el ecosistema más grande por años de ventaja"],
  "faq": [{"q":"¿Flux es mejor que Stable Diffusion?","a":"En calidad de imagen, sí — FLUX.1 Pro y Dev superan a SDXL en adherencia al prompt y calidad general. Sin embargo, Stable Diffusion tiene un ecosistema mucho más maduro con miles de modelos fine-tuned y extensiones. Flux es mejor calidad; SD es más personalizable."},{"q":"¿Qué es FLUX.1?","a":"FLUX.1 es la familia de modelos de generación de imágenes de Black Forest Labs. Hay tres variantes: [schnell] (rápido y libre para uso personal), [dev] (open-weights para investigación) y [pro] (mejor calidad, vía API de pago). Creado por ex-investigadores de Stability AI."},{"q":"¿Puedo usar Flux localmente?","a":"Sí. FLUX.1 [schnell] y [dev] son open-weights y pueden ejecutarse localmente con ComfyUI o Forge (fork de AUTOMATIC1111). Necesitas al menos 12GB VRAM para calidad completa, aunque hay versiones quantizadas para 8GB."},{"q":"¿Stable Diffusion 3 es mejor que Flux?","a":"Stable Diffusion 3 fue una decepción al lanzarse en 2024 — peor calidad que lo esperado. SDXL sigue siendo el punto de referencia de SD más usado. FLUX.1 supera tanto a SD3 como a SDXL en calidad general según la mayoría de evaluaciones comparativas."}]
},
"leonardo-ai-vs-midjourney": {
  "a": "Leonardo AI", "b": "Midjourney",
  "choose_a": ["✅ Necesitas activos de videojuegos: personajes, entornos, texturas, concept art para game design — Leonardo está diseñado para esto","✅ Quieres un plan gratuito generoso con tokens diarios para explorar sin pagar suscripción","✅ Necesitas modelos fine-tuned para estilos específicos de juegos (fantasy, sci-fi, pixel art) disponibles en la plataforma","✅ Quieres generar imágenes de referencia para un proyecto de juego o ilustración con mayor control de estilo"],
  "choose_b": ["✅ Priorizas la calidad artística más alta para fotorrealismo, arte conceptual cinematográfico o ilustraciones de marketing","✅ Necesitas la mayor consistencia y calidad predecible para producción profesional de imágenes","✅ Creas imágenes para uso amplio (marketing, editorial, arte) donde el nicho de videojuegos no es relevante","✅ Quieres el respaldo de la mayor comunidad de artistas IA para referencias y estilos"],
  "faq": [{"q":"¿Leonardo AI es gratuito?","a":"Sí. Leonardo AI tiene un plan gratuito con 150 tokens diarios (cada imagen cuesta entre 1-8 tokens según el modelo y tamaño). Los planes de pago empiezan desde $12/mes (Apprentice). Midjourney no tiene plan gratuito; desde $10/mes."},{"q":"¿Es bueno Leonardo AI para videojuegos?","a":"Leonardo AI es una de las mejores opciones para game art. Tiene modelos especializados para concept art de juegos, generación de texturas, personajes y entornos en estilos de juegos. Muchos estudios indie y artistas de juegos lo usan como parte de su pipeline de producción."},{"q":"¿Leonardo AI o Midjourney para concept art?","a":"Para concept art de videojuegos — Leonardo. Para concept art general de alta calidad (películas, publicidad, arte) — Midjourney suele producir resultados más impresionantes. La especialización de Leonardo en game design es su mayor ventaja."},{"q":"¿Qué modelos tiene Leonardo AI?","a":"Leonardo tiene varios modelos propios: Leonardo Diffusion XL, Leonardo Lightning XL (rápido), Kino XL (cinematográfico), Leonardo Phoenix y más. También soporta modelos de Stable Diffusion con fine-tuning. Puedes entrenar modelos personalizados con tus propias imágenes."}]
},
"kling-vs-runway": {
  "a": "Kling AI", "b": "Runway",
  "choose_a": ["✅ Necesitas generar videos de hasta 3 minutos con física de movimiento muy realista a un precio más competitivo","✅ Quieres la mejor relación calidad-precio en generación de video IA — Kling 2.0 compite directamente con Sora y Veo","✅ Necesitas texto-a-video con movimientos de cámara complejos y coherencia visual entre escenas","✅ Buscas una alternativa a Runway con mayor duración de video por defecto"],
  "choose_b": ["✅ Necesitas la suite de producción de video IA más completa con herramientas de edición: rotoscopia, eliminación de objetos, background swap","✅ Quieres una plataforma con años de track record en producción profesional usada por estudios de Hollywood","✅ Necesitas herramientas de video a video para transformar metraje existente con efectos de IA","✅ Tu flujo de trabajo requiere integración con herramientas de edición profesional (Premiere, Resolve)"],
  "faq": [{"q":"¿Kling AI o Runway para generación de video?","a":"Kling 2.0 es más competitivo en generación texto-a-video con videos más largos y menor costo. Runway es más completo como suite de producción: combina generación con edición avanzada. Para generación de clips — Kling; para producción integral — Runway."},{"q":"¿Cuánto cuesta Kling AI?","a":"Kling AI tiene un plan gratuito con créditos limitados. Los planes de pago empiezan desde $10/mes (Standard con 660 créditos). Runway empieza desde $12/mes (Standard) con 625 créditos al mes."},{"q":"¿Kling puede generar videos de 3 minutos?","a":"Sí. Kling 2.0 puede generar videos de hasta 3 minutos, significativamente más que los 4-16 segundos típicos de otros modelos. Runway Gen-3 Alpha genera hasta 10 segundos por clip. Para contenido más largo, Kling tiene ventaja."},{"q":"¿Es Kling AI mejor que Sora?","a":"Kling 2.0 es competitivo con Sora en calidad de movimiento y física. Sora tiene mayor acceso controlado (solo usuarios de ChatGPT Pro y Plus). Kling ofrece acceso más democrático con su tier gratuito. En benchmarks independientes, compiten en el top tier de generadores de video en 2025."}]
},
"capcut-vs-kling-ai": {
  "a": "CapCut", "b": "Kling AI",
  "choose_a": ["✅ Necesitas editar videos completos para redes sociales: cortar, añadir música, subtítulos automáticos, filtros y efectos en una sola app","✅ Quieres templates virales de TikTok e Instagram Reels listos para usar con un clic","✅ Eres creador de contenido mobile-first que edita videos directamente desde el teléfono","✅ Buscas la herramienta más completa de edición de video con IA para no profesionales, con plan gratuito muy completo"],
  "choose_b": ["✅ Tu objetivo es generar videos desde texto o imágenes con IA avanzada — no editar metraje existente","✅ Necesitas videos de mayor duración generados por IA con movimiento y física realistas","✅ Quieres capacidades de texto-a-video que van más allá de los efectos de edición de CapCut","✅ Produces contenido cinematográfico o artístico donde la generación IA es el punto central"],
  "faq": [{"q":"¿CapCut o Kling para TikTok?","a":"Para editar videos de TikTok con templates, música, subtítulos y efectos — CapCut es la herramienta estándar del sector, usada por la mayoría de creadores de TikTok. Kling es para generar clips de video IA que luego podrías editar en CapCut. Son complementarios, no competidores directos."},{"q":"¿CapCut es gratuito?","a":"CapCut tiene un plan gratuito muy completo — la mayoría de funciones básicas y muchas IA son gratuitas. Algunas funciones premium requieren CapCut Pro ($9.99/mes). Kling tiene plan gratuito con créditos limitados; planes desde $10/mes."},{"q":"¿Puede CapCut generar video desde texto?","a":"CapCut tiene algunas funciones de IA generativa, pero son limitadas comparadas con Kling o Runway. CapCut se centra en edición; Kling en generación. Para texto-a-video de calidad, Kling es significativamente más potente."},{"q":"¿CapCut es de TikTok/ByteDance?","a":"Sí. CapCut es propiedad de ByteDance, la misma empresa de TikTok. En algunos países ha habido discusiones regulatorias relacionadas. Para usuarios en EE.UU., esto es un factor a considerar en términos de privacidad de datos."}]
},
"runway-vs-capcut": {
  "a": "Runway", "b": "CapCut",
  "choose_a": ["✅ Necesitas producción de video profesional con IA: generación texto-a-video, rotoscopia automática, eliminación de fondos con movimiento","✅ Trabajas en proyectos creativos de alto nivel: cortometrajes, videos de marca, producción cinematográfica indie","✅ Quieres las herramientas de edición de video IA más avanzadas usadas por profesionales de Hollywood","✅ Necesitas video-a-video con transformación de estilo, motion brush y herramientas de control de cámara avanzadas"],
  "choose_b": ["✅ Eres creador de contenido para redes sociales que necesita editar videos rápidamente con templates virales","✅ Editas desde el móvil y necesitas la mejor experiencia mobile-first para TikTok, Reels e Instagram","✅ Buscas subtítulos automáticos, eliminación de fondo simple y efectos estéticos sin configuración técnica","✅ Tu presupuesto es limitado — CapCut ofrece más por menos para creación de contenido regular"],
  "faq": [{"q":"¿Runway o CapCut para videos profesionales?","a":"Runway para producción profesional y proyectos creativos ambiciosos con IA. CapCut para edición rápida de contenido de redes sociales. Runway tiene herramientas que CapCut no tiene (generación de video IA, rotoscopia, motion brush); CapCut es más accesible y económico para creación de contenido regular."},{"q":"¿Cuánto cuesta Runway?","a":"Runway tiene un plan gratuito con 125 créditos (suficiente para explorar). Los planes de pago empiezan desde $12/mes (Standard, 625 créditos). Para producción seria, el plan Pro ($28/mes) ofrece 2.250 créditos. CapCut es mayormente gratuito."},{"q":"¿Qué es Gen-3 Alpha de Runway?","a":"Gen-3 Alpha es el modelo de generación de video de Runway, que genera clips de hasta 10 segundos desde texto o imágenes. Compite con Sora, Kling y Veo en calidad cinematográfica. Es el modelo más avanzado de Runway disponible para usuarios."},{"q":"¿Runway tiene app móvil?","a":"Runway tiene app móvil (iOS y Android) pero es más limitada que la versión web. La experiencia completa, con todas las herramientas de IA avanzadas, está en el navegador. CapCut está diseñado desde cero para mobile."}]
},
"heygen-vs-synthesia": {
  "a": "HeyGen", "b": "Synthesia",
  "choose_a": ["✅ Quieres crear un avatar IA personalizado que se parezca a ti con clonación de voz en minutos","✅ Necesitas videos personalizados a escala: cada video con nombre del destinatario, datos personalizados — para ventas o marketing","✅ Produces videos de marketing, testimonios o presentaciones de ventas con avatar propio","✅ Necesitas doblaje de video existente en múltiples idiomas con sincronización de labios automática"],
  "choose_b": ["✅ Produces contenido de formación corporativa, eLearning y capacitación interna a escala","✅ Necesitas una plataforma con más de 230 avatares pre-construidos con diversidad de género, edad y etnia","✅ Tu organización necesita integración con LMS (sistemas de gestión de aprendizaje) y workflows corporativos","✅ Requieres una plataforma con mayor énfasis en cumplimiento corporativo y GDPR"],
  "faq": [{"q":"¿HeyGen o Synthesia para videos de formación?","a":"Synthesia está más orientado a formación corporativa y eLearning — tiene más integraciones con LMS y flujos de trabajo de L&D. HeyGen es mejor para videos de marketing personalizados y clonación de voz/avatar. Para formación interna a escala — Synthesia; para marketing con avatar propio — HeyGen."},{"q":"¿Cuánto cuesta HeyGen?","a":"HeyGen tiene un plan gratuito con 1 crédito de video (aprox. 1 minuto). Los planes de pago empiezan desde $29/mes (Creator). Synthesia empieza desde $29/mes (Starter) con 10 minutos de video al mes."},{"q":"¿Puede HeyGen clonar mi voz?","a":"Sí. HeyGen ofrece clonación de voz — grabas unos minutos de audio y el sistema crea una voz IA que suena como tú. También puedes crear un avatar de video que sincronice con tu voz clonada. Es una de sus funciones más populares."},{"q":"¿Son legales los avatares de IA?","a":"HeyGen y Synthesia requieren consentimiento explícito para crear avatares de personas reales. Las plataformas tienen políticas de uso aceptable que prohíben la creación de deepfakes no autorizados. Usar avatares con consentimiento para marketing propio o formación corporativa es completamente legal."}]
},
"pika-vs-kling-ai": {
  "a": "Pika", "b": "Kling AI",
  "choose_a": ["✅ Quieres efectos creativos únicos: transformar objetos, añadir efectos especiales sobre videos existentes (Pika Effects)","✅ Necesitas una herramienta de generación de video con interfaz intuitiva y efectos específicos para redes sociales","✅ Creas contenido creativo y experimental donde los efectos visuales únicos son prioritarios","✅ Quieres generar videos cortos animados de imágenes estáticas con movimiento inteligente"],
  "choose_b": ["✅ Necesitas videos de mayor duración (hasta 3 minutos) con movimiento y física más realistas","✅ Quieres la mejor calidad en generación texto-a-video de formato largo cinematográfico","✅ Necesitas resultados más consistentes y predecibles para producción de contenido a escala","✅ Buscas la mejor relación calidad-precio en generación de video IA de larga duración"],
  "faq": [{"q":"¿Pika o Kling para videos de redes sociales?","a":"Pika es más fuerte en efectos creativos y transformaciones de video — ideal para contenido viral con efectos únicos. Kling es mejor para videos generados de mayor duración y calidad cinematográfica. Para efectos especiales y clips cortos creativos — Pika; para video generado de mayor calidad — Kling."},{"q":"¿Pika es gratuito?","a":"Pika tiene un plan gratuito con créditos limitados. Los planes de pago empiezan desde $8/mes (Basic). Kling tiene plan gratuito y planes de pago desde $10/mes."},{"q":"¿Qué son los Pika Effects?","a":"Pika Effects son transformaciones creativas especiales: Pikaffects permite añadir efectos como 'explotar', 'deflate', 'melt' sobre objetos en videos o imágenes. Son populares para contenido viral en TikTok. También tiene 'Add Sound' para generar efectos de sonido automáticamente."},{"q":"¿Kling AI tiene efectos como Pika?","a":"Kling AI está más enfocado en la generación de video de alta calidad que en efectos especiales creativos. Para efectos únicos y transformaciones creativas — Pika tiene ventaja. Para calidad de generación general — Kling supera a Pika."}]
},
"luma-ai-vs-runway": {
  "a": "Luma AI", "b": "Runway",
  "choose_a": ["✅ Quieres la mayor calidad cinematográfica en generación de video desde texto o imagen con Dream Machine","✅ Buscas una alternativa a Runway más accesible en precio con calidad comparable en generación pura","✅ Necesitas videos con movimiento de cámara fluido y calidad visual cinematográfica sin efectos de edición adicionales","✅ Quieres explorar generación de video IA de alta calidad con un plan gratuito para empezar"],
  "choose_b": ["✅ Necesitas la suite completa de herramientas de producción de video IA: generación + edición avanzada en un solo lugar","✅ Tu flujo de trabajo incluye herramientas como rotoscopia, eliminación de objetos y video-a-video con transformación de estilo","✅ Trabajas en producción profesional donde necesitas control total sobre cada aspecto del video","✅ Quieres la plataforma con mayor historial y confianza en proyectos de producción de alto nivel"],
  "faq": [{"q":"¿Luma Dream Machine o Runway Gen-3?","a":"Luma Dream Machine v1.6 produce videos con calidad cinematográfica excelente, especialmente en fluidez de movimiento. Runway Gen-3 Alpha tiene más herramientas de edición integradas. Para generación pura de alta calidad — Dream Machine compite muy bien; para producción integral — Runway."},{"q":"¿Luma AI es gratuito?","a":"Luma AI tiene un plan gratuito con 30 generaciones de video al mes. Los planes de pago empiezan desde $29.99/mes (Plus, 100 generaciones). Runway tiene plan gratuito (125 créditos) y planes desde $12/mes."},{"q":"¿Qué más hace Luma AI además de video?","a":"Luma AI también tiene capacidades de 3D: puede crear escenas 3D y objetos en 3D desde fotos o video usando NeRF (Neural Radiance Fields). Esta funcionalidad 3D es única y complementa la generación de video para producción creativa."},{"q":"¿Luma AI vs Kling AI?","a":"Luma Dream Machine y Kling 2.0 son competidores directos en calidad. Kling permite videos más largos (hasta 3 min); Dream Machine produce clips más cortos pero con calidad cinematográfica muy consistente. Ambos son excelentes opciones en el top tier de generación de video en 2025."}]
},
"google-veo-3-vs-runway": {
  "a": "Google Veo 3", "b": "Runway",
  "choose_a": ["✅ Necesitas la más alta calidad de video generado por IA disponible en 2025 — Veo 3 es el modelo referencia de calidad","✅ Quieres videos con audio generado automáticamente: efectos de sonido, diálogos y música sincronizados con el video","✅ Accedes via Google Flow (para directores creativos) o Gemini Ultra para la mejor experiencia integrada de Google","✅ Quieres la generación más realista en física, iluminación y movimiento humano disponible actualmente"],
  "choose_b": ["✅ Necesitas acceso inmediato con planes claros sin lista de espera — Runway tiene disponibilidad general sin restricciones","✅ Tu flujo de trabajo requiere herramientas de edición integradas además de generación: rotoscopia, motion brush, video-a-video","✅ Quieres la suite más establecida con historial probado en producciones cinematográficas y publicidad","✅ Necesitas integración con herramientas de edición profesional existentes y workflows establecidos"],
  "faq": [{"q":"¿Veo 3 es el mejor generador de video IA?","a":"Veo 3 es considerado el modelo de mayor calidad en 2025 según evaluaciones independientes, especialmente en realismo y generación de audio sincronizado. Sin embargo, el acceso es limitado (Gemini Ultra, $249.99/mes, o Google Flow para cineastas). Kling 2.0, Runway y Sora compiten en el tier superior."},{"q":"¿Cómo accedo a Google Veo 3?","a":"Veo 3 está disponible en: Gemini Ultra ($249.99/mes, incluye Google One AI Premium), Google Flow (herramienta para cineastas, acceso selectivo) y VideoFX (waitlist). Es el modelo de acceso más restringido entre los principales generadores de video."},{"q":"¿Veo 3 genera audio además de video?","a":"Sí. Esta es la capacidad más novedosa de Veo 3 — genera audio sincronizado automáticamente con el video: efectos de sonido ambientales, diálogos de personajes y música. Ningún otro modelo principal hace esto de forma nativa con la misma calidad."},{"q":"¿Runway puede competir con Veo 3?","a":"Runway Gen-3 Alpha sigue siendo excelente, especialmente como herramienta de producción completa. En calidad pura de generación, Veo 3 tiene ventaja según benchmarks independientes. Pero Runway ofrece acceso universal y herramientas de edición que Veo 3 no tiene, lo que lo hace más práctico para la mayoría de flujos de trabajo."}]
},
"canva-ai-vs-figma-ai": {
  "a": "Canva AI", "b": "Figma AI",
  "choose_a": ["✅ Eres no diseñador que necesita crear materiales de marketing visualmente atractivos rápidamente","✅ Produces contenido para redes sociales, presentaciones, flyers e infografías con templates listos para usar","✅ Tu equipo de marketing necesita una herramienta todo-en-uno para diseño, video y publicación directa","✅ Quieres la plataforma de diseño IA más accesible con la menor curva de aprendizaje del mercado"],
  "choose_b": ["✅ Diseñas interfaces de usuario y productos digitales de forma profesional en equipo","✅ Necesitas un sistema de diseño completo con componentes, variables y prototipado interactivo avanzado","✅ Tu equipo de producto usa Figma como herramienta de diseño principal y quieres IA integrada en ese flujo","✅ Necesitas las funciones de IA de Figma: autocompletado de diseño, generación de copias para UI, sugerencias contextuales"],
  "faq": [{"q":"¿Canva o Figma para diseño de redes sociales?","a":"Canva claramente para redes sociales — tiene miles de templates de Instagram, TikTok, Twitter y otras plataformas, con tamaños correctos y diseños listos. Figma no está orientado a este caso de uso. Para contenido de redes sociales, Canva es la herramienta estándar del mercado."},{"q":"¿Canva AI es gratuito?","a":"Canva tiene un plan gratuito muy completo. Las funciones de IA (Magic Media, Magic Write, Background Remover) requieren Canva Pro ($15/mes) o están incluidas en el plan educativo gratuito. Figma tiene un plan gratuito para 3 proyectos; Figma Professional desde $15/mes."},{"q":"¿Pueden los diseñadores profesionales usar Canva?","a":"Canva tiene funciones suficientes para muchos proyectos profesionales, especialmente marketing. Sin embargo, para diseño de producto y UI/UX profesional, Figma es estándar del sector. Muchos diseñadores usan Canva para entregables de marketing y Figma para diseño de producto."},{"q":"¿Qué hace la IA de Canva?","a":"Canva AI incluye: Magic Media (genera imágenes y videos desde texto), Magic Write (redacción asistida), Background Remover mejorado, Magic Expand (amplía imágenes), Magic Edit (edición de imágenes con IA) y Magic Design (crea diseños completos desde una descripción)."}]
},
"figma-ai-vs-canva-ai": {
  "a": "Figma AI", "b": "Canva AI",
  "choose_a": ["✅ Diseñas productos digitales profesionales: apps móviles, sitios web, dashboards — Figma es el estándar de la industria","✅ Trabajas en equipo de producto con desarrolladores y necesitas handoff de diseño preciso con inspección de código","✅ Necesitas sistemas de diseño con componentes reutilizables, variables de diseño y prototipos interactivos avanzados","✅ Quieres las funciones de IA de Figma integradas en tu flujo: autocompletado, generación de variantes de UI, sugerencias"],
  "choose_b": ["✅ Produces contenido de marketing visual para redes sociales, presentaciones y materiales impresos","✅ Tu equipo no tiene diseñadores profesionales y necesita la herramienta más accesible para crear contenido visual","✅ Necesitas templates listos para usar en formatos estándar de redes sociales, presentaciones y documentos","✅ Quieres una herramienta de diseño IA todo-en-uno que también incluye edición de video básica y publicación"],
  "faq": [{"q":"¿Figma AI qué puede hacer?","a":"Figma AI incluye: generación de texto para UI (fills realistas en prototipos), sugerencias de diseño contextuales, búsqueda visual en la biblioteca de componentes, resumen de comentarios, y funciones en desarrollo como generación de pantallas desde prompts. Está integrado directamente en el flujo de diseño de Figma."},{"q":"¿Figma es gratuito?","a":"Figma tiene un plan gratuito (Starter) con 3 proyectos activos y colaboradores ilimitados en modo vista. El plan Professional ($15/usuario/mes) elimina limitaciones. Figma AI está incluido en los planes de pago."},{"q":"¿Figma o Adobe XD en 2025?","a":"Adobe XD fue discontinuado por Adobe en 2023. Figma es el estándar actual del sector para diseño de UI/UX. Los usuarios de XD han migrado principalmente a Figma. Adobe ahora recomienda Figma (que intentó adquirir) y sus herramientas en Creative Cloud."},{"q":"¿Los desarrolladores pueden usar Figma directamente?","a":"Sí. Figma tiene modo Dev (Dev Mode) que muestra especificaciones de CSS, iOS y Android, valores de espaciado, colores y assets exportables. Esto facilita el handoff de diseño a desarrollo sin herramientas adicionales."}]
},
"framer-ai-vs-canva-ai": {
  "a": "Framer AI", "b": "Canva AI",
  "choose_a": ["✅ Quieres crear y publicar un sitio web completo a partir de una descripción de texto — Framer AI genera el sitio entero con diseño responsivo","✅ Necesitas una web con animaciones avanzadas, scroll effects y código personalizable sin escribir HTML/CSS desde cero","✅ Eres freelancer o startup que necesita un sitio web de presentación profesional lanzado rápidamente","✅ Quieres un sitio publicado directamente en framer.com o tu dominio propio desde la misma herramienta"],
  "choose_b": ["✅ Necesitas crear múltiples formatos de diseño: posts de redes sociales, presentaciones, infografías, documentos — Canva cubre todos","✅ Tu equipo necesita diseño colaborativo de marketing sin experiencia técnica en herramientas de diseño web","✅ Produces contenido visual a escala para campañas de marketing en múltiples formatos simultáneamente","✅ No necesitas publicar un sitio web — tu necesidad es diseño gráfico para diferentes canales de comunicación"],
  "faq": [{"q":"¿Qué es Framer AI?","a":"Framer AI es la función de generación de sitios web de Framer — describes tu sitio en texto y Framer genera el diseño completo con páginas, secciones, tipografía y paleta de colores. Puedes publicar directamente. Framer también es una herramienta de diseño web avanzada con animaciones sin código."},{"q":"¿Framer AI es gratuito?","a":"Framer tiene un plan gratuito con publicación en subdominio framer.app y 1.000 páginas vistas/mes. Los planes de pago (Mini $5/mes, Basic $15/mes) añaden dominio propio y más tráfico. Canva tiene plan gratuito más completo para diseño gráfico."},{"q":"¿Framer o Webflow para sitios web sin código?","a":"Framer es más rápido para crear y publicar, con mejor experiencia de diseño visual y animaciones. Webflow ofrece más control sobre el CMS y estructura del sitio para proyectos complejos. Para sitios de presentación modernos — Framer; para proyectos con CMS complejo — Webflow."},{"q":"¿Canva puede hacer sitios web?","a":"Canva tiene una función de Sitios Web básica que permite publicar diseños como páginas web. Sin embargo, es muy limitada comparada con Framer — sin animaciones avanzadas, menos control de diseño web y herramientas SEO más básicas. Para sitios web reales, Framer es mucho más potente."}]
},
"looka-vs-canva-ai": {
  "a": "Looka", "b": "Canva AI",
  "choose_a": ["✅ Necesitas crear un logo profesional con identidad de marca completa: paleta de colores, tipografía y kit de marca en un solo flujo","✅ Quieres docenas de variaciones de logo generadas por IA para elegir y personalizar","✅ Necesitas los archivos de logo en formatos vectoriales (SVG, PDF) para usar en print y digital","✅ Estás creando una marca desde cero y necesitas la identidad visual base: logo + colores + fuentes"],
  "choose_b": ["✅ Ya tienes logo y necesitas crear todos los demás materiales de marketing: social media, presentaciones, documentos","✅ Tu equipo necesita una herramienta de diseño completa para el día a día, no solo para crear el logo inicial","✅ Buscas la plataforma de diseño más versátil con templates para cualquier formato y canal de comunicación","✅ Canva tiene logo maker propio — si necesitas algo básico, Canva puede hacerlo sin pagar por Looka"],
  "faq": [{"q":"¿Looka o Canva para crear un logo?","a":"Looka está especializado en logos y branding — genera muchas más opciones de logo profesionales con kits de marca completos. Canva tiene logo maker pero es menos especializado. Para crear un logo como base de tu identidad de marca — Looka. Para diseño de marketing general con logo básico — Canva."},{"q":"¿Cuánto cuesta Looka?","a":"Looka tiene dos modelos de precio: Logo Package ($65 pago único, archivos básicos) o Brand Kit Subscription ($96/año, todos los archivos + kit de marca completo + app de marca). Canva Pro cuesta $15/mes. Looka es un gasto puntual para el logo; Canva es continuo para diseño en curso."},{"q":"¿Los logos de Looka son únicos?","a":"Looka genera logos basados en tus preferencias de estilo, colores e industria. Son únicos en el sentido de que se combinan para ti, pero algunos elementos (iconos, fuentes) son compartidos entre clientes. Para un logo 100% único y exclusivo, un diseñador gráfico profesional sigue siendo la mejor opción."},{"q":"¿Qué incluye el kit de marca de Looka?","a":"El Brand Kit de Looka incluye: logos en múltiples formatos (PNG, SVG, PDF), variaciones de logo (horizontal, cuadrado, icono), paleta de colores, tipografía seleccionada, tarjetas de visita, plantillas de redes sociales y acceso a la app de marca para crear materiales adicionales."}]
},
"uizard-vs-figma-ai": {
  "a": "Uizard", "b": "Figma AI",
  "choose_a": ["✅ Quieres prototipar una idea de app o web en minutos desde una descripción de texto, sin conocimientos de diseño","✅ Eres fundador de startup o product manager que necesita validar conceptos de UI rápidamente antes de involucrar a diseñadores","✅ Quieres convertir bocetos en papel en wireframes digitales usando la función de escaneo de Uizard","✅ Necesitas una herramienta de prototipado IA que no requiera formación en herramientas de diseño profesional"],
  "choose_b": ["✅ Eres diseñador profesional de UI/UX que necesita la herramienta estándar del sector con control total","✅ Trabajas en un equipo de producto establecido con sistemas de diseño, componentes y handoff a desarrolladores","✅ Necesitas prototipado de alta fidelidad con interacciones complejas, transiciones y animaciones avanzadas","✅ Tu organización ya usa Figma y quieres las funciones de IA integradas en tu flujo de trabajo existente"],
  "faq": [{"q":"¿Uizard o Figma para startups?","a":"Uizard es ideal en fases tempranas para validar ideas rápidamente — un fundador puede crear un prototipo funcional en minutos sin diseñador. Figma es mejor cuando el equipo crece y necesita un sistema de diseño formal. Muchas startups empiezan en Uizard y migran a Figma al escalar."},{"q":"¿Uizard es gratuito?","a":"Uizard tiene un plan gratuito con 3 proyectos y funciones limitadas. Los planes de pago empiezan desde $12/mes (Pro). Figma tiene plan gratuito para 3 proyectos; planes de pago desde $15/mes."},{"q":"¿Qué es Uizard Autodesigner?","a":"Autodesigner es la función IA estrella de Uizard — describes la app que quieres en texto ('aplicación de fitness para seguimiento de rutinas') y Uizard genera automáticamente múltiples pantallas de UI con diseño coherente. Es el flujo más rápido para convertir una idea en un prototipo visual."},{"q":"¿Uizard puede usarse para desarrollo real?","a":"Uizard es para prototipado y diseño conceptual, no para desarrollo. No genera código listo para producción. Los prototipos son para validar ideas y presentar conceptos. Para desarrollo real, el diseño de Uizard se usa como referencia visual."}]
},
"uxpilot-vs-figma-ai": {
  "a": "UXPilot", "b": "Figma AI",
  "choose_a": ["✅ Necesitas generar wireframes y pantallas de UI completas desde prompts de texto sin abrir ninguna herramienta de diseño","✅ Haces investigación de UX con IA: generación de personas de usuario, mapas de customer journey, análisis heurístico","✅ Quieres una herramienta dedicada a UX que no requiera licencias de Figma para empezar","✅ Produces documentación de UX (personas, user flows, auditorías) de forma rápida con asistencia de IA"],
  "choose_b": ["✅ Ya tienes Figma como herramienta principal y quieres funciones de IA integradas en tu flujo existente","✅ Necesitas el flujo completo: diseño → prototipado → handoff a desarrolladores en una sola herramienta","✅ Trabajas en un equipo de diseño que necesita colaboración en tiempo real con sistemas de diseño compartidos","✅ Quieres el mayor ecosistema de plugins y integraciones del sector (300+ plugins en Figma Community)"],
  "faq": [{"q":"¿Qué es UXPilot?","a":"UXPilot es una herramienta de IA específica para diseño UX. Puede generar wireframes desde descripciones de texto, crear personas de usuario, mapas de empatía, user journeys y documentación de UX. Está orientada a investigadores UX y product managers que necesitan documentación UX rápida."},{"q":"¿UXPilot genera código?","a":"UXPilot se centra en wireframes y documentación de UX, no en código. Para generar código desde diseños, herramientas como GitHub Copilot o Cursor con contexto de diseño son más adecuadas. UXPilot es para la fase de descubrimiento y definición, no implementación."},{"q":"¿Figma AI puede generar pantallas desde texto?","a":"Figma está desarrollando capacidades de generación de UI desde prompts, pero en 2025 estas funciones están en evolución. Para generación de pantallas completas desde texto ya hoy — Uizard o UXPilot son más especializados. Figma AI es más fuerte en asistencia contextual dentro de un diseño existente."},{"q":"¿UXPilot vs Uizard?","a":"Ambas usan IA para UI/UX, pero con enfoques distintos. Uizard es mejor para prototipado rápido de apps con diseño visual completo. UXPilot es mejor para investigación y documentación de UX: personas, journeys, wireframes conceptuales. Para un prototipo que mostrar — Uizard; para investigación de UX — UXPilot."}]
},
"relume-vs-framer-ai": {
  "a": "Relume", "b": "Framer AI",
  "choose_a": ["✅ Necesitas crear el sitemap y wireframes de un sitio web complejo antes de diseñar — Relume genera la arquitectura entera desde una descripción","✅ Usas Webflow o Figma y quieres exportar componentes directamente a estas herramientas para continuar el diseño","✅ Eres diseñador web o agencia que trabaja en el diseño base de sitios antes de construirlos en Webflow","✅ Necesitas una biblioteca de componentes de Webflow listos para usar generados por IA según tu brief"],
  "choose_b": ["✅ Quieres publicar el sitio web directamente desde la herramienta sin necesitar Webflow o Figma","✅ Necesitas el flujo más rápido de 'texto → sitio publicado' sin pasos intermedios de diseño","✅ Tu sitio requiere animaciones avanzadas y efectos de scroll que se generan directamente en Framer","✅ Quieres diseño + hosting + dominio en un solo lugar con la menor fricción posible"],
  "faq": [{"q":"¿Relume para qué sirve exactamente?","a":"Relume es una herramienta de IA para diseño de sitios web que genera: sitemaps completos desde una descripción de empresa, wireframes de cada página y componentes listos para Webflow y Figma. Es el paso previo al diseño visual — te da la estructura y los componentes, no el sitio publicado."},{"q":"¿Relume o Webflow?","a":"Son herramientas complementarias, no alternativas. Relume te ayuda a planificar y estructurar el sitio; Webflow es donde lo construyes y publicas. Relume tiene integración directa con Webflow para exportar componentes. Muchas agencias de Webflow usan Relume para acelerar la fase de diseño."},{"q":"¿Cuánto cuesta Relume?","a":"Relume tiene un plan gratuito con 1 sitio. Los planes de pago empiezan desde $38/mes (Basic). Framer tiene plan gratuito con publicación en subdominio; planes desde $5/mes."},{"q":"¿Framer AI puede crear sitemaps?","a":"Framer AI se centra en generar el diseño visual del sitio, no en la arquitectura de información. Para sitemaps y wireframes estructurales antes de diseñar — Relume es la herramienta específica. Framer es mejor para ir directamente del concepto al sitio publicado visualmente."}]
},
"whimsical-ai-vs-figma-ai": {
  "a": "Whimsical AI", "b": "Figma AI",
  "choose_a": ["✅ Necesitas crear diagramas, mapas mentales, flowcharts y wireframes rápidos para documentar y planificar","✅ Tu equipo usa Whimsical para documentación visual de proyectos, arquitecturas de sistema o procesos de negocio","✅ Quieres IA que genere mapas mentales y diagramas automáticamente desde una idea o texto","✅ Eres product manager o desarrollador que necesita documentación visual sin herramienta de diseño profesional"],
  "choose_b": ["✅ Diseñas interfaces de usuario y productos digitales de forma profesional con prototipado interactivo","✅ Trabajas en un equipo de producto que necesita handoff de diseño preciso a desarrolladores","✅ Necesitas sistemas de diseño con componentes, variables y biblioteca compartida del equipo","✅ Quieres el estándar del sector para diseño de UI/UX con el mayor ecosistema de plugins"],
  "faq": [{"q":"¿Whimsical o FigJam para diagramas?","a":"Whimsical y FigJam (el lienzo colaborativo de Figma) son competidores directos para diagramas y mapas mentales. Whimsical tiene mejor experiencia específica para mapas mentales y wireframes rápidos. FigJam está más integrado con Figma si tu equipo ya usa Figma. Para equipos mixtos — Whimsical; para equipos Figma — FigJam."},{"q":"¿Whimsical AI es gratuito?","a":"Whimsical tiene un plan gratuito con 3 espacios y funciones básicas de IA (generación de diagramas limitada). El plan Pro ($15/mes) tiene IA ilimitada y más funciones colaborativas. Figma tiene plan gratuito para diseño y FigJam está incluido en el plan gratuito de Figma."},{"q":"¿Whimsical puede crear wireframes?","a":"Sí. Whimsical tiene componentes de wireframe básicos para crear mockups de UI rápidamente. No es tan potente como Figma para wireframes detallados, pero para conceptos rápidos y comunicación de ideas es muy efectivo. Muchos equipos ágiles usan Whimsical para wireframes iniciales y Figma para diseño final."},{"q":"¿Para qué sirve Whimsical?","a":"Whimsical es una herramienta de colaboración visual para: mapas mentales (brainstorming), flowcharts (flujos de proceso), wireframes básicos y documentos colaborativos con elementos visuales. Es popular en equipos de producto para documentar y comunicar ideas antes de diseñar o desarrollar."}]
},
"suno-vs-udio": {
  "a": "Suno", "b": "Udio",
  "choose_a": ["✅ Quieres generar canciones completas con letra y producción musical desde un prompt de texto de forma intuitiva","✅ Necesitas la plataforma de creación de música IA más popular con mayor comunidad y variedad de estilos","✅ Buscas la experiencia más sencilla: escribe un tema o letra y obtén una canción lista en segundos","✅ Quieres explorar géneros musicales variados con el menor tiempo de aprendizaje posible"],
  "choose_b": ["✅ Quieres mayor control sobre el proceso de producción: estilo, estructura, secciones y características del audio","✅ Necesitas calidad de audio muy alta con más opciones de personalización para proyectos musicales serios","✅ Quieres extender secciones de audio existentes o generar secciones específicas de una canción","✅ Priorizas la calidad de producción y la fidelidad musical sobre la facilidad de uso"],
  "faq": [{"q":"¿Suno o Udio para crear música?","a":"Suno es más fácil y rápido — ideal para crear canciones completas sin experiencia musical. Udio ofrece más control y calidad de producción para músicos o creadores con proyectos más serios. Para música casual y experimental — Suno; para proyectos con mayor control creativo — Udio."},{"q":"¿Suno es gratuito?","a":"Suno tiene un plan gratuito con 50 créditos diarios (5 canciones aprox.). El plan Pro ($10/mes) ofrece 2.500 créditos/mes y uso comercial. Udio también tiene plan gratuito con 1.200 generaciones/mes; Pro desde $10/mes."},{"q":"¿La música de Suno tiene derechos de autor?","a":"Con el plan gratuito, Suno retiene ciertos derechos. Los planes de pago (Pro y Premier) otorgan derechos comerciales sobre la música generada. Lee los términos actuales de Suno cuidadosamente si planeas usar la música comercialmente. Udio tiene políticas similares según el plan."},{"q":"¿Puede la IA reemplazar a músicos reales?","a":"La música IA como Suno y Udio puede generar pistas de fondo, jingles y experimentos creativos de forma eficiente. Sin embargo, para composición original con matiz emocional, interpretación y conexión artística real, los músicos humanos siguen siendo insustituibles. Son herramientas de asistencia, no reemplazos."}]
},
"speechify-vs-elevenlabs": {
  "a": "Speechify", "b": "ElevenLabs",
  "choose_a": ["✅ Quieres una app para escuchar artículos, PDFs, emails y documentos mientras haces otras cosas","✅ Eres estudiante o profesional con dislexia o preferencia por consumir contenido en formato audio","✅ Necesitas una herramienta de productividad personal para acelerar la lectura escuchando a 2-4x velocidad","✅ Quieres sincronización entre dispositivos para escuchar lo mismo en móvil, tablet y ordenador"],
  "choose_b": ["✅ Necesitas generar voz IA de calidad profesional para contenido: podcasts, narración, doblaje, locuciones","✅ Quieres clonar tu propia voz o crear una voz sintética para producción de audio o video","✅ Produces contenido multilingüe y necesitas doblaje de alta calidad en múltiples idiomas simultáneamente","✅ Desarrollas aplicaciones que necesitan síntesis de voz vía API con las voces más realistas del mercado"],
  "faq": [{"q":"¿Speechify o ElevenLabs para podcasts?","a":"ElevenLabs para crear locuciones y narración de podcast con voz IA de calidad profesional. Speechify para escuchar contenido existente — no es para producción. Si quieres que una voz IA narre tu podcast — ElevenLabs; si quieres escuchar artículos a mayor velocidad — Speechify."},{"q":"¿Speechify es gratuito?","a":"Speechify tiene un plan gratuito limitado. El plan Premium empieza desde $139/año. ElevenLabs tiene un plan gratuito con 10.000 caracteres/mes; planes de pago desde $5/mes (Starter)."},{"q":"¿Qué voces tiene Speechify?","a":"Speechify incluye más de 30 voces IA en múltiples idiomas, incluyendo voces famosas con licencia (Gwyneth Paltrow, Snoop Dogg). Las voces son buenas para escucha de contenido pero no llegan a la calidad de ElevenLabs para producción profesional."},{"q":"¿ElevenLabs puede leer en voz alta documentos?","a":"ElevenLabs está enfocado en síntesis y clonación de voz, no en escucha personal de documentos. Para leer tus PDFs y artículos — Speechify. Para generar audio de calidad profesional desde texto — ElevenLabs. Son herramientas con propósitos distintos."}]
},
"elevenlabs-vs-murf-ai": {
  "a": "ElevenLabs", "b": "Murf AI",
  "choose_a": ["✅ Necesitas la mayor calidad de síntesis de voz disponible — ElevenLabs tiene las voces IA más realistas del mercado en 2025","✅ Quieres clonar tu voz con un fragmento de audio de alta calidad para contenido personal o empresarial","✅ Produces doblaje multilingüe avanzado con sincronización de labios y conservación de la voz original","✅ Integras síntesis de voz en tu aplicación o producto vía API con alta fiabilidad y velocidad"],
  "choose_b": ["✅ Produces locuciones profesionales en un entorno de estudio de voz completo con control de pronunciación y énfasis","✅ Tu equipo de marketing necesita una herramienta de producción de audio más accesible con scripts de presentación","✅ Necesitas voces de alta calidad para presentaciones, eLearning y videos corporativos con flujo de trabajo sencillo","✅ Buscas un plan mensual más asequible para producción de audio corporativa regular sin API técnica"],
  "faq": [{"q":"¿ElevenLabs o Murf para locuciones?","a":"ElevenLabs tiene mejor calidad de voz y más opciones de personalización. Murf es más accesible para equipos de marketing y tiene un studio más completo para producir locuciones con scripts. Para la mejor calidad técnica — ElevenLabs; para un studio de voz más completo y accesible — Murf."},{"q":"¿ElevenLabs es gratuito?","a":"ElevenLabs tiene un plan gratuito con 10.000 caracteres/mes (unos 10 minutos de audio). Los planes de pago empiezan desde $5/mes (Starter, 30.000 caracteres). Murf tiene plan gratuito con 10 minutos de voz; planes de pago desde $29/mes."},{"q":"¿Cuánto cuesta clonar una voz en ElevenLabs?","a":"La clonación de voz instantánea (menor calidad) está disponible desde el plan Starter ($5/mes). La clonación profesional de voz (mayor calidad, requiere más datos de audio) está disponible en planes superiores. El proceso requiere entre 1 minuto (básico) y varios minutos de audio de muestra."},{"q":"¿Es legal clonar una voz con IA?","a":"Clonar tu propia voz es completamente legal. Clonar la voz de otra persona sin su consentimiento explícito viola los términos de ElevenLabs y Murf, y puede tener consecuencias legales. Ambas plataformas requieren declarar que tienes los derechos sobre la voz que clonas."}]
},
"elevenlabs-vs-playht": {
  "a": "ElevenLabs", "b": "Play.ht",
  "choose_a": ["✅ Priorizas la mayor calidad de síntesis de voz — ElevenLabs es reconocido como el estándar de calidad en el sector","✅ Necesitas clonación de voz profesional con la menor cantidad de audio de muestra posible","✅ Produces doblaje y traducción de video con conservación de la voz original en múltiples idiomas","✅ Integras voz IA en tu producto vía API con alta disponibilidad y latencia baja para tiempo real"],
  "choose_b": ["✅ Necesitas acceso a más de 900 voces en múltiples idiomas y acentos de diferentes proveedores","✅ Conviertes artículos de blog en podcasts automáticamente con la función Blog to Podcast","✅ Buscas una plataforma con mayor variedad de opciones de voz para encontrar exactamente el tono que necesitas","✅ Necesitas planes más accesibles con acceso ilimitado para producción de contenido a gran escala"],
  "faq": [{"q":"¿ElevenLabs o Play.ht para podcasts?","a":"Ambas pueden convertir texto en audio de calidad podcast. ElevenLabs tiene calidad de voz superior y mejor clonación. Play.ht tiene la función 'Blog to Podcast' integrada y mayor variedad de voces. Para calidad máxima — ElevenLabs; para variedad y flujo de contenido — Play.ht."},{"q":"¿Play.ht es gratuito?","a":"Play.ht tiene un plan gratuito muy limitado. Los planes de pago empiezan desde $39/mes (Creator) con 500.000 palabras/mes. ElevenLabs tiene plan gratuito (10.000 chars/mes) y planes desde $5/mes, siendo más accesible para empezar."},{"q":"¿Cuántas voces tiene Play.ht?","a":"Play.ht ofrece acceso a más de 900 voces de IA de múltiples proveedores en más de 100 idiomas. ElevenLabs tiene más de 1.000 voces pero con enfoque en calidad sobre cantidad. Play.ht tiene mayor variedad; ElevenLabs mayor calidad consistente."},{"q":"¿ElevenLabs tiene app?","a":"ElevenLabs tiene una aplicación web completa y API robusta. También tiene Reader App (iOS/Android) para convertir artículos en audio personalmente. Play.ht también tiene interfaz web y API. Ambas están diseñadas principalmente para uso en navegador y integración API."}]
},
}

COMPARISONS = [
    {'slug': 'chatgpt-vs-claude',                    'a': 'chatgpt',                'b': 'claude'},
    {'slug': 'gemini-vs-chatgpt',                    'a': 'gemini',                 'b': 'chatgpt'},
    {'slug': 'deepseek-vs-chatgpt',                  'a': 'deepseek',               'b': 'chatgpt'},
    {'slug': 'microsoft-copilot-vs-chatgpt',         'a': 'microsoft-copilot',      'b': 'chatgpt'},
    {'slug': 'meta-ai-vs-chatgpt',                   'a': 'meta-ai',                'b': 'chatgpt'},
    {'slug': 'grok-vs-chatgpt',                      'a': 'grok',                   'b': 'chatgpt'},
    {'slug': 'mistral-le-chat-vs-chatgpt',           'a': 'mistral-le-chat',        'b': 'chatgpt'},
    {'slug': 'character-ai-vs-chatgpt',              'a': 'character-ai',           'b': 'chatgpt'},
    {'slug': 'copilot-studio-vs-manus',              'a': 'copilot-studio',         'b': 'manus'},
    {'slug': 'n8n-vs-copilot-studio',                'a': 'n8n',                    'b': 'copilot-studio'},
    {'slug': 'make-vs-copilot-studio',               'a': 'make',                   'b': 'copilot-studio'},
    {'slug': 'lindy-vs-copilot-studio',              'a': 'lindy',                  'b': 'copilot-studio'},
    {'slug': 'relevance-ai-vs-copilot-studio',       'a': 'relevance-ai',           'b': 'copilot-studio'},
    {'slug': 'devin-vs-copilot-studio',              'a': 'devin',                  'b': 'copilot-studio'},
    {'slug': 'make-vs-n8n',                          'a': 'make',                   'b': 'n8n'},
    {'slug': 'cursor-vs-copilot',                    'a': 'cursor',                 'b': 'github-copilot'},
    {'slug': 'windsurf-vs-cursor',                   'a': 'windsurf',               'b': 'cursor'},
    {'slug': 'claude-code-vs-github-copilot',        'a': 'claude-code',            'b': 'github-copilot'},
    {'slug': 'replit-vs-github-copilot',             'a': 'replit',                 'b': 'github-copilot'},
    {'slug': 'bolt-new-vs-cursor',                   'a': 'bolt-new',               'b': 'cursor'},
    {'slug': 'v0-by-vercel-vs-cursor',               'a': 'v0-by-vercel',           'b': 'cursor'},
    {'slug': 'cline-vs-github-copilot',              'a': 'cline',                  'b': 'github-copilot'},
    {'slug': 'aider-vs-github-copilot',              'a': 'aider',                  'b': 'github-copilot'},
    {'slug': 'windsurf-vs-github-copilot',           'a': 'windsurf',               'b': 'github-copilot'},
    {'slug': 'deepl-vs-grammarly',                   'a': 'deepl',                  'b': 'grammarly'},
    {'slug': 'quillbot-vs-grammarly',                'a': 'quillbot',               'b': 'grammarly'},
    {'slug': 'jasper-vs-writesonic',                 'a': 'jasper',                 'b': 'writesonic'},
    {'slug': 'writesonic-vs-grammarly',              'a': 'writesonic',             'b': 'grammarly'},
    {'slug': 'hemingway-editor-vs-grammarly',        'a': 'hemingway-editor',       'b': 'grammarly'},
    {'slug': 'semrush-vs-copy-ai',                   'a': 'semrush',                'b': 'copy-ai'},
    {'slug': 'surferseo-vs-semrush',                 'a': 'surferseo',              'b': 'semrush'},
    {'slug': 'frase-vs-semrush',                     'a': 'frase',                  'b': 'semrush'},
    {'slug': 'clearscope-vs-surferseo',              'a': 'clearscope',             'b': 'surferseo'},
    {'slug': 'copy-ai-vs-jasper',                    'a': 'copy-ai',                'b': 'jasper'},
    {'slug': 'midjourney-vs-flux',                   'a': 'midjourney',             'b': 'flux'},
    {'slug': 'midjourney-vs-stable-diffusion',       'a': 'midjourney',             'b': 'stable-diffusion'},
    {'slug': 'ideogram-vs-midjourney',               'a': 'ideogram',               'b': 'midjourney'},
    {'slug': 'adobe-firefly-vs-midjourney',          'a': 'adobe-firefly',          'b': 'midjourney'},
    {'slug': 'recraft-ai-vs-midjourney',             'a': 'recraft-ai',             'b': 'midjourney'},
    {'slug': 'flux-vs-stable-diffusion',             'a': 'flux',                   'b': 'stable-diffusion'},
    {'slug': 'leonardo-ai-vs-midjourney',            'a': 'leonardo-ai',            'b': 'midjourney'},
    {'slug': 'kling-vs-runway',                      'a': 'kling-ai',               'b': 'runway'},
    {'slug': 'capcut-vs-kling-ai',                   'a': 'capcut',                 'b': 'kling-ai'},
    {'slug': 'runway-vs-capcut',                     'a': 'runway',                 'b': 'capcut'},
    {'slug': 'heygen-vs-synthesia',                  'a': 'heygen',                 'b': 'synthesia'},
    {'slug': 'pika-vs-kling-ai',                     'a': 'pika',                   'b': 'kling-ai'},
    {'slug': 'luma-ai-vs-runway',                    'a': 'luma-ai',                'b': 'runway'},
    {'slug': 'google-veo-3-vs-runway',               'a': 'google-veo-3',           'b': 'runway'},
    {'slug': 'canva-ai-vs-figma-ai',                 'a': 'canva-ai',               'b': 'figma-ai'},
    {'slug': 'figma-ai-vs-canva-ai',                 'a': 'figma-ai',               'b': 'canva-ai'},
    {'slug': 'framer-ai-vs-canva-ai',                'a': 'framer-ai',              'b': 'canva-ai'},
    {'slug': 'looka-vs-canva-ai',                    'a': 'looka',                  'b': 'canva-ai'},
    {'slug': 'uizard-vs-figma-ai',                   'a': 'uizard',                 'b': 'figma-ai'},
    {'slug': 'uxpilot-vs-figma-ai',                  'a': 'uxpilot',                'b': 'figma-ai'},
    {'slug': 'relume-vs-framer-ai',                  'a': 'relume',                 'b': 'framer-ai'},
    {'slug': 'whimsical-ai-vs-figma-ai',             'a': 'whimsical-ai',           'b': 'figma-ai'},
    {'slug': 'suno-vs-udio',                         'a': 'suno',                   'b': 'udio'},
    {'slug': 'speechify-vs-elevenlabs',              'a': 'speechify',              'b': 'elevenlabs'},
    {'slug': 'elevenlabs-vs-murf-ai',                'a': 'elevenlabs',             'b': 'murf-ai'},
    {'slug': 'elevenlabs-vs-playht',                 'a': 'elevenlabs',             'b': 'playht'},
    {'slug': 'descript-vs-adobe-podcast',            'a': 'descript',               'b': 'adobe-podcast'},
    {'slug': 'suno-vs-elevenlabs',                   'a': 'suno',                   'b': 'elevenlabs'},
    {'slug': 'notion-ai-vs-zapier-ai',               'a': 'notion-ai',              'b': 'zapier-ai'},
    {'slug': 'gamma-vs-notion-ai',                   'a': 'gamma',                  'b': 'notion-ai'},
    {'slug': 'otter-ai-vs-fireflies-ai',             'a': 'otter-ai',               'b': 'fireflies-ai'},
    {'slug': 'motion-vs-reclaim-ai',                 'a': 'motion',                 'b': 'reclaim-ai'},
    {'slug': 'zapier-ai-vs-make',                    'a': 'zapier-ai',              'b': 'make'},
    {'slug': 'perplexity-vs-notebooklm',             'a': 'perplexity',             'b': 'notebooklm'},
    {'slug': 'elicit-vs-consensus',                  'a': 'elicit',                 'b': 'consensus'},
    {'slug': 'consensus-vs-perplexity',              'a': 'consensus',              'b': 'perplexity'},
    {'slug': 'notebooklm-vs-humata',                 'a': 'notebooklm',             'b': 'humata'},
    {'slug': 'scite-vs-semantic-scholar',            'a': 'scite',                  'b': 'semantic-scholar'},
    {'slug': 'looker-studio-vs-tableau-ai',          'a': 'looker-studio',          'b': 'tableau-ai'},
    {'slug': 'julius-ai-vs-looker-studio',           'a': 'julius-ai',              'b': 'looker-studio'},
    {'slug': 'hex-vs-looker-studio',                 'a': 'hex',                    'b': 'looker-studio'},
    {'slug': 'rows-vs-hex',                          'a': 'rows',                   'b': 'hex'},
    {'slug': 'retool-ai-vs-looker-studio',           'a': 'retool-ai',              'b': 'looker-studio'},
    {'slug': 'bubble-vs-webflow',                    'a': 'bubble',                 'b': 'webflow'},
    {'slug': 'lovable-vs-bubble',                    'a': 'lovable',                'b': 'bubble'},
    {'slug': 'flutterflow-vs-bubble',                'a': 'flutterflow',            'b': 'bubble'},
    {'slug': 'glide-vs-bubble',                      'a': 'glide',                  'b': 'bubble'},
    {'slug': 'softr-vs-bubble',                      'a': 'softr',                  'b': 'bubble'},
    {'slug': 'webflow-vs-framer-ai',                 'a': 'webflow',                'b': 'framer-ai'},
    {'slug': 'photomath-vs-duolingo-max',            'a': 'photomath',              'b': 'duolingo-max'},
    {'slug': 'khanmigo-vs-photomath',                'a': 'khanmigo',               'b': 'photomath'},
    {'slug': 'duolingo-max-vs-khanmigo',             'a': 'duolingo-max',           'b': 'khanmigo'},
    {'slug': 'youlearn-vs-notebooklm',               'a': 'youlearn',               'b': 'notebooklm'},
    {'slug': 'synthesis-vs-khanmigo',                'a': 'synthesis',              'b': 'khanmigo'},
    {'slug': 'gamma-vs-beautiful-ai',                'a': 'gamma',                  'b': 'beautiful-ai'},
    {'slug': 'gamma-vs-pitch',                       'a': 'gamma',                  'b': 'pitch'},
    {'slug': 'gamma-vs-prezi',                       'a': 'gamma',                  'b': 'prezi'},
    {'slug': 'beautiful-ai-vs-pitch',                'a': 'beautiful-ai',           'b': 'pitch'},
    {'slug': 'slidesgo-vs-gamma',                    'a': 'slidesgo',               'b': 'gamma'},
    {'slug': 'tradingview-vs-fiscal-ai',             'a': 'tradingview',            'b': 'finchat'},
    {'slug': 'koyfin-vs-tradingview',                'a': 'koyfin',                 'b': 'tradingview'},
    {'slug': 'fiscal-ai-vs-koyfin',                  'a': 'finchat',                'b': 'koyfin'},
    {'slug': 'tickeron-vs-tradingview',              'a': 'tickeron',               'b': 'tradingview'},
    {'slug': 'uptrends-ai-vs-koyfin',               'a': 'uptrends-ai',            'b': 'koyfin'},
    {'slug': 'amazon-q-developer-vs-github-copilot','a': 'amazon-q-developer',     'b': 'github-copilot'},
    {'slug': 'continue-dev-vs-github-copilot',      'a': 'continue-dev',           'b': 'github-copilot'},
    {'slug': 'opencode-vs-claude-code',             'a': 'opencode',               'b': 'claude-code'},
    {'slug': 'zed-vs-cursor',                       'a': 'zed',                    'b': 'cursor'},
    {'slug': 'comfyui-vs-stable-diffusion',         'a': 'comfyui',                'b': 'stable-diffusion'},
    {'slug': 'krea-ai-vs-midjourney',               'a': 'krea-ai',                'b': 'midjourney'},
    {'slug': 'nano-banana-vs-leonardo-ai',          'a': 'nano-banana',            'b': 'leonardo-ai'},
    {'slug': 'chatgpt-images-vs-adobe-firefly',     'a': 'chatgpt-images',         'b': 'adobe-firefly'},
    {'slug': 'claude-design-vs-figma-ai',           'a': 'claude-design',          'b': 'figma-ai'},
    {'slug': 'google-stitch-vs-figma-ai',           'a': 'google-stitch',          'b': 'figma-ai'},
    {'slug': 'recraft-vs-canva-ai',                 'a': 'recraft',                'b': 'canva-ai'},
    {'slug': 'remove-bg-vs-canva-ai',               'a': 'remove-bg',              'b': 'canva-ai'},
    {'slug': 'seedance-vs-runway',                  'a': 'seedance-2-0',           'b': 'runway'},
    {'slug': 'whisper-vs-otter-ai',                 'a': 'whisper',                'b': 'otter-ai'},
    {'slug': 'adcreative-ai-vs-canva-ai',           'a': 'adcreative-ai',          'b': 'canva-ai'},
    {'slug': 'akkio-vs-julius-ai',                  'a': 'akkio',                  'b': 'julius-ai'},
    {'slug': 'autogpt-vs-manus',                    'a': 'autogpt',                'b': 'manus'},
    {'slug': 'coursera-coach-vs-khanmigo',          'a': 'coursera-coach',         'b': 'khanmigo'},
    {'slug': 'socratic-vs-khanmigo',                'a': 'socratic-by-google',     'b': 'khanmigo'},
]

# ── Build tool_slug → {choose_if, faq} ──────────────────────────────────────
tool_data = {}
for comp in COMPARISONS:
    slug_a = comp['a']
    slug_b = comp['b']
    key    = comp['slug']
    if key not in DATA_ES:
        continue
    d = DATA_ES[key]
    if slug_a not in tool_data:
        tool_data[slug_a] = {'choose_if': d['choose_a'], 'faq': d['faq']}
    if slug_b not in tool_data:
        tool_data[slug_b] = {'choose_if': d['choose_b'], 'faq': d['faq']}

# ── Generate SQL for tools table ─────────────────────────────────────────────
lines = []
lines.append("-- Spanish choose_if + faq UPDATE — generated by gen_tool_choose_faq_es_b2.py (batch 2/4)")
lines.append("BEGIN;")
for i, (tool_slug, td) in enumerate(sorted(tool_data.items()), start=1):
    ci_json = json.dumps(td['choose_if'], ensure_ascii=False)
    fq_json = json.dumps(td['faq'],       ensure_ascii=False)
    tag_ci  = f't{i}ci'
    tag_fq  = f't{i}fq'
    lines.append(
        f"UPDATE tools SET"
        f" choose_if = ${tag_ci}${ci_json}${tag_ci}$::JSONB,"
        f" faq = ${tag_fq}${fq_json}${tag_fq}$::JSONB"
        f" WHERE slug = '{tool_slug}' AND lang = 'es';"
    )
lines.append("COMMIT;")
sql = "\n".join(lines)
out_path = __file__.replace('.py', '.sql')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(sql)
print(f"-- Tools SQL written to {out_path}", file=sys.stderr)

# ── Generate SQL for comparisons table ───────────────────────────────────────
comp_lines = []
comp_lines.append("-- Spanish choose_a + choose_b + faq INSERT for comparisons table (batch 2/4)")
comp_lines.append("BEGIN;")
for i, comp in enumerate(COMPARISONS, start=1):
    key = comp['slug']
    if key not in DATA_ES:
        continue
    d = DATA_ES[key]
    ca_json  = json.dumps(d['choose_a'], ensure_ascii=False)
    cb_json  = json.dumps(d['choose_b'], ensure_ascii=False)
    faq_json = json.dumps(d['faq'],      ensure_ascii=False)
    tag_a = f'c{i}a'; tag_b = f'c{i}b'; tag_f = f'c{i}f'
    comp_lines.append(
        f"INSERT INTO comparisons "
        f"(slug,lang,tool_a,tool_b,tool_a_slug,tool_b_slug,tool_a_url,tool_b_url,"
        f"title,meta_desc,intro,table_data,best_a,best_b,verdict_a,verdict_b,choose_a,choose_b,faq)"
        f" SELECT slug,'es',tool_a,tool_b,tool_a_slug,tool_b_slug,tool_a_url,tool_b_url,"
        f"title,meta_desc,intro,table_data,best_a,best_b,verdict_a,verdict_b,"
        f"${tag_a}${ca_json}${tag_a}$::JSONB,"
        f"${tag_b}${cb_json}${tag_b}$::JSONB,"
        f"${tag_f}${faq_json}${tag_f}$::JSONB"
        f" FROM comparisons WHERE slug='{key}' AND lang='en'"
        f" ON CONFLICT (slug,lang) DO UPDATE SET"
        f" choose_a=EXCLUDED.choose_a, choose_b=EXCLUDED.choose_b, faq=EXCLUDED.faq;"
    )
comp_lines.append("COMMIT;")
comp_sql = "\n".join(comp_lines)
comp_out = __file__.replace('.py', '_comparisons.sql')
with open(comp_out, 'w', encoding='utf-8') as f:
    f.write(comp_sql)
print(f"-- Comparisons SQL written to {comp_out}", file=sys.stderr)
print(f"Batch 2/4 done: {len(DATA_ES)} comparisons, {len(tool_data)} tools")
