-- Hebrew translations for `best_for` field in tools table
-- 102 tools — translations done by Claude inline (2026-04-27)
-- Run in Supabase SQL editor

BEGIN;

UPDATE tools SET best_for = 'גרפיקה לפרסומות, פרסומות Facebook/Google' WHERE slug = 'adcreative-ai' AND lang = 'he';
UPDATE tools SET best_for = 'עיצוב מסחרי, אקוסיסטם Adobe' WHERE slug = 'adobe-firefly' AND lang = 'he';
UPDATE tools SET best_for = 'ניקוי אודיו, איכות פודקאסט, הקלטה מרחוק' WHERE slug = 'adobe-podcast' AND lang = 'he';
UPDATE tools SET best_for = 'תחזיות, חיזוי נטישה, ML ללא קוד' WHERE slug = 'akkio' AND lang = 'he';
UPDATE tools SET best_for = 'משימות אוטונומיות, סוכני AI בקוד פתוח' WHERE slug = 'autogpt' AND lang = 'he';
UPDATE tools SET best_for = 'מצגות עסקיות, pitch decks' WHERE slug = 'beautiful-ai' AND lang = 'he';
UPDATE tools SET best_for = 'אבות-טיפוס מהירים, MVP fullstack' WHERE slug = 'bolt-new' AND lang = 'he';
UPDATE tools SET best_for = 'אפליקציות ווב, marketplaces, SaaS' WHERE slug = 'bubble' AND lang = 'he';
UPDATE tools SET best_for = 'רשתות חברתיות, מצגות, שיווק' WHERE slug = 'canva-ai' AND lang = 'he';
UPDATE tools SET best_for = 'סרטונים לרשתות חברתיות, reels, עריכה' WHERE slug = 'capcut' AND lang = 'he';
UPDATE tools SET best_for = 'צ׳אט עם דמויות AI, משחקי תפקידים, כתיבה יצירתית' WHERE slug = 'character-ai' AND lang = 'he';
UPDATE tools SET best_for = 'משימות כלליות, כתיבה, תכנות' WHERE slug = 'chatgpt' AND lang = 'he';
UPDATE tools SET best_for = 'טקסטים ארוכים, ניתוח מסמכים, קוד' WHERE slug = 'claude' AND lang = 'he';
UPDATE tools SET best_for = 'טרמינל, משימות אג׳נטיות מורכבות' WHERE slug = 'claude-code' AND lang = 'he';
UPDATE tools SET best_for = 'מצגות AI, mockups, ויזואלים תואמי מותג' WHERE slug = 'claude-design' AND lang = 'he';
UPDATE tools SET best_for = 'דירוג תוכן, אופטימיזציית מילות מפתח' WHERE slug = 'clearscope' AND lang = 'he';
UPDATE tools SET best_for = 'פייפליינים מתקדמים, סטודיו משחקים, מודלים מותאמים' WHERE slug = 'comfyui' AND lang = 'he';
UPDATE tools SET best_for = 'קונצנזוס מדעי, בדיקת עובדות' WHERE slug = 'consensus' AND lang = 'he';
UPDATE tools SET best_for = 'טקסטים לפרסומות, קמפייני אימייל, פוסטים חברתיים' WHERE slug = 'copy-ai' AND lang = 'he';
UPDATE tools SET best_for = 'קורסים מקוונים, תעודות מקצועיות' WHERE slug = 'coursera-coach' AND lang = 'he';
UPDATE tools SET best_for = 'IDE מבוסס AI, ריפקטור קוד' WHERE slug = 'cursor' AND lang = 'he';
UPDATE tools SET best_for = 'תמונות מדויקות מ-prompt, אינטגרציה ל-ChatGPT' WHERE slug = 'dall-e-3' AND lang = 'he';
UPDATE tools SET best_for = 'תרגום מדויק, תוכן רב-לשוני' WHERE slug = 'deepl' AND lang = 'he';
UPDATE tools SET best_for = 'אלטרנטיבה חינמית ל-GPT-4' WHERE slug = 'deepseek' AND lang = 'he';
UPDATE tools SET best_for = 'פודקאסטים, עריכת וידאו מבוססת טקסט' WHERE slug = 'descript' AND lang = 'he';
UPDATE tools SET best_for = 'לימוד שפות, תרגול דיבור' WHERE slug = 'duolingo-max' AND lang = 'he';
UPDATE tools SET best_for = 'שכפול קולות, TTS, voiceover' WHERE slug = 'elevenlabs' AND lang = 'he';
UPDATE tools SET best_for = 'מאמרים מדעיים, סקירת ספרות' WHERE slug = 'elicit' AND lang = 'he';
UPDATE tools SET best_for = 'עיצוב UI/UX, שיתוף פעולה בצוות' WHERE slug = 'figma-ai' AND lang = 'he';
UPDATE tools SET best_for = 'סיכומי פגישות, משימות, סיכומים' WHERE slug = 'fireflies-ai' AND lang = 'he';
UPDATE tools SET best_for = 'אפליקציות מובייל, iOS/Android, ביצועים נטיביים' WHERE slug = 'flutterflow' AND lang = 'he';
UPDATE tools SET best_for = 'קוד פתוח, איכות גבוהה, אלטרנטיבה חינמית ל-Midjourney' WHERE slug = 'flux' AND lang = 'he';
UPDATE tools SET best_for = 'Landing pages, אתרי פורטפוליו' WHERE slug = 'framer-ai' AND lang = 'he';
UPDATE tools SET best_for = 'תקצירי תוכן, כתיבת SEO, ניתוח SERP' WHERE slug = 'frase' AND lang = 'he';
UPDATE tools SET best_for = 'מצגות, pitch decks, מסמכים ויזואליים' WHERE slug = 'gamma' AND lang = 'he';
UPDATE tools SET best_for = 'מידע עדכני, אקוסיסטם Google' WHERE slug = 'gemini' AND lang = 'he';
UPDATE tools SET best_for = 'השלמה אוטומטית, אינטגרציה ל-IDE' WHERE slug = 'github-copilot' AND lang = 'he';
UPDATE tools SET best_for = 'כלים פנימיים, אפליקציות מבוססות נתונים' WHERE slug = 'glide' AND lang = 'he';
UPDATE tools SET best_for = 'איכות גבוהה, אודיו ריאליסטי' WHERE slug = 'google-veo-3' AND lang = 'he';
UPDATE tools SET best_for = 'דקדוק, סגנון, שיפור טקסט' WHERE slug = 'grammarly' AND lang = 'he';
UPDATE tools SET best_for = 'חדשות בזמן אמת, תובנות מ-X/טוויטר' WHERE slug = 'grok' AND lang = 'he';
UPDATE tools SET best_for = 'כתיבה ברורה, קריאות, עריכה' WHERE slug = 'hemingway-editor' AND lang = 'he';
UPDATE tools SET best_for = 'מדע נתונים, אנליטיקה צוותית' WHERE slug = 'hex' AND lang = 'he';
UPDATE tools SET best_for = 'אווטרים, דיבוב, שיווק' WHERE slug = 'heygen' AND lang = 'he';
UPDATE tools SET best_for = 'שאלות ותשובות על PDF, מסמכים משפטיים, מאמרי מחקר' WHERE slug = 'humata' AND lang = 'he';
UPDATE tools SET best_for = 'פוסטרים עם טקסט, טיפוגרפיה' WHERE slug = 'ideogram' AND lang = 'he';
UPDATE tools SET best_for = 'תוכן שיווקי, כתיבת SEO' WHERE slug = 'jasper' AND lang = 'he';
UPDATE tools SET best_for = 'ניתוח CSV, ויזואליזציית נתונים' WHERE slug = 'julius-ai' AND lang = 'he';
UPDATE tools SET best_for = 'הוראה לכיתות K-12, מתמטיקה, מדע' WHERE slug = 'khanmigo' AND lang = 'he';
UPDATE tools SET best_for = 'סרטונים ארוכים, פיזיקת תנועה' WHERE slug = 'kling-ai' AND lang = 'he';
UPDATE tools SET best_for = 'נכסי משחק, תמונות מוצר, דמויות' WHERE slug = 'leonardo-ai' AND lang = 'he';
UPDATE tools SET best_for = 'סוכני אימייל, תזמון, בוטי תמיכה' WHERE slug = 'lindy' AND lang = 'he';
UPDATE tools SET best_for = 'לוגואים, מיתוג לעסקים' WHERE slug = 'looka' AND lang = 'he';
UPDATE tools SET best_for = 'דשבורדי BI, דיווח, אנליטיקה חינמית' WHERE slug = 'looker-studio' AND lang = 'he';
UPDATE tools SET best_for = 'אפליקציות full-stack, MVP של SaaS' WHERE slug = 'lovable' AND lang = 'he';
UPDATE tools SET best_for = 'וידאו ריאליסטי, סצנות תלת-ממד, Dream Machine' WHERE slug = 'luma-ai' AND lang = 'he';
UPDATE tools SET best_for = 'אוטומציות מורכבות, אינטגרציות בין אפליקציות' WHERE slug = 'make' AND lang = 'he';
UPDATE tools SET best_for = 'משימות אוטונומיות, מחקר, תכנות, סוכני ווב' WHERE slug = 'manus' AND lang = 'he';
UPDATE tools SET best_for = 'רשתות חברתיות, משימות יומיומיות, צ׳אט חינמי' WHERE slug = 'meta-ai' AND lang = 'he';
UPDATE tools SET best_for = 'Windows, Office 365, משימות יומיומיות' WHERE slug = 'microsoft-copilot' AND lang = 'he';
UPDATE tools SET best_for = 'סוכנים ארגוניים, אקוסיסטם Microsoft' WHERE slug = 'microsoft-copilot-studio' AND lang = 'he';
UPDATE tools SET best_for = 'אומנות אומנותית, פוטוריאליזם' WHERE slug = 'midjourney' AND lang = 'he';
UPDATE tools SET best_for = 'אוטומציית workflow, פייפליינים של AI' WHERE slug = 'n8n' AND lang = 'he';
UPDATE tools SET best_for = 'ניתוח PDF, סיכומים, שאלות ותשובות' WHERE slug = 'notebooklm' AND lang = 'he';
UPDATE tools SET best_for = 'הערות, בסיס ידע, מסמכים' WHERE slug = 'notion-ai' AND lang = 'he';
UPDATE tools SET best_for = 'תחזיות, ML ללא קוד' WHERE slug = 'obviously-ai' AND lang = 'he';
UPDATE tools SET best_for = 'פגישות, תמלול, סיכומים' WHERE slug = 'otter-ai' AND lang = 'he';
UPDATE tools SET best_for = 'מחקר, תשובות עם מקורות' WHERE slug = 'perplexity' AND lang = 'he';
UPDATE tools SET best_for = 'שיעורי בית במתמטיקה, פתרונות צעד אחר צעד' WHERE slug = 'photomath' AND lang = 'he';
UPDATE tools SET best_for = 'קליפים קצרים, אפקטים יצירתיים, רשתות חברתיות' WHERE slug = 'pika' AND lang = 'he';
UPDATE tools SET best_for = 'מצגות צוות, מצגות סטארטאפ' WHERE slug = 'pitch' AND lang = 'he';
UPDATE tools SET best_for = 'מצגות דינמיות, ויזואלים לסיפורים' WHERE slug = 'prezi' AND lang = 'he';
UPDATE tools SET best_for = 'פרפרזה, סיכום, כתיבה מחדש' WHERE slug = 'quillbot' AND lang = 'he';
UPDATE tools SET best_for = 'ניהול זמן, AI ליומן' WHERE slug = 'reclaim-ai' AND lang = 'he';
UPDATE tools SET best_for = 'אייקוני SVG, אומנות וקטורית, נכסי מותג' WHERE slug = 'recraft-ai' AND lang = 'he';
UPDATE tools SET best_for = 'צוותי ריבוי-סוכנים, בוטי מכירות ותמיכה' WHERE slug = 'relevance-ai' AND lang = 'he';
UPDATE tools SET best_for = 'Wireframes לאתרים, עיצוב ב-Figma ו-Webflow' WHERE slug = 'relume' AND lang = 'he';
UPDATE tools SET best_for = 'הסרת רקע, תמונות מוצר, cutouts' WHERE slug = 'remove-bg' AND lang = 'he';
UPDATE tools SET best_for = 'קידוד בענן, לימוד, פריסות מהירות' WHERE slug = 'replit' AND lang = 'he';
UPDATE tools SET best_for = 'גיליונות אלקטרוניים מבוססי AI, ייבוא נתונים' WHERE slug = 'rows' AND lang = 'he';
UPDATE tools SET best_for = 'וידאו קולנועי, מקצוענים' WHERE slug = 'runway' AND lang = 'he';
UPDATE tools SET best_for = 'חיפוש אקדמי, ציטוטים' WHERE slug = 'semantic-scholar' AND lang = 'he';
UPDATE tools SET best_for = 'מחקר SEO, ניתוח מתחרים' WHERE slug = 'semrush' AND lang = 'he';
UPDATE tools SET best_for = 'תבניות, Google Slides, PowerPoint' WHERE slug = 'slidesgo' AND lang = 'he';
UPDATE tools SET best_for = 'עזרה בשיעורי בית, כל המקצועות' WHERE slug = 'socratic-by-google' AND lang = 'he';
UPDATE tools SET best_for = 'פורטלי לקוחות, דשבורדים פנימיים' WHERE slug = 'softr' AND lang = 'he';
UPDATE tools SET best_for = 'טקסט-לווידאו, קליפי AI קולנועיים' WHERE slug = 'sora' AND lang = 'he';
UPDATE tools SET best_for = 'TTS, סיוע בקריאה, לימוד, נגישות' WHERE slug = 'speechify' AND lang = 'he';
UPDATE tools SET best_for = 'הרצה מקומית, התאמה מלאה' WHERE slug = 'stable-diffusion' AND lang = 'he';
UPDATE tools SET best_for = 'יצירת מוזיקה מהירה' WHERE slug = 'suno' AND lang = 'he';
UPDATE tools SET best_for = 'SEO באתר, ניקוד תוכן' WHERE slug = 'surferseo' AND lang = 'he';
UPDATE tools SET best_for = 'מתמטיקה לכיתות K-8, מיומנויות פתרון בעיות' WHERE slug = 'synthesis' AND lang = 'he';
UPDATE tools SET best_for = 'BI, ארגוני, ויזואליזציה' WHERE slug = 'tableau-ai' AND lang = 'he';
UPDATE tools SET best_for = 'מצגות מבוססות AI, סיפור' WHERE slug = 'tome' AND lang = 'he';
UPDATE tools SET best_for = 'מוזיקה עם ווקאלים, טראקים שלמים' WHERE slug = 'udio' AND lang = 'he';
UPDATE tools SET best_for = 'אבות-טיפוס, wireframes, MVP' WHERE slug = 'uizard' AND lang = 'he';
UPDATE tools SET best_for = 'קומפוננטות UI, React, אבות-טיפוס' WHERE slug = 'v0-by-vercel' AND lang = 'he';
UPDATE tools SET best_for = 'אתרי שיווק, CMS, landing pages' WHERE slug = 'webflow' AND lang = 'he';
UPDATE tools SET best_for = 'תמלול, כתוביות' WHERE slug = 'whisper' AND lang = 'he';
UPDATE tools SET best_for = 'IDE AI חינמי, עריכת מספר קבצים, קידוד אג׳נטי' WHERE slug = 'windsurf' AND lang = 'he';
UPDATE tools SET best_for = 'מאמרי SEO, תוכן חברתי' WHERE slug = 'writesonic' AND lang = 'he';
UPDATE tools SET best_for = 'אוטומציה, אינטגרציות ללא קוד' WHERE slug = 'zapier-ai' AND lang = 'he';

COMMIT;
