#!/usr/bin/env python3
"""
Translate May 17 batch (12 tools) to 7 languages.
Fetches updated EN content from Supabase, translates, writes SQL.

Run: python3 scripts/translate_tools_may17.py
Then: paste scripts/update_tools_may17_translated.sql into Supabase SQL Editor
Then: python3 scripts/generate-lang-tool-pages.py && git push
"""

import anthropic, json, time, re, urllib.request

client = anthropic.Anthropic()

SB_URL = 'https://lbjdwkvkkndvofysyssy.supabase.co'
SB_KEY = 'sb_publishable_tdDKX99tgBeQxM5OjDK_NQ_yQVavNUG'

SLUGS = [
    'cursor', 'notion-ai', 'heygen', 'figma-ai', 'luma-ai', 'pika',
    'kling-ai', 'midjourney', 'elevenlabs', 'adobe-firefly', 'perplexity', 'grok',
]

LANG_NAMES = {
    'ru': 'Russian', 'es': 'Spanish', 'de': 'German',
    'ua': 'Ukrainian', 'he': 'Hebrew', 'fr': 'French', 'pt': 'Portuguese',
}


def sb_get(path):
    req = urllib.request.Request(f'{SB_URL}/rest/v1/{path}',
        headers={'apikey': SB_KEY, 'Authorization': f'Bearer {SB_KEY}'})
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())


def translate_tool(tool, lang):
    lang_name = LANG_NAMES[lang]
    fields = {
        'best_for': tool['best_for'] or '',
        'description': tool['description'] or '',
        'description_long': tool['description_long'] or '',
        'pros': tool['pros'] or [],
        'cons': tool['cons'] or [],
    }
    prompt = f"""Translate this AI tool info to {lang_name}.
Rules:
- Keep tool name "{tool['name']}" unchanged
- Keep all product/brand names in English (Cursor, Claude, Firefly, etc.)
- Keep technical terms in English (API, IDE, MCP, SDK, TTS, STT, etc.)
- Keep prices and numbers as-is
- Translate naturally, not word-for-word
- For Hebrew: use right-to-left natural phrasing
- Return ONLY valid JSON with exactly these keys: best_for, description, description_long, pros (array), cons (array)

{json.dumps(fields, ensure_ascii=False)}"""

    msg = client.messages.create(
        model='claude-haiku-4-5-20251001',
        max_tokens=3000,
        messages=[{'role': 'user', 'content': prompt}]
    )
    text = msg.content[0].text.strip()
    text = re.sub(r'^```(?:json)?\n?', '', text)
    text = re.sub(r'\n?```$', '', text)
    m = re.search(r'\{[\s\S]+\}', text)
    return json.loads(m.group(0))


def dq(val):
    """Dollar-quote a string value for PostgreSQL."""
    if val is None:
        return 'NULL'
    # Use $$ quoting — safe as long as content doesn't contain $$
    return f'$${val}$$'


def arr_dq(items):
    """Build PostgreSQL ARRAY[$$...$$, ...] from a list."""
    if not items:
        return "ARRAY[]::text[]"
    parts = [f'$${item}$$' for item in items]
    return 'ARRAY[' + ','.join(parts) + ']'


def main():
    slugs_param = ','.join(SLUGS)
    tools_en = {
        t['slug']: t
        for t in sb_get(f'tools?lang=eq.en&slug=in.({slugs_param})&select=*&limit=20')
    }
    print(f'Fetched {len(tools_en)} EN tools\n')

    lines = [
        '-- May 17 batch translations — 12 tools × 7 languages',
        '-- Generated by translate_tools_may17.py',
        '-- Paste into Supabase SQL Editor',
        '-- Then: python3 scripts/generate-lang-tool-pages.py && git push',
        '',
    ]

    for slug in SLUGS:
        tool = tools_en.get(slug)
        if not tool:
            print(f'  SKIP {slug} — not found in EN')
            continue
        print(f'\n== {slug} ==')
        for lang in ['ru', 'es', 'de', 'ua', 'he', 'fr', 'pt']:
            print(f'  → {lang}...', flush=True)
            for attempt in range(3):
                try:
                    t = translate_tool(tool, lang)
                    lines.append(
                        f"-- {slug} [{lang}]\n"
                        f"UPDATE tools SET\n"
                        f"  best_for         = {dq(t['best_for'])},\n"
                        f"  description      = {dq(t['description'])},\n"
                        f"  description_long = {dq(t['description_long'])},\n"
                        f"  pros             = {arr_dq(t['pros'])},\n"
                        f"  cons             = {arr_dq(t['cons'])}\n"
                        f"WHERE slug = '{slug}' AND lang = '{lang}';\n"
                    )
                    print(f'    ✓')
                    time.sleep(0.5)
                    break
                except Exception as e:
                    if attempt < 2:
                        print(f'    retry ({e})...', flush=True)
                        time.sleep(5)
                    else:
                        print(f'    ERROR: {e}')

    sql = '\n'.join(lines)
    out = 'scripts/update_tools_may17_translated.sql'
    with open(out, 'w', encoding='utf-8') as f:
        f.write(sql)

    updates = sql.count('UPDATE tools SET')
    print(f'\nDone — {updates} UPDATE statements → {out}')
    print('Next: paste into Supabase → python3 scripts/generate-lang-tool-pages.py → git push')


if __name__ == '__main__':
    main()
