-- Ukrainian translations for `best_for` field in tools table
-- 102 tools — translations done by Claude inline (2026-04-27)
-- Run in Supabase SQL editor

BEGIN;

UPDATE tools SET best_for = 'Графіка для реклами, реклама Facebook/Google' WHERE slug = 'adcreative-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Комерційний дизайн, екосистема Adobe' WHERE slug = 'adobe-firefly' AND lang = 'ua';
UPDATE tools SET best_for = 'Очищення аудіо, якість подкасту, віддалений запис' WHERE slug = 'adobe-podcast' AND lang = 'ua';
UPDATE tools SET best_for = 'Прогнозування, передбачення відтоку, ML без коду' WHERE slug = 'akkio' AND lang = 'ua';
UPDATE tools SET best_for = 'Автономні задачі, AI-агенти з відкритим кодом' WHERE slug = 'autogpt' AND lang = 'ua';
UPDATE tools SET best_for = 'Бізнес-презентації, pitch decks' WHERE slug = 'beautiful-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Швидкі прототипи, fullstack MVP' WHERE slug = 'bolt-new' AND lang = 'ua';
UPDATE tools SET best_for = 'Веб-додатки, marketplaces, SaaS' WHERE slug = 'bubble' AND lang = 'ua';
UPDATE tools SET best_for = 'Соцмережі, презентації, маркетинг' WHERE slug = 'canva-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Відео для соцмереж, reels, монтаж' WHERE slug = 'capcut' AND lang = 'ua';
UPDATE tools SET best_for = 'Чат з AI-персонажами, рольові ігри, творче письмо' WHERE slug = 'character-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Загальні задачі, написання текстів, програмування' WHERE slug = 'chatgpt' AND lang = 'ua';
UPDATE tools SET best_for = 'Довгі тексти, аналіз документів, код' WHERE slug = 'claude' AND lang = 'ua';
UPDATE tools SET best_for = 'Термінал, складні агентні задачі' WHERE slug = 'claude-code' AND lang = 'ua';
UPDATE tools SET best_for = 'AI-презентації, mockups, візуали в стилі бренду' WHERE slug = 'claude-design' AND lang = 'ua';
UPDATE tools SET best_for = 'Оцінка контенту, оптимізація ключових слів' WHERE slug = 'clearscope' AND lang = 'ua';
UPDATE tools SET best_for = 'Розширені пайплайни, ігрові студії, кастомні моделі' WHERE slug = 'comfyui' AND lang = 'ua';
UPDATE tools SET best_for = 'Науковий консенсус, перевірка фактів' WHERE slug = 'consensus' AND lang = 'ua';
UPDATE tools SET best_for = 'Рекламні тексти, email-кампанії, пости в соцмережах' WHERE slug = 'copy-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Онлайн-курси, професійні сертифікати' WHERE slug = 'coursera-coach' AND lang = 'ua';
UPDATE tools SET best_for = 'AI IDE, рефакторинг коду' WHERE slug = 'cursor' AND lang = 'ua';
UPDATE tools SET best_for = 'Точні зображення з prompt, інтеграція з ChatGPT' WHERE slug = 'dall-e-3' AND lang = 'ua';
UPDATE tools SET best_for = 'Точний переклад, багатомовний контент' WHERE slug = 'deepl' AND lang = 'ua';
UPDATE tools SET best_for = 'Безкоштовна альтернатива GPT-4' WHERE slug = 'deepseek' AND lang = 'ua';
UPDATE tools SET best_for = 'Подкасти, монтаж відео на основі тексту' WHERE slug = 'descript' AND lang = 'ua';
UPDATE tools SET best_for = 'Вивчення мов, практика мовлення' WHERE slug = 'duolingo-max' AND lang = 'ua';
UPDATE tools SET best_for = 'Клонування голосу, TTS, озвучка' WHERE slug = 'elevenlabs' AND lang = 'ua';
UPDATE tools SET best_for = 'Наукові статті, огляд літератури' WHERE slug = 'elicit' AND lang = 'ua';
UPDATE tools SET best_for = 'UI/UX дизайн, командна співпраця' WHERE slug = 'figma-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Нотатки зустрічей, задачі, резюме' WHERE slug = 'fireflies-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Мобільні додатки, iOS/Android, нативна продуктивність' WHERE slug = 'flutterflow' AND lang = 'ua';
UPDATE tools SET best_for = 'Відкритий код, висока якість, безкоштовна альтернатива Midjourney' WHERE slug = 'flux' AND lang = 'ua';
UPDATE tools SET best_for = 'Landing pages, портфоліо-сайти' WHERE slug = 'framer-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Брифи контенту, SEO-копірайтинг, аналіз SERP' WHERE slug = 'frase' AND lang = 'ua';
UPDATE tools SET best_for = 'Презентації, pitch decks, візуальні документи' WHERE slug = 'gamma' AND lang = 'ua';
UPDATE tools SET best_for = 'Актуальна інформація, екосистема Google' WHERE slug = 'gemini' AND lang = 'ua';
UPDATE tools SET best_for = 'Автодоповнення, інтеграція з IDE' WHERE slug = 'github-copilot' AND lang = 'ua';
UPDATE tools SET best_for = 'Внутрішні інструменти, додатки на основі даних' WHERE slug = 'glide' AND lang = 'ua';
UPDATE tools SET best_for = 'Висока якість, реалістичне аудіо' WHERE slug = 'google-veo-3' AND lang = 'ua';
UPDATE tools SET best_for = 'Граматика, стиль, покращення тексту' WHERE slug = 'grammarly' AND lang = 'ua';
UPDATE tools SET best_for = 'Новини в реальному часі, інсайти з X/Twitter' WHERE slug = 'grok' AND lang = 'ua';
UPDATE tools SET best_for = 'Чітке письмо, читабельність, редагування' WHERE slug = 'hemingway-editor' AND lang = 'ua';
UPDATE tools SET best_for = 'Data science, командна аналітика' WHERE slug = 'hex' AND lang = 'ua';
UPDATE tools SET best_for = 'Аватари, дубляж, маркетинг' WHERE slug = 'heygen' AND lang = 'ua';
UPDATE tools SET best_for = 'Питання-відповіді з PDF, юридичні документи, наукові статті' WHERE slug = 'humata' AND lang = 'ua';
UPDATE tools SET best_for = 'Постери з текстом, типографіка' WHERE slug = 'ideogram' AND lang = 'ua';
UPDATE tools SET best_for = 'Маркетинговий контент, SEO-копірайтинг' WHERE slug = 'jasper' AND lang = 'ua';
UPDATE tools SET best_for = 'Аналіз CSV, візуалізація даних' WHERE slug = 'julius-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Репетиторство для K-12, математика, наука' WHERE slug = 'khanmigo' AND lang = 'ua';
UPDATE tools SET best_for = 'Довгі відео, фізика руху' WHERE slug = 'kling-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Ігрові ассети, фото товарів, персонажі' WHERE slug = 'leonardo-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Email-агенти, планування, боти підтримки' WHERE slug = 'lindy' AND lang = 'ua';
UPDATE tools SET best_for = 'Логотипи, брендинг для бізнесу' WHERE slug = 'looka' AND lang = 'ua';
UPDATE tools SET best_for = 'BI-дашборди, звітність, безкоштовна аналітика' WHERE slug = 'looker-studio' AND lang = 'ua';
UPDATE tools SET best_for = 'Full-stack додатки, MVP SaaS' WHERE slug = 'lovable' AND lang = 'ua';
UPDATE tools SET best_for = 'Реалістичне відео, 3D-сцени, Dream Machine' WHERE slug = 'luma-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Складні автоматизації, інтеграція додатків' WHERE slug = 'make' AND lang = 'ua';
UPDATE tools SET best_for = 'Автономні задачі, дослідження, програмування, веб-агенти' WHERE slug = 'manus' AND lang = 'ua';
UPDATE tools SET best_for = 'Соцмережі, повсякденні задачі, безкоштовний чат' WHERE slug = 'meta-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Windows, Office 365, повсякденні задачі' WHERE slug = 'microsoft-copilot' AND lang = 'ua';
UPDATE tools SET best_for = 'Корпоративні агенти, екосистема Microsoft' WHERE slug = 'microsoft-copilot-studio' AND lang = 'ua';
UPDATE tools SET best_for = 'Художнє мистецтво, фотореалізм' WHERE slug = 'midjourney' AND lang = 'ua';
UPDATE tools SET best_for = 'Автоматизація workflow, AI-пайплайни' WHERE slug = 'n8n' AND lang = 'ua';
UPDATE tools SET best_for = 'Аналіз PDF, резюме, питання-відповіді' WHERE slug = 'notebooklm' AND lang = 'ua';
UPDATE tools SET best_for = 'Нотатки, база знань, документи' WHERE slug = 'notion-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Прогнозування, ML без коду' WHERE slug = 'obviously-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Зустрічі, транскрипція, нотатки' WHERE slug = 'otter-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Дослідження, відповіді з джерелами' WHERE slug = 'perplexity' AND lang = 'ua';
UPDATE tools SET best_for = 'Домашні завдання з математики, покрокові рішення' WHERE slug = 'photomath' AND lang = 'ua';
UPDATE tools SET best_for = 'Короткі кліпи, креативні ефекти, соцмережі' WHERE slug = 'pika' AND lang = 'ua';
UPDATE tools SET best_for = 'Командні презентації, презентації стартапів' WHERE slug = 'pitch' AND lang = 'ua';
UPDATE tools SET best_for = 'Динамічні презентації, візуальний сторітелінг' WHERE slug = 'prezi' AND lang = 'ua';
UPDATE tools SET best_for = 'Парафраз, резюме, переписування' WHERE slug = 'quillbot' AND lang = 'ua';
UPDATE tools SET best_for = 'Тайм-менеджмент, AI для календаря' WHERE slug = 'reclaim-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'SVG-іконки, векторна графіка, бренд-ассети' WHERE slug = 'recraft-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Команди мульти-агентів, боти продажів і підтримки' WHERE slug = 'relevance-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'Wireframes для сайтів, дизайн у Figma і Webflow' WHERE slug = 'relume' AND lang = 'ua';
UPDATE tools SET best_for = 'Видалення фону, фото товарів, вирізки' WHERE slug = 'remove-bg' AND lang = 'ua';
UPDATE tools SET best_for = 'Програмування в хмарі, навчання, швидкі деплої' WHERE slug = 'replit' AND lang = 'ua';
UPDATE tools SET best_for = 'AI-таблиці, імпорт даних' WHERE slug = 'rows' AND lang = 'ua';
UPDATE tools SET best_for = 'Кінематографічне відео, професіонали' WHERE slug = 'runway' AND lang = 'ua';
UPDATE tools SET best_for = 'Академічний пошук, цитування' WHERE slug = 'semantic-scholar' AND lang = 'ua';
UPDATE tools SET best_for = 'SEO-дослідження, аналіз конкурентів' WHERE slug = 'semrush' AND lang = 'ua';
UPDATE tools SET best_for = 'Шаблони, Google Slides, PowerPoint' WHERE slug = 'slidesgo' AND lang = 'ua';
UPDATE tools SET best_for = 'Допомога з домашніми, усі предмети' WHERE slug = 'socratic-by-google' AND lang = 'ua';
UPDATE tools SET best_for = 'Клієнтські портали, внутрішні дашборди' WHERE slug = 'softr' AND lang = 'ua';
UPDATE tools SET best_for = 'Текст-у-відео, кінематографічні AI-кліпи' WHERE slug = 'sora' AND lang = 'ua';
UPDATE tools SET best_for = 'TTS, допомога в читанні, навчання, доступність' WHERE slug = 'speechify' AND lang = 'ua';
UPDATE tools SET best_for = 'Локальний запуск, повна кастомізація' WHERE slug = 'stable-diffusion' AND lang = 'ua';
UPDATE tools SET best_for = 'Швидка генерація музики' WHERE slug = 'suno' AND lang = 'ua';
UPDATE tools SET best_for = 'On-page SEO, оцінка контенту' WHERE slug = 'surferseo' AND lang = 'ua';
UPDATE tools SET best_for = 'Математика для K-8, навички розв''язання задач' WHERE slug = 'synthesis' AND lang = 'ua';
UPDATE tools SET best_for = 'BI, корпоративний, візуалізація' WHERE slug = 'tableau-ai' AND lang = 'ua';
UPDATE tools SET best_for = 'AI-презентації, сторітелінг' WHERE slug = 'tome' AND lang = 'ua';
UPDATE tools SET best_for = 'Музика з вокалом, повноцінні треки' WHERE slug = 'udio' AND lang = 'ua';
UPDATE tools SET best_for = 'Прототипи, wireframes, MVP' WHERE slug = 'uizard' AND lang = 'ua';
UPDATE tools SET best_for = 'UI-компоненти, React, прототипи' WHERE slug = 'v0-by-vercel' AND lang = 'ua';
UPDATE tools SET best_for = 'Маркетингові сайти, CMS, landing pages' WHERE slug = 'webflow' AND lang = 'ua';
UPDATE tools SET best_for = 'Транскрипція, субтитри' WHERE slug = 'whisper' AND lang = 'ua';
UPDATE tools SET best_for = 'Безкоштовний AI IDE, редагування кількох файлів, агентне програмування' WHERE slug = 'windsurf' AND lang = 'ua';
UPDATE tools SET best_for = 'SEO-статті, контент для соцмереж' WHERE slug = 'writesonic' AND lang = 'ua';
UPDATE tools SET best_for = 'Автоматизація, інтеграції без коду' WHERE slug = 'zapier-ai' AND lang = 'ua';

COMMIT;
