#!/usr/bin/env python3
"""Update EN content for design and chat categories."""
import urllib.request, json, os

SB_URL     = 'https://lbjdwkvkkndvofysyssy.supabase.co'
SB_SERVICE = os.environ.get('SB_SERVICE_KEY', '')
if not SB_SERVICE:
    print('ERROR: Set SB_SERVICE_KEY'); exit(1)

HDRS = {
    'apikey': SB_SERVICE,
    'Authorization': f'Bearer {SB_SERVICE}',
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

UPDATES = {
  # ── DESIGN ──────────────────────────────────────────────────────────────────
  'canva-ai': {
    'badge': 'freemium', 'users': '265M+',
    'best_for': 'AI-powered graphic design for non-designers and teams',
    'description': 'All-in-one design platform with AI tools for image generation, background removal, text effects, and layout suggestions. 265M monthly active users.',
    'description_long': "Canva is the world's most widely used design platform with 265 million monthly active users and 31 million paying subscribers. The AI features are grouped under Magic Studio — an umbrella that includes Dream Lab (image generation), Magic Write (AI copywriting), Magic Eraser (background removal), Magic Expand (outpainting), Magic Animate, and Magic Resize for adapting designs across formats.\n\nAs of 2026, AI usage in Canva is credit-based. The Free plan includes approximately 50 lifetime AI credits, which limits access to Dream Lab and other AI tools significantly. The Pro plan at $15 per month provides 500 AI credits per month along with full Magic Studio access. Teams plans at $30 per user per month offer higher credit limits. There is no credit top-up on Pro — users who exhaust their monthly allotment must upgrade to Teams.\n\nKey capabilities include drag-and-drop design, 600,000+ templates, AI image generation from text prompts, one-click background removal, AI-powered presentations, brand kits for teams, and direct social media publishing. The platform works entirely in the browser with no software installation required.\n\nPricing: Free plan includes 50 lifetime AI credits and basic design tools. Pro costs $15 per month (or $120 per year) with 500 monthly AI credits, premium templates, and brand kit. Teams is $30 per user per month with expanded credits and admin controls. Enterprise pricing is custom.\n\nLimitations: The credit-based model for AI features can be frustrating — 500 credits per month runs out quickly for heavy users. There is no standalone credit top-up on Pro. Canva's output is recognizable at a glance, which may not suit brands wanting highly unique visual identities.\n\nBest suited for marketers, social media managers, small business owners, and teams who need to create professional-looking designs quickly without hiring a graphic designer.",
    'pros': ['265M monthly users — largest design platform globally', 'Magic Studio bundles image gen, eraser, expand, animate, and resize in one place', '600,000+ templates covering social media, presentations, print, and video', 'Works entirely in browser — no software installation required', 'Brand kit and team features for consistent organizational design'],
    'cons': ['AI features are credit-limited — 500/month on Pro runs out quickly for heavy users', 'No credit top-up on Pro tier — must upgrade to Teams for more AI usage', 'Canva-style output is visually recognizable and may lack uniqueness', 'Advanced vector/print design workflows not as capable as Illustrator or Figma'],
  },
  'claude-design': {
    'badge': 'paid', 'users': 'from $20/mo',
    'best_for': 'AI-generated visual designs, presentations, and prototypes via conversation',
    'description': 'Anthropic Labs product that generates polished visual designs, presentations, and interactive prototypes from conversational prompts. Launched April 17, 2026. Included with Claude Pro and above.',
    'description_long': "Claude Design is a purpose-built AI design tool from Anthropic, launched on April 17, 2026 as a research preview under Anthropic Labs. It is a distinct product from general Claude — powered by Claude Opus 4.7 and specifically trained to generate polished visual output including presentations, one-pagers, slide decks, prototypes, and visual reports from natural language prompts.\n\nOn first run, Claude Design analyzes your codebase or design files to build a design system — extracting your brand colors, typography, and component patterns. Subsequent designs automatically conform to this system, producing consistent branded output without manual configuration. Exports are available as PDF, shareable URL, PPTX, or directly to Canva for further editing.\n\nKey capabilities include conversational design iteration (ask for changes in plain language), presentation generation, interactive prototype creation, one-pager and report design, and automatic brand system detection. The tool understands design intent rather than requiring precise specifications — describe what you need and it produces a complete visual.\n\nPricing: Claude Design is included with Claude Pro at $20 per month, Claude Max at $100 and $200 per month, Team plans, and Enterprise. It is not available on the Free tier. There is no standalone pricing — access requires an active Claude subscription.\n\nLimitations: As a research preview launched in April 2026, Claude Design is still maturing. Output quality can vary on complex multi-page layouts. It is not a replacement for professional design tools like Figma for UI/UX work — it excels at presentation and document design rather than interactive product design.\n\nBest suited for professionals who need polished presentations, reports, and one-pagers quickly without opening a design tool — particularly those already using Claude Pro for other work.",
    'pros': ['Generates complete visual designs from conversational prompts — no design skills needed', 'Automatically detects and applies your brand system (colors, typography, components)', 'Exports to PDF, URL, PPTX, or directly to Canva', 'Powered by Claude Opus 4.7 — understands design intent from natural language', 'Included with Claude Pro ($20/mo) — no separate subscription needed'],
    'cons': ['Research preview as of April 2026 — still maturing with variable output quality', 'Not available on Claude Free tier', 'Not a replacement for Figma or professional UI/UX design tools', 'No standalone pricing — requires active Claude subscription'],
  },
  'figma-ai': {
    'badge': 'freemium', 'users': '5M+',
    'best_for': 'AI-assisted UI/UX design and interactive prototyping inside Figma',
    'description': 'AI features natively integrated into Figma, including Figma Make for prompt-to-prototype generation, AI image generation, layer renaming, and code output. Free tier includes limited AI credits.',
    'description_long': "Figma AI refers to the suite of AI capabilities built directly into Figma's design platform, used by over 5 million active design professionals. The flagship AI feature is Figma Make — introduced in 2026 — which allows designers to describe a UI in natural language and receive a functional interactive prototype, complete with database connectivity via Supabase integration. This moves Figma from a static design tool toward an AI-native product development environment.\n\nFigma acquired Diagram (makers of the Magician AI plugin) and folded those capabilities into native Figma AI, including AI image generation and editing directly on the canvas, AI-powered layer renaming, intelligent component suggestions, and AI search across design assets. Code generation translates Figma designs into production-ready React, HTML, or CSS.\n\nKey capabilities include Figma Make (text to interactive prototype), AI image generation and editing, auto-layout suggestions, smart component matching, AI layer renaming, codebase-aware generation, and Supabase database connectivity for data-driven prototypes.\n\nPricing: Starter plan is free with limited monthly AI credits. Professional at $15 per user per month (annual) includes 500 AI credits per month. Organization at $55 per user per month includes 2,000 credits. Enterprise at $90 per user per month includes 4,250 credits. Additional AI credit packs and pay-as-you-go credits at $0.03 per credit are available from Q2 2026.\n\nLimitations: AI credits are consumed across all AI features and can run out quickly for teams doing heavy generative work. Figma Make outputs require developer review before production use. The platform is web-only, which can be slow on large complex files.\n\nBest suited for UI/UX designers and product teams who want AI assistance embedded in their existing Figma workflow, particularly for rapid prototyping and design-to-code output.",
    'pros': ['Figma Make generates functional interactive prototypes from text prompts', 'Native AI image generation and editing directly on the Figma canvas', 'Code generation outputs production-ready React, HTML, and CSS', 'AI layer renaming and component suggestions improve workflow speed', 'Acquired Diagram (Magician plugin) — capabilities now native, no plugin needed'],
    'cons': ['AI credits consumed across all features — 500/month on Professional runs out on heavy use', 'Additional credits cost $0.03 each — can add up for generative-heavy teams', 'Figma Make outputs require developer review before production deployment', 'Web-only platform can be slow on large complex design files'],
  },
  'framer-ai': {
    'badge': 'freemium', 'users': '1M+',
    'best_for': 'AI-generated websites with designer-quality output and CMS',
    'description': 'AI website builder that generates responsive, design-quality sites from text prompts. Includes AI Wireframer, AI Workshop coding assistant, and no-code CMS. Strong adoption among independent designers.',
    'description_long': "Framer is an AI-powered website builder popular among independent designers and design-focused teams. Unlike template-based builders, Framer generates sites with genuine design quality — custom layouts, fluid animations, and responsive breakpoints — that would typically require professional design work. The AI generates a complete site from a text description, which can then be customized in a visual editor.\n\nKey AI features include AI Wireframer for rapid layout generation, AI Workshop (a coding assistant for custom interactions and logic), AI-powered translation for multilingual sites, and integrations with OpenAI, Anthropic, and Gemini APIs as third-party plugin capabilities.\n\nThe platform handles hosting, CMS, and analytics. Sites are published to a Framer subdomain on the free plan or a custom domain on paid plans. Framer is particularly popular for portfolios, landing pages, product marketing sites, and startup websites where visual quality matters.\n\nPricing: Free plan includes full design tools and a Framer subdomain with a 'Made in Framer' badge. Basic at $10 per month (annual) or $15 per month adds a custom domain. Pro at $30 per month (annual) or $45 per month adds CMS, analytics, and password protection. Scale at $100 per month (annual) adds higher traffic limits and advanced CMS. Enterprise pricing is custom.\n\nLimitations: Framer is optimized for marketing sites — it is not suitable for complex web applications or e-commerce beyond basic storefronts. The visual editor has a learning curve compared to simpler builders like Squarespace. CMS capabilities are more limited than dedicated platforms like WordPress or Webflow.\n\nBest suited for designers, agencies, and startups who want to build visually exceptional marketing websites and portfolios without writing code.",
    'pros': ['Generates designer-quality websites from text prompts — not generic templates', 'AI Wireframer creates rapid layout structures for any content type', 'Full visual editor for customization after AI generation', 'Built-in hosting, CMS, and analytics on all paid plans', 'Popular among professional designers — strong output quality'],
    'cons': ['Not suitable for complex web apps or advanced e-commerce', 'Visual editor has a learning curve compared to simpler website builders', 'CMS less capable than WordPress or Webflow for content-heavy sites', 'Free plan shows a Framer badge on the site'],
  },
  'google-stitch': {
    'badge': 'free', 'users': '',
    'best_for': 'Free AI UI design and prototyping from text prompts, with infinite canvas',
    'description': 'Free Google Labs tool for AI-native UI design. Generates multi-screen app prototypes from text with voice input, infinite canvas, and interactive prototyping. Google acquired Galileo AI and rebranded it as Stitch.',
    'description_long': "Google Stitch is a free AI-native design tool from Google Labs, the result of Google's acquisition of Galileo AI in May 2025. It was significantly rebuilt and relaunched in March 2026 as a comprehensive AI design platform, now directly competing with Figma and Adobe in the AI-native design space.\n\nThe March 2026 update introduced Voice Canvas (speak directly to the design canvas for real-time critiques and edits), Vibe Design (objective-based generation that produces multiple design directions simultaneously), 5-screen multi-page generation from a single prompt, infinite canvas for large design systems, and interactive prototyping. Designs use DESIGN.md — a natural language design system format developed by Google — to maintain consistency across generated screens.\n\nKey capabilities include text-to-UI generation, voice interaction with the canvas, multi-directional design exploration, interactive prototyping, design system management via DESIGN.md, and export to standard formats.\n\nPricing: Completely free. The standard model provides 350 generations per month. An experimental model tier provides 50 generations per month for testing cutting-edge capabilities. No credit card required.\n\nLimitations: As a Google Labs experiment, Stitch may change significantly or be discontinued — Google has a history of sunsetting experimental products. The tool is newer than Figma or Adobe alternatives, with a smaller ecosystem of plugins, templates, and community resources.\n\nBest suited for designers and product teams who want to explore AI-native design without cost, and developers looking to quickly generate UI screens for prototyping before investing in detailed design work.",
    'pros': ['Completely free — 350 generations per month at no cost', 'Voice Canvas allows speaking directly to the design canvas for real-time edits', 'Multi-page generation creates 5 connected screens from a single prompt', 'Built by Google with Galileo AI technology — serious investment behind it', 'DESIGN.md format maintains visual consistency across generated designs'],
    'cons': ['Google Labs experiment — risk of discontinuation as with other Google products', 'Smaller ecosystem than Figma or Adobe — fewer plugins and community resources', 'Newer product with less mature tooling for professional production workflows', 'Experimental model limited to 50 generations per month'],
  },
  'looka': {
    'badge': 'paid', 'users': '2M+',
    'best_for': 'AI logo and brand identity generation for small businesses',
    'description': 'AI logo maker that generates brand identities from a few business details. One-time purchase model — pay per logo or annual Brand Kit subscription. Over 2 million businesses served.',
    'description_long': "Looka is an AI-powered logo and brand identity generator used by over 2 million businesses. Unlike subscription-based design tools, Looka uses a one-time purchase model for logos — you generate options for free, then pay only when you are ready to download the files you want to keep.\n\nThe logo generation process asks for business name, industry, style preferences, colors, and symbols, then produces dozens of options instantly. Logos are vector-based and fully customizable in Looka's editor before purchase. The Brand Kit subscription extends Looka beyond logos to produce business cards, email signatures, social media profiles, letterheads, and presentation templates — all automatically using your logo's design system.\n\nKey capabilities include AI logo generation from business details, color palette and font selection, a visual editor for customization, brand kit asset generation across 300+ branded materials, and an AI-generated website option on the top bundle.\n\nPricing: Logo generation is free to explore. Basic Logo download costs $20 one-time (low-resolution PNG only — not transparent, not vector — insufficient for professional use). Premium Logo costs $65 one-time and includes high-resolution files, vector formats (SVG, EPS, PDF), transparent background, and unlimited revisions. Brand Kit costs $96 per year and includes the full logo package plus branded templates for all business materials. Brand Kit + Website costs $129 per year and adds an AI-generated website.\n\nLimitations: The $20 Basic tier is misleading — it lacks transparency and vector formats needed for professional use. Premium at $65 is the practical minimum for real business use. Looka-generated logos are recognizable as AI-generated and may not work for brands needing highly unique visual identities.\n\nBest suited for freelancers, startups, and small businesses that need a professional logo and brand materials quickly without hiring a designer, accepting that output will follow established AI design patterns.",
    'pros': ['One-time purchase model — no recurring subscription required for logo ownership', 'Vector formats (SVG, EPS) included in Premium — usable for any application', 'Brand Kit generates 300+ branded materials from your logo automatically', 'Fast generation — dozens of logo options from a brief description in seconds', '2M+ businesses served — proven track record for small business branding'],
    'cons': ['$20 Basic tier lacks transparency and vector files — Premium at $65 is the real minimum', 'AI-generated logos follow recognizable patterns — may lack uniqueness for premium brands', 'Brand Kit requires annual subscription ($96/yr) on top of logo purchase', 'Not suitable for complex brand systems needing truly custom illustration or iconography'],
  },
  'relume': {
    'badge': 'freemium', 'users': '200K+',
    'best_for': 'AI sitemap and wireframe generation that exports to Webflow and Figma',
    'description': 'AI tool that generates website sitemaps and wireframes from a brief description, then exports directly to Webflow or Figma for development. Not a standalone builder — requires a separate Webflow or Figma subscription.',
    'description_long': "Relume is an AI-powered sitemap and wireframe generator built specifically for agencies and web designers who build sites in Webflow or design in Figma. The tool solves the early-stage planning problem: describe a website's purpose and audience, and Relume generates a full sitemap and then detailed wireframes for each page — ready to export and build on.\n\nThe component library contains over 1,000 pre-built Webflow and Figma components organized by section type (hero, features, pricing, FAQ, etc.). The AI sitemap generator produces a complete information architecture, and the AI wireframe tool populates pages with relevant components based on the site's goals. Both can be customized before export.\n\nKey capabilities include AI sitemap generation, AI wireframe generation with 1,000+ components, direct Webflow export (building blocks), Figma import, and mobile variant support on Pro.\n\nPricing: Free plan includes 30 Workflow components. Starter at approximately $32 per member per month includes the full 1,000+ component library, unlimited projects, AI sitemap and wireframe, and Figma and Webflow export. Pro at approximately $40 per member per month adds mobile variants, monthly library updates, and advanced collaboration. Annual billing provides approximately 15% discount. Note: Relume does not include Webflow or Figma subscriptions — users need active accounts on those platforms separately.\n\nLimitations: Relume is not a standalone website builder — it requires Webflow or Figma and the associated subscription costs. The tool solves planning and wireframing, not final design or development. The component library, while large, is Webflow/Figma-specific.\n\nBest suited for agencies, freelancers, and designers who already work in Webflow or Figma and want to accelerate the sitemap and wireframing phase of client projects.",
    'pros': ['AI generates complete sitemaps and wireframes from a one-paragraph description', '1,000+ component library covers every common website section type', 'Direct Webflow export and Figma import for seamless handoff', 'Significantly accelerates the planning phase of web projects', 'Mobile variants available on Pro for responsive design planning'],
    'cons': ['Not a standalone builder — requires separate Webflow or Figma subscriptions', 'Solves planning and wireframing only — not final design or development', 'Component library is Webflow/Figma-specific — no React or other framework output', 'Monthly cost adds on top of existing Webflow/Figma subscription costs'],
  },
  'remove-bg': {
    'badge': 'freemium', 'users': '150M+',
    'best_for': 'Instant AI background removal from photos and product images',
    'description': 'Industry-standard AI background removal tool. Processes images in 5 seconds with one click. API available for bulk and automated workflows. 150M+ images processed.',
    'description_long': "Remove.bg is the industry-standard tool for AI-powered background removal, owned by Kaleido AI. It processes any photo in approximately 5 seconds with a single click — no manual selection, masking, or design skills required. The service supports JPEG, PNG, WebP, and RAW formats up to 50MB, with output in transparent PNG.\n\nThe tool integrates across multiple surfaces: the web app at remove.bg, a desktop application for Windows, macOS, and Linux, mobile apps, a Figma plugin, a Photoshop plugin, Shopify and WooCommerce integrations, and a REST API for automated processing. The API supports bulk processing, making it practical for e-commerce operations removing backgrounds from thousands of product photos.\n\nKey capabilities include automatic subject detection (people, products, animals, cars), high-resolution output, batch processing via API, transparent background PNG output, and integrations with major design tools and e-commerce platforms.\n\nPricing: Free plan provides limited low-resolution preview images and a small number of free full-resolution credits. Pay-as-you-go starts at approximately $3 for a small credit pack. The Lite subscription at approximately $8.10 per month provides 40 full-resolution credits per month. Pro Volume+ plans scale up to $80.10 per month for 500 credits. Enterprise plans with custom API volume are available for high-throughput operations. Prices are EUR-denominated and may vary slightly by region.\n\nLimitations: Complex subjects with hair, fur, or transparent materials require manual touchup. Free credits are limited and the preview resolution is insufficient for professional use without purchasing. Credit costs add up quickly for high-volume e-commerce use.\n\nBest suited for e-commerce sellers, product photographers, and marketing teams who need to quickly remove backgrounds from product images at scale.",
    'pros': ['Industry-standard accuracy — processes any photo in 5 seconds automatically', 'API supports bulk processing for e-commerce and automated workflows', 'Integrates with Figma, Photoshop, Shopify, WooCommerce, and desktop apps', 'Handles people, products, animals, and cars with high accuracy', 'REST API makes it practical for high-volume product photography pipelines'],
    'cons': ['Complex subjects with hair, fur, or transparent materials may need manual touchup', 'Free tier provides only low-resolution previews — not usable for professional output', 'EUR-denominated credit costs add up quickly for high-volume use', 'Limited editing beyond background removal — just a focused single-function tool'],
  },
  'uizard': {
    'badge': 'freemium', 'users': '300K+',
    'best_for': 'AI UI prototyping from screenshots, sketches, and text prompts',
    'description': 'AI UI design and prototyping tool that converts screenshots, sketches, and text prompts into editable app mockups. Acquired by Miro in May 2024 — now operating as Uizard by Miro Labs.',
    'description_long': "Uizard is an AI-powered UI prototyping tool acquired by Miro in May 2024 and now operating as Uizard by Miro Labs. The tool converts screenshots of existing apps, hand-drawn sketches, and text descriptions into editable UI mockups — making it one of the fastest ways to go from idea to visual prototype without design skills.\n\nThe flagship feature is Autodesigner 2.0 (available on paid plans), which allows conversational section-by-section editing: describe a change to your design in plain language and Autodesigner applies it. This is more flexible than single-shot generation tools. Screenshot Scanner converts any app screenshot into an editable Uizard template in seconds, and Wireframe Scanner converts hand-drawn sketches into digital wireframes.\n\nKey capabilities include text-to-UI generation, screenshot-to-editable-template conversion, hand-drawn sketch recognition, conversational design editing (Autodesigner 2.0), interactive prototyping with click-through flows, and a component library for common UI elements.\n\nPricing: Free plan supports 3 projects and 5 screens per project, with 3 AI generations per month and access to Autodesigner 1.5 only. Pro at $12 per user per month (annual) provides 500 AI generations per month, 100 projects, the full template library, and Autodesigner 2.0. Business at $39 per user per month provides 5,000 AI generations per month and unlimited projects. Enterprise pricing is custom.\n\nLimitations: Autodesigner 2.0 — the most capable AI feature — requires a paid plan. Output at lower tiers can look generic. The Miro acquisition means the product roadmap may shift toward Miro's broader collaboration ecosystem, creating some uncertainty about standalone Uizard's development trajectory.\n\nBest suited for product managers, startup founders, and non-designers who need to quickly mock up app screens for stakeholder review or user testing without hiring a designer.",
    'pros': ['Converts any app screenshot into an editable UI template instantly', 'Hand-drawn sketch recognition translates paper wireframes to digital mockups', 'Autodesigner 2.0 enables conversational section-by-section design editing', 'Accessible to non-designers — no design skills required', 'Interactive prototyping with click-through flows for user testing'],
    'cons': ['Autodesigner 2.0 locked behind paid plan — free tier limited to older model', 'Output can appear generic without significant customization', 'Miro acquisition creates uncertainty about standalone Uizard roadmap', 'Limited component library compared to full design tools like Figma'],
  },
  'uxpilot': {
    'badge': 'freemium', 'users': '600K+',
    'best_for': 'AI UX design with wireframes, screen flows, and predictive heatmaps',
    'description': 'AI UX design assistant that generates UI screens, wireframes, and screen flows from text prompts with Figma export. Includes predictive heatmaps and code export.',
    'description_long': "UXPilot is an AI-powered UX design tool that generates wireframes, UI screens, and complete screen flows from text prompts. It targets UX designers and product teams who want to accelerate the wireframing phase without starting from a blank canvas. The Figma plugin integrates AI generation directly into existing Figma workflows.\n\nThe tool generates multiple screen variations from a single prompt, allowing designers to choose and iterate on the direction that fits best. Predictive heatmaps simulate where users are likely to look and click on a design — useful for validating layout decisions before user testing. Screen flow generation creates connected multi-screen prototypes from a feature description.\n\nKey capabilities include text-to-wireframe generation, UI screen generation, screen flow creation, predictive heatmap analysis, Figma plugin for in-editor generation, and code export for handoff to developers.\n\nPricing: Free plan supports up to 7 screens at a time with limited AI generations. Paid plans start at $14 per month for increased screen generation capacity and additional features. Higher tiers around $22 per month add team collaboration and higher usage limits. Pricing tiers are simpler than most competitors.\n\nLimitations: Free and basic paid plan feel limiting for serious professional use — the output quality and generation limits push users toward higher tiers quickly. Generated designs tend toward generic UI patterns and require customization to feel distinctive.\n\nBest suited for UX designers who want to accelerate wireframing and quickly generate multiple screen directions for stakeholder review, particularly those who already work in Figma.",
    'pros': ['Generates wireframes and full UI screens from text prompts quickly', 'Predictive heatmaps validate layout decisions before user testing', 'Figma plugin integrates AI generation into existing design workflows', 'Screen flow generation creates connected multi-screen prototypes automatically', 'Code export enables direct developer handoff'],
    'cons': ['Free and entry paid tiers feel limited for regular professional use', 'Generated designs lean toward generic UI patterns — customization needed', 'Smaller tool and community than Figma AI or Uizard', 'Predictive heatmaps are simulations, not data from real user behavior'],
  },

  # ── CHAT ─────────────────────────────────────────────────────────────────────
  'character-ai': {
    'badge': 'freemium', 'users': '20M+',
    'best_for': 'Conversational AI roleplay with custom characters',
    'description': 'The world\'s largest AI roleplay platform with 20M+ monthly active users and 10M+ characters. c.ai+ subscription at $9.99/mo removes ads and adds image generation.',
    'description_long': "Character.AI is the world's largest AI roleplay platform, with approximately 20 million monthly active users and over 10 million characters created by the community. Users can interact with characters built around fictional personas, celebrities, historical figures, or entirely original creations — with conversations that maintain character consistency across sessions.\n\nThe platform introduced full-screen interstitial ads for free users in early 2026, which became the most cited reason for user churn. Free tier users see ads between conversations; c.ai+ subscribers ($9.99/month) get an ad-free experience, priority response speed, and access to the Imagine Gallery image generator launched in March 2026. A Stories feature launched in November 2025 adds an adventure game format for character interactions.\n\nKey capabilities include multi-turn roleplay with consistent character personas, community character discovery, group conversations with multiple characters, voice mode, and image generation via Imagine Gallery on c.ai+.\n\nPricing: Free plan includes unlimited messaging with ad interruptions. c.ai+ costs $9.99 per month or approximately $7.92 per month billed annually ($94.99 per year) and removes ads, provides priority speed, and includes Imagine Gallery image generation.\n\nLimitations: The full-screen mid-conversation ads on the free tier are heavily criticized and disruptive. Character.AI has faced significant scrutiny over teenager safety — the platform has been sued over alleged harms to minors, and parental controls remain limited. The AI personas are fictional and not connected to real people.\n\nBest suited for fans of creative fiction, roleplay, and interactive storytelling who want to engage with custom AI personas across any character concept.",
    'pros': ['Largest AI roleplay platform — 20M+ MAU and 10M+ community-created characters', 'Consistent character personas across long multi-turn conversations', 'Group conversations with multiple characters simultaneously', 'c.ai+ subscription removes ads and adds Imagine Gallery image generation', 'Strong community for discovering popular characters across genres'],
    'cons': ['Free tier shows disruptive full-screen interstitial ads between conversations', 'Platform has faced serious safety scrutiny regarding younger users', 'AI personas are fictional — character consistency is simulated, not real', 'c.ai+ at $9.99/month is expensive relative to general-purpose AI alternatives'],
  },
  'chatgpt': {
    'badge': 'freemium', 'users': '1B+',
    'best_for': 'General-purpose AI assistant for writing, coding, analysis, and image generation',
    'description': 'OpenAI\'s flagship AI assistant with 1B+ monthly active users. Free and Go tiers include contextual ads (US, 2026). Plus $20/mo, Pro $100/mo, Pro $200/mo. GPT-5.5 is the current default model.',
    'description_long': "ChatGPT is the world's most widely used AI assistant, developed by OpenAI with over 1 billion monthly active users and 50 million paying subscribers as of 2026. The platform supports text generation, coding, data analysis, image creation (ChatGPT Images 2.0, launched April 2026), web browsing, file analysis, and voice conversation — all from a single interface.\n\nGPT-5.5 became the default model for all ChatGPT users on April 23, 2026, bringing significantly improved reasoning and instruction following. In February 2026, OpenAI introduced contextual advertising on the Free tier in the United States, followed by the Go tier ($8/month) — marking a major shift in the platform's monetization. Plus at $20/month remains ad-free. The Pro $100/month plan (launched April 9, 2026) provides 5x the usage limits of Plus. The Pro $200/month plan offers the highest limits.\n\nKey capabilities include multi-modal input (text, images, files, voice), GPT-5.5 reasoning, ChatGPT Images 2.0, web browsing, Python code execution, data analysis, custom GPTs (personal AI configurations), and the Canvas collaborative writing/coding mode.\n\nPricing: Free plan includes access to GPT-5.5 with ads (US). Go at $8/month includes higher limits with ads. Plus at $20/month is ad-free with full GPT-5.5 access and 50 image generations per day. Pro at $100/month provides 5x Plus limits. Pro at $200/month provides maximum limits. Team and Enterprise plans are available for organizations.\n\nLimitations: The introduction of ads on Free and Go tiers significantly reduced their value. Usage limits on Plus can be frustrating during peak hours. The breadth of features can make ChatGPT feel less specialized than tools purpose-built for coding (Claude Code) or research (Perplexity).\n\nBest suited for individuals and teams needing a versatile AI assistant across diverse tasks — writing, analysis, coding, image generation, and research — with the largest established model ecosystem.",
    'pros': ['1B+ monthly active users — the most widely adopted AI assistant globally', 'GPT-5.5 as the default model with strong reasoning and instruction following', 'Multi-modal: handles text, images, files, voice, code execution, and web browsing', 'ChatGPT Images 2.0 for high-quality AI image generation', 'Custom GPTs for personal AI configurations and specialized workflows'],
    'cons': ['Free and Go tiers now show contextual ads (US market, 2026)', 'Usage limits on Plus frustrating during peak hours', 'Less specialized than purpose-built tools for coding or deep research', 'Pro plans at $100–$200/month expensive for individual users'],
  },
  'claude': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI assistant for writing, analysis, coding, and agentic research tasks',
    'description': 'Anthropic\'s AI assistant with industry-leading safety and instruction following. Pro $20/mo includes Claude Code and Research mode; Max at $100/$200/mo for heavy users.',
    'description_long': "Claude is Anthropic's AI assistant, designed with a focus on safety, nuanced instruction following, and long-context reasoning. It is available via web, mobile, and desktop apps, and as an API. As of 2026, Claude Sonnet 4.6 is the standard model and Claude Opus 4.7 is the flagship — with Haiku 4.5 for lightweight tasks.\n\nSince 2025, Claude has expanded significantly: Claude Code (terminal coding agent) is included with Pro and above, Research mode enables multi-step deep research with citations, cross-conversation memory allows Claude to remember facts about you across sessions (Pro+), and integrations with Google Drive, Excel, and Chrome enable document and data work. The Model Context Protocol (MCP) enables Claude to connect to custom external tools.\n\nKey capabilities include long-document analysis (100K token context window), code writing and review, research synthesis with citations, multi-turn agentic workflows, Claude Code for autonomous coding, and voice mode on mobile. Claude is widely regarded as having the best instruction following and refusal behavior of any frontier model.\n\nPricing: Free plan includes access to Claude Sonnet and Haiku with daily usage limits. Pro at $20 per month (approximately $17 annual) provides Opus access, Claude Code, Research mode, memory, and 5x Free limits. Max at $100 per month provides approximately 5x Pro capacity. Max at $200 per month provides approximately 20x Pro capacity. Team at $30 per user per month is designed for organizations. Enterprise pricing is custom.\n\nLimitations: Pro plan limits can be reached quickly by heavy users who rely on Claude Code or Research mode. No user count is publicly disclosed. Anthropic's safety guidelines mean Claude declines more requests than some competitors — a feature for some users, a frustration for others.\n\nBest suited for professionals who prioritize instruction accuracy, safety, and nuanced long-form reasoning — writers, analysts, lawyers, researchers, and developers needing a trustworthy AI collaborator.",
    'pros': ['Best-in-class instruction following and nuanced long-form reasoning', 'Claude Code included with Pro — full terminal coding agent', 'Research mode for multi-step deep research with citations', 'Cross-conversation memory remembers facts about you across sessions (Pro+)', 'MCP support for connecting to custom external tools and data sources'],
    'cons': ['Pro plan limits reached quickly by heavy Claude Code or Research mode users', 'Max plans at $100–$200/month expensive for individual users', 'No publicly disclosed user count — less social proof than ChatGPT', 'Safety guidelines decline more requests than some competitors'],
  },
  'deepseek': {
    'badge': 'free', 'users': '',
    'best_for': 'Free AI chat with powerful reasoning and very low API costs',
    'description': 'Chinese AI assistant with a free consumer chat app and the lowest API prices among frontier models. DeepSeek V4 Pro at $1.74/M input tokens (75% discounted until May 31, 2026).',
    'description_long': "DeepSeek is a Chinese AI research lab that offers a free consumer chat interface at chat.deepseek.com alongside a low-cost API. The consumer product is free for everyday chat use, making it one of the most accessible frontier AI models globally. The API is the primary revenue source, priced significantly below competing frontier model APIs.\n\nDeepSeek V4 (the current generation as of May 2026) comes in two variants: V4 Flash at $0.14 per million input tokens and $0.28 per million output tokens, and V4 Pro at $1.74 per million input tokens and $3.48 per million output tokens (currently 75% discounted until May 31, 2026). Both models support a 1 million token context window and 384K maximum output tokens. New API accounts receive 5 million free tokens to start.\n\nKey capabilities include strong reasoning and code generation, very long context handling, Chinese and English proficiency at near-parity, and extremely low API costs that make it practical for high-volume applications.\n\nPricing: The consumer chat app at chat.deepseek.com is free. The API requires account creation and payment — pricing as above. There is no paid consumer subscription tier; monetization is API-only.\n\nLimitations: DeepSeek is a Chinese company subject to Chinese data laws — enterprise users with data privacy requirements should evaluate carefully. Anthropic publicly accused DeepSeek (among others) of systematic distillation of Claude models via fraudulent accounts in February 2026. The consumer product has periodic capacity issues during peak demand.\n\nBest suited for developers wanting very low-cost frontier model API access, and individuals who want free access to a capable reasoning model for personal chat use.",
    'pros': ['Consumer chat app is completely free with no usage limits for basic use', 'V4 Flash API at $0.14/M input tokens — among the lowest frontier model prices', '1 million token context window on both V4 Flash and V4 Pro', 'Strong reasoning and code generation capabilities at low cost', 'New API accounts get 5M free tokens to start'],
    'cons': ['Chinese company subject to Chinese data laws — enterprise privacy risk', 'Accused by Anthropic of model distillation via fraudulent accounts (Feb 2026)', 'No paid consumer tier — advanced features require API access', 'Periodic capacity issues on the free consumer chat during high demand'],
  },
  'gemini': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Google\'s AI assistant with deep Workspace integration and multimodal capabilities',
    'description': 'Google\'s flagship AI assistant with native integration across Google Workspace, Gmail, Drive, and YouTube. AI Plus $7.99/mo, AI Pro $19.99/mo, AI Ultra $249.99/mo. Powered by Gemini 3.1 Pro.',
    'description_long': "Gemini is Google's flagship AI assistant, available as a standalone app and deeply integrated across the entire Google ecosystem — Gmail, Docs, Drive, Sheets, Slides, YouTube, and Google Search. As of 2026, the current flagship model is Gemini 3.1 Pro, with Gemini 2.5 Flash available on the Free tier.\n\nGoogle restructured Gemini's pricing in January 2026. The AI Plus tier at $7.99 per month targets users who want more than the free tier without committing to the full Pro subscription. AI Pro at $19.99 per month provides access to Gemini 3.1 Pro with 1 million token context, 5TB Google Drive storage, and full Workspace AI integration. AI Ultra at $249.99 per month adds Deep Think reasoning, the Gemini Agent for autonomous task execution, and full Veo video generation. Business and Enterprise plans are available as Workspace add-ons at $14 and $30 per user per month.\n\nKey capabilities include Gemini 3.1 Pro reasoning, native integration with all Google Workspace apps (including real-time email drafting in Gmail and document editing in Docs), 1 million token context on Pro+, multimodal input (text, images, audio, video, files), and Veo video generation on Ultra.\n\nPricing: Free tier includes Gemini 2.5 Flash with 100 AI credits per month. AI Plus is $7.99/month. AI Pro is $19.99/month with Gemini 3.1 Pro and 5TB storage. AI Ultra is $249.99/month with all capabilities. Business $14/user/month and Enterprise $30/user/month as Workspace add-ons.\n\nLimitations: The value proposition depends heavily on how deeply embedded you are in Google's ecosystem. Gemini's AI Ultra tier at $249.99/month is among the most expensive in the market. The AI Pro subscription also bundles 5TB of Drive storage, which may be unnecessary for some users.\n\nBest suited for individuals and organizations heavily invested in Google Workspace who want AI that works natively within Gmail, Docs, Sheets, and Drive without switching between tools.",
    'pros': ['Native integration with Gmail, Docs, Drive, Sheets, Slides — works where you already are', 'Gemini 3.1 Pro with 1 million token context window on AI Pro and above', 'AI Ultra includes Veo video generation and Gemini Agent autonomous tasks', '5TB Google Drive storage bundled with AI Pro subscription', 'Best AI integration for Google Workspace power users'],
    'cons': ['Value heavily tied to Google ecosystem — less compelling for non-Workspace users', 'AI Ultra at $249.99/month is among the most expensive AI subscriptions available', '5TB Drive storage bundled with Pro may be unnecessary for some users', 'Gemini 2.5 Flash on free tier less capable than Pro models'],
  },
  'grok': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Real-time web search and AI reasoning integrated with X (Twitter)',
    'description': 'xAI\'s AI assistant with real-time web access via DeepSearch, integrated into X platform. Free for X users; SuperGrok Lite $10/mo, SuperGrok $30/mo with extended thinking and multi-modal capabilities.',
    'description_long': "Grok is the AI assistant developed by xAI (Elon Musk's AI company) and integrated into the X (formerly Twitter) platform. Unlike most AI assistants, Grok has real-time access to the web via DeepSearch, allowing it to answer questions about current events with live sources. Basic Grok access is free for all X users since Grok 3 launched in February 2025.\n\nThe 2026 pricing structure introduced multiple tiers. SuperGrok Lite at $10 per month (launched March 25, 2026) provides enhanced Grok access. SuperGrok at $30 per month or $300 per year provides DeepSearch, Big Brain extended thinking mode, voice mode, and 29 language support. X Premium at $8 per month and X Premium+ at $40 per month bundle X features with Grok access at different capability levels. SuperGrok Heavy at $300 per month provides the highest tier access. The API uses Grok 4 at $3.00 per million input tokens and $15.00 per million output tokens.\n\nKey capabilities include DeepSearch for real-time web research with citations, Big Brain extended thinking for complex reasoning tasks, voice mode, image generation, 29 language support, and native integration with X for social media context.\n\nPricing: Free for all X users (basic access). X Premium $8/month bundles X features. SuperGrok Lite $10/month for enhanced Grok. SuperGrok $30/month for full capabilities. X Premium+ $40/month. SuperGrok Heavy $300/month for maximum access.\n\nLimitations: The tiered pricing structure across X subscriptions and SuperGrok plans is confusing. The deepest capabilities require SuperGrok at $30/month on top of any X subscription. Grok's training data and safety approach differ from competitors like Claude or ChatGPT.\n\nBest suited for X power users who want real-time web search integrated with their social media workflow, and those who want an AI assistant with live internet access as a core feature.",
    'pros': ['DeepSearch provides real-time web access with live citations', 'Free basic access for all X users — lowest entry point of any frontier model', 'Big Brain extended thinking mode for complex multi-step reasoning', 'Native X integration provides social media context awareness', '29 language support across all SuperGrok tiers'],
    'cons': ['Pricing structure across X subscriptions and SuperGrok tiers is confusing', 'Full capabilities require $30/month SuperGrok on top of any X subscription costs', 'Training approach and safety standards differ significantly from Claude or ChatGPT', 'Heavily tied to X ecosystem — less valuable for non-X users'],
  },
  'meta-ai': {
    'badge': 'free', 'users': '3B+',
    'best_for': 'Free AI assistant built into Facebook, Instagram, WhatsApp, and Messenger',
    'description': 'Meta\'s free AI assistant powered by Llama 4, embedded across Facebook, Instagram, WhatsApp, and Messenger. Handles 10M business conversations per week on WhatsApp alone. Free with no subscription required.',
    'description_long': "Meta AI is the AI assistant developed by Meta, embedded across Facebook, Instagram, WhatsApp, Messenger, and available as a standalone app. It is powered by the Llama 4 model family — Meta's flagship open-weight models — and is completely free with no subscription required. Meta AI reaches the largest potential user base of any AI assistant by riding on Meta's 3 billion-user social media ecosystem.\n\nIn Q1 2026, Meta AI handled 10 million business conversations per week on WhatsApp alone, up from 1 million at the start of the year. Over 8 million advertisers use at least one Meta AI creative tool. The standalone Meta AI app competes directly with ChatGPT and Gemini as a general-purpose assistant, while the in-app integrations provide contextual AI help within each platform (generating image replies in Instagram DMs, helping draft responses in Messenger, answering questions in Facebook).\n\nKey capabilities include text generation, image generation (Imagine feature), web search integration, conversational AI in WhatsApp and Messenger, multilingual support, and creative tools for social media content.\n\nPricing: Meta AI is completely free. Meta is testing a paid Meta AI+ tier at approximately $20-30 per month that would gate advanced features, but as of May 2026 the core product remains free for all users with no announced launch date for the paid tier.\n\nLimitations: Meta AI's data practices are tied to Meta's broader advertising ecosystem — conversations may inform ad targeting. The assistant is less capable than frontier paid models (GPT-5.5, Claude Opus 4.7, Gemini 3.1 Pro) at complex reasoning tasks. Privacy-conscious users should review Meta's data policies before using.\n\nBest suited for casual AI assistance within Facebook, Instagram, WhatsApp, and Messenger — especially for users who want AI help without paying for a subscription.",
    'pros': ['Completely free — no subscription required for full access', 'Available natively in WhatsApp, Instagram, Facebook, and Messenger', 'Llama 4 provides capable general-purpose AI at no cost', 'Reaches 3B+ potential users through Meta\'s social media ecosystem', '8M+ advertisers already using Meta AI creative tools'],
    'cons': ['Data practices tied to Meta\'s advertising ecosystem — privacy considerations', 'Less capable than paid frontier models for complex reasoning tasks', 'In-app integrations vary significantly in capability across platforms', 'Standalone Meta AI app less polished than ChatGPT or Claude interfaces'],
  },
  'microsoft-copilot': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI assistant integrated across Microsoft 365, Teams, Word, Excel, and Outlook',
    'description': 'Microsoft\'s AI assistant powered by GPT and Gemini models. Free web chat at copilot.microsoft.com; Copilot Business $18-21/user/mo; Enterprise $30/user/mo with Researcher and Analyst agents.',
    'description_long': "Microsoft Copilot is Microsoft's AI assistant available as a free web experience at copilot.microsoft.com and as deep integrations across Microsoft 365 apps — Word, Excel, PowerPoint, Outlook, Teams, and more. The free consumer Copilot uses a mix of GPT-5.5 and Gemini models depending on the task, without requiring a Microsoft account.\n\nFor businesses, Copilot is licensed separately from Microsoft 365. Copilot Business provides AI assistance in all M365 apps, Copilot Chat for organizational knowledge queries, and business data protection. The May 2026 M365 E7 Frontier Suite at $99 per user per month bundles Microsoft 365 E5, Copilot, and Agent 365 for unified AI agent management across the organization. The Copilot Enterprise tier adds Researcher and Analyst agents that can autonomously conduct multi-hour research tasks and analyze complex datasets.\n\nKey capabilities include AI writing assistance in Word, formula generation and data analysis in Excel, presentation creation in PowerPoint, email drafting and meeting summaries in Outlook, meeting transcription and action items in Teams, and Researcher/Analyst autonomous agents on Enterprise.\n\nPricing: Free at copilot.microsoft.com for all users. Copilot Business at $18-21 per user per month (promotional pricing through June 2026, then $25.20 per month on monthly billing). Copilot Enterprise at $30 per user per month adds Researcher and Analyst agents, model choice, and Copilot Tuning. M365 E7 Frontier Suite at $99 per user per month bundles full stack.\n\nLimitations: The most powerful Copilot features require Microsoft 365 Business or Enterprise licenses in addition to the Copilot add-on — making total costs complex to calculate. The free tier at copilot.microsoft.com is capable but lacks the M365 integrations that differentiate Microsoft Copilot from other AI assistants.\n\nBest suited for organizations running Microsoft 365 who want AI embedded throughout their productivity suite — particularly for email, document creation, meeting summaries, and data analysis in Excel.",
    'pros': ['Native integration across Word, Excel, PowerPoint, Outlook, and Teams', 'Researcher and Analyst agents for autonomous multi-hour research and data analysis tasks', 'Free at copilot.microsoft.com for consumer use with no account required', 'Deepest Microsoft 365 integration of any AI tool — works where your data already lives', 'M365 E7 Frontier Suite bundles full AI + M365 stack for enterprise'],
    'cons': ['Full M365 integrations require M365 license plus Copilot add-on — costs stack up', 'Complex pricing across multiple tiers, licenses, and bundling options', 'Free consumer tier lacks the M365 app integrations that differentiate the product', 'Less capable at standalone creative tasks compared to ChatGPT or Claude'],
  },
  'mistral-le-chat': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Fast European AI assistant with strong privacy and multilingual capabilities',
    'description': 'European AI assistant by Mistral AI with the fastest inference of any frontier model (~1,000 words/sec). Pro $14.99/mo includes image generation, code interpreter, and agentic Work mode.',
    'description_long': "Mistral Le Chat is the consumer AI assistant from Mistral AI, a French AI company positioning itself as a privacy-respecting European alternative to US-based AI services. Le Chat runs on Mistral's own models and provides the fastest inference of any frontier AI assistant — approximately 1,000 words per second output speed, making it noticeably more responsive than ChatGPT or Claude for real-time conversation.\n\nThe 2026 version introduces Work mode — a multi-step agentic preview powered by Mistral Medium 3.5 that handles complex tasks requiring multiple reasoning steps. Image generation is powered by Black Forest Labs Flux Ultra. The code interpreter runs in a sandboxed environment for executing and testing code within the chat. Document uploads support PDFs, Word documents, and other formats for analysis.\n\nKey capabilities include very fast text generation, image generation via Flux Ultra, sandboxed code execution, document analysis, multilingual support across major European languages, and agentic Work mode for multi-step tasks.\n\nPricing: Free tier provides access to Mistral Medium and Small models with approximately 25 messages per day. Pro at $14.99 per month provides a soft cap of 150 messages and access to the full model suite including Mistral Large 3.5. A student discount reduces Pro to $7.04 per month with verification. Enterprise plans are available on request.\n\nLimitations: The message caps on both free and Pro tiers are restrictive compared to competitors like Claude or ChatGPT. Mistral's model suite, while very good, is less established than OpenAI's or Anthropic's for the most complex reasoning tasks. The agentic Work mode is still in preview as of 2026.\n\nBest suited for European users who prioritize data privacy and EU-jurisdiction data handling, and power users who value inference speed for rapid back-and-forth AI conversations.",
    'pros': ['Fastest inference of any frontier AI assistant — ~1,000 words/second output', 'European company with strong data privacy positioning — GDPR-compliant by default', 'Image generation via Black Forest Labs Flux Ultra on Pro', 'Code interpreter with sandboxed execution for testing code in-chat', 'Student discount reduces Pro to $7.04/month with academic verification'],
    'cons': ['Message caps on both free (~25/day) and Pro (soft 150 cap) are restrictive', 'Work mode agentic capabilities still in preview as of 2026', 'Model performance on complex reasoning slightly below OpenAI or Anthropic flagships', 'Smaller ecosystem and fewer integrations than ChatGPT or Claude'],
  },
  'perplexity': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI-powered search and research with real-time citations',
    'description': 'AI answer engine that combines real-time web search with frontier AI models, always citing sources. Pro $20/mo includes deep research, Perplexity Computer, and access to multiple AI models.',
    'description_long': "Perplexity is an AI answer engine that combines real-time web search with large language model reasoning, always providing cited sources for its answers. Unlike ChatGPT or Claude — which have knowledge cutoffs — Perplexity queries the live web for every response, making it particularly strong for current events, recent research, and fast-changing information.\n\nThe 2026 platform has expanded significantly beyond search. Perplexity Computer is an AI agent that operates a browser autonomously to complete multi-step web tasks. The Comet browser (Pro+) integrates Perplexity directly into web navigation. Labs generates dashboards, spreadsheets, and apps from natural language requests. The Agentic Research API enables developers to build applications on Perplexity's research capabilities.\n\nKey capabilities include real-time web search with citations, deep research reports (multi-source synthesis), Perplexity Computer for browser automation, Labs for generating structured outputs (dashboards, spreadsheets, apps), multiple AI model access (Claude, GPT-4o, Gemini on Pro), and a focus mode for specific source types.\n\nPricing: Free tier includes limited daily Pro queries. Pro at $20 per month provides unlimited Pro queries and 20 deep research queries per day. Max at $200 per month adds unlimited Labs access, Perplexity Computer with 10K credits per month, Comet browser, and frontier model access. Enterprise Pro at $40 per user per month adds SSO and 500 daily research queries. Enterprise Max at $325 per user per month provides maximum capabilities.\n\nLimitations: The depth of Perplexity's answers depends on what is publicly accessible on the web — it cannot access paywalled content or private databases. Deep research queries on Pro are limited to 20 per day. Max at $200/month is expensive for individual users.\n\nBest suited for researchers, journalists, analysts, and knowledge workers who need AI-assisted answers with verified, citable sources — particularly for questions requiring current information.",
    'pros': ['Real-time web search with citations on every response — no knowledge cutoffs', 'Deep research synthesizes multiple sources into comprehensive reports', 'Multiple AI model access on Pro — switch between Claude, GPT-4o, and Gemini', 'Perplexity Computer for autonomous browser-based task completion', 'Labs generates structured outputs (dashboards, spreadsheets, apps) from prompts'],
    'cons': ['Cannot access paywalled content or private databases', 'Deep research limited to 20 queries per day on Pro', 'Max plan at $200/month expensive for individual users', 'Answer quality depends on what is publicly available — weak on proprietary information'],
  },
}

def patch(slug, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        f'{SB_URL}/rest/v1/tools?slug=eq.{slug}&lang=eq.en',
        data=body, headers=HDRS, method='PATCH'
    )
    with urllib.request.urlopen(req) as r:
        return r.status

print(f'Updating {len(UPDATES)} tools...')
for slug, fields in UPDATES.items():
    status = patch(slug, fields)
    print(f'  {slug}: HTTP {status}')

print('Done.')
