#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Update EN content for marketing and research categories."""
import urllib.request, json, os

SB_URL     = 'https://lbjdwkvkkndvofysyssy.supabase.co'
SB_SERVICE = os.environ.get('SB_SERVICE_KEY', '')
if not SB_SERVICE:
    print('ERROR: Set SB_SERVICE_KEY'); exit(1)

HDRS = {
    'apikey': SB_SERVICE,
    'Authorization': f'Bearer {SB_SERVICE}',
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

UPDATES = {
  # ── MARKETING ─────────────────────────────────────────────────────────────────
  'adcreative-ai': {
    'badge': 'freemium', 'users': '2M+',
    'best_for': 'AI-generated ad creatives and social media visuals for performance marketing',
    'description': 'AI platform that generates conversion-optimized ad creatives, social media posts, and product photos. Acquired by Appier (Feb 2025). 2M+ users. Starter $39/mo, Professional $249/mo.',
    'description_long': "AdCreative.ai is an AI platform for generating conversion-optimized advertising creatives — display ads, social media posts, banners, and product photography. It was acquired by Appier, a Japanese AI marketing company, in February 2025, adding enterprise distribution and deeper data analytics to the platform. The service has over 2 million users ranging from individual dropshippers to enterprise brands.\n\nThe platform's core claim is performance prediction — it doesn't just generate creatives, it scores them for predicted conversion rate based on a proprietary model trained on advertising performance data. Users generate multiple variations and the platform surfaces the ones most likely to perform well before they spend on media.\n\nKey capabilities include AI ad creative generation across formats (Facebook, Google, banner ads), social media post generation, AI product photography (removing backgrounds and placing products in scenes), creative performance scoring, brand kit integration, and direct publishing integrations with Meta Ads and Google Ads.\n\nPricing: Starter at $39 per month provides 10 brand users and 500 downloads per month. Professional at $249 per month provides unlimited downloads and advanced analytics. Ultimate at $599 per month provides priority support and enterprise features. Enterprise pricing is custom. The Appier acquisition may result in pricing and feature changes over time.\n\nLimitations: Generated creatives often have a recognizable AI aesthetic that may not suit premium or luxury brand positioning. Performance scoring is predictive, not guaranteed — actual ad performance depends on audience targeting and campaign management. Starter plan's 500 downloads per month can be limiting for agencies managing multiple clients.\n\nBest suited for performance marketers, e-commerce brands, and digital agencies that run high-volume paid advertising campaigns and need to generate and test multiple creative variants quickly.",
    'pros': ['Performance scoring predicts conversion rate before spending on media', 'Generates creatives across Facebook, Google, banner, and social formats', 'AI product photography removes backgrounds and places products in lifestyle scenes', 'Direct publishing integrations with Meta Ads and Google Ads', '2M+ users with Appier acquisition adding enterprise distribution and analytics'],
    'cons': ['AI aesthetic recognizable — may not suit luxury or premium brand positioning', 'Performance scoring is predictive only — actual results depend on campaign execution', 'Starter plan 500 downloads/month limiting for agencies managing multiple clients', 'Acquisition by Appier may lead to pricing or product direction changes'],
  },
  'clearscope': {
    'badge': 'paid', 'users': '',
    'best_for': 'AI content optimization for SEO — targeting and topic depth scoring',
    'description': 'Content optimization platform that tells writers exactly what to cover for top Google rankings. AI Drafts generate SEO-optimized outlines. Essentials $129/mo, Business $399/mo. Used by enterprise content teams.',
    'description_long': "Clearscope is a content optimization platform that analyzes top-ranking Google search results for a target keyword and produces a weighted list of topics, subtopics, and terms the content must cover to rank competitively. The platform gives content a letter grade (A+ to F) based on how thoroughly it covers the topics present in ranking competitor content.\n\nIn 2024-2025, Clearscope added AI Drafts — AI-generated content outlines that incorporate the required topics and terms from the outset, reducing the time writers spend adding missing coverage after a first draft. The platform integrates with Google Docs and WordPress, enabling writers to receive real-time scoring feedback as they write without switching tools.\n\nKey capabilities include SERP analysis for target keywords, weighted term and topic recommendations, letter-grade content scoring, AI Drafts for pre-optimized outlines, Google Docs and WordPress integrations, competitor content analysis, and content inventory auditing.\n\nPricing: There is no free plan. Essentials at $129 per month provides 100 content reports per month and 1 user seat. Business at $399 per month provides 300 reports per month, 5 user seats, and advanced features. Enterprise pricing is custom for large teams with volume requirements.\n\nLimitations: At $129/month minimum with no free trial, Clearscope is a significant investment that requires active content production to justify. The platform optimizes for search engine ranking criteria — which may lead to technically complete but mechanically written content if not managed carefully. SEO-optimized content has diminishing returns as AI-generated search results change the landscape.\n\nBest suited for enterprise content teams, agencies, and mid-size businesses that produce regular long-form SEO content and need data-driven guidance on topic coverage to rank competitively.",
    'pros': ['Data-driven topic recommendations based on analysis of actual top-ranking content', 'Letter-grade scoring gives clear, actionable feedback on content completeness', 'AI Drafts generate pre-optimized outlines reducing post-draft revision time', 'Google Docs and WordPress integrations enable real-time scoring while writing', 'Content inventory auditing identifies underperforming existing content to improve'],
    'cons': ['$129/month minimum with no free trial — high commitment before testing value', 'Optimization focus can produce mechanically complete but creatively flat content', 'SEO optimization value decreasing as AI search (ChatGPT, Perplexity) changes user behavior', 'Business plan required for team use — $399/mo for 5 seats'],
  },
  'copy-ai': {
    'badge': 'freemium', 'users': '17M+',
    'best_for': 'AI content generation and GTM workflow automation for marketing teams',
    'description': 'AI content platform for marketing copy and GTM workflow automation. 17M users. Free 2K words/mo; Pro $36/mo; Agents $249/mo. Pivoting toward enterprise GTM automation beyond individual writing.',
    'description_long': "Copy.ai is an AI content and GTM (go-to-market) automation platform with 17 million users. Originally known as a quick AI copywriting tool for marketers, it has been pivoting toward workflow automation — building multi-step AI workflows that automate repetitive GTM tasks like content creation, lead enrichment, and sales outreach at scale.\n\nThe platform's content generation features cover a broad range of marketing use cases: blog posts, social media captions, email subject lines, ad copy, product descriptions, and more. The GTM AI Workflows enable connecting multiple AI steps into automated sequences — for example, pulling a lead from a CRM, researching their company, generating personalized outreach copy, and logging the activity automatically.\n\nKey capabilities include AI content generation for 90+ use cases, GTM Workflow automation, brand voice training, team collaboration features, API access, and integrations with HubSpot, Salesforce, and Zapier.\n\nPricing: Free plan provides 2,000 words per month and limited workflow access. Pro at $36 per month provides 10 seats, unlimited content generation, and 2,000 workflow credits. Agents at $249 per month provides full GTM workflow automation, unlimited credits, and priority support. Enterprise pricing is custom.\n\nLimitations: The 2,000 words/month free tier is restrictive for regular use. The GTM automation positioning places Copy.ai in direct competition with more established workflow tools (Zapier, Make) and enterprise GTM platforms (Outreach, Salesloft). Content quality for nuanced or technically complex topics requires significant editing.\n\nBest suited for marketing teams who need fast, volume content generation for standard marketing formats and are interested in automating repetitive GTM tasks with AI — particularly for outreach and lead enrichment workflows.",
    'pros': ['17M users — largest user base among AI marketing content platforms', 'GTM Workflow automation handles multi-step lead enrichment and outreach sequences', 'Free plan available — 2K words/month for light use or testing', 'Pro at $36/mo provides 10 seats — excellent value for small teams', 'Broad content generation coverage — 90+ templates for marketing use cases'],
    'cons': ['Free tier 2K words/month insufficient for regular content production', 'GTM automation capabilities less mature than dedicated workflow tools (Zapier, Make)', 'Content quality for technical or nuanced topics requires significant editing', 'Agents plan at $249/mo expensive relative to GTM automation alternatives'],
  },
  'frase': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI SEO content creation with topic research and AI visibility tracking',
    'description': 'SEO content tool that researches topics, creates AI-powered content briefs, and now tracks AI visibility in ChatGPT, Perplexity, Claude, and Gemini. Basic $39/mo annual; Pro ~$98/mo.',
    'description_long': "Frase is an SEO content creation platform that combines keyword research, competitor content analysis, AI writing, and content optimization into one workflow. Users start by entering a target keyword; Frase analyzes the top 20 search results, extracts the key topics and questions those pages cover, and generates an SEO brief. AI writing then generates content directly aligned with the brief.\n\nIn 2025-2026, Frase expanded into AI visibility tracking — monitoring whether your brand or content appears in AI-generated answers from ChatGPT, Perplexity, Claude, and Gemini. This positions Frase at the intersection of traditional SEO and the emerging GEO (Generative Engine Optimization) space.\n\nKey capabilities include keyword SERP analysis, competitor content topic extraction, AI content brief generation, AI article writing, content optimization scoring, AI answer engine visibility tracking (ChatGPT, Perplexity, Claude, Gemini), internal linking suggestions, and team collaboration.\n\nPricing: Basic at $39 per month (annual billing) provides 30 search queries per month and access to all core features. Solo at $49 per month includes a writer seat. Team at approximately $98 per month provides 80 queries and multiple seats. The paid plans include AI writing and optimization features. There is a limited free trial.\n\nLimitations: The 30 queries per month limit on Basic restricts output volume for content agencies or teams producing large volumes of content. AI writing quality is good for generic topics but requires significant editing for specialized, technical, or opinion-driven content. The AI visibility tracking feature is newer and less mature than the core SEO tooling.\n\nBest suited for in-house SEO teams, content managers, and small agencies that want to streamline the research-to-draft content creation workflow and track performance across both traditional search and AI answer engines.",
    'pros': ['Combines topic research, content brief generation, AI writing, and optimization in one workflow', 'AI answer engine visibility tracking across ChatGPT, Perplexity, Claude, and Gemini', 'Competitor content analysis identifies topic gaps and opportunities', 'Basic plan at $39/mo (annual) is affordable for individuals and small teams', 'Content optimization scoring shows what needs improvement for target keywords'],
    'cons': ['30 queries/month on Basic limits output for agencies and high-volume teams', 'AI writing quality requires editing for technical, specialized, or opinion content', 'AI visibility tracking feature newer — less mature than core SEO tooling', 'Annual commitment required for best pricing'],
  },
  'semrush': {
    'badge': 'paid', 'users': '1.16M+',
    'best_for': 'All-in-one SEO and competitive intelligence platform for digital marketers',
    'description': 'The comprehensive SEO and digital marketing platform with keyword research, competitor analysis, site audits, and content tools. Pro $139.95/mo, Guru $249.95/mo. 1.16M paying users.',
    'description_long': "Semrush is the leading all-in-one digital marketing platform, used by 1.16 million paying subscribers for SEO, paid advertising research, content marketing, social media management, and competitive intelligence. It is the most comprehensive single tool for understanding search visibility — covering keyword research, competitor analysis, backlink auditing, site health, and content optimization in one platform.\n\nThe 2025-2026 Semrush One bundle at $199 per month consolidates SEMrush, Semrush Social, and ContentShake AI into a single subscription, simplifying the cost for teams that need multiple tool categories. AI features embedded in the platform include AI-generated content briefs, AI writing (ContentShake AI), AI SEO recommendations, and generative AI answer visibility tracking.\n\nKey capabilities include keyword research with 25B+ keyword database, competitor organic and paid search analysis, backlink analysis, technical site audit, position tracking, content gap analysis, AI content writing (ContentShake AI), social media management, local SEO, and market intelligence.\n\nPricing: Pro at $139.95 per month provides core SEO tools for one user and 5 projects. Guru at $249.95 per month adds historical data, extended limits, and ContentShake AI. Business at $499.95 per month provides API access and white-label reports. Semrush One at $199 per month bundles Semrush, Social, and ContentShake AI. Annual billing provides approximately 17% savings.\n\nLimitations: Semrush is expensive — $139.95/month minimum with no meaningful free tier for professional use. The breadth of tools can feel overwhelming without dedicated SEO staff to use them effectively. For small businesses or individuals, tools like Ahrefs Starter or Ubersuggest may provide sufficient capability at lower cost.\n\nBest suited for in-house SEO teams, digital marketing agencies, and mid-to-large businesses that need comprehensive search visibility data and are willing to invest in a professional SEO platform.",
    'pros': ['Most comprehensive SEO platform available — keyword research, audit, backlinks, content in one', '25B+ keyword database with competitive intelligence across organic and paid search', 'Semrush One bundle at $199/mo consolidates Social and ContentShake AI tools', 'AI content writing and SEO recommendations integrated alongside data', '1.16M paying users — most widely adopted professional SEO tool'],
    'cons': ['$139.95/month minimum — high cost with no adequate free tier for professional use', 'Breadth of tools can overwhelm teams without dedicated SEO expertise', 'Pro plan limits (5 projects, restricted reports) push most teams to Guru at $249.95/mo', 'Annual commitment required for best pricing rates'],
  },
  'surfer-seo': {
    'badge': 'paid', 'users': '150K+',
    'best_for': 'AI SEO content optimization and writing with real-time SERP analysis',
    'description': 'SEO content editor that scores content against top-ranking pages in real time. ANNUAL-ONLY since 2026 — no monthly option. Discovery $49/mo, Standard $99/mo, Pro $182/mo annual. No free trial.',
    'description_long': "Surfer SEO is a content optimization and writing platform that provides real-time guidance on how to write content that ranks in Google. The core editor shows a live optimization score as writers work, based on analysis of the top-ranking pages for a target keyword — covering word count, heading structure, keyword usage, and semantic terms to include.\n\nSurfer AI combines content brief generation, AI writing, and optimization scoring in one workflow. Users can generate a full SEO article draft directly in Surfer that starts with an optimized structure, then edit and expand it with the optimization score guiding revisions. Surfer also includes keyword clustering (Keyword Surfer), domain audit, content planning, and SERP analyzer tools.\n\nKey capabilities include real-time content optimization scoring, AI article generation, keyword clustering and planning, domain content audit, SERP analyzer, topical authority planning, internal link suggestions, and integrations with Google Docs, WordPress, and Jasper.\n\nPricing: As of 2026, Surfer offers annual-only pricing — monthly subscriptions have been discontinued. Discovery at $49 per month (annual, paid upfront) provides 10 content editor uses per month. Standard at $99 per month (annual) provides 20 content editors. Scale Pro at $182 per month (annual) provides 40 editors. There is no free trial. A full year must be purchased upfront.\n\nLimitations: Annual-only pricing with no monthly option and no free trial represents a significant commitment before testing value. The $49-182/month range requires an active content production commitment to justify. Content optimization score can encourage keyword stuffing if writers optimize for score rather than reader experience.\n\nBest suited for dedicated content marketing teams and SEO agencies that produce regular long-form content and have already validated SEO content as a channel — annual-only pricing requires that commitment.",
    'pros': ['Real-time optimization scoring shows exactly what to improve while writing', 'AI article generation produces content starting from an optimized structure', 'Keyword clustering helps plan topical authority content calendars', 'Domain audit identifies optimization opportunities across existing content', 'Integrations with Google Docs, WordPress, and Jasper for flexible workflow'],
    'cons': ['Annual-only pricing since 2026 — no monthly option, no free trial', 'Full year must be paid upfront — significant commitment before testing value', 'Optimization-focused writing can produce keyword-heavy content that reads mechanically', 'Scale Pro at $182/mo expensive for smaller content teams'],
  },

  # ── RESEARCH ──────────────────────────────────────────────────────────────────
  'consensus': {
    'badge': 'freemium', 'users': '1M+',
    'best_for': 'AI search across 220M+ academic papers with consensus-finding summaries',
    'description': 'Academic search engine that finds and synthesizes scientific evidence across 220M+ research papers. Free limited; Pro $15/mo; Teams $9.99/seat/mo. Best for medical, scientific, and policy questions.',
    'description_long': "Consensus is an AI-powered academic search engine that searches over 220 million research papers and synthesizes what the scientific literature says about a specific question. Unlike Google Scholar (which returns a list of papers), Consensus extracts the key finding from each paper and generates a Consensus Meter — an aggregate view of whether the literature supports, contradicts, or is mixed on a specific claim.\n\nThe platform is designed for researchers, students, and evidence-based professionals who need to quickly determine what peer-reviewed science says on a topic without reading dozens of papers. Each result shows the paper, the methodology, the sample size, and the direction of the finding — with AI-generated summaries for each paper.\n\nKey capabilities include natural language academic search, Consensus Meter (visual synthesis of what research says), per-paper AI summaries, study snapshot cards (methodology, sample, finding), citation export, filter by study type (RCT, meta-analysis), and search across 220M+ papers from PubMed, Semantic Scholar, and other databases.\n\nPricing: Free plan provides limited searches per day with basic features. Pro at $15 per month provides unlimited searches, advanced filters, and GPT-4 Synthesis (AI-generated comprehensive summaries). Teams at $9.99 per seat per month provides shared workspace and team features. Academic institutions can access through institutional licenses.\n\nLimitations: Consensus is strongest for empirical research questions in health, science, and social science. It is less useful for historical, legal, or humanities research where peer-reviewed papers are not the primary evidence source. Coverage is biased toward English-language literature. The Consensus Meter simplifies complex scientific debates.\n\nBest suited for medical professionals, researchers, evidence-based policy professionals, and students who need to quickly survey the scientific literature on specific questions with AI-generated synthesis.",
    'pros': ['Searches 220M+ peer-reviewed papers — vastly larger than most academic tools', 'Consensus Meter synthesizes whether research supports or contradicts a claim', 'Per-paper AI summaries extract key findings without reading full papers', 'Filter by study type (RCT, meta-analysis) for evidence quality assessment', 'Teams plan at $9.99/seat/mo affordable for research groups'],
    'cons': ['Less useful for humanities, historical, or legal research domains', 'Biased toward English-language literature', 'Consensus Meter oversimplifies complex scientific debates to a simple metric', 'Free daily search limit too restrictive for active researchers'],
  },
  'elicit': {
    'badge': 'freemium', 'users': '2M+',
    'best_for': 'AI research assistant for systematic literature review and paper analysis',
    'description': 'AI research tool used by 2M+ researchers for systematic literature review. Finds, summarizes, and extracts data from academic papers. Free 2 reports/mo; Plus ~$10/mo; Pro ~$42/mo.',
    'description_long': "Elicit is an AI research assistant designed for systematic literature review — the process of comprehensively finding, evaluating, and extracting information from academic papers on a specific research question. It is used by over 2 million researchers and has become a standard tool for academic and professional research workflows.\n\nElicit's core workflow is more structured than a search engine: users define a research question, Elicit finds relevant papers, and then allows users to extract specific columns of information from each paper (methodology, population, outcomes, limitations). This turns a literature review into a structured table rather than a pile of links — enabling rapid synthesis across dozens or hundreds of papers.\n\nKey capabilities include semantic search across 100M+ papers, structured data extraction into tables, AI paper summaries, PDF upload and analysis, citation export (RIS, BibTeX), multiple evidence extraction columns (methodology, sample size, findings), automation for recurring reviews, and API for research workflow integration.\n\nPricing: Free plan provides 2 research reports per month and limited features. Plus at approximately $10 per month provides 15 reports per month and full data extraction. Pro at approximately $42 per month provides 50 reports per month, automation, and API access. Team plans at approximately $79 per month add collaboration features.\n\nLimitations: Elicit's structured extraction is powerful for quantitative research but less useful for qualitative analysis where insights are contextual rather than extractable. Report limits on lower tiers constrain usage for high-volume researchers. The platform is best for empirical research — humanities and social science literature is less well-served.\n\nBest suited for academic researchers, graduate students, and evidence-based professionals who need to conduct or update systematic literature reviews efficiently.",
    'pros': ['Structured data extraction turns paper lists into organized tables of findings', '2M+ researchers have validated it as a standard systematic review tool', 'PDF upload enables analysis of papers not in the database', 'Automation for recurring research questions that need periodic literature updates', 'Pro API access enables integration into custom research workflows'],
    'cons': ['Report limits on Free (2/mo) and Plus (15/mo) restrict high-volume researchers', 'Less useful for qualitative research where insights are contextual', 'Strong bias toward quantitative empirical research — humanities less well-served', 'Pro at $42/mo and Team at $79/mo expensive for academic budgets'],
  },
  'humata': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI document Q&A — ask questions about PDFs and research papers',
    'description': 'AI tool for asking questions about PDF documents, research papers, and long files. Free 60 pages/mo; Student $1.99/mo; Expert $9.99/mo; Team $99/mo for unlimited pages.',
    'description_long': "Humata is an AI document question-and-answer tool that allows users to upload PDF files — research papers, legal documents, reports, textbooks — and ask natural language questions about the content. The AI reads and understands the documents and answers questions with citations pointing to the specific sections that contain the relevant information.\n\nThe tool is used across research, legal, finance, and education for extracting specific information from long documents without reading them in full. Users can compare multiple documents, generate summaries, extract key terms, and get answers to highly specific questions that would require extensive manual search in traditional document review.\n\nKey capabilities include PDF upload and natural language Q&A, citation-backed answers linking to source sections, multi-document comparison, AI summarization, key term extraction, and document search.\n\nPricing: Free plan provides 60 pages of document processing per month. Student at $1.99 per month provides 200 pages per month — excellent value for students. Expert at $9.99 per month provides 1,000 pages per month. Team at $99 per month provides 10 team seats and unlimited pages.\n\nLimitations: Humata is specialized for document Q&A — it is not a general research tool and doesn't search external databases. Quality of answers depends on the quality and structure of the uploaded PDF. Complex tables, charts, and equations in PDFs may not be extracted accurately. The free tier's 60-page limit is quickly exhausted with even a single research paper upload.\n\nBest suited for law students, researchers, and professionals who regularly work with long PDFs and want to quickly find specific information without manual reading — particularly for due diligence, literature review, and document-heavy workflows.",
    'pros': ['Citation-backed answers point to exact sections in the document', 'Student plan at $1.99/mo is the most affordable AI document tool available', 'Multi-document comparison for parallel analysis', 'Works with any PDF — research papers, legal documents, reports, textbooks', 'Expert plan at $9.99/mo provides 1,000 pages — sufficient for most individual needs'],
    'cons': ['Free tier only 60 pages/month — exhausted by a single long research paper', 'Specialized for uploaded PDFs only — no external database search', 'Complex tables, equations, and charts may not extract accurately', 'Team plan at $99/mo expensive for unlimited pages relative to competitors'],
  },
  'notebooklm': {
    'badge': 'freemium', 'users': '10M+',
    'best_for': 'AI research notebook — ask questions and generate Audio Overviews from your sources',
    'description': 'Google\'s AI research notebook. Upload your own sources — PDFs, YouTube, web pages, Docs — then ask questions, get summaries, and generate Audio Overviews (podcast-style audio). Free; Plus $19.99/mo.',
    'description_long': "NotebookLM is Google's AI research and note-taking tool that allows users to upload their own sources — PDFs, YouTube videos, Google Docs, web pages, and audio files — and then ask questions, generate summaries, and create structured notes grounded in those specific sources. All AI responses cite the exact location in the source material, making it reliable for research without hallucinated citations.\n\nThe signature feature is Audio Overview — NotebookLM generates a podcast-style discussion between two AI hosts that explains and discusses the content of the uploaded sources. Users can also request specific output formats: study guides, briefing documents, FAQ pages, and structured summaries. In March 2026, Google launched Classroom Integration for NotebookLM and introduced a 50% student discount on the Plus plan.\n\nKey capabilities include multi-format source upload (PDF, YouTube, Google Docs, web pages, audio), cited Q&A grounded in uploaded sources, Audio Overview generation, study guide and briefing document generation, FAQ creation from sources, cross-source synthesis, and Classroom integration.\n\nPricing: Free tier provides significant capability including Audio Overviews and all core features with limits on notebook count and sources per notebook. Plus at $19.99 per month (Google One AI Premium, which also includes Gemini AI Pro) provides expanded limits, longer Audio Overviews, and customization options. Student discount of 50% applies with verification.\n\nLimitations: NotebookLM is limited to information in uploaded sources — it cannot search the web or access external databases. The free tier source and notebook limits can be restrictive for large research projects. Audio Overviews are informative but cannot be interacted with (no pause and ask follow-up questions during playback).\n\nBest suited for students, researchers, and knowledge workers who work from their own document collections and want an AI that understands and cites those specific sources — rather than a general web search tool.",
    'pros': ['All answers cite exact source locations — highly reliable for research use', 'Audio Overview generates podcast-style discussions of uploaded content', 'Completely free with significant capability — Audio Overviews, Q&A, study guides', 'Works from any format — PDF, YouTube, web pages, Google Docs, audio', 'Student discount (50%) and Classroom integration for educational use'],
    'cons': ['Limited to uploaded sources only — cannot search the web', 'Free tier limits notebook count and sources per notebook', 'Audio Overviews cannot be interrupted for follow-up questions during playback', 'Plus plan bundled with Google One AI Premium ($19.99/mo) — may be unwanted if only need NotebookLM'],
  },
  'scite': {
    'badge': 'freemium', 'users': '2M+',
    'best_for': 'Academic research with smart citations — see if papers support or contradict each other',
    'description': 'Academic research tool with 1.6B+ citation relationships showing whether papers support, mention, or contradict each other. 2M users. From $7.99/mo annual. Essential for evaluating scientific claims.',
    'description_long': "Scite is a research tool that analyzes over 1.6 billion citation relationships across academic literature to classify them as supporting, mentioning, or contrasting. Rather than just showing that Paper B cites Paper A, Scite shows whether Paper B's citation of Paper A agrees with, simply mentions, or disputes Paper A's claims. This makes it possible to evaluate the strength and direction of scientific evidence quickly.\n\nThe Smart Citations technology processes the context around each citation in 214 million papers, extracting the statement and classifying the citation relationship. When you look up a paper in Scite, you see at a glance how many other papers support it versus how many contradict it — critical information for evaluating whether a finding has held up over time.\n\nKey capabilities include smart citation analysis (supporting vs. contrasting vs. mentioning), natural language search across 214M+ papers, claim verification against the literature, citation search (find all papers citing a specific claim), integration with Zotero and Mendeley, custom dashboards, and PDF uploading for citation analysis.\n\nPricing: Free trial is available with limited features. Plans start from $7.99 per month (annual billing). Individual plans provide full smart citation access. The institutional pricing serves universities and research organizations at custom rates based on user count.\n\nLimitations: Coverage is biased toward biomedical and natural sciences — social sciences and humanities have less complete coverage. The classification of citations as supporting or contrasting requires reading context and can occasionally miscategorize ambiguous citations. Database size (214M papers) is smaller than Semantic Scholar (220M) but the citation classification adds significant unique value.\n\nBest suited for biomedical researchers, scientists, and evidence-based practitioners who need to quickly assess whether a specific scientific claim has been replicated or challenged in subsequent literature.",
    'pros': ['1.6B+ citation relationships classified as supporting, mentioning, or contrasting', 'Instantly shows whether a paper\'s findings have been supported or refuted by subsequent research', 'Smart citation context extraction identifies the exact statement being cited', 'Integration with Zotero and Mendeley for existing reference management workflows', '2M users with strong adoption in biomedical and scientific research'],
    'cons': ['Coverage biased toward biomedical and natural sciences — limited humanities coverage', 'Citation classification can occasionally miscategorize ambiguous statements', 'Database (214M papers) smaller than Semantic Scholar, though citation data adds unique value', 'Pricing not publicly detailed beyond starting rate — requires sign-up to see full options'],
  },
  'semantic-scholar': {
    'badge': 'free', 'users': '',
    'best_for': 'Free academic search engine with AI-powered paper summaries across 214M+ papers',
    'description': 'Free AI-powered academic search engine from the Allen Institute for AI with 214M+ papers. AI-generated paper abstracts, citation graphs, and semantic search. Completely free including API.',
    'description_long': "Semantic Scholar is a free AI-powered academic search engine developed by the Allen Institute for Artificial Intelligence (AI2), one of the leading nonprofit AI research organizations. It indexes over 214 million academic papers across all disciplines and applies AI to make the literature more accessible and discoverable.\n\nThe AI capabilities include TLDR summaries (one-sentence AI-generated abstracts for papers that lack them), semantic search that understands the meaning of a query rather than just matching keywords, citation velocity tracking (papers gaining rapid citations), and the concept graph that maps how topics and ideas connect across literature. The free Research API enables researchers and developers to build applications on top of Semantic Scholar's data.\n\nKey capabilities include natural language paper search across 214M+ papers, AI-generated TLDR summaries, semantic search for concept-level discovery, citation graph visualization, citation velocity tracking, paper recommendations, author profiles, and a completely free Research API.\n\nPricing: Semantic Scholar is completely free — the web interface, all AI features, and the Research API have no cost. The Allen Institute for AI funds the service as a public good for the scientific community. There are no premium tiers or paid upgrades.\n\nLimitations: Semantic Scholar is a search and discovery tool — it does not extract structured data from papers the way Elicit does, nor does it classify citations as supporting or contrasting the way Scite does. Coverage across disciplines is broad but depth varies — highly specialized fields may have incomplete coverage.\n\nBest suited for researchers, students, and developers who need a free, comprehensive academic search engine with semantic search capabilities and API access — particularly as a complement to Elicit or Scite for specific research workflows.",
    'pros': ['Completely free — no cost for any feature including the API', '214M+ papers across all academic disciplines', 'AI TLDR summaries for papers without abstracts', 'Semantic search understands research concepts rather than just keyword matching', 'Free Research API enables building research tools and applications'],
    'cons': ['Discovery tool only — does not extract structured data like Elicit', 'No citation relationship classification like Scite (supporting vs. contrasting)', 'Coverage depth varies across disciplines — specialized fields may be incomplete', 'No dedicated customer support — community-supported tool'],
  },
}

def patch(slug, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        f'{SB_URL}/rest/v1/tools?slug=eq.{slug}&lang=eq.en',
        data=body, headers=HDRS, method='PATCH'
    )
    with urllib.request.urlopen(req) as r:
        return r.status

print(f'Updating {len(UPDATES)} tools...')
for slug, fields in UPDATES.items():
    status = patch(slug, fields)
    print(f'  {slug}: HTTP {status}')

print('Done.')
