#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Update EN content for video and data categories."""
import urllib.request, json, os

SB_URL     = 'https://lbjdwkvkkndvofysyssy.supabase.co'
SB_SERVICE = os.environ.get('SB_SERVICE_KEY', '')
if not SB_SERVICE:
    print('ERROR: Set SB_SERVICE_KEY'); exit(1)

HDRS = {
    'apikey': SB_SERVICE,
    'Authorization': f'Bearer {SB_SERVICE}',
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

UPDATES = {
  # ── VIDEO ─────────────────────────────────────────────────────────────────────
  'capcut': {
    'badge': 'freemium', 'users': '800M+',
    'best_for': 'AI-powered video editing for social media and short-form content',
    'description': 'ByteDance\'s video editor with 800M+ monthly active users. AI features include auto-captions, background removal, voice cloning, and Seedance 2.0 video generation. Pro $7.99/mo.',
    'description_long': "CapCut is a video editing app developed by ByteDance with over 800 million monthly active users across mobile, desktop, and web. It is the most widely used short-form video editor globally, particularly popular among TikTok, Instagram Reels, and YouTube Shorts creators. As of 2026, CapCut has integrated Seedance 2.0 — ByteDance's AI video generation model — directly into the editing workflow, enabling AI-generated b-roll and scene creation from text prompts.\n\nThe AI feature set is extensive: auto-captions with multilingual translation, AI background removal on video (not just photos), voice cloning for dubbing and narration, AI color grading, auto-reframe for different aspect ratios, and AI-powered text-to-video via Seedance 2.0. The desktop version includes a full non-linear editing timeline comparable to entry-level professional tools.\n\nKey capabilities include Seedance 2.0 AI video generation, auto-captions and multilingual subtitles, AI background removal, voice cloning, AI-assisted color grading, auto-reframe for multiple aspect ratios, a template library of millions of clips and effects, and direct export to TikTok and Instagram.\n\nPricing: Free tier is comprehensive and includes most editing features with CapCut watermark on export. Pro at $7.99 per month removes the watermark, increases export resolution, adds AI credits, and unlocks premium templates. Standard at $9.99 per month adds team features. Business plans are available for agencies and enterprises.\n\nLimitations: ByteDance ownership creates ongoing regulatory risk in the United States — CapCut has faced potential bans alongside TikTok due to national security concerns. US users should factor this into long-term tooling decisions. The free tier watermark is prominent and unavoidable without a paid plan.\n\nBest suited for social media creators, content marketers, and agencies producing short-form video for TikTok, Instagram, and YouTube who need fast AI-assisted editing on mobile or desktop.",
    'pros': ['800M+ monthly active users — most widely used short-form video editor globally', 'Seedance 2.0 AI video generation integrated directly into editing workflow', 'Auto-captions with multilingual translation built in — no third-party tool needed', 'AI background removal on video, voice cloning, and auto-reframe for any aspect ratio', 'Free tier is genuinely capable — most features available without payment'],
    'cons': ['ByteDance ownership creates US regulatory risk — potential ban exposure', 'Free tier exports have a visible CapCut watermark requiring paid plan to remove', 'Seedance 2.0 AI video generation not available in the United States (legal issues)', 'Less capable than professional tools like Premiere Pro for complex long-form editing'],
  },
  'google-veo-3': {
    'badge': 'freemium', 'users': '',
    'best_for': 'High-quality AI video generation with native audio from Google DeepMind',
    'description': 'Google DeepMind\'s state-of-the-art AI video generation model. Available in Gemini AI Pro ($19.99/mo, 90 videos/month) and via API ($0.05–$0.60/sec). Veo 3.1 Lite is 50% cheaper.',
    'description_long': "Google Veo 3 is Google DeepMind's state-of-the-art AI video generation model, capable of producing high-definition video clips with synchronized native audio — including dialogue, sound effects, and ambient sound — from text and image prompts. It is currently the only major AI video model to generate audio natively alongside the video, rather than requiring separate audio post-production.\n\nVeo 3 is available to consumers through Google's Gemini AI Pro subscription ($19.99/month), which includes approximately 90 video generation credits per month. Veo 3.1, released alongside Veo 3, introduced Veo 3.1 Lite — a faster, 50% cheaper variant optimized for higher-volume use cases. The API enables developers and enterprises to integrate Veo into their own applications.\n\nKey capabilities include 1080p video generation from text and image prompts, native synchronized audio generation (dialogue, effects, ambience), Veo 3.1 Lite for cost-efficient volume generation, API access with per-second pricing, and integration with Google's Vertex AI for enterprise workflows.\n\nPricing: Consumer access via Gemini AI Pro at $19.99 per month includes Veo 3 generation credits (~90 videos/month). API pricing ranges from $0.05 per second for Veo 3.1 Lite to $0.60 per second for Veo 3 (full quality). Enterprise pricing through Google Cloud Vertex AI is available on request.\n\nLimitations: Consumer generation is gated behind a Gemini AI Pro subscription. API costs can accumulate quickly for high-volume production. Maximum clip length is currently limited (typically under 60 seconds per generation). As a newer model, Veo 3 is not yet widely integrated into third-party editing tools.\n\nBest suited for content creators, filmmakers, and marketing teams who need high-quality AI video with synchronized audio — particularly those already in the Google ecosystem and using Gemini AI Pro.",
    'pros': ['Only major AI video model to generate native audio (dialogue, effects, ambience) alongside video', 'Available in Gemini AI Pro — no separate subscription needed if already subscribed', 'Veo 3.1 Lite offers 50% cost reduction for higher-volume generation', 'API integration with Google Cloud Vertex AI for enterprise workflows', 'State-of-the-art video quality benchmarks as of 2026'],
    'cons': ['Consumer access requires Gemini AI Pro subscription ($19.99/mo)', 'Maximum clip length limited — not suitable for long-form narrative video', 'API costs add up quickly for high-volume production workflows', 'Less integrated into third-party editing tools compared to Runway or Kling'],
  },
  'heygen': {
    'badge': 'freemium', 'users': '2M+',
    'best_for': 'AI avatar video creation and video translation with lip sync in 175+ languages',
    'description': 'AI video platform for creating talking-head avatar videos and translating existing videos into 175+ languages with voice cloning and lip sync. Creator $29/mo, Pro $99/mo.',
    'description_long': "HeyGen is an AI video platform specializing in two distinct use cases: creating avatar-based talking-head videos without a camera, and translating existing videos into over 175 languages with AI voice cloning and lip sync. It has become the standard tool for enterprise video localization and for teams that produce training, marketing, and communications videos at scale.\n\nThe avatar creation workflow allows users to either use one of HeyGen's 300+ stock avatars or create a custom digital twin from a short video upload. Users input a script and the avatar delivers it with synchronized lip movement. The translation feature — Video Translate — takes any uploaded video, clones the speaker's voice, translates the speech, and generates lip-sync that matches the new language. The quality is sufficient for corporate communications and e-learning.\n\nKey capabilities include 300+ stock AI avatars, custom avatar creation from video upload, AI script generation from URLs and documents, video translation in 175+ languages with voice cloning and lip sync, Streaming Avatar API for real-time interactive avatars, and integrations with HubSpot, Salesforce, Zapier, and major LMS platforms.\n\nPricing: Free plan includes 3 minutes of video per month at limited resolution. Creator at $29 per month provides 15 credits per month (approximately 15 minutes of video), 300+ avatars, and 720p export. Pro at $99 per month provides 30 credits, custom avatars, 1080p export, and all translation features. Business at $149 per month provides 60 credits and API access. Enterprise pricing is custom.\n\nLimitations: Credit consumption per minute is high — Pro's 30 credits per month means approximately 30 minutes of generated video. High-volume users will find Enterprise pricing necessary. Avatar quality, while good for corporate use, is still visibly AI-generated for discerning viewers.\n\nBest suited for L&D teams, marketing agencies, and enterprises that produce regular video content and need to scale globally — particularly for training videos, product demos, and multilingual communications.",
    'pros': ['Video translation in 175+ languages with voice cloning and lip sync', '300+ stock AI avatars and custom digital twin creation from video upload', 'Enterprise integrations with HubSpot, Salesforce, and major LMS platforms', 'Streaming Avatar API for real-time interactive AI avatar applications', '2M+ users with strong adoption in enterprise L&D and marketing'],
    'cons': ['Credit model limits monthly video output — 30 minutes/month on Pro ($99/mo)', 'Avatar output visibly AI-generated — not suitable for consumer-facing brand video', 'Free tier limited to 3 minutes/month — insufficient for regular use', 'High volume use requires expensive Enterprise plan'],
  },
  'kling-ai': {
    'badge': 'freemium', 'users': '',
    'best_for': 'High-quality AI video generation with realistic motion and physics',
    'description': 'Kuaishou\'s AI video generation model with realistic motion and physics simulation. Version 3.0 as of 2026. Standard $5.99/mo, Pro $29.99/mo. Also available via Runway\'s multi-model platform.',
    'description_long': "Kling AI is an AI video generation model developed by Kuaishou Technology, the Chinese short-video platform. It gained international attention for producing unusually realistic motion and physics in generated clips — running water, cloth movement, and human motion that benchmark higher than competing models in side-by-side comparisons. Kling 3.0 is the current version as of 2026.\n\nThe platform offers both text-to-video and image-to-video generation, with output up to 1080p at up to 10 seconds per clip. Kling 3.0 introduced improved camera controls, allowing specification of pan, tilt, zoom, and tracking shots within a generation prompt. Kling is also available through Runway's multi-model platform, letting Runway subscribers access Kling 3.0 without a separate subscription.\n\nKey capabilities include text-to-video generation up to 10 seconds at 1080p, image-to-video animation, camera movement controls (pan, tilt, zoom, tracking), realistic motion physics, and API access for developers. The model is particularly strong on human motion and physical interactions.\n\nPricing: Free plan includes limited monthly credits. Standard at $5.99 per month provides 660 credits (approximately 66 clips at standard quality). Pro at $29.99 per month provides 3,000 credits. Premier at $54.99 per month provides 8,000 credits. Credits are also available as one-time purchases. Kling is accessible via Runway's Pro and Unlimited plans as part of the multi-model offering.\n\nLimitations: Maximum clip length of 10 seconds requires stitching for longer sequences. The Kuaishou ownership means similar data sovereignty considerations as other Chinese AI video tools. Generation speed varies and can be slow during peak demand on lower subscription tiers.\n\nBest suited for filmmakers, content creators, and agencies who prioritize motion realism in AI video and want access via either a direct Kling subscription or through Runway's multi-model platform.",
    'pros': ['Best-in-class motion realism and physics simulation among AI video models', 'Text-to-video and image-to-video generation up to 1080p at 10 seconds', 'Camera movement controls for pan, tilt, zoom, and tracking shots', 'Accessible via Runway multi-model platform — no separate subscription needed for Runway users', 'Standard plan at $5.99/mo is the most affordable entry point among major video models'],
    'cons': ['Maximum 10-second clip length requires stitching for longer sequences', 'Kuaishou (Chinese company) ownership — similar data sovereignty considerations as TikTok/CapCut', 'Generation speed can be slow during peak demand on lower tiers', 'Credits consumed per generation — heavy users will exhaust monthly allotments quickly'],
  },
  'luma-ai': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI video generation platform with access to multiple models including Kling',
    'description': 'Multi-model AI video platform with Dream Machine for video generation plus access to Kling 3.0 and other models. Lite $9.99/mo, Standard $29.99/mo, Pro $99.99/mo.',
    'description_long': "Luma AI is a multi-model AI video generation platform best known for Dream Machine, its in-house text-to-video and image-to-video model. In 2026, Luma expanded into a platform model — subscribers can access multiple AI video generation models including Kling 3.0, enabling users to choose the best model for each specific generation task without switching platforms.\n\nDream Machine excels at cinematic camera work and creative stylistic output — wide-angle shots, smooth tracking, and visually interesting compositions that go beyond literal prompt interpretation. The platform also offers Photon, a Luma image generation model, for image-to-video workflows. The combination of Dream Machine plus Kling 3.0 access makes Luma a versatile hub for AI video production.\n\nKey capabilities include Dream Machine text-to-video and image-to-video generation, Kling 3.0 access, Photon image generation, keyframe animation for guiding scene transitions, camera motion controls, and an API for developer integrations.\n\nPricing: Free plan provides limited monthly generations. Lite at $9.99 per month provides 100 fast generations. Standard at $29.99 per month provides 450 fast generations. Pro at $99.99 per month provides 2,250 fast generations. Enterprise pricing with volume API access is custom. Multi-model access (including Kling) is available on Standard and above.\n\nLimitations: The platform model means credits are shared across multiple generation types — users who rely heavily on Kling may burn through credits faster. Dream Machine output, while creative, can be inconsistent on literal prompt following compared to more controlled models.\n\nBest suited for creative professionals and agencies who want a single platform for AI video with access to multiple generation models, particularly those who value Dream Machine's cinematic aesthetic.",
    'pros': ['Multi-model platform — access Dream Machine, Kling 3.0, and Photon in one subscription', 'Dream Machine excels at cinematic camera work and creative stylistic video', 'Keyframe animation enables guided multi-scene video sequences', 'Standard plan at $29.99/mo provides 450 fast generations — good value', 'API access for building video generation into custom applications'],
    'cons': ['Credits shared across all models — heavy Kling use depletes Dream Machine credits too', 'Dream Machine can be inconsistent on literal prompt following', 'Multi-model access only on Standard plan and above ($29.99+)', 'Clip length limited — not suitable for full scenes without stitching'],
  },
  'pika': {
    'badge': 'freemium', 'users': '1M+',
    'best_for': 'Creative AI video editing with unique character and object manipulation effects',
    'description': 'AI video generator known for Pikaffects, Pikaswaps, and Pikaformance — unique character and object manipulation that goes beyond standard text-to-video. Pika 2.5. Basic $8/mo, Pro $28/mo.',
    'description_long': "Pika is an AI video generation tool that has differentiated itself through creative manipulation effects that go beyond standard text-to-video generation. While competing models focus on photorealistic video from prompts, Pika's signature features — Pikaffects, Pikaswaps, and Pikaformance — enable specific types of object and character transformation that have become popular for social media content and creative experimentation.\n\nPikaffects applies visual transformation effects to objects or characters in uploaded videos (melt, explode, turn to ice, crumple). Pikaswaps replaces objects or backgrounds in videos with AI-generated alternatives. Pikaformance transfers motion from one video onto a different character or style. Pika 2.5 (the current version as of 2026) improved general video generation quality alongside these signature effects.\n\nKey capabilities include standard text-to-video and image-to-video generation, Pikaffects for object transformation, Pikaswaps for object and background replacement, Pikaformance for motion transfer, and a web-based editing interface with a library of generated content.\n\nPricing: Free tier provides limited monthly credits. Basic at approximately $8 per month provides 700 credits. Pro at approximately $28 per month provides 2,000 credits and higher output resolution. Ultra at approximately $70 per month provides 6,000 credits and the fastest generation priority.\n\nLimitations: Pika's signature effects are creative but niche — they are best for social media and creative experiments, not photorealistic production. General text-to-video quality on Pika 2.5 benchmarks below Kling 3.0 or Veo 3 for realistic motion. The credit system can deplete quickly when experimenting with multiple effect types.\n\nBest suited for social media creators, designers, and creative teams who want unique AI video effects not available in other tools — particularly Pikaffects transformations for creative content.",
    'pros': ['Pikaffects, Pikaswaps, and Pikaformance are unique effects not available on other platforms', 'Strong for creative and experimental video content — distinctive visual output', 'Easy web-based interface — lower learning curve than professional video tools', 'Pika 2.5 improved general video quality alongside signature effects', 'Basic plan at $8/mo is the most affordable paid option among major AI video tools'],
    'cons': ['General text-to-video quality below Kling 3.0 or Veo 3 for realistic motion', 'Signature effects are niche — not suitable for standard photorealistic production', 'Credit system depletes quickly when experimenting with multiple effects', 'Not integrated into professional editing pipelines as a component tool'],
  },
  'runway': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Professional AI video generation and editing with multi-model access',
    'description': 'The leading AI video platform for creative professionals. Gen-4.5 for high-quality video generation plus access to Veo 3.1 and Kling 3.0. Standard $12–15/mo, Pro $28–35/mo, Unlimited $76–95/mo.',
    'description_long': "Runway is the leading AI video platform for creative professionals, known for pioneering text-to-video generation and consistently being at the frontier of AI video research. In 2026, Runway evolved into a multi-model platform — subscribers can choose between Runway's own Gen-4.5 model, Google's Veo 3.1, and Kuaishou's Kling 3.0 within a single subscription, enabling optimal model selection per generation task.\n\nGen-4.5 is Runway's in-house model optimized for cinematic quality and creative control — it supports reference-based generation (providing a reference image or video to guide style and subject consistency), camera motion controls, and multi-shot scene generation. The Act-One feature transfers facial expressions and emotions from a reference video onto a generated character, used in professional film and advertising.\n\nKey capabilities include Gen-4.5 text-to-video and image-to-video, Veo 3.1 and Kling 3.0 access, Act-One (expression transfer), reference-based generation for style/character consistency, camera motion controls, video-to-video transformation, green screen (background replacement), frame interpolation, and an API for production pipelines.\n\nPricing: Pricing varies by billing cycle (monthly vs annual). Standard at $12 per month (annual) or $15 per month provides 625 credits. Pro at $28 per month (annual) or $35 per month provides 2,250 credits and multi-model access including Veo 3.1 and Kling. Unlimited at $76 per month (annual) or $95 per month provides 2,250 credits plus unlimited Gen-4.5 Turbo. Enterprise pricing is custom.\n\nLimitations: Multi-model access (Veo 3.1, Kling) requires the Pro plan or above. Credits are shared across all generation types and models — a Pro subscription with heavy Kling use will deplete quickly. Runway is priced above entry-level tools like Kling direct or Pika.\n\nBest suited for creative professionals, filmmakers, and agencies who need the highest quality AI video output and the flexibility to choose between leading models — particularly those integrating AI video into professional production workflows.",
    'pros': ['Multi-model platform — access Gen-4.5, Veo 3.1, and Kling 3.0 in one subscription', 'Act-One enables professional-grade facial expression transfer between videos', 'Reference-based generation maintains subject and style consistency across clips', 'API access for integrating Runway into professional production pipelines', 'Consistent track record at the frontier of AI video research and quality'],
    'cons': ['Multi-model access (Veo 3.1, Kling) requires Pro plan ($28+/mo)', 'Credits shared across all models — heavy use of premium models depletes quickly', 'Priced above entry-level tools — Kling direct or Pika cheaper for basic generation', 'Monthly billing significantly more expensive than annual commitment'],
  },
  'seedance-2-0': {
    'badge': 'freemium', 'users': '',
    'best_for': 'ByteDance\'s AI video generation model — integrated in CapCut, API via fal.ai',
    'description': 'ByteDance\'s advanced AI video generation model, integrated into CapCut for global users. Not directly available in the USA (Disney lawsuit). API access via fal.ai. Produces cinematic quality video.',
    'description_long': "Seedance 2.0 is ByteDance's AI video generation model, representing the company's highest-capability video generation technology as of 2026. It is the model powering CapCut's AI video generation features globally and is available to developers via fal.ai's API marketplace. The model produces cinema-quality video clips with strong motion realism and follows complex compositional prompts.\n\nSeedance 2.0 is not directly available as a standalone consumer product in the United States. Disney filed a cease-and-desist against ByteDance in early 2026 over copyright concerns, and ByteDance preemptively restricted Seedance's US availability as a result. The model remains fully accessible in all other markets through CapCut and the fal.ai API.\n\nKey capabilities include text-to-video generation, image-to-video animation, camera motion controls, high-fidelity motion physics, and API access via fal.ai for developer integration. Output resolution and clip length match major competing models (up to 1080p, up to 10 seconds per clip).\n\nPricing: Seedance 2.0 access through CapCut is included with CapCut's existing plans. API access via fal.ai uses per-generation pricing that varies by output length and quality tier — generally comparable to other frontier video model APIs. No standalone Seedance subscription exists.\n\nLimitations: US market restriction is a significant limitation for US-based creators and developers. ByteDance ownership creates the same regulatory exposure as CapCut and TikTok. As a model primarily accessed through other platforms (CapCut, fal.ai), there is no direct Seedance consumer interface.\n\nBest suited for non-US content creators using CapCut who want access to ByteDance's best video generation model, and developers building video applications outside the US market via fal.ai.",
    'pros': ['Cinema-quality video generation — among the highest quality ByteDance has produced', 'Integrated into CapCut for seamless access within existing editing workflows', 'API via fal.ai for developer integration at competitive per-generation pricing', 'Strong motion realism and complex compositional prompt following'],
    'cons': ['Not available in the United States (Disney lawsuit, ByteDance restriction)', 'No standalone consumer product — accessed only through CapCut or fal.ai', 'ByteDance ownership creates ongoing regulatory exposure in Western markets', 'Less third-party integration than Kling or Runway models'],
  },
  'synthesia': {
    'badge': 'freemium', 'users': '50K+',
    'best_for': 'Enterprise AI avatar video for training, onboarding, and corporate communications',
    'description': 'Enterprise AI video platform for creating avatar-based training, onboarding, and communications videos. 230+ AI avatars, 160+ languages. Starter $29/mo ($18 annual), Creator $89/mo ($64 annual).',
    'description_long': "Synthesia is an enterprise-focused AI video platform for creating training, onboarding, and corporate communications videos using AI avatars. It is the market leader for enterprise L&D and HR video production, with customers including Zoom, Nike, and Heineken. The platform generates professional talking-head videos from a script and avatar selection — without cameras, studios, or production teams.\n\nThe 2026 platform includes over 230 AI avatars with diverse appearances and languages, custom avatar creation from a short video upload, an AI script assistant, and a slide-based editor similar to PowerPoint. Expressive avatars with emotion controls were added in 2025, improving the perceived quality of generated content for high-stakes corporate communication. The platform supports 160+ languages for global training deployment.\n\nKey capabilities include 230+ stock AI avatars, custom avatar creation, AI script generation, a slide-based video editor, emotion controls on expressive avatars, SCORM and LMS export for e-learning platforms, 160+ language support, and team collaboration features.\n\nPricing: Free plan provides 3 minutes of video per month. Starter at $29 per month (or $18 per month billed annually) provides 10 minutes of video per month and access to 90+ avatars. Creator at $89 per month ($64 annual) provides 30 minutes per month, all 230+ avatars, and custom avatar creation. Enterprise pricing is custom and includes dedicated support, API access, and SSO.\n\nLimitations: The per-minute pricing model makes high-volume production expensive — 30 minutes of video on Creator requires careful budgeting. Avatar quality, while good for corporate training, is clearly AI-generated and not suitable for customer-facing brand videos. The slide-based editor is purposely simple — not a full video editing tool.\n\nBest suited for L&D, HR, and internal communications teams at medium to large enterprises who regularly produce training and onboarding videos and want to scale without video production overhead.",
    'pros': ['Market leader for enterprise L&D video — proven with Zoom, Nike, and Heineken', '230+ AI avatars with emotion controls and expressive delivery', 'SCORM and LMS export for direct deployment to e-learning platforms', '160+ language support for global training programs', 'Custom avatar creation enables branded consistent spokesperson for all videos'],
    'cons': ['Per-minute pricing limits production volume — 30 min/month on Creator ($89/mo)', 'Avatar quality clearly AI-generated — not suitable for customer-facing brand content', 'Slide-based editor is simplified — not a full video editing tool', 'Enterprise pricing required for API access and high-volume production'],
  },

  # ── DATA ──────────────────────────────────────────────────────────────────────
  'akkio': {
    'badge': 'paid', 'users': '',
    'best_for': 'No-code AI analytics and predictive modeling for marketing agencies',
    'description': 'No-code AI analytics platform for predictive modeling and forecasting. From $49/mo. Havas Media partnership (Jan 2026) validates enterprise agency use. Best for analytics teams without data science skills.',
    'description_long': "Akkio is a no-code AI analytics platform targeting marketing agencies and business analytics teams who need predictive modeling without data scientists. The platform enables users to upload datasets and build predictive models through a guided interface — predicting customer churn, lead scores, sales forecasts, and campaign outcomes from historical data without writing code or understanding machine learning.\n\nThe January 2026 partnership with Havas Media Group — one of the world's largest media agency networks — validated Akkio's enterprise positioning. The integration enables Havas media planners to use Akkio's AI for audience prediction, campaign performance forecasting, and attribution modeling at scale.\n\nKey capabilities include no-code predictive model building from CSV or CRM data, automated feature selection, real-time predictions via API, integration with HubSpot, Salesforce, Google Sheets, and Airtable, and natural language report generation. The platform handles classification, regression, and time-series forecasting tasks.\n\nPricing: Akkio starts at $49 per month for the basic plan. Professional plans with higher data limits and collaboration features are priced higher. Agency plans with multi-client management and white-label options are available at custom pricing. There is no permanent free tier — only a trial period.\n\nLimitations: Akkio is purpose-built for structured tabular data prediction — it does not handle unstructured data (text, images) and is not a general analytics platform. The no-code approach limits customization for teams with data science expertise who need fine-grained model control. Pricing starts at $49/month with no free tier.\n\nBest suited for marketing agencies, growth teams, and business analysts who need predictive modeling from CRM and campaign data without data science resources.",
    'pros': ['No-code predictive modeling — no data science skills required', 'Havas Media Group partnership validates enterprise agency use case', 'Native integrations with HubSpot, Salesforce, Google Sheets, and Airtable', 'Handles classification, regression, and time-series forecasting tasks', 'Real-time prediction API for embedding models into business workflows'],
    'cons': ['No free tier — starts at $49/month', 'Limited to structured tabular data — no unstructured data (text, image) support', 'Limited customization for teams with data science expertise', 'Niche focus on predictive modeling — not a general-purpose analytics platform'],
  },
  'hex': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Collaborative AI data notebooks and apps for analytics teams',
    'description': 'Collaborative data notebook and app builder with AI-assisted SQL and Python. Community free; Team Creator seats ~$149–199/user/mo. GPU compute pay-as-you-go. Used by analytics and data science teams.',
    'description_long': "Hex is a collaborative data notebook and app-building platform that combines SQL and Python notebooks with AI-powered code assistance, enabling analytics teams to build data analysis workflows and publish interactive apps from a single tool. Unlike traditional Jupyter notebooks, Hex is designed for team collaboration — multiple users can work in the same notebook simultaneously, with version control, sharing, and presentation built in.\n\nHex AI assists with SQL generation, Python code completion, chart configuration, and explaining complex queries. The platform connects to data warehouses (Snowflake, BigQuery, Databricks, Redshift) and supports notebooks with mixed SQL/Python cells that share a data environment. Published apps allow non-technical stakeholders to interact with analytics outputs without seeing the underlying code.\n\nKey capabilities include collaborative SQL and Python notebooks, AI-assisted code generation and explanation, interactive app publishing, connections to all major data warehouses, versioning, scheduling for automated notebook runs, and GPU compute for ML workloads (pay-as-you-go).\n\nPricing: Community plan is free for individual use with limited features. Team plan Creator seats are priced at approximately $149-199 per user per month for data practitioners who build notebooks. Viewer seats for stakeholders who consume published apps are separately priced at lower rates. GPU compute for ML workloads is charged per usage. Enterprise pricing is custom.\n\nLimitations: Creator seat pricing is high — $149-199/month per active analyst makes Hex expensive for teams. The pricing model distinguishes between creators and viewers, which can complicate budget planning. The platform is excellent for analytics teams but not optimized for solo data science work.\n\nBest suited for analytics and data science teams at growth-stage and enterprise companies who want collaborative notebook tooling with AI assistance and the ability to publish interactive apps for business stakeholders.",
    'pros': ['Real-time collaborative notebooks — multiple users simultaneously', 'AI-assisted SQL and Python code generation and explanation', 'Published apps let non-technical stakeholders interact with outputs without code access', 'Connects to Snowflake, BigQuery, Databricks, and Redshift', 'GPU compute available for ML workloads on pay-as-you-go basis'],
    'cons': ['Creator seat pricing high — approximately $149–199/user/month', 'Pricing model separates Creator and Viewer seats — complex budget planning', 'Community free tier limited — not suitable for team collaboration', 'Expensive compared to self-hosted Jupyter or Databricks notebooks'],
  },
  'julius-ai': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Conversational AI data analysis — upload any dataset, ask questions in plain language',
    'description': 'Conversational AI data analyst. Upload CSV, Excel, or connect databases — ask questions in plain English and get charts, stats, and summaries. Free 15 msg/mo; Plus $29/mo; Pro $37/mo.',
    'description_long': "Julius AI is a conversational data analysis tool that allows users to upload spreadsheets, CSVs, and connect databases, then analyze data by asking questions in plain English. It generates charts, statistical summaries, and written data insights from natural language queries — making data analysis accessible to business users without SQL or Python knowledge.\n\nThe platform handles standard data analysis tasks conversationally: trend analysis, statistical summaries, correlation detection, chart generation, and data cleaning suggestions. It supports file uploads (CSV, Excel, JSON) and connects to Google Sheets, Dropbox, and OneDrive. Charts are interactive and exportable. Julius can also generate and run Python code for more complex analysis if needed.\n\nKey capabilities include conversational data querying in plain English, chart and visualization generation, statistical analysis (regression, correlation, descriptive stats), data cleaning assistance, Python code generation and execution, and exports to CSV, PNG, and PDF.\n\nPricing: Free plan provides 15 messages per month — limited for regular use. Plus at $29 per month provides 250 messages per month and unlimited file uploads. Pro at $37 per month provides 500 messages per month, priority processing, and API access. Business at $375 per month provides 5,000 messages and team features.\n\nLimitations: Message-based pricing limits heavy users — 500 messages/month on Pro is consumed quickly in iterative analysis sessions. The tool excels at exploratory analysis but is not designed for automated pipeline work or enterprise BI deployments. Complex statistical modeling requires prompting Python generation rather than native support.\n\nBest suited for business analysts, researchers, and managers who regularly work with structured data and want to explore and summarize datasets without writing SQL or Python.",
    'pros': ['Plain English data analysis — no SQL or Python required', 'Supports CSV, Excel, Google Sheets, Dropbox, and OneDrive', 'Interactive and exportable charts with one conversational request', 'Can generate and run Python code for complex analysis when needed', 'Low barrier to entry — Plus plan at $29/mo is accessible for individuals'],
    'cons': ['Message-based pricing limits iterative exploratory analysis', 'Not designed for automated data pipelines or enterprise BI', 'Complex modeling requires prompting Python generation rather than native statistical tools', 'Free tier (15 messages/mo) insufficient for regular use'],
  },
  'looker-studio': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Free Google-integrated BI dashboards with AI-powered formula assistance',
    'description': 'Google\'s free data visualization and BI reporting tool with connectors to 1,000+ data sources. Looker Studio Pro ($9/user/mo) adds Gemini AI formula assistant, team sharing, and support SLA.',
    'description_long': "Looker Studio (formerly Google Data Studio) is Google's business intelligence and data visualization platform. The core product is free and connects to over 1,000 data sources through native connectors (Google Analytics, Google Ads, BigQuery, Sheets, Search Console) and community connectors (Salesforce, Facebook Ads, Shopify, and hundreds more). It is widely used for marketing analytics, performance dashboards, and business reporting.\n\nLooker Studio Pro, introduced in 2023 and expanded in 2025-2026, adds the Gemini AI Formula Assistant — which generates Looker Studio formulas from plain language descriptions, significantly reducing the time required to build calculated fields and custom metrics. Pro also adds team workspace sharing with organizational controls, SLA-backed support, and scheduled email delivery of reports.\n\nKey capabilities include drag-and-drop report building, 1,000+ native and community data source connectors, embedded reports for sharing externally, scheduled email delivery, Gemini AI Formula Assistant (Pro), team workspaces (Pro), and integration with the broader Google Analytics and Google Cloud ecosystem.\n\nPricing: The core Looker Studio product is completely free with full dashboard building capability and 1,000+ connectors. Looker Studio Pro costs $9 per user per month and adds Gemini AI Formula Assistant, team workspaces, organizational asset management, SLA support, and scheduled email report delivery.\n\nLimitations: Looker Studio's free tier lacks features that competing BI tools include by default (team management, SLA support). The AI Formula Assistant is useful but limited in scope compared to natural language BI in tools like Hex or Databricks. For complex enterprise BI with advanced modeling, Google Looker (the enterprise product, separate from Looker Studio) is more capable.\n\nBest suited for marketing teams, analysts, and organizations already in the Google ecosystem who want free or low-cost dashboards connecting Google Analytics, Ads, and BigQuery data.",
    'pros': ['Core product is completely free — full dashboard building with 1,000+ connectors', 'Native Google ecosystem integration — Google Analytics, Ads, BigQuery, Sheets', 'Gemini AI Formula Assistant generates calculated fields from plain language (Pro)', 'Embeddable reports for sharing with clients and external stakeholders', 'Pro at $9/user/mo is among the lowest-cost BI upgrades available'],
    'cons': ['Team management and SLA support locked behind Pro tier', 'AI capabilities limited to formula generation — not natural language BI querying', 'Complex enterprise modeling less capable than full Looker or Tableau', 'Community connector quality varies — some third-party connectors unreliable'],
  },
  'retool-ai': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Building internal AI tools and apps on top of databases and APIs',
    'description': 'Low-code platform for building internal business tools — dashboards, admin panels, data editors — with AI components and agentic workflows. Free 5 users; Team $10/user/mo; Business $50/user/mo.',
    'description_long': "Retool is a low-code development platform for building internal business applications — admin panels, data dashboards, customer support tools, and operational workflows — by connecting directly to databases and APIs. As of 2026, Retool has added AI components and agentic workflow capabilities, enabling teams to embed AI into their internal tools without building custom AI infrastructure.\n\nRetool AI allows embedding LLM-powered components into apps: AI form completion, AI data summarization, AI chatbots within internal dashboards, and agentic workflows that chain multiple AI steps with human approval gates. The platform connects to Postgres, MySQL, Snowflake, MongoDB, REST APIs, GraphQL, and over 100 pre-built integrations. The drag-and-drop builder creates UIs while pre-built components handle common patterns.\n\nKey capabilities include visual app builder with drag-and-drop components, 100+ database and API integrations, AI components (LLM text generation, AI form assistants), agentic workflow builder with human-in-the-loop steps, JavaScript and Python support for custom logic, audit logs, and role-based access control.\n\nPricing: Free plan supports up to 5 users with full app building capabilities. Team at $10 per user per month adds staging environments, custom domains, and expanded AI component usage. Business at $50 per user per month adds SSO, custom branding, audit logs, and higher AI consumption limits. Enterprise pricing includes dedicated support and SLA.\n\nLimitations: Retool is optimized for internal tools — it is not suitable for building customer-facing production apps. AI agents in Retool are consumption-based with separate pricing that adds to per-seat costs. The visual builder, while powerful for Retool's use case, requires familiarity with data concepts (queries, transformations) to use effectively.\n\nBest suited for operations, product, and engineering teams at startups and enterprises who need to build custom internal tools on top of their existing data sources — particularly those adding AI-assisted workflows to existing business operations.",
    'pros': ['Low-code builder reduces internal tool development time from weeks to days', '100+ native integrations with databases, APIs, and SaaS tools', 'AI components enable LLM-powered features in internal apps without custom AI development', 'Free plan for up to 5 users — genuinely usable for small teams', 'Human-in-the-loop approval gates for AI agent workflows'],
    'cons': ['Not suitable for customer-facing production applications', 'AI agents billed separately on consumption basis — adds to per-seat costs', 'Requires data query knowledge to use effectively — not truly no-code', 'Business plan at $50/user/mo expensive for larger teams'],
  },
  'rows': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI-enhanced spreadsheet with built-in data integrations and web scraping',
    'description': 'Spreadsheet platform with built-in AI, web scraping, and 50+ data integrations. Ask AI to build formulas or analyze data in plain English. Free 20 AI tasks/mo; Plus $8/user/mo; Pro $79/mo.',
    'description_long': "Rows is a spreadsheet platform that brings AI and data integration capabilities directly into the spreadsheet experience, without requiring external tools or APIs. Unlike Excel or Google Sheets where AI is bolted on as an add-in, Rows built AI as a native capability alongside 50+ data source integrations — enabling users to pull live data from Twitter, LinkedIn, HubSpot, Stripe, Google Analytics, and others directly into spreadsheet cells.\n\nThe AI assistant is embedded in the formula bar and throughout the interface — it generates formulas from plain language descriptions, summarizes datasets, enriches data by querying external sources, and builds analyses from natural language requests. The built-in web scraping capability allows extracting structured data from any public website without third-party tools.\n\nKey capabilities include native AI formula generation and data analysis, 50+ live data integrations (Twitter, LinkedIn, HubSpot, Stripe, and more), built-in web scraping, real-time data refresh, sharing and embedding of spreadsheets, and API for automated updates.\n\nPricing: Free plan provides 20 AI tasks per month and access to most features. Plus at $8 per user per month provides 200 AI tasks per month and all data integrations. Pro at $79 per month provides 1,000 AI tasks per month, team features, and higher data refresh rates. Enterprise pricing is custom.\n\nLimitations: AI task limits on the free and Plus tiers restrict heavy AI use. The platform is newer than established spreadsheet tools — some users encounter rough edges in the interface. Rows is best as a data-pulling and analysis tool, not as a replacement for complex Excel financial models.\n\nBest suited for growth, marketing, and sales teams who regularly pull data from external sources into spreadsheets and want AI to help with analysis and formula creation without leaving the spreadsheet environment.",
    'pros': ['50+ live data integrations pull real data from Twitter, LinkedIn, HubSpot, and Stripe into cells', 'AI formula generation from plain language — no formula syntax knowledge required', 'Built-in web scraping for structured data from any public website', 'Real-time data refresh keeps spreadsheet data current automatically', 'Plus at $8/user/mo is very affordable for teams with moderate AI usage'],
    'cons': ['AI task limits (20/mo free, 200/mo Plus) restrict heavy analysis workflows', 'Newer platform — some rough edges compared to Google Sheets or Excel', 'Not suitable for complex financial modeling workflows that rely on advanced Excel features', 'Pro plan at $79/mo jumps significantly from $8/user Plus'],
  },
  'tableau-ai': {
    'badge': 'paid', 'users': '',
    'best_for': 'Enterprise BI with AI-powered analytics — Salesforce-integrated',
    'description': 'Enterprise business intelligence platform with AI analytics features including Einstein Copilot and Pulse. Viewer $15/Creator $75/user/mo. AI features require Tableau+ add-on at custom pricing.',
    'description_long': "Tableau is the leading enterprise business intelligence platform owned by Salesforce, used by tens of thousands of organizations for data visualization and analytics at scale. Tableau AI encompasses several products: Tableau Pulse (AI-generated business metrics delivered as natural language summaries), Einstein Copilot (conversational AI assistant within Tableau), and AI-powered anomaly detection and forecasting.\n\nTableau's 2026 positioning centers on Agentforce integration — connecting Tableau AI to Salesforce's Agentforce platform for agentic data analysis within the Salesforce ecosystem. This enables Salesforce CRM workflows to trigger Tableau data analysis automatically and surface insights within the Salesforce interface. The combination creates a powerful platform for sales, service, and revenue operations teams already using Salesforce.\n\nKey capabilities include interactive dashboards and data visualization, Tableau Pulse for AI-generated natural language metric summaries, Einstein Copilot for conversational data querying, anomaly detection, AI forecasting, Agentforce integration for agentic analysis, and connections to hundreds of data sources.\n\nPricing: Tableau is licensed per user per month. Viewer licenses (read-only access) start at $15 per user per month. Creator licenses (full access, build and publish) are $75 per user per month. Explorer licenses sit between. AI features including Tableau Pulse and Einstein Copilot require the Tableau+ add-on, which is custom-priced separately and negotiated at the enterprise level.\n\nLimitations: Tableau is expensive — Creator licenses at $75/month plus the Tableau+ add-on make it among the most expensive BI platforms. AI features requiring Tableau+ are not available at standard license tiers. The platform's complexity requires dedicated BI resources to administer and build dashboards.\n\nBest suited for large enterprises already in the Salesforce ecosystem who need best-in-class visualization capabilities and want AI analytics integrated into their CRM and sales operations workflows.",
    'pros': ['Market-leading visualization capabilities — extensive chart types and interactive dashboards', 'Tableau Pulse delivers AI-generated natural language metric summaries to business users', 'Native Salesforce and Agentforce integration for CRM-connected analytics', 'Handles massive datasets and complex calculated fields at enterprise scale', 'Most widely adopted enterprise BI platform — large talent pool and resource ecosystem'],
    'cons': ['Creator licenses at $75/user/month among the most expensive in enterprise BI', 'AI features (Tableau Pulse, Einstein Copilot) require custom-priced Tableau+ add-on', 'High administrative overhead — requires dedicated BI team to maintain', 'Overkill and cost-prohibitive for small teams or basic reporting needs'],
  },
}

def patch(slug, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        f'{SB_URL}/rest/v1/tools?slug=eq.{slug}&lang=eq.en',
        data=body, headers=HDRS, method='PATCH'
    )
    with urllib.request.urlopen(req) as r:
        return r.status

print(f'Updating {len(UPDATES)} tools...')
for slug, fields in UPDATES.items():
    status = patch(slug, fields)
    print(f'  {slug}: HTTP {status}')

print('Done.')
