#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Update EN content for productivity and writing categories."""
import urllib.request, json, os

SB_URL     = 'https://lbjdwkvkkndvofysyssy.supabase.co'
SB_SERVICE = os.environ.get('SB_SERVICE_KEY', '')
if not SB_SERVICE:
    print('ERROR: Set SB_SERVICE_KEY'); exit(1)

HDRS = {
    'apikey': SB_SERVICE,
    'Authorization': f'Bearer {SB_SERVICE}',
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

UPDATES = {
  # ── PRODUCTIVITY ──────────────────────────────────────────────────────────────
  'fireflies-ai': {
    'badge': 'freemium', 'users': '20M+',
    'best_for': 'AI meeting notes, transcription, and action item extraction',
    'description': 'AI meeting assistant that joins calls, transcribes, and extracts action items automatically. 20M users, $1B valuation (June 2025). Free 800min storage; Pro $10/user/mo; Business $19/user/mo.',
    'description_long': "Fireflies.ai is an AI meeting assistant that automatically joins video calls, records, transcribes, and analyzes meetings across Zoom, Google Meet, Microsoft Teams, Webex, and other platforms. It reached 20 million users and achieved a $1 billion valuation in June 2025, making it the most widely adopted AI meeting tool for small and mid-sized teams.\n\nAfter each meeting, Fireflies generates a searchable transcript, an AI summary with key topics, and an extracted list of action items with assigned owners. The AI Insights feature tracks speaking time, sentiment, filler words, and talk-to-listen ratios — useful for sales coaching and meeting effectiveness review. The search functionality allows querying across all past meeting transcripts for specific topics, decisions, or mentions.\n\nKey capabilities include automatic meeting recording and transcription, AI-generated summaries and action items, speaker diarization (who said what), topic tracking across meetings, AI Insights for coaching analytics, transcript search, integrations with Slack, Salesforce, HubSpot, Notion, and Zapier, and an API for building on meeting data.\n\nPricing: Free plan provides 800 minutes of meeting storage and 3 months of transcript access. Pro at $10 per user per month provides unlimited storage, transcription, and basic AI features. Business at $19 per user per month adds AI Insights analytics, CRM integrations, and team management. Enterprise at $39 per user per month adds SSO, compliance features, and dedicated support.\n\nLimitations: AI summary quality varies by meeting type — structured meetings produce better summaries than unstructured brainstorms. The bot joining meetings is visible to participants and may feel intrusive in sensitive discussions. Action item extraction requires clear verbal commitments — implied or indirect action items are often missed.\n\nBest suited for sales teams, customer success managers, and distributed teams that hold frequent external or internal meetings and want automated notes, follow-ups, and a searchable archive of all conversations.",
    'pros': ['Automatically joins calls across Zoom, Meet, Teams, and Webex without manual setup', 'AI Insights provides coaching analytics — speaking time, sentiment, talk-to-listen ratio', 'Searchable transcript archive across all past meetings', 'Integrates with Slack, Salesforce, HubSpot, Notion, and Zapier', '$1B valuation and 20M users — proven enterprise-grade reliability'],
    'cons': ['Meeting bot visible to participants — intrusive in sensitive or confidential discussions', 'Action item extraction misses indirect or implied commitments', 'AI summary quality inconsistent for unstructured or creative brainstorm sessions', 'Business tier ($19/user/mo) required for CRM integrations and AI coaching analytics'],
  },
  'gamma': {
    'badge': 'freemium', 'users': '10M+',
    'best_for': 'AI-generated presentations, documents, and websites from text prompts',
    'description': 'AI tool that generates polished presentations, documents, and web pages from a text prompt in seconds. Free 400 credits; Plus $8/mo; Pro $15/mo; Ultra (top tier) available.',
    'description_long': "Gamma is an AI-powered tool that generates polished presentations, documents, and web pages from a text description or outline in seconds. It is positioned as an alternative to PowerPoint and Google Slides that removes the blank-slide problem — users describe what they need and receive a complete, designed presentation ready to edit.\n\nThe output quality is notably higher than generic AI presentation tools — Gamma uses design principles (visual hierarchy, color coordination, appropriate imagery) to produce slides that look professionally designed rather than template-filled. Generated content can be exported to PowerPoint, shared via link, or published as a live web page. The platform also creates document and wiki formats, not just slide decks.\n\nKey capabilities include AI presentation generation from text prompts, AI document and wiki creation, one-click theme and style changes, web page publishing, export to PowerPoint, image generation integrated in slides, embed support for videos and interactive content, and team collaboration.\n\nPricing: Free plan provides 400 credits (sufficient for approximately 4 full presentations). Plus at $8 per month provides unlimited AI generations and core features. Pro at $15 per month adds advanced AI, custom domains for published pages, analytics, and priority support. An Ultra tier provides maximum features including the highest AI quality and custom branding.\n\nLimitations: Generated presentations often require editing to match exact brand standards. The web-based editor, while good, is less powerful than PowerPoint for complex custom animations or precise layout control. Credit-based free tier limits exploration.\n\nBest suited for professionals, consultants, and sales teams who frequently need to create presentations from outlines or briefs and want to skip the formatting and design process.",
    'pros': ['Generates complete, designed presentations from a text outline in seconds', 'Output quality significantly higher than generic AI presentation tools', 'Creates presentations, documents, and published web pages from the same interface', 'Export to PowerPoint for further editing in familiar tools', 'Plus at $8/mo provides unlimited AI generations — excellent value'],
    'cons': ['Generated output often requires editing for precise brand alignment', 'Web editor less powerful than PowerPoint for complex animations or custom layouts', 'Free tier credit limit (400 credits) restricts exploration before committing', 'Ultra tier pricing not fully transparent — requires contacting Gamma'],
  },
  'motion': {
    'badge': 'paid', 'users': '',
    'best_for': 'AI calendar and task scheduler that builds your daily plan automatically',
    'description': 'AI-powered calendar app that automatically schedules tasks, meetings, and projects into your calendar. No free plan. Pro AI $19/mo, Business AI $29/seat/mo. Pivoted to "AI Super App" in 2025.',
    'description_long': "Motion is an AI-powered productivity tool that automatically schedules tasks, meetings, and projects into your calendar based on priorities, deadlines, and available time blocks. Rather than manually blocking time for tasks, users tell Motion what needs to be done and when it is due — Motion then arranges the work into the calendar, rescheduling automatically when meetings are added or tasks take longer than planned.\n\nIn 2025, Motion pivoted toward an 'AI Super App' vision, adding AI documents (context-aware document creation that understands your calendar and tasks), AI sheets (spreadsheets with meeting and project context built in), and expanded project management capabilities. This positions Motion as an integrated work environment rather than just a scheduling tool.\n\nKey capabilities include automatic daily schedule generation from task lists and deadlines, intelligent rescheduling when meetings are added or tasks slip, project management with automatic resource leveling, team scheduling for coordinating across multiple calendars, AI documents with context awareness, and integrations with Google Calendar, Outlook, and Zoom.\n\nPricing: There is no free plan. Pro AI costs $19 per month (billed monthly) or $12 per month (billed annually). Business AI costs $29 per seat per month (monthly) or $20 per seat per month (annual). There is no free tier or trial without providing payment information.\n\nLimitations: No free plan means users must commit without trying the core scheduling experience. The automatic scheduling approach requires trusting the AI's time allocation decisions — users who want manual control over their schedule will find Motion frustrating. Some users report the AI's schedule rebuilding multiple times per day as disruptive.\n\nBest suited for high-velocity knowledge workers, managers, and entrepreneurs who have more tasks and meetings than they can manually manage and want AI to handle the scheduling logistics of the workday.",
    'pros': ['Automatically builds and rebuilds your daily schedule from tasks and deadlines', 'Rescheduling AI adapts in real time when meetings are added or tasks take longer', 'AI documents and sheets provide context-aware work environment', 'Project management with automatic resource leveling across team schedules', 'Integrates with Google Calendar and Outlook — works with existing calendar tools'],
    'cons': ['No free plan — must pay before trying the core scheduling experience', 'Automatic schedule rebuilding can feel disruptive to users who prefer manual control', 'AI Super App pivot adds complexity — may be unfocused compared to specialized tools', 'At $19–29/mo, expensive relative to basic calendar apps'],
  },
  'notion-ai': {
    'badge': 'freemium', 'users': '100M+',
    'best_for': 'AI writing assistance and AI agents within Notion workspace',
    'description': 'AI assistant built into Notion for writing, summarizing, and automating tasks. IMPORTANT: Free and Plus plans limited to 20 total AI responses EVER. Business $20/user/mo for unlimited AI Agents. 100M users.',
    'description_long': "Notion AI is the AI capability layer built into Notion, the widely used workspace and notes platform with 100 million users. The AI features include writing assistance, document summarization, Q&A across your workspace, AI-generated meeting notes, and as of 2025, AI Agents that can take actions inside Notion — creating pages, updating databases, and running multi-step automations autonomously.\n\nA critical change in 2025 severely limited AI access on lower tiers: Free and Plus Notion plans are now capped at 20 total AI responses lifetime — not per month, but cumulative forever. This makes AI essentially non-functional for regular use on free and Plus plans. Unlimited AI Agent access requires the Business plan at $20 per user per month.\n\nKey capabilities include AI writing, editing, and summarization within Notion documents; Ask AI for questions across your workspace; AI-generated meeting notes from transcripts; AI Agents that automate multi-step Notion workflows; integration with Notion databases for AI-powered data processing; and AI search across all workspace content.\n\nPricing: Free and Plus plans: 20 total AI responses lifetime (not per month). Business at $20 per user per month provides unlimited AI Agents, unlimited AI Q&A, and all AI features. Enterprise pricing is custom.\n\nLimitations: The 20-lifetime-response limit on Free and Plus plans makes Notion AI practically unusable for regular users at those tiers. The only real Notion AI plan is Business at $20/user/month, which is expensive per seat for larger teams. AI quality for niche or specialized content can be inconsistent.\n\nBest suited for teams already on Notion Business who want AI writing, summarization, and agents integrated into their existing workspace — the AI adds significant value at the Business tier, but the lower-tier limitations are severe.",
    'pros': ['Native AI within the Notion workspace — no switching tools for writing and summarization', 'AI Agents automate multi-step Notion workflows autonomously', 'Ask AI searches across all workspace content for answers', 'AI meeting notes integration with transcription tools', '100M users — most widely adopted workspace tool globally'],
    'cons': ['Free and Plus plans: only 20 LIFETIME total AI responses — essentially non-functional', 'Business plan at $20/user/mo required for unlimited AI — expensive per seat', 'AI Agents limited to Notion actions — cannot reach external systems without integrations', 'Quality of AI writing varies for specialized or technical content'],
  },
  'otter-ai': {
    'badge': 'freemium', 'users': '10M+',
    'best_for': 'AI meeting transcription and notes for individuals and small teams',
    'description': 'AI meeting transcription and note-taking assistant. Joins video calls or transcribes uploaded recordings. Auto-generates summaries and action items. Free 300min/mo; Pro $8.33/mo annual.',
    'description_long': "Otter.ai is an AI meeting transcription and note-taking service with over 10 million users. It attends Zoom, Google Meet, and Microsoft Teams meetings automatically, transcribes in real time, and generates AI summaries with action items after each meeting. Users can also upload audio and video files for transcription.\n\nOtter positions itself as accessible and affordable compared to enterprise meeting tools — the free tier and Pro plan serve individual users and small teams well without requiring an enterprise contract. The OtterPilot feature automatically joins calendar-synced meetings, takes notes, and sends summaries to participants, removing the need to manually start recording.\n\nKey capabilities include real-time transcription in meetings, speaker identification (diarization), AI summary generation, action item extraction, transcript search and highlighting, automated meeting summaries emailed to participants, integrations with Zoom, Google Calendar, and Outlook, and a mobile app for in-person meeting transcription.\n\nPricing: Free plan provides 300 minutes per month of transcription and limited AI features. Pro at $8.33 per month (annual billing) or $16.99 per month (monthly) provides 1,200 minutes per month, advanced AI summaries, and custom vocabulary. Business at $19.99 per user per month provides 6,000 minutes, team management, and priority support. Enterprise pricing includes compliance features and SSO.\n\nLimitations: Transcription accuracy in meetings with significant background noise, accents, or technical jargon is lower than advertised. The free tier 300-minute limit is adequate for occasional users but insufficient for daily meeting note-takers. Action item extraction quality depends heavily on meeting structure.\n\nBest suited for professionals who have 3-8 external or internal meetings per week and want automated transcription and notes without a significant time or cost investment.",
    'pros': ['OtterPilot automatically joins and transcribes all calendar-synced meetings', 'Free tier (300 min/mo) is genuinely usable for occasional meeting note needs', 'Pro at $8.33/mo annual is the most affordable paid AI meeting tool', 'Real-time transcription visible during the meeting to all participants', 'Mobile app enables transcription for in-person meetings'],
    'cons': ['Transcription accuracy drops with accents, background noise, or technical terminology', 'Free 300 min/month insufficient for daily meeting note-takers', 'Action item extraction requires clear verbal commitments — misses implied tasks', 'Business tier required for team management and higher transcription volumes'],
  },
  'reclaim-ai': {
    'badge': 'freemium', 'users': '100K+',
    'best_for': 'AI calendar optimization — automatically schedules focus time and habits',
    'description': 'AI calendar assistant that automatically schedules focus time, recurring habits, and 1:1 meetings around your priorities. Integrates with Google Calendar. Free Lite; Starter $8/user/mo; Business $12/user/mo.',
    'description_long': "Reclaim.ai is an AI calendar optimization tool that works within Google Calendar to automatically schedule focus time, recurring habits, personal tasks, and flexible meetings around fixed commitments. Unlike Motion which builds a full daily schedule, Reclaim focuses on protecting and optimizing time within an existing calendar rather than replacing calendar management entirely.\n\nThe core use cases are: scheduling focused work blocks that move automatically around meetings, maintaining daily and weekly habits (exercise, learning, deep work) by automatically finding and protecting time for them, and scheduling 1:1 meetings within shared availability windows. Reclaim continuously adjusts scheduled blocks as meetings are added or changed, ensuring protected time is always current.\n\nKey capabilities include automatic focus time scheduling, habit scheduling and protection, smart 1:1 meeting scheduling, task duration estimation, buffer time between meetings, team calendar analytics, and integrations with Slack (showing meeting status), Asana, Linear, Todoist, Jira, and Google Tasks.\n\nPricing: Free Lite plan provides basic focus time and habit scheduling for one user. Starter at $8 per user per month provides full features for individuals. Business at $12 per user per month adds team analytics, admin controls, and priority support. Enterprise pricing includes SSO and compliance features.\n\nLimitations: Reclaim only integrates with Google Calendar — Outlook and Microsoft 365 users cannot use it. The AI scheduling is conservative — it protects time but does not rebuild schedules as aggressively as Motion. Task scheduling requires Reclaim's own task interface or integrated task tools (Asana, Jira) rather than arbitrary task lists.\n\nBest suited for knowledge workers and teams on Google Calendar who want to protect focus time and maintain work habits without manually blocking calendar time every week.",
    'pros': ['Automatically protects focus time and habits around meeting schedules', 'Smart 1:1 meeting scheduling finds optimal shared windows automatically', 'Integrates with Slack, Asana, Linear, Todoist, Jira — works with existing tools', 'Gentle AI approach — optimizes calendar without completely rebuilding it like Motion', 'Starter at $8/user/mo very affordable for individuals'],
    'cons': ['Google Calendar only — no Microsoft Outlook or 365 support', 'Less aggressive schedule optimization than Motion — some users want more AI control', 'Task scheduling requires integrated task tool — no arbitrary task list support', 'Free tier limited — full feature set requires paid plan'],
  },
  'zapier-ai': {
    'badge': 'freemium', 'users': '2M+',
    'best_for': 'AI-powered workflow automation connecting 7,000+ apps',
    'description': 'The leading no-code automation platform with AI Agents for multi-step autonomous task execution. Free 100 tasks/mo; Professional $19.99/mo; Team $69/mo. AI Agents separately priced with usage-based billing.',
    'description_long': "Zapier is the leading no-code automation platform, connecting over 7,000 apps and enabling automated workflows (called Zaps) between them without coding. As of 2026, Zapier has expanded from trigger-action automation into AI Agents — autonomous multi-step workflows that use AI reasoning to make decisions, handle exceptions, and complete tasks that traditional rule-based automation cannot handle.\n\nZapier AI Agents represent a significant evolution: rather than fixed if-this-then-that logic, Agents can receive unstructured inputs (emails, messages, form submissions), use AI to interpret and route them, execute multiple conditional steps, and handle edge cases that would break traditional automation. This brings automation to workflows that previously required human judgment.\n\nKey capabilities include 7,000+ app integrations (the largest ecosystem in automation), traditional trigger-action Zaps, AI Agents for autonomous multi-step workflows, natural language automation building, tables and interfaces for simple app building, workflow debugging and monitoring, and an API for custom integrations.\n\nPricing: Free plan provides 100 tasks per month and supports 5 Zaps. Professional at $19.99 per month provides 750 tasks per month and unlimited Zaps. Team at $69 per month provides 2,000 tasks and multi-user management. AI Agents have separate consumption-based pricing on top of the subscription — billed per agent task run.\n\nLimitations: AI Agents are priced separately with consumption-based billing that adds to subscription costs — making total cost for heavy agent use difficult to predict. The platform's complexity grows quickly for advanced workflows. For teams with developer resources, direct API integrations are often more reliable and flexible than Zapier at high volume.\n\nBest suited for non-technical teams and individuals who want to automate repetitive workflows across multiple tools without writing code — from simple task automation to AI-powered multi-step business processes.",
    'pros': ['7,000+ app integrations — by far the largest automation ecosystem available', 'AI Agents handle unstructured inputs and exception cases that break rule-based automation', 'Natural language automation building — describe a workflow to generate it', 'Free plan (100 tasks/mo) is functional for simple individual automation', 'No coding required — accessible to non-technical users'],
    'cons': ['AI Agents priced separately on consumption basis — costs hard to predict', 'Platform complexity grows significantly for advanced multi-step workflows', 'Task limits on lower plans reached quickly for active automations', 'At high volume, direct API integrations often more reliable and cost-effective'],
  },

  # ── WRITING ───────────────────────────────────────────────────────────────────
  'deepl': {
    'badge': 'freemium', 'users': '100M+',
    'best_for': 'Professional-grade AI translation for documents and business content',
    'description': 'The highest-accuracy AI translation service used by 250K+ businesses. Translates documents, PDFs, and text with context awareness. DeepL Agent launched for automated translation workflows. Starter $10.49/mo.',
    'description_long': "DeepL is the professional-grade AI translation service recognized by linguists and translators as producing the most natural-sounding translations of any automated service. It supports 33 languages and is used by over 250,000 businesses and 100 million users globally — including the EU Parliament, which uses DeepL for official document translation.\n\nThe DeepL product line includes a web interface for text translation, document upload and download (preserving formatting in Word, PowerPoint, and PDF), a desktop app, browser extensions, and a Developer API. DeepL Agent, launched in 2025, enables automated translation workflows — triggering translations from file uploads, connecting to content management systems, and processing large document volumes without manual intervention.\n\nKey capabilities include high-accuracy text and document translation (Word, PowerPoint, PDF), glossary management for consistent company-specific terminology, tone settings (formal vs. informal), DeepL Agent for automated translation workflows, API with 99.9% uptime SLA, and browser extensions.\n\nPricing: Free plan provides limited character translations. Starter at $10.49 per month (annual) provides 1 million characters per month and document translations. Advanced at $34.49 per month provides 5 million characters, glossary management, and team features. Ultimate at $68.99 per month provides 20 million characters and highest API priority. Business plans with custom volumes are available.\n\nLimitations: DeepL covers 33 languages — significantly fewer than Google Translate (133 languages). For low-resource or uncommon language pairs, quality may not exceed competing services. The Starter character limit (1M/month) is quickly exhausted for document-heavy professional use.\n\nBest suited for businesses, law firms, consulting firms, and content teams that need professional-quality translation of business documents, communications, and marketing content.",
    'pros': ['Best-in-class translation quality — consistently rated above Google Translate by linguists', '250K+ business customers including EU Parliament', 'Glossary management ensures consistent company-specific terminology', 'DeepL Agent enables automated translation workflows at scale', 'Preserves document formatting when translating Word, PowerPoint, and PDF'],
    'cons': ['33 languages only — limited compared to Google Translate (133 languages)', 'Starter character limit (1M/mo) insufficient for document-heavy professional use', 'More expensive than Google Cloud Translation API for high-volume programmatic use', 'Agent and automation features require higher-tier plans'],
  },
  'grammarly': {
    'badge': 'freemium', 'users': '40M+',
    'best_for': 'AI writing assistant for grammar, style, tone, and clarity improvements',
    'description': 'The leading AI writing assistant with 40M daily active users. Checks grammar, style, tone, and clarity across all apps via browser extension. Free 100 prompts/mo; Pro $12/mo annual.',
    'description_long': "Grammarly is the most widely used AI writing assistant, with 40 million daily active users and integrations across Microsoft Office, Google Docs, Gmail, Slack, and virtually any text field via its browser extension. The product is used by individuals for personal writing improvement and by businesses for maintaining consistent communication standards.\n\nGrammarly checks and corrects grammar, spelling, punctuation, style, clarity, engagement, and delivery. The AI generative features (Pro) allow full-sentence rewrites, tone adjustment, email drafting from bullet points, and document summaries. The tone detector is particularly useful for business communications — identifying whether a message reads as confident, diplomatic, formal, or empathetic before sending.\n\nKey capabilities include real-time grammar and style correction, tone detection and adjustment, AI text generation and rewriting, document summarization, plagiarism detection (Pro), 500K+ word spell-check database, browser extension for all web apps, Microsoft Office and Google Docs add-ons, and a Grammarly keyboard for mobile.\n\nPricing: Free plan provides grammar and spelling correction with basic style suggestions and 100 AI prompt uses per month. Pro at $12 per month (annual) or $30 per month (monthly) provides full AI generative features, tone rewriting, plagiarism detection, and unlimited AI prompts. Business (formerly available as a tier) has been moved to Enterprise-only for organizations above a certain size — business teams now need to contact sales.\n\nLimitations: The Pro plan at $30/month (monthly) is expensive — the $12/month rate requires annual commitment. Removing the Business tier creates a gap between individual Pro and Enterprise, complicating pricing for small business teams. Grammarly's corrections are context-unaware at scale — it sometimes flags intentional stylistic choices as errors.\n\nBest suited for professionals, students, and content creators who write significant volumes of email, documents, and content and want real-time AI feedback on clarity and correctness without switching tools.",
    'pros': ['40M daily active users — most widely adopted writing assistant', 'Works across all apps via browser extension — no workflow change required', 'Tone detector identifies how messages read before sending', 'Free tier provides real grammar and style correction — genuinely useful without paying', 'Microsoft Office and Google Docs integrations for native document editing'],
    'cons': ['Pro monthly rate ($30/mo) expensive — annual commitment required for $12/mo', 'Business tier removed — teams now require Enterprise pricing (contact sales)', 'Context-unaware corrections sometimes flag intentional stylistic choices as errors', 'Generative AI features less sophisticated than purpose-built writing tools'],
  },
  'hemingway-editor': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Plain language writing — identifies complex sentences and passive voice',
    'description': 'Writing clarity tool that highlights overly complex sentences, passive voice, adverbs, and readability issues. Free web version; Desktop $19.99 one-time; Editor Plus $25/mo (AI rewrites) or $100/yr.',
    'description_long': "Hemingway Editor is a writing clarity tool named after Ernest Hemingway's famously direct prose style. Rather than fixing grammar, it highlights structural writing problems: sentences that are too complex, passive voice constructions, excessive adverbs, and phrases with simpler alternatives. The color-coded highlights make it immediately obvious where writing needs simplification.\n\nThe tool calculates a reading grade level for the text and targets a Grade 9 reading level as the standard for broad accessibility. It has been widely used by bloggers, journalists, content marketers, and technical writers who need to write clearly for general audiences.\n\nEditor Plus, launched in 2024, adds AI-powered rewrite suggestions to the classic editing interface — when Hemingway highlights a problematic sentence, AI rewrites propose simpler alternatives. This transitions Hemingway from a passive analysis tool to an active writing assistant.\n\nKey capabilities include color-coded readability highlights (complexity, passive voice, adverbs, weak phrasing), reading grade level calculation, AI rewrite suggestions (Editor Plus), export to Word and Markdown, and a distraction-free writing environment.\n\nPricing: Free at hemingwayapp.com for basic use. Hemingway Editor desktop app for Windows and macOS costs $19.99 as a one-time purchase. Editor Plus web subscription costs $25 per month or $100 per year and adds AI rewrite suggestions, more extensive AI capabilities, and sync across devices.\n\nLimitations: Hemingway's rules are absolute — it flags all passive voice and long sentences regardless of whether they are intentional stylistic choices. The tool is most useful for business writing and content marketing; creative writers and academics may find the Grade 9 target overly restrictive. AI rewrites in Editor Plus can oversimplify nuanced language.\n\nBest suited for content marketers, bloggers, and business writers who want to improve readability and directness in their writing — particularly those who tend toward complex sentence structures.",
    'pros': ['Immediately shows readability problems with color-coded highlights', 'One-time $19.99 desktop purchase — no recurring subscription for core features', 'Simple, focused interface minimizes distraction during editing', 'Editor Plus AI rewrites suggest simpler alternatives for flagged sentences', 'Grade level calculator ensures content is accessible to intended audiences'],
    'cons': ['Flags all passive voice and long sentences — even intentional stylistic choices', 'Grade 9 readability target too restrictive for academic or technical writing', 'AI rewrites can oversimplify nuanced language', 'Editor Plus at $25/mo expensive for what is a single-function clarity tool'],
  },
  'jasper': {
    'badge': 'paid', 'users': '70K+',
    'best_for': 'Enterprise AI content and GTM automation for marketing teams',
    'description': 'Enterprise AI writing platform pivoting to GTM (go-to-market) automation. 70K paying customers. Creator $39/mo annual; Pro $59/mo; Teams $125/mo (3 seats). Focus on brand voice and team workflows.',
    'description_long': "Jasper is an enterprise AI content platform that started as an AI writing assistant and has been pivoting toward go-to-market (GTM) automation — positioning itself as the AI layer for entire marketing operations rather than just a writing tool. The platform is used by 70,000 paying customers, primarily marketing teams at mid-market and enterprise companies.\n\nJasper's differentiation centers on brand voice consistency at scale. The Brand Voice feature trains the AI on company tone, style, and messaging guidelines so that all generated content stays on-brand regardless of which team member creates it. The platform supports content creation across the full marketing workflow — blog posts, social copy, email sequences, ad creative, and landing pages — with templates for hundreds of specific use cases.\n\nKey capabilities include Brand Voice training on company content, 50+ templates for specific content types, multi-language generation, Jasper Art (AI image generation), a browser extension for in-app content generation, team collaboration and approval workflows, integrations with HubSpot, Salesforce, and Google Ads, and a Campaign workflow for cross-channel content creation.\n\nPricing: Creator at $39 per month (annual) for individuals provides access to all AI writing features. Pro at $59 per month (annual) adds Brand Voice, 3 brand voices, and advanced AI features. Teams at $125 per month (annual) provides 3 seats, team collaboration, and campaign workflows. Enterprise pricing is custom.\n\nLimitations: Jasper's pricing is significantly higher than alternatives like Writesonic or QuillBot for equivalent capabilities. The GTM pivot means the product roadmap may be moving away from the individual writing use case. For most content creation tasks, general-purpose AI tools like ChatGPT or Claude provide comparable output at lower cost.\n\nBest suited for mid-market and enterprise marketing teams with established brand guidelines that need AI content generation at scale with brand consistency controls — not for individual writers looking for basic AI writing assistance.",
    'pros': ['Brand Voice feature trains AI on company tone for consistent on-brand content at scale', 'Comprehensive template library covers the full marketing content workflow', 'Campaign workflow enables coordinated multi-channel content creation', 'Team collaboration with approval workflows for enterprise content governance', 'Integrations with HubSpot, Salesforce, and Google Ads for GTM workflows'],
    'cons': ['Significantly more expensive than alternatives for individual writing use — Pro $59/mo', 'GTM automation pivot may be moving away from core writing assistance use case', 'General-purpose AI (ChatGPT, Claude) provides comparable quality at lower cost for most tasks', 'Teams plan at $125/mo (3 seats) expensive relative to capabilities'],
  },
  'quillbot': {
    'badge': 'freemium', 'users': '35M+',
    'best_for': 'AI paraphrasing, summarizing, and grammar checking for students and writers',
    'description': 'AI writing tool with 35M monthly active users specializing in paraphrasing, summarizing, and grammar checking. Includes an AI Humanizer. Free 125 words; Premium $8.33/mo annual.',
    'description_long': "QuillBot is a specialized AI writing tool with 35 million monthly active users, built around paraphrasing, summarizing, grammar checking, and citation generation. Unlike general-purpose AI writers, QuillBot focuses on improving and transforming existing text rather than generating from scratch — making it particularly popular among students and non-native English writers.\n\nThe core paraphrasing tool offers multiple modes (Standard, Fluency, Formal, Academic, Creative, Concise, and Expand) that transform text in different ways while preserving meaning. The AI Summarizer condenses long documents into key points. The Grammar Checker catches errors and suggests rewrites. In 2024, QuillBot added an AI Humanizer feature that attempts to make AI-generated text less detectable by AI detection tools.\n\nKey capabilities include multi-mode paraphraser, document summarizer, grammar checker, citation generator (MLA, APA, Chicago), plagiarism checker, translator, AI Humanizer, and integrations with Microsoft Word, Google Docs, and Chrome.\n\nPricing: Free plan provides paraphrasing up to 125 words at a time, summarization up to 600 words, and basic grammar checking. Premium at $8.33 per month (annual) or $19.95 per month (monthly) removes word limits, unlocks all modes, and adds the full feature set including AI Humanizer and unlimited plagiarism checks. A student discount is available.\n\nLimitations: The 125-word limit on the free paraphrasing tool is very restrictive — it is the primary driver of upgrading to Premium. The AI Humanizer, while useful, does not guarantee detection evasion as AI detection tools continuously improve. Academic integrity concerns apply to paraphrasing tools in educational contexts.\n\nBest suited for students, ESL writers, and content creators who need to rephrase, summarize, or check existing text — rather than generate original long-form content from scratch.",
    'pros': ['35M MAU — most widely used paraphrasing tool globally', 'Multiple paraphrase modes (Formal, Academic, Creative, Concise) for different contexts', 'AI Humanizer reduces detectability of AI-generated content', 'Citation generator supports MLA, APA, and Chicago formats', 'Premium at $8.33/mo annual is very affordable for students'],
    'cons': ['Free tier limited to 125-word paraphrasing — major restriction for real use', 'Paraphrasing tool raises academic integrity concerns in educational settings', 'AI Humanizer detection evasion not guaranteed as detection tools improve', 'Focused on transforming existing text — not suitable for original content creation'],
  },
  'writesonic': {
    'badge': 'freemium', 'users': '200K+',
    'best_for': 'AI content writing and GEO (Generative Engine Optimization) for AI search visibility',
    'description': 'AI writing platform pivoting to GEO — optimizing content for visibility in ChatGPT, Perplexity, Claude, and Gemini answers. Free limited; Lite $39/mo; Professional ~$98/mo. 200K users.',
    'description_long': "Writesonic is an AI content platform with 200,000 users that has been pivoting from general AI writing toward Generative Engine Optimization (GEO) — the emerging practice of optimizing content to appear in AI-generated answers from ChatGPT, Perplexity, Claude, and Gemini, rather than just in traditional Google search results.\n\nThe core product includes an AI Article Writer that generates SEO-optimized long-form articles, a chatbot builder (Botsonic) for AI customer service, social media content generation, landing page copy, and email marketing content. The GEO positioning reflects market awareness that brands increasingly need to rank in AI assistant answers in addition to Google.\n\nKey capabilities include long-form AI article writing, GEO content optimization for AI search visibility, Botsonic chatbot builder, social media content generation, landing page and ad copy, brand voice settings, SEO integration, and a real-time AI visibility tracker across ChatGPT, Perplexity, and Gemini.\n\nPricing: Free plan provides limited words and features for testing. Lite at $39 per month provides enhanced word limits and core features. Professional at approximately $98 per month provides unlimited generation, GEO tools, and advanced features. Enterprise pricing is custom.\n\nLimitations: Writesonic's Lite plan at $39 per month is expensive relative to competitors like Jasper or general-purpose tools. The GEO positioning is emerging and the actual impact on AI search visibility is difficult to measure. The product is still maturing on the GEO tooling, which is a newer capability.\n\nBest suited for content marketers and SEO teams who want to optimize content for both traditional search and AI-generated answer engines, particularly those tracking brand mentions in ChatGPT and Perplexity responses.",
    'pros': ['GEO tooling tracks and optimizes content visibility in ChatGPT, Perplexity, Claude, and Gemini', 'AI Article Writer produces SEO-optimized long-form content efficiently', 'Botsonic enables AI chatbot creation without development resources', 'Brand voice settings ensure consistent tone across generated content', 'Real-time AI visibility tracker across major LLM answer engines'],
    'cons': ['Lite plan at $39/mo expensive for AI writing relative to alternatives', 'GEO impact difficult to measure — ROI on AI search optimization not yet proven', 'User count (200K) small relative to competitors like Grammarly (40M DAU)', 'General AI writing quality comparable to cheaper or free alternatives'],
  },
}

def patch(slug, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        f'{SB_URL}/rest/v1/tools?slug=eq.{slug}&lang=eq.en',
        data=body, headers=HDRS, method='PATCH'
    )
    with urllib.request.urlopen(req) as r:
        return r.status

print(f'Updating {len(UPDATES)} tools...')
for slug, fields in UPDATES.items():
    status = patch(slug, fields)
    print(f'  {slug}: HTTP {status}')

print('Done.')
