#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Update EN content for voice and education categories."""
import urllib.request, json, os

SB_URL     = 'https://lbjdwkvkkndvofysyssy.supabase.co'
SB_SERVICE = os.environ.get('SB_SERVICE_KEY', '')
if not SB_SERVICE:
    print('ERROR: Set SB_SERVICE_KEY'); exit(1)

HDRS = {
    'apikey': SB_SERVICE,
    'Authorization': f'Bearer {SB_SERVICE}',
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

UPDATES = {
  # ── VOICE ─────────────────────────────────────────────────────────────────────
  'adobe-podcast': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI audio enhancement and recording for podcasters and content creators',
    'description': 'Adobe\'s AI audio tool for recording, enhancing, and editing podcast-quality audio. AI removes background noise and mic quality issues automatically. Free 30min/500MB; Premium $9.99/mo.',
    'description_long': "Adobe Podcast (podcast.adobe.com) is Adobe's AI-powered audio tool for content creators who record voice content — podcasters, YouTubers, educators, and remote workers — and need to clean up recordings made in imperfect environments. The flagship feature is Enhance Speech, which uses AI to remove background noise, reverb, echo, and room tone from audio files, making a laptop microphone recording sound like a professional studio recording.\n\nThe platform has expanded from a single enhancement tool into a fuller podcast production workflow. Users can record directly in the browser with AI background removal applied in real-time, transcribe recordings, edit audio by editing the transcript text (cut/paste text to cut/paste audio), and generate chapters automatically. Adobe Podcast is part of Adobe's Creative Cloud ecosystem but available as a standalone web tool without a full Creative Cloud subscription.\n\nKey capabilities include AI speech enhancement (background noise removal, reverb reduction), browser-based recording with live AI processing, transcript-based editing, automatic chapter generation, multi-track editing, and export to standard audio formats.\n\nPricing: Free plan provides 30 minutes of audio upload per month with a 500MB file size limit for enhancement. Premium at $9.99 per month or $99.99 per year removes limits, adds longer recordings, higher quality output, and team collaboration. Creative Cloud All Apps subscribers have Premium included.\n\nLimitations: The 30 minutes per month limit on the free tier restricts regular podcast use. Enhancement quality is excellent for voice isolation but struggles with music or complex audio. Not a full digital audio workstation — editing capabilities are simpler than Audacity or Adobe Audition.\n\nBest suited for podcasters, YouTubers, remote workers, and educators who need to quickly clean up voice recordings made in noisy or reverberant environments without professional recording setups.",
    'pros': ['Enhance Speech AI removes background noise and room reverb — makes laptop mics sound professional', 'Transcript-based editing lets you cut audio by editing text', 'Free tier available — 30 min/month sufficient for occasional use', 'Browser-based — no software installation required', 'Premium at $9.99/mo is affordable for regular podcasters'],
    'cons': ['Free tier limited to 30 minutes/month — insufficient for weekly podcasters', 'Not a full DAW — editing capabilities simpler than Audacity or Audition', 'Enhancement optimized for voice — struggles with music or complex mixed audio', 'Transcript-based editing less precise than waveform editing for fine cuts'],
  },
  'descript': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Podcast and video editing by editing the text transcript',
    'description': 'Podcast and video editor that works by editing a text transcript. AI removes filler words, clones your voice, and generates B-roll. Moved to minutes+credits model Sep 2025. Free 60min/mo; Creator $24/mo.',
    'description_long': "Descript is a podcast and video editing application built around transcript-based editing — rather than traditional waveform or timeline editing, users edit the transcript text and the audio/video edits automatically follow. This approach makes removing mistakes, cutting segments, and reorganizing content dramatically faster for non-technical creators.\n\nIn September 2025, Descript shifted from a seat-based pricing model to a minutes-plus-credits model — users pay for transcription minutes and AI feature credits separately. Key AI features include Overdub (voice cloning — generates new audio in your voice from text), Studio Sound (audio enhancement similar to Adobe Podcast's Enhance Speech), Underlord AI (removes filler words like 'um' and 'uh' automatically), AI screen recorder, and AI B-roll generation from text descriptions.\n\nKey capabilities include transcript-based audio and video editing, AI filler word removal, voice cloning (Overdub), audio enhancement (Studio Sound), AI B-roll generation, screen recording with AI commentary, multi-track podcast editing, and export to video formats or audio-only podcasts.\n\nPricing: Free plan provides 60 minutes of transcription per month and limited AI feature access. Hobbyist at $16 per month provides 180 minutes per month. Creator at $24 per month provides 300 minutes per month and full AI feature access including Overdub and Studio Sound. Business at $50 per month provides 600 minutes and team collaboration. Additional transcription minutes and AI credits are purchased separately.\n\nLimitations: The minutes+credits model introduced in September 2025 makes costs harder to predict for heavy users. Voice cloning (Overdub) quality, while good, requires a minimum 10-minute voice sample. The transcript-based editing approach is intuitive for talk-based content but limits complex multi-track music or sound design work.\n\nBest suited for podcasters, documentary filmmakers, course creators, and video editors who produce interview or talk-based content and want to work faster by editing text rather than waveforms.",
    'pros': ['Transcript-based editing dramatically speeds up podcast and interview editing', 'AI filler word removal eliminates ums, ahs, and false starts in one click', 'Overdub voice cloning generates new audio in your voice from text', 'Studio Sound AI enhancement removes background noise without Adobe Podcast', 'Screen recording with AI commentary generation for tutorial content'],
    'cons': ['Minutes+credits model (Sep 2025) makes costs less predictable than seat pricing', 'Overdub voice cloning requires 10+ minute voice sample for quality results', 'Less suitable for complex music production or multi-track mixing', 'Creator plan at $24/mo plus potential extra credit purchases'],
  },
  'elevenlabs': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Highest-quality AI voice generation and voice cloning for professionals',
    'description': 'Leading AI voice synthesis platform used by 60% of Fortune 500 companies. 3,000+ voices, 32 languages, voice cloning from 1 minute of audio. Free 10K credits; Creator $22/mo; Pro $99/mo.',
    'description_long': "ElevenLabs is the leading AI voice synthesis platform for professional voice generation, voice cloning, dubbing, and AI agent voice capabilities. It is used by 60% of Fortune 500 companies and has created over 250,000 AI voice agents deployed by businesses for customer service, IVR systems, and automated communications. The platform produces the highest-quality natural-sounding AI voices of any commercial service.\n\nCore capabilities include text-to-speech across 3,000+ voices and 32 languages, voice cloning from as little as one minute of audio, Dubbing Studio for translating and dubbing video content while preserving the original speaker's voice, an AI Voice Agent platform for building conversational voice bots, and a sound effects generator. The Conversational AI product enables building phone-based AI agents with natural speech.\n\nKey capabilities include 3,000+ AI voices with emotional range controls, professional voice cloning, multilingual dubbing with voice preservation, AI Voice Agent builder, sound effects generation, and a Developer API with sub-200ms latency for real-time applications.\n\nPricing: Free plan provides 10,000 characters (approximately 10 minutes of audio) per month. Starter at approximately $5 per month provides 30,000 characters. Creator at $22 per month provides 100,000 characters, professional voice cloning, and commercial use rights. Pro at $99 per month provides 500,000 characters and higher concurrency for AI agents. Scale and Business plans go up to $330 per month for high-volume production.\n\nLimitations: The character-based pricing model makes costs for long audio projects unpredictable. Professional voice cloning (Creator+) requires higher-tier plans. The AI Voice Agent product has a separate consumption-based pricing layer. For simple text-to-speech at scale, character costs add up quickly.\n\nBest suited for audiobook creators, content producers, enterprises building voice AI agents, and developers who need the highest-quality AI voice output for commercial applications.",
    'pros': ['Industry-leading voice quality — most natural-sounding AI voices commercially available', '3,000+ voices across 32 languages with emotional range controls', 'Professional voice cloning from 1 minute of audio', 'Dubbing Studio preserves original speaker voice when translating video', '60% Fortune 500 adoption validates enterprise-grade quality and reliability'],
    'cons': ['Character-based pricing makes long-form audio costs unpredictable', 'Professional voice cloning and commercial rights require paid plan ($22+/mo)', 'AI Voice Agents have separate consumption-based pricing on top of subscription', 'Pro plan at $99/mo required for high-volume production or concurrent agent use'],
  },
  'playht': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI text-to-speech and voice cloning for podcasts, articles, and apps',
    'description': 'AI text-to-speech platform with 900+ voices, voice cloning, and a WordPress plugin for auto-converting articles to audio. Free 12.5K chars/mo; Creator $31.20/mo; Unlimited $29/mo.',
    'description_long': "Play.ht is an AI text-to-speech platform that converts written content — blog posts, articles, newsletters, scripts — into natural-sounding audio. It has built a strong position with content publishers through its WordPress plugin, which automatically adds an audio player to every article using AI-generated voice. The platform offers 900+ voices across 142 languages.\n\nPlay.ht 3.0 introduced Ultra-realistic voice generation using a new model architecture, and the Voice Cloning feature creates a custom voice from a short audio sample. The platform offers an API for developers integrating text-to-speech into applications. The WordPress plugin is particularly valuable for publishers adding audio to articles without a manual recording workflow.\n\nKey capabilities include 900+ AI voices, voice cloning, WordPress plugin for article audio, API for application integration, podcast hosting (via partnered infrastructure), and support for SSML markup for fine-grained pronunciation control.\n\nPricing: Free plan provides 12,500 characters per month with watermarked audio. Creator at $31.20 per month (annual) provides 200,000 characters per month and commercial rights. The Unlimited plan at $29 per month provides unlimited characters with fair use policy. Enterprise pricing is custom.\n\nLimitations: The $31.20 Creator plan's character limit (200K/month) can be exhausted by high-volume article publishers. Voice quality, while strong, benchmarks slightly below ElevenLabs on naturalness metrics. The WordPress plugin is the key differentiator — without a publishing workflow, Play.ht has less differentiation versus competitors.\n\nBest suited for content publishers, bloggers, and newsletter creators who want to add audio versions of their written content, and developers who need a straightforward text-to-speech API.",
    'pros': ['WordPress plugin auto-converts articles to audio — ideal for publishers', '900+ voices across 142 languages', 'Unlimited plan at $29/mo provides unlimited characters — best value for high volume', 'Voice cloning enables custom brand voice creation', 'API for developer integration into custom applications'],
    'cons': ['Voice quality slightly below ElevenLabs on naturalness benchmarks', 'WordPress plugin is the key differentiator — less compelling without a publishing workflow', 'Creator plan character limits (200K/mo) can be exhausted by high-volume publishers', 'Free tier watermarks audio — not usable for commercial content'],
  },
  'speechify': {
    'badge': 'freemium', 'users': '20M+',
    'best_for': 'Text-to-speech reading assistant for documents, PDFs, and web pages',
    'description': 'AI reading assistant that converts any text — PDFs, web pages, Google Docs, emails — to audio at up to 4.5x reading speed. 20M+ users. Free tier; Premium $29/mo. NOTE: F-rating from BBB for subscription cancellation issues.',
    'description_long': "Speechify is an AI-powered text-to-speech reading assistant with over 20 million users, designed for people who prefer to consume written content by listening. It converts PDFs, web articles, Google Docs, emails, ebooks, and physical books (via camera scan) into audio using natural-sounding AI voices — at adjustable speeds up to 4.5x the typical reading pace.\n\nThe core use case is productivity for consumers: listening to documents while commuting, consuming reading material faster, or supporting dyslexia and other reading differences. The AI summarization feature condenses long documents into brief summaries. Speechify AI Studio, launched in 2024, adds text-to-speech voice cloning and voice-over production tools targeting creators rather than readers.\n\nKey capabilities include text-to-speech for PDFs, web pages, Google Docs, emails, and scanned text; speeds up to 4.5x; AI summarization; 200+ natural AI voices; Chrome extension for web reading; and iOS/Android apps.\n\nPricing: Free tier provides access to basic voices and limited features. Premium at $29 per month provides all voices, unlimited listening, and advanced AI features. An annual plan reduces the effective monthly cost. Speechify AI Studio has separate pricing for voice creation features.\n\nLimitations: Speechify has an F-rating from the Better Business Bureau (BBB) as of 2026, driven by user complaints about unauthorized charges and difficulty canceling subscriptions. This is a significant red flag for potential subscribers. The tool is optimized for consumption, not creation — it is not a podcast production tool.\n\nBest suited for professionals, students, and individuals with dyslexia who want to consume large volumes of written content faster by listening, but prospective subscribers should be aware of the reported billing and cancellation issues.",
    'pros': ['Converts any text source — PDFs, web pages, Google Docs, emails, scanned text — to audio', '4.5x speed listening enables consuming written content much faster', 'AI summarization condenses long documents into brief audio summaries', '20M+ users — widely adopted consumer reading tool', 'Chrome extension enables instant web article reading without manual import'],
    'cons': ['F-rating from Better Business Bureau — reported unauthorized charges and cancellation difficulties', 'Premium at $29/mo expensive for what is primarily a text-to-speech tool', 'Not suitable for podcast or voice production — purely a reading/consumption tool', 'AI voice quality at fast speeds can sound unnatural for some content types'],
  },
  'suno': {
    'badge': 'freemium', 'users': '12M+',
    'best_for': 'AI music generation — create full songs from text prompts',
    'description': 'The leading AI music generator — creates full songs with vocals and instrumentation from text prompts. 2M paid subscribers, $300M ARR, $5B+ valuation. Free limited; Pro $8/mo; Premier $30/mo.',
    'description_long': "Suno is the leading AI music generation platform, enabling anyone to create full songs — with vocals, instrumentation, and production — from text prompts describing style, mood, genre, and theme. It has the largest user base of any AI music tool, with 12 million users, 2 million paid subscribers, and approximately $300 million in annualized recurring revenue as of 2026. The company's $5 billion-plus valuation reflects investor confidence in AI's disruption of music creation.\n\nSuno V4 (the current version) produces music that is significantly more polished and consistent than earlier versions — handling tempo transitions, dynamics, and vocal phrasing at near-professional quality for certain genres. The Premier plan adds DAW export capabilities including MIDI and stem downloads, enabling integration with professional music production workflows.\n\nKey capabilities include text-to-song generation with vocals and full instrumentation, style and genre controls, extend/remix of generated songs, lyrics input for generated vocals, MIDI and stem export on Premier, and a mobile app for generation on the go.\n\nPricing: Free plan provides 50 credits per day (approximately 10 songs). Pro at $8 per month provides 2,500 credits per month, commercial rights, and unlimited non-commercial downloads. Premier at $30 per month provides 10,000 credits per month, commercial rights, MIDI export, stem downloads, and priority generation.\n\nLimitations: Suno is currently in litigation with major music labels (UMG, Sony) over copyright issues related to its training data — the legal outcome could affect the platform significantly. Generated music can sound formulaic for complex genres and lacks the nuance of human composition. MIDI and stem exports require the Premier plan.\n\nBest suited for musicians who want to prototype song ideas quickly, content creators who need background music, and non-musicians who want to create music for personal or commercial projects.",
    'pros': ['Full song generation with vocals and instrumentation from text prompts', '2M paid subscribers and $300M ARR — most commercially proven AI music platform', 'Pro at $8/mo provides 2,500 credits and commercial rights — excellent value', 'Premier adds MIDI and stem exports for DAW integration', 'V4 produces near-professional quality for many popular genres'],
    'cons': ['Active copyright litigation with major music labels — legal uncertainty', 'Generated music can sound formulaic for complex or niche genres', 'MIDI export and stems require Premier plan ($30/mo)', 'Vocals and lyrics occasionally misaligned with music timing on complex prompts'],
  },
  'udio': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI music creation with high sonic quality — note: download restrictions apply',
    'description': 'AI music generator with high-fidelity audio quality. WARNING: full track downloads restricted to paid subscribers following copyright settlement with UMG and Warner. Standard $10/mo, Pro $30/mo.',
    'description_long': "Udio is an AI music generation platform that competes with Suno on audio quality — many users rate Udio's sonic fidelity and production quality higher than competitors on certain genres, particularly electronic, ambient, and instrumental music. The platform generates full tracks from text prompts specifying genre, mood, tempo, and style.\n\nFollowing a copyright settlement with Universal Music Group and Warner Music Group in early 2026, Udio implemented significant restrictions on the free tier. Free users can generate music and listen within the platform but cannot download full tracks. Downloads of complete generated tracks are restricted to paid subscribers (Standard and above). This creates a meaningful limitation for free tier users who want to use generated audio in their own content.\n\nKey capabilities include text-to-music generation with high sonic fidelity, style and mood controls, track extension and variation, inpainting for editing specific sections of generated tracks, and a browser-based generation interface.\n\nPricing: Free plan provides limited generations per month with playback within the platform only — no full track downloads. Standard at $10 per month provides 1,200 credits (approximately 120 tracks) and download access. Pro at $30 per month provides 4,800 credits and priority generation.\n\nLimitations: Download restrictions on the free tier make Udio largely a walled garden for non-paying users — you can hear what you generated but cannot export or use it. The copyright settlement indicates ongoing legal risk in the AI music space. Suno has a larger community and more training data at this stage.\n\nBest suited for musicians and producers who prioritize audio quality over platform community size, and who are willing to subscribe to access downloads — particularly for electronic, ambient, and instrumental genres.",
    'pros': ['High-fidelity audio quality — competitive with or exceeding Suno on certain genres', 'Inpainting enables editing specific sections of generated tracks', 'Clean interface with good style and mood controls', 'Standard at $10/mo is lower entry price than Suno Pro ($8/mo, similar credits)'],
    'cons': ['Full track downloads restricted to paid subscribers — free tier is a walled garden', 'Copyright settlement with UMG and Warner creates ongoing legal uncertainty', 'Smaller community than Suno — fewer shared examples and style references', 'Platform future unclear given copyright pressures'],
  },
  'whisper': {
    'badge': 'free', 'users': '',
    'best_for': 'Open-source speech-to-text transcription — developer tool, not a consumer product',
    'description': 'OpenAI\'s open-source speech recognition model. State-of-the-art transcription accuracy across 99 languages. Free to run locally; API $0.006/minute. Developer tool — no built-in consumer UI.',
    'description_long': "Whisper is OpenAI's open-source speech recognition model, released in September 2022 and updated to Whisper v3 Large in late 2023. It is trained on 680,000 hours of multilingual web audio and achieves state-of-the-art transcription accuracy across 99 languages, with particularly strong performance on non-English speech compared to competing commercial services.\n\nWhisper is a developer-oriented tool — it ships as a Python package with no consumer-facing application. Developers run it locally on their own hardware (GPU recommended for speed), integrate it via OpenAI's API, or use it through third-party wrappers that add user interfaces. Many of the transcription tools in this catalog (Descript, Otter.ai) use Whisper or Whisper-derived models as their underlying transcription engine.\n\nKey capabilities include speech-to-text transcription in 99 languages, automatic language detection, translation to English from any supported language, timestamp-level output (word and segment), and multiple model size variants from tiny (fastest) to large-v3 (most accurate). The large-v3 model achieves near-human accuracy on clean audio in major languages.\n\nPricing: The model itself is free and open-source (MIT license) — downloadable from GitHub and runnable on local hardware. OpenAI's hosted Whisper API costs $0.006 per minute of audio, making it one of the most affordable commercial transcription APIs. There is no subscription — pay only for what you use.\n\nLimitations: Whisper has no consumer-facing interface — users need either technical knowledge to run it locally or use a third-party wrapper. Local inference requires significant RAM and benefits substantially from a GPU. The API is usage-based with no usage dashboard built into a consumer product.\n\nBest suited for developers building transcription into applications, researchers who need high-accuracy multilingual transcription, and technically capable users comfortable running Python scripts or using the API.",
    'pros': ['State-of-the-art transcription accuracy across 99 languages — free and open-source', 'API at $0.006/minute is among the most affordable commercial transcription services', 'Strong performance on non-English and heavily accented speech', 'Multiple model sizes — tiny for speed, large-v3 for maximum accuracy', 'MIT license — freely usable in commercial applications without royalties'],
    'cons': ['No consumer-facing UI — developer tool requiring technical knowledge to use', 'Local inference requires GPU for reasonable speed on long audio', 'No built-in usage dashboard or account management', 'Large-v3 model slow on CPU — cloud API recommended for production use'],
  },

  # ── EDUCATION ─────────────────────────────────────────────────────────────────
  'coursera-coach': {
    'badge': 'paid', 'users': '148M+',
    'best_for': 'AI learning coach for Coursera courses with personalized guidance',
    'description': 'AI learning assistant built into Coursera\'s platform. Provides personalized course recommendations, explains difficult concepts, and gives feedback on assignments. Requires Coursera Plus ($399/yr).',
    'description_long': "Coursera Coach is the AI-powered learning assistant integrated into Coursera's online learning platform. It is not a standalone product — access requires a Coursera Plus subscription ($399 per year or $59 per month). Coursera Plus provides unlimited access to 10,000+ courses and professional certificates from 300+ universities and companies, and Coach is embedded throughout this experience.\n\nCoach functions as a contextual tutor within courses: it can explain difficult concepts in the current lecture, suggest practice problems, answer questions about course material, and recommend related courses based on learning progress and goals. It also supports assignment help — providing hints and explanations without giving direct answers, in line with academic integrity policies.\n\nKey capabilities include personalized course recommendations based on learning goals and history, concept explanation within active courses, assignment assistance with hints and explanations, progress analysis, skill gap identification, and learning path suggestions across Coursera's catalog.\n\nPricing: Coursera Coach is included with Coursera Plus at $399 per year ($33.25/month effective) or $59 per month. Individual course purchases do not include Coach access. Enterprise and Teams plans have separate pricing.\n\nLimitations: Coursera Coach is not available without a Coursera Plus subscription — it cannot be purchased separately. The AI is constrained to supporting Coursera's existing course catalog and cannot provide general tutoring outside course content. The $399/year cost is only justified if the learner is actively using multiple courses throughout the year.\n\nBest suited for professionals pursuing multiple certificates or ongoing learning on Coursera who want AI-assisted guidance, and who find value in the broader Coursera Plus catalog beyond just the AI assistant.",
    'pros': ['Integrated directly into Coursera courses — context-aware concept explanation', 'Personalized course recommendations across 10,000+ courses from top universities', 'Coursera Plus bundles 10,000+ courses — Coach is an addition to existing value', 'Assignment help with hints rather than answers — maintains academic integrity', '148M+ registered learners — largest online learning platform globally'],
    'cons': ['Not available without Coursera Plus subscription ($399/yr) — not a standalone product', 'AI constrained to Coursera course content only', '$399/year only justified with active multi-course use throughout the year', 'Less capable than dedicated AI tutors like Khanmigo for fundamental concept explanations'],
  },
  'duolingo-max': {
    'badge': 'paid', 'users': '100M+',
    'best_for': 'AI-powered language learning with conversation practice and explanations',
    'description': 'Duolingo\'s premium AI tier with conversation practice powered by GPT-4, grammar explanations, and roleplay scenarios. $29.99/mo or $168/yr. NOTE: Video Call + Explain My Answer now free for all Duolingo users.',
    'description_long': "Duolingo Max is the highest subscription tier of Duolingo, the world's most downloaded language learning app with 100 million monthly active users. Max adds AI-powered features built on GPT-4o: Roleplay (interactive conversations with AI characters in context-appropriate scenarios), Explain My Answer (detailed explanations of why an answer was correct or incorrect), and Video Call (practice conversations with an AI Duolingo character via video).\n\nAn important update in 2025: Duolingo moved Video Call and Explain My Answer to the free tier for all users, making two of the three Max features available without a paid subscription. Roleplay remains the primary exclusive feature of Max. This change significantly reduces the value differential between Max and Duolingo's free or Super tier.\n\nKey capabilities include all Duolingo Super features (no ads, unlimited hearts, streak freeze), Roleplay for contextual AI conversation practice, Explain My Answer for detailed grammar and vocabulary explanations, and Video Call for video-based AI conversation practice.\n\nPricing: Duolingo Max costs $29.99 per month or $168 per year ($14/month). Duolingo Super costs $6.99 per month or $83.99 per year. Free Duolingo now includes Video Call and Explain My Answer.\n\nLimitations: With Video Call and Explain My Answer available for free, Max's primary exclusive feature is Roleplay — making the $29.99/month price hard to justify for many learners. Duolingo's gamification approach, while effective for habit building, is less rigorous than structured language curricula for advanced learners.\n\nBest suited for Duolingo users who heavily use Roleplay for conversation practice and find the gamified format effective for their learning style — and who want all features without the limitations of free or Super tiers.",
    'pros': ['Roleplay provides contextual AI conversation practice in real-world scenarios', 'Built on GPT-4o for high-quality conversational responses', 'Includes all Duolingo Super features (no ads, unlimited hearts)', '100M+ MAU — largest user community of any language learning app', 'Gamified format drives daily habit and streak maintenance'],
    'cons': ['Video Call and Explain My Answer now free for all users — Max differentiator reduced', 'At $29.99/mo, difficult to justify when most AI features are now free', 'Gamification-focused approach less rigorous than structured curricula for advanced learners', 'Only Roleplay remains exclusive to Max — expensive for one feature'],
  },
  'khanmigo': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI tutor from Khan Academy — Socratic method teaching for students',
    'description': 'Khan Academy\'s AI tutor powered by GPT-4. Uses Socratic method — guides students to answers through questions rather than giving answers directly. Free for teachers; $4/mo or $44/yr for students.',
    'description_long': "Khanmigo is Khan Academy's AI-powered tutoring assistant, built specifically to support student learning without doing students' work for them. Unlike most AI assistants that provide direct answers, Khanmigo uses the Socratic method — it responds to student questions with guiding questions that lead them toward understanding, preserving the learning process.\n\nKhanmigo is tightly integrated with Khan Academy's curriculum, which covers K-12 math, science, history, grammar, SAT prep, and computing. When a student is working through a Khan Academy exercise and gets stuck, Khanmigo can guide them through the problem step-by-step without revealing the answer. It also provides writing feedback, essay coaching, and general tutoring across subjects. For teachers, Khanmigo offers lesson planning, discussion question generation, and parent communication drafting.\n\nKey capabilities include Socratic tutoring across all Khan Academy subjects, essay writing coaching and feedback, SAT prep assistance, lesson plan generation for teachers, discussion question generation, and parent communication templates.\n\nPricing: Khanmigo is free for teachers (no subscription required). Students can access Khanmigo at $4 per month or $44 per year. Khan Academy's partnership with Anthropic and Microsoft subsidizes access. Some school districts provide Khanmigo free to all students through institutional agreements.\n\nLimitations: Khanmigo is constrained to supporting learning — it intentionally will not do homework for students, which is the right pedagogical choice but frustrating for users expecting a general-purpose AI. Coverage is limited to Khan Academy's curriculum scope.\n\nBest suited for K-12 students who want a guided tutor for math and science homework, parents supplementing school learning, and teachers who want AI assistance for lesson planning and student communication.",
    'pros': ['Socratic method guides students to answers without doing work for them', 'Free for teachers — best value AI teaching tool in the K-12 market', 'Deeply integrated with Khan Academy curriculum for contextual subject support', 'Essay writing coaching with constructive feedback, not just corrections', '$4/month is the most affordable student AI tutor available'],
    'cons': ['Intentionally will not do homework — frustrating for users expecting direct answers', 'Coverage limited to Khan Academy curriculum scope', 'Less capable outside of K-12 subjects and SAT prep', 'Interface is simpler than dedicated AI tutoring platforms'],
  },
  'photomath': {
    'badge': 'freemium', 'users': '100M+',
    'best_for': 'Step-by-step math problem solving from camera or typed input',
    'description': 'Math problem solver that uses your camera to scan equations and shows step-by-step solutions with explanations. 100M+ downloads. Free for basic solving; Plus $9.99/mo or $69.99/yr for detailed steps.',
    'description_long': "Photomath is the leading math-solving app, allowing students to photograph a handwritten or printed math problem and receive instant step-by-step solutions with explanations. It has accumulated over 100 million downloads since launch and covers arithmetic, algebra, trigonometry, calculus, statistics, and word problems at K-12 and introductory college level.\n\nThe core feature is camera-based math recognition — pointing the camera at a problem in a textbook or worksheet delivers immediate recognition and solving. The AI provides multiple solution methods when applicable (showing both the substitution and elimination methods for a system of equations, for example), and animated step-by-step explanations walk through each solving step. Typed input is also supported for cases where camera recognition struggles.\n\nKey capabilities include camera scanning for printed and handwritten math, step-by-step solutions with animated explanations, multiple solution methods, graph visualization for functions, word problem solving, and a scientific calculator.\n\nPricing: Free tier includes problem scanning and basic solution display. Photomath Plus at $9.99 per month or $69.99 per year unlocks detailed animated step explanations, multiple solution approaches, and word problem solving. A 7-day free trial is available.\n\nLimitations: Photomath is a step-by-step solver, not a conceptual tutor — it shows how to solve problems but does not build understanding the way Khanmigo does. Heavy reliance on Photomath for homework can impede learning. Advanced university-level math (proof-based, abstract algebra) is outside scope.\n\nBest suited for middle school and high school students who need step-by-step guidance solving specific math problems, and parents helping with math homework.",
    'pros': ['Camera scanning solves printed and handwritten math problems instantly', '100M+ downloads — most widely used math app globally', 'Multiple solution methods shown when applicable — builds understanding of alternatives', 'Covers arithmetic through calculus at K-12 level', '7-day free trial available before committing to Plus subscription'],
    'cons': ['Shows solutions without building deep conceptual understanding', 'Easy to misuse for copying homework without learning', 'Advanced university-level math (proof-based) outside scope', 'Camera recognition struggles with handwriting and unusual notation'],
  },
  'synthesis': {
    'badge': 'paid', 'users': '',
    'best_for': 'Adaptive math learning for kids ages 5–11 (K-5)',
    'description': 'Adaptive math learning platform originally built for SpaceX employees\' children. Covers K-5 math through game-based challenges. ~$99–119/yr, covers up to 7 children. Best for ages 5–11.',
    'description_long': "Synthesis is an adaptive math learning platform originally created for children of SpaceX and Tesla employees — it was built internally to address the educational needs of families in those companies and later opened to the public. It focuses exclusively on K-5 mathematics (ages 5-11) through game-based, problem-solving challenges rather than traditional drill-and-practice.\n\nThe platform's approach is distinctive: rather than asking children to memorize procedures, Synthesis presents mathematical challenges as puzzles and games that require strategic thinking and numerical reasoning. The AI tracks each child's understanding and adjusts difficulty and topic focus accordingly. The platform is designed to develop mathematical thinking rather than just computational skill.\n\nKey capabilities include adaptive K-5 math curriculum, game-based learning challenges, AI-driven difficulty adjustment, progress tracking for parents, and multiplayer challenges where children can compete or collaborate with peers.\n\nPricing: Synthesis costs approximately $99-119 per year (pricing has varied slightly). A single subscription covers up to 7 children, making it excellent value for large families. A free trial is available.\n\nLimitations: Synthesis is K-5 only (ages 5-11) — it does not cover middle school or high school mathematics. The game-based approach, while engaging for many children, may not satisfy parents looking for traditional curriculum alignment or standardized test preparation. Some children who prefer direct instruction may find the exploratory format frustrating.\n\nBest suited for parents of elementary school children (ages 5-11) who want to supplement school math with an engaging, adaptive program that develops mathematical thinking — especially families with multiple children where the 7-child coverage provides strong value.",
    'pros': ['Developed for SpaceX/Tesla employees\' children — exceptionally high starting bar', 'One subscription covers up to 7 children — excellent family value', 'Game-based approach makes math engaging for children who find worksheets boring', 'Adaptive AI adjusts to each child\'s pace and understanding', 'Develops mathematical thinking rather than just procedural memorization'],
    'cons': ['K-5 only (ages 5-11) — no coverage beyond elementary school', 'Does not align to traditional curriculum or standardized test prep', 'Exploratory format may frustrate children who prefer direct instruction', 'Annual subscription required — no monthly payment option'],
  },
  'youlearn': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI-powered study assistant that learns from your own documents and videos',
    'description': 'AI study tool that turns your own materials — PDFs, videos, YouTube links, web pages — into an interactive tutor. Ask questions, get summaries, create quizzes from your own content. Free; Pro $12/mo annual.',
    'description_long': "YouLearn is an AI study assistant that converts any learning material — PDFs, textbooks, YouTube videos, web pages, and uploaded documents — into an interactive tutoring experience. Rather than teaching a fixed curriculum, YouLearn becomes a tutor for whatever content the student provides, enabling AI-assisted learning from course slides, textbook chapters, lecture recordings, and research papers.\n\nThe platform analyzes uploaded or linked content and enables students to ask questions about it, request summaries of specific sections, generate practice quizzes from the material, create concept maps, and get explanations in simpler language. This makes it particularly valuable for university and professional learners working with their own course materials.\n\nKey capabilities include document and video upload, YouTube and URL import, conversational Q&A about uploaded content, AI-generated summaries, automatic quiz generation from content, concept map creation, multi-document analysis, and study session tracking.\n\nPricing: Free plan provides limited uploads and queries per month. Pro at $12 per month (annual, approximately $10 per month) provides unlimited uploads and queries. Max at $45 per month provides higher processing limits and priority support for heavy users.\n\nLimitations: YouLearn requires the user to provide their own learning materials — it does not teach a curriculum independently. AI explanations are generated from the provided content and may not catch conceptual errors in the source material. The Max tier at $45/month is expensive for what is fundamentally a document Q&A tool.\n\nBest suited for university students, professionals studying for certifications, and self-directed learners who have their own study materials and want AI to help them understand, summarize, and quiz themselves on that specific content.",
    'pros': ['Works from any content — PDFs, YouTube videos, web pages, personal notes', 'Generates quizzes automatically from uploaded material for self-testing', 'No fixed curriculum — adapts to whatever the student is studying', 'Pro at $12/mo (annual) is affordable for students', 'Multi-document analysis enables cross-referencing across multiple sources'],
    'cons': ['Requires user to provide all learning materials — no built-in curriculum', 'AI explanations limited by quality and accuracy of uploaded source material', 'Max tier at $45/mo expensive for document Q&A use case', 'Free tier limited — insufficient for regular academic use'],
  },
}

def patch(slug, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        f'{SB_URL}/rest/v1/tools?slug=eq.{slug}&lang=eq.en',
        data=body, headers=HDRS, method='PATCH'
    )
    with urllib.request.urlopen(req) as r:
        return r.status

print(f'Updating {len(UPDATES)} tools...')
for slug, fields in UPDATES.items():
    status = patch(slug, fields)
    print(f'  {slug}: HTTP {status}')

print('Done.')
