-- Update EN content: writing, marketing, video, design categories
-- Run in Supabase SQL Editor
-- After running: python3 scripts/translate-tools.py ru es de ua he fr pt --slugs=quillbot,jasper,semrush,frase,clearscope,capcut,kling-ai,runway,heygen,pika,luma-ai,synthesia,canva-ai,framer-ai

-- ============================================================
-- WRITING
-- ============================================================

UPDATE tools SET
  users = '50M+'
WHERE slug = 'quillbot' AND lang = 'en';

UPDATE tools SET
  description = 'Professional AI copywriter for content teams and agencies. Brand voice, workflows and 80+ templates. Starts at $49/month.',
  description_long = 'Jasper is an AI writing platform built for professional marketing and content teams. It is positioned firmly in the enterprise segment — the cheapest plan starts at $49/month, which already signals that Jasper targets teams who write at volume rather than individual bloggers.

The core differentiator is Brand Voice: Jasper learns your company''s tone, terminology, and style from your existing content, then applies it consistently across everything the team generates. This solves one of the hardest problems in AI writing at scale — maintaining a consistent voice across dozens of writers and content formats.

The platform offers 80+ templates covering blog posts, ad copy, product descriptions, email campaigns, LinkedIn posts, press releases, and more. The AI Campaign feature takes a single brief and generates complete multi-channel campaigns — website copy, social posts, email sequence, and ads — in one go.

Jasper integrates with Surfer SEO for content optimization, and connects to Google Docs, Chrome, and various CMS platforms. The API is available on higher tiers for teams that want to build Jasper into their own workflows.

At $49/month minimum, Jasper is expensive for individual creators. ChatGPT Plus ($20/month) or Claude Pro ($20/month) will produce comparable raw output at a fraction of the cost. Jasper''s value is specifically in the Brand Voice consistency, templates, and team collaboration features — things that matter at the 10+ person content team level.

Best for marketing agencies, in-house content teams, and growth companies that need to produce high volumes of branded content consistently.',
  pros = ARRAY[
    'Brand Voice learns your tone and applies it consistently across all content',
    '80+ templates cover every marketing format from ads to full campaign briefs',
    'AI Campaign generates complete multi-channel campaigns from a single brief',
    'Surfer SEO integration for content optimization built into the workflow'
  ],
  cons = ARRAY[
    'Starts at $49/month — expensive for individual creators vs ChatGPT or Claude at $20/mo',
    'Raw output quality similar to general-purpose LLMs — value is in templates and Brand Voice'
  ]
WHERE slug = 'jasper' AND lang = 'en';

-- ============================================================
-- MARKETING
-- ============================================================

UPDATE tools SET
  description = 'All-in-one SEO and AI visibility platform. Tracks rankings in Google, ChatGPT, Perplexity and Gemini. Semrush One from $199/mo.',
  description_long = 'Semrush is the dominant all-in-one SEO and digital marketing platform, used by over 10 million marketers, agencies, and enterprises worldwide. It combines keyword research, competitor analysis, backlink auditing, site health monitoring, and content optimization in a single platform.

In 2026, Semrush made its biggest strategic shift in its history with the launch of Semrush One — a bundle that adds AI Visibility Toolkit to the classic SEO suite. AI visibility tracking monitors how your brand appears in responses generated by ChatGPT, Perplexity, Google Gemini, and other AI search engines. This directly addresses the new reality that organic search is increasingly being replaced by AI-generated answers.

Semrush Copilot is included free on all plans. It automatically analyzes your site''s data and surfaces personalized recommendations — flagging ranking drops, keyword opportunities, and technical issues without requiring manual reporting.

Pricing: Classic plans remain at Pro $139.95/mo, Guru $249.95/mo, Business $499.95/mo (annual billing saves ~17%). Semrush One starts at $199/mo and includes both the SEO suite and AI Visibility Toolkit — the recommended choice for teams investing in future-proof visibility strategy.

The platform is expensive, and many smaller sites find the Pro plan sufficient for most needs. The data quality and breadth of competitive intelligence tools remain unmatched by any single competitor.

Best for SEO professionals, digital marketing agencies, and content teams who need comprehensive competitive intelligence and are adapting their strategy to include AI search visibility.',
  pros = ARRAY[
    'Most comprehensive SEO data — keyword research, backlinks, site audit, competitor intelligence',
    'AI Visibility Toolkit tracks brand presence in ChatGPT, Perplexity, Gemini responses',
    'Semrush Copilot included free — automated recommendations and issue detection',
    'Semrush One bundle covers both traditional SEO and AI search from $199/mo'
  ],
  cons = ARRAY[
    'Expensive — Pro starts at $139.95/mo, full AI suite requires Semrush One at $199/mo+',
    'Overwhelming for beginners — hundreds of tools require time to learn effectively'
  ]
WHERE slug = 'semrush' AND lang = 'en';

UPDATE tools SET
  description = 'AI research, content briefs and SEO optimization in one tool. Tracks AI visibility in ChatGPT, Perplexity and Gemini. Starter $49/mo.',
  pros = ARRAY[
    'Combines research, brief generation, and real-time content scoring in one workflow',
    'AI visibility tracking monitors brand presence in AI search engines from Starter plan',
    'Generates detailed content briefs with questions, headers, and competitor analysis',
    'Flat unlimited plan available for high-volume content operations'
  ],
  cons = ARRAY[
    'Professional plan ($129/mo) needed for more than 10 articles/month',
    'Less accurate keyword data than Semrush or Ahrefs for pure SEO research'
  ]
WHERE slug = 'frase' AND lang = 'en';

UPDATE tools SET
  description = 'Content optimization platform trusted by HubSpot, IBM and Adobe. Unlimited seats on all plans. Essentials from $129/mo.',
  pros = ARRAY[
    'Unlimited team seats on all plans — no per-user pricing for growing teams',
    'Trusted by top content teams at HubSpot, IBM, Adobe — proven enterprise reliability',
    'Real-time content grading against top-ranking competitors with keyword density analysis',
    'Topic Explorer surfaces related concepts and semantic keywords automatically'
  ],
  cons = ARRAY[
    'Essentials plan at $129/mo — expensive for small teams or individual content creators',
    'Narrower scope than Frase — focused on optimization only, no brief generation or research'
  ]
WHERE slug = 'clearscope' AND lang = 'en';

-- ============================================================
-- VIDEO
-- ============================================================

UPDATE tools SET
  description = 'AI video editor with 800M+ monthly active users. Auto-captions, AI background removal, Sora 2 and Veo 3.1 directly integrated. Free with no watermark.',
  pros = ARRAY[
    'Free with no watermark on exports — best value among major video editors',
    'Sora 2 and Veo 3.1 integrated directly into the editing interface',
    '800M+ monthly users — largest AI video editor by far',
    'One-click auto-captions, background removal, and AI voice cloning'
  ],
  cons = ARRAY[
    'Limited for professional or cinematic production — built for social content volume',
    'Advanced AI generation features consume credits that run out on the free tier'
  ]
WHERE slug = 'capcut' AND lang = 'en';

UPDATE tools SET
  description = 'Kling 3.0 (Feb 2026): native 4K output, storyboard tool, lip-synced audio. Free tier with 66 daily credits. Pro from $6.99/mo.',
  description_long = 'Kling AI is a video generation platform from Kuaishou, one of China''s largest technology companies. It has become one of the leading AI video generators globally, with 60 million registered users as of early 2026.

Kling 3.0, released February 7, 2026, is the current version and represents a significant technical leap. New in 3.0: native 4K output, a storyboard tool for per-shot camera control and pacing, native lip-synced audio generation in a single pipeline, and multi-shot sequences (3–15 seconds) with subject consistency across different camera angles. The subject consistency feature in particular has been a breakthrough — maintaining character appearance across cuts is one of the hardest problems in AI video.

The pricing is highly competitive: a free tier provides 66 daily credits (enough for several short clips), while paid plans range from Standard at approximately $6.99/month up to Pro and Ultra tiers at higher credit volumes. This makes Kling one of the most accessible high-quality video generators available.

Kling 3.0 is available directly at kling.ai and through Runway''s multi-model subscription, which bundles Kling, Runway, Google Veo, Seedance, and FLUX under one plan.

Limitations: outputs have a distinctly cinematic, polished look that can feel over-processed for casual or documentary-style content. The interface is less refined than Runway or Pika.

Best for creators who need high-quality character-consistent video with 4K output at an accessible price point.',
  pros = ARRAY[
    'Kling 3.0 delivers native 4K output with subject consistency across multi-shot sequences',
    'Storyboard tool gives per-shot camera control and pacing — unique among consumer video AI',
    'Native lip-synced audio generation in a single pipeline — no separate sync step',
    'Free tier with 66 daily credits — most generous free access among quality video generators'
  ],
  cons = ARRAY[
    'Cinematic processing style can feel over-polished for casual or natural-looking content',
    'Interface less refined than Runway or Pika for beginners'
  ]
WHERE slug = 'kling-ai' AND lang = 'en';

UPDATE tools SET
  description = 'Gen-4.5 is #1 on video generation leaderboards (Nov 2025). One subscription includes Runway, Veo 3.1, Kling 3.0, Seedance and FLUX models. From $15/mo.',
  description_long = 'Runway is a professional AI video and creative platform based in New York. It is used by filmmakers, studios, and creative teams for AI-assisted video generation, editing, and visual effects.

Gen-4.5, released November 2025, is the current flagship model and holds the #1 position on the Artificial Analysis Text-to-Video leaderboard with an Elo score of 1,247. Gen-4.5 introduced multi-shot consistency — maintaining characters, environments, and objects across scenes without manual reference injection.

A major 2026 development: Runway''s subscription now includes multi-model access. One plan gives users Gen-4.5, Google Veo 3.1, Kling 3.0 Pro, Seedance, and FLUX simultaneously — the broadest multi-model video generation bundle available. This repositions Runway from a single-model tool to a platform for accessing the best models per use case.

Pricing: Free trial (125 credits) → Standard $15/month → Pro $35/month → Unlimited $95/month (annual billing saves ~20%). The Standard plan already includes all multi-model access and is the best entry point for creators.

Characters and environments stay consistent across shots in Gen-4.5, making it the preferred tool for short films, music videos, and ad content that requires narrative continuity.

Limitations: pricing is higher than Kling or Pika for equivalent credit volumes. The free trial is limited and runs out quickly.

Best for professional filmmakers, creative agencies, and advanced creators who need top benchmark quality and character consistency across scenes.',
  pros = ARRAY[
    'Gen-4.5 is #1 on Text-to-Video leaderboard — highest benchmark quality available',
    'Multi-model subscription: one plan includes Runway, Veo 3.1, Kling 3.0, Seedance, FLUX',
    'Best character and environment consistency across multi-shot sequences',
    'Standard plan at $15/mo is the most accessible professional video generation entry point'
  ],
  cons = ARRAY[
    'More expensive per credit than Kling or Pika at equivalent quality levels',
    'Free trial (125 credits) runs out quickly — limited for evaluation'
  ]
WHERE slug = 'runway' AND lang = 'en';

UPDATE tools SET
  description = 'AI avatars and video dubbing in 175+ languages. Avatar IV with ultra-realistic lip-sync. $100M ARR. Starts at $24/month.',
  description_long = 'HeyGen is the leading AI avatar video platform, used by over 2 million users across marketing teams, L&D departments, and content creators. It has surpassed $100 million in annual recurring revenue and carries a $500 million valuation — making it the most commercially successful AI video platform focused on avatar-based content.

The core product: create professional videos by typing a script. HeyGen''s avatars lip-sync in 175+ languages with near-broadcast quality. Avatar IV, the current generation, delivers the most realistic lip-sync accuracy HeyGen has released.

Recent additions include Video Agent API (create videos programmatically from external triggers), ChatGPT-driven video creation (generate scripts and scenes from prompts directly in HeyGen), and premium B-roll sourcing via Sora 2 and Veo 3.1 for background footage. Synthesia is the closest competitor, starting at $22/month with 160+ avatars and strong L&D features.

Pricing starts at $24/month for the Creator plan, which includes 200+ avatars and 175+ languages. Higher tiers unlock custom avatar training (your face/voice), API access, and enterprise SSO.

Limitations: avatars still have the occasional uncanny valley quality in close-up shots. Custom avatar training requires submitting video footage of yourself and takes a few business days.

Best for marketing teams, HR/L&D departments, and content creators who need professional avatar-based videos at scale without camera, studio, or multilingual dubbing costs.',
  users = '2M+',
  pros = ARRAY[
    'Avatar IV delivers ultra-realistic lip-sync in 175+ languages — market-leading quality',
    '$100M ARR confirms enterprise reliability and product investment trajectory',
    'Video Agent API enables programmatic video creation from external triggers',
    'Sora 2 and Veo 3.1 integrated for premium B-roll footage generation'
  ],
  cons = ARRAY[
    'Close-up shots can still show uncanny valley quality on some avatar styles',
    'Custom avatar training requires video footage submission and multi-day processing time'
  ]
WHERE slug = 'heygen' AND lang = 'en';

UPDATE tools SET
  description = 'Pika 2.5: Pikaframes lets you set start and end images for precise AI video transitions. 80 free monthly credits. Known for creative social-first video effects.',
  pros = ARRAY[
    'Pikaframes generates controlled transitions between a start and end image (1–10 sec)',
    'Pikaffects, Pikaswaps and Pikadditions built specifically for Reels, TikTok and Shorts',
    '80 free monthly credits — accessible entry point for social creators',
    'Best tool for "what if" creative loops and viral visual effects'
  ],
  cons = ARRAY[
    'Less suitable for narrative or cinematic content — optimised for short social clips',
    'Free tier (80 credits/mo) runs out quickly for high-volume creators'
  ]
WHERE slug = 'pika' AND lang = 'en';

UPDATE tools SET
  description = 'Luma Ray3 and Ray3.14 generate cinematic AI video and photorealistic 3D scenes. Best for mood and environment-heavy shots. Freemium.',
  description_long = 'Luma AI is a San Francisco-based AI lab known for its photorealistic video generation and 3D scene reconstruction. The platform has evolved from its original NeRF-based 3D capture technology to become a leading cinematic AI video generator.

The current model family is Ray3 and Ray3.14 (the Dream Machine branding from 2024 has been retired). Ray3 is the standard model; Ray3.14 is the higher-quality variant optimized for cinematic mood, lighting, and atmospheric environments. Luma models are particularly strong at environment-heavy shots — sweeping landscapes, moody interiors, and atmospheric scenes where other models produce flat results.

Luma AI is available both directly at lumalabs.ai and through Runway''s multi-model subscription. The Runway bundle gives access to Ray3 alongside Gen-4.5, Veo 3.1, Kling 3.0, and Seedance under one subscription.

Pricing follows a freemium model: free tier with limited monthly generations, Dream (legacy plan name) at lower cost, Pro and higher tiers for volume users.

Limitations: Luma is weaker than Kling 3.0 on character consistency and human subject realism. Subject faces can drift across frames. Better for abstract, atmospheric, or landscape-focused content than character-driven narrative.

Best for filmmakers and visual artists who need cinematic environment and atmosphere quality — not for character-driven video or social content.',
  pros = ARRAY[
    'Ray3 and Ray3.14 lead on cinematic mood and environment-heavy shot quality',
    'Best photorealistic 3D scene reconstruction from video or images',
    'Available standalone and via Runway multi-model subscription',
    'Strong atmospheric and lighting quality compared to other video generators'
  ],
  cons = ARRAY[
    'Weaker than Kling 3.0 on character consistency — faces can drift across frames',
    'Dream Machine branding retired — some tutorials and reviews reference outdated model names'
  ]
WHERE slug = 'luma-ai' AND lang = 'en';

UPDATE tools SET
  description = 'Synthesia 3.0: AI avatars with Video Agents for real-time two-way conversations. 160+ avatars, 140+ languages. Starts at $22/month.',
  description_long = 'Synthesia is an AI video platform specializing in avatar-based corporate and training video production. It is used by over 50,000 companies including Heineken, Zoom, and Reuters for onboarding, L&D, compliance training, and internal communications.

Synthesia 3.0, released in 2026, is the biggest update in the platform''s history. Video Agents enable real-time two-way conversations with AI avatars — viewers can ask questions and the avatar responds in real time, turning passive video into interactive experiences. This is particularly powerful for training and customer-facing use cases. AI Copilot writes scripts and suggests visuals automatically from a brief. Interactive Courses package videos into structured learning modules with quizzes, progress tracking, and SCORM export for LMS integration.

The avatar library includes 160+ photorealistic AI presenters in 140+ languages. Custom avatar creation (your own likeness) is available on higher plans and takes 1–3 business days. SOC 2 Type II certification makes it enterprise-grade for security-conscious organizations.

Pricing starts at $22/month for the Starter plan (3 videos/month, 120 minutes/year). Growth and Enterprise plans unlock unlimited videos, Video Agents, custom avatars, and API access.

HeyGen is the closest competitor at $24/month with stronger lip-sync quality and broader language support. Synthesia has deeper LMS/SCORM integration and stronger enterprise compliance positioning.

Best for L&D teams, corporate communications, and enterprises that need structured interactive training content at scale.',
  pros = ARRAY[
    'Video Agents enable real-time two-way avatar conversations — unique interactive format',
    'AI Copilot writes scripts and suggests visuals from a brief automatically',
    'SCORM export and LMS integration built in — purpose-built for corporate training',
    'SOC 2 Type II certified — meets enterprise security and compliance requirements'
  ],
  cons = ARRAY[
    'Starter plan limited to 3 videos/month — upgrade required for regular production',
    'HeyGen offers stronger lip-sync quality and more languages at a similar price point'
  ]
WHERE slug = 'synthesia' AND lang = 'en';

-- ============================================================
-- DESIGN
-- ============================================================

UPDATE tools SET
  users = '220M+',
  description = 'Canva AI 2.0 (April 2026): full AI creative partner from idea to final design. Magic Studio, agentic capabilities, 220M+ monthly users. Pro $15/mo.',
  description_long = 'Canva is the world''s most popular visual design platform with 220 million monthly active users. Originally built as a simplified alternative to Adobe, it has evolved into a comprehensive AI-powered creative suite through Magic Studio — its AI feature layer.

Canva AI 2.0, launched April 16, 2026, represents the platform''s most aggressive repositioning: from "design tool with AI features" to a full AI creative platform with agentic capabilities. The AI now handles the entire creation workflow through conversation — research, writing, design layout, and social scheduling can all be initiated and iterated with natural language prompts.

Key Magic Studio features: Magic Design (generate complete designs from a text prompt), Magic Write (AI copywriting embedded in the editor), Magic Edit (modify any element by describing the change), Background Remover (one-click), Magic Resize (reformat any design for any platform instantly), and Text to Video (short video generation from a prompt).

Pricing: Free tier covers most casual use cases. Canva Pro at $15/month unlocks Brand Kit, unlimited premium templates, background remover, Magic Resize, and 1TB storage. Teams at $10/user/month (minimum 3 users). Enterprise pricing from ~$30/user/month.

Limitations: Canva is optimized for volume and speed, not professional-grade design precision. Typography controls, grid systems, and fine design control are limited compared to Figma or Adobe tools. Not suitable for product UI design.

Best for marketers, content creators, social media managers, and small businesses who need attractive visual content at speed.',
  pros = ARRAY[
    '220M+ monthly users — the most widely used design tool in the world',
    'Canva AI 2.0 handles full creative workflow through conversation — idea to final design',
    'Magic Resize reformats any design for any platform in one click',
    'Free tier genuinely capable — no subscription needed for most casual use'
  ],
  cons = ARRAY[
    'Limited typography and design precision vs Figma or Adobe — not for product UI design',
    'AI generation quality in video and complex layouts still trails dedicated tools'
  ]
WHERE slug = 'canva-ai' AND lang = 'en';

UPDATE tools SET
  description = 'Create landing pages from text descriptions with animations. Publish in one click. Free → Basic $15 → Pro $45 → Scale $100/mo.',
  pros = ARRAY[
    'Best landing page generator — full animated website from a text description in seconds',
    'Publish directly from Framer in one click — no separate hosting setup needed',
    'AI Wireframer, AI Workshop coding assistant, and multi-LLM plugin integrations built in',
    'Free tier available — upgrade to Basic $15/mo for custom domain and more pages'
  ],
  cons = ARRAY[
    'Scale plan at $100/mo is expensive for high-traffic or multi-site use cases',
    'Less suitable for complex web apps or e-commerce — optimised for marketing pages'
  ]
WHERE slug = 'framer-ai' AND lang = 'en';
