-- ============================================================
-- Update 5 tools (EN) — May 2026
-- Tools: clearscope, perplexity, microsoft-copilot, stable-diffusion, capcut
-- Run in Supabase SQL Editor
-- After running: translate to es, de, ru, ua, he, fr, pt
-- ============================================================

-- ============================================================
-- 41. CLEARSCOPE
-- ============================================================
UPDATE tools SET
  name        = $d41$Clearscope$d41$,
  url         = $d41$https://clearscope.io$d41$,
  domain      = $d41$clearscope.io$d41$,
  badge       = $d41$paid$d41$,
  best_for    = $d41$SEO content optimization, content inventory, LLM visibility tracking$d41$,
  description = $d41$Clearscope 2.0 rebranded as a full discoverability platform with AI-assisted drafting, Content Inventory Monitoring with Striking Distance and Content Decay views, and LLM tracking. New Essentials plan at $129/mo.$d41$,
  description_long = $dl41$Clearscope is an SEO content optimization platform that underwent a major rebrand with version 2.0, repositioning itself from a keyword-grading tool to a full discoverability platform. The update introduces a broader set of content lifecycle features designed to cover not just new content creation but ongoing inventory management and AI search visibility.

Draft with AI is one of the headline additions in Clearscope 2.0. It provides SEO-optimized content creation directly inside the platform and is available on all plans — not restricted to higher tiers. The feature previously called Reports has been renamed Drafts, aligning the nomenclature with the new AI-assisted writing workflow.

Content Inventory Monitoring adds two analytical views for managing existing content. Striking Distance surfaces pages that rank between positions 8 and 20 for target keywords — pages that are close to ranking on the first page and could be pushed up with targeted optimization. Content Decay identifies pages whose traffic or rankings have declined over a defined period, flagging them for refresh or consolidation before the decline compounds.

LLM tracking is a new capability that monitors how content appears in responses generated by large language models including ChatGPT, Perplexity, and similar AI search engines. This reflects the growing importance of AI search visibility alongside traditional Google rankings. Local SEO Targeting adds location-specific optimization for businesses targeting geographic search queries.

Pricing was restructured with the introduction of a new Essentials plan at $129 per month. Clearscope has eliminated feature gating on this tier — all features are available across plans, with the distinction being scale and usage limits rather than capability restrictions.

Clearscope is best for SEO content teams and agencies that need to optimize both new and existing content, monitor AI search visibility, and manage large content inventories with decay and striking-distance analysis.$dl41$,
  pros = ARRAY[
    'Draft with AI on all plans — SEO-optimized content creation without plan restrictions',
    'Striking Distance view identifies near-first-page content for targeted quick wins',
    'Content Decay monitoring flags declining pages before traffic loss compounds',
    'LLM tracking adds AI search visibility alongside traditional Google ranking data',
    'New Essentials plan at $129/mo with no feature gating — full access from entry tier'
  ],
  cons = ARRAY[
    'Paid-only starting at $129/mo — no free trial or meaningful free tier',
    'LLM tracking is a newer feature — coverage and accuracy across AI engines still maturing',
    'Feature set focused on SEO teams — less useful for general content writers without SEO context',
    'Higher-tier plans required for large-scale inventory monitoring at enterprise content volume'
  ]
WHERE slug = $d41$clearscope$d41$ AND lang = $d41$en$d41$;

-- ============================================================
-- 42. PERPLEXITY
-- ============================================================
UPDATE tools SET
  name        = $d42$Perplexity$d42$,
  url         = $d42$https://perplexity.ai$d42$,
  domain      = $d42$perplexity.ai$d42$,
  badge       = $d42$freemium$d42$,
  best_for    = $d42$AI search, deep research, agentic computer control, finance and study tools$d42$,
  description = $d42$Perplexity Deep Research now runs on Claude Opus 4.6. Personal Computer for Mac adds agentic control features for all users. Kimi K2.5 added to inference stack. Microsoft Teams integration and finance and study tools launched.$d42$,
  description_long = $dl42$Perplexity is an AI-powered search and research platform that answers queries with cited sources rather than a list of links. It is used for real-time research, fact-checking, competitive analysis, and academic study by individuals, researchers, and business teams. Perplexity's model stack is multi-provider, drawing on models from Anthropic, OpenAI, Mistral, and others.

Deep Research, Perplexity's long-form research capability, has been upgraded to run on Claude Opus 4.6, reflecting improved benchmark performance for complex multi-step research tasks. Deep Research conducts autonomous web searches, synthesizes findings across multiple sources, and produces structured reports with inline citations — suitable for tasks that would otherwise require hours of manual research.

Personal Computer for Mac is a native Mac application that extends Perplexity beyond search into agentic computer control. It can interact with on-screen content, automate desktop tasks, and respond to natural language instructions that require operating the computer itself. The feature is available to all users — not restricted to Pro subscribers. Perplexity also became available as a Microsoft Teams application, enabling the same computer-control agent capability within the Teams enterprise environment.

Kimi K2.5, the open-source model from Moonshot AI, has been added to Perplexity's inference stack as a selectable model option. This expands the model choices available to users running queries on the platform and introduces a capable open-source alternative to the closed models already offered.

Finance tools include an ETF holdings tab that displays portfolio composition data directly in Perplexity search results, useful for investors and analysts. Study tools on the iOS app can generate quizzes and flashcards from any content — articles, documents, or pages — for spaced-repetition learning.

Perplexity is free for standard use. Pro plan is $20 per month and adds Deep Research, model selection including Claude Opus 4.6, and higher usage limits. Perplexity is best for researchers, students, and professionals who need cited, real-time answers and want AI search with agentic capabilities beyond a standard chat interface.$dl42$,
  pros = ARRAY[
    'Deep Research on Claude Opus 4.6 — cited multi-step research reports for complex queries',
    'Personal Computer for Mac: agentic desktop control available to all users, not Pro-only',
    'Kimi K2.5 open-source model added to inference stack alongside Claude, GPT-4o, and others',
    'ETF holdings tab and iOS quiz/flashcard generation — practical finance and study integrations',
    'Microsoft Teams app brings Perplexity Computer into enterprise environments'
  ],
  cons = ARRAY[
    'Deep Research and model selection require Pro plan at $20/mo',
    'Agentic computer control on Mac is new — reliability on complex multi-step tasks varies',
    'Perplexity search can surface inaccurate citations — source verification remains necessary',
    'Finance data (ETF holdings) is informational and may lag real-time market data sources'
  ]
WHERE slug = $d42$perplexity$d42$ AND lang = $d42$en$d42$;

-- ============================================================
-- 43. MICROSOFT COPILOT
-- ============================================================
UPDATE tools SET
  name        = $d43$Microsoft Copilot$d43$,
  url         = $d43$https://copilot.microsoft.com$d43$,
  domain      = $d43$copilot.microsoft.com$d43$,
  badge       = $d43$freemium$d43$,
  best_for    = $d43$AI assistant, autonomous task delegation, M365 integration, Windows AI$d43$,
  description = $d43$Copilot Cowork launches agentic task delegation on iOS/Android. Microsoft 365 E7 + Agent 365 bundles Copilot enterprise-wide. Windows 11 May 2026 update adds taskbar AI agent monitoring and File Explorer enhancements.$d43$,
  description_long = $dl43$Microsoft Copilot is Microsoft's AI assistant platform integrated across Windows, Microsoft 365, mobile, and web. It is powered by models from OpenAI and Microsoft Research, and serves as the primary AI interface across the Microsoft ecosystem — from the Windows taskbar to Outlook, Teams, Word, Excel, and enterprise automation through the Power Platform.

Copilot Cowork, part of the Frontier program, introduces autonomous agentic task delegation. Available on iOS and Android, it allows users to assign real tasks — scheduling, research, drafting, web-based actions — and have Copilot execute them in the background without continuous user supervision. This moves Copilot from a chat assistant that responds to queries toward a delegated agent that completes multi-step tasks independently.

Microsoft 365 E7 is a new enterprise licensing tier that bundles Microsoft 365 E5, Copilot, and Agent 365 into a single plan. Agent 365 is the enterprise agent layer that enables organizations to build, deploy, and govern AI agents across their Microsoft environments. This consolidation simplifies procurement for large enterprises that previously needed separate SKUs for M365, Copilot, and automation capabilities.

Copilot Insights in Outlook Classic brings AI-generated email intelligence into the traditional Outlook desktop client. Users can ask Copilot about selected email text, receive AI-generated summaries of thread history, and surface action items without switching to the Outlook new app or the web version.

The Windows 11 May 2026 update embedded Copilot more deeply into the operating system. An AI agent monitoring indicator appears in the taskbar when Copilot is actively executing a background task, providing status visibility. File Explorer received AI-enhanced search and file management suggestions. Xbox mode adds a gaming-optimized interface layer accessible directly through Windows.

Microsoft Copilot is free with a Microsoft account at basic capability. Microsoft 365 Personal and Family plans include Copilot from $6 per user per month. Enterprise plans vary. Copilot is best for organizations already in the Microsoft ecosystem who want unified AI assistance, autonomous task agents, and deep integration with M365 applications.$dl43$,
  pros = ARRAY[
    'Copilot Cowork: autonomous task delegation on iOS/Android — true background agent execution',
    'M365 E7 bundles Copilot + Agent 365 with M365 E5 — simplified enterprise procurement',
    'Copilot Insights in Outlook Classic — AI email intelligence without switching to new app',
    'Windows 11 integration: taskbar agent monitoring and File Explorer AI enhancements',
    'Free tier available with a Microsoft account — lowest entry barrier of any major AI assistant'
  ],
  cons = ARRAY[
    'Copilot Cowork (Frontier program) is still in early access — not broadly available yet',
    'Full enterprise capabilities require M365 E7 or separate Copilot licensing at significant cost',
    'Quality varies significantly across M365 apps — more polished in Teams and Word than Excel',
    'Agentic features on mobile are new — reliability and scope of supported tasks still limited'
  ]
WHERE slug = $d43$microsoft-copilot$d43$ AND lang = $d43$en$d43$;

-- ============================================================
-- 44. STABLE DIFFUSION
-- ============================================================
UPDATE tools SET
  name        = $d44$Stable Diffusion$d44$,
  url         = $d44$https://stability.ai$d44$,
  domain      = $d44$stability.ai$d44$,
  badge       = $d44$free$d44$,
  best_for    = $d44$Open-source image generation, local inference, video AI, audio generation$d44$,
  description = $d44$Stability AI cleared its debt and signed an EA partnership in February 2026. SD3.5 is optimized for NVIDIA TensorRT/FP8 and AMD ONNX. SV4D 2.0 and Stable Audio Open Small launched with Arm partnership.$d44$,
  description_long = $dl44$Stable Diffusion is Stability AI's open-source image generation model series, widely used for local inference, fine-tuning, and commercial deployment. Unlike closed-source models, Stable Diffusion weights are publicly released and can be run on consumer hardware, making it the foundation of a large ecosystem of third-party tools, community fine-tunes, and commercial applications built on top of the base models.

Stability AI underwent a significant corporate recovery in early 2026. The company's debt was fully erased, resolving the financial instability that had threatened operations through 2024 and 2025. A strategic partnership with Electronic Arts (EA) was signed in February 2026, providing both capital and a high-profile commercial deployment context for Stability AI's models. James Cameron joined as an advisor, adding industry credibility to the company's video generation push.

SD3.5 performance has been improved through optimizations for NVIDIA TensorRT with FP8 quantization. This combination delivers faster inference speeds and significantly lower VRAM requirements on RTX-series GPUs, making SD3.5 more practical on mid-range consumer hardware than earlier large models. AMD support expanded through ONNX-optimized model variants designed for Radeon GPUs and Ryzen AI accelerators, broadening the addressable hardware base beyond NVIDIA.

SV4D 2.0 (Stable Video 4D 2.0) is a new video generation model release focused on higher-quality outputs for real-world scenes — improving coherence, motion quality, and subject consistency compared to the original SV4D release. Stable Audio Open Small, a compact audio generation model, was open-sourced in partnership with Arm and is optimized for efficient inference on Arm-based hardware.

All Stable Diffusion models remain free and open-source. The Stability AI platform offers a freemium API for hosted inference without local setup. Stable Diffusion is best for developers, researchers, and creative professionals who need open-source image and video generation they can run locally, fine-tune, or deploy commercially without per-image fees.$dl44$,
  pros = ARRAY[
    'Fully open-source — weights freely available for local use, fine-tuning, and commercial deployment',
    'SD3.5 optimized for NVIDIA TensorRT/FP8: faster inference and lower VRAM on RTX GPUs',
    'AMD ONNX-optimized variants for Radeon and Ryzen AI — not NVIDIA-exclusive',
    'SV4D 2.0 delivers higher-quality real-world video output over original SV4D',
    'Stable Audio Open Small open-sourced with Arm — audio generation available on edge hardware'
  ],
  cons = ARRAY[
    'Local setup requires technical knowledge — not suitable for non-technical users',
    'Best results on SD3.5 still require a capable GPU; CPU-only inference is slow',
    'Open-source ecosystem is fragmented — many forks, versions, and UIs with inconsistent quality',
    'Stability AI corporate instability history — partnership sustainability remains to be proven'
  ]
WHERE slug = $d44$stable-diffusion$d44$ AND lang = $d44$en$d44$;

-- ============================================================
-- 45. CAPCUT
-- ============================================================
UPDATE tools SET
  name        = $d45$CapCut$d45$,
  url         = $d45$https://capcut.com$d45$,
  domain      = $d45$capcut.com$d45$,
  badge       = $d45$freemium$d45$,
  best_for    = $d45$AI video editing, auto-edit, story generation, 2K/4K export$d45$,
  description = $d45$CapCut returned to the US in January 2026 via TikTok USDS Joint Venture LLC with Oracle/Silver Lake/MGX ownership. AI Auto-Edit, AI Story Maker with Google Veo 3 integration, and 2K/4K export launched in 2026.$d45$,
  description_long = $dl45$CapCut is a consumer and creator video editing application originally developed by ByteDance. It is widely used for short-form video production, social content creation, and increasingly for AI-assisted editing workflows. CapCut gained a large user base through tight integration with TikTok's creative ecosystem.

CapCut's availability in the United States was restored on January 22, 2026 following a legal and ownership resolution. The app is now operated through TikTok USDS Joint Venture LLC, a new corporate structure with Oracle, Silver Lake, and MGX holding majority ownership. This structure was established to satisfy US national security requirements regarding data handling. All US users were migrated to the new "CapCut US" app by March 2026, replacing the previous ByteDance-operated version.

AI Auto-Edit is a 2026 AI feature that analyzes uploaded footage using scene recognition and speech transcription, assigns quality scores to clips, and automatically assembles a cut based on pacing and content relevance. Users can review and override the auto-assembled edit, or use it as a starting point for manual refinement. This significantly reduces the time required to produce a first cut from raw footage.

AI Story Maker integrates Google Veo 3 for AI video generation directly inside CapCut. Users describe a scene or narrative in text, and Story Maker generates corresponding video segments using Veo 3, which can be combined with captured footage or published as standalone AI-generated content.

Export quality improved with the addition of 2K and 4K export options, raising the output ceiling for professional and semi-professional use cases. CapCut remains free for core editing features. The Pro plan is $9.99 per month and adds AI credits, cloud storage, premium templates, and higher export quality tiers.

CapCut is best for social content creators, short-form video producers, and individuals who need fast AI-assisted editing with minimal technical setup, and for creators who want access to Google Veo 3 video generation inside a consumer-friendly editing environment.$dl45$,
  pros = ARRAY[
    'AI Auto-Edit: scene recognition, speech transcription, and quality scoring automate first cuts',
    'AI Story Maker with Google Veo 3 integration — AI video generation inside the editing app',
    '2K and 4K export now available — higher output quality for semi-professional use',
    'Free tier covers core editing features — accessible without a subscription',
    'US legal status resolved — stable operation via TikTok USDS JV with Oracle/Silver Lake/MGX'
  ],
  cons = ARRAY[
    'US corporate structure is new — long-term data governance and ownership stability unproven',
    'AI Auto-Edit requires review — automated cuts often need manual adjustment for quality results',
    'AI credits for Story Maker and AI features consumed quickly on the free tier',
    'Pro at $9.99/mo is competitive but 2K/4K and full AI access require the paid plan'
  ]
WHERE slug = $d45$capcut$d45$ AND lang = $d45$en$d45$;
-- ============================================================
-- Update 5 tools (EN) — May 2026
-- Tools: descript, gamma, leonardo-ai, comfyui, meta-ai
-- Run in Supabase SQL Editor
-- After running: translate to es, de, ru, ua, he, fr, pt
-- ============================================================

-- ============================================================
-- 46. DESCRIPT
-- ============================================================
UPDATE tools SET
  name        = $d46$Descript$d46$,
  url         = $d46$https://descript.com$d46$,
  domain      = $d46$descript.com$d46$,
  badge       = $d46$freemium$d46$,
  best_for    = $d46$AI video editing, voice cloning, dubbing, MCP automation$d46$,
  description = $d46$Descript's Underlord AI now uses reasoning models for complex edits, with video generation via Veo 3.1 and Sora 2. Dubbing expanded to 45 languages with lip sync and 21 new stock voices.$d46$,
  description_long = $dl46$Descript is an AI-powered video and podcast editing platform that treats audio and video like a text document. Users edit media by editing a transcript — cutting words deletes the corresponding footage — and Underlord, Descript's built-in AI layer, handles complex production tasks automatically. It is used by podcasters, video creators, marketers, and production teams.

Underlord now runs on reasoning models, including selectable Gemini 3, enabling it to handle multi-step edit instructions that previously required manual execution. Users can describe complex sequences — cut all pauses over one second, remove filler words, add a chapter break before each topic shift — and Underlord executes them as a coordinated chain rather than a series of individual actions.

Video generation from text prompts is now available via integrated Veo 3.1 and Sora 2, allowing creators to generate B-roll or scene footage directly within Descript without switching to an external tool. Lip sync for dubbed and translated video was added alongside the generation features, improving realism for multilingual content.

Caption translation and dubbing expanded significantly: 39 additional languages are now supported for captions, and 6 new languages gained full dubbing support including voice synthesis. Descript also added 21 new stock voices for AI voiceover, bringing the total library to over 1,000.

MCP (Model Context Protocol) integration allows Claude, and other AI agents that support MCP, to control Descript via natural language prompts. This enables automated editing workflows where an external agent can issue editing commands, run exports, or manage projects programmatically.

Descript is best for video and podcast creators who want AI-assisted editing at the transcript level, and for teams producing multilingual or dubbed content who need integrated lip sync and voice synthesis.$dl46$,
  pros = ARRAY[
    'Underlord on reasoning models handles multi-step complex edits as a single instruction',
    'Veo 3.1 and Sora 2 integration for text-to-video B-roll without leaving the app',
    'Dubbing with lip sync now covers 45 languages — one of the broadest ranges available',
    'MCP integration: Claude and other agents can control Descript programmatically',
    '21 new stock voices added; 1,000+ total for AI voiceover'
  ],
  cons = ARRAY[
    'Reasoning model edits can be slower than manual execution for simple, single-step tasks',
    'Video generation credits are separate from core subscription and can add cost',
    'Lip sync quality varies by language — best results on the 6 fully supported dubbing languages',
    'MCP integration requires technical setup; not accessible to non-developer users'
  ]
WHERE slug = $d46$descript$d46$ AND lang = $d46$en$d46$;

-- ============================================================
-- 47. GAMMA
-- ============================================================
UPDATE tools SET
  name        = $d47$Gamma$d47$,
  url         = $d47$https://gamma.app$d47$,
  domain      = $d47$gamma.app$d47$,
  badge       = $d47$freemium$d47$,
  best_for    = $d47$AI presentations, marketing assets, infographics, programmatic content$d47$,
  description = $d47$Gamma launched a GA Generate API for programmatic content creation and Gamma Imagine for AI marketing graphics. SOC 2 Type II certified. Free plan includes 400 credits; paid plans from $8/mo annual.$d47$,
  description_long = $dl47$Gamma is an AI presentation and document creation platform that generates structured slides, documents, and web pages from text prompts. It is used by marketers, founders, educators, and consultants who need professionally designed visual content without slide-by-slide manual formatting. Gamma handles layout, design, and image placement automatically from the initial prompt.

The Generate API reached general availability in January 2026, enabling programmatic content creation at scale. Developers and marketing platforms can now call the Gamma API to generate presentations, documents, or pages automatically — for example, generating a customized deck for each sales prospect or producing a report template for each client without human intervention per output.

Gamma Imagine, launched in March 2026, is a new standalone AI image generation product targeting marketing asset creation. It produces charts, infographics, social graphics, and promotional visuals directly within the Gamma platform. This positions Gamma as a direct competitor to Canva's AI image features, with a particular focus on data visualization and structured marketing graphics rather than freeform artistic generation.

A new Ultra tier was introduced alongside Gamma Imagine, offering higher generation limits, priority processing, and access to the image generation capabilities. The platform achieved SOC 2 Type II certification, making it suitable for enterprise teams with compliance requirements around data security and vendor trust.

Pricing in 2026: Free plan at 400 credits, Plus at $8/month annual, Pro at $15/month annual, and Ultra at custom or higher-tier pricing. The free tier is generous for individual users who need occasional decks.

Gamma is best for marketers, salespeople, and founders who need AI-generated presentations and marketing graphics quickly, and for development teams that want to automate presentation generation via API.$dl47$,
  pros = ARRAY[
    'Generate API now GA — programmatic content creation at scale for any platform',
    'Gamma Imagine: AI image generation for charts, infographics, and social graphics built in',
    'SOC 2 Type II certified — suitable for enterprise teams with compliance requirements',
    'Free tier includes 400 credits — sufficient for occasional individual use',
    'Handles layout and design automatically — no slide-by-slide formatting required'
  ],
  cons = ARRAY[
    'Ultra tier pricing not publicly disclosed — requires inquiry for enterprise plans',
    'Gamma Imagine image quality is optimized for structured graphics, not artistic generation',
    'API access requires developer setup — not self-serve for non-technical users',
    'Free plan credits are consumed quickly when generating multiple full presentations'
  ]
WHERE slug = $d47$gamma$d47$ AND lang = $d47$en$d47$;

-- ============================================================
-- 48. LEONARDO AI
-- ============================================================
UPDATE tools SET
  name        = $d48$Leonardo AI$d48$,
  url         = $d48$https://leonardo.ai$d48$,
  domain      = $d48$leonardo.ai$d48$,
  badge       = $d48$freemium$d48$,
  best_for    = $d48$AI image generation, sketch-to-image, image-to-video, enterprise API$d48$,
  description = $d48$Leonardo AI launched the Creative Engine API for enterprise replication, rebranded as "Yours to Create," and added Motion 2.0 with improved lip sync. Real-time sketch-to-image with sub-second updates is best-in-class as of May 2026.$d48$,
  description_long = $dl48$Leonardo AI is an AI image and video generation platform used by game developers, concept artists, marketers, and creative studios. It offers a web-based interface alongside a robust API, combining proprietary model pipelines with third-party model integrations. The platform is built for high-volume creative production and professional asset generation workflows.

The Creative Engine API, launched April 14, 2026, is an enterprise-grade API that enables code extraction and replication of Leonardo's generation pipelines. Enterprises can use it to embed Leonardo's image and video generation capabilities into proprietary tools, internal platforms, and production workflows without exposing end users to the Leonardo interface directly.

Leonardo underwent a full rebrand in April 2026, adopting the identity "Yours to Create" developed by agency Koto. The rebrand accompanied the release of the new Alchemy v4 pipeline and the Phoenix architecture — updated generation models that improve quality on photorealistic and stylized outputs and reduce artifact rates on complex compositions.

Third-party model integrations expanded significantly: Veo 3, Sora 2, Kling, and Seedance are now accessible directly through Leonardo's interface and API, allowing users to run multiple leading video generation models from a single platform without separate subscriptions.

Motion 2.0, the platform's image-to-video system, received updates improving motion coherence across longer clips, enabling longer output durations, and adding improved lip sync for talking-head and character animation use cases. Sketch-to-image reached sub-second real-time update speeds, making it the fastest sketch-to-image implementation available as of May 2026.

Leonardo AI is best for creative professionals, game developers, and enterprise teams who need high-volume image and video generation with access to multiple leading models from a single API and interface.$dl48$,
  pros = ARRAY[
    'Creative Engine API: enterprise code extraction and replication of generation pipelines',
    'Alchemy v4 and Phoenix architecture reduce artifacts on complex photorealistic outputs',
    'Integrates Veo 3, Sora 2, Kling, and Seedance — multiple top models in one platform',
    'Sketch-to-image with sub-second real-time updates — best-in-class speed as of May 2026',
    'Motion 2.0: better motion coherence, longer clips, and improved lip sync for video'
  ],
  cons = ARRAY[
    'Enterprise Creative Engine API pricing not publicly listed — requires sales contact',
    'Multiple model integrations make the platform complex to navigate for new users',
    'Credit consumption varies by model — Veo 3 and Sora 2 are significantly more expensive per generation',
    'Free tier has limited daily token allocation — insufficient for professional volume use'
  ]
WHERE slug = $d48$leonardo-ai$d48$ AND lang = $d48$en$d48$;

-- ============================================================
-- 49. COMFYUI
-- ============================================================
UPDATE tools SET
  name        = $d49$ComfyUI$d49$,
  url         = $d49$https://comfyui.org$d49$,
  domain      = $d49$comfyui.org$d49$,
  badge       = $d49$free$d49$,
  best_for    = $d49$open-source AI image generation, node workflows, local GPU, 4K video$d49$,
  description = $d49$ComfyUI added an App View for beginners alongside the node editor, NVFP4 quantization for 2.5x speed on RTX 50 Series, AMD ROCm support, and Veo 3/Kling 3.0 nodes. Free and open-source.$d49$,
  description_long = $dl49$ComfyUI is a free, open-source node-based interface for running AI image and video generation models locally. Users build workflows by connecting nodes — each node performs one operation such as loading a model, applying a sampler, or encoding a prompt — giving precise control over every step of the generation process. It is the primary interface for users who run Stable Diffusion and other open-weight models on their own hardware.

App View, a major UX addition, provides a simplified interface that hides the node graph and presents a clean form-based UI for users who do not need to modify the underlying workflow. Node View remains fully available for advanced users. This dual-mode approach makes ComfyUI accessible to beginners without removing any capability from experienced users.

NVFP4 quantization, introduced for NVIDIA RTX 50 Series GPUs, enables generation to run 2.5 times faster while reducing VRAM consumption by approximately 60%. This means users with RTX 50 Series cards can run larger models that previously required more expensive hardware, or run existing models at substantially higher speeds.

Official AMD ROCm support landed for the Windows Desktop app, making ComfyUI fully supported on AMD GPUs on Windows for the first time without requiring manual workarounds. New nodes for Veo 3, Veo 3 Lite, and Kling 3.0 were added, along with 4K output support for ByteDance, Veo, and Kling video generation pipelines. RTX Video Super Resolution enables real-time 4K upscaling of generated video on supported NVIDIA hardware.

Python 3.13 compatibility was added, keeping ComfyUI current with the latest Python release and ensuring compatibility with newer packages in the Python ecosystem.

ComfyUI is best for advanced users, researchers, and developers who want full control over AI image and video generation workflows, run models locally on their own hardware, and need support for the latest open-weight and third-party models.$dl49$,
  pros = ARRAY[
    'Completely free and open-source — no subscription, no credit limits, no vendor dependency',
    'App View: beginner-friendly form UI without removing the full node graph for advanced users',
    'NVFP4 quantization: 2.5x faster generation and 60% less VRAM on RTX 50 Series GPUs',
    'Official AMD ROCm support on Windows — no manual workarounds required',
    'Veo 3, Kling 3.0 nodes and 4K video support via ByteDance/Veo/Kling pipelines'
  ],
  cons = ARRAY[
    'Node-based interface has a steep learning curve for users new to workflow-based generation',
    'Requires local GPU hardware — not suitable for users without a capable graphics card',
    'Community-maintained custom nodes vary in quality and may conflict with each other',
    'No cloud option — all computation is local; high-end hardware needed for large models'
  ]
WHERE slug = $d49$comfyui$d49$ AND lang = $d49$en$d49$;

-- ============================================================
-- 50. META AI
-- ============================================================
UPDATE tools SET
  name        = $d50$Meta AI$d50$,
  url         = $d50$https://ai.meta.com$d50$,
  domain      = $d50$ai.meta.com$d50$,
  badge       = $d50$free$d50$,
  best_for    = $d50$AI assistant, WhatsApp/Instagram integration, camera AI, group chats$d50$,
  description = $d50$Meta AI runs on the Llama 4 Muse Spark model with natural interruptions and language mixing. Live AI uses your camera for real-time questions. Deployed across WhatsApp, Instagram, Facebook, Messenger, and Threads.$d50$,
  description_long = $dl50$Meta AI is Meta's conversational AI assistant, powered by the Llama 4 family and deployed across Meta's entire platform ecosystem — WhatsApp, Instagram, Facebook, Messenger, and Threads. Unlike standalone AI assistants, Meta AI is embedded directly into the apps that billions of users already use daily, appearing in search bars, group chats, and post feeds without requiring a separate app or subscription.

The Muse Spark model, which powers the current version of Meta AI, is designed for natural conversational behavior. It supports mid-conversation interruptions — users can cut off a response and redirect the conversation without losing context — and handles topic switching and language mixing fluidly, including switching between languages in the same conversation without explicit instruction.

Live AI is a camera-based feature that enables real-time visual question answering. Users point their device camera at an object, scene, text, or product and ask Meta AI questions about what it sees. The feature works in real time without requiring a screenshot or upload step, enabling use cases like reading labels in a store, identifying plants, or understanding signage in a foreign language.

Side chats in group conversations give users a private channel to ask Meta AI questions that are grounded in the ongoing group discussion — for example, asking for a summary of what was decided, or getting a recommendation based on a destination the group is debating — without posting the AI's response to the whole group.

Meta AI is deployed across all major Meta platforms in the search bar, in group and individual chats, and in the feed. Hatch, an internal AI agent, is in testing for more agentic tasks. Agentic shopping features are planned for Instagram, enabling users to get product recommendations and complete purchases through Meta AI within the app.

Meta AI is best for users already active on Meta platforms who want an AI assistant integrated into their existing communication and social media apps, with no additional app or subscription required.$dl50$,
  pros = ARRAY[
    'Free with no subscription — available to all Meta platform users with no sign-up required',
    'Deployed across WhatsApp, Instagram, Facebook, Messenger, and Threads in one account',
    'Live AI: real-time camera-based visual question answering without uploading screenshots',
    'Muse Spark supports natural interruptions, topic switching, and mid-conversation language mixing',
    'Side chats in group conversations: private AI answers grounded in the group discussion'
  ],
  cons = ARRAY[
    'Capabilities lag behind dedicated AI assistants like ChatGPT or Claude for complex tasks',
    'Data is tied to Meta account — conversations may be used to train or improve Meta models',
    'No desktop-first experience — primarily designed for mobile use within Meta apps',
    'Agentic shopping and Hatch features are still in testing — not yet broadly available'
  ]
WHERE slug = $d50$meta-ai$d50$ AND lang = $d50$en$d50$;
