-- Tool freshness update — Batch 1: Gemini + Claude (short description, 8 active langs)
-- Facts: Gemini 3.5 Flash (stable, +Computer Use 2026-06-24), 3.5 Pro (Deep Think) → July.
--        Claude: Fable 5 (first public Mythos-class model, 2026-06-09) + Opus 4.8.
-- Pricing kept conservative/verified only (Claude Pro $20). Run in Supabase SQL Editor,
-- then: python3 scripts/generate-lang-tool-pages.py (or the tool-page generator).

-- ===== GEMINI =====
UPDATE tools SET description = 'Google''s flagship AI with the deepest Workspace integration. Gemini 3.5 Flash — now with agentic Computer Use — leads the lineup, while the more powerful 3.5 Pro with Deep Think arrives in July. Still the most generous free tier in 2026.' WHERE slug='gemini' AND lang='en';
UPDATE tools SET description = 'Флагманский ИИ Google с глубочайшей интеграцией в Workspace. Gemini 3.5 Flash — теперь с агентным Computer Use — возглавляет линейку, а более мощная 3.5 Pro с Deep Think выйдет в июле. По-прежнему самый щедрый бесплатный тариф в 2026 году.' WHERE slug='gemini' AND lang='ru';
UPDATE tools SET description = 'Флагманський ШІ Google з найглибшою інтеграцією у Workspace. Gemini 3.5 Flash — тепер з агентним Computer Use — очолює лінійку, а потужніша 3.5 Pro з Deep Think вийде в липні. Досі найщедріший безкоштовний тариф у 2026 році.' WHERE slug='gemini' AND lang='ua';
UPDATE tools SET description = 'ה-AI המוביל של Google עם האינטגרציה העמוקה ביותר ב-Workspace. Gemini 3.5 Flash — כעת עם Computer Use סוכנותי — מוביל את הסדרה, בעוד ש-3.5 Pro החזק יותר עם Deep Think יגיע ביולי. עדיין מסלול החינם הנדיב ביותר ב-2026.' WHERE slug='gemini' AND lang='he';
UPDATE tools SET description = 'Googles Flaggschiff-KI mit der tiefsten Workspace-Integration. Gemini 3.5 Flash — jetzt mit agentischem Computer Use — führt die Reihe an, während das stärkere 3.5 Pro mit Deep Think im Juli erscheint. Weiterhin die großzügigste kostenlose Stufe 2026.' WHERE slug='gemini' AND lang='de';
UPDATE tools SET description = 'La IA insignia de Google con la integración más profunda en Workspace. Gemini 3.5 Flash —ahora con Computer Use con agentes— encabeza la gama, mientras que el más potente 3.5 Pro con Deep Think llega en julio. Sigue siendo el nivel gratuito más generoso de 2026.' WHERE slug='gemini' AND lang='es';
UPDATE tools SET description = 'L''IA phare de Google avec l''intégration Workspace la plus poussée. Gemini 3.5 Flash — désormais avec Computer Use agentique — domine la gamme, tandis que le plus puissant 3.5 Pro avec Deep Think arrive en juillet. Toujours l''offre gratuite la plus généreuse de 2026.' WHERE slug='gemini' AND lang='fr';
UPDATE tools SET description = 'A IA principal do Google com a integração mais profunda no Workspace. O Gemini 3.5 Flash — agora com Computer Use com agentes — lidera a linha, enquanto o mais potente 3.5 Pro com Deep Think chega em julho. Ainda o nível gratuito mais generoso de 2026.' WHERE slug='gemini' AND lang='pt';

-- ===== CLAUDE =====
UPDATE tools SET description = 'Anthropic''s AI assistant, known for careful reasoning, coding and long documents. Now offers Fable 5 — its first Mythos-class model for the public — alongside the faster Opus 4.8. Free tier plus Pro ($20/mo), Max and Enterprise plans.' WHERE slug='claude' AND lang='en';
UPDATE tools SET description = 'ИИ-ассистент Anthropic, известный аккуратными рассуждениями, программированием и работой с длинными документами. Теперь доступна Fable 5 — первая модель класса Mythos для широкой публики — вместе с более быстрой Opus 4.8. Бесплатный тариф, а также Pro ($20/мес), Max и Enterprise.' WHERE slug='claude' AND lang='ru';
UPDATE tools SET description = 'ШІ-асистент Anthropic, відомий акуратними міркуваннями, програмуванням і роботою з довгими документами. Тепер доступна Fable 5 — перша модель класу Mythos для широкого загалу — разом зі швидшою Opus 4.8. Безкоштовний тариф, а також Pro ($20/міс), Max та Enterprise.' WHERE slug='claude' AND lang='ua';
UPDATE tools SET description = 'עוזר ה-AI של Anthropic, מוכר בחשיבה זהירה, תכנות ועבודה עם מסמכים ארוכים. כעת מציע את Fable 5 — מודל ה-Mythos הראשון שלו לציבור הרחב — לצד Opus 4.8 המהיר יותר. מסלול חינם וכן תוכניות Pro ($20 לחודש), Max ו-Enterprise.' WHERE slug='claude' AND lang='he';
UPDATE tools SET description = 'Anthropics KI-Assistent, bekannt für sorgfältiges Reasoning, Programmieren und lange Dokumente. Bietet jetzt Fable 5 — sein erstes Mythos-Modell für die Öffentlichkeit — neben dem schnelleren Opus 4.8. Kostenlose Stufe sowie Pro ($20/Monat), Max und Enterprise.' WHERE slug='claude' AND lang='de';
UPDATE tools SET description = 'El asistente de IA de Anthropic, conocido por su razonamiento cuidadoso, la programación y los documentos largos. Ahora ofrece Fable 5 —su primer modelo de clase Mythos para el público— junto al más rápido Opus 4.8. Nivel gratuito y planes Pro ($20/mes), Max y Enterprise.' WHERE slug='claude' AND lang='es';
UPDATE tools SET description = 'L''assistant IA d''Anthropic, reconnu pour son raisonnement soigné, le code et les documents longs. Propose désormais Fable 5 — son premier modèle de classe Mythos pour le grand public — aux côtés du plus rapide Opus 4.8. Offre gratuite et forfaits Pro (20 $/mois), Max et Enterprise.' WHERE slug='claude' AND lang='fr';
UPDATE tools SET description = 'O assistente de IA da Anthropic, conhecido por raciocínio cuidadoso, programação e documentos longos. Agora oferece o Fable 5 — seu primeiro modelo da classe Mythos para o público — ao lado do mais rápido Opus 4.8. Nível gratuito e planos Pro ($20/mês), Max e Enterprise.' WHERE slug='claude' AND lang='pt';
