#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Update EN content for nocode, presentations, and business-investment categories."""
import urllib.request, json, os

SB_URL     = 'https://lbjdwkvkkndvofysyssy.supabase.co'
SB_SERVICE = os.environ.get('SB_SERVICE_KEY', '')
if not SB_SERVICE:
    print('ERROR: Set SB_SERVICE_KEY'); exit(1)

HDRS = {
    'apikey': SB_SERVICE,
    'Authorization': f'Bearer {SB_SERVICE}',
    'Content-Type': 'application/json',
    'Prefer': 'return=minimal'
}

UPDATES = {
  # ── NOCODE ────────────────────────────────────────────────────────────────────
  'bubble': {
    'badge': 'freemium', 'users': '3M+',
    'best_for': 'No-code web application builder with full database and logic support',
    'description': 'The most powerful no-code platform for building complex web apps — marketplaces, SaaS tools, internal dashboards. 3M+ users. Free; Starter $29/mo; Growth $119/mo; Team $349/mo.',
    'description_long': "Bubble is the most capable no-code web application builder available, used by over 3 million developers and entrepreneurs to build fully functional web applications — marketplaces, SaaS products, CRM systems, and internal tools — without traditional programming. Unlike website builders (Webflow, Squarespace), Bubble handles complex logic, user authentication, databases, APIs, and multi-user workflows that constitute a real web application.\n\nBubble's visual editor lets builders define database structures, create complex conditional logic, design responsive interfaces, and connect to external APIs — all through visual interfaces rather than code. The platform runs on Bubble's managed infrastructure, handling hosting, scaling, and database management. AI features added in 2024-2025 enable describing features in natural language and having Bubble generate the corresponding elements and logic.\n\nKey capabilities include a visual relational database, complex conditional logic and workflows, user authentication and permissions, responsive design editor, API connector for external integrations, plugin ecosystem (1,000+ plugins), Bubble AI for natural language app building, and managed hosting with automatic scaling.\n\nPricing: Free plan provides full building capability with a Bubble subdomain and limited capacity. Starter at $29 per month adds a custom domain and increased capacity. Growth at $119 per month provides higher capacity for apps with growing user bases. Team at $349 per month provides the highest capacity and collaboration features. Enterprise pricing is custom.\n\nLimitations: Bubble has a steep learning curve — mastering its visual logic and database design requires significant time investment. Performance on complex queries and large datasets can be slower than custom-coded applications. Migrating off Bubble is difficult — vendor lock-in is real. Free plan capacity is insufficient for anything beyond development.\n\nBest suited for entrepreneurs, startup founders, and non-technical teams who want to build fully functional web applications and SaaS products without development resources.",
    'pros': ['Most powerful no-code platform — handles complex database logic, auth, and multi-user workflows', 'AI-assisted app building via natural language feature descriptions', '1,000+ plugins extend core capabilities significantly', '3M+ users with strong community tutorials and templates', 'Managed hosting with automatic scaling — no DevOps required'],
    'cons': ['Steep learning curve — mastering visual logic takes significant time', 'Performance slower than custom-coded apps on complex queries and large datasets', 'Vendor lock-in — migrating off Bubble is difficult and expensive', 'Free plan capacity too limited for production apps'],
  },
  'flutterflow': {
    'badge': 'freemium', 'users': '500K+',
    'best_for': 'Visual mobile and web app builder that exports clean Flutter code',
    'description': 'Visual builder for Flutter mobile and web apps. Generates production-quality Dart/Flutter code you can export. Free; Basic $39/mo; Growth $80/mo; Business $150/mo.',
    'description_long': "FlutterFlow is a visual application builder that generates production-quality Flutter/Dart code for iOS, Android, and web apps. Unlike other no-code tools that lock users into a proprietary runtime, FlutterFlow produces real, exportable Flutter code — meaning teams can start visually and transition to code-based development when complexity demands it.\n\nThe platform includes a visual UI editor with drag-and-drop components, a state management system, API and backend integrations (Firebase, Supabase, REST APIs), a logic builder for conditional actions, and AI features that generate components and pages from natural language descriptions. FlutterFlow AI (powered by Claude) can build complete app screens from text prompts.\n\nKey capabilities include visual Flutter UI building, production-quality Dart code export, Firebase and Supabase native integration, REST API integration, state management, FlutterFlow AI for natural language app generation, a custom actions system for writing Dart code when needed, and TestFlight/Play Store direct deployment.\n\nPricing: Free plan provides full building capability with FlutterFlow subdomain deployment (no code export). Basic at $39 per month adds code export and custom domain. Growth at $80 per month adds GitHub sync and team features. Business at $150 per month provides priority support and advanced team management.\n\nLimitations: Code export requires the Basic plan or above — the key differentiator over other no-code tools requires paying. Building complex custom interactions sometimes requires dropping into custom Dart code, reducing the pure no-code promise. Flutter knowledge helps significantly when customizing exported code.\n\nBest suited for mobile app developers who want to accelerate UI development, agencies building client mobile apps, and entrepreneurs who want a no-code start with a clear code-export exit strategy.",
    'pros': ['Exports production-quality Flutter/Dart code — no permanent vendor lock-in', 'FlutterFlow AI generates complete screens from natural language prompts', 'Native Firebase and Supabase integration for backend setup', 'Deploys directly to iOS App Store, Google Play, and web', 'Clear path from visual to code-based development as complexity grows'],
    'cons': ['Code export requires Basic plan ($39/mo) — free tier builds but cannot export', 'Complex custom interactions require custom Dart code — not purely no-code', 'Flutter knowledge needed to effectively customize exported code', 'Smaller community and plugin ecosystem than Bubble'],
  },
  'glide': {
    'badge': 'freemium', 'users': '100K+',
    'best_for': 'No-code apps built from Google Sheets, Excel, and Airtable data',
    'description': 'No-code app builder that turns spreadsheets (Google Sheets, Excel, Airtable) into mobile and web apps. AI-powered components. Free; Maker $25/mo; Team $99/mo; Business $249/mo.',
    'description_long': "Glide is a no-code app builder that creates mobile and web applications directly from spreadsheet data — Google Sheets, Excel, Airtable, or Glide's own native tables. It occupies a different niche from Bubble (which handles complex custom logic) by focusing on making data in spreadsheets interactive and presentable as a user-facing app.\n\nCommon use cases include internal tools (inventory management, team directories, event check-in), customer-facing apps (service catalogs, booking tools, directories), and data-driven apps where the underlying data lives in a spreadsheet that stakeholders already manage. Glide apps update automatically when the source spreadsheet is updated.\n\nKey capabilities include data source connections (Google Sheets, Excel, Airtable, Glide Tables), drag-and-drop UI building, AI-powered columns (run AI formulas on each row — classify text, extract data, generate descriptions), user authentication, form submission, action buttons, and integration with Zapier and Make.\n\nPricing: Free plan provides basic app building with limited rows and a Glide subdomain. Maker at $25 per month adds custom domains and more rows. Team at $99 per month provides team collaboration and higher data limits. Business at $249 per month provides the highest limits and enterprise features.\n\nLimitations: Glide is best for data-presentation and simple form/action apps — it is not suitable for complex multi-step workflows or apps with sophisticated business logic. Scalability is limited by spreadsheet data source constraints. The Business plan at $249/month is expensive for what is fundamentally a spreadsheet-to-app converter.\n\nBest suited for teams with data in spreadsheets who need to create functional apps for internal or client use — without requiring development resources.",
    'pros': ['Instantly turns Google Sheets, Excel, or Airtable into mobile and web apps', 'AI-powered columns run AI formulas on each spreadsheet row automatically', 'App updates automatically when the source spreadsheet is updated', 'Lowest learning curve of any no-code app builder for spreadsheet-native users', 'Form submissions and action buttons add interactivity to static data'],
    'cons': ['Limited to data-presentation and simple action apps — not suitable for complex logic', 'Scalability constrained by spreadsheet data source limitations', 'Business plan at $249/mo expensive relative to capabilities', 'Weaker than Bubble for custom UI or multi-step workflows'],
  },
  'lovable': {
    'badge': 'freemium', 'users': '500K+',
    'best_for': 'AI vibe coding — generate full-stack web apps from natural language prompts',
    'description': 'The hottest AI app builder in 2025-2026. Describe a full-stack web app in natural language, Lovable builds it — React frontend, Supabase backend, deployed instantly. Free 5 credits/day; Starter $20/mo; Pro $25/mo.',
    'description_long': "Lovable is an AI-first full-stack web application builder that generates complete React applications — with Supabase backend, authentication, and database — from natural language descriptions. It emerged as one of the fastest-growing developer tools in 2025, representing the 'vibe coding' trend of generating and iterating on full applications through conversation.\n\nThe workflow is conversational: describe a feature, Lovable generates the code, deploys a live preview URL, and waits for feedback. Iteration happens by describing changes in plain language — 'add a search bar to the top', 'make the card grid show 3 columns on desktop', 'add user authentication'. The generated code is real React/TypeScript that can be exported, deployed to custom domains, or synced to GitHub.\n\nKey capabilities include natural language full-stack app generation, React and TypeScript code generation, native Supabase integration (database, auth, storage), live preview URLs for every iteration, GitHub sync, custom domain deployment, Stripe payment integration, and a visual editor for design adjustments.\n\nPricing: Free plan provides 5 generation credits per day. Starter at $20 per month provides 100 credits per month and custom domains. Pro at $25 per month provides 200 credits per month and all features. Additional credit packs are purchasable. Teams and Enterprise pricing is available.\n\nLimitations: Generation credits are consumed per AI request — complex features and iterative debugging can exhaust credits quickly. Generated code, while functional, often requires developer review and cleanup for production-quality standards. Complex enterprise application patterns are beyond current capabilities.\n\nBest suited for entrepreneurs, designers, and product managers who want to build and prototype functional web applications without writing code — and for developers who want to accelerate scaffolding and prototyping.",
    'pros': ['Generates complete full-stack React + Supabase apps from natural language prompts', 'Live preview URLs for every iteration — test changes instantly', 'GitHub sync enables developer collaboration and version control', 'Stripe payment integration for launching paid products quickly', 'Represents the forefront of vibe coding — fastest path from idea to deployed app'],
    'cons': ['Credits consumed per AI request — iterative debugging exhausts monthly allowance quickly', 'Generated code requires developer review for production-quality standards', 'Pro at $25/mo limited to 200 credits — insufficient for complex multi-feature apps', 'Complex enterprise patterns beyond current AI generation capabilities'],
  },
  'softr': {
    'badge': 'freemium', 'users': '',
    'best_for': 'No-code client portals and internal tools built on Airtable and Google Sheets',
    'description': 'No-code builder for client portals, member sites, and internal tools using Airtable or Google Sheets as the database. Free; Business $269/mo annual for full features.',
    'description_long': "Softr is a no-code app builder specialized for creating client portals, member directories, internal dashboards, and data-driven websites using Airtable, Google Sheets, or HubSpot as the backend database. Its focus on portals — gated, login-required web apps that present external data to specific users — differentiates it from general-purpose no-code tools.\n\nThe typical Softr use case is a client portal where customers can log in and see their project status, invoices, or service data from an Airtable or Google Sheets database that the agency manages in the background. This requires no code — the Softr interface allows dragging portal components, setting up login/authentication, and defining which records are visible to which users based on email matching.\n\nKey capabilities include Airtable and Google Sheets native integration, user authentication and membership, data filtering by logged-in user, payment gating via Stripe and PayPal, portal and directory templates, drag-and-drop page builder, custom domains, and form submissions back to the data source.\n\nPricing: Free plan provides limited blocks and no custom domain. Business at $269 per month (annual billing) is the main paid tier for professional use — it provides custom domains, unlimited records, all authentication features, and team management. Enterprise pricing is custom.\n\nLimitations: Softr is specialized — it excels at portals and data-presentation apps but lacks the flexibility of Bubble for complex multi-step logic. The Business plan price jump from free to $269/month is steep with no intermediate option for small teams. The platform is best when Airtable or Google Sheets is already the data source.\n\nBest suited for agencies, consultants, and SaaS companies that need to give clients gated access to their own data — typically companies already managing client data in Airtable.",
    'pros': ['Best no-code tool for client portals and gated member sites', 'Native Airtable and Google Sheets integration — works with data you already manage', 'User-specific data filtering shows each user only their own records', 'Payment gating via Stripe/PayPal for membership and access control', 'Pre-built portal and directory templates accelerate common use case setup'],
    'cons': ['Business plan at $269/mo annual is a large price jump from the free tier', 'Specialized for portals — limited flexibility for complex custom app logic', 'Best when Airtable or Google Sheets is already the data source', 'Less capable than Bubble for multi-step workflows and complex logic'],
  },
  'webflow': {
    'badge': 'freemium', 'users': '3.5M+',
    'best_for': 'Professional no-code website building with designer-level control and CMS',
    'description': 'The professional standard for no-code website design. Designer-level visual control, powerful CMS, and direct CSS/HTML output. Basic $14/mo; CMS $23/mo; Business $39/mo. Legacy Editor removed Aug 2026.',
    'description_long': "Webflow is the professional standard for no-code website design, used by over 3.5 million designers, agencies, and companies to build visually sophisticated websites with full control over layout, animation, and interaction — without writing code. Unlike template-based builders (Wix, Squarespace), Webflow gives designers direct control over CSS classes, flexbox/grid layouts, and custom interactions, producing websites that would typically require a developer to build.\n\nWebflow CMS is a flexible content management system that powers blog-driven sites, product catalogs, and content-heavy marketing sites. Webflow's AI Layouts (2025) generate responsive page layouts from text descriptions. In August 2026, Webflow removed the Legacy Editor — the simpler editing mode — in favor of the full Designer interface.\n\nKey capabilities include a visual CSS/flexbox/grid editor, custom animations and interactions, Webflow CMS for content management, Webflow AI Layouts for AI-generated page layouts, e-commerce functionality, hosting with global CDN, form submissions, code embedding for custom functionality, and a large template marketplace.\n\nPricing: Basic at $14 per month (annual) provides a custom domain and hosting for a simple site. CMS at $23 per month adds the content management system and up to 2,000 CMS items. Business at $39 per month provides 10,000 CMS items, higher traffic limits, and form submissions. E-commerce plans start at $29 per month. Enterprise pricing is custom.\n\nLimitations: Webflow has a significant learning curve — mastering the visual CSS editor takes time and benefits from understanding web design fundamentals. The Legacy Editor removal in August 2026 may frustrate non-technical editors who relied on it. Webflow is a website builder, not a web application builder — it is not suitable for complex app logic.\n\nBest suited for professional designers, agencies, and design-forward companies who need maximum visual control and cannot achieve their design vision with simpler website builders.",
    'pros': ['Maximum visual control over CSS, animations, and interactions for professional design', 'Webflow CMS handles complex content structures for content-heavy sites', 'AI Layouts generate responsive page layouts from text descriptions', '3.5M+ users with strong designer community and extensive template marketplace', 'Output is clean HTML/CSS deployable on custom hosting if needed'],
    'cons': ['Steep learning curve — understanding CSS fundamentals strongly recommended', 'Legacy Editor removed Aug 2026 — non-technical editors face a learning adjustment', 'Website builder only — not suitable for complex application logic like Bubble', 'E-commerce plan required for online store functionality — additional cost'],
  },

  # ── PRESENTATIONS ─────────────────────────────────────────────────────────────
  'beautiful-ai': {
    'badge': 'freemium', 'users': '',
    'best_for': 'Smart presentation slides that auto-format as you add content',
    'description': 'Presentation tool with "smart slides" that automatically reformat and resize content as you add it. No true free tier — 14-day trial only. Pro $12/mo annual; Team $40/user/mo.',
    'description_long': "Beautiful.ai is a presentation tool built around smart slides — slide templates that automatically reformat and resize as content is added. Rather than manually adjusting layouts when adding bullet points or images, Beautiful.ai's slides maintain visual balance automatically, reducing the time spent on formatting versus content.\n\nThe AI features include a presentation generator that creates a slide deck from a text description or pasted outline, an AI writer for generating slide content, and an AI image generator for visual slide elements. The brand kit ensures all slides use consistent colors, fonts, and logos.\n\nKey capabilities include smart slide auto-formatting, AI presentation generator from text outlines, AI content writer for slides, brand kit for consistent styling, team collaboration with real-time editing, presentation analytics (who viewed, how long), and export to PowerPoint.\n\nPricing: There is no permanent free plan — Beautiful.ai offers a 14-day free trial. Pro at $12 per month (annual) is for individual use. Team at $40 per user per month provides shared templates, brand controls, and admin features. Enterprise pricing is custom.\n\nLimitations: The lack of a free plan beyond the trial is a significant barrier for testing. The $40 per user per month Team plan is expensive — especially compared to Gamma at $8/month or Pitch at $8/month for team plans. Smart slides, while useful, can sometimes feel constraining when specific custom layouts are needed.\n\nBest suited for business teams that frequently create presentations and want to eliminate formatting time — particularly those on the Team plan who need consistent brand compliance across team presentations.",
    'pros': ['Smart slides auto-reformat as content is added — eliminates manual layout adjustment', 'AI presentation generator creates full decks from text outlines', 'Brand kit ensures visual consistency across team presentations', 'Presentation analytics track viewer engagement with your deck', 'Export to PowerPoint for stakeholders who need editable slides'],
    'cons': ['No permanent free plan — 14-day trial only before payment required', 'Team plan at $40/user/mo expensive compared to alternatives (Gamma $8, Pitch $8)', 'Smart slides can constrain highly custom layout requirements', 'Less capable than Gamma for document and web page creation beyond slides'],
  },
  'pitch': {
    'badge': 'freemium', 'users': '1M+',
    'best_for': 'Collaborative team presentations with real-time editing and analytics',
    'description': 'Collaborative presentation tool for teams with real-time editing, analytics, and a polished template library. Free individual plan; Pro $12/mo per workspace.',
    'description_long': "Pitch is a presentation tool designed for team collaboration, offering real-time multi-user editing similar to Figma's collaborative editing model for slide decks. It has grown to over 1 million users with particularly strong adoption among startup and tech teams.\n\nPitch's design sensibility prioritizes modern, clean aesthetics — its template library is smaller than Canva but curated for professional business use. The platform includes presentation analytics showing who opened the deck, how long they spent on each slide, and whether they downloaded it. AI features generate outline structures and slide content from text prompts.\n\nKey capabilities include real-time collaborative editing, AI presentation generation from outlines, slide analytics (opens, time spent, downloads), workspace management for team assets, 100+ curated templates, embedding and sharing via link, integrations with Slack, Notion, and Figma, and export to PDF and PowerPoint.\n\nPricing: Free plan provides full presentation building with unlimited decks and 1 workspace. Pro at $12 per month provides unlimited workspaces, advanced analytics, custom domain, and priority support. Team plan provides multiple seats with shared brand assets.\n\nLimitations: Pitch's template library is curated but smaller than Canva or Gamma. The AI features are less sophisticated than dedicated AI presentation tools like Gamma. For solo users, Pitch's collaborative features are less valuable.\n\nBest suited for startups, agencies, and product teams that collaborate on presentations and value clean design aesthetics and engagement analytics.",
    'pros': ['Real-time collaborative editing — multiple team members work simultaneously', 'Presentation analytics show who viewed each slide and for how long', 'Free plan provides full feature access with unlimited decks', 'Clean, modern template library appropriate for professional business contexts', 'Integrations with Slack, Notion, and Figma for team workflow'],
    'cons': ['Smaller template library than Canva or PowerPoint', 'AI generation less sophisticated than dedicated tools like Gamma', 'Less valuable for solo users where collaboration features are not needed', 'Pro analytics and workspace features require paid plan'],
  },
  'prezi': {
    'badge': 'freemium', 'users': '100M+',
    'best_for': 'Non-linear AI presentations with zoom and pan storytelling format',
    'description': 'Non-linear presentation tool with zoom-and-pan navigation for storytelling-style presentations. AI generates structures from text prompts. 100M+ users. Standard $7/user/mo, Plus $15, Premium $25.',
    'description_long': "Prezi is a presentation platform that pioneered the non-linear, zoom-and-pan presentation format as an alternative to traditional slide-by-slide decks. Rather than moving through fixed slides, Prezi presentations navigate a spatial canvas — zooming into subtopics and panning between sections — which can be more engaging for storytelling and exploratory presentations.\n\nPrezi has 100 million users and remains the leading choice for presentations where visual storytelling, spatial narrative, or overview-then-detail structures are needed. Prezi AI generates presentation structures from text prompts, and Prezi Video places the presenter inside the presentation for video-based delivery — popular for recorded pitches and virtual presentations.\n\nKey capabilities include the non-linear spatial canvas, zoom-and-pan navigation, AI presentation generation from text prompts, Prezi Video for presenter-in-slide video delivery, templates for the spatial format, real-time collaboration, and analytics.\n\nPricing: Free plan provides 1 Prezi with limited features and Prezi branding. Standard at $7 per user per month provides 3 Prezis and basic features. Plus at $15 per user per month provides unlimited Prezis, privacy controls, and offline access. Premium at $25 per user per month adds analytics and full Prezi Video features. Teams plan at $39 per user per month provides admin and brand features.\n\nLimitations: The non-linear format is distinctive but can be disorienting for audiences unfamiliar with it — the zooming effect has been criticized as dizzying. Prezi is less versatile than PowerPoint or Gamma for standard business presentations. The free tier is very limited at 1 Prezi.\n\nBest suited for educators, sales professionals, and presenters who want spatial storytelling formats that would feel flat in a traditional slide deck — particularly for pitches, educational content, and complex multi-layered topics.",
    'pros': ['Non-linear spatial canvas enables storytelling formats impossible in slide decks', '100M+ users — most widely used non-PowerPoint presentation format', 'Prezi Video places presenter inside the presentation for video delivery', 'AI generates complete structures from text prompts', 'Effective for overview-then-detail narrative structures'],
    'cons': ['Zooming format can be disorienting or dizzying for audiences', 'Less versatile than PowerPoint or Gamma for standard business presentation formats', 'Free tier very limited — only 1 Prezi with branding', 'Learning curve to use spatial canvas effectively compared to linear slides'],
  },
  'slidesgo': {
    'badge': 'freemium', 'users': '20M+',
    'best_for': 'Free AI-powered presentation templates for Google Slides and PowerPoint',
    'description': 'AI presentation generator with 15,000+ templates for Google Slides and PowerPoint. Free 12 templates/mo; Premium $3/mo. 20M+ monthly users. Best value for template-based presentations.',
    'description_long': "Slidesgo is a presentation template platform with AI generation capabilities, providing over 15,000 professionally designed templates for Google Slides, PowerPoint, and Canva. It is one of the most-used presentation tools globally with 20 million monthly users, primarily due to its generous free tier and template variety.\n\nSlidesgo AI generates complete presentation decks from a topic description, selecting appropriate templates and generating slide content. The templates cover virtually every presentation use case — business reports, educational presentations, marketing decks, project proposals, event announcements, and more — with new templates added weekly.\n\nKey capabilities include AI presentation generation from text prompts, 15,000+ templates for Google Slides and PowerPoint, Canva integration for editing, automatic customization to brand colors, animated templates, and free images and icons included in templates.\n\nPricing: Free plan provides access to 12 template downloads per month and basic AI generation. Premium at $3 per month (annual) provides unlimited downloads, premium templates, and full AI generation features. The $3/month price point makes Premium one of the most affordable paid presentation tools available.\n\nLimitations: Template-based approach means output can look similar to other Slidesgo users — lack of uniqueness for brand-sensitive presentations. AI generation quality produces usable but not distinctive presentations. Full AI capabilities and unlimited templates require the Premium plan, even though the $3/month price is very low.\n\nBest suited for students, educators, small business owners, and individuals who need professional-looking presentations quickly without a large budget — particularly those who work regularly in Google Slides or PowerPoint.",
    'pros': ['$3/month Premium is the most affordable paid AI presentation tool available', '15,000+ templates covering virtually every presentation use case', 'AI generation creates complete decks from a single topic description', 'Works natively in Google Slides and PowerPoint — no new tool to learn', '20M+ monthly users validates broad template quality and variety'],
    'cons': ['Template-based output recognizable to audiences familiar with Slidesgo', 'AI generation quality not as distinctive as Gamma or Beautiful.ai', 'Free tier limited to 12 downloads/month', 'Best templates require Premium subscription'],
  },

  # ── BUSINESS-INVESTMENT ───────────────────────────────────────────────────────
  'finchat': {
    'badge': 'freemium', 'users': '350K+',
    'name': 'Fiscal.ai',
    'url': 'https://fiscal.ai',
    'domain': 'fiscal.ai',
    'best_for': 'AI-powered financial research and stock analysis for investors',
    'description': 'Rebranded from FinChat to Fiscal.ai. AI financial research tool with data on 100K+ public companies — financials, transcripts, KPIs, and AI-generated analysis. Plus $24/mo; Pro $64/mo.',
    'description_long': "Fiscal.ai (formerly FinChat.io, rebranded in 2025) is an AI-powered financial research platform providing data and analysis on over 100,000 public companies worldwide. It combines structured financial data — income statements, balance sheets, cash flow, KPIs — with AI that can analyze earnings transcripts, generate company summaries, and answer specific financial questions using that data.\n\nThe platform aggregates data from SEC filings, earnings transcripts, and financial databases, then applies AI to make that information interactive. Users can ask questions like 'what was Apple's gross margin trend over the last 8 quarters' and receive answers with charts directly from the data — rather than manually building models in Excel.\n\nKey capabilities include financials and KPIs for 100K+ public companies, AI analysis of earnings transcripts, natural language financial queries with chart generation, company comparison tools, industry peer analysis, export to Excel and Google Sheets, and AI-generated investment thesis summaries.\n\nPricing: Free plan provides limited queries and basic data access. Plus at $24 per month provides expanded data access, unlimited AI queries, and full transcript search. Pro at $64 per month provides advanced features, institutional-grade data, and higher export limits.\n\nLimitations: Fiscal.ai covers public companies only — no private company data or alternative data sources. The AI analysis is based on publicly available data and should not be treated as investment advice. Data coverage for non-US companies varies in completeness compared to US public companies.\n\nBest suited for retail investors, finance students, and professionals who want fast AI-assisted analysis of public company financials without maintaining expensive Bloomberg or FactSet subscriptions.",
    'pros': ['100K+ public company coverage with AI-powered analysis of financials and transcripts', 'Natural language queries generate charts and data summaries from financial filings', 'AI earnings transcript analysis extracts key statements and management tone', 'Plus at $24/mo is significantly cheaper than Bloomberg or FactSet alternatives', 'Export to Excel and Google Sheets for further modeling'],
    'cons': ['Public companies only — no private company or alternative data', 'AI analysis based on public data — not a substitute for professional investment advice', 'Non-US company data coverage less complete than US public company coverage', 'Pro at $64/mo required for advanced institutional-grade features'],
  },
  'tickeron': {
    'badge': 'paid', 'users': '',
    'best_for': 'AI trading signals and pattern recognition for active traders',
    'description': 'AI trading platform with pattern recognition, price predictions, and portfolio analysis for active traders. Investor $60/mo; Swing $80/mo; Day $90/mo; Expert $250/mo. 50% off annual.',
    'description_long': "Tickeron is an AI trading platform that uses machine learning to identify technical patterns, generate price predictions, and provide trading signals for active investors and traders. The platform covers stocks, ETFs, Forex, and crypto, offering real-time AI analysis alongside educational content and backtesting tools.\n\nTickeron's AI Robots are automated trading signals that identify entry and exit points based on technical patterns — double bottoms, head and shoulders, support/resistance levels, and trend signals. The confidence levels attached to each signal help traders filter for higher-probability setups. The platform also provides AI portfolio analysis with suggestions for rebalancing and risk management.\n\nKey capabilities include AI pattern recognition and trading signals, AI Robots for automated signal generation, price prediction with confidence levels, portfolio analysis and rebalancing suggestions, backtesting, Forex and crypto signals, market scanning, and educational trading content.\n\nPricing: Plans vary by trader type. Investor at $60 per month targets long-term investors. Swing at $80 per month targets swing traders. Day at $90 per month targets day traders with real-time signals. Expert at $250 per month provides all features plus expert-level tools. Annual billing provides 50% discount across all plans.\n\nLimitations: Trading signals and pattern recognition are probabilistic — no AI tool can guarantee profitable trading outcomes. Pattern recognition tools have faced scrutiny over backtesting overfitting, where signals appear strong historically but underperform forward-looking. Platform quality of execution depends entirely on how traders use the signals, not just the signals themselves.\n\nBest suited for active retail traders who want AI-assisted technical analysis and trading signal identification — with the understanding that signals require independent judgment and are not guaranteed to be profitable.",
    'pros': ['AI pattern recognition covers stocks, ETFs, Forex, and crypto', 'AI Robots generate automated trading signals with confidence levels', 'Portfolio analysis with AI rebalancing and risk management suggestions', 'Backtesting enables validation of signal quality on historical data', '50% annual discount makes costs more manageable for regular use'],
    'cons': ['Trading signals are probabilistic — no guarantee of profitability', 'Pattern recognition may suffer from backtesting overfitting versus forward performance', 'Day trader plan ($90/mo) expensive for retail traders on limited budgets', 'AI signals require independent trader judgment — not plug-and-play trading'],
  },
  'tradingview': {
    'badge': 'freemium', 'users': '100M+',
    'best_for': 'Professional charting and trading platform for stocks, crypto, and forex',
    'description': 'The industry-standard charting platform used by 100M+ traders globally. AI-powered indicators, screeners, and analysis tools. Prices raised April 2026. Essential $12.95/mo, Plus $29.95, Premium $59.95.',
    'description_long': "TradingView is the industry-standard charting and market analysis platform used by over 100 million traders globally for stocks, cryptocurrency, forex, futures, and indices. It provides the most comprehensive chart customization and technical analysis toolset available as a web-based platform — with thousands of community-built custom indicators and a Pine Script language for creating custom technical analysis tools.\n\nTradingView raised prices in April 2026 across all tiers. The platform integrates AI-powered features including AI summary (natural language analysis of a security's technical picture), AI screener (identifying stocks meeting AI-generated criteria), and GPT-powered natural language market analysis alongside the classic technical tools.\n\nKey capabilities include multi-timeframe and multi-symbol charts, 100K+ community indicators in the indicator library, Pine Script for custom indicator development, stock and crypto screeners, economic calendar, news integration, broker connections for direct trading (Interactive Brokers, Alpaca, and others), paper trading, and AI summary and screener.\n\nPricing: Free plan provides basic charting with limited indicators and saved charts. Essential at $12.95 per month provides more indicators, saved layouts, and alerts. Plus at $29.95 per month removes ads, adds more charts per layout, and server-side alerts. Premium at $59.95 per month provides the maximum features, chart comparison, and volume profile. Ultimate at $199.95 per month provides the highest data refresh rates and maximum capabilities.\n\nLimitations: The April 2026 price increases made some tiers more expensive. Free plan limitations (indicator count, saved charts) are quite restrictive for serious technical analysis. Pine Script has a learning curve for creating custom indicators.\n\nBest suited for active traders and investors across any asset class who need professional-grade charting and technical analysis tools — from casual investors checking charts to professional traders building custom strategies.",
    'pros': ['Industry standard — used by 100M+ traders globally across all asset classes', '100K+ community indicators and Pine Script for custom development', 'Broker integrations for direct trading within the platform', 'AI summary and screener add natural language analysis to classic technical tools', 'Best-in-class multi-chart layouts and multi-timeframe analysis'],
    'cons': ['Prices raised April 2026 — higher cost than before for all tiers', 'Free plan heavily limited — serious use requires paid subscription', 'Pine Script has a learning curve for custom indicator creation', 'Ultimate plan at $199.95/mo expensive for retail traders'],
  },
  'uptrends-ai': {
    'badge': 'freemium', 'users': '',
    'best_for': 'AI stock market trends and momentum analysis for retail investors',
    'description': 'AI-powered stock analysis platform providing trend detection, sector momentum, and AI market insights for retail investors. Free; Essentials $15/mo; Pro $49/mo.',
    'description_long': "Uptrends AI is a market analysis platform that uses AI to detect stock price trends, sector momentum, and market signals for retail investors. The platform focuses on making institutional-style trend analysis accessible to individual investors without requiring advanced technical knowledge or expensive data subscriptions.\n\nThe AI analyzes price action, volume, and market breadth to surface stocks showing significant trend changes, unusual momentum, or technical pattern setups. Sector rotation analysis identifies where institutional money appears to be flowing across market sectors. The platform provides natural language explanations of its AI findings rather than raw technical indicators.\n\nKey capabilities include AI trend detection for stocks and ETFs, sector rotation and momentum analysis, AI market condition summaries, watchlist management with AI alerts, stock screening by momentum and trend criteria, and a daily market briefing.\n\nPricing: Free plan provides limited stock analysis and basic market summaries. Essentials at $15 per month provides full trend analysis, sector data, and more watchlist capacity. Pro at $49 per month provides advanced analytics, higher watchlist limits, and priority feature access.\n\nLimitations: Uptrends AI is a retail-focused trend tool — it does not provide the depth of fundamental analysis available in platforms like Fiscal.ai or the technical sophistication of TradingView. Coverage is primarily US equities. As a newer platform, the track record for signal quality is shorter than established competitors.\n\nBest suited for retail investors who want AI to surface trending stocks and sector momentum without building complex technical analysis setups themselves.",
    'pros': ['AI surface trending stocks and sector momentum automatically', 'Natural language explanations make AI findings accessible without technical knowledge', 'Sector rotation analysis identifies where institutional money is flowing', 'Free plan available for basic trend analysis', 'Essentials at $15/mo affordable for active retail investors'],
    'cons': ['Limited fundamental analysis depth compared to Fiscal.ai', 'Less technical depth than TradingView for serious chart analysis', 'Primarily US equities coverage', 'Newer platform with shorter track record for signal quality'],
  },
}

def patch(slug, data):
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        f'{SB_URL}/rest/v1/tools?slug=eq.{slug}&lang=eq.en',
        data=body, headers=HDRS, method='PATCH'
    )
    with urllib.request.urlopen(req) as r:
        return r.status

print(f'Updating {len(UPDATES)} tools...')
for slug, fields in UPDATES.items():
    status = patch(slug, fields)
    print(f'  {slug}: HTTP {status}')

print('Done.')
