-- Tool freshness update — Batch 2: nano-banana, writesonic, perplexity, bolt-new,
-- cursor, duolingo-max, khanmigo (short description, 8 active langs).
-- Only stale MODEL-VERSION references corrected; existing pricing left as-is.
-- Run in Supabase SQL Editor, then regenerate tool pages.

-- ===== NANO-BANANA (Gemini 2.5/3 -> 3.5) =====
UPDATE tools SET description = 'AI image editor built on Google''s Gemini 3.5 image model. Industry-leading character consistency — keep faces, outfits and composition identical across multiple edits.' WHERE slug='nano-banana' AND lang='en';
UPDATE tools SET description = 'Редактор изображений на базе модели Google Gemini 3.5. Лучшая в индустрии консистентность персонажей — лица, одежда и композиция остаются одинаковыми при множественных правках.' WHERE slug='nano-banana' AND lang='ru';
UPDATE tools SET description = 'Редактор зображень на базі моделі Google Gemini 3.5. Найкраща в індустрії консистентність персонажів — обличчя, одяг і композиція залишаються однаковими за багатьох правок.' WHERE slug='nano-banana' AND lang='ua';
UPDATE tools SET description = 'עורך תמונות מבוסס על מודל התמונות Gemini 3.5 של Google. עקביות דמויות מהמובילות בתעשייה — שמירה על פנים, לבוש והרכב זהים לאורך עריכות מרובות.' WHERE slug='nano-banana' AND lang='he';
UPDATE tools SET description = 'Bildbearbeitung auf Basis von Googles Gemini-3.5-Bildmodell. Branchenführende Charakterkonsistenz — Gesichter, Outfits und Komposition bleiben über mehrere Bearbeitungen identisch.' WHERE slug='nano-banana' AND lang='de';
UPDATE tools SET description = 'Editor de imágenes basado en el modelo de imagen Gemini 3.5 de Google. Consistencia de personajes líder en el sector: rostros, ropa y composición idénticos a lo largo de varias ediciones.' WHERE slug='nano-banana' AND lang='es';
UPDATE tools SET description = 'Éditeur d''images basé sur le modèle d''image Gemini 3.5 de Google. Cohérence des personnages parmi les meilleures du secteur — visages, tenues et composition identiques sur plusieurs retouches.' WHERE slug='nano-banana' AND lang='fr';
UPDATE tools SET description = 'Editor de imagens baseado no modelo de imagem Gemini 3.5 do Google. Consistência de personagens líder do setor — rostos, roupas e composição idênticos em várias edições.' WHERE slug='nano-banana' AND lang='pt';

-- ===== WRITESONIC (GPT-4o/Claude 3.7/Gemini 1.5 -> latest frontier) =====
UPDATE tools SET description = 'Writesonic is now an AI Search Visibility platform. Article Writer produces long, research-backed articles with competitor analysis, while Chatsonic runs the latest frontier models from OpenAI, Anthropic and Google.' WHERE slug='writesonic' AND lang='en';
UPDATE tools SET description = 'Writesonic теперь платформа AI Search Visibility. Article Writer создаёт длинные статьи с реальным исследованием и анализом конкурентов, а Chatsonic работает на новейших флагманских моделях OpenAI, Anthropic и Google.' WHERE slug='writesonic' AND lang='ru';
UPDATE tools SET description = 'Writesonic тепер платформа AI Search Visibility. Article Writer створює довгі статті з реальним дослідженням і аналізом конкурентів, а Chatsonic працює на найновіших флагманських моделях OpenAI, Anthropic і Google.' WHERE slug='writesonic' AND lang='ua';
UPDATE tools SET description = 'Writesonic היא כעת פלטפורמת AI Search Visibility. Article Writer מפיק מאמרים ארוכים מבוססי מחקר עם ניתוח מתחרים, ו-Chatsonic פועל על המודלים המובילים העדכניים של OpenAI, Anthropic ו-Google.' WHERE slug='writesonic' AND lang='he';
UPDATE tools SET description = 'Writesonic ist jetzt eine AI-Search-Visibility-Plattform. Article Writer erstellt lange, recherchierte Artikel mit Wettbewerbsanalyse, während Chatsonic die neuesten Spitzenmodelle von OpenAI, Anthropic und Google nutzt.' WHERE slug='writesonic' AND lang='de';
UPDATE tools SET description = 'Writesonic es ahora una plataforma de AI Search Visibility. Article Writer produce artículos largos y documentados con análisis de la competencia, mientras Chatsonic usa los últimos modelos punteros de OpenAI, Anthropic y Google.' WHERE slug='writesonic' AND lang='es';
UPDATE tools SET description = 'Writesonic est désormais une plateforme d''AI Search Visibility. Article Writer produit de longs articles documentés avec analyse concurrentielle, tandis que Chatsonic utilise les derniers modèles de pointe d''OpenAI, Anthropic et Google.' WHERE slug='writesonic' AND lang='fr';
UPDATE tools SET description = 'O Writesonic agora é uma plataforma de AI Search Visibility. O Article Writer produz artigos longos e fundamentados com análise de concorrência, enquanto o Chatsonic usa os mais recentes modelos de ponta da OpenAI, Anthropic e Google.' WHERE slug='writesonic' AND lang='pt';

-- ===== PERPLEXITY (Opus 4.6 -> 4.8) =====
UPDATE tools SET description = 'Perplexity''s AI answer engine with cited sources and Deep Research, now running on Claude Opus 4.8. Agentic control on Mac, Teams integration, finance tabs and iOS study tools included.' WHERE slug='perplexity' AND lang='en';
UPDATE tools SET description = 'ИИ-движок ответов Perplexity с цитированием источников и Deep Research, теперь на Claude Opus 4.8. Агентное управление на Mac, интеграция Teams, финансовые вкладки и учебные инструменты на iOS.' WHERE slug='perplexity' AND lang='ru';
UPDATE tools SET description = 'ШІ-рушій відповідей Perplexity з цитуванням джерел і Deep Research, тепер на Claude Opus 4.8. Агентне керування на Mac, інтеграція Teams, фінансові вкладки та навчальні інструменти на iOS.' WHERE slug='perplexity' AND lang='ua';
UPDATE tools SET description = 'מנוע התשובות של Perplexity עם מקורות מצוטטים ו-Deep Research, כעת על Claude Opus 4.8. שליטה סוכנותית ב-Mac, אינטגרציית Teams, לשוניות פיננסים וכלי לימוד ל-iOS.' WHERE slug='perplexity' AND lang='he';
UPDATE tools SET description = 'Perplexitys KI-Antwortmaschine mit zitierten Quellen und Deep Research, jetzt mit Claude Opus 4.8. Agentische Steuerung auf dem Mac, Teams-Integration, Finanz-Tabs und iOS-Lerntools inklusive.' WHERE slug='perplexity' AND lang='de';
UPDATE tools SET description = 'El motor de respuestas con IA de Perplexity, con fuentes citadas y Deep Research, ahora con Claude Opus 4.8. Control con agentes en Mac, integración con Teams, pestañas de finanzas y herramientas de estudio en iOS.' WHERE slug='perplexity' AND lang='es';
UPDATE tools SET description = 'Le moteur de réponses IA de Perplexity, avec sources citées et Deep Research, désormais propulsé par Claude Opus 4.8. Contrôle agentique sur Mac, intégration Teams, onglets finance et outils d''étude iOS.' WHERE slug='perplexity' AND lang='fr';
UPDATE tools SET description = 'O motor de respostas com IA da Perplexity, com fontes citadas e Deep Research, agora com Claude Opus 4.8. Controle com agentes no Mac, integração com Teams, abas de finanças e ferramentas de estudo no iOS.' WHERE slug='perplexity' AND lang='pt';

-- ===== BOLT-NEW (Opus 4.6 -> 4.8) =====
UPDATE tools SET description = 'Bolt builds full-stack web apps from a prompt — bundled database, auth, storage, edge functions and hosting, no third-party services. Now on Claude Opus 4.8 with adjustable reasoning and support for much larger projects.' WHERE slug='bolt-new' AND lang='en';
UPDATE tools SET description = 'Bolt создаёт фулстек веб-приложения по запросу — встроенные база данных, авторизация, хранилище, edge-функции и хостинг, без сторонних сервисов. Теперь на Claude Opus 4.8 с настраиваемым рассуждением и поддержкой намного больших проектов.' WHERE slug='bolt-new' AND lang='ru';
UPDATE tools SET description = 'Bolt створює фулстек вебзастосунки за запитом — вбудовані база даних, авторизація, сховище, edge-функції та хостинг, без сторонніх сервісів. Тепер на Claude Opus 4.8 з налаштовуваним міркуванням і підтримкою значно більших проєктів.' WHERE slug='bolt-new' AND lang='ua';
UPDATE tools SET description = 'Bolt בונה אפליקציות ווב full-stack מתוך פרומפט — מסד נתונים, אימות, אחסון, edge functions ואחסון אתרים מובנים, ללא שירותי צד שלישי. כעת על Claude Opus 4.8 עם חשיבה מתכווננת ותמיכה בפרויקטים גדולים בהרבה.' WHERE slug='bolt-new' AND lang='he';
UPDATE tools SET description = 'Bolt erstellt Full-Stack-Web-Apps aus einem Prompt — mit integrierter Datenbank, Auth, Speicher, Edge Functions und Hosting, ohne Drittanbieter. Jetzt mit Claude Opus 4.8, einstellbarem Reasoning und Unterstützung für deutlich größere Projekte.' WHERE slug='bolt-new' AND lang='de';
UPDATE tools SET description = 'Bolt crea aplicaciones web full-stack desde un prompt: base de datos, autenticación, almacenamiento, edge functions y hosting integrados, sin servicios de terceros. Ahora con Claude Opus 4.8, razonamiento ajustable y soporte para proyectos mucho mayores.' WHERE slug='bolt-new' AND lang='es';
UPDATE tools SET description = 'Bolt crée des applications web full-stack à partir d''un prompt — base de données, auth, stockage, edge functions et hébergement intégrés, sans services tiers. Désormais sur Claude Opus 4.8, avec raisonnement réglable et prise en charge de projets bien plus grands.' WHERE slug='bolt-new' AND lang='fr';
UPDATE tools SET description = 'O Bolt cria aplicativos web full-stack a partir de um prompt — banco de dados, autenticação, armazenamento, edge functions e hospedagem integrados, sem serviços de terceiros. Agora com Claude Opus 4.8, raciocínio ajustável e suporte a projetos muito maiores.' WHERE slug='bolt-new' AND lang='pt';

-- ===== CURSOR (Opus 4.7 -> 4.8) =====
UPDATE tools SET description = 'Cursor 3.4 with Composer 2.5: an agentic dev environment with multi-repo, parallel agents and Dockerfile provisioning. Composer 2.5 hits ~63% SWE-Bench at $0.50/task — near Claude Opus 4.8 quality at a fraction of the cost.' WHERE slug='cursor' AND lang='en';
UPDATE tools SET description = 'Cursor 3.4 с Composer 2.5: агентная среда разработки с мультирепо, параллельными агентами и Dockerfile-провижнингом. Composer 2.5 даёт ~63% на SWE-Bench за $0.50/задача — близко к качеству Claude Opus 4.8 за долю стоимости.' WHERE slug='cursor' AND lang='ru';
UPDATE tools SET description = 'Cursor 3.4 з Composer 2.5: агентне середовище розробки з мультирепо, паралельними агентами та Dockerfile-провіженінгом. Composer 2.5 дає ~63% на SWE-Bench за $0.50/задача — близько до якості Claude Opus 4.8 за частку вартості.' WHERE slug='cursor' AND lang='ua';
UPDATE tools SET description = 'Cursor 3.4 עם Composer 2.5: סביבת פיתוח סוכנותית עם ריבוי מאגרים, סוכנים מקבילים והקצאת Dockerfile. Composer 2.5 מגיע ל-~63% ב-SWE-Bench בעלות $0.50 למשימה — קרוב לאיכות Claude Opus 4.8 בשבריר מהמחיר.' WHERE slug='cursor' AND lang='he';
UPDATE tools SET description = 'Cursor 3.4 mit Composer 2.5: eine agentische Entwicklungsumgebung mit Multi-Repo, parallelen Agenten und Dockerfile-Provisioning. Composer 2.5 erreicht ~63 % SWE-Bench bei $0,50/Aufgabe — nahe an Claude Opus 4.8 zu einem Bruchteil der Kosten.' WHERE slug='cursor' AND lang='de';
UPDATE tools SET description = 'Cursor 3.4 con Composer 2.5: un entorno de desarrollo con agentes, multirepo, agentes en paralelo y aprovisionamiento de Dockerfile. Composer 2.5 alcanza ~63 % en SWE-Bench a $0,50/tarea, cerca de la calidad de Claude Opus 4.8 por una fracción del coste.' WHERE slug='cursor' AND lang='es';
UPDATE tools SET description = 'Cursor 3.4 avec Composer 2.5 : un environnement de développement agentique avec multi-dépôt, agents parallèles et provisionnement Dockerfile. Composer 2.5 atteint ~63 % au SWE-Bench à 0,50 $/tâche — proche de la qualité de Claude Opus 4.8 pour une fraction du coût.' WHERE slug='cursor' AND lang='fr';
UPDATE tools SET description = 'Cursor 3.4 com Composer 2.5: um ambiente de desenvolvimento com agentes, multirrepo, agentes paralelos e provisionamento de Dockerfile. O Composer 2.5 atinge ~63% no SWE-Bench a $0,50/tarefa — perto da qualidade do Claude Opus 4.8 por uma fração do custo.' WHERE slug='cursor' AND lang='pt';

-- ===== DUOLINGO-MAX (GPT-4 -> current GPT) =====
UPDATE tools SET description = 'Duolingo''s premium AI tier: conversation practice, grammar explanations and roleplay scenarios powered by current GPT models. $29.99/mo or $168/yr. Note: Video Call and Explain My Answer are now free for all Duolingo users.' WHERE slug='duolingo-max' AND lang='en';
UPDATE tools SET description = 'Премиум-уровень Duolingo с ИИ: разговорная практика, объяснения грамматики и ролевые сценарии на современных моделях GPT. $29.99/мес или $168/год. Примечание: Video Call и Explain My Answer теперь бесплатны для всех пользователей Duolingo.' WHERE slug='duolingo-max' AND lang='ru';
UPDATE tools SET description = 'Преміум-рівень Duolingo зі ШІ: розмовна практика, пояснення граматики та рольові сценарії на сучасних моделях GPT. $29.99/міс або $168/рік. Примітка: Video Call та Explain My Answer тепер безкоштовні для всіх користувачів Duolingo.' WHERE slug='duolingo-max' AND lang='ua';
UPDATE tools SET description = 'מסלול הפרימיום של Duolingo עם AI: תרגול שיחה, הסברי דקדוק ותרחישי תפקידים המופעלים על מודלי GPT עדכניים. $29.99 לחודש או $168 לשנה. הערה: Video Call ו-Explain My Answer כעת חינמיים לכל משתמשי Duolingo.' WHERE slug='duolingo-max' AND lang='he';
UPDATE tools SET description = 'Duolingos Premium-KI-Stufe: Konversationsübungen, Grammatikerklärungen und Rollenspiele mit aktuellen GPT-Modellen. 29,99 $/Monat oder 168 $/Jahr. Hinweis: Video Call und Explain My Answer sind jetzt für alle Duolingo-Nutzer kostenlos.' WHERE slug='duolingo-max' AND lang='de';
UPDATE tools SET description = 'El nivel premium con IA de Duolingo: práctica de conversación, explicaciones gramaticales y juegos de rol con modelos GPT actuales. $29.99/mes o $168/año. Nota: Video Call y Explain My Answer ahora son gratis para todos los usuarios de Duolingo.' WHERE slug='duolingo-max' AND lang='es';
UPDATE tools SET description = 'L''offre premium IA de Duolingo : pratique de conversation, explications grammaticales et jeux de rôle propulsés par les modèles GPT actuels. 29,99 $/mois ou 168 $/an. Note : Video Call et Explain My Answer sont désormais gratuits pour tous les utilisateurs de Duolingo.' WHERE slug='duolingo-max' AND lang='fr';
UPDATE tools SET description = 'O nível premium com IA do Duolingo: prática de conversação, explicações de gramática e cenários de roleplay com modelos GPT atuais. $29.99/mês ou $168/ano. Observação: Video Call e Explain My Answer agora são gratuitos para todos os usuários do Duolingo.' WHERE slug='duolingo-max' AND lang='pt';

-- ===== KHANMIGO (GPT-4 -> current GPT) =====
UPDATE tools SET description = 'Khan Academy''s AI tutor built on current GPT models. Uses the Socratic method — guiding students to answers through questions rather than giving them away. Free for teachers; $4/mo or $44/yr for students.' WHERE slug='khanmigo' AND lang='en';
UPDATE tools SET description = 'ИИ-репетитор Khan Academy на современных моделях GPT. Использует сократический метод — подводит ученика к ответу вопросами, а не выдаёт готовое. Бесплатно для учителей; $4/мес или $44/год для учеников.' WHERE slug='khanmigo' AND lang='ru';
UPDATE tools SET description = 'ШІ-репетитор Khan Academy на сучасних моделях GPT. Використовує сократівський метод — підводить учня до відповіді запитаннями, а не дає готове. Безкоштовно для вчителів; $4/міс або $44/рік для учнів.' WHERE slug='khanmigo' AND lang='ua';
UPDATE tools SET description = 'המורה הפרטי ב-AI של Khan Academy מבוסס על מודלי GPT עדכניים. משתמש בשיטה הסוקרטית — מוביל את התלמיד לתשובה דרך שאלות במקום לתת אותה. חינם למורים; $4 לחודש או $44 לשנה לתלמידים.' WHERE slug='khanmigo' AND lang='he';
UPDATE tools SET description = 'Der KI-Tutor der Khan Academy auf Basis aktueller GPT-Modelle. Nutzt die sokratische Methode — führt Lernende per Fragen zur Antwort, statt sie vorzugeben. Kostenlos für Lehrkräfte; 4 $/Monat oder 44 $/Jahr für Schüler.' WHERE slug='khanmigo' AND lang='de';
UPDATE tools SET description = 'El tutor con IA de Khan Academy, basado en modelos GPT actuales. Usa el método socrático: guía al estudiante hacia la respuesta con preguntas en lugar de darla. Gratis para docentes; $4/mes o $44/año para estudiantes.' WHERE slug='khanmigo' AND lang='es';
UPDATE tools SET description = 'Le tuteur IA de la Khan Academy, basé sur les modèles GPT actuels. Il utilise la méthode socratique — guider l''élève vers la réponse par des questions plutôt que la donner. Gratuit pour les enseignants ; 4 $/mois ou 44 $/an pour les élèves.' WHERE slug='khanmigo' AND lang='fr';
UPDATE tools SET description = 'O tutor com IA da Khan Academy, baseado em modelos GPT atuais. Usa o método socrático — guia o aluno até a resposta por meio de perguntas, em vez de entregá-la. Gratuito para professores; $4/mês ou $44/ano para alunos.' WHERE slug='khanmigo' AND lang='pt';
